### ISSUE TITLE
update wallet-core then password error

### ISSUE THREAD

**Issue by JavionHe** [trustwallet/wallet-core#1011]
my app has many people use com.trustwallet.walletcore:walletcore:0.10.0 , their password is String ,and use StoredKey.store() ,
and now i update it to com.trustwallet:wallet-core:2.0.15 , the password request byte[] ,
when my user get the old StoredKey , input password to get storedKey.privateKey , it is error .
It affects many users ,how do i fix it ?

**Comment by hewigovens** [comment]
What’s the name of your app? Just convert your string password to byte array

**Comment by JavionHe** [comment]
@hewigovens sorry , it is my mistake, I use the error function to convert ,
at first I thought the encryption was adjusted, 
thank you for your help.
