### ISSUE TITLE
How to send Binance transaction testnet??

### ISSUE THREAD

**Issue by RajKumar7777** [trustwallet/wallet-core#1021]
```swift
let wallet = HDWallet(mnemonic: "**** ****", passphrase: "")

let privateKey = wallet.getKeyForCoin(coin: .binance)
let publicKey = privateKey.getPublicKeySecp256k1(compressed: true)

let token = BinanceSendOrder.Token.with {
    $0.denom = "BNB" // BNB or BEP2 token symbol
    $0.amount = 4   // Amount, 1 BNB
}

let orderInput = BinanceSendOrder.Input.with {
    //$0.address = CosmosAddress(hrp: .binance, publicKey: publicKey)!.keyHash
    $0.address = SegwitAddress(hrp: .binance, publicKey: publicKey).witnessProgram
    $0.coins = [token]
}

let orderOutput = BinanceSendOrder.Output.with {
    // $0.address = CosmosAddress(string: "bnb1hlly02l6ahjsgxw9wlcswnlwdhg4xhx38yxpd5")!.keyHash
    // $0.address = SegwitAddress(string: "")!.witnessProgram
    $0.address = "tbnb16h65pzx8xjg0xlmuz9lzvkawc6hj82gq9wxulh".data(using: .utf8)!
    $0.coins = [token]
}

let input = BinanceSigningInput.with {
    $0.chainID = "Binance-Chain-Nile" // Testnet Chain id
    $0.accountNumber = 727198         // On chain account number
    $0.sequence = 1                   // Sequence number
    $0.source = 0                     // BEP10 source id
    $0.privateKey = privateKey.data
    $0.memo = ""
    $0.sendOrder = BinanceSendOrder.with {
        $0.inputs = [orderInput]
        $0.outputs = [orderOutput]
    }
}

let output: BinanceSigningOutput = AnySigner.sign(input: input, coin: .binance)
print("output", output.encoded.dataToHexString())

let param = ["sync": output.encoded.dataToHexString(), "body": ""] as [String: Any]
```

When I try to send above param to https://testnet-dex.binance.org/api/v1/broadcast results in failed response as:
```json
{"code":400,"failed_tx_index":0,"message":"broadcast tx 400: invalid hex in a given tx","success_tx_results":[]}
```
  
Please support to solve this issue.

**Comment by hewigovens** [comment]
keyhash was wrong, should not use `SegwitAddress().witnessProgram`, and we don't support testnet address in `AnyAddress` or old `CosmosAddress`, but you can calculate the keyhash by yourself:

`Hash::sha256ripemd(publicKey)`

**Comment by RajKumar7777** [comment]
Then please provide some example to get proper keyhash and send Binance transaction.

**Comment by hewigovens** [comment]
please check https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Blockchains/BinanceChainTests.swift#L28

**Comment by RajKumar7777** [comment]
Thank you for quick response..For mainnet which address should I use SegwitAddress or cosmos address or AnyAddress??

**Comment by hewigovens** [comment]
in latest version, no more `CosmosAddress`, only `AnyAddress`

**Comment by RajKumar7777** [comment]
Ok..Thank you

**Comment by RajKumar7777** [comment]
I have done transaction using mainnet by followed your suggested code..But still am getting same error response as:
{
    code = 400;
    "failed_tx_index" = 0;
    message = "broadcast tx 400: invalid hex in a given tx";
    "success_tx_results" =     (
    );
}
Instead it should say no balance only..

**Comment by hewigovens** [comment]
Make sure you set correct chain id

**Comment by RajKumar7777** [comment]
Using this Binance-Chain-Tigris
I have balance also..But still receiving same error..
Following this link only: https://docs.binance.org/api-reference/dex-api/paths.html#apiv1broadcast
Requesting two parameters that is sync and body.
For sync parameter am using our output.encode.hexString value....What should I use in body parameter?? Any idea??
