### ISSUE TITLE
Send Binance getting invalid hex

### ISSUE THREAD

**Issue by RajKumar7777** [trustwallet/wallet-core#1025]
let privateKey = wallet.getKeyForCoin(coin: .binance)
        let publicKey = privateKey.getPublicKeySecp256k1(compressed: true)
        
        print("BNBPrivateKey", privateKey.data.hexString)
        print("BNBPublivKey", privateKey.getPublicKeySecp256k1(compressed: true))
        print("BNBAddress", wallet.getAddressForCoin(coin: .binance))
        
        let token = BinanceSendOrder.Token.with {
            $0.denom = "BNB" // BNB or BEP2 token symbol
            $0.amount = Int64(0.001)   // Amount, 1 BNB
        }
        
        let orderInput = BinanceSendOrder.Input.with {
            $0.address = AnyAddress(publicKey: publicKey, coin: .binance).data
            $0.coins = [token]
        }

        let orderOutput = BinanceSendOrder.Output.with {
            $0.address = AnyAddress(string: "bnb1vczjtps08p3uquvvw9mnwc6r08urwz6yzu4aym", coin: .binance)!.data
            $0.coins = [token]
        }
        
        let input = BinanceSigningInput.with {
            $0.chainID = "Binance-Chain-Tigris" // Chain id (network id),                 from /v1/node-info api
            $0.accountNumber = 576590              // On chain account / address number,     from /v1/account/<address> api
            $0.sequence = 1                  // Sequence number, plus 1 for new order, from /v1/account/<address> api
            $0.source = 0                     // BEP10 source id
            $0.privateKey = privateKey.data
            $0.memo = ""
            $0.sendOrder = BinanceSendOrder.with {
                $0.inputs = [orderInput]
                $0.outputs = [orderOutput]
            }
        }

        let output: BinanceSigningOutput = AnySigner.sign(input: input, coin: .binance)
        print("output", output.encoded.hexString)

       Above is my code..I need to send bnb from one address to another..Folowing exactly same as your document. But am getting invalid hexString.

       Please help to sort out this issue.

**Comment by hewigovens** [comment]
can you share your address? `$0.amount = Int64(0.001)` is 0?

**Comment by RajKumar7777** [comment]
Hi.. My address: bnb10mfhwu4ktjvzlgyqmkrtdulc303wv2dx34mve7

**Comment by RajKumar7777** [comment]
I need to send 0.001 BNB

**Comment by hewigovens** [comment]
BNB decimals is 8, you need to pass `100000` for 0.001 BNB

**Comment by RajKumar7777** [comment]
Ok..Now am getting a hexString..
When I try to send that hexString for a broadcast API..am receiving error:
{
    code = 400;
    "failed_tx_index" = 0;
    message = "encoding/hex: invalid byte: U+007B '{'";
    "success_tx_results" =     (
    );
}

API: https://dex.binance.org/api/v1/broadcast
Post parameters: let param = ["sync": false, "body": output.encoded.hexString] as [String: Any]

Don't know what am doing wrong here??

**Comment by hewigovens** [comment]
hmm, try sequence = 0?

**Comment by RajKumar7777** [comment]
Still same error response

**Comment by hewigovens** [comment]
from: https://docs.binance.org/api-reference/dex-api/paths.html#apiv1broadcast, `sync` is located in url query, and body should be your raw tx

**Comment by RajKumar7777** [comment]
Can refer some example or any other document??

**Comment by hewigovens** [comment]
sorry, can you join https://t.me/BinanceDEXchange and ask them?

**Comment by RajKumar7777** [comment]
ok

**Comment by hewigovens** [comment]
close now because rpc part is not related with wallet core
