### ISSUE TITLE
Generated hex invalid for broadcast

### ISSUE THREAD

**Issue by ajith9870** [trustwallet/wallet-core#1026]
val privateKey = PrivateKey(priv.data())
                val publicKey = privateKey.getPublicKeySecp256k1(true)

                val signingInput = Binance.SigningInput.newBuilder()
                signingInput.chainId = "Binance-Chain-Tigris"
                signingInput.accountNumber = 576590
                signingInput.sequence = 0

                signingInput.privateKey = ByteString.copyFrom(privateKey.data())

                val token = Binance.SendOrder.Token.newBuilder()
                token.denom = "BNB"
                token.amount = 1

                val input = Binance.SendOrder.Input.newBuilder()
                input.address = ByteString.copyFrom(AnyAddress(publicKey, CoinType.BINANCE).data())
                input.addAllCoins(listOf(token.build()))

                val output =  Binance.SendOrder.Output.newBuilder()
                output.address = ByteString.copyFrom(AnyAddress("bnb1vczjtps08p3uquvvw9mnwc6r08urwz6yzu4aym", CoinType.BINANCE).data())
                output.addAllCoins(listOf(token.build()))

                val sendOrder = Binance.SendOrder.newBuilder()
                sendOrder.addAllInputs(listOf(input.build()))
                sendOrder.addAllOutputs(listOf(output.build()))

                signingInput.sendOrder = sendOrder.build()

                val sign: Binance.SigningOutput = AnySigner.sign(signingInput.build(), CoinType.BINANCE, Binance.SigningOutput.parser())
                val signBytes = sign.encoded.toByteArray()

                Log.d("decode",signBytes.toHexString())

 When I try to send above param to https://dex.binance.org/api/v1/broadcast results in failed response as:

{"code":400,"failed_tx_index":0,"message":"broadcast tx 400: invalid hex in a given tx","success_tx_results":[]}
Please support to solve this issue.

**Comment by hewigovens** [comment]
duplicated with #1025
