### ISSUE TITLE
TWAnySignerSignJSON don't support Filecoin

### ISSUE THREAD

**Issue by wenzhenxiang** [trustwallet/wallet-core#1027]
**Describe the bug**
I use the sample.cpp of the sample folder test Filecoin, when I try TWAnySignerSignJSON function, will feedback the error message. (terminating with uncaught exception of type std::invalid_argument: Invalid address data)

**To Reproduce**
in sample.cpp, just change change TWCoinTypeEthereum to TWCoinTypeFilecoin. and then make build.

**Expected behavior**
can get SignJSON info.

**Screenshots**
![image](https://user-images.githubusercontent.com/18651846/86425155-f7a5f480-bd16-11ea-9685-243b7473d245.png)

**Comment by hewigovens** [comment]
It told you exactly what's wrong, not just coin type, you need to change Filecoin/SigningInput accordingly

**Comment by wenzhenxiang** [comment]
thank you for your reply，do you have plans to support Filecoin can be used directly

**Comment by wenzhenxiang** [comment]
sorry I got it wrong，It's no problem
