### ISSUE TITLE
More than a year has passed, is EOS still not supported?

### ISSUE THREAD

**Issue by cppfuns** [trustwallet/wallet-core#1028]
https://github.com/trustwallet/trust-wallet-ios/issues/803

**Comment by vikmeup** [comment]
EOS is supported on Wallet Core side, feel free to integrate it if you use it.

Closing this PR, as it's not related to this repo.

**Comment by cppfuns** [comment]
> EOS在Wallet Core方面受支持，如果您使用EOS，请随时进行集成。
> 
> 正在关闭此PR，因为它与该回购无关。

Is EOS Dapp supported?

**Comment by dreson4** [comment]
Actually sad seeing this, EOS has no developers for now.
Will integrate EOS myself. Hate having too many wallets for different chains.
