### ISSUE TITLE
Signature verification Failed

### ISSUE THREAD

**Issue by ajith9870** [trustwallet/wallet-core#1030]
**Describe the bug**
val lstValues: List<String> = mnemonic!!.split(" ").map { it -> it.trim() }
                        val end = getPrivateKeyFromMnemonicCode(lstValues)
                        val privatekey = PrivateKey(end,false)
                        val orderJson: String = GsonBuilder().serializeNulls().create().toJson(order)
                        val signature: ByteArray = Signature.signMessage(orderJson.toByteArray(), privatekey)
                        val signed = WCBinanceOrderSignature(
                            Hex.toHexString(signature),
                            Hex.toHexString(privatekey.publicKey.bytes)
                        )
                        wcClient?.approveBnbOrder(id, signed)

Hi i am trying to sign in trade order but signature verification failed. but transfer order and cancel order working with same code. Help to solve this issue..

**Comment by hewigovens** [comment]
could you please submit this issue here: https://github.com/trustwallet/wallet-connect-kotlin ?

**Comment by ajith9870** [comment]
submitted
