### ISSUE TITLE
Deep-link amount is not working on the Android only

### ISSUE THREAD

**Issue by syrohei** [trustwallet/wallet-core#1032]
**Example deep link**
https://link.trustwallet.com/send?coin=714&token_id=SWINGBY-888&address=bnb17ya27znhy4cmqczd2wwanyjwc50twxn5auk85k&amount=128.90605714&memo=69f3b1

**Expected**
the amount should be set 128.90605714

**Actual** 
the amount on the wallet says 12890605714

**Trust wallet version**
Version 1.11.6

**Comment by vikmeup** [comment]
@syrohei I'm gonna close this issue on Wallet Core. 

This issue will be fix in the next release next week. Thanks
