### ISSUE TITLE
Not able to get private key

### ISSUE THREAD

**Issue by ajith9870** [trustwallet/wallet-core#1035]
val wallet = HDWallet(seed1, "")
                val add = wallet.getAddressForCoin(CoinType.BITCOIN)
                val private = wallet.getKeyForCoin(CoinType.BITCOIN)
                val publicKey = private.getPublicKeySecp256k1(true)
                Log.d("addres", add)
                Log.d("addpriv", private.data().toHex())
                Log.d("addpub",publicKey.data().toHex())

Hi I am an Android Developer, By using this sdk i am able to get correct address and public key, but private key returning wrong.

And custom derivation path also not working

                val private = wallet.getKey("M/44H/2H/0H/0/0")

 please help to solve this issue.

**Comment by catenocrypt** [comment]
You state address and public key are ok, and private key is wrong.  I assume address and private key are ok, and public key is wrong, since public key is derived from private.
Maybe for bitcoin public key, you want the non-compressed format -- use with false parameter `private.getPublicKeySecp256k1(false)`.
For derivation path format should be: `m/84'/0'/0'/0/0`; i.e. character backtick for hardened elements.

**Comment by ajith9870** [comment]
invalid_argument: SegwitAddress needs a compressed SECP256k1 public key.

And m/44'/0'/0'/0/0 this format working.. but both private key and address is wrong by setting
  val private = wallet.getKey("m/44'/0'/0'/0/0")

can you please tell me the exact method to get private key for bitcoin by using mnemonics.

**Comment by hewigovens** [comment]
could you please share what's wrong and expected result? you can create a test Mnemonic

**Comment by ajith9870** [comment]
Hi i have created test mnemonics for your reference

val testseed = "exhibit observe else join sail ice agent invite moment note ivory ahead"
                val wallet = HDWallet(testseed, "")
                val private = wallet.getKey("m/44'/0'/0'/0/0")
                val publicKey = private.getPublicKeySecp256k1(true)
                val add = CoinType.BITCOIN.deriveAddressFromPublicKey(publicKey)
                Log.d("addres", add)
                Log.d("addpriv", private.data().toHex())
                Log.d("addpub",publicKey.data().toHex())

The result i got
address - bc1q5uxxxcvpw4uwppycnawm6asxdf2jeqvn77kxy2
privatekey - a7d445d657cd51e608db1b029c1c8b8660de651ce24fa797bf182c08e26af80e
publickey - 028d5e4e714b033c797cac8166de0f582fc99f8ecb84373f0fadd746ddf39d20ef

The result i expected
address - 1GEGgnSEQY41LywyarQwD77JNRt2rZ3JQK
publickey - 028d5e4e714b033c797cac8166de0f582fc99f8ecb84373f0fadd746ddf39d20ef
privatekey - L2qwzLq3NVSKWSCCgEkQpBVvUCLRi3Zj7sRPFVsmMpJngpprq5gB

i have used iancoleman for getting this expected result
https://iancoleman.io/bip39/

**Comment by hewigovens** [comment]
if you look at the publickeys, they are same:
1. `CoinType.deriveAddressFromPublicKey` returns segwit address by default
2. https://iancoleman.io/bip39/ uses WIF for private key, wallet core returns hex string

if you'd like to use legacy 1 bitcoin address, you should use class `BitcoinAddress`

**Comment by catenocrypt** [comment]
Here is sample code and output for the test data.  Address is the expected.  Closing ticket.

```
val wallet = HDWallet("exhibit observe else join sail ice agent invite moment note ivory ahead", "")
val privateKey = wallet.getKey("m/44'/0'/0'/0/0")
showLog("privateKey: \n${privateKey.data().toHexString(false)}")
val publicKey = privateKey.getPublicKeySecp256k1(true)
showLog("publicKey: \n${publicKey.data().toHexString(false)}")
val address = BitcoinAddress(publicKey, 0x00)
showLog("address: \n${address.description()}")
```

```
privateKey:  a7d445d657cd51e608db1b029c1c8b8660de651ce24fa797bf182c08e26af80e
publicKey:  028d5e4e714b033c797cac8166de0f582fc99f8ecb84373f0fadd746ddf39d20ef
address:  1GEGgnSEQY41LywyarQwD77JNRt2rZ3JQK
```

**Comment by RajKumar7777** [comment]
@catenocrypt look for path: m/44'/0'/0'/0/0 - private key is L2qwzLq3NVSKWSCCgEkQpBVvUCLRi3Zj7sRPFVsmMpJngpprq5gB But we receive a7d445d657cd51e608db1b029c1c8b8660de651ce24fa797bf182c08e26af80e

check: https://iancoleman.io/bip39/

**Comment by catenocrypt** [comment]
That is formatting issue; one is hex string (32 bytes), the other is WIF or base58 format.  I would bet that the data is the same.

**Comment by RajKumar7777** [comment]
When I try to sign with that private key am getting wrong value which results in fail transaction.

**Comment by RajKumar7777** [comment]
val wallet = HDWallet("exhibit observe else join sail ice agent invite moment note ivory ahead", "")
val privateKey = wallet.getKey("m/44'/0'/0'/0/0")
showLog("privateKey: \n${privateKey.data().toHexString(false)}")
val publicKey = privateKey.getPublicKeySecp256k1(true)
showLog("publicKey: \n${publicKey.data().toHexString(false)}")
val address = BitcoinAddress(publicKey, 0x00)
showLog("address: \n${address.description()}")

Like using(BitcoinAddress) above how to get data for Litecoin

**Comment by catenocrypt** [comment]
```
    val coin: CoinType = CoinType.LITECOIN
    // Get the default address
    val address = wallet.getAddressForCoin(coin)
```

Please refer to  `https://github.com/trustwallet/wallet-core/blob/master/samples/android/app/src/main/java/com/trust/walletcore/example/MainActivity.kt`.
In your example, you use derivation path `"m/44'/0'/0'/0/0"`, 44 is the purpose (SLIP44), the next number 0 is the coin, 0 is BTC in SLIP44.  Litecoin is 2, btw (https://github.com/satoshilabs/slips/blob/master/slip-0044.md).

**Comment by RajKumar7777** [comment]
Yeah working as expected thanks
