### ISSUE TITLE
[Filecoin] DecodeSignedMessage CBOR error

### ISSUE THREAD

**Issue by togiter** [trustwallet/wallet-core#1036]
**Describe the bug**
When I use IOS signed filecoin transaction to broadcast lotus testnet node, there is an error(`decode unmarshaling t.Message: cbor input had wrong number of fields`). How can I solve this problem

**Screenshots**
ios sign got the result: `82885501a699731e9d4f382d01539a72985a431c75f74b9b55014074462b17b9d28f6579acdf634c1d28af2e89110048004f550445d5a000430013884300c35000405842013dd5cb90d156b356e7d53c8f85600c838b132afdb3896cd67f5ec6e379c658b708346b8d5d418a57125318448b18c6e735a889d80ac4e12e70e14d9303da6ca700`
<img width="1038" alt="截屏2020-07-15 21 06 10" src="https://user-images.githubusercontent.com/18685332/87549500-7704d200-c6e0-11ea-9f23-f4bfae69e8cf.png">

go decode signedMessage got the error :  `decode unmarshaling t.Message: cbor input had wrong number of fields`
<img width="857" alt="截屏2020-07-15 21 08 16" src="https://user-images.githubusercontent.com/18685332/87549860-ed093900-c6e0-11ea-95ad-dc44df5df9a1.png">

And, How can I solve this problem?

**Comment by togiter** [comment]
Maybe missed “from”

**Comment by hewigovens** [comment]
probably lotus has some new updates, will check it soon

**Comment by hewigovens** [comment]
can you share your golang decoding code?

**Comment by togiter** [comment]
`func DecodeSignedMessage(data []byte) (*SignedMessage, error) {
	var msg SignedMessage
	if err := msg.UnmarshalCBOR(bytes.NewReader(data)); err != nil {
		return nil, err
	}

	return &msg, nil
}`

**Comment by togiter** [comment]
Here! [https://github.com/filecoin-project/lotus/blob/master/chain/types/signedmessage.go](url)            `func DecodeSignedMessage(data []byte) (*SignedMessage, error) {
	var msg SignedMessage
	if err := msg.UnmarshalCBOR(bytes.NewReader(data)); err != nil {
		return nil, err
	}

	return &msg, nil
}`

**Comment by togiter** [comment]
Here!  https://github.com/filecoin-project/lotus/blob/master/chain/types/signedmessage.go 
`func DecodeSignedMessage(data []byte) (*SignedMessage, error) {
	var msg SignedMessage
	if err := msg.UnmarshalCBOR(bytes.NewReader(data)); err != nil {
		return nil, err
	}

	return &msg, nil
}`

**Comment by terorie** [comment]
@hewigovens iirc Filecoin changed the message layout since original integration. I'll take a look later today!

**Comment by hewigovens** [comment]
@terorie Thanks 🙏

**Comment by terorie** [comment]
@togiter Here's a version of wallet-core that should fix this issue: https://github.com/terorie/trustwallet-core/tree/terorie/filecoin-changes
If you could verify that it indeed solves your issue, that'd be great!

**Comment by togiter** [comment]
How do I verify with ios Cocoapods Import？

**Comment by hewigovens** [comment]
we will publish a new build later, so you can verify it

**Comment by togiter** [comment]
I got the same error using cocoapods' latest trustwallet core (v2.1.3), haven't you built the latest package yet?

**Comment by hewigovens** [comment]
could you please try 2.1.4?

**Comment by togiter** [comment]
swift sign `tx：82885501a699731e9d4f382d01539a72985a431c75f74b9b55014074462b17b9d28f6579acdf634c1d28af2e89110048004ef2ca9032e000430013884300c3500040584201e73d6e65cbdc680dbb67cede877f5503199554e94a38dd11708f0524fc349f6075f5d0548996937fd240c21c9dc30a56ed8ed04aa25ecec6da135b8bcfb9d8a401`

pod trustcore v2.1.4 got the same error ：unmarshaling t.Message: cbor input had wrong number of fields。

**Comment by hewigovens** [comment]
have you tired to clean and rebuild your swift project? the length of your data(134 bytes) seems shorter than `FilecoinTests.swift` (164 bytes)

**Comment by terorie** [comment]
@togiter The CBOR message you posted decodes to this (https://cbor.me):
```
82                                      # array(2)
   88                                   # array(8)  # <==== This indicates the old version
      55                                # bytes(21)
         01A699731E9D4F382D01539A72985A431C75F74B9B
      55                                # bytes(21)
         014074462B17B9D28F6579ACDF634C1D28AF2E8911
      00                                # unsigned(0)
      48                                # bytes(8)
         004EF2CA9032E000
      43                                # bytes(3)
         001388
      43                                # bytes(3)
         00C350
      00                                # unsigned(0)
      40                                # bytes(0)
   58 42                                # bytes(66)
```

The version field is missing, so I'm 90% sure this is generated by the old version of wallet-core.
The new wallet-core version generates `array(9)`, which is compatible with new Lotus.

**Comment by togiter** [comment]
Yes, now it is. I used to use pod update and pod install = > pod 'trustwalletcore' '~ > 2.1.4'
Get the same error, but remove the pod 'trustwalletcore', '~ > 2.1.4' = > pod install, and then re install it. The build is successful.

**Comment by togiter** [comment]
@hewigovens  New I Got the Same Error `unmarshaling t.Message: cbor input had wrong number of fields`, FileCoin Space Race Network not support yet! , When can you add support Space Race Network?

**Comment by catenocrypt** [comment]
We don't have plans to do it now.  Contribution from FileCoin community is welcome.

**Comment by hewigovens** [comment]
@togiter do you know what has been changed in space race network?

**Comment by togiter** [comment]
The Msg Struct is `
type Message struct {
	Version uint64

	To   address.Address
	From address.Address

	Nonce uint64

	Value abi.TokenAmount

	GasLimit   int64
	GasFeeCap  abi.TokenAmount
	GasPremium abi.TokenAmount

	Method abi.MethodNum
	Params []byte
}
`
A little bit of a change is move ‘gasPrice’ field, Added ‘GasFeeCap’，‘GasPremium’ fields!
https://github.com/filecoin-project/lotus/blob/master/chain/types/message.go

**Comment by hewigovens** [comment]
Thanks for the info, will take a look soon

**Comment by hewigovens** [comment]
@catenocrypt @togiter could you guys please take a look the new changes if any chance, mainnet is going to launch soon (hopefully), I will take a look after web3 stuff on iOS

**Comment by terorie** [comment]
@hewigovens I can file a PR if you want.

**Comment by hewigovens** [comment]
@terorie for sure, thanks 🙏, hope this is the last time change before mainnet

**Comment by togiter** [comment]
Space race network has become stable. When can you add support for `filecoin` message signature!

**Comment by wjd-jax** [comment]
Same problem, field has been changed, hope to be supported as soon as possible

**Comment by hewigovens** [comment]
@terorie is working on this, he will open a pr soon, be patient :)

**Comment by terorie** [comment]
See my PR #1114 for a fix to this, updating wallet-core to the latest Filecoin message ABI.

@togiter @wjd-jax these "+1" comments are not helpful, won't help prioritize and just spam everyone's inbox. Please use the :+1: or :-1: buttons on GitHub to show support instead.
