### ISSUE TITLE
Update Zcash consensus branch ID

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#1038]
**Describe the bug**
ZCash went thought a network upgrade and consensus branch ID being changed: https://zips.z.cash/zip-0250

https://github.com/trustwallet/wallet-core/commit/586da8074c1c0825a84247779696c2139d3120ab#diff-a353960cd4b32e9bc718b45be79b50feR32 - This value needs to be updated, only for zcash

**Comment by hewigovens** [comment]
no need to change wallet core code, we can pass branch id from plan
