### ISSUE TITLE
TWBitcoinScriptHashTypeForCoin return type should be UInt32

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1041]
There is no such enum case for Bitcoin Cash and Bitcoin Gold, it will crash in Swift and be null in Kotlin

Kotlin:

```kotlin
assertNotNull(BitcoinScript.hashTypeForCoin(CoinType.BITCOINCASH)) //  will fail
```

Swift:
![image](https://user-images.githubusercontent.com/360470/87778298-9117ef00-c85d-11ea-81ab-c8bc1c5f700d.png)

**Comment by catenocrypt** [comment]
Will check soon.
