### ISSUE TITLE
Implement Nested Segwit Bitcoin address

### ISSUE THREAD

**Issue by civa** [trustwallet/wallet-core#1046]
When you wanna receive crypto via Trust wallet from most exchanges. It says  invalid address.This is because native segwit is not supported widely yet

It would be better if users can choose between native segwit and nested segwit

Current way i solve is by receiving first in another wallet then move to trust

**Comment by hewigovens** [comment]
Actually wallet core does support create compatible segwit address (aka P2WPKH nested in P2SH), I know some other wallet implemented it using wallet core, it's an UI design choice, eventually everyone will use native format, bitcoin core will change to native segwit address by default:

>   Since version 0.16.0, Bitcoin Core’s built-in wallet has defaulted to generating P2SH-wrapped segwit addresses when users want to receive payments. These addresses are backwards compatible with all widely-used software. Starting with Bitcoin Core 0.20 (expected about a year after 0.18), Bitcoin Core will default to native segwit addresses (bech32) that provide additional fee savings and other benefits. 

https://bitcoin.org/en/release/v0.18.0#graphical-user-interface-gui
