### ISSUE TITLE
How to get legacy address for Litecoin

### ISSUE THREAD

**Issue by RajKumar7777** [trustwallet/wallet-core#1051]
val wallet = HDWallet("exhibit observe else join sail ice agent invite moment note ivory ahead", "")
val privateKey = wallet.getKey("m/44'/0'/0'/0/0")
showLog("privateKey: \n${privateKey.data().toHexString(false)}")
val publicKey = privateKey.getPublicKeySecp256k1(true)
showLog("publicKey: \n${publicKey.data().toHexString(false)}")
val address = BitcoinAddress(publicKey, 0x00)
showLog("address: \n${address.description()}")

Like using above BitcoinAddress class I can get expected legacy address for BTC...Now I need to get for Litecoin
How to get for LTC??
Path: "m/44'/2'/0'/0/0"

**Comment by hewigovens** [comment]
could you please check our existing tests (cpp/swift) first? https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Blockchains/LitecoinTests.swift#L16

**Comment by RajKumar7777** [comment]
I can get the address as expected thanks for the quick response.Now I need to push transaction below is my code.
  
        let utxoTxId = Data(hexString: "xxxxxxxxxxxxxxxxxxxxx")!
        let privateKey = PrivateKey(data: Data(hexString: LtcPrivateKey.data.hexString)!)!
        let address = BitcoinAddress.init(publicKey: LtcPublicKey, prefix: CoinType.litecoin.p2pkhPrefix)?.description ?? ""
        print("litecoin Address", address)

        let satoshiAmount = self.convertToSatoshi(value: Decimal(string: "0.01") ?? 0)
        
        let utxo = BitcoinUnspentTransaction.with {
            $0.outPoint.hash = Data(utxoTxId.reversed()) // reverse of UTXO tx id, Bitcoin internal expects network byte order
            $0.outPoint.index = 0                     // outpoint index of this this UTXO, "vout" field from blockbook utxo api
            $0.outPoint.sequence = UINT32_MAX
            $0.amount = 14450346                             // value of this UTXO, "value" field from blockbook utxo api
            $0.script = BitcoinScript.lockScriptForAddress(address: address, coin: .litecoin).data // Build lock script from address or public key hash
        }

        let input = BitcoinSigningInput.with {
            $0.hashType = BitcoinSigHashType.all.rawValue | BitcoinSigHashType.fork.rawValue
            $0.amount = satoshiAmount
            $0.byteFee = 1
            $0.toAddress = "toAddress"
            $0.changeAddress = address // can be same sender address
            $0.coinType = CoinType.litecoin.rawValue
            $0.utxo = [utxo]
            $0.privateKey = [privateKey.data]
            $0.useMaxAmount = false
        }

        let output: BitcoinSigningOutput = AnySigner.sign(input: input, coin: .litecoin)
        guard output.error.isEmpty else {
            print("output.error", output.error)
            return
        }
        // encoded transaction to broadcast
        print(output.encoded.hexString)

       when I try to push as raw transaction am getting error as :
{
    error = "Error validating transaction: Error running script for input 0 referencing 178014d7370b2ec235988c40786ef1f2d8ed309ba8305986dbf765ffd774166a at 0: Script was NOT verified successfully..";
}
