### ISSUE TITLE
Error in compiling using dockerfile

### ISSUE THREAD

**Issue by FreeManNumOne** [trustwallet/wallet-core#1055]
make[1]: Leaving directory '/wallet-core/build/local/src/protobuf/protobuf-3.9.0/src'
libprotoc 3.9.0
-- The C compiler identification is Clang 9.0.0
-- The CXX compiler identification is Clang 9.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-9 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-9 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:16 (find_library):
  Could not find Protobuf using the following names:

-- Configuring incomplete, errors occurred!
See also "/wallet-core/protobuf-plugin/build/CMakeFiles/CMakeOutput.log".
The command '/bin/bash -o pipefail -c tools/install-dependencies' returned a non-zero code: 1

**Comment by hewigovens** [comment]
Have you run `bootstrap.sh` successfully? protobuf will be downloaded

**Comment by FreeManNumOne** [comment]
I reported an error when I was using the official dockerfile build ！

**Comment by FreeManNumOne** [comment]
> Have you run `bootstrap.sh` successfully? protobuf will be downloaded

I reported an error when I was using the official dockerfile build ！

**Comment by hewigovens** [comment]
sounds like a network issue:
>    The command '/bin/bash -o pipefail -c tools/install-dependencies' returned a non-zero code: 1

that's why I asked if you can run `bootstrap.sh` or `tools/install-dependencies` without problem

**Comment by catenocrypt** [comment]
Could reproduce, will check.

**Comment by FreeManNumOne** [comment]
> sounds like a network issue:
> 
> > The command '/bin/bash -o pipefail -c tools/install-dependencies' returned a non-zero code: 1
> 
> that's why I asked if you can run `bootstrap.sh` or `tools/install-dependencies` without problem

Have you encountered such a problem? I installed docker based on centos

**Comment by hewigovens** [comment]
Yes, it's broken somehow, @catenocrypt is looking at this issue now

**Comment by hewigovens** [comment]
@FreeManNumOne could you please try this workaround? it worked for me

```patch
diff --git a/protobuf-plugin/CMakeLists.txt b/protobuf-plugin/CMakeLists.txt
index bc4bcb29..7375fc0e 100644
--- a/protobuf-plugin/CMakeLists.txt
+++ b/protobuf-plugin/CMakeLists.txt
@@ -13,7 +13,7 @@ endif()
 include_directories(${PREFIX}/include)
 link_directories(${PREFIX}/lib)

-find_library(Protobuf REQUIRED PATH ${PREFIX}/lib/pkgconfig)
+find_package(Protobuf REQUIRED PATH ${PREFIX}/lib/pkgconfig)
```

**Comment by FreeManNumOne** [comment]
> ```diff
> pkgconfig
> ```

I modified the file too much or not
protobuf-plugin/CMakeLists.txt
#find_library(Protobuf REQUIRED PATH ${PREFIX}/lib/pkgconfig)
find_package(Protobuf REQUIRED PATH ${PREFIX}/lib/pkgconfig)

**Comment by FreeManNumOne** [comment]
> @FreeManNumOne could you please try this workaround? it worked for me
> 
> ```diff
> diff --git a/protobuf-plugin/CMakeLists.txt b/protobuf-plugin/CMakeLists.txt
> index bc4bcb29..7375fc0e 100644
> --- a/protobuf-plugin/CMakeLists.txt
> +++ b/protobuf-plugin/CMakeLists.txt
> @@ -13,7 +13,7 @@ endif()
>  include_directories(${PREFIX}/include)
>  link_directories(${PREFIX}/lib)
> 
> -find_library(Protobuf REQUIRED PATH ${PREFIX}/lib/pkgconfig)
> +find_package(Protobuf REQUIRED PATH ${PREFIX}/lib/pkgconfig)
> ```

I modified the file too much or not @hewigovens 
protobuf-plugin/CMakeLists.txt
#find_library(Protobuf REQUIRED PATH ${PREFIX}/lib/pkgconfig)
find_package(Protobuf REQUIRED PATH ${PREFIX}/lib/pkgconfig)

**Comment by hewigovens** [comment]
please try the Docker file in this branch: https://github.com/trustwallet/wallet-core/pull/1056

**Comment by FreeManNumOne** [comment]
> please try the Docker file in this branch: #1056
docker build successful thanks
