### ISSUE TITLE
BTC XPub wallet import (was: Watch-Only Wallets)

### ISSUE THREAD

**Issue by HeroHann** [trustwallet/wallet-core#1058]
Please enable us to import a pub or something along these lines to watch other wallets like our hardware cold-storage from inside Trust-Wallet without the need to switch apps all the time.

**Comment by catenocrypt** [comment]
Importing by public key is possible, this may partly satisfy your use cases.
Importing the private key (extended or not) or recovery phrase is not supported, and it would not be a good idea for security: private key should not leave the hardware wallet in any form.
Another issue is that currently Trust Wallet does not support multiple wallet addresses for the same coin, and there are no plans to support this in the foreseeable future.

See the section  'Method 4: Import via Public Key' section of the guide:
https://community.trustwallet.com/t/how-to-import-a-wallet/87#method-4-import-via-public-key

**Comment by HeroHann** [comment]
Yeah I get for ETH it is possible but why not for lets say BTC / LTC.
Also I don't want to export my private Key from the hardware-wallet, but only the xpub. That way I could see the balance but don't loose security.

**Comment by catenocrypt** [comment]
No current plan for BTC XPub import.
No plans for supporting multiple addresses for a coin.  Closing.
