### ISSUE TITLE
Cant able to archive the project

### ISSUE THREAD

**Issue by RajKumar7777** [trustwallet/wallet-core#1060]
Hi,

I am using your SDK in my project. I can able to run a project but when I try to archive am getting error as could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1103.0.32.62.0_0' Reader: '1100.0.33.8_0')', using libLTO version 'LLVM version 11.0.0.

   Am using Xcode version - 11.1

**Comment by hewigovens** [comment]
I believe it's a bitcode setting issue, we have bitcode enabled in Trust iOS
