### ISSUE TITLE
Support testnet for every supported coin in wallet-core

### ISSUE THREAD

**Issue by gituser** [trustwallet/wallet-core#1061]
**Is your feature request related to a problem? Please describe.**
When developing anything in cryptocurrency field in order to test you must use testnet network instead of the production network to avoid real money losses.
Also automated transaction signing tests might be easier using public testnets.
Also testing new features ONLY available on testnet prior mainnet is a must have feature in wallet-core.

**Describe the solution you'd like**
Support testnet for every coin supported by wallet-core (if there is any).
Testnets mostly differ to main networks by address-format, specific network-id or id used when you sign transaction.

**Describe alternatives you've considered**
Providing clear testnet integration gives better testing abilities for developers using wallet-core, less errors in production environment.
Alternative: every developer should implement testnet support manually and fork wallet-core.

**Testnet support now**
Cosmos (MUON) is already testnet-ready (Gaia) for signing transactions.
Ethereum is supported as well on Ropsten.

**Comment by vikmeup** [comment]
We already covered the signing transactions with real test cases, see tests folder, but you need to always implement on the wallet side integration tests, feel free to use our samples. 

Write tests unit / integration tests before do any testing. 

We do not plan to support test networks.
