### ISSUE TITLE
How do I use TrustWallet on the Java server side?

### ISSUE THREAD

**Issue by dengpan1** [trustwallet/wallet-core#1066]
How do I use TrustWallet on the Java server side?

**Comment by dengpan1** [comment]
Is there a corresponding'.so' file?

**Comment by hewigovens** [comment]
Yes, you can take a look at go example: https://github.com/trustwallet/wallet-core/tree/master/samples/go, build wallet core then load it in Java somehow

**Comment by dengpan1** [comment]
Yes, I found it, but I don't know how to port it to a Java program. using Java calls should require a '.so' file and then call it through JNI

**Comment by hewigovens** [comment]
Yes, that's how we did in android lib: https://github.com/trustwallet/wallet-core/blob/master/CMakeLists.txt#L59, I think you could adjust `CMakeLists.txt` to build the so

**Comment by dengpan1** [comment]
> 是的，这就是我们在android lib中所做的：[https](https://github.com/trustwallet/wallet-core/blob/master/CMakeLists.txt#L59) : [//github.com/trustwallet/wallet-core/blob/master/CMakeLists.txt#L59](https://github.com/trustwallet/wallet-core/blob/master/CMakeLists.txt#L59)，我认为您可以进行调整`CMakeLists.txt`以构建
> 
> > <img alt="" width="48" src="https://repository-images.githubusercontent.com/170738310/987bc300-61ea-11e9-884d-633a624095f6"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> 的GitHub**[trustwallet /钱包核心](https://github.com/trustwallet/wallet-core)**跨平台，跨区块链的钱包库 通过在GitHub上创建一个帐户来为trustwallet / wallet-core开发做出贡献。

can someone compile it for me? I can only use Java, I can't use c++, I have spent a long time still can't use.

**Comment by hewigovens** [comment]
sorry, that's not our main focus, maybe you can try go in backend? we have a small guide here: https://developer.trustwallet.com/wallet-core/integration-guide/server-side
