### ISSUE TITLE
Sign Bitcoin transaction offline with AnySigner and in Golang?

### ISSUE THREAD

**Issue by 3tbraden** [trustwallet/wallet-core#1068]
## AnySigner on the backend and for Bitcoin?
On the [website](https://developer.trustwallet.com/wallet-core/integration-guide/wallet-core-usage#transaction-signing), you mention
>A generic, coin-independent signer also exists (AnySigner), but its usage is recommended **only in browser-based applications**.

Why is that only in browser-based applications?

So I was experimenting with AnySigner to sign transactions offline. When I tried it on Bitcoin with the following code(referencing [here](https://github.com/trustwallet/wallet-core/blob/master/tests/Bitcoin/TWBitcoinSigningTests.cpp#L81)),
````c++
auto input = buildInputP2PKH();
auto inputString = input.SerializeAsString();
auto inputData = TWDataCreateWithBytes((const byte*)inputString.data(), inputString.size());
auto output = TWAnySignerSign(inputData, TWCoinTypeBitcoin);
std::cout << hex(TWDataBytes(output), TWDataBytes(output) + TWDataSize(output))<< std::endl;
````
I got output:
````
0ae10108021a96010a220a20fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f10ffffffff0f1a6a47304402202819d70d4bec472113a1392cadc0860a7a1b34ea0869abb4bdce3290c3aba086022023eff75f410ad19cdbe6c6a017362bd554ce5fb906c13534ddc306be117ad30a012103c9f4836b9a4f77fc0d81f7bcb01b7f1b35916864b9476c241ce9fc198bd25432222108b0ff8ea001121976a914769bdff96a02f9135a1d19b749db6a78fe07dc9088ac222108aefbf38901121976a9149e089b6889e032d46e3b915a3392edfd616fb1c488ac12e1010100000001fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f000000006a47304402202819d70d4bec472113a1392cadc0860a7a1b34ea0869abb4bdce3290c3aba086022023eff75f410ad19cdbe6c6a017362bd554ce5fb906c13534ddc306be117ad30a012103c9f4836b9a4f77fc0d81f7bcb01b7f1b35916864b9476c241ce9fc198bd25432ffffffff02b0bf0314000000001976a914769bdff96a02f9135a1d19b749db6a78fe07dc9088acaefd3c11000000001976a9149e089b6889e032d46e3b915a3392edfd616fb1c488ac000000001a4034333064363230356465386431396131363330333032626634646438346265396533373638613666366265623164623464643232346336366563666431626431
````
which is the expected output
````
0100000001fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f000000006a47304402202819d70d4bec472113a1392cadc0860a7a1b34ea0869abb4bdce3290c3aba086022023eff75f410ad19cdbe6c6a017362bd554ce5fb906c13534ddc306be117ad30a012103c9f4836b9a4f77fc0d81f7bcb01b7f1b35916864b9476c241ce9fc198bd25432ffffffff02b0bf0314000000001976a914769bdff96a02f9135a1d19b749db6a78fe07dc9088acaefd3c11000000001976a9149e089b6889e032d46e3b915a3392edfd616fb1c488ac00000000
````
with some weird header and trailing bytes.\
Is this the correct way to use the function and the expected output?

## AnySigner in Go?
And following up on #889, is there golang example on how to use AnySigner?

I am trying to write some golang code to use AnySigner with cgo(referencing [here](https://github.com/trustwallet/wallet-core/blob/master/samples/go/main.go)).
````go
// signingInput constructed from Bitcoin.pb.go
inputBytes, err := proto.Marshal(&signingInput)
if err != nil {
    log.Fatal(err)
}
inputData := TWDataCreateWithGoBytes(inputBytes)
signed := C.TWAnySignerSign(inputData, C.TWCoinTypeBitcoin)
````
However in the above code, while `inputBytes` is some long bytes, `inputData` somehow gets reduced to just a few bytes, and subsequently the `signed` output is also short and doesn't look right. Any idea on that?

Sorry for this lengthy issue with several questions at once. Would really appreciate any advice.(If deem fit and worth it maybe I can split this into several separate issues.)

**Comment by catenocrypt** [comment]
> Why is that only in browser-based applications?

AnySigner is not type safe, conversion to-and-from blockchain-specific structures is error prone.  That's the drawback, and that is why in typed-languages (Go, Swift, Kotlin, C++) the typed sign() methods are recommended.

**Comment by catenocrypt** [comment]
> Is this the correct way to use the function and the expected output?

An additional step is missing:
- any signer expects the serialized version of TW::Bitcoin::Proto::SigningInput
- also the return value is the serialized version of a TW::Bitcoin::Proto::SigningOutput, which contains the encoded transaction as well.  So you need to convert the result to this structure.  This is missing.  The `encoded` field of SigningOutput contains the encoded TX.
 
See for example below test (this is for Filcoin, but analogue):
https://github.com/trustwallet/wallet-core/blob/master/tests/Filecoin/TWAnySignerTests.cpp

```
auto outputData = TWAnySignerSign(inputData, TWCoinTypeFilecoin);

    ASSERT_EQ(hex(TWDataBytes(outputData), TWDataBytes(outputData) + TWDataSize(outputData)),
              "0aa401"
              "828900583103a33d476e13eb8bde5d21becf2b86dd60642f0297cc6a5b914de8 ...

    Proto::SigningOutput output;
    output.ParseFromArray(TWDataBytes(outputData), static_cast<int>(TWDataSize(outputData)));

    ASSERT_EQ(hex(output.encoded()),
              "828900583103a33d476e13eb8bde5d21becf2b86dd60642f0297cc6a5b914de8 ...
```

**Comment by catenocrypt** [comment]
> And following up on #889, is there golang example on how to use AnySigner?

There is a small Go integration sample, but unfortunately it contains only wallet handling and key handling operations (https://github.com/trustwallet/wallet-core/tree/master/samples/go, it's also documented here: https://developer.trustwallet.com/wallet-core/integration-guide/server-side).

**Comment by 3tbraden** [comment]
@catenocrypt thank you for the very prompt response, very useful info! Any idea about why the go code is not working? I am thinking `TWDataCreateWithGoBytes(inputBytes)` is not generating `TWData` correctly in go.

**Comment by hewigovens** [comment]
`TWData` and `TWString` are `const void` pointers in C, to get correct length you need to use method like `TWDataSize` or convert it back to go types with method `TWDataGoBytes`

**Comment by 3tbraden** [comment]
@hewigovens right, so I updated the code to print the bytes with `TWDataBytes` and the input `TWData` looks alright.
````go
inputData := TWDataCreateWithGoBytes(inputBytes)
defer C.TWDataDelete(inputData)
fmt.Printf("inputData: %x\n", TWDataGoBytes(inputData))
````
> inputData: 080110c0fc82aa02180122223142703955316f6756334131...

But after `C.TWAnySignerSign()` the output is drastically reduced in length and the unmarshalled `SigningInput` does not look right.
````go
output:= C.TWAnySignerSign(inputData, C.TWCoinTypeBitcoin)
fmt.Printf("output raw: %x\n", output)
fmt.Printf("output twdata: %x\n, TWDataGoBytes(output))
var signedOutput pb.SigningOutput
err = proto.Unmarshal(TWDataGoBytes(signed), &signedOutput)
if err != nil {
	log.Fatal(err)
}
fmt.Printf("signing output: %v\n, signedOutput)
````
> output raw: f504120
> output twdata: 22174d697373696e6720696e70757473206f72205554584f73
> signing output: {{{} [] [] 0xc00012c888} 0 [] <nil> []  Missing inputs or UTXOs}

**Comment by hewigovens** [comment]
I think your code is correct, `SigningOutput` has an `error` field to tell if something goes wrong: the error was: "Missing inputs or UTXOs", so it might miss something when you built the signing input

**Comment by 3tbraden** [comment]
right, so I was missing the `SigningInput.Plan` where I have to put in the utxos as well. It's working now. Thanks for the help.

**Comment by hewigovens** [comment]
would you mind to share your go code? so we can update our go sample in case someone else needs it.

**Comment by 3tbraden** [comment]
Of course. Feel free to use/reference/amend the code below. And please let me know if there's anything wrong/missing from the implementation.
````go
privKeyBytes, err := hex.DecodeString("945f423798858e24aa1ab490648013db63ad1f539ebbb8cb1399edd1d0b59716")
if err != nil {
	log.Fatal(err)
}
utxoHash, err := hex.DecodeString("fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f")
if err != nil {
	log.Fatal(err)
}
btcutilAddr, err := btcutil.DecodeAddress("bc1qw29x4hrt6tahz4jvuhzrq6y5el3spqt499zuay", &chaincfg.MainNetParams)
if err != nil {
	log.Fatal(err)
}
p2pkh, err := txscript.PayToAddrScript(btcutilAddr)
if err != nil {
	log.Fatal(err)
}
utxo := pb.UnspentTransaction{
	OutPoint: &pb.OutPoint{
		Hash:     utxoHash,
		Index:    0,
		Sequence: 4294967295,
	},
	Amount: 625000000,
	Script: p2pkh,
}
plan := pb.TransactionPlan{
	Amount: 625000000,
	Utxos:  []*pb.UnspentTransaction{&utxo},
}
signingInput := pb.SigningInput{
	HashType:      1, // 1 for TWBitcoinSigHashTypeAll
	Amount:        625000000,
	ByteFee:       1,
	ToAddress:     "1Bp9U1ogV3A14FMvKbRJms7ctyso4Z4Tcx",
	ChangeAddress: "1FQc5LdgGHMHEN9nwkjmz6tWkxhPpxBvBU",
	PrivateKey:    [][]byte{privKeyBytes},
	Utxo:          []*pb.UnspentTransaction{&utxo},
	CoinType:      0,
	Plan:          &plan,
}
inputBytes, err := proto.Marshal(&signingInput)
if err != nil {
	log.Fatal(err)
}
inputData := TWDataCreateWithGoBytes(inputBytes)
defer C.TWDataDelete(inputData)
outputData := C.TWAnySignerSign(inputData, C.TWCoinTypeBitcoin)
var output pb.SigningOutput
err = proto.Unmarshal(TWDataGoBytes(outputData), &output)
if err != nil {
	log.Fatal(err)
}
fmt.Printf("<== bitcoin signed output: %x\n", output.Encoded)
````
The utxo in the code is not valid though, it's with made-up data, but anyway it signs with the correct data format.

**Comment by hewigovens** [comment]
go sample code updated: https://github.com/trustwallet/wallet-core/pull/1070, we have api to get lock script from an address
