### ISSUE TITLE
[Polkadot] Extrinsic with era signature seems not valid

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1079]
It's rejected by network (same as @polkadot/api 1.26.1)

**Comment by vikmeup** [comment]
@hewigovens what's needed for this?

**Comment by hewigovens** [comment]
I can check this later if no other tasks, need to cross check with polkadot.js to see what's wrong

**Comment by vikmeup** [comment]
How to reproduce this issue? Or how relevant is it to the transfers?
