### ISSUE TITLE
Missing inputs for LTC segwit address 

### ISSUE THREAD

**Issue by AjithNoah** [trustwallet/wallet-core#1080]
Hi, when i send small amount like 0.001 hex generated but when i send my full balance(0.01999326) hex not generated.. please help to solve this issue. But when i use legacy with custom path everything works fine

        var cointype: CoinType?
        var bytefee =1
        cointype = CoinType.LITECOIN

        val wallet = HDWallet(mnemonic, "")
        val private = wallet.getKeyForCoin(cointype)
        val address = wallet.getAddressForCoin(cointype)

        val toAddress = ltc1qds5dg0hznar5uxsq0xncqvjs8atwv3gseu82g3
        val changeAddress = ltc1qxsjdvzl7h89ygjvgaql773dzusyky70pw25sk9
        val script = BitcoinScript.lockScriptForAddress(address, cointype).data()

        val input = Bitcoin.SigningInput.newBuilder().apply {
            this.amount = myvalue
            this.hashType = BitcoinSigHashType.ALL.value()
            this.toAddress = toAddress
            this.changeAddress = changeAddress
            this.byteFee = bytefee
            this.coinType = cointype.value()
        }

        if (utoxlist.size > 0){
            for (i in 0..utoxlist.size.minus(1)){

                val txid = utoxlist[i].txid
                val vout = utoxlist[i].output_no
                val value = utoxlist[i].value!!.toDouble()
                val satoshi = value*100000000
                val sat = satoshi.toLong()

                val utox = Numeric.hexStringToByteArray(txid)
                val utxoTxId = utox

                val outPoint = Bitcoin.OutPoint.newBuilder().apply {
                    this.hash = ByteString.copyFrom(utxoTxId.reversedArray())
                    this.sequence = Long.MAX_VALUE.toInt()
                    this.index = vout!!
                }.build()
                val utxo = Bitcoin.UnspentTransaction.newBuilder().apply {
                    this.amount = sat
                    this.outPoint = outPoint
                    this.script = ByteString.copyFrom(script)
                }.build()

                input.addUtxo(utxo)
                input.addPrivateKey(ByteString.copyFrom(private.data()))

            }

            val output = AnySigner.sign(input.build(), cointype, Bitcoin.SigningOutput.parser())
            val signedTransaction = output.encoded?.toByteArray()
            val hex = signedTransaction?.toHexString(false)

**Comment by hewigovens** [comment]
try to set `useMaxAmount` flag in `SigningInput`
