### ISSUE TITLE
How to view the amount of currency in a wallet?

### ISSUE THREAD

**Issue by GiraffeKey** [trustwallet/wallet-core#1087]
How would you display to a user the total amount of bitcoin in their wallet?

**Comment by catenocrypt** [comment]
A node can return the balance of an address.  Wallet-core does not deal with communication with a node.  A Bitcoin node can be addressed through its RPC interface, and it can be asked for the balance of a Bitcoin address, or the balance across a number of public addresses.  Wallet-core is not involved in this part, only to the extent to derive the Bitcoin address from the wallet mnemonic.
