### ISSUE TITLE
 Unable to find the requested Boost libraries. How to do？

### ISSUE THREAD

**Issue by a2012s** [trustwallet/wallet-core#1088]
Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:39 (find_package)
  CMakeLists.txt:45 (find_host_package)

**Comment by hewigovens** [comment]
Try install it with package manager

**Comment by catenocrypt** [comment]
Alternatively you can specify boost location using -DBOOST_ROOT, but it is much cleaner if it is installed in standard location.

```shell
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=~/prog/boost_1_66_0/[boost]
```
