### ISSUE TITLE
Checksum APK Android published

### ISSUE THREAD

**Issue by jwcelyo** [trustwallet/wallet-core#1089]
**Is your feature request related to a problem? Please describe.**

Although the wallet trust is fully open source, I still don't feel safe using the apk on android.  we need to make a checksum of the apk and the same apk is published here

**Describe the solution you'd like**

generate checksum before publishing and upload the apk on github too

**Describe alternatives you've considered**

**Additional context**

**Comment by vikmeup** [comment]
Trust Wallet is not open source, only core library as Wallet Core. There is no plans to support this yet, but this might change in the future.

**Comment by hewigovens** [comment]
probably we could add checksum file to https://trustwallet.com/dl/apk as well? @madcake thought?

**Comment by jwcelyo** [comment]
In fact, the checksum file is very important, so that we will be able to validate if it is even published on Google Play.  So through reverse engineering we can audit as little as possible within the code.

**Comment by hewigovens** [comment]
close this for now
