### ISSUE TITLE
[Android] iOS KeyStore equivalent

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1093]
Make StoredKey easier to use on Android

**Comment by willmeet** [comment]
do you lost your keystore of your android app ? 

Then the simple solution >
http://www.technologymanias.com/2020/10/missing-or-lost-keystore-of-your.html

**Comment by ArmK888** [comment]
Can I store my wallets with StoredKey now, or is it not possible at the current time?

**Comment by hewigovens** [comment]
close this for now
