### ISSUE TITLE
[Android] Add missing blockchain test

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1095]
Android doesn't have address / signer tests for some blockchain (comparing to Swift)

**Comment by vikmeup** [comment]
@catenocrypt is this issue fixed? or there is more tests to cover on Android?

**Comment by catenocrypt** [comment]
Only a small portion is done so far.

**Comment by vikmeup** [comment]
> Only a small portion is done so far.

would you be able to describe the scope for tests and current coverage? to better understand that's needed to be done

**Comment by catenocrypt** [comment]
There has been some additions, but there is still some missing test on android side.  I'm closing this now, as low prio, reopening later if appropriate.
