### ISSUE TITLE
Add Flow blockchain support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1096]
- https://www.onflow.org/
- https://github.com/onflow/flow/blob/master/docs/accounts-and-keys.md#keys
- https://github.com/onflow/flow/blob/master/docs/accounts-and-keys.md#signing-a-transaction

**Comment by hewigovens** [comment]
@lmcmz might work on this

**Comment by catenocrypt** [comment]
Note: BUSD is being introduced to Flow chain as well.

**Comment by catenocrypt** [comment]
Reopening

**Comment by catenocrypt** [comment]
Integrating Flow into Trust Wallet blockchain scheme has several challenges:

* Account creation.  Flow does not use key derivation, and accounts have to be created using a transaction.  What account to show after a new wallet creation or import?  Should Trust Wallet create accounts?  When?  Who pays the small fee?

* Account/Address.  In flow an account can have multiple keys associated, and the account ID is just an ID, the keys are stored separately.  What should Trust Wallet show as address?  The account ID?  How to obtain the same address after a passphrase-reimport?

* Crypto Primitives.  Flow uses ECDSA SECP256K1 and/or P-256.  To check if ECDSA P-256 is supported.

* Practical considerations.  No wallet implementation is available, makes it harder to test interoperability.  No easy way to get hold of some FLOW for testing.

* Implementation.  What data to store in the Address object?  The account ID only?  Or also list of keys (with metadata)?  We cannot generate an Address from a public key (derived from a derivation path).

**Comment by catenocrypt** [comment]
Putting on hold, waiting some time until Flow resources are more available (wallet, exchange, etc.)

See PR #1255 , branch ar/flow0

**Comment by Superfuture** [comment]
Upvote!
