### ISSUE TITLE
[Android]empty/missing DT_HASH in "libTrustWalletCore.so" (built with --hash-style=gnu?)

### ISSUE THREAD

**Issue by codeFarmL** [trustwallet/wallet-core#1100]
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: empty/missing DT_HASH in "libTrustWalletCore.so" (built with --hash-style=gnu?)

**Comment by hewigovens** [comment]
how did you build the lib? can you share your sample project?

**Comment by SamaKaur** [comment]
Hi, @codeFarmL  were you able to resolve this issue? As I am getting the same issue in my project. Can I get more details on this to fix please.
