### ISSUE TITLE
Bitcoin does not support not setting the change address

### ISSUE THREAD

**Issue by wjd-jax** [trustwallet/wallet-core#1108]
After testing, it was found that the minimum amount of change was 79. I don't know whether I can support the situation where the change is 0, such as the situation of transferring all bitcoin out of a certain account

**Comment by hewigovens** [comment]
Can you share your code? don't forget to set `use_max_amount` in `SigningInput`; or you can construct your own `TransactionPlan` to set change = 0

**Comment by wjd-jax** [comment]
I saw this field, thank you for your reply, it solved my problem, I will close this problem
