### ISSUE TITLE
[WIP] Define information for each coin

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/wallet-core#111]
1) chain ID
2) Is this only coin, or there is also support for tokens on the blockchain?
3) default network fee - in satoshis.
4) Native Token name, aka `ERC20`, `TRC10`, or Default to `symbol` + `20`

**Comment by vikmeup** [comment]
@alejandro-isaza, @hewigovens what's the best way to configure chain ID? it could be `Int` or `String`

Would it make sense to have such struct:
```swift
struct ChainID {
     struct Ethereum {
        static let mainnet = 1
     }
     struct Wanchain {
        static let mainnet = 1
     }
     struct Binance {
        static let mainnet = "Binance-Chain"
     }
    struct Stellar {
         static let mainnet = "Stellar-Network"
         static let kin = "Kin-Chain"
    }
}
```

@alejandro-isaza C++ wise, what's the easier to make this work and generate code for it?

**Comment by hewigovens** [comment]
how about just do: 
```swift
extension CoinType {
    var chainId: Int 
    var chainIdString: String
}
```

**Comment by alejandro-isaza** [comment]
We can also just use string for everything. The alternative is to use `std::variant<int, std::string>` but we can expose that on the interface.

**Comment by vikmeup** [comment]
Better design to avoid hardcoding and getting chain ID from the network itself.
