### ISSUE TITLE
Add timelock support

### ISSUE THREAD

**Issue by roy1210** [trustwallet/wallet-core#1110]
**Is your feature request related to a problem? Please describe.**
It is very nice if we can run `timeLock`, `timeUnlock`, and `timeRelock` function via walletConnect.

https://github.com/binance-chain/javascript-sdk/blob/master/docs/api-docs/classes/tokenmanagement.md#timelock
https://docs.binance.org/timelock.html

**Describe the solution you'd like**
Maybe add `timelock_order`, `timerelock_order`, and `timeunlock_order` in here.

https://github.com/trustwallet/wallet-core/blob/61c55bfa7f49ec9c916d54aad6b4cd0c32051613/src/proto/Binance.proto#L173

**Comment by hewigovens** [comment]
when does user want to lock a token? we could add them

**Comment by roy1210** [comment]
Hi @hewigovens, 

Thank you for your reply!
Currently, I'm working on my project in which one of the main features is to let user process `timeLock`, `timeRelock`, and `timeUnlock` for their BEP2 token. It is very helpful if TW will support those 3 order ASAP. 

Thank you very much!!

**Comment by roy1210** [comment]
Idea is something like this.
https://gist.github.com/roy1210/fce0ef2a56b82fb0c3e6ef42b4adf0d8#file-gistfile1-txt-L26

**Comment by roy1210** [comment]
Hi @hewigovens 
Any update for this request? 
Please help to advise ETA for adding `timelock`, `timeunlock`, and `timerelock` order. Thank you!!

**Comment by hewigovens** [comment]
@catenocrypt will work on this in a few days

**Comment by catenocrypt** [comment]
@roy1210 , implementation is available, I'd appreciate if you could test it. Let me know if you need instructions for testing from a branch.
PR: #1118 
branch: https://github.com/trustwallet/wallet-core/tree/ar/bnb-timelock

**Comment by roy1210** [comment]
Hi @catenocrypt 
Thank you! Actually, I'm using `@trustwallet/walletconnect": "0.0.12` to communicating between walletAddress and Binance chain. I opened issue at this repo due to [this](https://developer.trustwallet.com/wallet-connect/dapp).
So is it possible to just send the `tx order` by `trustSignTransaction(NETWORK_ID, tx)` function from frontend(react) side?

Idea is something like this.
https://gist.github.com/roy1210/fce0ef2a56b82fb0c3e6ef42b4adf0d8#file-gistfile1-txt-L26


![image](https://user-images.githubusercontent.com/42575132/94577079-b5099f00-02a8-11eb-8a48-15478926b6da.png)

**Comment by roy1210** [comment]
hmm... perhaps merge those timelock orders to master branch maybe?

**Comment by catenocrypt** [comment]
> @catenocrypt   hmm... perhaps merge those timelock orders to master branch maybe?

Merged.

**Comment by roy1210** [comment]
@catenocrypt 

Will get `msg should not be nil` error. Do you have any idea??

**Comment by roy1210** [comment]
<img width="894" alt="Screenshot 2020-09-30 at 12 47 58 PM" src="https://user-images.githubusercontent.com/42575132/94644240-529db680-031b-11eb-992b-14abaa11861b.png">

**Comment by roy1210** [comment]
![image](https://user-images.githubusercontent.com/42575132/94644359-aa3c2200-031b-11eb-83cb-13e2432288c6.jpeg)

**Comment by roy1210** [comment]
@catenocrypt 
<img width="914" alt="Screenshot 2020-09-30 at 6 45 16 PM" src="https://user-images.githubusercontent.com/42575132/94676017-39156280-034d-11eb-8180-817d8da1b79c.png">
![image](https://user-images.githubusercontent.com/42575132/94676113-69f59780-034d-11eb-9428-8f003a3b75c4.png)

**Comment by catenocrypt** [comment]
We will release a new version, you need to wait for that to test.

**Comment by roy1210** [comment]
Hi @catenocrypt 
I think `amount` should be `Coin[]` type instead of int64. So we can choose currency too.
https://github.com/trustwallet/wallet-core/blob/master/src/proto/Binance.proto#L167

so like:
```
amount: [{
  "denom": "BNB",
  "amount": 10000
}]
```

Ref:
https://github.com/binance-chain/javascript-sdk/blob/master/docs/api-docs/classes/tokenmanagement.md#timelock

https://github.com/binance-chain/javascript-sdk/blob/aa1947b696f984aa931f5f029e4a439c45d5e853/src/types/msg/send.ts#L8

https://github.com/binance-chain/javascript-sdk/blob/aa1947b696f984aa931f5f029e4a439c45d5e853/__tests__/transaction.test.ts#L242

https://github.com/binance-chain/javascript-sdk/blob/ac5a108a81b55ca0cd034b5ca352fc1c22093aa1/__tests__/token.test.ts#L42

**Comment by catenocrypt** [comment]
Thanks for the feedback, corrected with #1124 .

**Comment by roy1210** [comment]
> We will release a new version, you need to wait for that to test.

Hi can I try again now?

**Comment by catenocrypt** [comment]
You can try with latest update, 2.2.12

**Comment by roy1210** [comment]
Thank you very much!
Would you mind to give a sample code for timelock with 0.01BNB?

**Comment by roy1210** [comment]
Hi @catenocrypt 
I tried but Error returns `msg should not be nil`.
Could you advise if I missing somewhere??

![image](https://user-images.githubusercontent.com/42575132/94768780-eedec080-03e2-11eb-9301-6da4a236d2d9.png)

**Comment by hewigovens** [comment]
@roy1210 the app needs to update to latest wallet core to test

**Comment by roy1210** [comment]
@hewigovens 


Actually, I'm using @trustwallet/walletconnect": "0.0.12 to communicating between walletAddress and Binance chain. I opened issue at this repo due to [this link](https://developer.trustwallet.com/wallet-connect/dapp) mentioned.
So is it possible to just send the tx by trustSignTransaction(NETWORK_ID, tx) function from frontend(react) side?

**Comment by catenocrypt** [comment]
Then I'm confused if wallet-core is used at all...  @hewigovens ?
BTW, @trustwallet/walletconnect has latest version `0.1.37`, `0.0.12` is more than a year old!
https://www.npmjs.com/package/@trustwallet/walletconnect/v/0.1.37

**Comment by hewigovens** [comment]
@catenocrypt  @roy1210, Yes, should be supported. to support new timelock orders, we have to update both both wallet core and app, basically the flow is: dapp -> wallet connect -> app -> wallet core,

@trustwallet/walletconnect was depreciated, we have an issue to remove it from developer docs: https://github.com/trustwallet/developer/issues/146

**Comment by roy1210** [comment]
@hewigovens 
Thank you for your explain.
I'm using react in my app and able to connect wallet via scanning QR code from TW.

If you don't suggest to use @trustwallet/walletconnect anymore, would you give some example to achieve timelock order? 
Maybe example repository is ideal.

**Comment by hewigovens** [comment]
if you take a look at the code: https://github.com/trustwallet/web-core/blob/master/packages/walletconnect/src/index.ts, only two small helpers; we don't have examples, you can play around binance js sdk to figure out how to set those values

**Comment by roy1210** [comment]
@hewigovens 
Ok, I'm using @walletconnect/core instead of @trustwallet/walletconnect.
However, I'm facing this error when app runs. 
I'm not sure why this error happen even I didn't use `qrcodeModal` in my app. (Just showing QR code without modal)

Code:
https://gist.github.com/roy1210/4aa87a3fe88fab069a4096e408402f5f#file-gistfile1-txt-L25

```
  const walletConnect = async () => {
    const walletConnector = (window.mywallet = new WalletConnect({
      bridge: "https://bridge.walletconnect.org", // Required
      // Memo: Error no matter apply qrcodeModal or remove it
      // qrcodeModal: QRCodeModal,
    }));
```
![image](https://user-images.githubusercontent.com/42575132/94792257-4a24a900-040b-11eb-8ee8-ff5e84e1d5a4.png)

**Comment by hewigovens** [comment]
You'd better to join wallet connect channel for help https://t.me/walletconnect

**Comment by roy1210** [comment]
@hewigovens 
Noted.
> @trustwallet/walletconnect was depreciated, we have an issue to remove it from developer docs: trustwallet/developer#146

Please update the dev docs with using @walletconnect/core instead of @trustwallet/walletconnect since walletconnect was depreciated. May I know ETA for docs update? Kindly let me know once done!

**Comment by roy1210** [comment]
Hi @hewigovens 

Kindly please help to clarify, I understand "@trustwallet/walletconnect" was deprecated. But is it still possible to run 'timelock' order with "@trustwallet/walletconnect" ?? Or is it impossible??

**Comment by roy1210** [comment]
Hi @hewigovens 
Would you mind replying my above question? Thank you!

**Comment by hewigovens** [comment]
it is possible to sign `timelock` order through wallet connect after wallet core new build integrated into iOS/Android app, we will release them soon

**Comment by roy1210** [comment]
Hi @hewigovens 

Thank you very much for your reply!! That's great !! 
(It's very difficult to implement `import Connector from "@walletconnect/core` by myself since there is no docs available yet...)

I think maybe `@trustwallet/walletconnect` is required to update `@walletconnect/core` to the latest version instead of `^1.0.0-beta.32`to accept the timelock order.
https://github.com/trustwallet/web-core/blob/master/packages/walletconnect/package.json#L49 

Let me know once `@trustwallet/walletconnect` release new version.

**Comment by roy1210** [comment]
Hi @hewigovens 
>it is possible to sign timelock order through wallet connect after wallet core new build integrated into iOS/Android app, we will release them soon

I'd like to confirm that should below code will works once release new version? 
My React app is using `@trustwallet/walletconnect": "0.0.12`.


```
  if (context.wallet.walletconnect) {
      Binance.getAccount(context.wallet.address)
        .then((response) => {
          const account = response.result;
          console.log("AccountInfo:", account);
          const tx = (window.tx = {
            accountNumber: account.account_number.toString(),
            chainId: CHAIN_ID,
            sequence: account.sequence.toString(),
          });

          if (mode === Mode.TIMELOCK) {
            const addr = base64js.fromByteArray(
              crypto.decodeAddress(context.wallet.address)
            );
            const description = lockDescription;
            const timelockTimestamp = Number(moment(lockTime).format("X"));
            const amount = [
                denom: CoinSymbol.BNB,
                amount: (parseFloat(lockAmount) * Math.pow(10, 8)).toString(),
              },
            ];
            tx.time_lock_order = {
              from_address: addr,
              description: description,
              amount: amount,
              lock_time: timelockTimestamp,
            };
          } else {
            throw new Error("invalid mode");
          }
          console.log("tx", tx);
          window.mywall = context.wallet.walletconnect;
          context.wallet.walletconnect
            .trustSignTransaction(NETWORK_ID, tx)
            .then((result) => {
              // Returns transaction signed in json or encoded format
              window.result = result;
              console.log("Successfully signed timeLock msg:", result);
              binance.bnbClient
                //Memo: Get error
                .sendRawTransaction(result, true)
                .then((response) => {
                  console.log("Response", response);
                  setSending(false);
                  setVisible(false);
                  getBalances();
                })
                .catch((error) => {
                  message.error(error.message);
                  setSending(false);
                  setVisible(false);
                  console.error(error);
                });
            })
```

**Comment by roy1210** [comment]
Hi @hewigovens 
```
 .trustSignTransaction(NETWORK_ID, tx)
            .then((result) => {
              // Returns transaction signed in json or encoded format
              window.result = result;
              console.log("Successfully signed timeLock msg:", result);
```
May I know how to decode (convert to string) the `result` return from `.trustSignTransaction` function? ( I guess it is HEX format...)
I want to check what this `result` is telling. Probably it is an error message or missing `msg` that's why didn't go through `binance.bnbClient.sendRawTransaction(result, true)`

Result:
72f0625dee0a00126a0a26eb5ae9872103e42f00e97b1cd4c674dab66c084bcd983f4c941dc4d3597bc3671f15bb3402a51240b180b7818d730ca80c4e1b67487c279182bd3f8847f8afca5a57105e4532a72a51d7b44fe4cd4f3ff72ff280a68f702ca45c71daf80ef1e5247c7cd69effb2ea

**Comment by roy1210** [comment]
Hi @hewigovens 
Sorry again, Could you update above my question?

**Comment by hewigovens** [comment]
@roy1210 we have updated the [doc](https://github.com/trustwallet/developer/blob/5088fdf112a98258a5c83eb92b545a17ca3b6584/wallet-connect/dapp.md), pr is https://github.com/trustwallet/developer/pull/147, I think you can try `timeLock` with  [iOS beta](https://trustwallet.com/beta)

**Comment by roy1210** [comment]
@hewigovens 
Thank you very much.
May I know recommended version for "@walletconnect/client"?

**Comment by hewigovens** [comment]
I tried latest (1.3.0)

**Comment by roy1210** [comment]
Hi @hewigovens 

```
```

**Comment by roy1210** [comment]
@hewigovens 
早上好！我會講中文。也許私聊問問題比較好？這是我的微信，隨時可以找到我😄
Roy_Wu1210

**Comment by roy1210** [comment]
Hi @hewigovens  @catenocrypt 

Can I omit [`source`, `memo` and `private_key`](https://github.com/trustwallet/wallet-core/blob/master/src/proto/Binance.proto#L192) when making the transaction object?

So this is the  [request object](https://gist.github.com/roy1210/99553472844f2c27c4d0f3142daae56c#file-gistfile1-js-L46) in order to make a argument of `sendCallRequest(request)`. But `_sendCallRequest(request)` won't return anything and looks like looping some task forever. Would you mind giving some advice, please? 

Or I'd love to see example of timestamp order. Thank you!!
 
<img width="1761" alt="Screenshot 2020-10-13 at 12 36 48 PM" src="https://user-images.githubusercontent.com/42575132/95816622-1ffbb100-0d52-11eb-8f7b-e9c447cc7fac.png">
