### ISSUE TITLE
TWHDWalletGetKey with 1' coin index in derivation path results in segmentation fault

### ISSUE THREAD

**Issue by 3tbraden** [trustwallet/wallet-core#1111]
I believe that testnet is not supported. But is there any chance that I can get the key with `TWHDWalletGetKey(wallet, derivation_path)` with a derivation path such as `m/84'/1'/0'/0/0`? It currently fails with segmentation fault.

**Comment by hewigovens** [comment]
can you share your code? swift code works fine for me

```swift
let wallet = HDWallet(strength: 128, passphrase: "")
let key = wallet.getKey(coin: .bitcoin, derivationPath: "m/84'/1'/0'/0/0")
print(key.data.hexString)
// afb6b3a3a372518d98fb232fbfac225f30a8475e32afbed2e958a8ebbc7d3c4e
```

**Comment by 3tbraden** [comment]
Oh right I was running with outdated build files. It works fine after rebuilding on the latest release.
