### ISSUE TITLE
NANO Wallet pending transactions 

### ISSUE THREAD

**Issue by juankstylez** [trustwallet/wallet-core#1119]
Hi ! My NANO wallet in trustwallet does not want to receive transactions, they are in "PENDING" status, it has been for days like this, I think you have a problem with the NODO representative of your wallet, CAN YOU repair it? I need to receive my nanos and they are still "PENDING"

the only way to solve this problem was to restore my seed in another interface which uses Magnum wallet

**Comment by vikmeup** [comment]
> Hi ! My NANO wallet in trustwallet does not want to receive transactions, they are in "PENDING" status, it has been for days like this, I think you have a problem with the NODO representative of your wallet, CAN YOU repair it? I need to receive my nanos and they are still "PENDING"
> 
> the only way to solve this problem was to restore my seed in another interface which uses Magnum wallet

Can you upgrade to the latest version? this issue should be resolved in the latest build
