### ISSUE TITLE
Bitcoin.SigningInput.Builder is failing with NoSuchMethodException Android. - Version 2.2.10 / 2.2.3

### ISSUE THREAD

**Issue by Karthikmoback** [trustwallet/wallet-core#1121]
Bitcoin.SigningInput.Builder method is failing when i tried with below code in android Java.

import wallet.core.jni.proto.Bitcoin;

Bitcoin.SigningInput.Builder btcBuilder = Bitcoin.SigningInput.newBuilder();

**Exception**
2020-09-30 16:35:55.349 5145-5145/com.example.appname W/UnsafeUtil: platform method missing - proto runtime falling back to safer methods: java.lang.NoSuchMethodException: copyMemory [class java.lang.Object, long, class java.lang.Object, long, long]

Trust wallet version using : 2.2.10 (also tried with 2.2.3)

I tried in both simulator and Device. Both failed with same exception.
I cleaned the project multiple times and tried, still I'm getting same error. 
It was working fine till few days back, now I'm getting this exception without code change.
Its been a blocker for me to sign, Kindly let me know whats going wrong.

**Comment by catenocrypt** [comment]
Sounds like a serious issue, but I have not encountered similar error before.  Maybe something wrong with your project environment.

Could you maybe try our android sample in a new project?
https://github.com/trustwallet/wallet-core/tree/master/samples/android

**Comment by Karthikmoback** [comment]
There was issue with UTXO and inputs been filled, the exception has not caused the signing hash to fail.
I got it wrong, thinking because of the exception. Sorry for the confusion and thanks for the support.
