### ISSUE TITLE
Remove Smart Chain Legacy

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1128]
Next month

**Comment by catenocrypt** [comment]
It's OK to hide the legacy version from `docs/coins.md` temporarily, and keep only the new one, but the new should point to `smartchain` folder; this could be a source of confusion (we don't want new assets to `bsc` folder).  OK?

```
- | 20000714 | Smart Chain      | BNB    | <img src="https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/bsc/info/logo.png" width="32" />          | <https://www.binance.org/en/smartChain> |
+ | 20000714 | Smart Chain      | BNB    | <img src="https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/smartchain/info/logo.png" width="32" />          | <https://www.binance.org/en/smartChain> |
```

**Comment by hewigovens** [comment]
let's update the script to ignore legacy items

**Comment by catenocrypt** [comment]
I think that's overengineering.  I think we can live with the out-of-sync coins.md file for the temp period, I can update to make sure rest is in sync (it is now), and correct folder is mentioned.
