### ISSUE TITLE
[Filecoin] Return json to push into mpool

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1147]
https://github.com/filecoin-project/lotus/blob/master/documentation/en/api-methods.md#MpoolPush

**Comment by togiter** [comment]
In the new version, how can I convert the signed JSON(Not Hex) data to `type.SignMessage` And then broadcast the transaction to the chain as a parameter of method  `MpoolPush?`

**Comment by hewigovens** [comment]
try sending to a lotus node via json rpc
