### ISSUE TITLE
Public should return correct string representation for getPublicKeyEd25519()

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/wallet-core#118]
If I call `privateKey.getPublicKeyEd25519().description` then get:
`01684c1889d98792caae6a4d10268bb19b2210a78b4fcb4a1fba6ef25beae93212`, but it supposed to be in this format: `edpku9ZF6UUAEo1AL3NWy1oxHLL6AfQcGYwA5hFKrEKVHMT3Xx889A`

**Comment by alejandro-isaza** [comment]
What format is that? Is there a spec?

**Comment by vikmeup** [comment]
@alejandro-isaza not very sure, but it seems like Tezos using this method to convert public key: https://github.com/TrustWallet/wallet-core/blob/30b62d3efea50f01a60f076386db634dede1fe2f/tests/Tezos/OperationListTests.cpp#L55

**Comment by alejandro-isaza** [comment]
Seems like that is specific to Tezos

**Comment by vikmeup** [comment]
Not needed.
