### ISSUE TITLE
btc bip44 derivationPath is Error generating address

### ISSUE THREAD

**Issue by liutianv1** [trustwallet/wallet-core#1184]
**Describe the bug**
on ios swift
I'm already here coins.json Change the path of BTC to bip44，but generated btc address is bip84

**To Reproduce**
![image](https://user-images.githubusercontent.com/35363659/99908225-5bf43f80-2d1c-11eb-8973-89cfb01de1b9.png)

**Expected behavior**
It is expected that the address of BTC bip44 can be generated

**Screenshots**

**Additional context**

**Comment by hewigovens** [comment]
changing deviation path in coins.json will change the private key, if you want to legacy address, you need to use `BitcoinAddress` class, `CoinType` method will always derive bc1 address
