### ISSUE TITLE
How generate bip44 btc testnet address？

### ISSUE THREAD

**Issue by liutianv1** [trustwallet/wallet-core#1186]
**Is your feature request related to a problem? Please describe.**
I'm already here coins.json The information of btctestnet is added in. The generated public key is correct, but the address of the generated bip44 is not correct
![image](https://user-images.githubusercontent.com/35363659/99929582-b2976300-2d88-11eb-8bc3-6e8d166c3658.png)
![image](https://user-images.githubusercontent.com/35363659/99929599-c3e06f80-2d88-11eb-8672-121b3c10c3d5.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by liutianv1** [comment]
@hewigovens

**Comment by liutianv1** [comment]
please tell me how to do , thanks

**Comment by liutianv1** [comment]
ok, im do it .

**Comment by liutianv1** [comment]
ok , im do it

**Comment by liutianv1** [comment]
ok ,im do it .change p2pkhPrefix to 111 in the coins.json

**Comment by eggham0518** [comment]
How to change??
