### ISSUE TITLE
Refactor TWHDWalletGetAccountKey and switch case inside HDWallet::getNode

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/wallet-core#119]
Maybe we can have something like `TWHDWalletGetKey(struct TWHDWallet *wallet, TWCoinType coin, DerivationPath path)`

**Comment by alejandro-isaza** [comment]
It is going to be `TWHDWalletGetKey(struct TWHDWallet *wallet, TWCoinType coin)` since we can deduce the derivation path form the coin.

**Comment by hewigovens** [comment]
Yes, `TWHDWalletGetKey(struct TWHDWallet *wallet, TWCoinType coin)` should be enough.

And we have at least 3 types:

1. BTC `m/44'/0'/0'/0/0`
2. XLM `m/44'/148'/0'` (NANO / Nimiq)
3. AION `m/44'/425'/0'/0'/0'` (Tezos)

The differences between 1/2 is level, 1/3 is hardened, we have 3 `getNode` methods in `HDWallet`, maybe we can do just a simple `for` loop + curve check in one `HDWallet::getNode`.

**Comment by hewigovens** [comment]
👍，it's fixed in https://github.com/TrustWallet/wallet-core/pull/120
