### ISSUE TITLE
Can’t to Bip44 Test Address  sign

### ISSUE THREAD

**Issue by liutianv1** [trustwallet/wallet-core#1192]
**Describe the bug**
![image](https://user-images.githubusercontent.com/35363659/100059485-1d6a9c00-2e66-11eb-886c-8ea0aafe9f58.png)

**To Reproduce**
code follow：
let utxo = BitcoinUnspentTransaction.with {
            $0.outPoint.hash = Data(utxoTxId.reversed()) // reverse of UTXO tx id, Bitcoin internal expects network byte order
            $0.outPoint.index = 0                       // outpoint index of this this UTXO, "vout" field from blockbook utxo api
            $0.outPoint.sequence = UINT32_MAX
            $0.amount = 5151                             // value of this UTXO, "value" field from blockbook utxo api
            $0.script = BitcoinScript.lockScriptForAddress(address: address, coin: coin).data // Build lock script from address or public key hash
        }

        let input = BitcoinSigningInput.with {
            $0.hashType = BitcoinSigHashType.all.rawValue | BitcoinSigHashType.fork.rawValue
            $0.amount = 600
            $0.byteFee = 1
//            $0.toAddress = "1Bp9U1ogV3A14FMvKbRJms7ctyso4Z4Tcx"
            $0.toAddress = "mxf3hJdXuP6faTbwWC34vm3c5PYGqLjQ9m"
            $0.utxo = [utxo]
            $0.privateKey = [privateKey.data]
        }

        let output: BitcoinSigningOutput = AnySigner.sign(input: input, coin: coin)
        print("签名：",output.encoded.hexString)

change "1Bp9U1ogV3A14FMvKbRJms7ctyso4Z4Tcx " can sign
**Expected behavior**
hope can to bip44 test Address sign 
Or i how to do can test address sign 

**Screenshots**

**Additional context**

**Comment by liutianv1** [comment]
![image](https://user-images.githubusercontent.com/35363659/100060028-f82a5d80-2e66-11eb-9b56-d2a33a04cdb5.png)

**Comment by liutianv1** [comment]
@hewigovens

**Comment by liutianv1** [comment]
I did, and I successfully transferred it to testnet

**Comment by gituser** [comment]
@liutianv1 would be helpful for others to know how you did it.

Please share your code.

Thank you.

**Comment by liutianv1** [comment]
ok , Let me sort it out

**Comment by jc0803kevin** [comment]
@liutianv1 请教一下，如何支持bitcoin testnet 424493741

**Comment by YaakovHuang** [comment]
@liutianv1   Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401

**Comment by liutianv1** [comment]
> @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401

首先需要在coins.json里面添加btc测试网的json

**Comment by liutianv1** [comment]
1.coins.json里面添加测试网的信息，然后打包编译
![image](https://user-images.githubusercontent.com/35363659/114375759-979e8180-9bb7-11eb-987b-c5f3b448e7b6.png)
{
    "id": "bitcointest",
    "name": "Bitcoin TestNet",
    "coinId": 1,
    "symbol": "BTC",
    "decimals": 8,
    "blockchain": "Bitcoin",
    "derivationPath": "m/44'/1'/0'/0/0",
    "curve": "secp256k1",
    "publicKeyType": "secp256k1",
    "p2pkhPrefix": 111,
    "p2shPrefix": 196,
    "hrp": "tbc",
    "publicKeyHasher": "sha256ripemd",
    "base58Hasher": "sha256d",
    "xpub": "zpub",
    "xprv": "zprv",
    "explorer": {
      "url": "https://blockchair.com",
      "txPath": "/bitcoin/transaction/",
      "accountPath": "/bitcoin/address/",
      "sampleTx": "0607f62530b68cfcc91c57a1702841dd399a899d0eecda8e31ecca3f52f01df2",
      "sampleAccount": "17A16QmavnUfCW11DAApiJxp7ARnxN5pGX"
    },
    "info": {
      "url": "https://bitcoin.org",
      "client": "https://github.com/trezor/blockbook",
      "clientPublic": "",
      "clientDocs": "https://github.com/trezor/blockbook/blob/master/docs/api.md"
    }
  }
2.根据derivationPath 获取获取私钥
    String derivationPath = CoinType.BITCOINTESTNET.derivationPath();
    PrivateKey privateKey = wallet.getKey(CoinType.BITCOINTESTNET, derivationPath);
3.根据私钥推导出公钥
    PublicKey publicKey = privateKey.getPublicKeySecp256k1(true);
4.根据公钥获取bip44的测试地址。看一下这个文档。https://en.bitcoin.it/wiki/List_of_address_prefixes
        BitcoinAddress bitcoinAddress = new BitcoinAddress(publicKey, CoinType.BITCOINTESTNET.p2pkhPrefix());
        String description = bitcoinAddress.description();
        System.out.println(description);
5.之后的签名流程就和trust-wallet-core中的示例一样了。
6.哪位大神英文好，可以帮忙翻译一下给外国友人看。

**Comment by YaakovHuang** [comment]
> > @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401
> 
> 首先需要在coins.json里面添加btc测试网的json

我是做的android ，我发现coin.json只有源码里面才有这个文件啊，我导入依赖的话，应该怎么修改这个文件呢

**Comment by liutianv1** [comment]
> > > @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401
> > 
> > 
> > 首先需要在coins.json里面添加btc测试网的json
> 
> 我是做的android ，我发现coin.json只有源码里面才有这个文件啊，我导入依赖的话，应该怎么修改这个文件呢

看下我发的详细信息

**Comment by YaakovHuang** [comment]
> > > > @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401
> > > 
> > > 
> > > 首先需要在coins.json里面添加btc测试网的json
> > 
> > 
> > 我是做的android ，我发现coin.json只有源码里面才有这个文件啊，我导入依赖的话，应该怎么修改这个文件呢
> 
> 看下我发的详细信息

相当于我要自己修改源码之后重新编译打包对吗，只有这种办法哈？

**Comment by liutianv1** [comment]
> > > > > @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401
> > > > 
> > > > 
> > > > 首先需要在coins.json里面添加btc测试网的json
> > > 
> > > 
> > > 我是做的android ，我发现coin.json只有源码里面才有这个文件啊，我导入依赖的话，应该怎么修改这个文件呢
> > 
> > 
> > 看下我发的详细信息
> 
> 相当于我要自己修改源码之后重新编译打包对吗，只有这种办法哈？

没错！

**Comment by YaakovHuang** [comment]
> > > > > > @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401
> > > > > 
> > > > > 
> > > > > 首先需要在coins.json里面添加btc测试网的json
> > > > 
> > > > 
> > > > 我是做的android ，我发现coin.json只有源码里面才有这个文件啊，我导入依赖的话，应该怎么修改这个文件呢
> > > 
> > > 
> > > 看下我发的详细信息
> > 
> > 
> > 相当于我要自己修改源码之后重新编译打包对吗，只有这种办法哈？
> 
> 没错！

谢啦，我试一下

**Comment by YaakovHuang** [comment]
> > > > > > > @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401
> > > > > > 
> > > > > > 
> > > > > > 首先需要在coins.json里面添加btc测试网的json
> > > > > 
> > > > > 
> > > > > 我是做的android ，我发现coin.json只有源码里面才有这个文件啊，我导入依赖的话，应该怎么修改这个文件呢
> > > > 
> > > > 
> > > > 看下我发的详细信息
> > > 
> > > 
> > > 相当于我要自己修改源码之后重新编译打包对吗，只有这种办法哈？
> > 
> > 
> > 没错！
> 
> 谢啦，我试一下
在coins.json添加bitcoin test之后重新编译项目遇到了下面这个错误，请问你遇到过吗
![image](https://user-images.githubusercontent.com/9527803/114489292-7b492600-9c45-11eb-9ded-1a11cde1d8fa.png)

**Comment by liutianv1** [comment]
> > > > > > > > @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401
> > > > > > > 
> > > > > > > 
> > > > > > > 首先需要在coins.json里面添加btc测试网的json
> > > > > > 
> > > > > > 
> > > > > > 我是做的android ，我发现coin.json只有源码里面才有这个文件啊，我导入依赖的话，应该怎么修改这个文件呢
> > > > > 
> > > > > 
> > > > > 看下我发的详细信息
> > > > 
> > > > 
> > > > 相当于我要自己修改源码之后重新编译打包对吗，只有这种办法哈？
> > > 
> > > 
> > > 没错！
> > 
> > 
> > 谢啦，我试一下
> > 在coins.json添加bitcoin test之后重新编译项目遇到了下面这个错误，请问你遇到过吗
> > ![image](https://user-images.githubusercontent.com/9527803/114489292-7b492600-9c45-11eb-9ded-1a11cde1d8fa.png)

遇到了，报错的代码里面添加一下BitcoinTEstnet

**Comment by YaakovHuang** [comment]
> > > > > > > > > @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 首先需要在coins.json里面添加btc测试网的json
> > > > > > > 
> > > > > > > 
> > > > > > > 我是做的android ，我发现coin.json只有源码里面才有这个文件啊，我导入依赖的话，应该怎么修改这个文件呢
> > > > > > 
> > > > > > 
> > > > > > 看下我发的详细信息
> > > > > 
> > > > > 
> > > > > 相当于我要自己修改源码之后重新编译打包对吗，只有这种办法哈？
> > > > 
> > > > 
> > > > 没错！
> > > 
> > > 
> > > 谢啦，我试一下
> > > 在coins.json添加bitcoin test之后重新编译项目遇到了下面这个错误，请问你遇到过吗
> > > ![image](https://user-images.githubusercontent.com/9527803/114489292-7b492600-9c45-11eb-9ded-1a11cde1d8fa.png)
> 
> 遇到了，报错的代码里面添加一下BitcoinTEstnet
谢了 方便加个联系方式咨询下不 ？

**Comment by onesand** [comment]
> > > > > > @liutianv1 Hello，我在做btc签名的时候也遇到了这个问题，想请教一下，方便加个联系方式不 ？ 我的vx: MrHuang401
> > > > > 
> > > > > 
> > > > > 首先需要在coins.json里面添加btc测试网的json
> > > > 
> > > > 
> > > > 我是做的android ，我发现coin.json只有源码里面才有这个文件啊，我导入依赖的话，应该怎么修改这个文件呢
> > > 
> > > 
> > > 看下我发的详细信息
> > 
> > 
> > 相当于我要自己修改源码之后重新编译打包对吗，只有这种办法哈？
> 
> 没错！

可以给一下你 build 后的 trustcore 我吗？我这windows不好编译...

**Comment by jiuyaopinyin** [comment]
> 1.coins.json里面添加测试网的信息，然后打包编译 ![image](https://user-images.githubusercontent.com/35363659/114375759-979e8180-9bb7-11eb-987b-c5f3b448e7b6.png) { "id": "bitcointest", "name": "Bitcoin TestNet", "coinId": 1, "symbol": "BTC", "decimals": 8, "blockchain": "Bitcoin", "derivationPath": "m/44'/1'/0'/0/0", "curve": "secp256k1", "publicKeyType": "secp256k1", "p2pkhPrefix": 111, "p2shPrefix": 196, "hrp": "tbc", "publicKeyHasher": "sha256ripemd", "base58Hasher": "sha256d", "xpub": "zpub", "xprv": "zprv", "explorer": { "url": "https://blockchair.com", "txPath": "/bitcoin/transaction/", "accountPath": "/bitcoin/address/", "sampleTx": "0607f62530b68cfcc91c57a1702841dd399a899d0eecda8e31ecca3f52f01df2", "sampleAccount": "17A16QmavnUfCW11DAApiJxp7ARnxN5pGX" }, "info": { "url": "https://bitcoin.org", "client": "https://github.com/trezor/blockbook", "clientPublic": "", "clientDocs": "https://github.com/trezor/blockbook/blob/master/docs/api.md" } } 2.根据derivationPath 获取获取私钥 String derivationPath = CoinType.BITCOINTESTNET.derivationPath(); PrivateKey privateKey = wallet.getKey(CoinType.BITCOINTESTNET, derivationPath); 3.根据私钥推导出公钥 PublicKey publicKey = privateKey.getPublicKeySecp256k1(true); 4.根据公钥获取bip44的测试地址。看一下这个文档。https://en.bitcoin.it/wiki/List_of_address_prefixes BitcoinAddress bitcoinAddress = new BitcoinAddress(publicKey, CoinType.BITCOINTESTNET.p2pkhPrefix()); String description = bitcoinAddress.description(); System.out.println(description); 5.之后的签名流程就和trust-wallet-core中btc正式网签名的示例一样了。 6.哪位大神英文好，可以帮忙翻译一下给外国友人看。

老哥你好,我按照你这个操作,json也改完编译好之后,地址和私钥都正确,但是后面的步骤按照示例直接卡在AnySigner.plan和AnySigner.sign上了,请问你那怎么样?

**Comment by liutianv1** [comment]
> 

我这里是正常的，你可以贴一下你的错误信息

**Comment by jiuyaopinyin** [comment]
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/16219599/157789359-2c2e957f-07f1-46cc-87b2-00ea95267c1b.png">
这里直接报空指针了,但是如果我把coin换成.bitcoin的话就是正常的.

**Comment by liutianv1** [comment]
![image](https://user-images.githubusercontent.com/35363659/157790139-422ef6c9-1e8b-4468-85c9-026d7d9a42e2.png)
![image](https://user-images.githubusercontent.com/35363659/157790194-75457f37-1e51-4a62-9b4a-e4163eb9bf0f.png)
  我这里没有报错，不清楚你这边啥情况 @jiuyaopinyin

**Comment by jiuyaopinyin** [comment]
> ![image](https://user-images.githubusercontent.com/35363659/157790139-422ef6c9-1e8b-4468-85c9-026d7d9a42e2.png) ![image](https://user-images.githubusercontent.com/35363659/157790194-75457f37-1e51-4a62-9b4a-e4163eb9bf0f.png) 我这里没有报错，不清楚你这边啥情况 @jiuyaopinyin

我直接照着你这个又重写了一下,还是卡到那了,大哥能给一下你封装的framework和这个类文件吗?

**Comment by developerjet** [comment]
> ![image](https://user-images.githubusercontent.com/35363659/100060028-f82a5d80-2e66-11eb-9b56-d2a33a04cdb5.png)

请教一哈，一下这个utxoTxId的hexString是怎么来的呢。

**Comment by tiantianlikeu** [comment]
> 

这个是基础啊，根据你的btc地址查询utxo的接口就可以拿到了

**Comment by developerjet** [comment]
> > 
> 
> 这个是基础啊，根据你的btc地址查询utxo的接口就可以拿到了

如何支持BTC Test Net的钱包地址生成，转账签名处理呢，目前最新的库没有找到coin.json的文件。

**Comment by tiantianlikeu** [comment]
> > > 
> > 
> > 
> > 这个是基础啊，根据你的btc地址查询utxo的接口就可以拿到了
> 
> 如何支持BTC Test Net的钱包地址生成，转账签名处理呢，目前最新的库没有找到coin.json的文件。
往上翻，我21年的回复中有答案

**Comment by developerjet** [comment]
> coins.json

看了一下，主要是要对coins.json文件进行修改，然后再进行编译处理，但是目前的库文件里没有找到coins.json文件呢。

**Comment by tiantianlikeu** [comment]
> > coins.json
> 
> 看了一下，主要是要对coins.json文件进行修改，然后再进行编译处理，但是目前的库文件里没有找到coins.json文件呢。

刚看了一下源码，貌似改名了，registry.json

**Comment by developerjet** [comment]
> > > coins.json
> > 
> > 
> > 看了一下，主要是要对coins.json文件进行修改，然后再进行编译处理，但是目前的库文件里没有找到coins.json文件呢。
> 
> 刚看了一下源码，貌似改名了，registry.json

我如何对已Pod进来的WalletCore的registry.json进行添加BTC测试网络，然后编译成功呢
