### ISSUE TITLE
Android build error

### ISSUE THREAD

**Issue by SunSeekerX** [trustwallet/wallet-core#1194]
/root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:82:36: error: expected function body after function declarator
  long double acosl(long double __x) __RENAME_LDBL(acos, 3, 21);
                                     ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:86:36: error: expected function body after function declarator
  long double asinl(long double __x) __RENAME_LDBL(asin, 3, 21);
                                     ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:90:36: error: expected function body after function declarator
  long double atanl(long double __x) __RENAME_LDBL(atan, 3, 21);
                                     ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:94:54: error: expected function body after function declarator
  long double atan2l(long double __y, long double __x) __RENAME_LDBL(atan2, 3, 21);
                                                       ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:98:35: error: expected function body after function declarator
  long double cosl(long double __x) __RENAME_LDBL(cos, 3, 21);
                                    ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:102:35: error: expected function body after function declarator
  long double sinl(long double __x) __RENAME_LDBL(sin, 3, 21);
                                    ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:106:35: error: expected function body after function declarator
  long double tanl(long double __x) __RENAME_LDBL(tan, 3, 21);
                                    ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:108:29: error: expected function body after function declarator
  int ilogbl(long double __x) __RENAME_LDBL(ilogb, 3, 3) __attribute_const__;
                              ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:112:53: error: expected function body after function declarator
  long double ldexpl(long double __x, int __exponent) __RENAME_LDBL(ldexp, 3, 3);
                                                      ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:117:53: error: expected function body after function declarator
  long double ldexpl(long double __x, int __exponent) __RENAME_LDBL(ldexp, 3, 3);
                                                      ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:121:35: error: expected function body after function declarator
  long double logl(long double __x) __RENAME_LDBL(log, 3, 21);
                                    ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:125:37: error: expected function body after function declarator
  long double log10l(long double __x) __RENAME_LDBL(log10, 3, 21);
                                      ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:129:37: error: expected function body after function declarator
  long double log1pl(long double __x) __RENAME_LDBL(log1p, 3, 21);
                                      ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:133:25: error: expected function body after function declarator
  double log2(double __x) __INTRODUCED_IN(18);
                          ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:134:24: error: expected function body after function declarator
  float log2f(float __x) __INTRODUCED_IN(18);
                         ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:135:36: error: expected function body after function declarator
  long double log2l(long double __x) __RENAME_LDBL(log2, 18, 18);
                                     ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:141:36: error: expected function body after function declarator
  long double logbl(long double __x) __RENAME_LDBL(logb, 3, 18);
                                     ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:145:66: error: expected function body after function declarator
  long double modfl(long double __x, long double* __integral_part) __RENAME_LDBL(modf, 3, 21);
                                                                   ^
  /root/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/math.h:149:54: error: expected function body after function declarator
  long double scalbnl(long double __x, int __exponent) __RENAME_LDBL(scalbn, 3, 3);

**Comment by hewigovens** [comment]
Did you follow this guide? https://developer.trustwallet.com/wallet-core/developing-the-library/building which step did you see those errors?

**Comment by SunSeekerX** [comment]
tools/android-release

**Comment by hewigovens** [comment]
we haven't tried run release script on Linux, can you try macOS?

**Comment by SunSeekerX** [comment]
I don`t have macOS

**Comment by SunSeekerX** [comment]
please U try run release script on linux or docker

**Comment by SunSeekerX** [comment]
Sorry, my colleague opened this issue with my account.
