### ISSUE TITLE
[Flutter/Dart] Support Dart: Use Dart FFI 

### ISSUE THREAD

**Issue by hhstore** [trustwallet/wallet-core#1200]
# Support Dart: 

- since i want to use `wallet-core` in dart. 
- so i try to use `dart:ffi` to make it. 
- but i am not quite familiar with `wallet-core`. 
- anyone who wants to help me? or any suggestions on where to start first?
- i would really appreciate it.

## my fork: 

- https://github.com/better-dart/trustwallet-core/tree/dart/ffi-base-on-v2.3.9
- dev-branch: `dart/ffi-base-on-v2.3.9`
- i will add `dart:ffi` to support dart here.

## dart ffi: 

- https://dart.dev/guides/libraries/c-interop
- https://flutter.dev/docs/development/platform-integration/c-interop

### libs: 

- [x] https://github.com/dart-lang/ffi
- [x] https://github.com/dart-lang/ffigen
    - a tool to auto gen binding codes.

### usage: c++ with ffi 

- https://github.com/dart-lang/tflite_native

![image](https://user-images.githubusercontent.com/3252130/101440225-3a689a00-3951-11eb-9ba5-46f2574e0581.png)

# Maybe these are the things I need?

## docs: 

- binding: https://developer.trustwallet.com/wallet-core/developing-the-library/building

- ios: https://developer.trustwallet.com/wallet-core/integration-guide/ios-guide

```
 pod 'TrustWalletCore'

```

- android: https://developer.trustwallet.com/wallet-core/integration-guide/android-guide

> jni load: 

```java
init {
    System.loadLibrary("TrustWalletCore")
}

```

- go: https://developer.trustwallet.com/wallet-core/integration-guide/server-side

## *.h

- https://github.com/trustwallet/wallet-core/blob/81a5b234f6/include/TrustWalletCore/TWHDWallet.h

## jni: 

- https://github.com/trustwallet/wallet-core/blob/81a5b234f6/jni/cpp/TWJNI.h

## gen proto ? 

- https://github.com/trustwallet/wallet-core/blob/e8ff9c7106/tools/generate-files

- pb: https://github.com/trustwallet/wallet-core/blob/e8ff9c7106/src/proto/Ethereum.proto

## iOS: 

- https://github.com/trustwallet/wallet-core/blob/81a5b234f6/tools/ios-build

## Android: 

- https://github.com/trustwallet/wallet-core/blob/81a5b234f6/tools/android-build

## code gen: 

- https://github.com/trustwallet/wallet-core/blob/99af2f62cd/codegen/lib/code_generator.rb

**Comment by hhstore** [comment]
## dart ffi progress: 

- https://github.com/better-dart/wallet-core/blob/dart%2Fffi-base-on-v2.3.9/dart/README.md
- the `Binding file` has been successfully generated, and I am testing it.

**Comment by hewigovens** [comment]
Are you building dart bindings on top of existing iOS/android lib?

**Comment by hhstore** [comment]
> Are you building dart bindings on top of existing iOS/android lib?

- from this doc, https://developer.trustwallet.com/wallet-core/developing-the-library/releasing
    - https://bintray.com/trust/wallet-core/com.trustwallet.wallet-core
- i find `android` wallet-core.aar file. 
- i still working on how to add `android aar` to my flutter project and call it via `dart binding codes`, since the docs related to `dart:ffi` are really rare.
- i think i need  `ios/Android` dynamic library. 
- but i not sure, if `aar` is what i needed? or i should build a dynamic library by myself.


## about dart ffi usage: 


- https://flutter.dev/docs/development/platform-integration/c-interop#step-3-load-the-code-using-the-ffi-library


![image](https://user-images.githubusercontent.com/3252130/101438114-941a9580-394c-11eb-8a0a-1a763b70dd3a.png)


- a rust ffi binding usage: https://github.com/Hentioe/mikack-ffi
    - https://github.com/Hentioe/mikack-ffi/blob/master/Makefile#L42
> this a rust ffi usage, use for a flutter project. i think i'm going to do something like this. 

![image](https://user-images.githubusercontent.com/3252130/101438341-215dea00-394d-11eb-9dc2-af3dca54d8dd.png)

**Comment by hewigovens** [comment]
Hey, what's status of dart binding? I think you can skip building process and unzip aar from here https://bintray.com/trust/wallet-core/com.trustwallet.wallet-core/2.4.1

**Comment by jayateertha043** [comment]
Hey, 
I was also looking for the same integration ,if you managed to integrate trust wallet into flutter kindly let me know

Thanks and regards
Jayateertha G

**Comment by jayateertha043** [comment]
Can't we just put the aar files into android/lib/ folder and interact with them using method channel ?

**Comment by hhstore** [comment]
@hewigovens 


- It's not going well. 
- I encountered some native-related problems, which I can't solve at the moment.
- Due to time constraints, I am temporarily using the `dart native library` instead.
- However, I will still consider replacing it with `trustwallet-core`.
- I would still try the `FFI` or `channel method` to bind the `trustwallet-core`.

## Follow up:

- The latest developments will be synchronized in the following 2 projects.


## use FFI: 

- https://github.com/better-dart/trustwallet-core


## use Platform Channels: 


- https://github.com/better-dart/flutter_trust_wallet_core
- channel method

**Comment by hhstore** [comment]
@jayateertha043 

- Using the `channel method` is a good choice. 
- To use the channel method, you need to write Android/iOS `native codes`, but I'm not familiar with native. 
- If you are familiar with native coding, you can try it.
