### ISSUE TITLE
Build android from sources.

### ISSUE THREAD

**Issue by kiwina** [trustwallet/wallet-core#1201]
I just cant get it done tons of errors, obbviously for security reasons building your own version is a must. But tageting android on a mac witch likely works is contradicting

**Comment by vikmeup** [comment]
See example from CI on how to run with all configuration for android

- tests: https://github.com/trustwallet/wallet-core/blob/master/.github/workflows/android-ci.yml
- release: https://github.com/trustwallet/wallet-core/blob/master/.github/workflows/android-release.yml
