### ISSUE TITLE
Ethereum: support for new fee structure (EIP 1559)

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#1209]
https://eips.ethereum.org/EIPS/eip-1559 

Timeline?
Resources, Practical guide?

**Comment by hewigovens** [comment]
how does this related to wallet core? it looks like it's done by RPC / networking level

**Comment by catenocrypt** [comment]
Info on current status
https://hackmd.io/@timbeiko/1559-updates/https%3A%2F%2Fhackmd.io%2F%40timbeiko%2F1559-update-004

**Comment by catenocrypt** [comment]
Implementing support for EIP-1559 should become timely 1, max 2 months before the expected time of its launch on mainnet.  This is still further away, so I close this issue for now.

I had contact with Pooja Ranjan, filled out their questionnaire.
