### ISSUE TITLE
XDAI & MATIC network support in android wallet by default

### ISSUE THREAD

**Issue by kropple** [trustwallet/wallet-core#1211]
**Is your feature request related to a problem? Please describe.**
many evm compatible networks are supported like POA or TOMOCHAIN, which few use.

the rather popular XDAI and MATIC networks are not on the list when importing a private key :(

**Describe the solution you'd like**
bring XDAI and MATIC networks in the list at key import

**Describe alternatives you've considered**
i have to use another wallet for these networks, but i love trustwallet

**Comment by catenocrypt** [comment]
Can you be more specific?
Do you mean implementing XDAI and MATIC blockchain support in wallet core?
Or just the possibility for address derivation?

Support for these blockchains is not planned currently.
