### ISSUE TITLE
[Android/Kotlin] Different JSON/KeyStore format

### ISSUE THREAD

**Issue by toidv** [trustwallet/wallet-core#1217]
The `exportJSON()` function of `StoredKey` object generate the different format with previous one [(example)](https://github.com/trustwallet/wallet-core/blob/2d050d03b7c3adbb32a346182a48abf2e48d64c3/tests/Keystore/Data/wallet.json#L22). 
The wallet address was move to `activeAccounts`, so the previous implementation can't read the new json format properly

**The old format:** 
`{"id":"b60407b4-839c-4cee-a247-c66f8ac1d2f0","version":3,"type":"private-key","crypto":{"ciphertext":"90a438c65be079de6292cb13a20ffa4be41e6bb1e9b7e790f0d3b0a40b68600e","cipherparams":{"iv":"016088bcae96f7d8575940caf7fbc0db"},"kdf":"scrypt","kdfparams":{"r":8,"p":6,"n":4096,"dklen":32,"salt":"1c02fcf2d9c28c7dc52bddb0c9fe7b52f76729eb37580afd21dd1698cb9d617a"},"mac":"775fccea93d1201b61dfc5069d6b1edcda5a96be8ad9c9f2e336868bfeb6fc7d","cipher":"aes-128-ctr"},"address":"2427f61593Eb99CBf3DC7B4d2177bB651A3F61b9"}`

**The new one:**
`{"activeAccounts":[{"address":"0x219D5b85644457E7bfD42670c545c89c22E2840F","coin":60,"derivationPath":"m/44'/60'/0'/0/0"}],"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"06735cada8ef1a4bdfab625ee2511605"},"ciphertext":"47eebc008585884def44caa03e54ad549bf62186890d91365ed4666e08e12116","kdf":"scrypt","kdfparams":{"dklen":32,"n":4096,"p":6,"r":8,"salt":"b953a328493ed5ade641987bd9a052ce777e80f1e4bbce1fa589cb26e86b8e4b"},"mac":"6b5e94f09030ad6f422fd2c609bf5cfe8b150b87ab64542f30ab8e6c36acd6e6"},"id":"e8814193-51db-4915-9f0d-fbf0f89fa356","name":"Untitled","type":"private-key","version":3}`

Please also support the old format for exporting JSON file

**Comment by hewigovens** [comment]
You can try to import old keystore file then export, `Account.cpp` has code to deal with legacy ones https://github.com/trustwallet/wallet-core/blob/master/src/Keystore/Account.cpp#L44, the old one is ethereum only, most of case you will use multi coin keystore file

**Comment by toidv** [comment]
@hewigovens: The problem is when exporting JSON file for a new wallet, it can't import to the old implementation or the other ethereum wallets, because the format is a little different. Adding another API rather than `exportJSON` would be nice. 

Recently, we can work around to archive the previous format by using [web3j](https://github.com/web3j/web3j) but native support from the library will be cool
```
override fun exportKeystore(param: ExportKeystoreWalletUseCase.Param): Single<String> {
    return Single.fromCallable {
               ...
		val storedKey = StoredKey.load(file.absolutePath)
		val privateKey = storedKey.privateKey(CoinType.ETHEREUM, password.toByteArray()).data().toHexString(false)
		val keyPair  = Credentials.create(privateKey).ecKeyPair
		val walletFile = org.web3j.crypto.Wallet.createLight(param.password, keyPair)
		Gson().toJson(walletFile)
    }
}
```

**Comment by hewigovens** [comment]
@catenocrypt could you add one `exportEthereumKeystore` method when you adding android keystore? thanks

**Comment by jpnapps** [comment]
how to boardcast tron transaction? please help me

**Comment by catenocrypt** [comment]
Wallet core can be used to create the signed transaction; you have to handle sending the TX to a Tron node yourself.
Next time please use our telegram channel for such questions (https://t.me/trust_developers).
