### ISSUE TITLE
BTC CPFP Support Child-Pays-For-Parent, for changing an already broadcast transactions

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#1222]
For subsequent boosting of fee for an already broadcast Bitcoin transaction, there is RBF, but there is also another option: CPFP.
Replace-by-Fee (see #976 ) is not intuitive, cumbersome, and handled differently by clients.
Child-Pays-For-Parent is another approach, does not rely on any special flag, and it is more flexible that it can change not only the fee.
How CPFP works I describe by an example:
  - I create a TX with input of 0.2 BTC from address A, with output of 0.1 BTC to address B and change 0.0999 to A, with fee 0.0001.  Let's assume the TX size is 200 bytes, and the fee rate is thus 50 sats/byte.
- I realize the fee should have been much higher, like this it will not be picked up by miners, but be in pending for a long time
- To boost this TX, I create _another_ tx, with:
- input the change output of the first tx, 0.0999 from A
- output again A, but with 0.0991.

The 2nd TX uses an UTXO from TX1, which is pending, but this is allowed.  Of course, TX2 will be included in a block only together with or after TX1.  
Miners will consider TX2 together with TX1, and consider the _average_ fee of the two.  The 2 TXs will have avg 225 sats/byte fee (400 bytes, 0.0009 btc).
If TX2 has sufficient high fee, it will raise the average sufficiently to be competitive to mine.

Most wallets do not support CPFP, only Bitcoin Core and Electrum.

**Comment by hewigovens** [comment]
what should we do for this?

**Comment by catenocrypt** [comment]
Closing for now, we can reopen if there is demand/need.
