### ISSUE TITLE
Disable running codecov patch on master

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1239]
only need to run project level coverage on master, patch/diff will be enforced on each pull request

**Comment by catenocrypt** [comment]
The anomaly observed:
- PR #1230 contains only test additions, so it cannot decrease coverage
- coverage/project reports coverage decrease
- coverage/patch reports no change
- PR branch was created off commit f162f0f.  Coverage build reported -0.01% coverage decrease.
- After more commits, and merging master commit 1dfd9fa, coverage build reports -0.02%.
- PR #1227 for commit 1dfd9fa showed following numbers (cov/hits/missed, after commit and before):  95.28% 12453 616 ; 95.29%  12506 617
- PR #1230 shows following numbers (cov/hits/missed, after commit and before):  95.28% 12453 616 ; 95.30% 12518 617)
- Coverage build on master, commit 1dfd9fa, shows 95.30% 12518 617  https://codecov.io/gh/trustwallet/wallet-core/tree/1dfd9fa491cb9c1728e2bb082109f1d8a5018e8b
- I expect the before number for PR #1230 to match the after numbers for PR #1227 (commit 1dfd9fa), but they are not (95.30 vs 95.28)

So it looks to me that coverage (project) comparison is not producing the correct numbers.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/13562139/104462520-f94b5180-55b0-11eb-8962-e6f1db01b4db.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/13562139/104462549-036d5000-55b1-11eb-9aa4-2bdf5e91b767.png">

**Comment by hewigovens** [comment]
let's ask codecov support?
