### ISSUE TITLE
Deep links do not open [android] [dapp browser]

### ISSUE THREAD

**Issue by nance2uiuc** [trustwallet/wallet-core#1254]
**Describe the bug**
I'm trying to open something like “https://t.me/joinchat/F_BETUjG0Crb2s6mFx1LWA” from a page inside the dapp browser, but instead of launching the telegram app, the browser stalls for over 30sec and eventually opens a Google search query of an invite link (not even the original link) as- "tg:join?invite=F_BETUjG0Crb2s6mFx1LWA".

**To Reproduce**
Go to any page with a telegram link and try to open it from the dapp browser. For instance, https://opengsn.org/

**Expected behavior**
A page should pop up saying "Open in telegram". The user should be able to click the link and the telegram app should open.

**Additional context**
The "Open in Telegram" page shows for a brief moment right before the dapp browser hijacks it and displays the google search query.

**Comment by ivanKis** [comment]
@vikmeup 
Maxim has commented  that this feature was disabled by security reasons. 
https://github.com/trustwallet/android/issues/3875#issuecomment-765362830 

Also I checked iOS. Telegram deep link handling is disabled in dApp browser.
