### ISSUE TITLE
ALGO Token not accessible

### ISSUE THREAD

**Issue by RebelCoderRU** [trustwallet/wallet-core#1257]
Bug description:

After ALGO tokens arrived into the wallet (first, initial transaction), they automatically became 'staked' and are not accessible. 'Staked' shows 0, and you can't stake or withdraw them as "Not available" error is shown.

Transaction details: [Link](https://algoexplorer.io/tx/37EYFSDSFUDNJASCRQNN6N77E4LVRCHOAR5LGDITLEA2W3EGUOUA)

**First ALGO transfer to the wallet:**
![image](https://user-images.githubusercontent.com/20476773/105412708-bd159200-5c3d-11eb-829b-231da25d9fb0.png)

We can see, tokens are both, available and staked. Also, no three-dot menu for staking is visible.

**Here we can see that 0 tokens are staked:**
![image](https://user-images.githubusercontent.com/20476773/105412812-e33b3200-5c3d-11eb-8034-2e9ebcb436ad.png)

**Attempt to stake or withdraw results in the following error:**
![image](https://user-images.githubusercontent.com/20476773/105412887-fea63d00-5c3d-11eb-9a8d-46268f0048e3.png)

**Comment by vikmeup** [comment]
ALGO tokens staked automatically by the network, no actions are required.

**Comment by vikmeup** [comment]
Stake and Unstake options will be removed in the next build
