### ISSUE TITLE
[Bitcoin]How to build OMNI(USDT) transaction? Help, please.

### ISSUE THREAD

**Issue by vicishero** [trustwallet/wallet-core#1259]

**Comment by hewigovens** [comment]
we decided to not support it, please use USDT on Ethereum or other network

**Comment by vicishero** [comment]
OK, I think wallet-core is a great c + + open source project. I'm not very familiar with the code right now. If I want to support Omni function base on wallet-core, can you provide some development ideas? If completed, it will be open source

**Comment by vicishero** [comment]
OK, I think Wallet core is a great c + + open source project. I'm not very familiar with the code right now. If I want to support Omni function, can you provide some development suggestions? If completed, it will be open source.

**Comment by hewigovens** [comment]
Yes, please join https://t.me/trust_developers for help
