### ISSUE TITLE
[iOS] complier error of google/protobuf

### ISSUE THREAD

**Issue by EricDLee-sz** [trustwallet/wallet-core#1262]
**Describe the bug**
I have integrated wallet-core via Cocoapods but in Development Pods way. Any idea on this issue? Or is it possible to install wallet-core in this way? If the answer is NO, how can I use a forked repo?

**To Reproduce**
1. download repo
2. install pod using 'path'
3. build iOS project

**Expected behavior**
Project build successfully

**Screenshots**
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/54877716/105973207-6ab5f480-60c7-11eb-8389-dd186c6a4204.png">

**Additional context**

**Comment by hewigovens** [comment]
try this way
```ruby
pod 'TrustWalletCore', git: 'https://github.com/trustwallet/wallet-core', branch: 'master'`
```

we have a pull request enables installing from local path: https://github.com/trustwallet/wallet-core/pull/1189, you still need to setup wallet core development environment, the best way is building and testing in `swift/TrustWalletCore.xcworkspace` first then integrate it to your app
