### ISSUE TITLE
Protocol message tag had invalid wire type.

### ISSUE THREAD

**Issue by jc0803kevin** [trustwallet/wallet-core#1271]
**Describe the bug**
{"Error":"class com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException : Protocol message tag had invalid wire type."}

**To Reproduce**

**Expected behavior**

tron tx hex 
0a208a9cde896b2938fabd55b165d23466b386ceca14c25670e3992cb2594cf6ccdf1241e5fe0e28b468e54ac0e05f0750c40bb454c64830e24692ba8eee5ab8c72f0e5124b50c6887aff12e15c95ec4bd25130b33fbc82a2635e982a5b88b69f75602f9001a0261b62208b2b7e15f301d929e2ab9047b227261775f64617461223a7b22636f6e7472616374223a5b7b22706172616d65746572223a7b22747970655f75726c223a22747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e576974686472617742616c616e6365436f6e7472616374222c2276616c7565223a7b226f776e65725f61646472657373223a22343162353532333261346135343861653933663531356565643464343433336664643832656362323534227d7d2c2274797065223a22576974686472617742616c616e6365436f6e7472616374227d5d2c2265787069726174696f6e223a313631313932373132363030302c226665655f6c696d6974223a31303030303030302c227265665f626c6f636b5f6279746573223a2236316236222c227265665f626c6f636b5f68617368223a2262326237653135663330316439323965222c2274696d657374616d70223a313631313839313132363030307d2c227369676e6174757265223a5b2265356665306532386234363865353461633065303566303735306334306262343534633634383330653234363932626138656565356162386337326630653531323462353063363838376166663132653135633935656334626432353133306233336662633832613236333565393832613562383862363966373536303266393030225d2c2274784944223a2238613963646538393662323933386661626435356231363564323334363662333836636563613134633235363730653339393263623235393463663663636466227d

**Additional context**
`

String mnemonicCode = "xxxxxx";
        HDWallet hdWallet = new HDWallet(mnemonicCode, "");
        PrivateKey privateKey = hdWallet.getKey(HDCoin.TRX.getPath(0));
        System.out.println("privateKey ->" + Hex.encodeHexString(privateKey.data()));

        try {
            TrxInvoker trxInvoker = new TrxInvoker();
            JSONObject data = trxInvoker.getNowBlock();

            Tron.BlockHeader blockHeader = Tron.BlockHeader.newBuilder()
                    .setNumber(data.getLong("number"))
                    .setTxTrieRoot(ByteString.copyFrom(Hex.decodeHex(data.getString("txTrieRoot"))))
                    .setWitnessAddress(ByteString.copyFrom(Hex.decodeHex(data.getString("witness_address"))))
                    .setParentHash(ByteString.copyFrom(Hex.decodeHex(data.getString("parentHash"))))
                    .setTimestamp(data.getLong("timestamp"))
                    .setVersion(data.getIntValue("version"))
                    .build();

            Tron.TransferTRC20Contract transferTRC20Contract = Tron.TransferTRC20Contract.newBuilder()
                    // 1000
                    .setAmount(ByteString.copyFrom(new BigInteger("1000", 10).toByteArray()))
                    .setToAddress("TSVwmz6nkwQwzxjLSZWauMmQTZC9UczhPC")
                    .setOwnerAddress("TJRyWwFs9wTFGZg3JbrVriFbNfCug5tDeC")
                    .setContractAddress("THTR75o8xXAgCTQqpiot2AFRAjvW1tSbVV")
                    .build();

            Tron.WithdrawBalanceContract withdrawBalanceContract = Tron.WithdrawBalanceContract.newBuilder()
                    .setOwnerAddress("TSVwmz6nkwQwzxjLSZWauMmQTZC9UczhPC")
                    .build();

            Tron.Transaction transaction = Tron.Transaction.newBuilder()
                    .setTransferTrc20Contract(transferTRC20Contract)
                    .setTimestamp(data.getLong("timestamp"))
                    .setBlockHeader(blockHeader)
                    .setFeeLimit(10000000L)
                    .build();

            Tron.SigningInput signingInput = Tron.SigningInput.newBuilder()
                    .setPrivateKey(ByteString.copyFrom(privateKey.data()))
                    .setTransaction(transaction)
                    .build();

            Tron.SigningOutput signingOutput = AnySigner.sign(signingInput, CoinType.TRON, Tron.SigningOutput.parser());

            System.out.println("signingOutput ->" + Hex.encodeHexString(signingOutput.toByteArray()));
        } catch (Exception e) {
            e.printStackTrace();
        }`

**Comment by hewigovens** [comment]
can you check out swift test? https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Blockchains/TronTests.swift#L24, it's already json

**Comment by jc0803kevin** [comment]
@hewigovens 
This is my raw data
`
{
	"raw_data": {
		"contract": [
			{
				"parameter": {
					"type_url": "type.googleapis.com/protocol.TransferContract",
					"value": {
						"amount": 1000,
						"owner_address": "41b55232a4a548ae93f515eed4d4433fdd82ecb254",
						"to_address": "41022eb6ae38cd55380e4fd2da31c9b6895044ff3a"
					}
				},
				"type": "TransferContract"
			}
		],
		"expiration": 1611935235000,
		"fee_limit": 10000000,
		"ref_block_bytes": "6c2b",
		"ref_block_hash": "7c0be6f2e03785b7",
		"timestamp": 1611899235000
	},
	"signature": [
		"19329bdbe33f58346f5a40209bd2f87376b8e16104eff00e5093b960a08d1253760800fc800b6b607a43c457b073b428540c37d5c79761629e321c41d2ae6c8101"
	],
	"txID": "ed72c8263c5d92e1e64af138b8e3c58a225b591d3dd400d4c87fde0a4ab7c9ce"
}
`

**Comment by jc0803kevin** [comment]
> can you check out swift test? https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Blockchains/TronTests.swift#L24, it's already json

run this case 
result: class com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException : Protocol message tag had invalid wire type

**Comment by hewigovens** [comment]
how did you send the json blob? try https://developers.tron.network/reference#walletbroadcasttransaction-1, @vcoolish have you ever seen this error response?

**Comment by vcoolish** [comment]
No, I haven't seen such

**Comment by jc0803kevin** [comment]
@hewigovens 只能通过 signingOutput.getJson()，然后通过https://api.trongrid.io/wallet/broadcasttransaction 进行广播交易是可以完成，如何通过hex(signingOutput.toByteArray())  再通过广播十六进制https://api.trongrid.io/wallet/broadcasthex

**Comment by hewigovens** [comment]
you can try to get the signed `signature` and build the raw hex by yourself, but it might be removed in future release, better to use `json`

**Comment by jiuyaopinyin** [comment]
> @hewigovens 只能通过 signingOutput.getJson()，然后通过https://api.trongrid.io/wallet/broadcasttransaction 进行广播交易是可以完成，如何通过hex(signingOutput.toByteArray()) 再通过广播十六进制https://api.trongrid.io/wallet/broadcasthex

老哥你解决了吗?

**Comment by jiuyaopinyin** [comment]
> you can try to get the signed `signature` and build the raw hex by yourself, but it might be removed in future release, better to use `json`

How to use this step details?please?

**Comment by shinedlc** [comment]
is anyone solved it ?....

**Comment by luqiao19950804** [comment]
官方都不搞raw_data_hex了么

**Comment by shinedlc** [comment]
> broadcasthex
最终用自定义的 Sample.proto构建了raw_data_hex 和签名版 sign_raw_data_hex,可以成功广播！
1、先把proto转成你的代码类
protoc --swift_out=. ./Sample.proto
java_lite for android: protoc --java_out=lite:. ./TLink.proto
java for server: protoc --java_out=. ./TLink.proto
2、导入类后构建sign_raw_data_hex (或者可以直接通过raw_data_hex构建，从api.trongrid.io/wallet/createtransaction获取的，然后签名一下就丢上去?)
3、把签名后的hex丢上去：https://api.trongrid.io/wallet/broadcasthex
4、Samle.proto 

`
        syntax = "proto3";
        
        package YourPakageName;
        option java_package = "wallet.core.jni.proto";
        
        
        message Contract {
            enum ContractType {
                AccountCreateContract = 0;
                TransferContract = 1;
                TransferAssetContract = 2;
                VoteAssetContract = 3;
                VoteWitnessContract = 4;
                FreezeBalanceContract = 11;
                UnfreezeBalanceContract = 12;
                WithdrawBalanceContract = 13;
                UnfreezeAssetContract = 14;
                TriggerSmartContract = 31;
                FreezeBalanceV2Contract = 54;
                UnfreezeBalanceV2Contract = 55;
                WithdrawExpireUnfreezeContract = 56;
                DelegateResourceContract = 57;
                UnDelegateResourceContract = 58;
            }
            ContractType type = 1;
            message Parameter {
    	         message Transfer {
    	 		        bytes owner_address = 1;
    	 		        bytes to_address = 2;
    	 		        int64 amount = 3;
    	         }
    	         string type_url = 1;
    	         Transfer value = 2;
            }
            Parameter parameter = 2;
        }
        
        
        message raw {
            bytes ref_block_bytes = 1;
            bytes ref_block_hash = 4;
            int64 expiration = 8;
            repeated Contract contract = 11;
            int64 timestamp = 14;
        }
        
        message signRaw {
		        raw raw_data = 1;
            repeated bytes signature = 2;
        }
`
proto是通过手动反编译createtransaction的raw_data_hex来的，其他人有更好的版本方式分享一下，刚开始也尝试使用Google_Protobuf_Any来构建parameter，这样可以使用trustWalletCore内置的Contract结构之类的，想直接用TronSigningOutput生成的json初始化，但输出json或serializedData总是缺失一些type_url或value这种字段，看起来应该是Google_Protobuf_Any字段附加的信息，在swift中会解析或打包成@type格式，时间有限，最终先完全自定义结构使用吧，有谁弄研究过TronSigningOutput的json怎么打包出type_url或value这种字段的，也告诉我一声～👌
