### ISSUE TITLE
Send failure with 1857 utxos, Ravencoin, MaxAmount

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#1276]
- Ravencoin
- Wallet had 1857 UTXOs
- Supposedly none of the UTXOs was dust
- Byte fee was 1069, dust limit was 1069*148 = 158212 (0.00158212)
- Available amount was 2382.14664887 RVN.

There is a video of the use case

- RVN is selected; 
- Send;
- destination address is filled (via QR code; RPQiaQFKTu9xqP5uXieKtR8R6D6C6nfQ8V);
- Max amount is entered (likely by tapping max; 2382.14664887).
- About 24 seconds elapse, while the tx is prepared.
- Confirmation screen is shown, with send amount 2379.20818167, fee 2.9384672.

Fee is correct; (1857 * 148 + 1 * 34 + 10) * 1069 = 293846720
Public key: xpub6DSp5CbPiHHfV7yv8Pyf8yqZJrHqMDU1xWdLa4mi2YBWkAjrWZ3gdSh9W7wrw2F9ZhP9PQatUfX3hz6FmqAogbFSYmKb7ydTNDuiP8P4JFD
Own address (one of?): RSmH2oR8xU1BX5zWwnDVk2kv2qiUbhDz46
Destination address is: RPQiaQFKTu9xqP5uXieKtR8R6D6C6nfQ8V has incoming TXs:

The video ends here, but the claim is the user got Dust error.

Identical behaviour on iOS and Android client.

Later 100, then 500 could be sent successfully.
Leter TXs to RPQiaQFKTu9xqP5uXieKtR8R6D6C6nfQ8V, in chunks 100 RVN, 4x500, 279.19583401; on Feb 1.

https://user-images.githubusercontent.com/13562139/106768609-5d0aec80-663c-11eb-9ef6-372be2b985cf.MP4

**Comment by catenocrypt** [comment]
While analyzing this issue, a performance issue was found/fixed, but that is for non-max case, does not apply to this use case.  #1274 .

**Comment by catenocrypt** [comment]
@vcoolish

**Comment by vcoolish** [comment]
Info to add:
Video ends because of some bug on iOS with dust error handling. On Android it shows Dusts error so it means transaction broadcast happened.
@ArtemGoryunov have you found out something on that?

**Comment by catenocrypt** [comment]
It may be that there is some limit/overflow in the encoded transaction; is size; or encoded size field somewhere.  Encoded tx would be more than 256kb in size.  But this is just a guess.
It is quite difficult to reproduce with real UTXOs, it is hard to create such an UTXO set, and the set form this case is no longer unspent.

**Comment by ArtemGoryunov** [comment]
@vcoolish  didn't find. As I understand dust error should not be shown in this case.

**Comment by catenocrypt** [comment]
Cannot be reproduced; root cause was not found; Closing as inconclusive.
See related:  #1278 #1274 #1275 #1282
