### ISSUE TITLE
[Tezos] Expose underlying sign method

### ISSUE THREAD

**Issue by simonmcl** [trustwallet/wallet-core#1283]
**Is your feature request related to a problem? Please describe.**

You have implemented your own local forging for Tezos Operations, but it doesn't include any smart contract operations. I'm currently using remote forge from a private Tezos node, and would like to use WalletCore to manage the wallet creation. However the swift/java code only exposes signing methods that require you to use your own operation classes and local forging methods.

I can't get to the underlying sodium instance, prefix definitions etc, to sign a raw forged hex string.

**Describe the solution you'd like**

I would like to access this function, so that I can supply my own forged data:
```
Data Signer::signData(const PrivateKey& privateKey, const Data& data) {
    Data watermarkedData = Data();
    watermarkedData.push_back(0x03);
    append(watermarkedData, data);

    Data hash = Hash::blake2b(watermarkedData, 32);
    Data signature = privateKey.sign(hash, TWCurve::TWCurveED25519);

    Data signedData = Data();
    append(signedData, data);
    append(signedData, signature);
    return signedData;
}
```

If possible I would like to supply the curve that is passed in also. Our app also supports non-hd wallets, with support for the other curve to generate Tz2 address. I'd like to use this function for all the signing requirements.

**Describe alternatives you've considered**

Nothing else is possible. I've had to also include a dependency to a swift version of Sodium, and bypass the trust wallet signing entirely. I would like to remove this duplicate dependency.

**Additional context**

I would be interested in trying to incorporate more to the local forging in the future, but for right now this is a massive task that I can't spend the time on. Direct access to the signer is a better solution right now

**Comment by hewigovens** [comment]
Does this help you https://github.com/trustwallet/wallet-core/discussions/1252#discussioncomment-294771? probably adding a new operation type to `Tezos.proto` is the best option

**Comment by simonmcl** [comment]
@hewigovens no i've already tired that. If you look at the above function its not just signing with the privateKey, its adding a watermark and running blake2b hash on it. I can't find a way to access any of these functions directly, and this process wouldn't be common knowledge to other devs trying to achieve it either.

Currently devs are forced to duplicate a dependency and read the code to figure out whats needed. Tezos devs will more than likely always need access to this function. Even if full local forging support is added, new types could be added to Michelson that would leave devs stuck until a patch, unless they had direct access to this function.

**Comment by hewigovens** [comment]
we currently don't have plan to support this, feel free to keep your own fork
