### ISSUE TITLE
Memory leak vulnerability in try-catch in walletconsole/Util.cpp

### ISSUE THREAD

**Issue by brutalsavage** [trustwallet/wallet-core#1286]
**Describe the bug**
`buffer` is allocated in `try` block however there is no `delete` call for deallocation in `catch` block for if the exception is thrown after the buffer allocation. If the exception is thrown after `new` there is a memory leak. Potential exception can be thrown from `infile.gcount()` or `infile.close()` .

This is similar to #921 except the missing `delete` is in the `catch` block.

**Comment by catenocrypt** [comment]
@brutalsavage , could you specify the source file location?  thanks

**Comment by brutalsavage** [comment]
here is the vulnerable function https://github.com/trustwallet/wallet-core/blob/883e0e5f65f429526a2f322567365207374158f0/walletconsole/lib/Util.cpp#L68-L95

**Comment by brutalsavage** [comment]
@catenocrypt Hi! Thanks for taking a look at this and fixing it. This vulnerability was detected by our deep learning based vulnerability detection model. Along with the detection, our model also localizes the vulnerability by producing a version of the function with code that contributed to the vulnerability highlighted. We provide the localization output of the vulnerable function identified in this Issue. The intensity of the highlight correspond to how important the code snippet was for vulnerability detection in this function. 
<p align="center">
<img src="https://user-images.githubusercontent.com/33969208/111919270-89998d00-8a5f-11eb-8018-87d2beaacae5.png">
</p>

As part of our university research project we would like to evaluate the usefulness of the model’s localization outputs. You can help us out by clicking one of the options below:

- This vulnerability is a **real** vulnerability and the localization output is **useful**. <a href="https://www.eecg.utoronto.ca/~xiachunq/vulnerability_survey.php?project_issue=wallet-core1286&choice=real_useful" target="_blank">check</a> 
- This vulnerability is a **real** vulnerability but the localization output is **not useful**. <a href="https://www.eecg.utoronto.ca/~xiachunq/vulnerability_survey.php?project_issue=wallet-core1286&choice=real_not_useful" target="_blank">check</a> 
- This vulnerability is **not a real** vulnerability. <a href="https://www.eecg.utoronto.ca/~xiachunq/vulnerability_survey.php?project_issue=wallet-core1286&choice=not_real" target="_blank">check</a>
