### ISSUE TITLE
Can`t trade on DEX with TW

### ISSUE THREAD

**Issue by RomanAnikienko** [trustwallet/wallet-core#1288]
Hi!
Recently, I decided to use DEX in Trust Wallet, but found one problem...
When I try to open an order in TrustWallet via DEX, I get the message "Account not found". (Screenshot attached)

Dear developers, how to solve this issue?
![2021-02-06 14 08 41](https://user-images.githubusercontent.com/953473/107112960-95e9d200-6885-11eb-953a-591d3454cd53.jpg)

**Comment by hewigovens** [comment]
duplicated with https://github.com/trustwallet/wallet-core/discussions/1287
