### ISSUE TITLE
Trust Wallet is not support well for NEAR. Trust钱包对NEAR的支持不佳。

### ISSUE THREAD

**Issue by veneris** [trustwallet/wallet-core#1289]
Phone model: Apple 11;  
System version: 14.3;  
App version: 5.11(5118);  

I imported my account through the mnemonic phrase, but it is different from the account in the NEAR online wallet (wallet.near.org).  
The account in the NEAR online wallet is similar to "*.near" instead of "0x...", and the balance in the Trust wallet is 0, which is wrong.  
On this point, you can refer to Math Wallet.  
In addition, if you import the NEAR watch account, you can see the balance, but only the available balance, not the total balance，and when I try to click on the wallet, the app crashes.

手机型号：Apple 11；  
系统版本：14.3；  
App版本：5.11（5118）;  

我通过助记词短语导入了我的帐户，但它与NEAR在线钱包（wallet.near.org）中的帐户并不是同一个。  
NEAR在线钱包中的帐户地址形式是“ * .near”，而不是“ 0x ...”，并且Trust钱包中的余额为0，这是错误的。  
关于这一点，您可以参考Math Wallet。  
另外，如果您导入NEAR监视帐户，可以看到余额，但只能看到可用余额，而不是总余额，并且当我尝试单击钱包时，应用程序崩溃。

**Comment by hewigovens** [comment]
We have fixed near watch wallet crash, will be released to App Store soon

**Comment by veneris** [comment]
> We have fixed near watch wallet crash, will be released to App Store soon

When will the wallet suffix of ".near" be supported?

**Comment by hewigovens** [comment]
No, we will revisit this when near gets more traction
