### ISSUE TITLE
Ethereum/BSC Multi-Coin WalletConnect signature - chainId problem

### ISSUE THREAD

**Issue by jurosh** [trustwallet/wallet-core#1290]
When using Multi-Coin wallet (connected through WalletConnect) it seems to be impossible to request raw signature for Binance Smart Chain. It always acts like we only use Ethereum chain, and returns chainId as `1`.

By using standalone Ethereum/BSC wallets (WalletConnect ) it does work correctly. Problem is only with Multi-Coin Wallet.

**Steps to reproduce the behavior:**
1. Crete Multi-Coin Wallet
2. Connect to website using WalletConenct
3. Request dapp signature for some request (call of signTransaction)
4. App will not understand that it's using Binance Smart Chain and not Ethereum - user will see ETH, not BNB for send transaction, and might see info about not having funds

**Expected behavior**
Dapp or TW need way to set chain (chainId) when connecting WalletConnect. Alternatively, sendTransaction should set chain based on provided chainId.

**Comment by vikmeup** [comment]
Have you tried passing chain ID on init of the session? Ref: https://docs.walletconnect.org/tech-spec#session-request

**Comment by jurosh** [comment]
> Have you tried passing chain ID on init of the session? Ref: https://docs.walletconnect.org/tech-spec#session-request

 :clap: Wow, Thanks. I must have missed it!

This fix `chainId` in walletConnect connector state.

```
connector.createSession({ chainId: 56 })
```

Going to test transactions now, but I suppose that it will resolve that too.
