### ISSUE TITLE
Browser redirects to link.trustwallet.com/wc (when using WalletConnect) instead of redirecting to TW app

### ISSUE THREAD

**Issue by jurosh** [trustwallet/wallet-core#1299]
We are having troubles with TrustWallet WalletConnect integration on iOS only (on Android there are no issues).

Steps to repro:
- Add Multi-Coin wallet to TrustWallet
- Open web dApp in Chrome/Safari **on mobile iOS directly** (same device as TrustWallet)
- dApp connect to mobile WalletConnect and ask for signature

Instead of asking signature in TrustWallet window, it instead redirects page to https://link.trustwallet.com/wc (so our app is closed)
- After clicking "Open in Trust Wallet" button there, TW app say: `Warning - Deep Link is not supported.` (Also not always, sometimes nothing happens)

**Expected behavior**
Expected would be to redirect into TrustWallet app and ask for confirmation of walletConnect signature. Same as on Android.

**Additional context**
TrustWallet 5.13
iOS 14.4

Note that I am aware that this might not be bug, but possibly misunderstanding of WalletConnect API on iOS... but I cannot find any reasonable help to resolve this so far. And seems it might be issue with TrustWallet, as it works reliably on Android.

**Comment by vikmeup** [comment]
Can you provide video of the issue? I'm not able to understand how to reproduce this issue?

**Comment by jurosh** [comment]
It's happening with active WalletConnect (Multi-Coin Wallet) session (after unlocked wallet = active session):
https://user-images.githubusercontent.com/1630137/108418963-35b64100-7232-11eb-878f-1da5202ed3e2.mp4
- On video you can see how I clicked Button to ask for signature of text..
- It then redirects instead, and after click on "Open in TrustWallet" no signature is asked too..

If that would be helpful, I can prepare some test environment..

**Comment by chuckbergeron** [comment]
We've seen this now when people are connecting their Trust wallets to our PoolTogether dapp via WalletConnect. Connecting the wallet worked, but when they go to send an "Approve DAI" transaction it redirects to the browser with "https://link.trustwallet.com/wc" in the URL bar.

**Comment by fr2p** [comment]
Exactly the same problem here :/

**Comment by hewigovens** [comment]
It looks like web socket reconnecting in latest iOS app is broken, will fix it soon

**Comment by fr2p** [comment]
Any update on this? Thanks in advance

**Comment by vikmeup** [comment]
> Any update on this? Thanks in advance

We expect to push an iOS update today/tomorrow with fixes for this issue.

**Comment by hewigovens** [comment]
Trust iOS 5.15 is released to App Store

**Comment by fr2p** [comment]
Problem solved 👌 thank you 🙏💪

**Comment by jurosh** [comment]
Works great now! Thanks :+1:

**Comment by satishrapid** [comment]
This is again happen in latest version 6.3

**Comment by chichkanov** [comment]
> This is again happen in latest version 6.3

Same issue here
