### ISSUE TITLE
Add support for Stellar

### ISSUE THREAD

**Issue by johnnynanjiang** [TrustWallet/wallet-core#13]
Name: [Stellar](https://www.stellar.org/)
HD Derivation Scheme: BIP44 Coin / `148`
Symbol: `XLM`

Checklist

* [x]  Coin configuration
* * [x]  coin type / decimals
* * [x]  recommended tx block explorer 
           [web viewer](https://www.stellar.org/laboratory/#?network=public)
           [tx example on testnet](https://horizon-testnet.stellar.org/transactions/a6ff5f8f3cddab096780edeee6c0781bbe28f563e9b492cc6bcca4aff1a4293c)
* [x]  Account / Address
* * [x]  derived from bip39 phrases
* * [x]  from public key / string
* * [x]  validation
* [x]  Transaction
* * [x]  serialization
* * [x]  signing
* [x]  C interfaces
* * [x]  Validate generated code in Android and iOS projects
* [x]  Tests
* * [x]  Unit test
* * [x]  integration test ( Java / Swift)

**Comment by hewigovens** [comment]
Append some references
https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0005.md#key-derivation-for-ed25519

**Comment by hewigovens** [comment]
it's done
