### ISSUE TITLE
Broadcast a Tron Transaction

### ISSUE THREAD

**Issue by ansalbeeone** [trustwallet/wallet-core#1311]
Below is my signing output result and how broadcast a transaction using this data

`{"raw_data":{"contract":[{"parameter":{"type_url":"type.googleapis.com/protocol.TransferContract","value":{"amount":1000000,"owner_address":"419c84ec90ef46e68530893cf3229a1dd695b8b457","to_address":"41105e58ce5d754034475f24149ab910f9602bc141"}},"type":"TransferContract"}],"expiration":1608078105411,"ref_block_bytes":"0000","ref_block_hash":"9afbf4c8996fb924","timestamp":1608042105411},"signature":["7204dd578e610164d415f30e57eeb07cab2028a82992c6986f932271796d14b810f85e7b634e0606eefcfe9c76a85663f68a076be8efe7f2355fdb2dc5986f2801"],"txID":"6f3027995c380950442a0f9479ccf31948c7d1134314e333d4b3688799f3d4d1"}`

**Comment by catenocrypt** [comment]
Sorry, context is missing, what is this related to?  What is the issue? What is the question?

**Comment by ansalbeeone** [comment]
below is my code .I want to broadcast transaction using this data

    `       val trc20Contract = Tron.TransferContract.newBuilder()
                .setOwnerAddress("")
                .setToAddress("")
                // 1000
                .setAmount(100)

        val transaction = Tron.Transaction.newBuilder()
                .setTransfer(trc20Contract)
                .build()
        val signingInput = Tron.SigningInput.newBuilder()
                .setTransaction(transaction)
                .setPrivateKey(ByteString.copyFrom("privatekey".toHexByteArray())).build()
        val output = AnySigner.sign(signingInput,CoinType.TRON,Tron.SigningOutput.parser())

        `print("output*******${output.json}")``

**Comment by hewigovens** [comment]
pass valid values to
```kotlin
.setOwnerAddress("")
.setToAddress("")
```
