### ISSUE TITLE
Tron Send Error iOS - How can i signin with this code, from the TronSigningOutput how can I broadcast tron       

### ISSUE THREAD

**Issue by akhilccrb** [trustwallet/wallet-core#1314]
How can i signin with this code, from the TronSigningOutput how can I broadcast tron       

 let contract = TronTransferContract.with {
            $0.ownerAddress = ""
            $0.toAddress = ""
            $0.amount = 1000000
        }

        let input = TronSigningInput.with {
            $0.transaction = TronTransaction.with {
                $0.contractOneof = .transfer(contract)

            }
            $0.privateKey = Data(hex:"") 
        }
        
        

        let output: TronSigningOutput = TronSigner.sign(input: input)

**Comment by hewigovens** [comment]
you need to pass valid values to 
```swift
$0.ownerAddress = from.description
$0.toAddress = to.description
```

**Comment by akhilccrb** [comment]
> you need to pass valid values to
> 
> ```swift
> $0.ownerAddress = from.description
> $0.toAddress = to.description
> ```


Yes, am passed valid tron address, and I got a valid TronSigningOutput  object , then how can I broadcast to blockchain

**Comment by akhilccrb** [comment]
I need to Send TRX, but am stuck at broadcasting in iOS Swift

**Comment by hewigovens** [comment]
see `BroadcastTransaction` in https://developers.tron.network/reference#walletgettransactionsign-1

**Comment by akhilccrb** [comment]
How can we done with trust code sdk ? , so no broadcasting method available right ?
