### ISSUE TITLE
Tron Send Error Trustwallet - wallet code sdk iOS - How can i signin with this code, from the TronSigningOutput how can I broadcast tron, I need to Send TRX, but am stuck at broadcasting in iOS Swift

### ISSUE THREAD

**Issue by akhilccrb** [trustwallet/wallet-core#1315]
How can i signin with this code, from the TronSigningOutput how can I broadcast tron       

 let contract = TronTransferContract.with {
            $0.ownerAddress = "TR8YVwg5HkarEFEs4Db7vXZjsvxS2Q7jJL"
            $0.toAddress = "TA6FznqYJm5MNohJUccmxjdgGz1P4FYjga"
            $0.amount = 1000000
        }

        let input = TronSigningInput.with {
            $0.transaction = TronTransaction.with {
                $0.contractOneof = .transfer(contract)

            }
            $0.privateKey = Data(hex:"privatekey") 
        }
        
        

        let output: TronSigningOutput = TronSigner.sign(input: input)

**Comment by hewigovens** [comment]
try sending `output.json` to tron api: `https://developers.tron.network/reference#walletbroadcasttransaction-1`

**Comment by akhilccrb** [comment]
From output.json we didn't get raw_data_hex , how can I broad cast ?

**Comment by 503943647** [comment]
Has the problem been resolved?
