### ISSUE TITLE
How do I install the TrustWallet.so execution environment on Centos7

### ISSUE THREAD

**Issue by Black52** [trustwallet/wallet-core#1319]
My system is CentOS7.6。 The GCC version is 4.8.5。Can not change the operating system, how to install, thank you。

**Comment by hewigovens** [comment]
please refer to build environment on [Ubuntu](https://github.com/trustwallet/wallet-core/blob/master/.github/workflows/linux-ci.ym), you need to use `clang`

**Comment by Black52** [comment]
> 请参考[Ubuntu](https://github.com/trustwallet/wallet-core/blob/master/.github/workflows/linux-ci.ym)上的构建环境，您需要使用`clang`
I follow the Ubuntu installation and CMAKE keeps getting errors.Do you have a more detailed document of CentOS environment

**Comment by Black52** [comment]
WARNING: Skipped generating Xcode project because the xcodegen tool is not installed.
#### Building... ####
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:17 (message):
  You should use clang compiler


-- Configuring incomplete, errors occurred!
See also "/root/wallet-core/build/CMakeFiles/CMakeOutput.log".
