### ISSUE TITLE
All Caps BCH Addresses Should Be Valid

### ISSUE THREAD

**Issue by eddywm** [TrustWallet/wallet-core#132]
The address below is a valid BCH address and it shoudl pass the test.
`BITCOINCASH:QZDALJYS6GDUFK47D34599D9NAWW8DU6XQRWPWP5SU`

**Comment by vikmeup** [comment]
@alejandro-isaza haha, sounds like we might need to lowercase string for bitcoin cash

**Comment by eddywm** [comment]
@vikmeup We might need to lowercase only for the new `bitcoincash: ` type of address, 
This is because legacy BCH addresses are case sensitive.

**Comment by sudeepb02** [comment]
Hi @eddywm @vikmeup ,

I'd like to take up this issue if no one else is working on it.

**Comment by hewigovens** [comment]
@sudeepb02 thanks, feel free to submit a pull request

**Comment by hewigovens** [comment]
this seems not a convention, let's close thi for now
