### ISSUE TITLE
** TRON Broadcast raw_data_hex is not getting from  output.json** 

### ISSUE THREAD

**Issue by akhilccrb** [trustwallet/wallet-core#1320]
let contract = TronTransferContract.with {
$0.ownerAddress = "TR8YVwg5HkarEFEs4Db7vXZjsvxS2Q7jJL"
$0.toAddress = "TA6FznqYJm5MNohJUccmxjdgGz1P4FYjga"
$0.amount = 1000000
}

    let input = TronSigningInput.with {
        $0.transaction = TronTransaction.with {
            $0.contractOneof = .transfer(contract)

        }
        $0.privateKey = Data(hex:"privatekey") 
    }
    
    

    let output: TronSigningOutput = TronSigner.sign(input: input)

Or how can I generate raw_data_hex , all I want is to send tron in iOS 

**raw_data_hex is not getting from  output.json** 

"{\"raw_data\":{\"contract\":[{\"parameter\":{\"type_url\":\"type.googleapis.com/protocol.TransferContract\",\"value\":{\"amount\":1,\"owner_address\":\"419c84ec90ef46e68530893cf3229a1dd695b8b457\",\"to_address\":\"41521ea197907927725ef36d70f25f850d1659c7c7\"}},\"type\":\"TransferContract\"}],\"expiration\":1615327861580,\"ref_block_bytes\":\"0000\",\"ref_block_hash\":\"9afbf4c8996fb924\",\"timestamp\":1615291861580},\"signature\":[\"21dbbe17149f2d353411e610b90790b09f92d2a64d52ba2b63762c6c880354506f25a6fb6b37be5664535301ab4bf94e8cbac1417825b97f20433d3110a3ea6900\"],\"txID\":\"fbc56ac43a360cb0af1f311fd5b96ea2b8c7f41d83209e53559d62abd0543431\"}"

**Comment by hewigovens** [comment]
stop spamming, `output.json` is ready to submit

**Comment by hewigovens** [comment]
curl example (your data)

```shell
curl --location --request POST 'https://api.trongrid.io/wallet/broadcasttransaction' \
--header 'Content-Type: application/json' \
--data-raw '{
    "raw_data": {
        "contract": [
            {
                "parameter": {
                    "type_url": "type.googleapis.com/protocol.TransferContract",
                    "value": {
                        "amount": 1,
                        "owner_address": "419c84ec90ef46e68530893cf3229a1dd695b8b457",
                        "to_address": "41521ea197907927725ef36d70f25f850d1659c7c7"
                    }
                },
                "type": "TransferContract"
            }
        ],
        "expiration": 1615327861580,
        "ref_block_bytes": "0000",
        "ref_block_hash": "9afbf4c8996fb924",
        "timestamp": 1615291861580
    },
    "signature": [
        "21dbbe17149f2d353411e610b90790b09f92d2a64d52ba2b63762c6c880354506f25a6fb6b37be5664535301ab4bf94e8cbac1417825b97f20433d3110a3ea6900"
    ],
    "txID": "fbc56ac43a360cb0af1f311fd5b96ea2b8c7f41d83209e53559d62abd0543431"
}'
```

```json
{
    "code": "TAPOS_ERROR",
    "txid": "fbc56ac43a360cb0af1f311fd5b96ea2b8c7f41d83209e53559d62abd0543431",
    "message": "5461706f7320636865636b206572726f72"
}
```

**Comment by akhilccrb** [comment]
How can I solve "code": "TAPOS_ERROR", this error

**Comment by la20-pointer** [comment]
> How can I solve "code": "TAPOS_ERROR", this error

i have this error to how can i fix this ???
