### ISSUE TITLE
How to change LTC addres from BIP84 to BIP44?

### ISSUE THREAD

**Issue by subzero1234lx** [trustwallet/wallet-core#1321]
when i import a wallet with nm phrases ltc addres that deriven is incorect and in fact mt ltc balance does not apear in wallet because the addres is diffrent 

i generate a bip39 num and import it to wallet 
LTC addres that trust wallet make is not in list and completely diffrent

**Comment by subzero1234lx** [comment]
steak match riot hood decide rate sign file below little drastic gossip

if insert this words to bip39 the first ltc addres is 

LKGKevjjT8wR4rcjCdwSrGU7tmuaawMivu

but when input this words to trust wallet Ltc addres is 

ltc1qugzy9g6pmhtuk05lxfx0mnuly7pna0muskvgjz

and i search the addreses in bip39 list but this one is not there .

**Comment by subzero1234lx** [comment]
i found it 
in this wallet ltc addres use BIP84 
but every wallet uses BIP44

so how can user change this ?

**Comment by catenocrypt** [comment]
Yes, Trust Wallet uses purpose 84 for LTC address derivation.
Derivation path is defined here:   https://github.com/trustwallet/wallet-core/blob/master/coins.json#L40
84 is used for other Bitcoin forks as well.  There is no way the user can change this.

Which other wallet do you compare against?

**Comment by subzero1234lx** [comment]
exodus use 44 for lite coin 
if i have a wallet in exodus and import it in trust wallet LTC wallet does not come
it is not good 
the user should do this 
or wallet search for addreses that has deposite in it

**Comment by catenocrypt** [comment]
BIP84 is used for Segwit-compliant implementations.  Apparently Exodus does not use segwit addresses.
This is not a bug.
Sorry, I don't think there is a way to import the same LTC non-segwit address into Trust Wallet.
You may just transfer the LTC funds to the segwit address, LTC transfer fees are really low.

**Comment by subzero1234lx** [comment]
cool
tanx man
