### ISSUE TITLE
Dapp browser clipboard support

### ISSUE THREAD

**Issue by ArtemKolichenkov** [trustwallet/wallet-core#1324]
**Describe the bug**
Trust DApp browser does not support usual "copy to clipboard" web functionality via `navigator.clipboard.writeText("example")`, which is probably a similar issue to [this stackoverflow question](https://stackoverflow.com/questions/61243646/clipboard-api-call-throws-notallowederror-without-invoking-onpermissionrequest). This forces developers to use some funky workarounds. 

P.S. Not sure if this is correct repo for this bug report, but [dapp-browser repo](https://github.com/trustwallet/dapps-browser) is archived and haven't been touched for more than a year. Please move this issue to more appropriate place if it exists or tell me where to post it.

**To Reproduce**
I've made a testing page on codesandbox - https://codesandbox.io/s/wgng0
You can open it in Trust DApp browser (the url that's shown in the codesandbox browser section)
As you can see the button that uses `navigator.clipboard` is not working because `navigator.permissions` is not defined, and hence `clipboard-write` permission is denied too.

**Expected behavior**
Expect to use `navigator.clipboard` to copy text to clipboard.

**Comment by catenocrypt** [comment]
This is not correct repo, I will transfer it to correct one.

**Comment by vikmeup** [comment]
Thanks for reporting. We will have this feature enabled in the upcoming build next week.

**Comment by KholdStare** [comment]
@optout21 @vikmeup Where is the correct repo? There was no link provided here to the new issue or the fix.

I am still seeing permission issues on android, and opening https://wgng0.csb.app/ in trustwallet shows that `navigator.permissions` is `false`. Does the WebView have `android.permission.WRITE_EXTERNAL_STORAGE` enabled?

https://stackoverflow.com/questions/61429649/copy-to-clipboard-using-navigator-clipboard-writetext-not-working-in-android-web
