### ISSUE TITLE
Payment link to bypass passcode lock

### ISSUE THREAD

**Issue by Astro33s** [trustwallet/wallet-core#1325]
**Describe the bug**
I found bug on Android version if your Trust Wallet locked with passcode you can bypass it by Coinbase Payment url
You can test the bug on soar.sh they using coinbase as payment url 
**To Reproduce**
Go to soar.sh create order and try to pay with your locked Trust Wallet, it will not ask for passcode.
**Expected behavior**
Bypass passcode lock

Thanks so much hope i helped

**Comment by vikmeup** [comment]
Thank you for reporting your findings, would you be able to file it on https://bugcrowd.com/binance for further details? We currently looking into this your report. 

I'm going to close this issue as it's not relevant to Wallet Core repo.
