### ISSUE TITLE
Unable to find the Boost header files.

### ISSUE THREAD

**Issue by subzero1234lx** [trustwallet/wallet-core#1326]
hi all
when i want to import this project to android studio i got this error :

 Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:42 (find_package)
  CMakeLists.txt:48 (find_host_package)

i use windows :( 
win 10 
android studio 4.1.2

please help

**Comment by catenocrypt** [comment]
Try setting a global BOOST_ROOT env variable, pointing to Boost library folder (the '[boost]' subfolder).
Please note that Windows is not a supported platform.
