### ISSUE TITLE
Android Sample  project  "error: package wallet.core.jni does not exist"

### ISSUE THREAD

**Issue by subzero1234lx** [trustwallet/wallet-core#1333]
after  days trying to open this project (android sample )i got this error 

/home/mahmood/AndroidStudioProjects/wallet-core-master/jni/java/wallet/core/java/AnySigner.java:12: error: package wallet.core.jni does not exist
import wallet.core.jni.CoinType;

my system is ubuntu 20.04 and i installed every thing that in building guid

**Comment by hewigovens** [comment]
Have you run it successfully before? if so try this:
- run `tools/generate-files`
- click `Build / Refresh Linked C++ Projects` in Android Studio

**Comment by subzero1234lx** [comment]
hi
i did not run it successfully before
i arrive to this error after days and some errors 
i run "tools/generate-files"
but it does not work and it say :
"/AndroidStudioProjects/wallet-core-master/tools/build/local does not exist or not complete, fallback to /usr/local
PREFIX: /usr/local"

**Comment by hewigovens** [comment]
I'm afraid we don't support building android lib on Ubuntu, can you please try macOS?
