### ISSUE TITLE
[Tezos] How do I support for custom derivation path?

### ISSUE THREAD

**Issue by dengpan1** [trustwallet/wallet-core#1337]
Does Tezos support custom derived path? According to the "coin.json" description, the path is m/44'/1729'/0'/0'. What if he wants to infinitely derive the child key? Is m/44'/1729'm/0 '/1' ?

**Comment by catenocrypt** [comment]
Trust Wallet does not use multiple accounts, only one address per coin+wallet.
A different implementation using wallet core is free to create custom derivations; see HDWallet class.
Walletconsole utility also has interactive commands for testing derivations using any path.
