### ISSUE TITLE
[AnySigner] remove not used encode method

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1359]
`TWAnySignerDecode` and `TWAnySignerEncode`, not used in the app at all

**Comment by 10gic** [comment]
It's introduced in https://github.com/trustwallet/wallet-core/pull/962, removing it may break others.

**Comment by hewigovens** [comment]
I don't think anyone is using this, even we don't use

**Comment by catenocrypt** [comment]
@madcake , can you confirm it's OK to remove?  Originally it was requested by you.  Thx.

**Comment by madcake** [comment]
confirm
