### ISSUE TITLE
Support THORChain cross-chain swaps

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#1368]
a) Support native THORChain
b) Support primitives for cross-chain swaps

https://docs.thorchain.org

**Comment by catenocrypt** [comment]
Governance proposal for THORChain support ended positively (5.53m vs. 3.32k TWT)
https://governance.trustwallet.com/#/trustwallet/proposal/QmXUPz8WpKZwctPNpuDbfVXvBDnheowwowuDePYKi5a65B

**Comment by catenocrypt** [comment]
ThorChain support has been merged (https://github.com/trustwallet/wallet-core/pull/1369, https://github.com/trustwallet/wallet-core/pull/1439).
ThorSwap support will come a bit later, until it proves its viability a bit more.
On hold for now.

**Comment by hewigovens** [comment]
will reopen this once Thorchain re-enable cross chain swap

**Comment by mhamed-19** [comment]
@hewigovens @catenocrypt 

THORchain has been running swaps for 8+ months, including recently adding LUNA/UST. The volume daily is over $100m+. 

What more are you guys waiting for to add THORChain swaps/functionality into the wallet?

**Comment by hewigovens** [comment]
@mhamed-19 on the roadmap
