### ISSUE TITLE
When add Chia (XCH) support ?

### ISSUE THREAD

**Issue by togiter** [trustwallet/wallet-core#1386]
## Description

official website:  https://www.chia.net/

Name:  Chia 

HD Derivation Scheme:

Symbol:  XCH 

Documentation:
https://github.com/Chia-Network

Reason:
HOT
## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by catenocrypt** [comment]
Currently not planned.
