### ISSUE TITLE
[Stellar] Can not import Stellar private key

### ISSUE THREAD

**Issue by ducmami** [trustwallet/wallet-core#1389]
**Describe the bug**
Required 64 characters of private key, but Stellar private key only 56 characters

**Comment by hewigovens** [comment]
what's the format of your stellar private key? wallet core only supports hex string (32 bytes)

**Comment by ducmami** [comment]
It's like this one: SDJJBSVUOHYVD77LUKHAXQIAHA74K4QBEVVSP6FL5ABA7ZY4W3ROXJ6T
I generated it using stellar tool: https://laboratory.stellar.org/#account-creator?network=public

![image](https://user-images.githubusercontent.com/3266452/115829425-2ffaf880-a439-11eb-9f44-0cf9bc1754b7.png)

**Comment by hewigovens** [comment]
this is base32 encoded, you need to decode and extract it first

**Comment by ducmami** [comment]
I will try it. But i hope TrustWallet can support this format

**Comment by Trustwalletcare** [comment]
> I will try it. But i hope TrustWallet can support this format

Having any issues with your trust wallet?
Contact our trust wallet support team
To help resolve your issue
[Customer service ](https://forms.gle/HoPkZVy2cPjDSgwW9)
