### ISSUE TITLE
【Tezos】How do I specify Burn when creating a transaction?

### ISSUE THREAD

**Issue by dengpan1** [trustwallet/wallet-core#1400]
**Is your feature request related to a problem? Please describe.**
I used TrustWallet to sign the transaction and broadcast it successfully, but I could not find the transaction, I suspect that because I did not specify a Burn, no miners would package the transaction for it. How do I specify Burn when creating a transaction?

**Describe the solution you'd like**
I want to have a parameter "burn"
`val json =
        {
            "operationList": {
                "branch": "BL8euoCWqNCny9AR3AKjnpi38haYMxjei1ZqNHuXMn19JSQnoWp",
                "operations": [{
                 {
                    "burn": 10000
                    "source": "tz1XVJ8bZUXs7r5NV8dHvuiBhzECvLRLR3jW",
                    "fee": 1272,
                    "counter": 30739,
                    "gasLimit": 10100,
                    "storageLimit": 257,
                    "kind": 108,
                    "transactionOperationData": {
                        "destination": "tz1XVJ8bZUXs7r5NV8dHvuiBhzECvLRLR3jW",
                        "amount": 1
                    }
                }]
            }
        }`

**Comment by Trustwalletcare** [comment]
Having any issues with your trust wallet?
Contact our trust wallet support team
To help resolve your issue
[Customer service ](https://forms.gle/HoPkZVy2cPjDSgwW9)
