### ISSUE TITLE
class com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException : Protocol message tag had invalid wire type.

### ISSUE THREAD

**Issue by search110** [trustwallet/wallet-core#1401]
## Description

Name:

HD Derivation Scheme:

Symbol:

Documentation:

Reason:

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by search110** [comment]
你还、使用TRX离线签名后进行广播、返回 com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException : Protocol message tag had invalid wire type信息、是因为信息缺少吗？

**Comment by YingJie0712** [comment]
我也遇到这个问题，请问你是怎么解决的
