### ISSUE TITLE
TurtleCoin Support

### ISSUE THREAD

**Issue by 0xGaming-YT** [trustwallet/wallet-core#1402]
## Description

Name:[TurtleCoin](https://TurtleCoin.lol)

HD Derivation Scheme:BIP44 / 0

Symbol:TRTL

Documentation:docs.turtlecoin.lol

Reason:Because it's one of the fastest crypto.

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by catenocrypt** [comment]
Integration not planned
