### ISSUE TITLE
[Polkadot] Bond failed in batch action

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1414]

**Comment by vikmeup** [comment]
This is the new runtime change for supporting staking or it affects transfers too?

**Comment by catenocrypt** [comment]
For staking, not used by regular transfers.

**Comment by hewigovens** [comment]
hmm, https://polkadot.subscan.io/extrinsic/0xc619b605a31c9562c8f489b9c53c64f5191564ee689c7f541e4a53bfce2c7346?event=4953055-7 Stash/Staked doesn't have extra parameter, only `Account` has account id; probably something wrong in utility:batch

**Comment by hewigovens** [comment]
I figured it out, we should use `utility::batch_all` and stake at least 1 DOT: https://polkadot.subscan.io/extrinsic/4955314-2

**Comment by catenocrypt** [comment]
So `batch_all` instead of `batch`?

**Comment by hewigovens** [comment]
Yes, batch_all is atomic, will tell you why it's failed

**Comment by vikmeup** [comment]
Are we using this batch all for staking or transfers well?

**Comment by hewigovens** [comment]
Only staking
