### ISSUE TITLE
[Bitcoin Cash] Add Support for SLP Tokens

### ISSUE THREAD

**Issue by RowanSkie** [trustwallet/wallet-core#1419]
Hey, can Trust Wallet support SLP tokens?

SLP tokens are the implementation of the Simple Ledger Protocol that is built upon Bitcoin Cash. There are two kinds of SLP tokens, normal ones (called SLP tokens) and NFTs.

**Comment by hewigovens** [comment]
currently we don't have plan to support it

**Comment by hewigovens** [comment]
there is one fork does support it: https://github.com/IFWallet/wallet-core
