### ISSUE TITLE
pro guard query

### ISSUE THREAD

**Issue by mdsaiyad** [trustwallet/wallet-core#1420]
Hi i am using com.trustwallet:wallet-core dependency and its working fine when i am not using proguard but when i use it with proguard it get error.. so i need to know Proguard rules of this library .. PLease let me know waiting for early and positive feedback

**Comment by vikmeup** [comment]
Did you consider to exclude wallet core from pro guard?

**Comment by Trustwalletcare** [comment]
Having any issues with your trust wallet?
Contact our trust wallet support team
To help resolve your issue
[Customer service ](https://forms.gle/HoPkZVy2cPjDSgwW9)
