### ISSUE TITLE
BIP 0021 Support for BEP20

### ISSUE THREAD

**Issue by jjs2484** [trustwallet/wallet-core#1429]
Hi,

Is there some special formatting or prefix to use for BEP20 tokens and the BIP 0021 URI format?.

BIP 0021 URI's work fine for coins like BTC, ETH, LTC, and so on but don't seem to work for any assets on the Binance Smart Chain....

**Comment by catenocrypt** [comment]
What is the exact use case?  You would want Trust Wallet to be opened in Send, with parameters preloaded?  Can you provide a sample URI?

**Comment by jjs2484** [comment]
_You would want Trust Wallet to be opened in Send, with parameters preloaded?_

Exactly.

This URI works for BTC-
bitcoin:1M9P2KpGcuVNK1QtKdM5xTJjKnTSgozhRQ?amount=0.00001965

This does not work for CAKE-
cake:0x43f7B2BB1BD1c7aC865824F7208165aF7D7Fdc91?amount=0.30154835

**Comment by hewigovens** [comment]
please use deep linking for tokens: https://developer.trustwallet.com/deeplinking

**Comment by duythien0912** [comment]
https://link.trustwallet.com/send?asset=c714_tBUSD-BD1&address=0xF7CA188360114559BD05a4f25557290d6b6409fB&amount=1&memo=test

Hi @hewigovens @catenocrypt I was trying to use the above deep link to open BUSD on Trust wallet app but it but it was crash.

Can you guys help.

**Comment by duythien0912** [comment]
Working:
trust://send?asset=c60_t0x6B175474E89094C44Da98b954EedeAC495271d0F&address=0xF7CA188360114559BD05a4f25557290d6b6409fB&amount=1&memo=test

Crash:
trust://send?asset=c714_tBUSD-BD1&address=0xF7CA188360114559BD05a4f25557290d6b6409fB&amount=1&memo=test

**Comment by hewigovens** [comment]
@duythien0912 if you tried to send bep tokens, the address should be staring with bnb1, not ethereum address

**Comment by duythien0912** [comment]
@hewigovens Hi, when I copy the address from metamask it show 0xF7CA188360114559BD05a4f25557290d6b6409fB
What address will be on bnb1

**Comment by duythien0912** [comment]
Btw I also use this deep link for the smart chain but it doesn't work ( don't open send UI just open the app ).

https://link.trustwallet.com/send?asset=c10000714_t0xe9e7cea3dedca5984780bafc599bd69add087d56&address=0x83577cC880E83cc3b5FB15F2adE45f2Cd23EECb2&amount=1&data=test
