### ISSUE TITLE
Need  For A High Level Helper Function  HDWallet.getKeyAt(CoinType, Change, Index)

### ISSUE THREAD

**Issue by eddywm** [TrustWallet/wallet-core#144]
There's a need for a high level function for getting a **private key** at certain change value and certain index.
 `HDWallet.getKeyAt(CoinType, Change, Index)`

The alternative is passing the string path to get the private key but it's kinda look very low level calling
`getKey(m/44/123/34/0/1) ` everywhere on the app side

**Comment by alejandro-isaza** [comment]
This as added already: https://github.com/TrustWallet/wallet-core/blob/7d551c5eaf91c20669e2b64e0b8892be26e318d3/include/TrustWalletCore/TWHDWallet.h#L64

**Comment by hewigovens** [comment]
@eddywm will be available after this merged: https://github.com/TrustWallet/wallet-core/pull/139/files

**Comment by eddywm** [comment]
> @eddywm will be available after this merged: https://github.com/TrustWallet/wallet-core/pull/139/files

Cool 👌
