### ISSUE TITLE
[Codgen] Unable to execute the `codegen/bin/newcoin` on Linux / ruby 2.5.1

### ISSUE THREAD

**Issue by Galadrin** [trustwallet/wallet-core#1444]
**Describe the bug**
I'm trying to add Crypto.org CRO blockchain to TrustWallet, but get the following issue.
here is the patch for the [coins.json](https://github.com/Galadrin/wallet-core/commit/c27200c4c42e7d1b2e8b6592ce8713bef3def20c)

**logs**
```
codegen/bin/newcoin cryptoorg
New coin template for coin 'cryptoorg' requested
Updated file: include/TrustWalletCore/TWCoinType.h  new line: '    TWCoinTypeCrypto.org = 394,
'
Updated file: include/TrustWalletCore/TWBlockchain.h  new line: '    TWBlockchainCosmos = 36,
'
Updated file: src/Coin.cpp  new line: '#include "Crypto.org/Entry.h"
'
Updated file: src/Coin.cpp  new line: 'Crypto.org::Entry Crypto.orgDP;
'
Updated file: src/Coin.cpp  new line: '        case TWCoinTypeCrypto.org: entry = &Crypto.orgDP; break;
'
Generated file src/Crypto.org/Address.h
Generated file src/Crypto.org/Address.cpp
Generated file src/Crypto.org/Entry.h
Generated file src/Crypto.org/Entry.cpp
Generated file src/proto/Crypto.org.proto
Generated file src/Crypto.org/Signer.h
Generated file src/Crypto.org/Signer.cpp
Generated file tests/Crypto.org/AddressTests.cpp
Generated file tests/Crypto.org/SignerTests.cpp
Traceback (most recent call last):
        5: from codegen/bin/newcoin:134:in `<main>'
        4: from codegen/bin/newcoin:37:in `generate_file'
        3: from /usr/share/ruby/erb.rb:876:in `result'
        2: from /usr/share/ruby/erb.rb:876:in `eval'
        1: from (erb):21:in `generate_file'
codegen/bin/newcoin:20:in `format_name': undefined method `gsub' for nil:NilClass (NoMethodError)
```

**Additional context**
OS: CentOS Linux release 8.3.2011

**Comment by catenocrypt** [comment]
I tried with the modified coins.json, and worked without error.
Does it work on the unmodified coins.json?
Might be some issue with the environment (ruby version, etc.)

**Comment by Galadrin** [comment]
> Does it work on the unmodified coins.json?

Tryed with another coin, same issue

> Might be some issue with the environment (ruby version, etc.)
```
ruby --version
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
```

What is the prefered environment ?

**Comment by hewigovens** [comment]
I also noticed the name `Crypto.org` has a `.`, the generated code won't compile

**Comment by Galadrin** [comment]
> @Galadrin there is a bug in `TWAddressTests.cpp.erb`, current workaround is to patch L21 to:
> 
> ```c++
>     auto addr = WRAP(TWAnyAddress, TWAnyAddressCreateWithString(string.get(), TWCoinType<%= format_name(coin) %>));
> ```

Thank's this workaround is what's missing :)
