### ISSUE TITLE
[Cosmos] Serialized tx for new stargate api endpoint

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1446]
From https://v1.cosmos.network/rpc/v0.41.4, `/cosmos/tx/v1beta1/txs` endpoint

**Comment by AbstractAlao** [comment]
Trying to view ATOM balance causes the app to crash

**Comment by vikmeup** [comment]
> Trying to view ATOM balance causes the app to crash

Can you elaborate on the issue? iOS or Android? Which version of the app? Any video?

**Comment by AbstractAlao** [comment]
It's on Android. When I go to view my balance it gets stuck and then crashes. Wallet Core 2.6.10 Version 1.30.4  I'll see if I can provide a video.

**Comment by pitbull123456** [comment]
You will have to use the trust wallet be to view your balance

**Comment by hewigovens** [comment]
will reopen this when we start working it

**Comment by BreakZero** [comment]
hi @hewigovens any advices for learning this to me?

**Comment by hewigovens** [comment]
Just check latest cosmos sdk code and gaia cli
