### ISSUE TITLE
Android cannot download the latest dependency library 

### ISSUE THREAD

**Issue by YuedongMa** [trustwallet/wallet-core#1451]
Why download version 2.6.0 and below is enough, download the latest version 2.6.9 dependency library report 403. I am a newcomer, do I need any additional configuration?
Could not GET 'https://dl.bintray.com/aoeiuv020/maven/com/trustwallet/wallet-core/2.6.9/wallet-core-2.6.9.pom'. Received status code 403 from server: Forbidden

**Comment by catenocrypt** [comment]
Can you post logs/screenshot?

**Comment by YuedongMa** [comment]
I am a newcomer, can you give me the latest aar package or how to generate aar package?Below is the screenshot
![Dingtalk_20210601173417](https://user-images.githubusercontent.com/15702737/120301948-f6eb5900-c2ff-11eb-8c91-04dc423c9b00.jpg)

**Comment by vikmeup** [comment]
Bintray service shutdown on May 1 (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/), it's no longer allow to use older version of Wallet Core.

I would suggest to use latest version instead.

**Comment by madcake** [comment]
https://github.com/trustwallet/wallet-core#android
