### ISSUE TITLE
Tron wallet shows a strange old date

### ISSUE THREAD

**Issue by Shrif88** [trustwallet/wallet-core#1454]
Tron wallet shows a strange old date (Dec 31 1969) in the history of the transaction on iOS. See attached screenshots for more info including app version. Also, I get notifications about some deposits in but they do not show up in the history while I see them in tronscan.org

![IMG_0769](https://user-images.githubusercontent.com/15613849/120740043-70ca4080-c4c0-11eb-8a8d-d8da492f5906.jpg)
![IMG_0770](https://user-images.githubusercontent.com/15613849/120740046-70ca4080-c4c0-11eb-93a0-8fe9adfdd26a.PNG)

**Comment by je153** [comment]
If having any issues with your trust and wallet you can write to trust wallet support to get your issues fixed

Trustwalletinstantsupp@gmail.com

**Comment by Shrif88** [comment]
@je153  the docs says to open an issue here, are you trust wallet team member? 
https://developer.trustwallet.com/wallet-core

**Comment by hewigovens** [comment]
Could you please share your tx hash?

**Comment by Shrif88** [comment]
@hewigovens  I sent you the info in private text, check your telegram.

**Comment by catenocrypt** [comment]
This was a backend issue, resolved (btw, Jan 1, 1970 is the start of the Unix epoch).
