### ISSUE TITLE
I cannot delete the dapp browser cache

### ISSUE THREAD

**Issue by dancespiele** [trustwallet/wallet-core#1463]
**Describe the bug**
When I delete browser cache it doesn't work, I continue see the history and when I access to dapp it still connect automatically to my wallet

**To Reproduce**
`Settings => Preferences => dapp browser => Delete browser cache` (maybe the name are not exactly because I have the app in Spanish)
**Expected behavior**
I shouldn't see the history or connect automatically to the apps after delete the cache

**Additional context**
OS: Android 8.0.0

**Comment by hewigovens** [comment]
probably android webview limit, try to back up and re-install? @madcake or @vcoolish may have better solution

**Comment by vcoolish** [comment]
This is Android client issue. We will improve this in next release
