### ISSUE TITLE
Failed to load resource: the server responded with a status of 401 ()

### ISSUE THREAD

**Issue by happyeric77** [trustwallet/wallet-core#1467]
I am using walletconnect/web3-provider to try to connect to trustwallet ios APP. My config on walletconnect is listed below:
```
try {
    console.log("Log in with connect wallet")
    const provider = await new WalletConnectProvider({
        rpc: {
            56: "https://bsc-dataseed1.binance.org",
        },
    });
    // provider.networkId = 56;
    await provider.enable();
    const web3 = await new Web3(provider);
    console.log(web3)
    resolve(web3)
} catch {
    console.log("Install metamask or use wallet connect")
} 
```
It is normally connected to wallet, but it is not working right. 
So I check the provider and find out that the chain ID is pointing to "1" instead of the BSC chainID "56". see below:
<img width="791" alt="Screen Shot 2021-06-13 at 17 52 08" src="https://user-images.githubusercontent.com/52155607/121801331-cb5a5e00-cc71-11eb-9a80-4ae4c92a8c6c.png">

And following error keep poping up:
```
[Error] Failed to load resource: the server responded with a status of 401 ()  https://mainnet.infura.io/v3(v3, line 0)
```

Am I doing anything not correct?

**Comment by hewigovens** [comment]
This is not really related to wallet core, try this `options`:

```js
{
  rpc: {
    56: "https://bsc-dataseed1.binance.org",
  },
  chainId: 56,
}
```
