### ISSUE TITLE
[BUG] Send THORChain Transaction is failing due to low gas

### ISSUE THREAD

**Issue by thorswapdev** [trustwallet/wallet-core#1475]
**Describe the bug**
Send Tx for `THORChain (Native $RUNE)` is failing due to low gas limit.

Setting the gas limit to `0.02 $RUNE (2000000 ie8 format)` will fix the issue.

**To Reproduce**
1. Send `Native $RUNE` to an address
2. Transaction Fails due to `out of gas in location`

Failing tx: https://viewblock.io/thorchain/tx/B2D7247B19683A140243B352A9D3E40DD8BEAD2A93C12B290A6F518088F7B682

**Expected behavior**
Tx should be sent out without an issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/83067690/123024803-a1a6e280-d3a7-11eb-91c0-67b4e472e544.png)

**Additional Context**
If the transaction is requested from THORSwap (app.thorswap.finance) and signed by TrustWallet, it goes without issue.
Please consider the exact tx request format from THORSwap.

**Comment by hewigovens** [comment]
New iOS build will fix this issue

**Comment by thorswapdev** [comment]
> New iOS build will fix this issue

Sounds great.

**Comment by TrustwalletsupportCommunity** [comment]
Hi

**Comment by hewigovens** [comment]
could you please try latest iOS version (6.1) in App Store?

**Comment by thorswapdev** [comment]
It works now
