### ISSUE TITLE
ALAWASHEER 

### ISSUE THREAD

**Issue by Abdullaha22** [trustwallet/wallet-core#1477]
Hello.  When I send Ethereum to my wallet it suddenly disappears and when I go to the sending notifications it appears to me that Ethereum has been sent to someone else, knowing that I cannot leave my wallet and delete it because I have money in it and I cannot send to drive me to another governorate without Ethereum in my wallet. Please solve the problem and thank you
![Screenshot_٢٠٢١٠٦٢٦-١٤٠٠٥٣_Chrome](https://user-images.githubusercontent.com/86519501/123511847-8d573400-d68c-11eb-947a-d9303c8a7667.jpg)

**Comment by hewigovens** [comment]
please join and ask in https://t.me/trustwallet
