### ISSUE TITLE
Error: errorMissingInputUtxos

### ISSUE THREAD

**Issue by srikanthsrnvs** [trustwallet/wallet-core#1478]
**Describe the bug**
When I attempt to create a valid transactions containing valid input UTXO's, I get an error after signing the transactions saying that I'm missing input UTXOs

**To Reproduce**
Here is my code: 
![Screen Shot 2021-06-27 at 6 38 25 PM](https://user-images.githubusercontent.com/25404406/123561527-ddaac080-d776-11eb-967a-6d03302b96d0.png)
![Screen Shot 2021-06-27 at 6 38 38 PM](https://user-images.githubusercontent.com/25404406/123561535-e4d1ce80-d776-11eb-9095-5d9eb8d92730.png)

### I call the functions using
![Screen Shot 2021-06-27 at 6 39 11 PM](https://user-images.githubusercontent.com/25404406/123561546-f87d3500-d776-11eb-8af0-cce2a70a1075.png)

**Expected behavior**
A transaction should be signed

**Screenshots**
![Screen Shot 2021-06-27 at 6 39 42 PM](https://user-images.githubusercontent.com/25404406/123561558-0af76e80-d777-11eb-892e-8e4193bdcb5d.png)

**Additional context**

**Comment by srikanthsrnvs** [comment]
Keep in mind that the UTXOs do exist. In fact, when I print `input`, I get this which is correct. As you can see, there is a perfect input UTXO in there
![Screen Shot 2021-06-27 at 6 40 55 PM](https://user-images.githubusercontent.com/25404406/123561583-367a5900-d777-11eb-888a-2ecc5aa548c5.png)

**Comment by catenocrypt** [comment]
I don't see obvious reason for the error.  One possible reason can be filtering out dust transactions.  Though with the low byteFee=2 value that is unlikely.
There are many edge case tests in these files:
- https://github.com/trustwallet/wallet-core/blob/master/tests/Bitcoin/TransactionPlanTests.cpp
- https://github.com/trustwallet/wallet-core/blob/master/tests/Bitcoin/TWBitcoinSigningTests.cpp
Look for cases with `Error_missing_input_utxos`, maybe that gives you an idea.

**Comment by srikanthsrnvs** [comment]
I found the issue. For some reason - when I use a legacy address it doesn’t work
When I use a segwit address, it does

Srikanth
________________________________

**Comment by hewigovens** [comment]
what's your wallet core version? could you please try latest? we have a fix for legacy address: https://github.com/trustwallet/wallet-core/pull/1433

**Comment by srikanthsrnvs** [comment]
Most recent version. I am using testnet addresses like: `mjvSp3PweYBqmqpAZxpYZUR3L3sANeyzTz`

**Comment by hewigovens** [comment]
We don’t support testnet addresses

**Comment by srikanthsrnvs** [comment]
That's weird because when I use testnet witness addresses, it works.
