### ISSUE TITLE
what is the Integration Criteria for a new blockchain?

### ISSUE THREAD

**Issue by hench-ye** [trustwallet/wallet-core#1479]
Sorry all, I have read https://developer.trustwallet.com/wallet-core/newblockchain. 
Our blockchain only rank 861 on CoinMarketCap, far below top 30. I think this criteria is too strict for a new blockchain.
I also notice that a proposal should be approved at https://governance.trustwallet.com . But I only see four blockchains have given proposals and 1M TWT is too expensive for us. 
Can you allow us to pull request to trustwallet-core ? We really need this wallet library for wallet developers. Thanks.

**Comment by hewigovens** [comment]
just fork and use your own wallet core version, we don't have a plan to add TOP chain

**Comment by hench-ye** [comment]
Hi hewigovens, thanks for your reply. If We submit a proposal and get approved, is it possible that we can merge into trustcore library ?
