### ISSUE TITLE
Sign tron raw transaction

### ISSUE THREAD

**Issue by rasouliali1379** [trustwallet/wallet-core#1481]
I have a raw transaction in hash and I want to sign it
I want to parse it into `TransferTRC20Contract` object using this line of code 

` val trc20Contract = Tron.TransferTRC20Contract.parseFrom(ByteString.copyFrom(rawTransaction.hexStringToByteArray()))`

but I getting this error 

` com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.`

Am i doing it write?
Is it even possible?
What should I do?

**Comment by hewigovens** [comment]
we don't support this kind of decoding, please check out java-tron to see if that works
