### ISSUE TITLE
HDWallet Support in node js/ npm

### ISSUE THREAD

**Issue by umar-shafiq** [trustwallet/wallet-core#1484]
Hi, As the documentation provided there is HDWallet integration mentioned for javascript. 
https://developer.trustwallet.com/wallet-core/integration-guide/wallet-core-usage

But When I check the wallet-core package for NPM I couldn't find the exports for HDWallet and no functionality of HDWallet is provided?

**Comment by hewigovens** [comment]
we don't support js/ts binding now

**Comment by punithbm** [comment]
@hewigovens  is HDWallet & its functionality is supported now in js/ts?

**Comment by hewigovens** [comment]
@punithbm Yes, see the tests here https://github.com/trustwallet/wallet-core/blob/master/wasm/tests/HDWallet.test.ts
