### ISSUE TITLE
Any String or mnemonic can be used to create wallet with  HDWallet(seedPhrase, passphrase)

### ISSUE THREAD

**Issue by weishirongzhen** [trustwallet/wallet-core#1485]
**Describe the bug**
`val wallet = HDWallet("aa", "")`
Run android sample demo provided by this repo, even use "aa" as seedPhrase, wallet still successfully created.

**To Reproduce**
Run sample demo in this repo, change seedPhrase from legal mnemonic to "aa", run again

**Expected behavior**
wallet should not be  created

**Screenshots**
![pic](https://user-images.githubusercontent.com/54241621/124247029-13bfba00-db54-11eb-9ea8-eb7a84bbc690.png)
**Additional context**

**Comment by catenocrypt** [comment]
Sequence of steps:
1. HDWallet()
2. TWHDWalletCreateWithMnemonic(mnemonic, passphrase)
3. HDWallet::HDWallet(mnemonic, passphrase)
4a. mnemonic_to_seed()
4b. updateEntropy()
5. mnemonic_to_bits() 

Return from mnemonic_to_bits is not checked.

**Comment by weishirongzhen** [comment]
Could this issue push a little bit more 🏃🏃🏃🙌🙌🙌

**Comment by catenocrypt** [comment]
Review pending on #1527, should be merged within a few days at most.

**Comment by mmm0171** [comment]
0xa36fD8fF0524f287422337d99bABdf05923f581B
