### ISSUE TITLE
isValidWord() return is not expected

### ISSUE THREAD

**Issue by weishirongzhen** [trustwallet/wallet-core#1486]
**Describe the bug**
android:
"di" is not show in bip39 words list but,
`val isValidWord = Mnemonic.isValidWord("di")`
isValidWord == true

as TWMenemonic.h file said
```
/// Determines whether word is a valid menemonic word.
TW_EXPORT_STATIC_METHOD
bool TWMnemonicIsValidWord(TWString *_Nonnull word);
```

**Expected behavior**
Mnemonic.isValidWord("di") return false

**Comment by hewigovens** [comment]
Thanks for the report, will fix it soon
