### ISSUE TITLE
Generic UTXO selection 

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1495]
extract code from bitcoin, so that other utxo chains can reuse it
- [ ] Move `TransactionPlan` to `Common.proto`
- [ ] Add common `UTXO` proto model (id/index/amount)
- [ ] Add `TWUTXOSelector` interface (max amount / dust filter / fee)

**Comment by hewigovens** [comment]
will work on this in week or so

**Comment by catenocrypt** [comment]
Being part of #1480

**Comment by hewigovens** [comment]
This one can be closed? new utxo chain should just reuse `InputSelector` @catenocrypt

**Comment by catenocrypt** [comment]
Done with #1650 .
