### ISSUE TITLE
Android：com.trustwallet:wallet-core:2.6.11 is error

### ISSUE THREAD

**Issue by codeFarmL** [trustwallet/wallet-core#1497]
Android：com.trustwallet:wallet-core:2.6.11

Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
Could not find com.trustwallet:wallet-core:2.6.11.
Searched in the following locations:
- https://jcenter.bintray.com/com/trustwallet/wallet-core/2.6.11/wallet-core-2.6.11.pom
- https://repo.maven.apache.org/maven2/com/trustwallet/wallet-core/2.6.11/wallet-core-2.6.11.pom
- https://dl.google.com/dl/android/maven2/com/trustwallet/wallet-core/2.6.11/wallet-core-2.6.11.pom
- https://jitpack.io/com/trustwallet/wallet-core/2.6.11/wallet-core-2.6.11.pom
Required by:
project :app

Why is that？

This version is fine.
com.trustwallet:wallet-core:2.6.1.

**Comment by hewigovens** [comment]
new versions are hosted on github: https://github.com/trustwallet/wallet-core/packages/700258

**Comment by codeFarmL** [comment]
maven {
            url "https://jitpack.io"
        } 

The maven doesn't work anymore?

**Comment by codeFarmL** [comment]
android：

 implementation(name: 'wallet-core-2.6.11', ext: 'aar')

Straight away?
