### ISSUE TITLE
BNB Transaction error

### ISSUE THREAD

**Issue by rasouliali1379** [trustwallet/wallet-core#1498]
I'm trying to send 0.01 bnb to an address and I'm generating a raw transaction using this example 
[https://github.com/trustwallet/wallet-core/blob/master/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/binance/TestBinanceTransactionSigning.kt](url)

when I'm trying to broadcast the transaction in this link 

[https://bscscan.com/pushTx](url)

I'm getting this error 

`Unable To Broadcast Txn : {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"rlp: too few elements for types.LegacyTx"}}`

This is my code 

`       val privateKey =
        PrivateKey("private_key".toHexBytes())
        val address = BINANCE.deriveAddress(privateKey)
        Log.e("address", address.toString())
        val publicKey = privateKey.getPublicKeySecp256k1(true)

        val signingInput = Binance.SigningInput.newBuilder()
        signingInput.chainId = "Binance-Chain-Nile"
        signingInput.accountNumber = 4355033
        signingInput.sequence = 1

        signingInput.privateKey = ByteString.copyFrom(privateKey.data())

        val token = Binance.SendOrder.Token.newBuilder()
        token.denom = "BNB"
        token.amount = 10000

        val input = Binance.SendOrder.Input.newBuilder()
        input.address = ByteString.copyFrom(AnyAddress(publicKey, BINANCE).data())
        input.addAllCoins(listOf(token.build()))

        val output =  Binance.SendOrder.Output.newBuilder()
        output.address = ByteString.copyFrom(AnyAddress("bnb16urwafzcvusuw7kdvc8ptaay55zjnw0jeccvr2", BINANCE).data())
        output.addAllCoins(listOf(token.build()))

        val sendOrder = Binance.SendOrder.newBuilder()
        sendOrder.addAllInputs(listOf(input.build()))
        sendOrder.addAllOutputs(listOf(output.build()))

        signingInput.sendOrder = sendOrder.build()

        val sign: SigningOutput = AnySigner.sign(signingInput.build(), BINANCE, SigningOutput.parser())
        val signBytes = sign.encoded.toByteArray()
        Log.e("tx", signBytes.toHex())`

Is there any problem in my code?

**Comment by catenocrypt** [comment]
The sample is for Binance chain, not Binance Smart Chain, while you tried to push to BSC.  BC and BSC are quite different.  For BSC, it is very similar to Ethereum; see the Eth samples.
