### ISSUE TITLE
How can I resolve "conflicting names: libprotobuf.a." without use_framework!

### ISSUE THREAD

**Issue by tuannm2** [trustwallet/wallet-core#1506]
install pod "TrustWalletCore"

<img width="1213" alt="Screen Shot 2021-07-08 at 11 32 07" src="https://user-images.githubusercontent.com/85265921/124863060-a642dc00-dfe0-11eb-977d-6b64c4b68566.png">

Here is my Podfile:
<img width="860" alt="Screen Shot 2021-07-08 at 11 38 33" src="https://user-images.githubusercontent.com/85265921/124863286-08034600-dfe1-11eb-9efc-93e50bd98bfa.png">

**Comment by hewigovens** [comment]
try latest `2.6.x` version

**Comment by tuannm2** [comment]
> try latest `2.6.x` version

Thank you for your answer.

I saw the lastest version on doc is 2.6.11 and I try install this version. But I got this error :))

<img width="1218" alt="Screen Shot 2021-07-08 at 11 48 51" src="https://user-images.githubusercontent.com/85265921/124864161-a7750880-dfe2-11eb-94ba-a8ef5091769d.png">

**Comment by hewigovens** [comment]
what's your deployment target? it needs iOS 12.0+

**Comment by tuannm2** [comment]
> what's your deployment target? it needs iOS 12.0+

Thank you very much. It work 👌👌👌
