### ISSUE TITLE
Fully Open Source Wallet & Release On F-Droid

### ISSUE THREAD

**Issue by trymeouteh** [trustwallet/wallet-core#1513]
https://walletscrutiny.com/android/com.wallet.crypto.trustapp/

https://f-droid.org/

Please make this app fully open source and release the app onto the F-Droid app repository.

**Comment by AbakumovAlexandr** [comment]
Request: 'Please fully open your source code'.
Result: 'Issue closed the same day without ANY reasoning'.

Takeaway: 'We are so trustworthy that we will not bother providing any proofs. Our proof is our brand name (TRUSTWallet), so just trust us.'

Nice :D

**Comment by 48-mq** [comment]
@vikmeup @rkokhatskyi @satoshiotomakan @Milerius Thoughts?

**Comment by Buld1n** [comment]
So?

**Comment by satoshiotomakan** [comment]
@ghost @Buld1n This issue is not related to the wallet core repository

**Comment by Buld1n** [comment]
> @ghost @Buld1n This issue is not related to the wallet core repository

So, are you confirming that this is not an open-source product?
