### ISSUE TITLE
iOS 14.6: impossible to connect Trustwallet  'watch' wallet with an app using WalletConnect

### ISSUE THREAD

**Issue by elena-zh** [trustwallet/wallet-core#1536]
**Describe the bug**
I have imported my Ethereum wallet into the Trustwallet app using 'Address' option, so I can use it in the 'watch' only mode.
When I try to connect an app using WalletConnect with the Trustwallet installed in an iPhone with iOS 14.6, nothing happens. I mean 'QR Scan Code' screen is closed and that it.

**To Reproduce**
1. Install TrustWallet on an iPhone (in my case iPhone 12 mini) with 14.6 iOS
2. Import an Ethereum wallet using 'Address' option 
3. Try to connect the TrustWallet with an app using WallectConnect

**Expected behavior**
An explanation modal  'This is watch-only wallet' should appear (like it works in Android)

**Screenshots**
![image](https://user-images.githubusercontent.com/70885163/126127775-1cdd6a94-0602-4a2e-9eb3-854789a6b069.png)

**Additional context**
-

**Comment by hewigovens** [comment]
Thanks for the report, will address this soon

**Comment by hewigovens** [comment]
Please update to latest App Store version
