### ISSUE TITLE
Can't find "HT" Symbol.

### ISSUE THREAD

**Issue by wcj233** [trustwallet/wallet-core#1538]
## Description
Currently, I pod 'TrustWalletCore' in my project with Swift, the version of TrustWalletCore is 2.6.11. Then I want to use ECO Chain in my project, but I can't find 'HT' symbol from TWCoinType. From this link(https://github.com/trustwallet/wallet-core/blob/master/docs/registry.md), it should support HT symbol, but I'm not sure how to get it.

Name:
[ECO Chain](https://www.hecochain.com/en-us)

Symbol:
[HT](https://github.com/trustwallet/wallet-core/blob/master/docs/registry.md)

**Comment by hewigovens** [comment]
just merged, will be available after version 2.6.16

**Comment by wcj233** [comment]
Thank you very much for your reply.  Could you please tell me when will the new version be released?
