### ISSUE TITLE
Regarding the tron signature issue, please take a look.

### ISSUE THREAD

**Issue by onesand** [trustwallet/wallet-core#1539]
Tron.TransferContract transferContract = Tron.TransferContract.newBuilder()
                        .setOwnerAddress("TQeSTkjmLuiusocywhedvcNBbok2xVDp8A")
                        .setToAddress("TWiPRXR5wXSEP54xqaRyWaG2mX2P1uKwZi")
                        .setAmount(100000)
                        .build();

http request from https://nile.trongrid.io/wallet/getnowblock ...

Gson gson = new Gson();
NowBlockBean blockBean = gson.fromJson(response.body(),NowBlockBean.class);

Tron.BlockHeader blockHeader = Tron.BlockHeader.newBuilder()
                         .setTimestamp(System.currentTimeMillis())
                         .setTxTrieRoot(ByteString.copyFrom(blockBean.getBlock_header().getRaw_data().getTxTrieRoot().getBytes()))
                         .setParentHash(ByteString.copyFrom(blockBean.getBlock_header().getRaw_data().getParentHash().getBytes()))
                         .setWitnessAddress(ByteString.copyFrom(blockBean.getBlock_header().getRaw_data().getWitness_address().getBytes()))
                         .setNumber(blockBean.getBlock_header().getRaw_data().getNumber())
                         .setVersion(blockBean.getBlock_header().getRaw_data().getVersion())
                         .build();

Tron.Transaction transaction  = Tron.Transaction.newBuilder()
                         .setTimestamp(System.currentTimeMillis())
                         .setTransfer(transferContract)
                         .setExpiration(time + 10 * 60 * 60 * 1000)
                         .setBlockHeader(blockHeader)
                         .build();

Tron.SigningInput signingInput = Tron.SigningInput.newBuilder()
                          .setTransaction(transaction)
                          .setPrivateKey(ByteString.copyFrom(privateKey.data())).build();

Tron.SigningOutput output = AnySigner.sign(signingInput, CoinType.TRON, Tron.SigningOutput.parser());

Then,output.getJson() retrun:

{"raw_data":{"contract":[{"parameter":{"type_url":"type.googleapis.com/protocol.TransferContract","value":{"amount":100000,"owner_address":"41a0fd3834ad94617d1a3db5ecb60af17990a2cfb6","to_address":"41e38d1a0b9455bb114f053bc45f363c42a2246bf9"}},"type":"TransferContract"}],"expiration":1626954960000,"ref_block_bytes":"ab39","ref_block_hash":"88b9b73c1d16eac4","timestamp":1626918964062},"signature":["9503369474c405133b1fb8c52a1c626bb6654bbccba134a8fd311031f57148477446025771b1605ece12b2ab919b168449e9b99a0dabd939e9830a5338c319f401"],"txID":"86bf572889cb11f5250ce426a0669f6ee6461eed63d34e889e189ae8853d6727"}

And,https://nile.trongrid.io/wallet/broadcasttransaction... return:

{"code":"TAPOS_ERROR","txid":"86bf572889cb11f5250ce426a0669f6ee6461eed63d34e889e189ae8853d6727","message":"5461706f7320636865636b206572726f72"}

Decode message : Tapos check error

**Comment by hewigovens** [comment]
duplicated with https://github.com/trustwallet/wallet-core/issues/1532
