### ISSUE TITLE
The ecdsa.c file does not check sig array size

### ISSUE THREAD

**Issue by whodoyouremember** [TrustWallet/wallet-core#154]
The ecdsa.c file does not check sig array size。The ecdsa_sig_to_der function in the ecdsa.c file，Array index "i" should be used before restriction checking，If the array is larger than 64 bits, because there is no limit on the size of the array, a buffer overun vulnerability can be created.

**Comment by alejandro-isaza** [comment]
Can you provide an example of a set of input parameters that would cause this problem?

**Comment by hewigovens** [comment]
close this for now, we only call `ecdsa_sig_to_der` from `PrivateKey::signAsDER`, and `sig` is created from `ecdsa_sign_digest` which should always be 64 bytes if it's succeeded.
