### ISSUE TITLE
Support Taproot

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#1542]
**Taproot** is a next major Bitcoin softfork.  It is expected to get activated on mainnet in mid-November.

Tasks:
- [x] Support sending to Taproot addresses (should not be enabled before receive support in popular wallets)  (mostly done)
- [ ] Schnorr signature support
- [ ] Taproot primitives in scripts

/later:/
- [ ] Create Taproot address, support sending from Taproot address (receive)

Docs:
* [BIP 340: Schnorr Signatures](https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki0)
* [BIP 341: Taproot: SegWit version 1 spending rules](https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki0)
* [BIP 342: Validation of Taproot Scripts](https://github.com/bitcoin/bips/blob/master/bip-0342.mediawiki0)
* [BIP 350: Bech32m format for v1+ witness addresses](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki0)

**Comment by catenocrypt** [comment]
Segwit v1 support, with Bech32m encoding is already supported, see:

https://github.com/trustwallet/wallet-core/pull/1345

https://community.trustwallet.com/t/taproot-support-send-already-supported/213127

**Comment by catenocrypt** [comment]
Schnorr support in the included Trezor library:
- A schnorr version is included (from longer time), bot used
- A wc-specific variation exists for Zilliqa
- Current latest Trezor contains Bitcoin ABC Schnorr, which is a different variant
- BTC Schnorr support is work-in-progress on in Trezor, see:

- https://github.com/trezor/trezor-firmware/issues/1534  Issue: Re-enable secp256k1-zkp and make it default
- https://github.com/trezor/trezor-firmware/pull/1678  PR
- https://github.com/trezor/trezor-firmware/issues/1656  Issue: Support Taproot

We should include Trezor version once it is availble.

**Comment by mmm0171** [comment]
0xa36fD8fF0524f287422337d99bABdf05923f581B
