### ISSUE TITLE
Solana Staking in Trust Wallet

### ISSUE THREAD

**Issue by sggts04** [trustwallet/wallet-core#1546]
**Describe the solution you'd like**
Support for Solana Staking on Trust Wallet. Solana ecosystem has been booming lately and Solana + SOL Staking has been added to most major exchanges and wallets.
Even Exodus supports Solana Staking from wallet, would love to see the feature in trust wallet!

**Comment by hewigovens** [comment]
Thanks for the suggestion, we will consider it
