### ISSUE TITLE
[Android] UnsatisfiedLinkError empty/missing DT_HASH/DT_GNU_HASH

### ISSUE THREAD

**Issue by burgessjp** [trustwallet/wallet-core#1556]
**Describe the bug**
java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/xxx.bulm-tG49UICSQHANS7r6qtAk4g==/base.apk!/lib/arm64-v8a/libTrustWalletCore.so" (new hash type from the future?)

**Additional context**
I recently encountered a crash on some devices and it recurs on these devices。I don't know the reason now, need help。

**Sdk Version**: 2.6.12
### App Info
**minSdkVersion**: 23
**targetSdkVersion**:29

**Comment by hewigovens** [comment]
@madcake @vcoolish do you guys have any thought on this?

**Comment by vcoolish** [comment]
Some version of Android has bugs with PakcageManager, which doesn't update the so libs while updating the apk file.
Do you use app bundle or apk?

**Comment by burgessjp** [comment]
> Some version of Android has bugs with PakcageManager, which doesn't update the so libs while updating the apk file.
> Do you use app bundle or apk?

@vcoolish apk,include arm64-v8a and armeabi-v7a

**Comment by mmm0171** [comment]
.

**Comment by James22-crypto** [comment]
Still having issues with your wallet?

**Comment by burgessjp** [comment]
> Still having issues with your wallet?

yes

**Comment by James22-crypto** [comment]
Contact their automated service on here so they can confirm your account with the issue and resolve this issue for you immediately.
 https://forms.gle/VbTkY8mBQqMme6Ja6

**Comment by James22-crypto** [comment]
I had the same issue and was solved when I contacted their instant replying support

**Comment by SamaKaur** [comment]
Describe the bug
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: library "libTrustWalletCore.so" not found

Additional context
App is been crashing when initializing wallet with  
init {
        System.loadLibrary("TrustWalletCore")
    }

Crashlytics has been reporting this issue recently.

Sdk Version: 2.8.0

App Info
minSdkVersion: 26
targetSdkVersion: 33

Device 
Nokia C20
