### ISSUE TITLE
Allow import mnemonic phrase for all coins

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/wallet-core#156]
Currently, we have a call that you can pass coins.
```
createWallet(password: String, coins: [CoinType])
``` 

But import only has ability to import one specific coin, it needs to support passing coins
```
func `import`(mnemonic: String, encryptPassword: String, coin: CoinType) throws
```

**Comment by alejandro-isaza** [comment]
A mnemonic string will support any coin. Just call `getAccount`
