### ISSUE TITLE
Support signing json protobuf for Harmony/Zilliqa/Solana/Algorand

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1564]

**Comment by catenocrypt** [comment]
Would it be possible to support json signing for all chains?  (all with AnySign)

**Comment by hewigovens** [comment]
Not all chains implement AnySigner.signJSON method, we could do all non utxo chains

**Comment by gituser** [comment]
Would be nice to have support for `signJSON` method for all chains, it should be trivial to add this.
