### ISSUE TITLE
Mobile browser dapp wallet connect redirects to link.trustwallet.com/wc instead of trust wallet (only in ios not in android)

### ISSUE THREAD

**Issue by satishrapid** [trustwallet/wallet-core#1565]
Facing troubles with TrustWallet WalletConnect integration on iOS only.

Steps to reporduce:
1)add ethereum wallet in trust wallet
2)Open web dApp in Chrome/Safari on mobile iOS directly (same device as TrustWallet)
3)connect dapp with mobile wallet connect and do send transaction.

Expected behavior:
trust wallet should open for confirm the transaction

Actual behavior:
app redirect to    ###https://link.trustwallet.com/wc

Additional context
trust wallet: 6.3

![Screenshot 2021-08-09 213105](https://user-images.githubusercontent.com/82157294/128737529-9fecc99f-17b6-4919-a93f-94f95baa54f2.png)
![Screenshot 2021-08-09 213136](https://user-images.githubusercontent.com/82157294/128737561-d841bc2d-bd4b-4e62-860e-4b6666a4dc14.png)

**Comment by vikmeup** [comment]
This is an issue with Apple handling Universal Linking incorrectly in some cases, WalletConnect team is aware of this across all wallets that are using WalletConnect on iOS.

If you press open in Trust Wallet - it will open properly.
