### ISSUE TITLE
Synchronize BitcoinCash().address(string:) and BitcoinCashAddress(string:) output

### ISSUE THREAD

**Issue by dstranz** [TrustWallet/wallet-core#157]
Swift library expose 2 methods to create BCH Address:
- BitcoinCash().address(string:) 
- BitcoinCashAddress(string:) 

## Expected Behavior

Have equal output from each of them.

## Current Behavior

- BitcoinCash().address(string:) have a code that is prepending HRP string (bitcoincash:).
- BitcoinCashAddress(string:) doesn't have this code and returns nil for addresses without HRP.

## Possible Solution

Add the code prepending HRP directly in TWBitcoinCashAddressInitWithString method as it is available in C++ implementation CashAddress::CashAddress(const std::string& string) from CashAddress.cpp.

## Steps to Reproduce (for bugs)

This will pass:
```
        XCTAssertEqual(
            "bitcoincash:prm3srpqu4kmx00370m4wt5qr3cp7sekmcksezufmd",
            BitcoinCash().address(string: "prm3srpqu4kmx00370m4wt5qr3cp7sekmcksezufmd")?.description
        )
```

This will fail:
  ```
      XCTAssertEqual(
            "bitcoincash:pqx578nanz2h2estzmkr53zqdg6qt8xyqvwhn6qeyc",
            BitcoinCashAddress(string: "prm3srpqu4kmx00370m4wt5qr3cp7sekmcksezufmd")?.description
        )
```

**Comment by hewigovens** [comment]
Different purposes.

BitcoinCash.address is more high level, it accepts both cash addr and legacy address string.

BitcoinCashAddress is low level, it expects full cash addr.
