### ISSUE TITLE
Not able to use android example in android studio

### ISSUE THREAD

**Issue by Ak23598** [trustwallet/wallet-core#1577]
**Describe the bug**

**I get this error**

 error: cannot find symbol
    public static <T extends Message> T plan(Message input, CoinType coin, Parser<T> parser) throws Exception {
                                                            ^
  symbol:   class CoinType
  location: class AnySigner

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by hewigovens** [comment]
Thanks for the report, will fix it soon
