### ISSUE TITLE
Build for 64bit google

### ISSUE THREAD

**Issue by trustwalletvn** [trustwallet/wallet-core#1584]
This app only has 32-bit [x86] native libraries. Beginning August 1, 2019 Google Play store requires that all apps that include native libraries must provide 64-bit versions. For more information, visit https://g.co/64-bit-requirement
Affected Modules: trustwalletcore

**Comment by vikmeup** [comment]
@trustwalletvn can you stop using Trust Wallet branding/trademark?

**Comment by trustwalletvn** [comment]
ok. no problem

**Comment by trustwalletvn** [comment]
> 
> 
> @trustwalletvn can you stop using Trust Wallet branding/trademark?

ok
No problem

**Comment by trustwalletvn** [comment]
WTF you report my website ?

> 
> 
> @trustwalletvn can you stop using Trust Wallet branding/trademark?

**Comment by hewigovens** [comment]
https://github.com/trustwallet/wallet-core/issues/1589
