### ISSUE TITLE
ios-xcframeworks build failed due to one commit

### ISSUE THREAD

**Issue by weishirongzhen** [trustwallet/wallet-core#1595]
**Describe the bug**
ios-xcframeworks build failed due to this commit, when I revert it ,build pass 
https://github.com/trustwallet/wallet-core/commit/79d51466772663b4d84917a9c6cb777358f6aa49
**To Reproduce**
run ./tool/ios-xcfraeworks

**Expected behavior**
build frameworks success

**Additional context**
+------+-----------------------------+-------------+
|                 fastlane summary                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 1    | default_platform            | 0           |
| 2    | Switch to ios               | 0           |
|      | swift_protobuf_xcframework  |             |
|      | lane                        |             |
| 3    | create_xcframework          | 77          |
| 4    | Switch to ios               | 0           |
|      | core_xcframework lane       |             |
| 💥   | create_xcframework          | 14          |
+------+-----------------------------+-------------+

[10:01:55]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

/opt/homebrew/Cellar/fastlane/2.191.0/libexec/gems/fastlane-2.191.0/fastlane_core/lib/fastlane_core/ui/interface.rb:153:in `shell_error!': \e[31m[!] Exit status of command 'set -o pipefail && xcodebuild -workspace "TrustWalletCore.xcworkspace" -scheme "WalletCore" SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES OTHER_CFLAGS="-fembed-bitcode" BITCODE_GENERATION_MODE="bitcode" ENABLE_BITCODE=YES -destination "generic/platform=iOS" -archivePath "build/archives/0_WalletCore.xcarchive" archive | tee '/Users/wei/Library/Logs/fastlane/xcbuild/2021-08-24/27545/xcodebuild.log' | xcpretty --color --simple' was 65 instead of 0. (FastlaneCore::Interface::FastlaneShellError)

**Comment by hewigovens** [comment]
@weishirongzhen could you please try branch `h/remove-types`?

**Comment by weishirongzhen** [comment]
> @weishirongzhen could you please try branch `h/remove-types`?
build success on this branch
