### ISSUE TITLE
Pub Key generation failing across various test vectors

### ISSUE THREAD

**Issue by saltyskip** [trustwallet/wallet-core#1598]
**Describe the bug**
Pubkey generation seems to be failing on version 2.6.19 in various test vectors in my local project

**To Reproduce**
A surefire way to reproduce this seems to be using a foreign language mnemonic, howeverI found another ethereum pubkey test vector below

**Expected behavior**
Should be able to get pubkeys without crashing

attaching Swift Test Vectors below

```
func testEthXpubKey() throws {
        let xpubAddr2 = HDWallet.getPublicKeyFromExtended(
                extended: "xpub6C6jY27yfexxBjyzUWQGeA23ZWoH4VjWfPfhFYVEmJb2Rw7mWWi4SNXUAMgk2evZvznU49R5rtHdLZWuh7Z994g36j1v3uGXvawV2oqA8P8",
                coin: .ethereum,
                derivationPath: DerivationPath(purpose: .bip44, coin: CoinType.ethereum.slip44Id, account: 0, change: 0, address: 0).description
            )!

        debugPrint(CoinType.ethereum.deriveAddressFromPublicKey(publicKey: xpubAddr2))
        debugPrint("helllo")
    }
```

```
    func testESMnemonic() throws {
        let mnemonic = ["llanto", "radical", "atraer", "riesgo", "actuar", "masa", "fondo", "cielo", "dieta", "archivo", "sonrisa", "mamut"]
        guard let wallet = try? Wallet(mnemonic: mnemonic, chain: .bitcoin) else {
            XCTAssert(false)
            return
        }
        // let address = BlockchainAddressGenerator.shared.getDefaultBlockchainAddress(from: wallet, x: 0, y: 0, chain: .bitcoin)
        // XCTAssertEqual(address, "1BhAZYcgpytdeNvf9mP6obAwMyKLY8C5Kk")

        let xPub = wallet.getExtendedPubKey(for: .bitcoin)
        XCTAssertEqual(xPub, "xpub6Cq43Vqyvb2DwXzjzNeMpPuxXRCN1WnmRCmYLPaaSv2XZXM2yCwUHpWEyB3zQ3FGCQsvY21gecMaQR7b2zhhgiHnjzDYpKCE2LACueaSMuR")
    }
```

**Comment by hewigovens** [comment]
There are two issues here after checking old 2.6.9 version

1. Can't get Ethereum public key from xpub, I don't think we support this before
2. Only validates mnemonic words from bip39 english dict, this was introduced in 2.6.17 ( https://github.com/trustwallet/wallet-core/pull/1527)

will create two separate issues

**Comment by hewigovens** [comment]
tracked in https://github.com/trustwallet/wallet-core/issues/1599 and https://github.com/trustwallet/wallet-core/issues/1600

**Comment by catenocrypt** [comment]
Please see https://github.com/trustwallet/wallet-core/issues/1607#issuecomment-912046867 .

**Comment by catenocrypt** [comment]
@saltyskip , starting from v. 2.6.24, you will need the checked=false in HDWallet creation for non-English passphrases, no other change needed.

`TWHDWalletCreateWithMnemonicCheck`
https://github.com/trustwallet/wallet-core/blob/master/include/TrustWalletCore/TWHDWallet.h#L39
PR #1616

**Comment by saltyskip** [comment]
Thank you very much @catenocrypt! I upgraded to 2.6.25 and all my vectors pass now. This is a comprimise that works great for me, I appreciate it a lot for you guys to look into this.
