### ISSUE TITLE
Adding dependency to project

### ISSUE THREAD

**Issue by piotrkst** [TrustWallet/wallet-core#16]
Cannot add the dependency to the project:

```
dependencies {
    compile 'com.trustwallet.walletcore:walletcore:0.4.0'
}

```

Got an error:
`Failed to resolve: com.trustwallet.walletcore:trust-walletcore:0.4.0
`

Cannot really find the repository that contains it.

**Comment by alejandro-isaza** [comment]
Yes, we have been having trouble uploading to OSSRH. Will try to resolve soon. In the meantime please install to your local maven repo.

**Comment by alejandro-isaza** [comment]
Ok, should be working now. Let me know if you still have problems.
