### ISSUE TITLE
cpp equivalant method of hex.EncodeToString

### ISSUE THREAD

**Issue by Hazhir007** [trustwallet/wallet-core#1623]
what is equivalent of  keyHex := hex.EncodeToString(TWDataGoBytes(keyData)) in cpp?

//keyData is private key

here is the source code of the sample given in the main website : https://developer.trustwallet.com/wallet-core/integration-guide/server-side

**Comment by hewigovens** [comment]
Please check `hex` function in `HexCoding.h`
