### ISSUE TITLE
Add Mnemonic -> Address Tests For All The Integrations

### ISSUE THREAD

**Issue by eddywm** [TrustWallet/wallet-core#163]
`Mnemonic - > Address derivation tests` are great way to ensure the all derivation cycle [ `Mnemonic Phrase `- > `Bip39 Seed` - > `Extended Key` - >` Private Key `- > `Public Key` - > `Address` ] was implemented correctly and users funds won't be sent to wrong addresses.

If these tests are correct, we have the certainty that the  `Private Keys `and `Public Keys` were also correct. That's the reason we'll be adding them for each integration

**Comment by vikmeup** [comment]
@eddywm add to the checklist item for the PR, make sure everyone follow that rule before PR is merged for blockchain integration.

**Comment by hewigovens** [comment]
Added
