### ISSUE TITLE
Add KCC support

### ISSUE THREAD

**Issue by lingyun92** [trustwallet/wallet-core#1640]
## Add KCC(KuCoin Community Chain) support

TokenName: [KuCoin Token](https://kucoin.com/)
ChainName: [KCC](http://kcc.io/)

Symbol: KCS
Documentation: https://docs.kcc.io/
Reason: KCC is a high-performance and decentralized public chain built by KCS’ and KuCoin’s fan communities.
Developed based on go-there with the purpose of providing community users with a higher-speed, convenient and low-cost blockchain user experience.

Fully compatible with Ethereum and ERC-20 smart contracts, extremely low costs in migration.

**Comment by hewigovens** [comment]
thanks for reaching out, we will consider add it later, closing for now

**Comment by lingyun92** [comment]
Thanks, 非常感谢。
