### ISSUE TITLE
Lost POA Network support using WalletConnect

### ISSUE THREAD

**Issue by yadatashy** [trustwallet/wallet-core#1642]
**Describe the bug**
After updating to TrustWallet iOS v 6.5(6522), we cannot connect to TrustWallet via our Apps using WalletConnect. It shows only 9 network options to select.

**To Reproduce**
Use https://app.ryno.exchange or https://flip.ryno.exchange and choose WalletConnect.

**Expected behavior**
After choosing WalletConnect, TrustWallet should show only POA Network for connection.

**Screenshots**
![photo_2021-09-14 16 47 42](https://user-images.githubusercontent.com/88944220/133269624-093ce5be-0703-46b9-99b7-ddc997931b4c.jpeg)

**Comment by hewigovens** [comment]
Thanks for reporting, will add it back

**Comment by hewigovens** [comment]
Will be available in next release
<img src=https://user-images.githubusercontent.com/360470/133358666-080eab4b-2891-4338-a10d-1cdc283d0933.png width=45% />

**Comment by yadatashy** [comment]
@hewigovens Thanks for the quick fix. I just updated the app and it works very well.
