### ISSUE TITLE
Update RPC URL for Polygon 

### ISSUE THREAD

**Issue by ggf31416** [trustwallet/wallet-core#1658]
From https://docs.matic.network/docs/develop/network-details/network/

> New unified URL (recommended): 
https://polygon-rpc.com/
> Use this new aggregated RPC link to avoid RPC disconnects

I get significantly higher performance with Meta mask using the above configuration, updating the url for Trust Wallet should obtain the same performance.

**Comment by hewigovens** [comment]
Thanks for suggestion, will check
