### ISSUE TITLE
[Cardano][Testnet][Address]

### ISSUE THREAD

**Issue by Hazhir007** [trustwallet/wallet-core#1659]
i can not see any unit tests for testnet addresses , does wallet-core supports testnet addresses for cardano?

**Comment by Hazhir007** [comment]
i see this line in TWCoinType.h

which i suppose there would be support for testnet addresses in wallet-core ?
but can not see how to use it/ 

TWCoinTypeCardano = 1815, // Note: Cardano Shelley testnet uses purpose 1852 (not 44) 1852/1815

**Comment by hewigovens** [comment]
usually we don't support testnet addresses
