### ISSUE TITLE
curl: (22) The requested URL returned error: 403 Forbidden

### ISSUE THREAD

**Issue by kuldeep-1k** [trustwallet/wallet-core#1665]
While installing TrustWalletCore pods version 0.12.33 getting the error
`curl: (22) The requested URL returned error: 403 Forbidden
`
System:- Apple MBP M1

**To Reproduce**
Either fresh install TrustWalletCore pod version 0.12.33 or
(if previously installed on system) deintegrate TrustWalletCore pod and re-install

**Expected behavior**
It must install the pods or give a clear error response for the solution.

**Screenshots**
PFA
<img width="945" alt="Screenshot 2021-09-22 at 2 26 20 PM" src="https://user-images.githubusercontent.com/49232281/134314042-5f61782e-fc43-4a85-8c08-06674e93a097.png">

**Comment by hewigovens** [comment]
This version is super old, could you please try latest 2.6.x?

**Comment by kuldeep-1k** [comment]
@hewigovens I know the thats old and new version after 2.0.22 is working fine for us, but this (0.12.33) was working for us 2 days back and suddenly we started falling into that error.

Currently we are not in the right state to upgrade this but we have planned that as well and we have started working on that as well.

But we really need help so that it works for us for now and at-least next few more days.

**Comment by hewigovens** [comment]
why do you guys still use old build 18 months ago? @vikmeup let's keep old builds until next week?

**Comment by kuldeep-1k** [comment]
@hewigovens due to some security and right issues we were not able to upgrade to new updates, we planned it but we were not getting approval for the same, and now we have escalated the same and we can now upgrade to latest one but it would be great help if we get a week more so that we can have a smooth transition from older to latest version.

Thank you a lot !!!

**Comment by vikmeup** [comment]
Can you try again? should be available now?

**Comment by kuldeep-1k** [comment]
@vikmeup yes its working now, thank you thanx a lot!!!

really appreciate quick help...

**Comment by hewigovens** [comment]
Please update to new build asap, old builds won't be available soon
