### ISSUE TITLE
[raw_data_hex][Sign]

### ISSUE THREAD

**Issue by wcj233** [trustwallet/wallet-core#1668]
Hi, I tried to sign the information of Tron by using AnySigner. I'm using Swift to develop. Now I have a `raw_data_hex` and `private key`, how can I sign this data?

The raw_data_hex is like:
`0a022489220894b95b2a56b5c3b740b8fff28dc12f5ab101081f12ac010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412770a1541f4ea52c222af5033009f9c0eac9b31e78174658c121541ec5e8661f8855b1724d4f668f11ab722b4b3b74d18904e22444bf3e2d000000000000000000000000000000000000000000000000000000000000003d600000000000000000000000000000000000000000000000000000000614c388570e0b5ef8dc12f900180e1eb17`

**Comment by hewigovens** [comment]
can you join https://t.me/trust_developers and search tron in chat history? usually it's related to get correct data from endpoint

**Comment by jiuyaopinyin** [comment]
> 0a022489220894b95b2a56b5c3b740b8fff28dc12f5ab101081f12ac010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412770a1541f4ea52c222af5033009f9c0eac9b31e78174658c121541ec5e8661f8855b1724d4f668f11ab722b4b3b74d18904e22444bf3e2d000000000000000000000000000000000000000000000000000000000000003d600000000000000000000000000000000000000000000000000000000614c388570e0b5ef8dc12f900180e1eb17

hi,Did you finish it?

**Comment by EvgenV** [comment]
> Hi, I tried to sign the information of Tron by using AnySigner. I'm using Swift to develop. Now I have a `raw_data_hex` and `private key`, how can I sign this data?
> 
> The raw_data_hex is like: `0a022489220894b95b2a56b5c3b740b8fff28dc12f5ab101081f12ac010a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412770a1541f4ea52c222af5033009f9c0eac9b31e78174658c121541ec5e8661f8855b1724d4f668f11ab722b4b3b74d18904e22444bf3e2d000000000000000000000000000000000000000000000000000000000000003d600000000000000000000000000000000000000000000000000000000614c388570e0b5ef8dc12f900180e1eb17`

Did you succeed?
