### ISSUE TITLE
bip 49 address derivation via HD Wallet

### ISSUE THREAD

**Issue by dharinisp4** [trustwallet/wallet-core#1673]
I want to derive a test net address for bip 49 something like mg8PDfcsUZAPKyTgtmrnfpWhiFD4EqLSCy 
but for any derivation path i use i get the same address with sequence starting with bc1 
here are some example 

E/BTC: m/0'/0/0 ----bc1qjwl0nemk5xl34d9jmy352c0k9vvem6h0g0cg3j
E/BTC: m/44'/0'/0'/0/0 ----bc1qkgsv8w9nfdfrjspf9dnsn3u9wzefz4mfjwwj4p
E/BTC: m/49'/0'/0'/0/0 ----bc1qgnldvv2tv785afg5ful9jt2zkdqdv07czstsva
E/BTC: m/84'/0'/0'/0/0 ----bc1qcg0080d2p4vc62atq7el9aguaryt505dq79zml 

could anyone help me out please as while going through some issues /discussion i found out that trust has removed testing environment.

**Comment by hewigovens** [comment]
we don't support testnet addresses, but can take a look at this method (https://github.com/trustwallet/wallet-core/blob/master/swift/Sources/Extensions/BitcoinAddress%2BExtension.swift#L19) to create bip49 addresses
