### ISSUE TITLE
why trust wallet's litecoin wallert  address is start with ltc1xxxxxxxxxxxxxxxx

### ISSUE THREAD

**Issue by Hello-Linux** [trustwallet/wallet-core#1675]
Why does the trust wallet litecoin address is start with ltc1xxxxxxxxx, which is different from other digital wallets? The prompt that other exchanges withdraw money to this address is not supported, but I withdraw money to imtoken wallet and It is  support LTC, Why trust wallet is not supported?

**Comment by hewigovens** [comment]
Take look at this: https://help.crypto.com/en/articles/4056348-send-and-receive-btc-ltc-difference-between-segwit-and-legacy-address

we're using native segwit address by default, many other exchanges / wallets don't adopt this yet

**Comment by Hello-Linux** [comment]
@hewigovens When will this feature be supported?

**Comment by hewigovens** [comment]
we don't have plan to support legacy litcoin address, better to ask other exchanges support new native segwit address

**Comment by Hello-Linux** [comment]
@hewigovens Can the binance exchange transfer money to this wallet address at present?

**Comment by hewigovens** [comment]
Yes, binance supports it

**Comment by Hello-Linux** [comment]
@hewigovens Thank you very much for your reply!

**Comment by Hello-Linux** [comment]
@hewigovens Hello, I have another question. When does trust wallet support transaction password verification? Other wallets, such as imtoken, will let you enter the transaction password for confirmation during the transaction.
