### ISSUE TITLE
Feature request: Friendlier personal_sign message request

### ISSUE THREAD

**Issue by imsys** [trustwallet/wallet-core#1694]
**Is your feature request related to a problem? Please describe.**
I'm developing an App, and I have only used used metamask for that. When using personal_sign there, I get a clean plaintext message that I can verify and know what I'm signing. But when I try to do the same in Trustwallet through WalletConnect, I get a hexadecimal that's really intimidating and scary, how could we be sure it is not asking to sign a transaction?

**Describe the solution you'd like**
If possible, I would want TrustWallet to show a friendlier personal_sign message

**Describe alternatives you've considered**
Alternative would be to let the user have to deal with it, or maybe only supporting metamask in the app.

**Additional context**
![Selection_423](https://user-images.githubusercontent.com/911254/136690899-069ae35d-412e-41bf-b49e-638c5931060e.png)

![trustwalletsign](https://user-images.githubusercontent.com/911254/136690918-b128b857-9b7a-4ed1-be4d-e11b6159723d.jpg)

**Comment by imsys** [comment]
@vikmeup , sure! I will create a test sample later today.

**Comment by imsys** [comment]
There is a single page example here:
https://codepen.io/imsys/pen/qBXByvO

Or if you prefer, the same html/js page as a gist:
https://gist.github.com/imsys/2afacdd00961afa9994902cd298db16b

More info on personal_sign:
https://docs.metamask.io/guide/signing-data.html#a-brief-history
https://github.com/ethereum/go-ethereum/pull/2940

**Comment by vikmeup** [comment]
> I just tested on iOS, it works nice there! So it is a Android only issue. @hewigovens
> 
> ![trustwallet-ios-sign](https://user-images.githubusercontent.com/911254/138373270-d9c575a7-2aed-48cf-9f16-8d379251988b.jpg)

Reported to android team, we will improve this in the upcoming releases.

**Comment by hewigovens** [comment]
close for now, will update this when android app fixes this

**Comment by vcoolish** [comment]
Thanks for report!
Will be fixed in next release
<img width="383" alt="Screenshot 2021-11-20 at 13 00 07" src="https://user-images.githubusercontent.com/32914239/142723857-85e7efce-cd04-4961-9374-09773646d1e7.png">
