### ISSUE TITLE
Will we ever support SPM?

### ISSUE THREAD

**Issue by smotched** [trustwallet/wallet-core#1706]
There are no actively developed swift projects using cocopods only. The swift community has completely switched to SPM, its obviously better in every way. Its best to do this earlier to future proof projects that depend on the library.

This library is the single and only reason we still depend on cocopods.

**Comment by smotched** [comment]
@vikmeup I would love to be that is not my expertise. Perhaps we can get a issue started with all the necessary steps and I can implement portions I am able to.

**Comment by hewigovens** [comment]
we will publish binary dynamic frameworks for SPM soon and we can add `Package.swift` later

**Comment by hewigovens** [comment]
May I know your app name? here is my test `Package.swift`  https://github.com/hewigovens/wallet-core-spm, will add it to wallet core once #1720 merged, we also bundle `SwiftProtobuf` as a binary framework, so you may need to change your project `Package.swift` accordingly.
