### ISSUE TITLE
MacOs Swift

### ISSUE THREAD

**Issue by unauthxrized** [trustwallet/wallet-core#1723]
Hi! Add please macOs support for swift

**Comment by nerzh** [comment]
Hello, I created a SPM package, added a binary target as xcframework and have the same error

/Users/nerzh/Library/Developer/Xcode/DerivedData/ESCore-faiiwqkvgqryxxewcscrxxsaught/SourcePackages/artifacts/escore/WalletCore.xcframework:1:1: error build: While building for macOS, no library for this platform was found in '/Users/nerzh/Library/Developer/Xcode/DerivedData/ESCore-faiiwqkvgqryxxewcscrxxsaught/SourcePackages/artifacts/escore/WalletCore.xcframework'.

**Apple M1 Max Ventura 13**
