### ISSUE TITLE
[Master Key][Private Key][TWCurveED25519Extended]

### ISSUE THREAD

**Issue by Hazhir007** [trustwallet/wallet-core#1724]
i have this mnemonic keywords:

"poet spider smile swift roof pilot subject save hand diet ice universe over brown inspire ugly wide economy symbol shove episode patient plug swamp"

i want to get to a master key such as :

master key : "08cec6e16201d0fe98a1cda7a3942e6d3d5aacaf87ce01d396697b1df008e042681d0749cea359028a779faeccc883fe142de67568702e10b71bac64dd610237"

i know we can get to this master key from that mnemonic.

and from this master key get a private key as follow:

private key: "80918defe6164e64fe5c8c6a52dfb91611052ffb86f7f08f868853300009e04260b1b5086d517f97f6400acc6dcf8deeaffd0acbe1d718631fa747a1cce6445b"

the problem is when i call the get master key method like this :

```cpp
PrivateKey masterPrivKey = wallet.getMasterKey(TWCurve::TWCurveED25519Extended);
```
it returns: "b0e349c4b8763f57547e06a647890feb9023c895ac82a98f32c085823a2c4e46"

how can i get the master key ?

**Comment by hewigovens** [comment]
this should be fixed after https://github.com/trustwallet/wallet-core/pull/1726
