### ISSUE TITLE
Create a wallet from privateKey  

### ISSUE THREAD

**Issue by XhhAndroid** [trustwallet/wallet-core#1736]
我想通过导入的privatekey创建一个钱包，使用了api如下
val storedKey = StoredKey.importPrivateKey(keyArray,"n", byteArrayOf(),CoinType.BINANCE)
but storedKey is null
who can help me?

**Comment by hewigovens** [comment]
Take a look at the similar swift test case: https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Keystore/KeyStoreTests.swift#L176, and try non-empty password
