### ISSUE TITLE
Add a transaction password confirmation function!!!

### ISSUE THREAD

**Issue by Hello-Linux** [trustwallet/wallet-core#1754]
**Is your feature request related to a problem? Please describe.**
Hello, can we add a transaction password confirmation function? What I mean is that when I withdraw coins, I am prompted to enter the transaction password, because this function is available in the imtoken wallet, but the trustwallet does not have this function,I think this function is very useful and can increase the security of transactions. If one day I lose my phone, others will not be able to steal my cryptocurrency .

**Comment by vikmeup** [comment]
We plan to add support for master password feature by end of the year. I will close this issue here, but you can expect this be available by EOY.

**Comment by Hello-Linux** [comment]
@vikmeup  Thank you very much!

**Comment by Hello-Linux** [comment]
@vikmeup  It's been so long, and this feature hasn't been implemented yet?
