### ISSUE TITLE
Prices: Add option for BSC to fetch price data from alternative sources

### ISSUE THREAD

**Issue by ilikenwf** [trustwallet/wallet-core#1760]
**Is your feature request related to a problem? Please describe.**
Coin Market Cap regularly drops the ball - not only does it regularly screw up decimal places (thus screwing coins like Baby Floki Millionaire and Evergrow from initial growth hype), but it also updates very slowly.

**Describe the solution you'd like**
It would be amazing to be able to also, optionally, use Poocoin, Bogged, Coingecko,  or any of the other pricing sites for the various chains instead of Coin Market Cap if possible.

**Describe alternatives you've considered**
I'd fork and figure out how to do this myself but haven't yet become familiar enough with this project to know where price data is fetched.

**Comment by catenocrypt** [comment]
Sorry, this has nothing to do with wallet-core library.
I suggest searching https://community.trustwallet.com/ for details (there are backup price providers), and our official Telegram channels.
