### ISSUE TITLE
Is possible to sign a message using the wallet-core SDK?

### ISSUE THREAD

**Issue by henrique2601** [trustwallet/wallet-core#1780]
I am creating an app that is a wallet too and I need to be able to sign a message like on this website:
https://app.mycrypto.com/sign-message

I tried using the sign message provided in the SDK but was not successful, can you give me some sample code of how do it from an HDWallet?

    let wallet = HDWallet(mnemonic: "ripple scissors kick mammal hire column oak again sun offer wealth tomorrow wagon turn fatal", passphrase: "")!
    let etherAdress = wallet.getAddressForCoin(coin: .ethereum)
    let privateKey = wallet.getKeyForCoin(coin: .ethereum)
    let message = "AAABfSVYpi0Ou1szwloATw".data(using: .utf8)!

    let sig3 = privateKey.sign(digest: message, curve: .secp256k1)!
    print("### ether: \(etherAdress)")
    print("### sig3: \(sig3.hexString)")

Using this code and comparing it to the website the output is diferent.

**Comment by hewigovens** [comment]
Take a look at this example: https://github.com/trustwallet/trust-web3-provider/blob/master/ios/TrustWeb3Provider/DAppWebViewController.swift#L240

**Comment by henrique2601** [comment]
I am using wallet-core to create a wallet-like app, I am not using DApp, there is some way of doing it directly without using Dapp?

**Comment by hewigovens** [comment]
That's not dapp code, but swift code using wallet core to sign ethereum message

**Comment by henrique2601** [comment]
It worked, thank you, I was struggling a lot to implement it.

**Comment by jiuyaopinyin** [comment]
> It worked, thank you, I was struggling a lot to implement it.

请问你最后是怎么完成的?我现在也遇到了同样的问题

**Comment by jiuyaopinyin** [comment]
> It worked, thank you, I was struggling a lot to implement it.

May I ask how did you end up doing it? i am having the same problem now
