### ISSUE TITLE
[Bitcoin] Receive to Taproot address

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#1785]
Sending to a Taproot address is supported.  However, to be able to receive to a Taproot address, support is needed:
- Construct a Taproot (v1 Segwit) address from a Schnorr public key
- Create Schnorr signature for taproot
- Validate Taproot spend
- Handle Schnorr signatures
- Import a wallet with Taproot private key

If all this is done, default Bitcoin address type can be changed to Taproot. This switch makes sense only if the ecosystem supports Taproot widely, which will take time.

**Comment by BiGBoysBBAMSG** [comment]
hi
