### ISSUE TITLE
[Keystore] Support multiple accounts per coin 

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#1788]
**Describe the bug**

Currently our keystore always expects to only have 1 account/address per wallet. Bitcoin for example already supports 4 different types of addresses: 1,3, bc1 and taproot. It would be great to provide an interface to generate each account and then allow clients to select which address they want to use. 

Another use case to allow users to have multiple accounts with different derivation paths, Phantom wallet as an example, which using different derivation path. 

Clarification: one keystore/wallet still has one mnemonic / master private key.

**Comment by catenocrypt** [comment]
0. Given a mnemonic and a coin
1. private key is generated using default derivation path
2. address is derived from public key, using default creation method

In 1. alternative non-standard derivation path can be used
In 2. alternative address derivation can be used (e.g. P2PK/Segwit)
Both are coin specific, and probably it should be restricted to alternatives that make sense.

Issues:
- Support one default-or-alternative address per coin (multiple in multiple wallets), or possible multiple in a single wallet?
- Have a generic scheme where each address has an (optional) generic tag, such as 'phantom' or 'legacy p2pk', or structured for each address derivation path and address derivation scheme are stored (as meta info)

**Comment by catenocrypt** [comment]
Some ideas/tasks:

- Extend KeyStore to support multiple coins.  This is mostly done:
 -- Way to retrieve all acounts (getAccounts)
 -- Add optional tag/name to each account
 -- Way to retrieve a specific account for a coin (default, by derivpath, by tag)
- Formalize alternative derivation paths
 -- Store alternative derivation paths in registry.json
 -- Method to get alternative derivation paths
 -- In AnyAddress, support alternative derivation paths
 -- In KeyStore support alternative derivation paths
- Formalize different address formats.  Currently there is one implicit default per coin
 -- Store alternative address formats in registry.json
 -- Method to get alternative address formats
 -- In AnyAddress, support alternative address formats
 -- In KeyStore, support alternative address formats
