### ISSUE TITLE
Wallet connect on Android doesn't work properly

### ISSUE THREAD

**Issue by Blackening999** [trustwallet/wallet-core#1789]
**Describe the bug**
Wallet Connect on Android results in an empty transaction on the BSC network. After attempting to do the same with WalletConnect on iOS - Android Wallet connect works like a charm

**To Reproduce**
Steps to reproduce:
1. Create a new TrustWallet instance.
2. Put BNB + CAKE there.
3. Opened App which communicates via WalletConnect account on Android.
4. Signing the transaction results in empty tx - dead end.
5. Opened App which communicates via WalletConnect account on iOS.
7.  Signing the transaction results in success.
8. Opened App which communicates via WalletConnect account on Android.
11.  Signing the transaction results in success.
WAT?

**Expected behavior**
WalletConnect transaction signing should result in the same successful transaction mining no matter if it was done through iOS to Android TrustWallet app.

**Comment by ivanKis** [comment]
@Blackening999 what is android app version do you use?

**Comment by vcoolish** [comment]
What was the dApp you interacted with?
