### ISSUE TITLE
Dart FFI support

### ISSUE THREAD

**Issue by ed0xe** [trustwallet/wallet-core#1791]
I'm attempting to [create a wrapper](https://github.com/k9wallet/wallet_core_flutter) of wallet-core to be used in a [Flutter](https://flutter.dev) app. My approach is simple and seems to work fine, but there are some inefficiencies and potentially multiple points of failure as the current flow goes like this:

```
Dart -> Kotlin/Swift -> wallet-core
```

Given that I can [Generate all proto definitions for Dart](https://github.com/k9wallet/wallet_core_flutter/tree/master/lib/protos) and Flutter apps are [capable of directly loading native libs](https://docs.flutter.dev/development/platform-integration/c-interop), Ideally I'd like to use the wallet-core lib as such:

```
Dart -> wallet-core
```

So far I can generate the necessary Dart code with https://pub.dev/packages/ffigen , But I have been unable to compile the wallet-core library to be used as such as I am no C++ expert. 

Ideally I'm asking for Feedback, Opinions , and possibly some support. Should I just continue building it using Kotlin/Swift as intermediately?, or generate the dart bidding and with some help compile to the library properly?

**Comment by hewigovens** [comment]
can check this thread? https://github.com/trustwallet/wallet-core/discussions/1264
