### ISSUE TITLE
[Solana] Add support for Staking Pools

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#1792]
**Is your feature request related to a problem? Please describe.**

Current onchain staking UX is quite difficult and requires multiple steps to stake. It would better to integrate Staking Pool to provide liquid staking and instant stake/unstake functionality

Reference: https://spl.solana.com/stake-pool

**Comment by catenocrypt** [comment]
Some of the top staking pools:
https://marinade.finance/
https://lido.fi/solana
https://www.socean.fi/

**Comment by catenocrypt** [comment]
Operations of stake pool managers and validators are not in scope, only of pool users.

Only stake (of SOL) and unstake (of SOL) by users is in scope, stake deposit not.

**Comment by catenocrypt** [comment]
Top 4 staking pools, by liquidity; APY and SOL staked (current values):

Marinade:  6.67%  6589 kSOL
Lido:        6.10%  1015 kSOL
Socean:   7.26%  659 kSOL
Parrot:    7.00%  379 kSOL

**Comment by catenocrypt** [comment]
For now this is abandoned, alternative is native staking directly with a validator.
PR #1805 and branch ar/solana-stake-pool is abandoned.
