### ISSUE TITLE
# [Codecov](https://codecov.io/gh/trustwallet/wallet-core/pull/1064?src=pr&el=h1) Report

### ISSUE THREAD

**Issue by Angymr** [trustwallet/wallet-core#1793]
# [Codecov](https://codecov.io/gh/trustwallet/wallet-core/pull/1064?src=pr&el=h1) Report
> Merging [#1064](https://codecov.io/gh/trustwallet/wallet-core/pull/1064?src=pr&el=desc) into [master](https://codecov.io/gh/trustwallet/wallet-core/commit/fe98234dd230554ee62f73ccc1203884af0b7e44&el=desc) will **increase** coverage by `0.02%`.
> The diff coverage is `97.82%`.

[![Impacted file tree graph](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/graphs/tree.svg?width=650&height=150&src=pr&token=OFfM4qnsxJ)](https://codecov.io/gh/trustwallet/wallet-core/pull/1064?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master    #1064      +/-   ##
==========================================
+ Coverage   95.15%   95.18%   +0.02%     
==========================================
  Files         429      429              
  Lines       12574    12639      +65     
==========================================
+ Hits        11965    12030      +65     
  Misses        609      609              
```

| [Impacted Files](https://codecov.io/gh/trustwallet/wallet-core/pull/1064?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/Binance/Address.h](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-c3JjL0JpbmFuY2UvQWRkcmVzcy5o) | `100.00% <ø> (ø)` | |
| [src/Coin.h](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-c3JjL0NvaW4uaA==) | `100.00% <ø> (ø)` | |
| [src/Ethereum/Entry.h](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-c3JjL0V0aGVyZXVtL0VudHJ5Lmg=) | `100.00% <ø> (ø)` | |
| [src/HDWallet.h](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-c3JjL0hEV2FsbGV0Lmg=) | `100.00% <ø> (ø)` | |
| [src/Keystore/StoredKey.h](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-c3JjL0tleXN0b3JlL1N0b3JlZEtleS5o) | `100.00% <ø> (ø)` | |
| [src/interface/TWAccount.cpp](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-c3JjL2ludGVyZmFjZS9UV0FjY291bnQuY3Bw) | `25.00% <0.00%> (ø)` | |
| [src/interface/TWAnyAddress.cpp](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-c3JjL2ludGVyZmFjZS9UV0FueUFkZHJlc3MuY3Bw) | `94.66% <ø> (ø)` | |
| [walletconsole/lib/Address.h](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-d2FsbGV0Y29uc29sZS9saWIvQWRkcmVzcy5o) | `100.00% <ø> (ø)` | |
| [src/Binance/Address.cpp](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-c3JjL0JpbmFuY2UvQWRkcmVzcy5jcHA=) | `100.00% <100.00%> (ø)` | |
| [src/Binance/Serialization.cpp](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree#diff-c3JjL0JpbmFuY2UvU2VyaWFsaXphdGlvbi5jcHA=) | `97.50% <100.00%> (+0.94%)` | :arrow_up: |
| ... and [13 more](https://codecov.io/gh/trustwallet/wallet-core/pull/1064/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/trustwallet/wallet-core/pull/1064?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/trustwallet/wallet-core/pull/1064?src=pr&el=footer). Last update [fe98234...a1c1ee6](https://codecov.io/gh/trustwallet/wallet-core/pull/1064?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

_Originally posted by @codecov[bot] in https://github.com/trustwallet/wallet-core/issues/1064#issuecomment-668979687_

**Comment by catenocrypt** [comment]
codecov.io is no longer supported
