### ISSUE TITLE
Couldn't retrieve package - bad request

### ISSUE THREAD

**Issue by duprass** [trustwallet/wallet-core#1802]
**Describe the bug**
Try to add wallet-core as dependency to android project. Failing to retrieve package from github. Results to this error 
![image](https://user-images.githubusercontent.com/8008905/143288695-109c7167-f01f-48ba-ad4a-86afbcad64ee.png)

**To Reproduce**
build.gradle (project) 
```
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
        maven {
            url = uri("https://maven.pkg.github.com/trustwallet/wallet-core")
            credentials {
                username = project.findProperty("gpr.user") as String ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") as String ?: System.getenv("TOKEN")
            }
        }
    }
}
```

dependency in build.gradle (app)

`implementation 'com.trustwallet:wallet-core:2.6.34'`

**Expected behavior**
Successful retrieve package from github

**Additional context**
There's no offline mode in gradle and username/token is correct.

**Comment by duprass** [comment]
mavenLocal() solved issue

**Comment by tuannm2** [comment]
<img width="1082" alt="Screen Shot 2021-12-21 at 14 49 11" src="https://user-images.githubusercontent.com/85265921/146891714-623f1ac8-5ba7-404a-8fd5-290dc4ee2a30.png">

Could you show me what am i wrong in this case. I got "Bad request" too. Thank you
