### ISSUE TITLE
Polkadot-address wrong

### ISSUE THREAD

**Issue by wcj233** [trustwallet/wallet-core#1807]
I tried to generate polkadot address with Swift language, but the generated address is different from the address which is generated by ImToken, I'm not sure where I missed. The code snippet is below:

```
let wallet = HDWallet.init(mnemonic: mnemonic, passphrase: "")
let polkadotAddress = wallet.getAddressForCoin(coin: CoinType.polkadot)
```

Thanks!

**Comment by hewigovens** [comment]
This is a known issue, it uses different derivation scheme, we might enable private key importing for Trust app later

**Comment by wcj233** [comment]
Thanks for your help. So currently I can't generate the same polkadot address as ImToken by using trustWalletCore, correct?
