### ISSUE TITLE
Add Cardano Support

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#1815]

**Comment by Dick890** [comment]
Doesn't it support now?

**Comment by vikmeup** [comment]
> Doesn't it support now?

It supports an older version of Cardano.

**Comment by catenocrypt** [comment]
Current Shelley address implementation is incompatible with AdaLite and Yoroi wallets, despite same derivation path.  First step is to consolidate this.

**Comment by catenocrypt** [comment]
Shelley address handling requires rework.  For an address, it uses two keys of two different derivation path, which makes it nontrivial to integrate into the current wallet core scheme.
