### ISSUE TITLE
How to add other token/chain using this library?

### ISSUE THREAD

**Issue by ironwill1023** [trustwallet/wallet-core#1824]
Hi, I have question.
https://github.com/trustwallet/wallet-core/blob/master/samples/android/app/src/main/java/com/trust/walletcore/example/MainActivity.kt
I'd like to know how I can add Algorand transaction signing part here. Where is the documentation about this?
Thanks.

**Comment by hewigovens** [comment]
Take a look at the cpp test: https://github.com/trustwallet/wallet-core/blob/master/tests/Algorand/SignerTests.cpp#L90
