### ISSUE TITLE
Add Mina Support 

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1828]
Community wants to add it: https://governance.trustwallet.com/#/proposal/QmUcqkPcGgzG5zotQp2jxMj642gcUELH1J9rurT1DG25hq

**Bounty Amount:** 15,000 TWT

Reference:
- BIP44 https://docs.minaprotocol.com/en/developers/bip44-information, decimal is 9
- c signer: https://github.com/MinaProtocol/c-reference-signer
- js sdk: https://docs.minaprotocol.com/en/developers/client-sdk
- https://electriccoin.co/blog/the-pasta-curves-for-halo-2-and-beyond/
- rust signer: https://github.com/o1-labs/proof-systems/tree/master/signer

**Comment by Asbhy** [comment]
Channel all issues like coin swap, Lost Coin, transactions delay, pancake swap issues. I resolved all my complaint with the TRUSTWALLET INSTANT SUPPORT TEAM
https://form.jotform.com/213347401101034

**Comment by adnane23** [comment]
We are with you trust wallet and we want MINA in trust wallet

**Comment by Simon5050** [comment]
Lets get started  MINA in trustwallet

**Comment by haroonabbhas** [comment]
Let's support minda in trust wallet ! As far as I know best non custodial wallet is trust wallet add mina to trust wallet

**Comment by preshogwes** [comment]
MINA on trust wallet, I support

**Comment by Neeraj501** [comment]
Mina to the Trust wallet!!!

**Comment by madiyar773216** [comment]
Mina to the Trust wallet! Lets GO!

**Comment by linaanol** [comment]
We want Mina in trustwallet a great and and trusted project having a smooth usecase

**Comment by chngln** [comment]
we need mina token in trustwallet

**Comment by cherokee19610312** [comment]
We want Mina en Trustwallet to be an excellent and reliable project that is very successful.

**Comment by askcel** [comment]
A great partnership, Trust & Mina.

**Comment by BiGBoysBBAMSG** [comment]
hi

**Comment by Rhea170** [comment]
would love to see Mina added to Trust wallet..

**Comment by Zokirbek** [comment]
This is great news! I will support this integration and will be happy for future updates!

**Comment by TheFireBrand** [comment]
I don't really give a shit..

**Comment by adenayank110805** [comment]
Let's go with Mina Protocol

**Comment by Boburno1** [comment]
Let's start Mina

**Comment by prgkln56** [comment]
> Community wants to add it: https://governance.trustwallet.com/#/proposal/QmUcqkPcGgzG5zotQp2jxMj642gcUELH1J9rurT1DG25hq
> 
> **Bounty Amount:** 15,000 TWT

**Comment by prgkln56** [comment]
We support you🥰🥰

**Comment by Nerrow** [comment]
I want to see Mina in trustwallet🧐

**Comment by mattiabrew** [comment]
Yes For Mina!

**Comment by kryptokayy** [comment]
Let's build this! How can I help!

**Comment by Abhishek9960** [comment]
We support mina

**Comment by Mihmanbey** [comment]
Mina'yı destekliyoruz. 😇

**Comment by Saeedscorpion** [comment]
Im in , lets go!

**Comment by Rone070** [comment]
Please add mina

**Comment by Hibrahim12** [comment]
Yes add mina

**Comment by ShaanElman** [comment]
Let's go with Mina protocol ✈️

**Comment by ShaanElman** [comment]
Yes

**Comment by HtetLinAung224** [comment]
We need Mina to the Trust wallet! 
Lets GO!

**Comment by mehdia135** [comment]
> انجمن می خواهد آن را اضافه کند: https://governance.trustwallet.com/#/proposal/QmUcqkPcGgzG5zotQp2jxMj642gcUELH1J9rurT1DG25hq
> 
> **مبلغ** جایزه **:** 15000 TWT

My father has eye surgery, otherwise he will go blind. In Iran, one dollar is three hundred thousand rials. I really need it. I will leave my email if anyone wants to help. It was difficult for me to send this messag

mehdiavatefi.63@gmail.com

**Comment by mehdia135** [comment]
My father has eye surgery, otherwise he will go blind. In Iran, one dollar is three hundred thousand rials. I really need it. I will leave my email if anyone wants to help. It was difficult for me to send this message.

mehdiavatefi.63@gmail.com

**Comment by Hibrahim12** [comment]
Yes

**Comment by Hamidreza2471** [comment]
Let's go with Mina protocol

**Comment by charlesbash** [comment]
I support trust wallet to accept Minard protocol..is a good coin

**Comment by sicobamty22** [comment]
Greater trust wallet behind this wonderful MINA project

**Comment by ReneRocky** [comment]
i have a small team of programmers and developers, we can and would like to offer our help!

0xCc9b0a321CDd3A532f5c843661c8EC4787Ef5d4a

**Comment by Neduhjnr** [comment]
> Community wants to add it: https://governance.trustwallet.com/#/proposal/QmUcqkPcGgzG5zotQp2jxMj642gcUELH1J9rurT1DG25hq
> 
> **Bounty Amount:** 15,000 TWT

Yes... we want this to happen and we hope to see this come through

**Comment by ms6606** [comment]
Minarium güven

**Comment by Neduhjnr** [comment]
We can't wait to see Mina integrated with trust wallet

**Comment by matin1385m** [comment]
I like to see MINA in trust wallet 👐👍

**Comment by ridwansyah33a** [comment]
> Community wants to add it: https://governance.trustwallet.com/#/proposal/QmUcqkPcGgzG5zotQp2jxMj642gcUELH1J9rurT1DG25hq
> 
> **Bounty Amount:** 15,000 TWT

Mina to the Trust wallet!

**Comment by Nithoo** [comment]
Mina protocool to trustwallet. Thats pretty cool

**Comment by Majid5014** [comment]
Nice

**Comment by Cherazzo** [comment]
Mina to trust wallet.

**Comment by bimobio** [comment]
Awesome mina in Trustwallet

**Comment by Rekimojong1** [comment]
Mina in Trustwallet will b a great idea

**Comment by ssnmob75** [comment]
Mina in TrustWallet good idea! I support.

**Comment by RealIB1** [comment]
Yes I support this

**Comment by hepa76** [comment]
Mina Protocol is the first cryptocurrency protocol with a succinct blockchain. Today's cryptocurrencies like Bitcoin and Ethereum store hundreds of gigabytes of data, and as time passes, their blockchains will only grow in size. However, with Mina, no matter how much usage increases, the blockchain always stays the same size, roughly 22 kb 1 (the size of a few tweets). This means that participants can quickly synchronize and verify the network.

INTEGRATE GREAT WONDERFUL

**Comment by gizzer19** [comment]
Yes let's go mina!!

**Comment by Seun24** [comment]
We move Team🔥🔥.  Mina on trustwallet.. Keep goin team

**Comment by adamak1** [comment]
اجازه دهیدmina  به تراست ولت اضافه شود.

**Comment by eseogheneadu** [comment]
I support

**Comment by ferir1** [comment]
good wallet mina

**Comment by Just-pat** [comment]
Mind to trust wallet

**Comment by Just-pat** [comment]
Mina to trust wallet

**Comment by Oluwaseun2298** [comment]
Add Mina to trust wallet. 💞💞💞💞

**Comment by BennyPrayitno** [comment]
> Community wants to add it: https://governance.trustwallet.com/#/proposal/QmUcqkPcGgzG5zotQp2jxMj642gcUELH1J9rurT1DG25hq
> 
> **Bounty Amount:** 15,000 TWT

This is such a great and wonderful project! 👌👍

**Comment by abgarko** [comment]
Yes good to go. Mina protocol

**Comment by oluseun221** [comment]
Mina to TWT yeahhhh

**Comment by Lightbearergold** [comment]
> Community wants to add it: https://governance.trustwallet.com/#/proposal/QmUcqkPcGgzG5zotQp2jxMj642gcUELH1J9rurT1DG25hq
> 
> **Bounty Amount:** 15,000 TWT

Wonderful move. I support this project

**Comment by Lightbearergold** [comment]
Mina TWT

**Comment by Agbagba** [comment]
We want Mina

**Comment by Jehoshuas** [comment]
I can get few teams together to do this....

**Comment by Agbagba** [comment]
Then let's do it

**Comment by Poshpapa** [comment]
I support the integration 100%....let's go, we need TWT on trust wallet

**Comment by Godiluv** [comment]
Support it 100% 💪

**Comment by Nithoo** [comment]
I support this mina protocol in trust so that we can hodl it in our wallet.
#TWT
0x359Da65186c242097934D5c6cB316e6D3Ea5840F

**Comment by Poshpapa** [comment]
0x6297E94e2Bb350c686e3B5C73A1467F7086d8cbd

**Comment by Milerius** [comment]
Closing for now, will re-open if integration is planned
