### ISSUE TITLE
Support Arweave chain

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#1832]
Project website:   https://www.arweave.org 

Reference:
- https://github.com/acolytec3/arweave-mnemonic-keys
- https://github.com/Zondax/ledger-arweave/blob/master/app/src/crypto_store.c
- https://github.com/libtom/libtomcrypt/tree/develop/src/pk/rsa

Info:
- 4096-bit RSA key is used
- Key can be generated firectly
- Key can be generated off a BIP39-like mnemonic, directly from mnemonic seed (no derivation path) (arweave-mnemonic-keys). 64-byte seed is used as PRNG seed for prime number selection. For PRNG HmacDrbg is used (available in trezor)
- Also could be generated using proper BIP39/BIP32/BIP44 style, with derivation path, using 472 coin ID (32-byte node private key plus 32-byte extension)
- Coin ID 472 is registered (slip 44), but not used so far
- Key can be derived from mnemonic, using pseudo-random generation to get more bits (4096 bits off a ~128 bit mnemonic) (uses HmacDrbg, available in trezor), also RSA generation is used
- PrivateKey impl. needs to be extended for 4069-bit key and RSA pubkey derivation
- No suitable RSA implementation found so far (C/C++); reference implementations usually don't include key generation; arweave code could be ported, but it's a large amount of code, Javascript.  Key generation is almost more code logic than just the signing.

Possible options for address generation / interoperability:
- No key generation, only key import.  Key generation logic is not needed, interoperable, but very much not user friendly UX: key files would have to be transferred to mobile app somehow
- Key generation Bip44-compliant: not interoperable with other phrase-based Arweave wallets; key generation logic is needed, but it's output does not have to match exactly other implementation, since it will not be interoprable as well.
- Key generation interoperable with Arweave way, but _not_ Bip44 compliant.  Key generation algorithm has to be implemented exactly, output of deterministic generation should be the same in every case. This puts some additional constraint in implementations used; inital PRNG and prime number generation all use prng internally which must be the same.
 
Open:
- What implementation to use for RSA key generation, signing?

**Comment by Asbhy** [comment]
Channel all issues like coin swap, Lost Coin, transactions delay, pancake swap issues. I resolved all my complaint with the TRUSTWALLET INSTANT SUPPORT TEAM
https://form.jotform.com/213347401101034

**Comment by catenocrypt** [comment]
Open Issues:
- No BIP39 is used, how to generate 4096-bit key from master key?
- New private key type is needed, 4096-bit
- What implementation to use for RSA signing?

**Comment by hewigovens** [comment]
This is a good chance to discuss with AR team? to see if we have other options

**Comment by hewigovens** [comment]
Updated with some references

**Comment by catenocrypt** [comment]
PR #2176 closed, implementation requires large amount of code to be ported (incl. e.g. prime number generation, RSA, etc.), too much effort vs. benefit rn, closing.

**Comment by Milerius** [comment]
Closing for now, will re-open if planned later
