### ISSUE TITLE
Connecting trust wallet to other mobile apps via wallet connect doesn't work (Android only)

### ISSUE THREAD

**Issue by dokocat** [trustwallet/wallet-core#1837]
**Describe the bug**
When using a low end Android device connecting an app with trust wallet does not bring up the walletconnect dialog. Tested on Redmi 9 and Galaxy a51. Works on iOS fine and newer Android devices such as pixel 4.

**To Reproduce**
1. Use a low end Android such as Redmi 9 or Galaxy a51
2. Install an app that allows you to connect trust wallet. Tested on Opensea, okex defi, and zerion mobile apps.
3. In the app, select trust wallet as the wallet to connect to.
4. You will go to trust wallet
5. There will not be any connection dialog. However if you test on a new Android like a pixel 4, it does work.

**Expected behavior**
The wallet connect dialog to connect the app to trust wallet should appear.

**Screenshots**
It's easy to reproduce if you have the said devices.

**Additional context**
All latest versions of all apps and system ui's.

**Comment by vikmeup** [comment]
> **Describe the bug** When using a low end Android device connecting an app with trust wallet does not bring up the walletconnect dialog. Tested on Redmi 9 and Galaxy a51. Works on iOS fine and newer Android devices such as pixel 4.
> 
> **To Reproduce**
> 
> 1. Use a low end Android such as Redmi 9 or Galaxy a51
> 2. Install an app that allows you to connect trust wallet. Tested on Opensea, okex defi, and zerion mobile apps.
> 3. In the app, select trust wallet as the wallet to connect to.
> 4. You will go to trust wallet
> 5. There will not be any connection dialog. However if you test on a new Android like a pixel 4, it does work.
> 
> **Expected behavior** The wallet connect dialog to connect the app to trust wallet should appear.
> 
> **Screenshots** It's easy to reproduce if you have the said devices.
> 
> **Additional context** All latest versions of all apps and system ui's.

In the dapp browser you are expected to use web3/metamask login - just press that button.

WalletConnect meant to be used via regular browser.

**Comment by dokocat** [comment]
Thanks for the response! However, we're integrating wallet connect in our react native app and letting users connect to trust wallet, not through a browser. It's the same integration you can see on Opensea's mobile app where you can connect to trust wallet. 

If this isn't supported, is there a recommended way to directly connect to Trustwallet from another mobile app? For reference, we're able to get this working with metamask, huobi wallet, tokenpocket, imtoken, coin98. But not with trust wallet.

**Comment by vikmeup** [comment]
Can you check this again on the latest version? it should be working as rest of the wallets.

**Comment by dokocat** [comment]
Sure! Tested on latest version again and still same results. Again this doesn't happen on newer Android phones, only lower end ones. It happens on redmi 9 (most popular phone in India) and galaxy a51. 

We are using version 3.19 on the galaxy a51 which is the latest according to the playstore.
On the redmi 9 we are on the beta track using 3.20 and same issue.

The app we use to test the connection on are zerion, and opensea android mobile apps.

**Comment by ivanKis** [comment]
@dokocat hey, could you make a video of this issue? I can't reproduce such behavior on my Redmi 9 and Samsung a30. Tested on 3.20 and 3.19 versions. Connection dialog was displayed correctly.

**Comment by dokocat** [comment]
Hey! I got it to work by creating a new multi coin wallet. The connect dialog works now for both wallets. Also it works if you uninstall trustwallet and reinstall. Not sure why but, yeah all good now!

**Comment by dokocat** [comment]
Ah! I think I found the culprit. If you don't have a pin set on trustwallet, it won't prompt the wallet connect connection screen.

**Comment by venom25w** [comment]
I have my issue with the trust wallet where i can’t make any transactions on usdt tron network its showing tron smart contract simulation failed. trust wallet it self says its trusted but my thousands of doller are stuck in this wallet. it is not expected from trust wallet they are not allowing me to do any transactions they have frozen my amount without any reason its my hard earned money they should fix my wallet.email-jamesworkemail252@gmail.com
