### ISSUE TITLE
How to update wallet-core inside docker image

### ISSUE THREAD

**Issue by apm-dev** [trustwallet/wallet-core#1841]
**Describe the bug**
When I clone the project and run these steps:
```
./bootstrap.sh
./tools/generate-files
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug
make -Cbuild
```

and after that try to run or build my (golang) project then throws lots of errors like:

```
/wallet-core/build/libTrustWalletCore.a(Entry.cpp.o): In function `__cxx_global_var_init':
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/iostream:74: undefined reference to `std::ios_base::Init::Init()'
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/iostream:74: undefined reference to `std::ios_base::Init::~Init()'
/wallet-core/build/libTrustWalletCore.a(Entry.cpp.o): In function `TW::Cosmos::Address::isValid(TWCoinType, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/wallet-core/src/Cosmos/Address.h:40: undefined reference to `std::allocator<char>::allocator()'
/wallet-core/src/Cosmos/Address.h:40: undefined reference to `std::allocator<char>::~allocator()'
```

while before pulling the new version of codes, everything was ok.

also, I cloned the code and build it on Mac but now how can I use it in my **GoLang** project?

**Comment by apm-dev** [comment]
**Fixed**
I just build the project by following the [document](https://developer.trustwallet.com/wallet-core/developing-the-library/building#full-build).
And some methods were deprecated, so I changed them. like:
- `TWHDWalletGetKeyBIP44` -> `TWHDWalletGetDerivedKey`
- `TWHDWalletIsValid` -> `TWMnemonicIsValid`
- and also change my `cgo import path` to my latest wallet-core clone

**Comment by hewigovens** [comment]
@apm-dev could you please open a pr to fix go sample code? thanks

**Comment by apm-dev** [comment]
@hewigovens Yes sure, I'll do that.
