### ISSUE TITLE
Can not build Android

### ISSUE THREAD

**Issue by sylvestrevgen** [trustwallet/wallet-core#1862]
**Describe the bug**
Can not build Android on Mac OS.

**To Reproduce**
Follow instructions on wallet core site build instructions.

**Expected behavior**
Android will build.

**Screenshots**
<img width="810" alt="Screenshot 2021-12-20 at 23 45 24" src="https://user-images.githubusercontent.com/32303723/146836939-65dd6659-4104-4eb2-a762-1922969db731.png">

**Additional context**

**Comment by hewigovens** [comment]
Did you build android sample app or wallet core for android?

**Comment by sylvestrevgen** [comment]
It was wallet core for Android. I already build wallet core. I think the problem was in new Android Studio. I downgrade Android Studio to 4.1 and downgrade jdk to 11 and everything is ok.

**Comment by hewigovens** [comment]
Thanks for the update, closing now
