### ISSUE TITLE
StoredKey.decryptMnemonic causes APP to crash

### ISSUE THREAD

**Issue by LB6264** [trustwallet/wallet-core#1865]
![image](https://user-images.githubusercontent.com/12064223/146900638-403774c2-a410-49fd-8ade-7d17901a263c.png)
Keystore import, the user enters the wrong password, the jni layer crashes, causing the Android app to crash. It is expected that at the jni layer, if the user enters the wrong password, an exception should be thrown to the Java layer. Java will catch the exception and give the user a friendly prompt instead of Crash directly at the jni layer, hope to be able to modify

The following is the program call entry, the above picture is the crash triggered by the jni layer

   val storedKey = StoredKey.importJSON(keystore.toByteArray())
   val mnemonic = storedKey.decryptMnemonic(pwd.toByteArray())

**Comment by hewigovens** [comment]
Check check if store key is null before decrypting
