### ISSUE TITLE
Mnemonic phrase is invalid, but it is real Trust Wallet test wallet.

### ISSUE THREAD

**Issue by sylvestrevgen** [trustwallet/wallet-core#1866]
**Describe the bug**
Mnemonic phrase is invalid, but it is real test wallet in Trust Wallet. Mnemonic.isValidWord for each word return true, but Mnemonic.isValid return false.

**To Reproduce**
I use in Flutter with dart:ffi. Build wallet-core a few days ago from master. I don't know is this problem on native kotlin or swift. Please, check this.

**Expected behavior**
Mnemonic phrase is valid.

**Screenshots**
<img width="968" alt="Screenshot 2021-12-22 at 12 02 01" src="https://user-images.githubusercontent.com/32303723/147075097-2d112c38-286c-4447-a5af-3ab805e4b784.png">

**Additional context**

**Comment by sylvestrevgen** [comment]
In dart implementation, I already removed mnemonic valid check from HDWallet.createWithMnemonic and it's ok - no errors, wallet is created with correct mnemonic and correct addresses. I think I will be check valid mnemonic with third-party package. I suppose it is a bug. I wish I wrong and it is only my bug.

**Comment by hewigovens** [comment]
@catenocrypt could you please take a look at this too?

**Comment by henrique2601** [comment]
I have a similar problem in Swift, additionally, if I use **check: false** when initializing the HDWallet most of the things works fine, except the **wallet.entropy.hexstring** that always returns an empty string.

**Comment by hewigovens** [comment]
What's the version are you guys using? I just tried master + swift test and it works as expected

![image](https://user-images.githubusercontent.com/360470/147169128-ca4e46d0-8e6f-45d6-99c1-528ac9feccd1.png)

```bash
Test Case '-[WalletCoreTests.HDWalletTests testValidate]' started.
"great achieve master earn property zone glow neither divorce thought curtain domain" is true
Test Case '-[WalletCoreTests.HDWalletTests testValidate]' passed (0.001 seconds).
```

**Comment by sylvestrevgen** [comment]
I don't know which version. I just build master branch for iOS month ago.

**Comment by sylvestrevgen** [comment]
I will try to rebuild last new master branch and will try again.

**Comment by hewigovens** [comment]
close for now, feel free to reopen it

**Comment by catenocrypt** [comment]
Could not reproduce.  Some comments:
- The mentioned mnemonic is valid indeed
- The validity check method has been moved/deprecated recently; TWHDWalletIsValid has been deprecated in favor of TWMnemonicIsValid(), see #1527
- one possibility is some inconsistent build wrt the deprecation
