### ISSUE TITLE
【solana】Incorrect private key length

### ISSUE THREAD

**Issue by LB6264** [trustwallet/wallet-core#1868]
The length of the private key is 44, but the length of the official private key is 88. The picture below is an example of code calling, I hope to fix the length of the private key
![image](https://user-images.githubusercontent.com/12064223/147180732-97d6bd88-4497-4583-b568-9cbb53f25b62.png)

**Comment by LB6264** [comment]
![image](https://user-images.githubusercontent.com/12064223/147180926-101e3ee2-d2f1-4f68-b24f-7bbd759e23ce.png)
This is the official wallet private key length 64

**Comment by elvinasn** [comment]
Any updates?

**Comment by RomanSytnyk** [comment]
It seems I've solved that issue.
Solana private key consists of 32 bytes of seed & 32 bytes of public key.

If you pass into `PrivateKey(data: keyData)` the full private key (64 bytes), keyData variable in my example, it would return `nil`

You need to pass only first 32 bytes to get the private key:

`PrivateKey(data: keyData.prefix(32))`

That will return you working PrivateKey
