### ISSUE TITLE
fatal error: 'gnu/stubs.h' file not found

### ISSUE THREAD

**Issue by yjgfn** [trustwallet/wallet-core#1871]
./tools/android-build

  In file included from /usr/android-sdk-linux/ndk/21.2.6472646/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/__config:215:
  /usr/include/features.h:485:10: fatal error: 'gnu/stubs.h' file not found
  #include <gnu/stubs.h>
           ^~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

**Comment by hewigovens** [comment]
Duplicated with #1872
