### ISSUE TITLE
[Terra] Add CW20 support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1876]
https://docs.terra.money/Tutorials/Smart-contracts/Manage-CW20-tokens.html

**Comment by catenocrypt** [comment]
A sample CW20 token is Anchor ANC:
https://github.com/trustwallet/assets/blob/master/blockchains/terra/assets/terra14z56l0fp2lsf86zy3hty2z47ezkhnthtr9yq76/info.json
