### ISSUE TITLE
[Algorand] Allow sending 0 amount tx

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#1888]

**Comment by catenocrypt** [comment]
I tried changing test `TEST(AlgorandSigner, Sign)` to have 0 amount, and it worked.

https://github.com/trustwallet/wallet-core/blob/master/tests/Algorand/SignerTests.cpp#L60

**Comment by hewigovens** [comment]
@catenocrypt have you tried to broadcast it? I got signature error form iOS app
