### ISSUE TITLE
Generate swifty typealias

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/wallet-core#189]
It looks like we can generate typealias like this:

```swift
typealias TWBitcoinSigningInput = TW_Bitcoin_Proto_SigningInput
typealias TWBitcoinUnspentTransaction = TW_Bitcoin_Proto_UnspentTransaction
typealias TWBitcoinTransactionPlan = TW_Bitcoin_Proto_TransactionPlan
typealias TWBitcoinOutPoint = TW_Bitcoin_Proto_OutPoint
```

We can remove `TW` prefix once we remove TrustCore's Bitcoin implementation

**Comment by vikmeup** [comment]
@hewigovens @alejandro-isaza should we still need these aliases? or already implemented?

**Comment by alejandro-isaza** [comment]
Yes, we should still do this. Right now it's a manual process.
