### ISSUE TITLE
Support EIP-1559 transactions

### ISSUE THREAD

**Issue by hdadr** [trustwallet/wallet-core#1890]
**Is your feature request related to a problem? Please describe.**
On android the trust wallet does not support eip-1559 transaction type 2. Which is really bad for the user, as if i want to modify the gas fee i can only modify 1 parameter which makes me over pay for the transaction, as it just bumps up both the miner tip and the base fee to the same specified amount. For example: i increase the gas fee from 50 gwei to 80 gwei it makes me pay 160 gwei if the base fee is at 80 gwei, however with tx type to, i can set base fee to 78 and miner tip to 2, which result in half of the tx costs.

**Describe the solution you'd like**
Support transaction type 2 (eip-1559) on ethereum mainnet.

**Describe alternatives you've considered**
There is no alternative solution

**Comment by vikmeup** [comment]
> **Is your feature request related to a problem? Please describe.** On android the trust wallet does not support eip-1559 transaction type 2. Which is really bad for the user, as if i want to modify the gas fee i can only modify 1 parameter which makes me over pay for the transaction, as it just bumps up both the miner tip and the base fee to the same specified amount. For example: i increase the gas fee from 50 gwei to 80 gwei it makes me pay 160 gwei if the base fee is at 80 gwei, however with tx type to, i can set base fee to 78 and miner tip to 2, which result in half of the tx costs.
> 
> **Describe the solution you'd like** Support transaction type 2 (eip-1559) on ethereum mainnet.
> 
> **Describe alternatives you've considered** There is no alternative solution

Latest version of Android already supports EIP1559
