### ISSUE TITLE
Bitcoingold support? Its been an year BTG

### ISSUE THREAD

**Issue by qasimsaleem1** [trustwallet/wallet-core#1910]
We are using trust wallet for a while.
But we are waiting for bitcoingold to be added in trustwallet as member of 200K community are waiting for it.
People find trustwallet great and easy way to store their asset we are waiting for bitcoingold support in it.

As we want to withdraw our coins their in it.

Your kind action in this matter will be highly appreciated.
Its been a while looking forward for it,

Kindly refer to someone else as telegram send to pull request
kindly send or assign to someone who take the responsibility to add and support asset
Thanks

**Comment by catenocrypt** [comment]
Duplicate, #1909
