### ISSUE TITLE
Near protocol deposit issue

### ISSUE THREAD

**Issue by headria** [trustwallet/wallet-core#1920]
after signing the transaction, the deposit change to an integer number. (ex. I want to send "1000000000000000000000000" which is equal to 1 NEAR, in the final data after signing it changed to 1, which is incorrect and it should be to 1000000000000000000000000 ).

Website near transaction result for send 5 NEAR,

"transaction": { "signer_id": "arab2.testnet", "public_key": "ed25519:DK2DSND8dtEVCxM4miSuKPCNmz7gm6CfWwq6DXfuGrte", "nonce": 78650022000002, "receiver_id": "b6ea122313da14bb542a3622f36dda184a1b7c9bb1550bb022623e3ee76f736f", "actions": [ { "Transfer": { "deposit": "5000000000000000000000000" } } ], "signature": "ed25519:2AtP1orhrYcTztWRq4tLTx8U7nsQgaW6qi8vkbKRTcxWvLcWN3Zb9mnuPAA3fJKUx3E18GiiZcXM4JSSdWXkYTpp", "hash": "5c1xNKLTG4stcAvzYAYwa4E9Gdio6RSqJXx7vMH7rL5s" },

our transaction result for send 1 NEAR

"transaction": { "signer_id": "1e350eb8eb9c24deec11c12affca191cfa012d76ec0c6eed6c0e0bd03e3941ee", "public_key": "ed25519:32vA1Jf5LodSphnxDYpBiLWLmgykA88nEg3psPLhzLBw", "nonce": 5, "receiver_id": "b6ea122313da14bb542a3622f36dda184a1b7c9bb1550bb022623e3ee76f736f", "actions": [ { "Transfer": { "deposit": "16" } } ], "signature": "ed25519:7enQ2oHprG1XUeznmmhqjyHtgdgk6cuQvzjpbsTCUgAriyaAzwFpXivCK2GA8zfHuH4Pe8pw5p7mMYPfK9Ju1s8", "hash": "GGuTR6ks6b6FAjxcbK5XkECKrzzTW1Ss9W5HZnXZw6Fr" }

please check the deposit field.

**Comment by hewigovens** [comment]
`deposit` is `uint128_t` and should be serialized as little endian byte order, please check `NEARTests.swift`

**Comment by headria** [comment]
I'm see the NEARTest.swift but its look like android test. not thing was diffrent. please help me how to solve it.

**Comment by headria** [comment]
@hewigovens I'm using swift code for the ios app too, but the problem is not solved.

**Comment by SonDN-DDS** [comment]
@headria @hewigovens  I tried to sign transaction near look like NEARTests.swift, but I don't know how to send tracsaction, please help me!
