### ISSUE TITLE
Can not run Android sample project.

### ISSUE THREAD

**Issue by leiiiooo** [trustwallet/wallet-core#1933]
**Describe the bug**
I try to use *wallet-core* in a new project. I integration with https://developer.trustwallet.com/wallet-core/integration-guide/android-guide this, but can not run totally. After that, I try to upgrade the version to *2.6.36* also cannot work. later I try to add *id 'maven'* to my Gradle file can not work. Sad, anyone can help me or give me some advice, where am I wrong.

**To Reproduce**

**Expected behavior**

**Screenshots**
Follow this guide.
<img width="903" alt="image" src="https://user-images.githubusercontent.com/17199087/149619624-428ee6c0-514e-43d1-a8c0-39d3e8b1f7f5.png">

**Additional context**

**Comment by leiiiooo** [comment]
Sorry, my fault.

**Comment by WanTranAndroid** [comment]
@leiiiooo I am having the same problem as you. can you give me your contact eg telegram, skype,...
