### ISSUE TITLE
Signing bnb transaction results in the same hex no matter the inputs. Android kotlin.

### ISSUE THREAD

**Issue by tajition** [trustwallet/wallet-core#1939]
**Describe the bug**
Signing transaction and outputting the hex results in the same hex irrespective of input values such as amount sender address etc. 
**To Reproduce**
Create a new android project. 
Import wallet-core
Create the wallet 
Create a BNB transaction and sign it. 

**Expected behavior**
raw transaction hex should be valid. 
There are two issues:
1) Signed transaction is not valid
2) Changing input does not change the hex

Tried sending the resulting hex to this endpoint:
https://api.bscscan.com/api?module=proxy&action=eth_sendRawTransaction&hex=0xf904808000831cfde080&apikey=YourApiKeyToken

**Screenshots**

**Additional context**
Used this example from the tests:

https://github.com/trustwallet/wallet-core/blob/master/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/binance/TestBinanceTransactionSigning.kt

**Comment by catenocrypt** [comment]
I've tried changing the amount, and result changed as well.
Report is not confirmed, may be different issue.
Closing.

See
https://github.com/trustwallet/wallet-core/pull/1940
https://github.com/trustwallet/wallet-core/runs/4837371669?check_suite_focus=true

```
com.trustwallet.core.app.blockchains.binance.TestBinanceTransactionSigning > testSignBinanceTransaction[integration-tests(AVD) - 8.0.0] FAILED 
	org.junit.ComparisonFailure: expected:<...be612070a03424e42100[2121f0a14bffe47abfaede50419c577f1074fee6dd1535cd112070a03424e421002126a0a26eb5ae98721026a35920088d98c3888ca68c53dfc93f4564602606cbb87f0fe5ee533db38e50212404fd277a9293a290c3dec93a8b09f51a3c5aed457a0ccf53bbb206fc208772ded105bc5d6e534fa378dc6226c4b01386dc84e6c00402b0222cea7d6b464674623]> but was:<...be612070a03424e42100[1121f0a14bffe47abfaede50419c577f1074fee6dd1535cd112070a03424e421001126a0a26eb5ae98721026a35920088d98c3888ca68c53dfc93f4564602606cbb87f0fe5ee533db38e50212401b1181faec30b60a2ddaa2804c253cf264c69180ec31814929b5de62088c0c5a45e8a816d1208fc5366bb8b041781a6771248550d04094c3d7a504f9e8310679]>
	at org.junit.Assert.assertEquals(Assert.java:115)
```
