### ISSUE TITLE
Unable to generate the xcode project

### ISSUE THREAD

**Issue by hsiaosiyuan0** [TrustWallet/wallet-core#194]
## Expected Behavior

The xcode project should be generated successfully.

## Current Behavior

Unable to generate a runnable xcode project.

## Possible Solution

I'm not sure the correctness of below commands, only they worked in a previous version.

## Steps to Reproduce (for bugs)

```
1. make a fresh clone of the latest master branch, the hash is 4299eceb92dbb3e079a0c42d9e8d66fdf8b10a54 ✔️
2. ./bootstrap.sh ✔️
3. ./tools/generate-files ✔️
4. cd ./swift ✔️
5. pod install ✘
```

met a error message like below:

```
Analyzing dependencies
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

    project 'path/to/Project.xcodeproj'
```

**Comment by alejandro-isaza** [comment]
Make sure you have `Xcodegen` installed `brew install xcodegen. Once you do try running generate-files again. Also if you run `pod install` make sure you are in the swift folder.

**Comment by vikmeup** [comment]
@alejandro-isaza I just noticed the same problem, `xcodegen` wasn't installed and `tools/generate-files` did not provide any warnings to install `xcodegen`.

If there is a way to show an error if `xcodegen` not install, would give better clarify.

**Comment by alejandro-isaza** [comment]
No because we want it still work on Linux. We could show a waning.
