### ISSUE TITLE
Android minSdk

### ISSUE THREAD

**Issue by leiiiooo** [trustwallet/wallet-core#1941]
**Is your feature request related to a problem? Please describe.**
I see the min support for SDK is 23, is there some new features that I cannot use in the blow 23 version. Need clear response, because I can force override the version *tools:overrideLibrary*, but I am not sure whether there are some risks.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hewigovens** [comment]
Please test it by yourself we don't know either (Trust Android supports higher sdk version)
