### ISSUE TITLE
Invalid balance calculation 

### ISSUE THREAD

**Issue by dellasorte** [trustwallet/wallet-core#1979]
**Describe the bug**
Invalid balance calculation in BTC wallet when transaction has inputs that are not imported into TrustWallet. In my case the ttotal amount sent was bigger than it was in TrustWallet. So I now it says "Transfer: -184,467,440,737.095513 BTC". this number is not an accident it is "ffffffffff99ddc6". I believe it may cause not just a calculation result, but may lead to integer overflow. 

**To Reproduce**
1. Create two wallet, put something 500 satoshi on each and export private keys
2. Import keys to electrum and  sweep coins anywhere else. this must be one transaction
3. broadcast it, check your trust wallet transfer histories

**Expected behavior**
Wallet has to use it outputs amounts to calculate resulting balance instead of using total transaction amount.

**Screenshots**
![20220127_193230](https://user-images.githubusercontent.com/5054485/151412614-88ad2c9a-24a6-456b-b6ec-cde555fea300.jpg)

**Comment by vikmeup** [comment]
Do you have an address/xpub to reproduce it? Or transaction ID of the overflow amount.

It does seems like an UI issue with the amount, we can look into it.

**Comment by vikmeup** [comment]
I was able to confirm this issue not related to the wallet core or the balance. Backend service that provides list of transactions for a specific address has invalid amount returned due to having 2 addresses having balance, but normally only 1 is supported for our product. 

This problem will resolved today/tomorrow. I will close this issue for now.

**Comment by covain** [comment]
@dellasorte reimport and check again. Report if the issue is still in place.

**Comment by dellasorte** [comment]
> covain

Yeah it is resolved now. thanks
