### ISSUE TITLE
Q: How can I generate mnemonic phrase?

### ISSUE THREAD

**Issue by y9san9** [trustwallet/wallet-core#1987]

**Comment by Alphabeta770** [comment]
For the creation of a mnemonic phrase, we need at least 128 bits of entropy, and at most 256 bits. Depending on the length of the initial entropy, the mnemonic phrase will be 12 to 24 words long.
Let’s say we want to create a 12-word-long mnemonic phrase. We start off by generating 128 bits of entropy.

**Comment by catenocrypt** [comment]
The `HDWallet` has method to create a wallet with a new random mnemonic, number of entropy bits can be specified (128 bits -> 12 words, 256 bits -> 24 words)
https://github.com/trustwallet/wallet-core/blob/master/include/TrustWalletCore/TWHDWallet.h#L26

I also recommend checking the sample apps:
https://github.com/trustwallet/wallet-core/tree/master/samples

**Comment by y9san9** [comment]
Thanks a lot mates!
