### ISSUE TITLE
FAILED-OUT OF ENERGY - While Triggering Tron Smart Contract. 

### ISSUE THREAD

**Issue by akhilccrb** [trustwallet/wallet-core#2007]
In iOS Swift 

let a_input = TronSigningInput.with{
                $0.transaction = TronTransaction.with{
                    
                    $0.blockHeader = TronBlockHeader.with {
                        $0.timestamp = Int64(timeStFrom)
                        $0.number = Int64(number)
                        $0.version = Int32(version)
                        $0.txTrieRoot = Data(hexString: "\(txTrieRoot)")!
                        $0.parentHash = Data(hexString: "\(parentHash)")!
                        $0.witnessAddress = Data(hexString: "\(witness_address)")!
                    }
                    
                    
                    $0.triggerSmartContract = TronTriggerSmartContract.with{

                        $0.contractAddress = contractAdd

                        $0.callValue = Int64(Callval)
                        $0.ownerAddress = ownerAdd
                        $0.data = Data(hexString: dataFrom)!

                    }
             

                    $0.feeLimit = Int64(feeLmt)
                    $0.timestamp = Int64(timeStFrom)
                    $0.expiration = Int64(timeStFrom) + 10 * 60 * 60 * 1000

                }
                $0.privateKey = Data(hexString: "\(privateKey)")!

            }

 **let output: TronSigningOutput = AnySigner.sign(input: a_input, coin: .tron)**

Output 

{
    "raw_data": {
        "contract": [
            {
                "parameter": {
                    "type_url": "type.googleapis.com/protocol.TriggerSmartContract",
                    "value": {
                        "contract_address": "412be7aacbfafd082e70c13ac12ffcb59d03d8d24b",
                        "data": "095ea7b3000000000000000000000000696137c98cc5fdad4469b6f16b71209e6d79b22400000000000000000000000000000000000000000000000000000002540be400",
                        "owner_address": "419c84ec90ef46e68530893cf3229a1dd695b8b457"
                    }
                },
                "type": "TriggerSmartContract"
            }
        ],
        "expiration": 1644361500000,
        "fee_limit": 1000000000,
        "ref_block_bytes": "b797",
        "ref_block_hash": "73b038e6f9216e3e",
        "timestamp": 1644325500000
    },
    "signature": [
        "54ff6135949b70363550da204e5c9a20643a39a80e60981cdeb78f133787a9d13ed3d03926760eb73a0787be390bd862a9fbe989329322bfd7b5e5a0f29e74b800"
    ],
    "txID": "11e32c54f828482ec39da27f2f1ba9bd12e0dd2ae8e79ded01330ec6d4f35317"
}

**I Broadcasted this output to   -     https://api.trongrid.io/wallet/broadcasttransaction** 

Output : 

**Validate signature error: e1daa1a267b390a4417ecef3203b4f2be0914f61daf26e468fad7c7a699818ef6e7069e3f92d04a3bb989d10d1f81dc751f9527cdb3c5bb87c63dd71caef70d801 is signed by TT4Wjcp3TPhmFDoMsrtXwKFXJxcHEeV73t but it is not contained of permission.**

**Comment by hewigovens** [comment]
Make sure you have the right private key?

**Comment by akhilccrb** [comment]
Yes, Private key is right.

**Comment by zhcandroid** [comment]
> 是的，私钥是对的。

我也遇到了同样的问题 请问您的问题解决了吗？
