### ISSUE TITLE
suggestFee for EIP1559

### ISSUE THREAD

**Issue by BreakZero** [trustwallet/wallet-core#2009]
**Describe the bug**
most of time we get the `maxPriorityFee` is bigger than `baseFee`. from the code return:
 ```
return json{
        {"baseFee", toString(baseFee)},
        {"maxPriorityFee", toString(tip)},
    };
```
and check from [example](https://github.com/zsfelfoldi/ethereum-docs/blob/master/eip1559/feeHistory_example.js), maybe
```
return json{
        {"baseFee", toString(baseFee + tip)},
        {"maxPriorityFee", toString(tip)},
    };
```

**Comment by hewigovens** [comment]
We actually don't use this method in the app right now, going to remove it
