### ISSUE TITLE
[Android]  change set(CMAKE_CXX_VISIBILITY_PRESET hidden) to set(CMAKE_CXX_VISIBILITY_PRESET default)

### ISSUE THREAD

**Issue by hnord-vdx** [trustwallet/wallet-core#2013]
I am not so familiar with cmake but I am wondering what implications changing:
`set(CMAKE_CXX_VISIBILITY_PRESET hidden)` to ` set(CMAKE_CXX_VISIBILITY_PRESET default)`
would have? (in CMakeLists.txt)

The setting is causing dart ffi to throw lookup errors on android (when using TrustWalletCore to develop flutter applications).

By changing the setting it would allow the flutter community to directly pull the library from this repo instead of building and hosting a custom library for flutter.

**Comment by catenocrypt** [comment]
Which CMakeLists.txt do you mean, the main one in the root folder?

I wonder that this change can affect the size of the built library.  @hewigovens ?

**Comment by hnord-vdx** [comment]
Yes the main one: [/CMakeLists.txt](https://github.com/trustwallet/wallet-core/blob/a771f38d3af112db7098730a5b0b9a1a9b65ca86/CMakeLists.txt)

**Comment by hnord-vdx** [comment]
@hewigovens Alright, I compiled two versions on macOS (libTrustWalletCore.a):

Original /CMakeLists.txt
`set(CMAKE_CXX_VISIBILITY_PRESET hidden)` yields 220.7 mb

Modified  /CMakeLists.txt
`set(CMAKE_CXX_VISIBILITY_PRESET default)` yields 220.7 mb

It doesn't seem to affect the binary size. Could there be a difference in size when compiled for android?

**Comment by hnord-vdx** [comment]
@hewigovens Android build size (trustwalletcore.aar):

Original /CMakeLists.txt
`set(CMAKE_CXX_VISIBILITY_PRESET hidden)` yields 15.8 mb

Modified /CMakeLists.txt
`set(CMAKE_CXX_VISIBILITY_PRESET default)` yields 15.8 mb

The problem only arises when running flutter on android. I will need to investigate more, but dart ffi accesses the exported C interfaces defined in the `TW<>.h` files. To give you an example; when trying to generate a wallet from a mnemonic phrase this function `TWStringCreateWithUTF8Bytes` can not be looked up.

**Comment by hewigovens** [comment]
I think we need to explicitly add `__attribute__((visibility("default")))` to `TW<>.h` for shared libraries and keep `set(CMAKE_CXX_VISIBILITY_PRESET hidden)`

**Comment by hnord-vdx** [comment]
We could also create a module definition file. But I don't know which option is the easiest to implement and maintain.

**Comment by hewigovens** [comment]
Feel free to open a pr for this, we'd like to merge it as long as it doesn't affect other language builds

**Comment by hnord-vdx** [comment]
@hewigovens Wouldn't explicitly exporting functions have the same effect to the binary size as changing the preset? Btw as I don't use c or c++ I don't think im the best candidate for that pr

**Comment by hewigovens** [comment]
Those interfaces in `TW<>.h` are expected visible (won't affect much binary size), we probably need to define a macro for `__attribute__((visibility("default")))`, cmake might help generate it

**Comment by hewigovens** [comment]
Windows port had similar issue, you may refer to this commit: https://github.com/kaetemi/wallet-core-windows/commit/0b235b650261979a664cd87d05121c5d5ea6a9bf
