### ISSUE TITLE
Add support for the Cronos EVM chain

### ISSUE THREAD

**Issue by zhdanovichq** [trustwallet/wallet-core#2014]
## Description

Name: Crypto.com Coin / https://cronos.crypto.org/ 
HD Derivation Scheme: BIP-44 `m’/44’/60’/0’/0`
Symbol: CRO
Documentation: https://cronos.crypto.org/docs/getting-started/
Reason: The cronos is a very promising project! According to the defillama website, the cronos chain is in 9th place in the value of TVL.

**Comment by catenocrypt** [comment]
Crypto.org CRO is supported, see https://github.com/trustwallet/wallet-core/blob/master/registry.json#L1746
The mentioned derivation path belongs to Celo, BTW.

**Comment by zhdanovichq** [comment]
@catenocrypt Oh nooo...

You mention Crypto.org Chain. 
But I created an issue about Cronos Chain integration in Trust wallet.
🥺
