### ISSUE TITLE
[Stellar] Add Claimable Balances support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2016]
Claimable Balances allow sender sending asset to receiver without preset a trustline

https://developers.stellar.org/docs/glossary/claimable-balance/

**Comment by catenocrypt** [comment]
Create Claimable Balance operations needs following info:
- asset
- amount
- list of claimants.  Here we would used only one claimant, and always use Unconditional (i.e., not use claiming time conditions).

It returns a BalanceID, which is input for Claim Claimable Balance. 

To clarify the use case supported in Trust Wallet:
- will Trust Wallet perform Create Claimable Balance, or Claim Claimable Balance, or both?
- how will the BalanceID parameter get to the claimer?

**Comment by hewigovens** [comment]
@catenocrypt This process will be similar to Nano, Sender creates `Claimable Balance` and receiver claims it. There is an API to list all claimable balances https://developers.stellar.org/api/resources/claimablebalances/list/
