### ISSUE TITLE
Invalid session when i try to connect with walletconnect 2.0

### ISSUE THREAD

**Issue by anmoldh121** [trustwallet/wallet-core#2035]
I am making a dapp on react native with solana. when i try to connect it with walletconnect 2.0 it says `Invalid session`. I am using deep for connection my session uri looks like this. `https://link.trustwallet.com/wc?uri=wc%3Ab13ca511deb8ab51a7db6f496456fda04a9741d9a29f3fb83ecdf8e623511284%402%3Fcontroller%3Dtrue%26publicKey%3Da1e961850211c11ea99f8f89743073e7e9be0a2d6154071fffb2d15dae163969%26relay%3D%257B%2522protocol%2522%253A%2522waku%2522%257D`

**Comment by hewigovens** [comment]
WC2.0 support is working in the proces
