### ISSUE TITLE
Support BIP39 Passphrase

### ISSUE THREAD

**Issue by besoeasy** [trustwallet/wallet-core#2045]
**Is your feature request related to a problem? Please describe.**
Lot of wallets support BIP39 Passphrase, importing those wallets into **trust wallet** is a big mess

**Describe the solution you'd like**
We can use **HDWallet("seed", "Passphrase")** , so its just matter of adding a field in wallet import UI to solve this. 

**Describe alternatives you've considered**
Coinomi wallet has it implemented

**Additional context**
![as](https://user-images.githubusercontent.com/8281782/156166916-21e84d8d-2caf-4c40-87fc-911f7bc6e184.png)

**Comment by hewigovens** [comment]
This feature was removed from Trust for a long time because it caused confusion for ordinary users: if you forget and import your passphrase it might be a totally different wallet.

We might consider this feature later but let's close this issue for now
