### ISSUE TITLE
Transaction data format version for BitcoinCash

### ISSUE THREAD

**Issue by ne3Vubeki** [trustwallet/wallet-core#2047]
**Describe the bug**
0100000001e28c2b95529315989.....
-^
version 1

**To Reproduce**
[swift/Tests/Blockchains/BitconCashTests.swift](https://github.com/trustwallet/wallet-core/blob/377d1942cc7dff3af9c9b6c7595a6d8f21463ed0/swift/Tests/Blockchains/BitconCashTests.swift)

**Expected behavior**
For bitcoin cash, I need to use version 2.
How to set up bitcoin cash signature for version 2:
0200000001e28c2b95529315989.....
-^

**Comment by hewigovens** [comment]
Isn't it compatible? What is the difference between 1/2 on bitcoin cash?

**Comment by ne3Vubeki** [comment]
My node is running version 2 and is returning an error for signing version 1.
Here is the description for version 2:
https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/transaction.md#transaction-requirements
https://apexpl.github.io/bitcoin_cash_sv_abc_transaction_signatures.html

**Comment by hewigovens** [comment]
Which node are you running? `Bitcoin Cash Node:23.1.0(EB32.0)` accepts version 1 tho

**Comment by ne3Vubeki** [comment]
Thank you, I figured it out, you can close it.

**Comment by jiuyaopinyin** [comment]
> Thank you, I figured it out, you can close it.

hello,sir, Can you share your solution? I also need to modify the bitcoin version now, but I don't know how to modify it.
