### ISSUE TITLE
npm missing leads to failure to build the project and generate the Xcode project

### ISSUE THREAD

**Issue by ivrusuboca** [TrustWallet/wallet-core#205]
If the Node.js package manager (npm) is not found , the project does not get built nor the Xcode project file(s) get generated. 

Current behaviour, as it happens on my machine : 

[.....]
Compile Swift Module 'SwiftProtobuf' (77 sources)
Compile Swift Module 'Conformance' (4 sources)
Compile Swift Module 'SwiftProtobufPluginLibrary' (18 sources)
Compile Swift Module 'protoc_gen_swift' (18 sources)
protoc-gen-swift 1.3.1
#### Generating files... ####
~/work/public/walletcore/js ~/work/public/walletcore
tools/generate-files: line 31: npm: command not found

**Comment by alejandro-isaza** [comment]
Fixed with https://github.com/TrustWallet/wallet-core/pull/206
