### ISSUE TITLE
iOS export mnemonic crash

### ISSUE THREAD

**Issue by zColdWater** [trustwallet/wallet-core#2055]
**Describe the bug**
step1: create a wallet from privatekey 
step2: export mnemonic from this wallet 

<img width="1662" alt="截屏2022-03-04 上午10 22 34" src="https://user-images.githubusercontent.com/13477474/156686986-bc2d0860-7fcd-4b3e-b6bc-e61ed136ccda.png">

**Comment by hewigovens** [comment]
That's expected crash, you can't export mnemonic from private key

**Comment by zColdWater** [comment]
@hewigovens  So let's say we read a wallet using keystore.json, so how do I know if wallet has mnemonic?

**Comment by hewigovens** [comment]
Do you have sample code? catch exception or check return value is nil

**Comment by zColdWater** [comment]
@hewigovens  
like this, user can use import privatekey for generate a wallet, but I dont known wallet type (mnemonic or privatekey), so if I try export mnemonic will crash, wont to catch closure. 

Chinese: 如果用户通过 keystore.json 的文件导入一个钱包，那么我又不知道钱包的类型，我怎么知道这个钱包有没有助记词，如果我调用导出助记词的方法，会直接强制解包crash，并不会走catch的回调。

``` swift
func example() throws -> String {
    let keystoreDirectory = URL.init(fileURLWithPath: "exmaple")
    let keyStore = try KeyStore(keyDirectory: keystoreDirectory)
    
    // User import wallet from privatekey
    let data = Data(hexString: "---------privatekey---------")
    let privateKey = PrivateKey(data: data!)
    let wallet = try keyStore.import(privateKey: privateKey!, name: "example wallet", password: "password", coin: .ethereum)
    
    // keyStore.wallets -- I dont known which wallet has mnemonic or not
    return try keyStore.exportMnemonic(wallet: wallet, password: "password")
}

do {
    let mnemonic = try example() // will crash 
    print("mnemonic:\(mnemonic)")
} catch let ex {
    print("ex:\(ex)")
}
```

**Comment by zColdWater** [comment]
May I have your TG bro? 
可以TG加个好友吗，大佬，我想咨询下这个问题。
@hewigovens

**Comment by AlleniCode** [comment]
You can't export a wallet mnemonic if you import it with private key, but you can export the mnemonic and private key if you import it with mnemonic.

Chinese: 当你通过私钥导入一个钱包的时候它是不能导出助记词的，但是你通过助记词导入钱包的话可以同时导出助记词和私钥。当你无法判断是否能导出助记词的时候，你就需要在创建和导入的时候做个标记了。
@zColdWater

**Comment by zColdWater** [comment]
例如：像我下面的keystore，密码是password，ETH Coin = 60 的钱包。 
我创建的时候是HD钱包，带助记词的，然后我故意改了下面的 type 字段，从 mnemonic 改成 private-key，然后导入 TrustWallet App，我发现TrustWallet是可以知道这个keystore有助记词的。 所以我想知道我们导入这个keystore生成一个钱包，是如何知道他是有助记词的还是没有助记词的。 因为我没找到Wallet这个类型有哪个属性可以判断这个。 @AlleniCode  大佬 

```json
```
{"activeAccounts":[{"address":"0x65e278ffAfcc84Ca592AA0d190C0875ef3F04EC2","coin":60,"derivationPath":"m/44'/60'/0'/0/0"}],"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"9e5b1c5477a0db61eff5b5800d5a03d3"},"ciphertext":"bb71916ad6278821f15db168f19cfe13470781eb2778de794718f71fef1a48dea5d819f9da1a6eb2959a5c4dccd142ba82b3b2dd78ae46e1fa0fd22617942832ab36ac3912b1745fc9","kdf":"scrypt","kdfparams":{"dklen":32,"n":16384,"p":4,"r":8,"salt":""},"mac":"88d7353d85d613e7f760a1b304b5c870bc9b6389adc8a7eae28e65ee2772644c"},"id":"1fb4a782-3ab6-4be9-a431-639bd4631d72","name":"123","type":"private-key","version":3}
```
```

**Comment by AlleniCode** [comment]
> 
Keystore is same as private key, can't export mnemonic.

Chinese: Keystore 和 私钥一样，无法导出助记词。（如果你是在 TrustWallet 创建了一个 HD 钱包，它是可以导出助记词和私钥的（keystore）, 但是你再次导入这个私钥或者keystore的时候，我就不清楚里面的存储逻辑了）

**Comment by zColdWater** [comment]
@AlleniCode 大佬，我现在的逻辑是，我用 trustwallet-core 代码创建一个HD钱包，存在keystore里面，然后将这个keystore导入trustwallet app，它是能够知道我的这个keystore是有助记词的（有显示助记词的这一项），即使我改了 keystore json 里面的 type 字段，从 mnemonic 改成 private-key，所以我就想知道 trustwallet 是如何知道这个keystore是有助记词的？ 

你其实把我上面提到的json复制导入到trustwalllet，密码是password，coin_type是ETH，你就能看到 trustwallet app 是知道这个钱包有助记词的，但是这个是我用代码在我本地生成的。

**Comment by zColdWater** [comment]
但是我查看了 trustwallet-core 的API，没有发现能判断钱包(Wallet)是否有助记词的属性，所以我去导出助记词，如果这个keystore没有助记词，那么就crash了，强制解包了。

**Comment by hewigovens** [comment]
Keystore is just an encrypted json file, it could be mnemonic or private key. If you import a keystore that generated from wallet core, there is a `type` field inside the keystore json, you can check it by yourself.

**Comment by zColdWater** [comment]
> Keystore is just an encrypted json file, it could be mnemonic or private key. If you import a keystore that generated from wallet core, there is a `type` field inside the keystore json, you can check it by yourself.
I see, but I wonder known why TrustWallet App can recognize has mnemonic or not even though no `type` field. 
我可以通过field去判断，但是我想知道 trustwallet app 为什么可以不用这个type的字段，也可以知道有没有助记词。 @hewigovens  谢谢

**Comment by hewigovens** [comment]
Coincidence, it happens to be a mnemonic (you just changed the type) and wallet core will try to decode it when you call the `exportMnemonic` method

**Comment by AlleniCode** [comment]
> 

If you want to test the keystore, you should find a real keystore exported from TrustWallet, but not just change the 'type' filed. You can import a privete key in TrustWallet and export it's ketstore to test it, I think it won't crash again.

Chinese: 你要是想测试一下 keystore 是否能够导出助记词，你应该再试一个其他的 keystore, 用另一个钱包（不在 TrustWallet 里面）的私钥导入再导出它的 keystore，而不是直接去更改 keystore 里面的 type 字段。

`我可以通过type这个field去判断，但是我想知道 trustwallet app 为什么可以不用这个type的字段，也可以知道有没有助记词。`
这个可以通过地址去找，之前出现过同样的地址的话，就去查一下是否有存储助记词之类的。。。

**Comment by zColdWater** [comment]
OK thx guys, I see, but I try create hd wallet from other app, and then export keystore json, and then import to trustwallet for check.

Chinese: 谢谢各位大佬，我尝试从其他app创建 HD钱包（带助记词），然后导出keystore json然后再导入进trustwallet 看看。 

@AlleniCode  @hewigovens

**Comment by zColdWater** [comment]
> > 
> 
> If you want to test the keystore, you should find a real keystore exported from TrustWallet, but not just change the 'type' filed. You can import a privete key in TrustWallet and export it's ketstore to test it, I think it won't crash again.
> 
> Chinese: 你要是想测试一下 keystore 是否能够导出助记词，你应该再试一个其他的 keystore, 用另一个钱包（不在 TrustWallet 里面）的私钥导入再导出它的 keystore，而不是直接去更改 keystore 里面的 type 字段。
> 
> `我可以通过type这个field去判断，但是我想知道 trustwallet app 为什么可以不用这个type的字段，也可以知道有没有助记词。` 这个可以通过地址去找，之前出现过同样的地址的话，就去查一下是否有存储助记词之类的。。。

U are right thx guys
