### ISSUE TITLE
Present EIP-712 nicer

### ISSUE THREAD

**Issue by anxolin** [trustwallet/wallet-core#2058]
**Is your feature request related to a problem? Please describe.**
When signing any offchain data using EIP-712, TrustWallet present the user in a non-user friendly way.

It presents just a JSON blob.

The users have a hard time verifying what they sign, which is a security concern.

**Describe the solution you'd like**
Do something like Metamask do, present the structured data:
![image](https://user-images.githubusercontent.com/2352112/156821337-bbdae374-76e3-4c1e-98d0-521fc3a574ff.png)

**Additional context**
You can try to trade in https://cowswap.exchange/ to validate the feature

**Comment by hewigovens** [comment]
This is a known issue, we will consider improving it and thanks for the report.

**Comment by fafrd** [comment]
Note that this also affects OpenSea NFT listing, which is probably the most popular use case for wallet signatures at the moment. User sees a giant JSON blob.

**Comment by hewigovens** [comment]
Please check latest iOS build in App Store, user can navigate the JSON easily now, Android will follow similar idea later

**Comment by anxolin** [comment]
@hewigovens i just updated the IOS app 7.0, it stills look pretty not user friendly:

![IMG_4863 2](https://user-images.githubusercontent.com/2352112/157775819-19393d2b-06dc-4d22-87fd-a0f339fac0b9.PNG)

**Comment by anxolin** [comment]
I would honestly reopen the issue

**Comment by hewigovens** [comment]
Can you try WalletConnect? Dapp browser will be updated later (just added back finally)
