### ISSUE TITLE
Android call function error.

### ISSUE THREAD

**Issue by leiiiooo** [trustwallet/wallet-core#2063]
**Describe the bug**
For Android:
If I call *StoredKey.accountForCoin* function with the *wallet* is null, it will crash, but for iOS with Swift code, it will create an account automatic with the target coin type. 

**To Reproduce**
1.  create *PrivateKey* 
2. call *StoredKey.importPrivateKey*
3. call *StoredKey.wallet* get a wallet
4. call *StoredKey.accountForCoin* with step 3 wallet.

**Expected behavior**
Get a new account, same logic with iOS.

**Comment by hewigovens** [comment]
Not a real issue, please check `null` before using it

**Comment by leiiiooo** [comment]
Thanks, but why iOS can do that? Why do we have different logic for public API? One more question, if I want to create *Account* with the target *CoinType*, how to make it?

**Comment by hewigovens** [comment]
Swift binding has `Keystore` wrapper on top of C++ `StoredKey` implementation, Java doesn't have this equivalent yet

**Comment by leiiiooo** [comment]
大佬，那我现在想要导入一个private key并且保存为一份keystore文件，我该如何操作呢？我看了Android的测试用例，也没有相关的逻辑只能参考Swift代码？能给个方向吗？🙏

**Comment by badjone** [comment]
I met the same problem, how to solve it

**Comment by badjone** [comment]
@leiiiooo 大兄弟，这个问题有解决方案吗
