### ISSUE TITLE
Android Sign transaction with PrivateKey

### ISSUE THREAD

**Issue by HemangiVekaria** [trustwallet/wallet-core#2066]
Hello, Sorry i added this under bug label.

I am using this library for wallet creation and signing transaction. I have added functionlity of import wallet by adding 12/24 word mnemonic. Now i want to add functionlity to import wallet with PrivateKey. So as i read https://github.com/trustwallet/wallet-core/discussions/1812 here  if import wallet using private key then no need to use HDWallet. 
So in this case i can retrieve address of wallet by using something like this  

            BigInteger key = new BigInteger(privateKey, 16);
            String cleanPrivateKey = Numeric.cleanHexPrefix(privateKey);
            ECKeyPair keypair = ECKeyPair.create(key);
            String addresss = Numeric.prependHexPrefix(Keys.getAddress(keypair));

I got correct address with this. Now the question is Here Private key is string with 64 character long. So at a time of signing transaction doing it like this 
byte[] decrypted =  <byte [] of private key which received from new HDWallet() object>
 signinginput_er.setPrivateKey(ByteString.copyFrom(decrypted));
**AnySigner.sign(signerInputs, CoinType.ETHEREUM, Ethereum.SigningOutput.parser());

If i have a string private key then how can i use that for siging transaction same as above. 
Can anyone help please?

**Comment by hewigovens** [comment]
Are you using `ECKeyPair` from web3j? It looks like the private key is a hex string? just decoded into raw bytes to use

**Comment by HemangiVekaria** [comment]
When user enter Private key which is 64 character long at that time i use ECKeyPair to get address of wallet from that PrivateKey. I will try by converting that hexa string to byte[] and then use that for signing.

**Comment by HemangiVekaria** [comment]
Hey @hewigovens Thanks for the help. Converted  Hex Private key to raw bytes and it's work.
