### ISSUE TITLE
Add way to derive extended pubkey for custom account (HDWallet)

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2084]
Method `TWHDWalletGetExtendedPublicKey` derives an extended public key, but always using the default 0 account value (it uses derivation path `m/purpose/coin/0'`.
Add a way to obtain extended public key for non-default accounts.

Triggered by discussion https://github.com/trustwallet/wallet-core/discussions/2081

**Comment by mark2021blue** [comment]
Thank you very much! ! !

**Comment by mark2021blue** [comment]
The final requirement to be realized is to derive the derived address, Derivation Path, public key, etc. only through "BIP32 Extended Public Key" or "Account Extended Public Key"
reference：https://iancoleman.io/bip39/#englis
![2022-03-18 10 49 54](https://user-images.githubusercontent.com/83812275/158928714-4bd68fd5-ef84-4016-8df2-92ea7397f8f2.png)
h

**Comment by mark2021blue** [comment]
great news!
@catenocrypt @hewigovens  Thank you very much! ! !
