### ISSUE TITLE
SPM conflict SwiftProtobuf

### ISSUE THREAD

**Issue by nerzh** [trustwallet/wallet-core#2088]
Sorry for my english

**Describe the bug**
Google FireBase has SwiftProtobuf as a dependency:
.package(
      name: "SwiftProtobuf",
      url: "https://github.com/apple/swift-protobuf.git",
      "1.15.0" ..< "2.0.0"
    ),

but wallet-core has SwiftProtobuf as a dependency too:

.binaryTarget(
            name: "SwiftProtobuf",
            url: "https://github.com/trustwallet/wallet-core/releases/download/2.6.36/SwiftProtobuf.xcframework.zip",
            checksum: "40518a795e841bbd2c7e1f7019357b8e09b321a9c1ea264b0819f85575ac04c2"
        )

Because you have a binary target, this causes a name conflict with SwiftProtobuf.

Please, tell me what to do with it, thanks

**To Reproduce**
1. add Firebase to ios project
2. add wallet-core to the project

**Expected behavior**
No conflict with SwiftProtobuf

**Comment by hewigovens** [comment]
Yes, because wallet core is a binary framework, it needs `SwiftProtobuf` as a binary framework too. The workaround is: download wallet core xcframework from github release and manually add it to your project.

**Comment by nerzh** [comment]
@oliveratkinson-bc it would be great

**Comment by hewigovens** [comment]
@oliveratkinson-bc I agree with you, but wallet core needs special build steps and SPM seems limited (unlike CocoaPods, easy to add scripts) cc @Milerius

**Comment by oliveratkinson-bc** [comment]
It's worth noting that SPM has got some upgrades as of 5.7, one of which is "Package Manager Plugins" that should aid in the ability to script elements of the build pipeline

**Comment by nerzh** [comment]
this article says it's available already in 5.6

https://theswiftdev.com/beginners-guide-to-swift-package-manager-command-plugins

**Comment by oliveratkinson-bc** [comment]
@nerzh yes, but it had issues, became usable in 5.7

**Comment by EvgenV** [comment]
Hi @oliveratkinson-bc ! 
Have you managed to solve this problem? Could you please share with workaround?

**Comment by nerzh** [comment]
🙄

**Comment by MaksymVereshchaka** [comment]
I would like to know if there are any results?

**Comment by MaksymVereshchaka** [comment]
@nerzh @oliveratkinson-bc @EvgenV 
I would like to know if there are any results?

**Comment by oliveratkinson-bc** [comment]
@MaksymVereshchaka I have not found a workaround for this issue

**Comment by nerzh** [comment]
no, I don’t understand why the package was called that at all. You could also call the wallet not Trustwallet but Googlewallet, why not ? 😀

**Comment by tysonwil** [comment]
@nerzh were you ever able to find a workaround to this?

**Comment by dinhnhat0401** [comment]
@tysonwil @nerzh @oliveratkinson-bc take a look at this PR. Please give a thumb up if this fix your issue.
https://github.com/trustwallet/wallet-core/pull/3599
