### ISSUE TITLE
[Thorchain] Cosmos v0.45 SDK upgrade

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2089]
Thorchain disables standard Cosmos `cosmos-sdk/MsgSend` and uses its own `thorchain/MsgSend` https://gitlab.com/thorchain/thornode/-/blob/develop/proto/thorchain/v1/x/thorchain/types/msg_send.proto

```protobuf
syntax = "proto3";
package types;

option go_package = "gitlab.com/thorchain/thornode/x/thorchain/types";

import "cosmos/base/v1beta1/coin.proto";
import "gogoproto/gogo.proto";

message MsgSend {
  bytes from_address = 1  [(gogoproto.casttype) = "github.com/cosmos/cosmos-sdk/types.AccAddress"];
  bytes to_address = 2  [(gogoproto.casttype) = "github.com/cosmos/cosmos-sdk/types.AccAddress"];
  repeated cosmos.base.v1beta1.Coin amount = 3 [(gogoproto.castrepeated) = "github.com/cosmos/cosmos-sdk/types.Coins", (gogoproto.nullable) = false];
}
```

The difference is: `from_address` and `to_address` type is `bytes` not `string`

**Comment by catenocrypt** [comment]
Note: message type was already `thorchain/MsgSend`, but Cosmos message was reused unmodified content-wise.  With the change in types, a separate proto file is needed.
