### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION

### ISSUE THREAD

**Issue by ne3Vubeki** [trustwallet/wallet-core#2094]
Hello, in my dart plugin when using TrustWalletCore, an error occurs:

    java_vm_ext.cc:577]     JNI DETECTED ERROR IN APPLICATION: mid == null
    java_vm_ext.cc:577]     in call to CallIntMethod
    java_vm_ext.cc:577]     from int wallet.core.jni.BitcoinScript.hashTypeForCoin(wallet.core.jni.CoinType)
Methods for fixes indicated in the issue: https://github.com/trustwallet/wallet-core/issues/961
don't help.
How can this error be corrected?

**Comment by ne3Vubeki** [comment]
I was able to run without errors by disabling minification. At the same time, this application, which is so voluminous after connecting the TrustWalletCore library, has increased even more. 

Is it possible to split the library into parts?
For example, I use only the functionality of signing transactions

**Comment by hewigovens** [comment]
No plan to split the library, it cause a hassle the benefits
