### ISSUE TITLE
SDK is not supported by compiler

### ISSUE THREAD

**Issue by nerzh** [trustwallet/wallet-core#2099]
**Describe the bug**
Failed to build module 'WalletCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)')

**To Reproduce**
build with xcode 13.3

Please tell me how to solve this problem ?

**Comment by hewigovens** [comment]
Could you please check other code calling wallet core? Make sure it can compile. Xcode doesn't show real compiling error sometimes; we will also update Xcode version on CI later

**Comment by nerzh** [comment]
sorry my english is very bad.

If I add via JPM to a clean project, the build succeeds, but I can't use JPM because of this issue: https://github.com/trustwallet/wallet-core/issues/2088

If I use the way to add this package to my project through the framework, then I run into another problem, which I described above.

I checked, I created a clean project and added the package as a framework and immediately caught this error:
**Failed to build module 'WalletCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)', while this compiler is 'Apple Swift version 5.6 (swiftlang-5.6.0.323.62 clang-1316.0.20.8)')**

**Comment by nerzh** [comment]
So, 

via SPM == conflict with SwiftProtobuf
via xcframework == SDK is not supported by the compiler

**Comment by hewigovens** [comment]
Are you using Xcode 13.3? I will try it today

**Comment by nerzh** [comment]
Yes, Xcode Version 13.3 (13E113)

**Comment by hewigovens** [comment]
Just tried, it works for me tho
![image](https://user-images.githubusercontent.com/360470/160313241-0bdcca2a-240d-4331-8494-aa7a49001af3.png)

**Comment by nerzh** [comment]
I didn't add the Protobuf xcframework ...
