### ISSUE TITLE
Can we support Java jar support for aar is not support in Pure java env.?

### ISSUE THREAD

**Issue by oday0311** [trustwallet/wallet-core#2108]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Java version Sdk is needed. and will not be too much work change from android sdk.

**Describe alternatives you've considered**

**Additional context**

**Comment by hewigovens** [comment]
I think you can use the library in Java, just the demo and tests are written in Kotlin

**Comment by oday0311** [comment]
no, what I mean is pure java env, current sdk support android java, but java server env.
