### ISSUE TITLE
[Ethereum] Signing transaction with WalletConnect returns invalid tx on iOS

### ISSUE THREAD

**Issue by Hamidrezana** [trustwallet/wallet-core#2116]
I'm trying to sign a transaction from my Dapp with wallet connect.
Transaction data is something looks like this:

```
{
  data: "0x731133e9000000000000000000000000f5bf2d36c2a5dad449630d1e5550a90604ac12910000000000000000000000000000000000000000000000000000000000001286000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000",
  from: "0xf5BF2d36C2A5Dad449630d1E5550a90604Ac1291",
  gasLimit: "0x493e0",
  gasPrice: "0x700014a8c",
  nonce: "0xa",
  to: "0x8c0418db865964ca3f6d04f1d6356cc7f896c73f" 
}
```

but signed transaction hash that returned is invalid.

```
02f9011381890a850700014a87850700014a87830493e0948c0418db865964ca3f6d04f1d6356cc7f896c73f80b8a4731133e9000000000000000000000000f5bf2d36c2a5dad449630d1e5550a90604ac12910000000000000000000000000000000000000000000000000000000000001286000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000c080a05c2bb8a56f03e275f4ad623c176a7fa93c9879d63b29c9e98336435f72073e70a06fad8dac313291877e91c324aa82d3d4774a4755d4fac96f8a74cc2cfd1a4fda
```

This is works well on android but not on iOS.

**Comment by hewigovens** [comment]
Did you send eth_signTransaction or eth_sendTranaction?

**Comment by hewigovens** [comment]
eth_signTransaction expects raw tx, eth_sendTransaction expects tx hash, I would say ios is correct

**Comment by Hamidrezana** [comment]
I'm using standalone client as in [doc](https://docs.walletconnect.com/quick-start/dapps/client#sign-transaction-eth_signtransaction)

I have add my transaction data schema and tx hash in issue.

**Comment by hewigovens** [comment]
The comment says it's signed tx, you need to broadcast it
```js
// Sign transaction
connector
  .signTransaction(tx)
  .then((result) => {
    // Returns signed transaction
    console.log(result);
  })
```

**Comment by vcoolish** [comment]
Could you please send what android returns?

**Comment by Hamidrezana** [comment]
@vcoolish This what I got from android device for that transaction:

```
0xf9010c0a850700014a8c830493e0948c0418db865964ca3f6d04f1d6356cc7f896c73f80b8a4731133e9000000000000000000000000f5bf2d36c2a5dad449630d1e5550a90604ac12910000000000000000000000000000000000000000000000000000000000001286000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000820135a09dd9aed57364d444329c3e61c395f5b6f21bda839a4dbddf4c67b1243acfed8da07a2ccce54b2cfb91fbb2a0c59d76aa944c65212efa6f7e58f71d89a69b3d0248
```

**Comment by Hamidrezana** [comment]
@hewigovens 

I knew that but *result* is no correct and I can not broadcast it.

It is incorrect on iOS devices, it is correct on android

**Comment by hewigovens** [comment]
It looks just lack of 0x prefix? Can we test your dapp somehow?

**Comment by Hamidrezana** [comment]
I don't think the problem is just 0x.
It's on my local.

I can add this note that I test with other wallet on iOS, and it is correct on other wallet.

**Comment by hewigovens** [comment]
@Hamidrezana Debugging this now

**Comment by rsrbk** [comment]
@Hamidrezana I've tried to sign a similar tx to yours (only r/s/v is different) and it produced a valid hash:
https://www.ethereumdecoder.com/?search=0xf9010a0a850700014a8c830493e0948c0418db865964ca3f6d04f1d6356cc7f896c73f80b8a4731133e9000000000000000000000000f5bf2d36c2a5dad449630d1e5550a90604ac1291000000000000000000000000000000000000000000000000000000000000128600000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000026a0b3895913501cae703aca7bda7951a854a83d17f6e5eeb9371d00b0573e03471aa017694d053a3cbb21cb84c9e816b99cf0248978cc2f360a4b53f55be8f9549589

Could you give more details about your which app do you use and if the app version is the latest? Also where exactly you take the hash from?

**Comment by rsrbk** [comment]
@Hamidrezana 
Trust Wallet for iOS uses [EIP-1559](https://consensys.net/blog/quorum/what-is-eip-1559-how-will-it-change-ethereum/), for the gas fee format when signing even when transaction data provides it in the old way (via `gasPrice`). This is done to save users eth on gas fees.

You need to make sure that the way you decode the hash takes EIP-1559 into account. Here is an example with the hash that you provided here: https://go.dev/play/p/apWm9QQhOKu

@vcoolish we probably need to upgrade TW Android for the similar logic.

**Comment by vcoolish** [comment]
We do have similar logic on fees.

**Comment by Hamidrezana** [comment]
@rsrbk @hewigovens Does it make a difference for broadcasting signed transaction hash?

I just want to get signed transaction hash from wallet and manually broadcast it.
