### ISSUE TITLE
Add zkSync v2 support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2122]
Those are EVM compatible zk rollup L2 networks

- https://v2-docs.zksync.io/dev/zksync-v2/handling-of-eth.html
- https://starknet.io/building-on-starknet/developer-tools/

**Comment by ZahraDress** [comment]
اضافه کنید

**Comment by AyushBherwani1998** [comment]
@hewigovens is anyone working on the issue? If not, I would like to take the issue.

**Comment by hewigovens** [comment]
@AyushBherwani1998 we're refactoring to support any evm chain without changing code: https://github.com/trustwallet/wallet-core/issues/2214, this issue is on hold

**Comment by punithbm** [comment]
Hi @hewigovens, Is anyone picking StarkNet integration as well ? or I can look into it

**Comment by hewigovens** [comment]
@punithbm https://github.com/trustwallet/wallet-core/issues/2679 need to fix this, contributions are welcome
