### ISSUE TITLE
Reorganize source files

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2134]
For source files, an organizing principle is:
- In folder where there are many subfolders, there should not be files, with the exception of small number of files.

This does not currently hold for several folders, e.g.:
- src has many chain subfolders, and also many generic files

Some recommendations:
- Move src/CHAIN subfolders to src/blockchains/CHAIN
- Move src/SOURCE.cpp to src/generic/SOURCE.cpp, but src/interface can stay.
- Similar structure under tests

It is important that any move is done properly via `git`, to correctly preserve history.

**Comment by Dawqq77** [comment]
https://coinmarketcap.com/currencies/chainlink/

**Comment by hewigovens** [comment]
let's close this for now
