### ISSUE TITLE
Add Beacon SDK for connection & interaction with Dapps on Tezos Blockchain

### ISSUE THREAD

**Issue by dvkam** [trustwallet/wallet-core#2140]
**Is your feature request related to a problem? Please describe.**
Trustwallet supports Tezos. But you cannot use Trustwallet to connect and interact with Dapps on the Tezos Blockchain.
Many users ask in chats that they have/use Trustwallet -How to connect? And the answer is its not possible, they need to install other wallets like Temple or Kukai.

**Describe the solution you'd like**
In order for Trustwallet to be able to connect and interact with Dapps on the Tezos Blockchain, Trustwallet needs to implement the beacon interface. This can be done without changes to the beacon sdk.
The github link to the beacon sdk: https://github.com/airgap-it/beacon-sdk
Documentation: https://docs.walletbeacon.io/
Telegram Chat for eventual support: https://t.me/AirGap

Once integrated the trustwallet will get added to the supported list and will be visible as option to connect with.

**Describe alternatives you've considered**
No alternative considered.

Example that happens often
![grafik](https://user-images.githubusercontent.com/82422481/162638915-f8a67352-4860-4cc8-949b-9757d6ddbd8a.png)

**Comment by Reudlak** [comment]
Possibility to use trustwallet with tezos dapps would be awesome

**Comment by hewigovens** [comment]
I checked that Beacon has iOS and Android SDK, so no need to implement in wallet core side, I will close this issue for now (Added to our internal product backlog). If Trust app decides to integrate Tezos dapps, will use mobile sdk directly.

**Comment by BearCooder** [comment]
So for now this integration is frozen? Hopefully it gets picked up soon.. 
Saw this discussion also https://github.com/trustwallet/wallet-core/discussions/2124

**Comment by BearCooder** [comment]
@hewigovens this might be of interest for you regarding walletconnect: https://github.com/airgap-it/beacon-sdk/issues/351#issuecomment-1203860144

**Comment by hewigovens** [comment]
@BearCooder thanks for the update , we're working on WalletConnect v2 integration

**Comment by Primate411** [comment]
Tezos is king. The sooner you come to support, the more OG will be your future standing and support
