### ISSUE TITLE
Add support for Tezos NFT / FA2 tokens

### ISSUE THREAD

**Issue by dvkam** [trustwallet/wallet-core#2141]
**Is your feature request related to a problem? Please describe.**
Really many users use Trustwallet with Tezos and put their Tezos Wallet to receive Tokens or NFTs on Tezos. But once they receive them they cant see it in Trustwallet because Trustwallet does not support the Tezos token standard. So no possibility to use or transfer.

**Describe the solution you'd like**
In order for Trustwallet to support Tezos tokens and NFTs, Trustwallet needs to implement the Tezos token standard FA2.
FA2 Standard Link: https://gitlab.com/tezos/tzip/-/blob/master/proposals/tzip-12/tzip-12.md
FA1.2 Standard: https://gitlab.com/tezos/tzip/-/blob/master/proposals/tzip-7/tzip-7.md

Both standards are actively used although FA2 is the newer one.

If you have questions or need help with integration the Tezos Commons Foundation can help
https://tezoscommons.org/contact/

**Describe alternatives you've considered**
An alternative for the end user is to export trustwallet keys and import them into other wallets that support tezos tokens. Its a solution but not really viable.

**Additional context**
Examples
![grafik](https://user-images.githubusercontent.com/82422481/162639172-4775e0ac-6a88-4edb-8f52-dc29d2a43452.png)
![grafik](https://user-images.githubusercontent.com/82422481/162639198-7659268f-f55e-48db-99aa-5b9a81bc2db9.png)

**Comment by BearCooder** [comment]
Will this integration happen in the next few weeks/months?

**Comment by hewigovens** [comment]
@BearCooder Yes, low priority

**Comment by Milerius** [comment]
Interesting doc: https://netezos.dev/docs/call-smart-contracts.html

**Comment by Primate411** [comment]
Supporting the Tezos FA standards will onboard thousands of real long term active users into your wallet ecosystem.
