### ISSUE TITLE
Move logic from `TWAnyAddress` to C++ class `AnyAddress`

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2143]
All the logic are done in `TWAnyAddress.cpp`, not a good practice, we'd like to implement all the logic in cpp classes and keep C interface simple and stupid, just Like `TWHDWallet.cpp` and `HDWallet.cpp`

**Comment by catenocrypt** [comment]
This is not valid any more, logic has been removed from `TWAnyAddress.cpp` already through #2300 . See also #2269 
https://github.com/trustwallet/wallet-core/blame/master/src/interface/TWAnyAddress.cpp

Closing.
