### ISSUE TITLE
Doge signing error

### ISSUE THREAD

**Issue by serin-sebastian** [trustwallet/wallet-core#2156]
I have signed a doge transaction and when I try to broadcast the transaction , I got the following error

![Screenshot (75)](https://user-images.githubusercontent.com/94120034/164683840-67155e38-c184-4995-87ff-c5344fd1eb0e.png)
![Screenshot (74)](https://user-images.githubusercontent.com/94120034/164684137-b7177d73-2523-4a30-a24b-739413d94677.png)

**Comment by hewigovens** [comment]
try reversing your txid

**Comment by serinkuriapilly1997** [comment]
> try reversing your txid

I have already tried that , but the error still exist.  when i decode the transaction the txid is shown as interchanged ( adjacent characters interchanged). for example  f30944c3f6a0670f4e732a98079d2ddfa22b312fbb4c96fad225b21cfbf5c235 is shown as 3f90443c6f0a76f0e437a28970d9d2fd2ab213f2bbc469af2d522bc1bf5f2c53 while d
![Screenshot (76)](https://user-images.githubusercontent.com/43596599/165064587-c28e924c-7e77-47ea-b4be-3dbdd2df301a.png)
ecoding.

**Comment by hewigovens** [comment]
how did you reverse it? you need to decode the tx id as bytes then reverse

**Comment by serin-sebastian** [comment]
I tried this but when I try to decode then server error (500) occurred . I am attaching my code sample here
![doge_error](https://user-images.githubusercontent.com/94120034/165239910-7fdb448c-6c48-4bab-8447-a4b53e24c128.png)
![Screenshot (79)](https://user-images.githubusercontent.com/94120034/165239956-a1d49036-cae4-4440-8201-e2fede480fc5.png)
.

**Comment by catenocrypt** [comment]
The mentioned TX has only 1 output, as far as I can see, so the outputIndex 7 is wrong.

https://blockchair.com/dogecoin/transaction/af8ff35aa7237b1b59c790826bca62fcef4776cd699e6de8b5b4cf704760fac1

**Comment by serin-sebastian** [comment]
Thank you it works but transaction is not confirmed yet. transaction hash is : 2f4a97555523b1e0eae8d97366573151b1cb7bf98c954dbd1cefb3cfdeadc5e4


![Screenshot (80)](https://user-images.githubusercontent.com/94120034/165263453-c1a2d4ce-d72e-4b07-ab93-218e61501820.png)
.

**Comment by serin-sebastian** [comment]
Is there any other issue with my code? . There are multiple txids so, Is there any change in this code
![complaint](https://user-images.githubusercontent.com/94120034/165514488-b6b18a26-72b2-4d3a-8fa5-b01ab7a8e16d.png)
?

**Comment by serin-sebastian** [comment]
Transaction is successfully broadcasted but it showing minor preference low . Transaction is not yet confirmed . How can i increase the minor preference in my code

**Comment by hewigovens** [comment]
You set byte fee as 1 which is too low at current network situation https://blockchair.com/dogecoin/charts/median-transaction-fee-usd

**Comment by serin-sebastian** [comment]
Then what is the sufficient value for byte fee ?
