### ISSUE TITLE
Scanning QR Code for XNO (NANO) gives wrong amount

### ISSUE THREAD

**Issue by besoeasy** [trustwallet/wallet-core#2162]
**Describe the bug**
Scanning QR Code for XNO (NANO) gives wrong amount

It parses basic RAW value, doesn't convert it into NANO units

_?amount=1000000000000000000000000000000_  

parameter should give 1 NANO, instead it gives 1000000000000000000000000000000 NANO

**To Reproduce**
Scan any NANO QR code with amount parameter 

**Expected behavior**
Trust wallet should convert RAW to NANO units

**Screenshots**
![photo_2022-04-26_12-59-52](https://user-images.githubusercontent.com/8281782/165246044-845a160f-edf9-42d0-90a6-66e87826d9d2.jpg)

**Comment by catenocrypt** [comment]
Is this Android or iOS version?
Could you provide sample QR code?

**Comment by besoeasy** [comment]
> Is this Android or iOS version? Could you provide sample QR code?

tested on **android** 

![Screenshot 2022-04-29 040037](https://user-images.githubusercontent.com/8281782/165858364-e5f52f76-dc00-45e4-90a1-2f47a741248c.png)

**Comment by vcoolish** [comment]
use parameter value for it

**Comment by vcoolish** [comment]
Your attitude for nano pay link is wrong. You have to pass formatted amount.
Check how trust wallet generates receive deep link on Receive screen.

**Comment by ArtemGoryunov** [comment]
instead `amount` the `value` name should be used

**Comment by besoeasy** [comment]
@hewigovens well almost all NANO wallets use amount, not value.

It would be nice for trust wallet to add support for amount, rather than telling whole NANO community to change standard

Here is the popular reference, by one of community member

https://nanojson.medium.com/how-to-create-a-stylish-nano-qr-code-1bfc1eba5a96

**Comment by hewigovens** [comment]
we support various standards: bip21, eip681 and solana pay, does nano has similar uri protocol?

**Comment by vcoolish** [comment]
Your whole nano community is some random medium article with hardcoded link text?
Take a look at https://paynano.me
They use formatted amount. Just as other blockchain communities. Please close this issue.

**Comment by cbrunnkvist** [comment]
Yes @hewigovens of course it does. LMGTFY:

https://docs.nano.org/integration-guides/the-basics/#uri-and-qr-code-standards


The standard URI format for XNO is:
`nano:<address>?amount=<raw_amount>`
