### ISSUE TITLE
TronSigningOutput.encode

### ISSUE THREAD

**Issue by jiuyaopinyin** [trustwallet/wallet-core#2170]
TronSigningOutput has .json now. 
can it add menthod  like EthereumSigningOutput.encode?
Or is there any way to get Tronsigned hex now?I want to do the broadcast of hex, not json

**Comment by Bastek8** [comment]
#2156

**Comment by jiuyaopinyin** [comment]
> #2156

what did that mean?

**Comment by jiuyaopinyin** [comment]
> > #2156
> 
> what did that mean?

you mean i can use the bitcoinSignOutput?

**Comment by hewigovens** [comment]
you can broadcast the json to the node directly (trongrid api)
