### ISSUE TITLE
TronSigningOutput.json  have no "raw_data_hex" value

### ISSUE THREAD

**Issue by jiuyaopinyin** [trustwallet/wallet-core#2174]
1. use https://api.nileex.io/wallet/getnowblock getinfo
```
let contract = TronTransferContract.with {
                    $0.ownerAddress = "TF17Fnj797ukLJsBDAKnmcKY8T4ihtv1MC"
                    $0.toAddress = "TB7QepEkcbyXJAfJA6diyTC1GPapHnUfGT"
                    $0.amount = 100000000
                }

        
                let input = TronSigningInput.with {
                    $0.transaction = TronTransaction.with {
                        $0.contractOneof = .transfer(contract)
                        $0.timestamp = 1651131078000
                        $0.blockHeader = TronBlockHeader.with {
                            $0.timestamp = 1651131078000
                            $0.number = 25879278
                            $0.version = 23
                            $0.txTrieRoot = Data(hexString: "197a099ef4cb93c80d242495b6f923939cd44bf05b7716f4fa96fde45c29163d")!
                            $0.parentHash = Data(hexString: "00000000018ae2ed66df8a69507a37b77fac79aaa0a99571a4b3eb77a545e58c")!
                            $0.witnessAddress = Data(hexString: "414bbb38ac8f2c666f56c16e0b21ccda04d18b6b6b")!
                        }
                        $0.expiration = 1651131078000 + 10 * 60 * 60 * 1000
                    }
                    $0.privateKey = Data(hexString: "49fb3a81fda24c02e70fa77805c46818004ee0def691170bd31fbb1295691bfe")!
                }
        let output: TronSigningOutput = AnySigner.sign(input: input, coin: .tron)
```
3. outputjson: {"raw_data":{"contract":[{"parameter":{"type_url":"type.googleapis.com/protocol.TransferContract","value":{"amount":100000000,"owner_address":"413734aa0f627ff23915397113bcbe7b598896efa4","to_address":"410c852de139c14b31360df1e9642e8adc5a95c677"}},"type":"TransferContract"}],"expiration":1651167078000,"ref_block_bytes":"e2ee","ref_block_hash":"3e327c83ee4dec62","timestamp":1651131078000},"signature":["86468c1d0e08884470c003fcd8f42ead0755c6359fbee47fb2546608b3c57e7176ee0d2e5c47820d5b84bdf9a2b271fb2a28330f784f3eb6f4fa5511daa6795001"],"txID":"16533dc8af98a70795fcc7c519c3a8942a6429f1ceed484ae763772c533eee63"}
4. set json to https://cn.developers.tron.network/reference/broadcasttransaction
    {
  "code": "TAPOS_ERROR",
  "txid": "16533dc8af98a70795fcc7c519c3a8942a6429f1ceed484ae763772c533eee63",
  "message": "5461706f7320636865636b206572726f722e"
}

 code : error
**The cause of this error has been found, but there is another problem**
 

the output.json  have no "raw_data_hex" value
<img width="600" alt="image" src="https://user-images.githubusercontent.com/16219599/165702365-4c126a86-a30e-4997-881b-4721f4aa9901.png">

**Comment by jiuyaopinyin** [comment]
The reason for the fourth error is because of different node problems,
But another question is, is it possible to get raw_data_hex in walletcore? Or get the hex that can be used for broadcasting in the end?

**Comment by hewigovens** [comment]
the json you got from wallet core can be broadcasted to node directly
