### ISSUE TITLE
Increase constant in Cardano's estimateTxSize function

### ISSUE THREAD

**Issue by kai-newton** [trustwallet/wallet-core#2178]
**Describe the bug**
A constant 11 is added to [estimateTxSize](https://github.com/trustwallet/wallet-core/blob/master/src/Cardano/Signer.cpp#L228). I believe value is too low since a TTL of ~500 is required to prevent transactions from failing. This translates to far longer than expected tx times.

**To Reproduce**
Sign a Cardano transaction without a plan.

**Comment by catenocrypt** [comment]
This constant has affect on estimated fee: a very slight over-estimation is used, to reduce chance of 'fee too low' errors.  However, it should work properly without extra constant as well.
This constant has nothing to do with TTL.
Correct me if I'm wrong.

**Comment by kai-newton** [comment]
Yes, you're right, I just found out that a fee above the minimum threshold does nothing. Any idea of why the transactions take so long though. A TTL of 200 has a failure rate of ~80%. Is it just network congestion at the time of testing?

**Comment by hewigovens** [comment]
could you please test it again? it depends on the network
