### ISSUE TITLE
Wanted functionlity to sign transaction when implementing Swap functionality

### ISSUE THREAD

**Issue by HemangiVekaria** [trustwallet/wallet-core#2194]
Hello 

I am developing an app which has functionality to swap tokens like ETH to UNI etc,. So what i did for now is i am getting some json data from our server-side(uesd kyberswap ) like this

**_{
    "rawTransaction": {
        "from": "0x123456...",
        "data": "0x32464be8....",
        "value": "0x0",
        "to": "0xd999999",
        "chainId": 97
    },
    "estimatedGas": "29840"
}_**

Now i am signing this whole json using this method 

_**AnySigner.signJSON(json, privatekey, CoinType.ETHEREUM.value());**_

So this is correct way or is there any other way to sign transactions for SWAP. Can anyone please help?

**Comment by HemangiVekaria** [comment]
What is way to sign that swapping transactions from mobile app with this TurstWallet SDK.  
![image](https://user-images.githubusercontent.com/17717369/166866471-0d49cdcd-7e69-4ed5-9e85-02f0e898d7c3.png)
i am using this methods to sign native and ERC20 token transfer. There's same way to do for swap?

**Comment by catenocrypt** [comment]
These are native coin transfer and ERC20 token transfer transactions.  I believe for swap one needs a contract call.  But this is outside of the scope of wallet core.

You may dig around here:
https://github.com/trustwallet/wallet-core/blob/master/tests/Ethereum/TWAnySignerTests.cpp#L124
https://github.com/trustwallet/wallet-core/blob/master/tests/Ethereum/ContractCallTests.cpp#L38
https://github.com/trustwallet/wallet-core/blob/master/tests/Ethereum/Data/uniswap_router_v2.json

**Comment by HemangiVekaria** [comment]
Can you share any sample or anything which helps me? from server side we are using kyberswap and from my application i am calling api and from backend through kyberswap it's creating rawtransaction and send back to mobile app in json format which i already shared in start of this thread. Now after that i need to sign that so how can i sign that? Can you please help me for this as i am new to this blockchains and wallets.
