### ISSUE TITLE
Build `WalletCore` as a static xcframework

### ISSUE THREAD

**Issue by acecilia** [trustwallet/wallet-core#2208]
Hi 👋 

**Is your feature request related to a problem? Please describe.**
Linking statically [is known](https://acecilia.medium.com/static-vs-dynamic-frameworks-in-swift-an-in-depth-analysis-ff61a77eec65) to be more performant, reducing app launch time and app size

**Describe the solution you'd like**
Currently there is a dynamic `WalletCore` xcframework attached to the releases. Would like to also have a static version

**Describe alternatives you've considered**
N/A

**Additional context**
If not possible for the authors of this repository to generate and maintain both dynamic and static xcframeworks, would it be possible to provide some instructions of what tweaks are needed in the codebase to build the static xcframework, so I can do that myself?

Thanks!

**Comment by hewigovens** [comment]
We haven't had the performance issue because of dynamic wallet core, if you want to build a static one, you might need to write your own script to create and test with SPM's binary target

`swift/project.yml` is a good starting point

**Comment by acecilia** [comment]
@hewigovens Thanks for that. Would you accept a PR adding a static xcframework to the releases?

**Comment by hewigovens** [comment]
We will consider if it works well with SPM
