### ISSUE TITLE
[Solana] Add generic raw signing mode

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2215]
Add support for signing of an arbitrary, already compiled&encoded byte stream (raw).

**Comment by AyushBherwani1998** [comment]
@hewigovens @catenocrypt do you have any time estimation for adding this support?

**Comment by hewigovens** [comment]
@AyushBherwani1998 I think we can just `PrivateKey.sign` to sign the raw tx, no need to add new method
