### ISSUE TITLE
[Kotlin] Codegen API doc from C headers 

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2217]
Dokka https://github.com/Kotlin/dokka

**Comment by catenocrypt** [comment]
Most non-test swift code is generated, so codegen logic has to be extended to:
- read descriptions from source files (TW*.h)
- generate documentation comments in a common format, understood by documenting tool

**Comment by hewigovens** [comment]
@Milerius can you update your finding here?

**Comment by Milerius** [comment]
> @Milerius can you update your finding here?

Kotlin comments use Asterix style: https://kotlinlang.org/docs/kotlin-doc.html

We need to find a good way with a script similar to the swift one to convert the `///` doxygen comments into Kotlin one. I suggest to use sed or perl with regex once again

**Comment by Milerius** [comment]
Implemented in #2678
