### ISSUE TITLE
TrustWalletCore had not exported spec256k1Extended & nistp256Extended interface.

### ISSUE THREAD

**Issue by weixuefeng** [trustwallet/wallet-core#2219]
**Describe the bug**
i used flutter-wallet-core for my wallet. and my coin used nistp256, when i use the method: `PrivateKey.getPublicKey(curve)`, i have not found the api for nistp256extended.

https://github.com/trustwallet/wallet-core/blob/master/include/TrustWalletCore/TWPrivateKey.h#L43 why there have not nistP256Extended & Spec256Extended?

**Comment by hewigovens** [comment]
It's supported in `TWPublicKey` https://github.com/trustwallet/wallet-core/blob/master/include/TrustWalletCore/TWPublicKey.h#L38, call this method to get full public key
