### ISSUE TITLE
The coinTypes method of coin Entry classes are not used

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2225]
Each blockchain implementation has an `Entry` class, and each publishes the list of coins it can handle
(see e.g. https://github.com/trustwallet/wallet-core/blob/master/src/Ethereum/Entry.h#L17)
This was meant to be used by the dispatcher, to know which coin handler to invoke.

Related to #2214 .

However, currently these are not used, but dispatcher is a large `switch` statement, which is updated every time a coin is added  (here: https://github.com/trustwallet/wallet-core/blob/master/src/Coin.cpp#L107)

There is also a `blockchain` field in the `registry.json`, which also tells which blockchain implementation is used for this coin (see here: https://github.com/trustwallet/wallet-core/blob/master/registry.json#L346).

These 2 (3?) sources of information should be consolidated.
However, some considerations:
- Using info from entry classes, searching all of them all the time is very inefficient
- Consolidating above information at startup into a map solved the efficiency, but probably runs into initialization order issues (esp. in Android implementation)
- Using the fields from `registry.json` should be done at codegen time, but may be cumbersome there.

**Comment by catenocrypt** [comment]
Alternative solution:

- Current `switch`-based dispatcher to be changed based on __blockchain__ instead of coin type.
- Entry classes don't need to advertise their supported tokens nor blockchain
- Adding a new EVM coin would mean addition to the registry.json, but __no change__ to the Ethereum Entry class nor the dispatcher

**Comment by hewigovens** [comment]
Switch on `Blockchain` type makes sense, still need coin type for special cases
