### ISSUE TITLE
[NEAR] serialize FunctionCall actions

### ISSUE THREAD

**Issue by grachyov** [trustwallet/wallet-core#2226]
https://github.com/trustwallet/wallet-core/blob/386de18f9f9aa34c65afabc425450f55e9077f09/src/NEAR/Serialization.cpp#L55

Only `Transfer` actions are serialized right now.

These `FunctionCall` actions are necessary in order to use dapps.

**Comment by hewigovens** [comment]
@grachyov could you please help add this feature?

**Comment by grachyov** [comment]
@hewigovens could you please make a release after it is merged?

**Comment by hewigovens** [comment]
@grachyov Try pre-release 2.9.0

**Comment by grachyov** [comment]
Cool, thanks!
