### ISSUE TITLE
How can I get the same private key address as web3.js ?

### ISSUE THREAD

**Issue by hehonghui** [trustwallet/wallet-core#2229]
**Describe the bug**

I am using [web3.js](https://github.com/solana-labs/solana-web3.js/) libray with mnemonic words to generating account, but the private key address  through web3.js is different from that of word generation through wallet-core, how can wallet-core get the same private key address as web3.js?

**To Reproduce**

I use web3.js to create a account with mnemonic, [code](https://github.com/liuqiang4mrcd/wallet/blob/master/dist/index.html) like bellow:

```js
        function createdAddress(mnemonic){
            const derivePath = "m/44'/501'/0'"
            // mnemonic
            const seed = bip39.mnemonicToSeedSync(mnemonic);
            const derivedSeed = ed25519.derivePath(derivePath, seed.toString("hex")).key;
    
            // private key
            privateKey = bs58.encode(nacl.sign.keyPair.fromSeed(derivedSeed).secretKey);
            address = bs58.encode(nacl.sign.keyPair.fromSeed(derivedSeed).publicKey);
            console.log("address:", address);
            console.log("base58 privateKey:", privateKey)
        }
        
        const mnemonic = 'desk live opera elegant scale tattoo popular clown wing income depart slim'
        createdAddress(mnemonic)
```

and i will see the output like this:

```
address:5rPGcn5dNGJ88oSxdkNWwwe8TR3pmUQkfWCrnAXUGRRs
bs58 privateKey:5AgT8bLqrdbqFQgahxmQ54s4ZDrTWRu79gnrbqhnkjcP22XtyjYGzPSZ7gbr7rFHYJYM2jL88M9RSZSetDDcmDHj
```

But when i use wallet-core to generate account with same mnemonic , i will get a different private key value; android code like this:

```java
public static String byteArrayToHexString(byte[] bytes, boolean withPrefix) {
    final StringBuilder sb = new StringBuilder();
    if (withPrefix) {
        sb.append("0x");
    }
    for (byte element: bytes) {
        sb.append(String.format("%02x", element & 0xFF));
    }
    return sb.toString();
}


private void createSolanaAccount() {
        String mnemonicText = 'desk live opera elegant scale tattoo popular clown wing income depart slim';
        String password = "";
        HDWallet mWallet = new HDWallet(mnemonicText, password);
        final CoinType targetCoin = CoinType.SOLANA;
        final String walletAddress = mWallet.getAddressForCoin(targetCoin);
        Log.e(String.format("Default %s , derivation path: %s, address: %s", targetCoin.name(), targetCoin.derivationPath(), walletAddress));

        // private key
        final PrivateKey secretPrivateKey = mWallet.getKey(targetCoin, targetCoin.derivationPath());

        // private key 
        String hexPrivateKey = byteArrayToHexString(secretPrivateKey.data(), false);
        Log.e("", String.format("### solana hex private key: %s, bs58 : %s ", hexPrivateKey, Base58.encode(secretPrivateKey.data()));
}
```

android output:

```
ddress: 5rPGcn5dNGJ88oSxdkNWwwe8TR3pmUQkfWCrnAXUGRRs
solana hex private key: d06a72d4fab0659df79a0e693479c4ad497f29d2738907940afd55170bed6f76, bs58 : 2anhjQuL13KJJzJBWgaPXYeSazbmZ9sT4P6rmoTSBDD1ALWZFL
```

You can see the wallet-core's private key is: `2anhjQuL13KJJzJBWgaPXYeSazbmZ9sT4P6rmoTSBDD1ALWZFL`, and the web3.js is : `5AgT8bLqrdbqFQgahxmQ54s4ZDrTWRu79gnrbqhnkjcP22XtyjYGzPSZ7gbr7rFHYJYM2jL88M9RSZSetDDcmDHj`. And now, how can i get the same private key value with web3.js ? Thanks.

**Expected behavior**

get the same private key value with web3.js.

**Comment by hewigovens** [comment]
`secretKey` in web3.js is 64 bytes (32 private + 32 public), if you compare the first 32 bytes, they're same

**Comment by nguyenhaiduc06** [comment]
@hehonghui do you have code for swift

**Comment by adam-alex-albert** [comment]
> @hehonghui do you have code for swift
` let key = hdWallet?.getKey(coin: .solana, derivationPath: "m/44'/501'/\(addressIndex)'/0'")
                        if let data = key?.data, let publicKeyData = key?.getPublicKeyEd25519().data {
                            // 64 bytes (32 private + 32 public)
                            var fullData = Data()
                            fullData.append(data)
                            fullData.append(publicKeyData)
                            
                            let text = Base58.encodeNoCheck(data: fullData)
                        }`

**Comment by adam-alex-albert** [comment]
> @hehonghui do you have code for swift

`
let key = hdWallet?.getKey(coin: .solana, derivationPath: "m/44'/501'/(addressIndex)'/0'")
if let data = key?.data, let publicKeyData = key?.getPublicKeyEd25519().data {
// 64 bytes (32 private + 32 public)
var fullData = Data()
fullData.append(data)
fullData.append(publicKeyData)

                        let text = Base58.encodeNoCheck(data: fullData)
                    }
`

**Comment by adam-alex-albert** [comment]
> @hehonghui do you have code for swift
```
let key = hdWallet?.getKey(coin: .solana, derivationPath: "m/44'/501'/(addressIndex)'/0'")
if let data = key?.data, let publicKeyData = key?.getPublicKeyEd25519().data {
// 64 bytes (32 private + 32 public)
var fullData = Data()
fullData.append(data)
fullData.append(publicKeyData)

                        let text = Base58.encodeNoCheck(data: fullData)
                    }
```
