### ISSUE TITLE
Solana token transfer signature's length is not equal with web3.js 

### ISSUE THREAD

**Issue by hehonghui** [trustwallet/wallet-core#2231]
**Describe the bug**
Solana token transfer signature's length is not equal with web3.js 

**To Reproduce**
If i use web3.js or solana command line tools to make a transaction, i will get a signature like `5xKKn8MSjxTSc116aB26iXmQo8NH58cmN739Utf8Mt21Y6ZPR2QLza2j1LVMQ6pcvrw7j19fRJr6QHj56D3tvH7w`, but when i use wallet-core to do the same thing, i will get a longer signature,  wallet-core `TestSolanaSigner` test case:

```kotlin
   @Test
    fun testTokenTransferSign() {
        val tokenTransferMessage = Solana.TokenTransfer.newBuilder().apply {
            tokenMintAddress = "SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt"
            senderTokenAddress = "EDNd1ycsydWYwVmrYZvqYazFqwk1QjBgAUKFjBoz1jKP"
            recipientTokenAddress = "3WUX9wASxyScbA7brDipioKfXS1XEYkQ4vo3Kej9bKei"
            amount = 4000  // 0.004
            decimals = 6
        }.build()
        val signingInput = Solana.SigningInput.newBuilder().apply {
            tokenTransferTransaction = tokenTransferMessage
            recentBlockhash = "CNaHfvqePgGYMvtYi9RuUdVxDYttr1zs4TWrTXYabxZi"
            privateKey = ByteString.copyFrom(Base58.decodeNoCheck("9YtuoD4sH4h88CVM8DSnkfoAaLY7YeGC2TarDJ8eyMS5"))
        }.build()

        val output = AnySigner.sign(signingInput, SOLANA, SigningOutput.parser())

        val expectedString = "PGfKqEaH2zZXDMZLcU6LUKdBSzU1GJWJ1CJXtRYCxaCH7k8uok38WSadZfrZw3TGejiau7nSpan2GvbK26hQim24jRe2AupmcYJFrgsdaCt1Aqs5kpGjPqzgj9krgxTZwwob3xgC1NdHK5BcNwhxwRtrCphGEH7zUFpGFrFrHzgpf2KY8FvPiPELQyxzTBuyNtjLjMMreehSKShEjD9Xzp1QeC1pEF8JL6vUKzxMXuveoEYem8q8JiWszYzmTMfDk13JPgv7pXFGMqDV3yNGCLsWccBeSFKN4UKECre6x2QbUEiKGkHkMc4zQwwyD8tGmEMBAGm339qdANssEMNpDeJp2LxLDStSoWShHnotcrH7pUa94xCVvCPPaomF"
        assertEquals(output.encoded, expectedString)
    }
```

such as : `PGfKqEaH2zZXDMZLcU6LUKdBSzU1GJWJ1CJXtRYCxaCH7k8uok38WSadZfrZw3TGejiau7nSpan2GvbK26hQim24jRe2AupmcYJFrgsdaCt1Aqs5kpGjPqzgj9krgxTZwwob3xgC1NdHK5BcNwhxwRtrCphGEH7zUFpGFrFrHzgpf2KY8FvPiPELQyxzTBuyNtjLjMMreehSKShEjD9Xzp1QeC1pEF8JL6vUKzxMXuveoEYem8q8JiWszYzmTMfDk13JPgv7pXFGMqDV3yNGCLsWccBeSFKN4UKECre6x2QbUEiKGkHkMc4zQwwyD8tGmEMBAGm339qdANssEMNpDeJp2LxLDStSoWShHnotcrH7pUa94xCVvCPPaomF` . 

When i submit this signature to the  solana devnet via http, error will occur.

curl http example:

```
curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "sendTransaction",
    "params": [
      "PGfKqEaH2zZXDMZLcU6LUKdBSzU1GJWJ1CJXtRYCxaCH7k8uok38WSadZfrZw3TGejiau7nSpan2GvbK26hQim24jRe2AupmcYJFrgsdaCt1Aqs5kpGjPqzgj9krgxTZwwob3xgC1NdHK5BcNwhxwRtrCphGEH7zUFpGFrFrHzgpf2KY8FvPiPELQyxzTBuyNtjLjMMreehSKShEjD9Xzp1QeC1pEF8JL6vUKzxMXuveoEYem8q8JiWszYzmTMfDk13JPgv7pXFGMqDV3yNGCLsWccBeSFKN4UKECre6x2QbUEiKGkHkMc4zQwwyD8tGmEMBAGm339qdANssEMNpDeJp2LxLDStSoWShHnotcrH7pUa94xCVvCPPaomF"
    ]
  }
'
```

error:

```
{"jsonrpc":"2.0","error":{"code":-32002,"message":"Transaction simulation failed: Blockhash not found","data":{"accounts":null,"err":"BlockhashNotFound","logs":[],"unitsConsumed":0}},"id":1}
```

**Expected behavior**
How can i get the right signature of solana token transfer transaction, and submit to https://api.devnet.solana.com . Thanks for helping.

**Comment by hewigovens** [comment]
what's the equivalent web3.js code? also try sending wallet core tx mainnet

**Comment by hehonghui** [comment]
> what's the equivalent web3.js code? also try sending wallet core tx mainnet

Yes，I want to send token transfer transaction to devnet, but the signed signature is incorrect, and i don't find any example about this. Can you guys share some workaround?

**Comment by hewigovens** [comment]
I don't think we support devnet

**Comment by jalchr** [comment]
> I don't think we support devnet

@hewigovens Does this apply to all chains or just Solana ?
I'm also trying to send transactions to Mumbai and Ropsten networks. I got a TrnxHash but I fail to see it in the corresponding explorers. 
Any hints ?

**Comment by hewigovens** [comment]
@jalchr for ethereum, it should just work if you pass correct chain id and enough gas

**Comment by jalchr** [comment]
I'm asking about Testnets. 
You mentioned that the signed transaction from TrustWallet " ... does not support devnet". 
Is this true for all testnets ?

**Comment by hewigovens** [comment]
@jalchr this is wallet core repo, but that's true for the app, it doesn't support all testnet or devnet now

**Comment by jalchr** [comment]
Can you mention which testnet is supported  ? so we can utilize it for testing ?
Thanks

**Comment by blukhi99** [comment]
hello @jalchr @hewigovens @hehonghui @phuang @philiparthurmoore

I am also looking for a solution for the SOLANA sign transaction in mainnet. I want to serialize the Message but, am unable to get serialized Message. do you have ideas about it?
