### ISSUE TITLE
Token block chain open

### ISSUE THREAD

**Issue by Soheilafsha** [trustwallet/wallet-core#2249]
من به عنوان یک شخص حقیقی با تفکر و ذهنیت پیشرفت در حوضه علم و فن اوری درخواست دارم به عنوان کمک های بشر دوستانه به میزان بسیار محدود در حد گذران زندگی معمولی با توجه به سازمان حقوق بشر با متخصصین مربوطه بررسی کنید که ایا داشتن یک مکان و سرپناه و کمک هزینه برای تامین خورد و خوراک روزمره شامل حال من میشود یا خیر .
من به عنوان انسان معتقدم باید راه هایی برای کمک رسانی به نیازمندان واقعی رو فراهم نمود . با بهره بردن از اخرین تکنولوژی ها و استفاده از هوش مصنوعی هر چه سریع تر باید پروژه هایی راه اندازی و تست و اجرا شود که به مردم نیازمند و تحت سلطه و دیکتاتور کمک کرد که زیر بار تحریم ها از همه طرف زیر فشار از کرسنگی و فشار های روحی روانی بیشتر از این ترور شخصیتی و زجر مداوم نباشند .
اگر این اتفاق نیفتد پس کل سیستم دارای مشکل و اخبار دروغ هست که جیب سودجویان رو بیشتر پر کند.
حرف با عمل فرق میکند در این صورت از همکاری در توسعه دلسرد و ناامید خواهم شد

**Comment by catenocrypt** [comment]
Please write in English.
