### ISSUE TITLE
[Terra] Add support v2

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2256]
1. Changing the “bank/MsgSend” to “cosmos-sdk/MsgSend”.
2. Wasm tx types need to be cosmwasm.wasm.v1.MsgExecuteContract.

https://github.com/terra-money/core/blob/main/WASM_MIGRATE.md#contract-address (edited)

**Comment by catenocrypt** [comment]
We should support only Protobuf version only now, “cosmos-sdk/MsgSend” type is not relevant with protobuf.

**Comment by catenocrypt** [comment]
Assets part: https://github.com/trustwallet/assets/issues/20968
