### ISSUE TITLE
My wallet is attached 

### ISSUE THREAD

**Issue by Soheilafsha** [trustwallet/wallet-core#2260]
با سلام و عرض ادب خدمت همکاران محترم ، کیف پول من در معرض هکران و نفوذگران قرار گرفته و به سرقت رفته .
لطفا به من در بازیابی و ایمن سازی کیف پول شخصی و امنیت اکوسیستم در پیشرفت و ارتقای راههای نفوظ را جلوگیری نمایید

Wifi:
b'5K2YUVmWfxbmvsNxCsfvArXdGXm7d5DC9pn4yD75k2UaSYgkXTh'
کلید عمومی:
045f81956d5826bad7d30daed2b5c8c98e72046c1ec8323da336445476183fb7ca54ba511b8b782bc5085962412e8b9879496e3b60bebee7c36987d1d5848b9a50

کلید خصوصی:
9f86d081884c7d659a2feaa0c55ad015a3bf
4f1b2b0b822cd15d6c15b0f00a08

**Comment by hewigovens** [comment]
please use English, thanks
