### ISSUE TITLE
Considering integrating range-v3 as performance and readability improvements

### ISSUE THREAD

**Issue by Milerius** [trustwallet/wallet-core#2261]
**Is your feature request related to a problem? Please describe.**

I was browsing the code for potential improvements, and reading: https://github.com/trustwallet/wallet-core/blob/1d4b214b3d7e81e6b29e477dcf722b42314bffe3/src/Bitcoin/InputSelector.cpp#L51

**Describe the solution you'd like**

I think a range library could be integrated as a direct dependency such as boost, range-v3 is also partially integrated in c++20, and ported by the standard:  https://eel.is/c++draft/range.slide

It's a header-only library, so it's very easy to integrate.

Please check the following carefully: https://godbolt.org/z/WhaEcMPsh (check the assembly of `slice` and `slice_modern`)

as you can see the assembly is very different, and the code is much easier to read for the `range` version, there are places in the code where range could be used for readability and performance reasons.

Also if you check, many code part have such utility function for `views` only and unnecessary copy are made there. (slice is only used for `std::vector<TypeWithAmount> InputSelector<TypeWithAmount>::select(int64_t targetValue, int64_t byteFee, int64_t numOutputs)` but the slice itself it's just use to do some filtering or to call other functions later, IMHO view/range would improve a lot the code base.

If we take the following code:

```cpp
for (size_t numInputs = 1; numInputs <= n; ++numInputs) {
        const auto fee = feeCalculator.calculate(numInputs, numOutputs, byteFee);
        const auto targetWithFeeAndDust = targetValue + fee + dustThreshold;
        if (maxWithXInputs[numInputs] < targetWithFeeAndDust) {
            // no way to satisfy with only numInputs inputs, skip
            continue;
        }
        auto slices = slice(sorted, static_cast<size_t>(numInputs));

        slices.erase(
            std::remove_if(slices.begin(), slices.end(),
                [targetWithFeeAndDust](const std::vector<TypeWithAmount>& slice) {
                    return sum(slice) < targetWithFeeAndDust;
                }),
            slices.end());
        if (!slices.empty()) {
            std::sort(slices.begin(), slices.end(),
                [distFrom2x](const std::vector<TypeWithAmount>& lhs, const std::vector<TypeWithAmount>& rhs) {
                    return distFrom2x(sum(lhs)) < distFrom2x(sum(rhs));
                });
            return filterOutDust(slices.front(), byteFee);
        }
    }
```

it could be simplified as 

```cpp
using ranges::view;
for (size_t numInputs = 1; numInputs <= n; ++numInputs) {
        const auto fee = feeCalculator.calculate(numInputs, numOutputs, byteFee);
        const auto targetWithFeeAndDust = targetValue + fee + dustThreshold;
        if (maxWithXInputs[numInputs] < targetWithFeeAndDust) {
            // no way to satisfy with only numInputs inputs, skip
            continue;
        }
        auto filter_functor = [targetWithFeeAndDust](auto&& slice) { return sum(slice) < targetWithFeeAndDust;});
        auto r = sorted | sliding(static_cast<size_t>(numInputs)) | filter(filter_functor);
        
        if (!r.empty()) {
            auto min_functor = [distFrom2x](auto&& lhs, auto&& rhs) { return distFrom2x(sum(lhs)) < distFrom2x(sum(rhs));});
            return filterOutDust(ranges::min(r,  min_functor), byteFee);
        }
    }
```

In the second solution, no containers are created, only a view on the initial container in order to extract the desired value.

**Describe alternatives you've considered**

Upgrading to C++20 / rewriting the extras

**Comment by hewigovens** [comment]
Is C++20 available for mobile OS like iOS / Android?

**Comment by Milerius** [comment]
> Is C++20 available for mobile OS like iOS / Android?

Since we use clang, according to https://en.cppreference.com/w/cpp/compiler_support it's clang 10 for minimal range support - which clang version is used to build on iOS / Android ?

**Comment by Milerius** [comment]
> iOS SDK usually uses latest clang built by Apple but we tend to include less dependencies as much as possible

I will try to use C++20 in another PR then

**Comment by hewigovens** [comment]
Let's close this for now, if you want to work on this, feel free to reopen
