### ISSUE TITLE
Can't build the project using bootstrap or the Dockerfile

### ISSUE THREAD

**Issue by madhat1** [TrustWallet/wallet-core#227]
Hi, Calling `./bootstrap.sh` results with the following error:
`make[2]: Leaving directory '/mnt/development/work/wallet-core/build/protobuf/staging/protobuf-3.7.0/src'
make[1]: Leaving directory '/mnt/development/work/wallet-core/build/protobuf/staging/protobuf-3.7.0/src'
/home/borisf/dev/work/wallet-core/build/local/bin/protoc: error while loading shared libraries: libprotoc.so.18: cannot open shared object file: No such file or directory`

The same happens if I use the Dockerfile: `docker build .`.

I'm building on Ubuntu 16.04.

Would appreciate your assistance,
Thanks,
Boris

**Comment by alejandro-isaza** [comment]
Should be fixed now
