### ISSUE TITLE
Ethereum ABI: Support for fixed-size arrays

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2302]
Currently only byte array is supported with fixed size (e.g.  `bytes160`).  Some functions use fixes-size arrays, such as `address[4]`.

Example:
```
multiRoute(bytes msgData, address inputToken, uint256 inputAmount, address outputToken, address[4] referrals)
```

<img width="563" alt="image" src="https://user-images.githubusercontent.com/13562139/172784554-7d8ec66d-1748-4039-9df4-e99ae29ebdc4.png">

https://etherscan.io/tx/0xb6658239f3236e466c8915c34d165423ecc39fb36aa15389951f388ebdf05c75

See also: https://github.com/trustwallet/wallet-core/discussions/2299

**Comment by Milerius** [comment]
Good example of encoding/decoding: <https://github.com/rust-ethereum/ethabi/blob/c42c67350d10c440097f8e1fa4d107145288b582/ethabi/src/encoder.rs#L215>

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/

**Comment by catenocrypt** [comment]
Some more explanation:
In the Ethereum ABI parameters, there is support for variable-size array with arbitrary type: `ParamArray`
(see https://github.com/trustwallet/wallet-core/blob/master/src/Ethereum/ABI/Array.h#L18)

There is also support for fixed-size array, but only for bytes: `ParamByteArrayFix`
(https://github.com/trustwallet/wallet-core/blob/master/src/Ethereum/ABI/Bytes.h#L40)
These are covered by tests (mostly in https://github.com/trustwallet/wallet-core/blob/master/tests/Ethereum/AbiTests.cpp).

The new, fixed-size array would be a new class, `ParamArrayFix`, with fixed size (similar to ParamByteArrayFix), but arbitrary type (similar to ParamArray).

- N is the fixed number of elements, N > 0
- Type name would by of the form `<elemType>[<N>]`, e.g. `address[3]`
- There is no need for optional prototype element, as there will be always at least one element
- Constructor should take N and N elements (these cannot change later in the life of the object)
- No need to add(), as size is fixed
- isDynamic is false, size is fixed
- getCount is N
- getSize is size of element * N
- encoded form contains the elements (but not N)
