### ISSUE TITLE
[Codegen] Ruby 3.0 compatibility

### ISSUE THREAD

**Issue by jiuyaopinyin** [trustwallet/wallet-core#2313]
MAC build with ./bootstrap.sh

/Users/admin/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)

SortedSet was removed from stdlib in Ruby 3.0

**Comment by hewigovens** [comment]
Thanks for the report, we will fix it
