### ISSUE TITLE
walletconnect doesn't work for trust wallet ios app

### ISSUE THREAD

**Issue by paololim** [trustwallet/wallet-core#2338]
Copy of https://github.com/trustwallet/wallet-core/issues/2197, which I could not reopen. Provided more context, including a link to a demo where you can observe the issue happening.

**Describe the bug**
Using the `WalletConnect` npm package, we are not able to our Trust Wallet app to properly connect with our dapp. A new WalletConnect connection seems to be prematurely added to the WC seciton of the app, but our site is still waiting for the user to read the ETH message and sign it

**To Reproduce**
You can see it here: https://wallet-kit-e2e-react-pr-299.onrender.com/

Steps:
1. click on "connect my wallet"
<img width="251" alt="Screen Shot 2022-06-22 at 1 28 51 PM" src="https://user-images.githubusercontent.com/85070/175100342-19f3db6d-c6b9-47c2-ad68-fd724a85d873.png">

2. scroll down to "trust" and click on it
<img width="360" alt="Screen Shot 2022-06-22 at 1 29 15 PM" src="https://user-images.githubusercontent.com/85070/175100414-bbb9874a-9ab9-472b-a1fb-6d94b5ad48fb.png">

3. scan the QR code with ios app (my app version is `7.9 (650)` )

4. app hangs with:
![IMG_5646](https://user-images.githubusercontent.com/85070/175100847-90d41544-2b14-48f7-8949-7b84a1d92f75.PNG)

**Expected behavior**

A sign-in view, with the message, should be displayed and there's a way for the user to confirm the message. For example, we get the following with rainbow using the exact same code in the previous section:

<img width="250" height="400" alt="Screen Shot 2022-05-05 at 2 11 55 PM" src="https://user-images.githubusercontent.com/85070/166986157-251322bb-9d83-404c-812f-8dfb61947193.jpg">

**Additional context**

In case it might help, the `client` object from `client.signPersonalMessage` above is the following (after `JSON.stringify`):
```json
{
  "protocol":"wc",
  "version":1,
  "_bridge":"https://f.bridge.walletconnect.org",
  "_key":{ },
  "_clientId":"68a2c54b-0245-4526-9a25-79d77d71a9d1",
  "_clientMeta":{
    "description":"",
    "url":"http://localhost:4200",
    "icons":[
      "http://localhost:4200/assets/apple-touch-icon.png",
      "http://localhost:4200/assets/favicon-32x32.png",
      "http://localhost:4200/assets/favicon-16x16.png",
      "http://localhost:4200/favicon.ico"
    ],
    "name":"Dashboard"
  },
  "_peerId":"a938900b-6831-4740-b41c-59a2af9448af",
  "_peerMeta":{
    "description":"",
    "icons":[ ],
    "name":"Trust Wallet",
    "url":"https://trustwallet.com"
  },
  "_handshakeId":1651769694012533,
  "_handshakeTopic":"a56c05ed-bc12-47bc-af06-646c1c71c423",
  "_connected":true,
  "_accounts":[ "0xADe186d1607fC324196aF0d37aFF64e975ea4378" ],
  "_chainId":1,
  "_networkId":0,
  "_rpcUrl":"",
  "_eventManager":{
    "_eventEmitters":[
      { "event":"display_uri" },
      { "event":"connect" },
      { "event":"call_request_sent" },
      { "event":"wc_sessionRequest" },
      { "event":"wc_sessionUpdate" },
      { "event":"response:1651769694012533" },
      { "event":"connect" },
      { "event":"disconnect" },
      { "event":"response:1651769706341401" }
    ]
  },
  "_cryptoLib":{ },
  "_sessionStorage":{ "storageId":"walletconnect" },
  "_signingMethods":[
    "eth_sendTransaction",
    "eth_signTransaction",
    "eth_sign",
    "eth_signTypedData",
    "eth_signTypedData_v1",
    "eth_signTypedData_v2",
    "eth_signTypedData_v3",
    "eth_signTypedData_v4",
    "personal_sign",
    "wallet_addEthereumChain",
    "wallet_switchEthereumChain",
    "wallet_getPermissions",
    "wallet_requestPermissions",
    "wallet_registerOnboarding",
    "wallet_watchAsset",
    "wallet_scanQRCode"
  ],
  "_transport":{
    "opts":{
      "protocol":"wc",
      "version":1,
      "url":"https://f.bridge.walletconnect.org",
      "subscriptions":[ "68a2c54b-0245-4526-9a25-79d77d71a9d1" ]
    },
    "_queue":[ ],
    "_events":[
      { "event":"message" },
      { "event":"open" },
      { "event":"close" },
      { "event":"error" }
    ],
    "_subscriptions":[ "68a2c54b-0245-4526-9a25-79d77d71a9d1" ],
    "_protocol":"wc",
    "_version":1,
    "_url":"https://f.bridge.walletconnect.org",
    "_netMonitor":{
      "_eventEmitters":[
        { "event":"online" }
      ]
    },
    "_socket":{ },
    "_nextSocket":null
  }
}
```

**Comment by hewigovens** [comment]
could you please try to update iOS app to latest version (7.9 650)? I tried and worked

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/360470/175217535-8ddb040b-ed98-471f-a7de-29d87858b725.png">

**Comment by hewigovens** [comment]
This wallet kit looks good for testing, can we get a beta invite?

**Comment by paololim** [comment]
@hewigovens thanks for quickly taking a look at that. i made sure my app was updated, but still see the same issue on my end:

https://user-images.githubusercontent.com/85070/175329853-6ae24b38-ee83-4955-b8fd-b8f0569e28e8.MP4

Is there anything I can provide that would help? Thanks!

**Comment by ArtemGoryunov** [comment]
@paololim  On your side, do you see connection screen or sign request does not work?

**Comment by paololim** [comment]
> @paololim On your side, do you see connection screen or sign request does not work?

Just seems to hang on "connecting may take a few seconds" on my ios app. I deleted it and re-installed too, just in case if it makes a difference (it did not).

**Comment by paololim** [comment]
Update: I actually waited for it and it says "Failed to connect" after about 1 full minute.

**Comment by hewigovens** [comment]
Looks like network issue, try to remove all sessions and kill the app then try again

**Comment by ArtemGoryunov** [comment]
@paololim try to do it with VPN, please

**Comment by paololim** [comment]
> Looks like network issue, try to remove all sessions and kill the app then try again

By removing all sessions, what exactly do you mean?

**Comment by hewigovens** [comment]
Remove all WalletConnect sessions on your app, Settings -> WalletConnect -> Remove each

**Comment by paololim** [comment]
> Remove all WalletConnect sessions on your app, Settings -> WalletConnect -> Remove each

@hewigovens This occurs even when I delete the app. The video I posted above has no existing WC sessions

**Comment by hewigovens** [comment]
@paololim Does this still happen on latest iOS app? we couldn't reproduce it

**Comment by paololim** [comment]
> @paololim Does this still happen on latest iOS app? we couldn't reproduce it

@hewigovens hello! Sorry, I just saw this now. We are still seeing this issue when testing internally - though some people have said it is working for them, while others have said it is not. We would really like to work with you on this to make sure the experience is great for both Trust's and Dynamic's users. Someone from our team is compiling videos/screenshots to recreate the issue and will post them here shortly.

> This wallet kit looks good for testing, can we get a beta invite?

When you have a chance, please email hello@dynamic.xyz directly and we will get your team set up with beta access directly to our SDK - again, we would love to work with your team to make this a great experience for both!

**Comment by eadonj** [comment]
to add to paolo's comment - this what happened yesterday for me:

1. I was able to connect and sign with Opensea - then i signed out
2. I was able to connect but not sign with dynamic - then i signed out
3. Tried uniswap and it failed
4. Went back to Opensea and could no longer connect
5. Went back to Dynamic and could no longer connect
6. I cleared the cache in Trust app and in my Browser
7. I went back to Opensea, could not connect
8. I went back to Dynamic, could not connect

**Comment by hewigovens** [comment]
> to add to paolo's comment - this what happened yesterday for me:
> 
> 1. I was able to connect and sign with Opensea - then i signed out
> 2. I was able to connect but not sign with dynamic - then i signed out
> 3. Tried uniswap and it failed
> 4. Went back to Opensea and could no longer connect
> 5. Went back to Dynamic and could no longer connect
> 6. I cleared the cache in Trust app and in my Browser
> 7. I went back to Opensea, could not connect
> 8. I went back to Dynamic, could not connect

@eadonj this looks weird, usually you disconnect from the dapp + remove the session from the app, you should be able to connect (at most kill and relaunch the app), do you run your own bridge or somehow?

**Comment by eadonj** [comment]
i don't use a bridge or anything like that. it was just standard connecting and disconnecting from the different sites.

**Comment by eadonj** [comment]
should we setup a call? we can screenshare a show you what's happening

**Comment by Sprimage** [comment]
Can confirm this is a trustwallet issue. Random and hard to track as well

**Comment by loic-combis** [comment]
Hey there! Having the same issue when deep linking from a flutter app on IOS...

**Comment by ifarshgar** [comment]
I also have this problem when trying to use trust walletconnect feature. It just hangs on that "wait a few seconds" message. I have the latest app version on IOS. Sometimes after trying to get a connection multiple times I get connected by chance after many attempts but this is really annoying. It has been like this for ever. It is not a matter of now or a month ago.
