### ISSUE TITLE
Big BUG : network fee change

### ISSUE THREAD

**Issue by nonomaxxis** [trustwallet/wallet-core#2344]
Hi,
why network fee change after transfer confirm?

![photo_2022-06-27_14-33-45](https://user-images.githubusercontent.com/6130447/175930878-20831bce-69f4-4b73-bf03-bea765de8953.jpg)
![photo_2022-06-27_14-33-51](https://user-images.githubusercontent.com/6130447/175930883-0a444f5b-54f6-4f1e-be65-9837c8672e2e.jpg)

**Comment by vcoolish** [comment]
could you please share your transaction hash?

**Comment by nonomaxxis** [comment]
Thanks for following up.
This is the second time this has happened to me.
They are exactly the same.

```
https://blockchair.com/dogecoin/transaction/f2b59cfd4930922bd451a44f2115dbaea748d3fa53e4886e2ba2a4bbf4f31f82?from=trustwallet

https://blockchair.com/dogecoin/transaction/b95b7deb2138dc06cdbf8818d8cb94a3ae77ccf9c454983b8eba949d276f86b1?from=trustwallet
```

**Comment by nonomaxxis** [comment]
hi, please check this.

https://github.com/dogecoin/dogecoin/issues/3018#issuecomment-1172976618

**Comment by nonomaxxis** [comment]
Why is no one doing anything to solve this problem?

**Comment by hewigovens** [comment]
@nonomaxxis We're investigate, will post update soon
