### ISSUE TITLE
Invalid Order Signature

### ISSUE THREAD

**Issue by jack75015** [trustwallet/wallet-core#2345]
**Describe the bug**
Hey

I recently try to sell one of my ERC721 on opensea but got an Invalid Order Signature error.
I did the same 2 weeks later but got no problem.

I think the problem comming with the new seapot protocol using (and creating) by opensea.

Steps:
- I click on the sell button
- got the message to sign on my trust wallet app
- sign
- got the error on opensea

Here is the error I got on my js console:
```
instrument.js:107 RRNLRequestError: Relay request for `useHandleBlockchainActionsCreateOrderMutation` failed by the following reasons:

1. Invalid order signature
       create(orderData: $orderData, clientSignature: $clientSi
       ^^^
    at t.createRequestError (createRequestError.js:110:15)
    at fetchWithMiddleware.js:93:37
```

(I import my trust wallet mnemonisc to metamask and did the same steps and got no problem)

Any body got the same issue?

**Comment by hewigovens** [comment]
Try latest app in the app store / Google Play, if you're using wallet core release, also try latest build
