### ISSUE TITLE
I can not download lastest version(2.9.5) with Android

### ISSUE THREAD

**Issue by gunny520min** [trustwallet/wallet-core#2346]
I can download version 2.6.3. but when i use lastest version 2.9.5, it fail

**Comment by hewigovens** [comment]
What's the error message? have you setup your gradle to load packages from GitHub packages?

**Comment by RonnieNava** [comment]
> 



> What's the error message? have you setup your gradle to load packages from GitHub packages?

Unresolved dependencies

Could not resolve com.trustwallet:wallet-core:2.9.5.

**Comment by hewigovens** [comment]
Take a look at this: https://github.com/trustwallet/wallet-core/discussions/2335
