### ISSUE TITLE
EIP-681 QR code BSC fails to properly read

### ISSUE THREAD

**Issue by jjs2484** [trustwallet/wallet-core#2363]
Scanning a QR code in the EIP-681 format with the @chain_id included fail to properly read for BSC (BNB and BEP20's), and MATIC. It works for ETH and ERC20's though. Is EIP-681 only supported for Ethereum? If so what would be the correct URI format for a QR code for BSC BNB?

**Comment by hewigovens** [comment]
Yeah, currently we only enable eip681 for Ethereum, for bnb chain, please use bip21 and refer to "Send Payment" example on https://developer.trustwallet.com/deeplinking#payment

**Comment by jjs2484** [comment]
Odd... Wouldn't it make more sense to support EIP-681 for QR codes for EVM compatible chains (BSC, MATIC, etc.). Rather than BIP-0021 which isn't EVM related at all.... Deeplinking is great for specific payment buttons, but in terms of QR codes, other wallets are supporting EIP-681 for EVM chains so it kind of puts us in between a rock and a hard place, if we support them for other chains the QR code is broken for trust wallet, or we use BIP-0021 it works for trust wallet but not other wallets....

**Comment by hewigovens** [comment]
@jjs2484 good point, let me confirm app team, this one is tricky, `ethereum:` will be treated as EIP681, for other chains there is no well know protocol name like `ethereum`, or we can handle chain id instead

**Comment by hewigovens** [comment]
@ArtemGoryunov can you check if this makes sense? enable eip681 for other evm chains

**Comment by ArtemGoryunov** [comment]
@jjs2484 Thank you for raising this question. Fixes will be available by end of the week for both planform.
