### ISSUE TITLE
[Cointest] Support generating coin type test by id

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2366]
`codegen/bin/cointest` generates tests for all coins, would like to improve it
1. Add optional coin id parameter to only generate tests for that coin
2. Skip existed and generated tests

**Comment by catenocrypt** [comment]
Note: when adding new chain, docs (https://developer.trustwallet.com/wallet-core/newblockchain) suggest using `codegen/bin/newcoin`, which invokes test generation for the given coin only.
