### ISSUE TITLE
Manage boost by `tools/install-dependencies` script

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2378]
Make sure we have same boost version across macOS / Linux / Android / iOS, Wasm could be different for now; This should also solve the issue when you use Android Studio + M1 MacBook

**Comment by hewigovens** [comment]
@Milerius does this issue still make sense?

**Comment by Milerius** [comment]
Not so much benefits without caching - closing for now.

**Comment by hewigovens** [comment]
current approach has inconsistent boost versions, any idea to solve this?

**Comment by Milerius** [comment]
> Current approach has inconsistent boost versions, any idea to solve this later? I realize we don't need cache boost, only use pure headers

We can always specify the version in apt-get or brew, my long term goal is to get ride of boost dependencies by using only the standard.

**Comment by hewigovens** [comment]
sounds good, we're using boost/multiprecision, hex and base64, not that much
