### ISSUE TITLE
XDC Blockchain support (asking for blockchain support)

### ISSUE THREAD

**Issue by tchadrack** [trustwallet/wallet-core#2393]
I really appreciate the project, trustwallet. 

But I think it could get even better if adding support to the XDC blockchain

https://explorer.xinfin.network/
https://xinfin.network/#stats
https://xinfin.org/xdc-utility

Please, consider adding support to this blockchain!

Regards,

**Comment by hewigovens** [comment]
Hey, we don't have plan to add XDC in near future
