### ISSUE TITLE
Add Echelon (ECH)

### ISSUE THREAD

**Issue by echelonfoundation** [trustwallet/wallet-core#2396]
We would like to request adding the new blockchain Echelon (ECH) to your repository here. EVM and Cosmos Hybrid Blockchain.

Official Site: https://ech.network
Official Dapp: https://app.ech.network

RPC Details and Documentation: https://docs.ech.network

**Comment by echelonfoundation** [comment]
We can create a PR if needed? Let us know. Thanks!

**Comment by Milerius** [comment]
> We can create a PR if needed? Let us know. Thanks!

Hello @echelonfoundation you can find equivalent pull request [here](https://github.com/trustwallet/wallet-core/pulls?q=is%3Apr+evmos+is%3Aclosed)

**Comment by echelonfoundation** [comment]
> > We can create a PR if needed? Let us know. Thanks!
> 
> Hello @echelonfoundation you can find equivalent pull request [here](https://github.com/trustwallet/wallet-core/pulls?q=is%3Apr+evmos+is%3Aclosed)

We would like to have Echelon (ECH) added to Trust Wallet, is there a PR we need to create for anything? Is anyone assigned to this to add compatibility within your current code updates for Cosmos/EVM chains for Echelon? Thank you!

**Comment by hewigovens** [comment]
@echelonfoundation we'll take a look and let you know (don't create pr now), usually you need to add code to wallet core first

**Comment by echelonfoundation** [comment]
> @echelonfoundation we'll take a look and let you know (don't create pr now), usually you need to add code to wallet core first

Just keep us updated @hewigovens we are more than willing to assist with any questions your team may have or code assistance. Thank you!

**Comment by hewigovens** [comment]
Hey, thanks for your interests, we had an internal discussion and decided not to add it now, will consider it later

**Comment by echelonfoundation** [comment]
> Hey, thanks for your interests, we had an internal discussion and decided not to add it now, will consider it later

Is there an issue? We would like to be added and when would you "consider later"?
