### ISSUE TITLE
[Improvements]: Decrease build time

### ISSUE THREAD

**Issue by Milerius** [trustwallet/wallet-core#2427]
**Describe the bug**

Build time can be very long with clang-tidy enabled

**Proposed Solution**

- [ ] Execute clang tidy per target
- [ ] Exclude deps from TrustWalletCore target
- [ ] Use unity build

**To Reproduce**

compile with `-DTW_ENABLE_CLANG_TIDY=ON`

**Expected behavior**

Being able to compile in under 10 min.

**Comment by trastvolt** [comment]
m/clang_tidy_smart_scanning
