### ISSUE TITLE
[NPM] Getting Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script

### ISSUE THREAD

**Issue by punithbm** [trustwallet/wallet-core#2429]
**Describe the bug**
When trying to use the wallet-core with [viteJs](https://vitejs.dev/), it works fine in the development environment. 
But after build, we are getting uncaught eval error due to unsafe-eval as shown below:

![Screenshot 2022-07-29 at 11 18 43 PM](https://user-images.githubusercontent.com/13044958/181816537-aace1979-39d4-40bd-afd0-9cf61f08cd1e.png)

We have included in the wallet core using wasm as shown below:

![Screenshot 2022-07-29 at 11 21 54 PM](https://user-images.githubusercontent.com/13044958/181816952-61ed489a-a992-4c91-82f4-577d5f966204.png)

After the yarn build, we are getting errors in the build due to unsafe-eval. Please check the above request and let me know if there is any workaround to handle this error.

**Comment by hewigovens** [comment]
We're aware of this issue, need to build with `DYNAMIC_EXECUTION=0`

**Comment by GouthamJM** [comment]
@hewigovens , will this issue be fixed soon ?

**Comment by punithbm** [comment]
@hewigovens  could you please let us know how to set `DYNAMIC_EXECUTION=0`  We were able to build [wasm-building](https://developer.trustwallet.com/wallet-core/developing-the-library/building#wasm-building) But not able to set that flag. If you can provide some more information on how to build. It will be really helpful.

**Comment by hewigovens** [comment]
@punithbm @GouthamJM I will push a draft pr today

**Comment by punithbm** [comment]
@hewigovens  Thanks a lot. Really appreciate it.

**Comment by hewigovens** [comment]
@punithbm can you try pull request #2472 ? let me know if that works for you

**Comment by punithbm** [comment]
@hewigovens  Tried building with the changes mentioned in the PR. But I am still getting the issue. It's because of the way I am importing the script in the index.html file? 

```
<head>
  <meta charset="UTF-8" />
  <link rel="icon" type="image/svg+xml" href="/src/assets/images/favicon.svg" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Extension</title>
  
  <script>
    var Module = {
      onRuntimeInitialized: function () {
        console.info("Module.onRuntimeInitialized");
      }
    };
  </script>
  <script type="module">
    import { TW } from "@trustwallet/wallet-core";
    window.TW = TW;
  </script>
</head>
```

We are using the wallet core in the Chrome Extension and the error is showing up when we are loading it there.
Attaching the screenshot for the same 

<img width="1725" alt="Screenshot 2022-08-01 at 12 51 07 PM" src="https://user-images.githubusercontent.com/13044958/182094747-9e6770f4-22b8-4d00-9478-6d40226d577c.png">

**Comment by hewigovens** [comment]
There are a few things could go wrong for Chrome Extension
1. no `unsafe-eval` in manifest v3 and `wasm-unsafe-eval` is available after version 102
2. did you add proper `content_security_policy` to manifest?
3. I saw similar issue on emscripten https://github.com/emscripten-core/emscripten/issues/16969

**Comment by punithbm** [comment]
@hewigovens  Thanks for your suggestions. I tried with 1 & 2 options and adding them is not resolving our issue. Do you know any other workarounds or ways we can make this run in the extension?

Cause in the latest chrome extension with manifest version 3 error is poping up where as in the previous version 2 it works. However chrome store now only accepts version 3 apps.

**Comment by punithbm** [comment]
@hewigovens  did you get a chance to check on the above request 👆

**Comment by hewigovens** [comment]
@punithbm can you try version 3.0.1? it fixed on our side

**Comment by punithbm** [comment]
@hewigovens  your pull request #2472 itself worked for us later after making some updates to the import method in the project. I was using [vitejs](https://vitejs.dev/) with react for the development of chrome extension development. Thanks for your support. Also happy to submit a sample for react + vitejs.

**Comment by hewigovens** [comment]
@punithbm Great, please add a vitejs sample link to the readme 🙏

**Comment by punithbm** [comment]
@hewigovens when working on the sample I observed that in PR #2472  you've updated the export method of the wallet core as shown below: 

![Screenshot 2022-09-02 at 6 23 18 AM](https://user-images.githubusercontent.com/13044958/188036698-777ecc3c-0ad5-402b-ad7b-2537c6878159.png)

Was there any specific reason for it? cause now when I was trying to declare the variables as 
```
account: typeof WalletCore.HDWallet
```
I am getting the not exported error. Is it possible for you to check?

**Comment by hewigovens** [comment]
In order to make `initWasm` typed, `WalletCore` is an `interface` now (can't do Promise<_namespace_>), blow code works for us
```typescript
let wallet: typeof WalletCore.HDWallet; 
```

**Comment by punithbm** [comment]
Oh ok. But when I tried with the above code got this error for the type. 
 
![Screenshot 2022-09-02 at 12 10 21 PM](https://user-images.githubusercontent.com/13044958/188074663-1bc99b34-7628-4f76-ba3e-c50474daa26c.png)

**Comment by hewigovens** [comment]
Not quite sure, probably need to check your sample source code
