### ISSUE TITLE
Improves memory handling in TWAnyAddress

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2430]
**Describe the bug**
Not really a bug:  create a class to automatically handle deallocation of `TWAnyAddress` object.

**Additional context**
https://github.com/trustwallet/wallet-core/blob/master/src/interface/TWAnyAddress.cpp#L16

```
struct TWAnyAddress {
    TWString* address;
    enum TWCoinType coin;
};

void TWAnyAddressDelete(struct TWAnyAddress* _Nonnull address) {
    TWStringDelete(address->address);
    delete address;
}
```

**Comment by catenocrypt** [comment]
I think I misunderstood the real issue here.  Here's how I think it should be:

- There is a `TWAnyAddress` struct holding an address (incl. coin) ☑️
- Internals of `TWAnyAddress` should be hidden, should not be visible in the .h file ❗️
- `TWAnyAddress` can can be created from address string or pubkey ☑️
- Methods to obtain address string / coin from `TWAnyAddress` (`TWAnyAddressDescription`, `TWAnyAddressCoin`) ☑️
- `TWAnyAddressDelete` to clean up address object when no longer needed ☑️
- Since internals is not visible to outside, ` std::string`  can be used to store the string inside the struct. ❗️

So the proposed changes:
- Move definition of internals of `TWAnyAddress` to the .cpp file
- Change the type of `address` field from `TWString*` to `std::string`

**Comment by kamranmosa** [comment]
Tk
