### ISSUE TITLE
Add New Blockchain - Echelon (ECH)

### ISSUE THREAD

**Issue by echelonfoundation** [trustwallet/wallet-core#2477]
## Description

Name: Echelon (https://ech.network)

HD Derivation Scheme: m/44'/60/0/0/0

Symbol: ECH

Documentation: https://docs.ech.network

Reason: It is a hybrid blockchain with a lot of features that rival competitors. IBC compatible, EVM compatible, etc.

Dapp: https://app.ech.network

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by hewigovens** [comment]
Thanks for your interest, we will consider adding EcheIon in the future
