### ISSUE TITLE
Cardano Staking

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2478]
**Is your feature request related to a problem? Please describe.**
Support Cardano Staking.  Currently transfer & tokens are supported.
TODO:
- Check staking address support, extend supported address formats if needed (https://github.com/trustwallet/wallet-core/blob/master/src/Cardano/AddressV3.h#L26)
- Add messages (in proto, Signing, tests) for staking/unstaking/etc.
- Test

Some additional info:
- Staked ADA is not locked for a given period, but can be spent any time while staked
- Staking does not have an amount, instead, the address is staked, with all ADA on it.
- Rewards are earned staring with the next epoch
- Unstaking is instant

**Comment by hewigovens** [comment]
@catenocrypt can you give an estimation for this? how long and what we need to do?

**Comment by x80486** [comment]
Hello folks! I usually don't "resuscitate" closed/resolved items, but I'm not sure I understand how this was implemented. For instance, when I go to the `Cardano (ADA)` token I'm unable to see the option for `Stake`, as it's found for other tokens like `KAVA`, `ATOM`, etc.

So how is it staking for `ADA` implemented then?

**Comment by Milerius** [comment]
Hello @x80486 - it's not yet implemented in the end user application, stay tuned.

**Comment by Kamranwew70** [comment]
چرا
