### ISSUE TITLE
Expose Basic Hex and Byte Array conversion utilities

### ISSUE THREAD

**Issue by eddywm** [TrustWallet/wallet-core#248]
As we have started to move away from Java crypto stack (`BitcoinJ`, `Web3J`), we are still depending on these libs for some basic utility functions like :
- Converting `ByteArray` to `HexString`
- Converting `HexString` to `ByteArray`
- Handling of Hex `0x` prefix in the conversion process

**Comment by alejandro-isaza** [comment]
I think it's overkill to implement this in wallet core. It should be implemented in the host language (Java or Kotlin).
