### ISSUE TITLE
HDWallet Mnemonic import problem

### ISSUE THREAD

**Issue by developerjet** [trustwallet/wallet-core#2489]
**Describe the bug**
                
                let txContext = "gas source rapid topic swim vintage tiny symptom foil boy action parade"
                let hdWallet = HDWallet(mnemonic: txContext, passphrase: passphrase)
                let eth = Ethereum()
                let privateKey = hdWallet.getKey(at: eth.derivationPath(account: 0, change: 0, at: 0))
                let publicKey = privateKey.publicKey(compressed: false)
                let address = publicKey.ethereumAddress.description.lowercased()

                print("privateKey === \(privateKey)")  // be5103569203d40a8c464a0e698982a67ce421620a044dc1c1ead60db74dae77
                print("publicKey === \(publicKey)") // 04a97296ab6dc7fa2a9cccf3e9bea100aceeb305abb7ebf14851ad02abf3aa50144a5f99956c6579d4c7f3980918118aeb57e45420e04b012604ca42c65f78877b
                print("address === \(address)") // 0xfb8fb12b7457136d919bb1227bd7f9b51e0818cc

**To Reproduce**

**Expected behavior**
Mnemonics：gas source rapid topic swim vintage tiny symptom foil boy action parade
Correct address: 0x1fce35fed32bd480607cafd818350a3ff3d5cfea

You can import and verify the metamask through this mnemonic. The correct eth address should be 1fce35fed32bd480607cafd818350a3ff3d5cfea

Please help me to check the specific reason or where my code is wrong. Thank you very much.

**Screenshots**

**Additional context**
Hello, I have an urgent question to ask. Why do I import the wallet through mnemonic words? Why do the generated addresses and private keys not match the addresses and private keys on the metamask wallet? Please check them for help. Thank you.

**Comment by hewigovens** [comment]
try `hdWallet.getKeyForCoin(CoinType.ethereum)`, I got correct result:
```bash
Create wallet: gas source rapid topic swim vintage tiny symptom foil boy action parade
Get Ethereum public key: 0x045ef02298377d918dbcfa35a93bd4f51e76723d83447a98cd75ed3830b0e51513380708e0d00393ab5c5ee8650124687ae3786cffd6b95aa38612aea127c34ad9
Get Ethereum address: 0x1FcE35Fed32bd480607CAFD818350A3fF3d5CFeA
```

**Comment by developerjet** [comment]
> try `hdWallet.getKeyForCoin(CoinType.ethereum)`, I got correct result:
> 
> ```shell
> Create wallet: gas source rapid topic swim vintage tiny symptom foil boy action parade
> Get Ethereum public key: 0x045ef02298377d918dbcfa35a93bd4f51e76723d83447a98cd75ed3830b0e51513380708e0d00393ab5c5ee8650124687ae3786cffd6b95aa38612aea127c34ad9
> Get Ethereum address: 0x1FcE35Fed32bd480607CAFD818350A3fF3d5CFeA
> ```

I tried to import the wallet in the way you said, but the value is still wrong. What is the reason.

            let mnemonicWords = txContext // gas source rapid topic swim vintage tiny symptom foil boy action parade
            print("mnemonics === \(txContext)")
            
            // 助记词导入
            let passphrase = wallet.walletPassword
            guard let hdWallet = HDWallet.init(mnemonic: mnemonicWords, passphrase: passphrase) else {
                return
            }
            
            let privateKey = hdWallet.getKeyForCoin(coin: .ethereum)
            let puiblicKey = privateKey.getPublicKeySecp256k1(compressed: false)
            walletAddress = hdWallet.getAddressForCoin(coin: .ethereum)
            wallet.privateKey = privateKey.data.hexString
            wallet.publicKey = puiblicKey.description
            wallet.mnemonics = mnemonicWords // 助记词
        }
        
        print("privateKey === \(wallet.privateKey)")
        print("walletAddress === \(walletAddress)")
        
        //mnemonics === gas source rapid topic swim vintage tiny symptom foil boy action parade
        //privateKey === be5103569203d40a8c464a0e698982a67ce421620a044dc1c1ead60db74dae77
        //walletAddress === 0xfb8fB12B7457136d919BB1227Bd7F9B51e0818Cc

**Comment by hewigovens** [comment]
You set a non empty passphrase, try empty string

**Comment by developerjet** [comment]
> 

OK, I tried it according to your method. Now the address is correct. Thank you very much.

**Comment by developerjet** [comment]
Hello, how can I generate the private key and address of other currencies? 

For example, my cointype is 32。
`              // CoinType = 32
                let privateKey = hdWallet.getDerivedKey(coin: .gcCoin, account: 1, change: 0, address: 0)`
