### ISSUE TITLE
pod install curl: (22) The requested URL returned error: 403

### ISSUE THREAD

**Issue by developerjet** [trustwallet/wallet-core#2490]
**Describe the bug**
pod install curl: (22) The requested URL returned error: 403

**To Reproduce**
[!] Error installing TrustWalletCore
[!] /usr/bin/curl -f -L -o /var/folders/6p/3wv50zjs69x0gv7lb4l_qdgc0000gn/T/d20220810-32580-15rgx4i/file.zip https://s3.amazonaws.com/wallet-core/TrustWalletCore-iOS-0.10.0.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.11.3 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 403

**Expected behavior**
What is the way to import successfully? My terminal is hung with an agent or failed, but importing other libraries can succeed.

**Screenshots**

**Additional context**

**Comment by hewigovens** [comment]
you're installing very old build, can you try latest?

**Comment by developerjet** [comment]
How can I install the latest version? I directly used the pod 'trustwalletcore' sample provided by you to install the pod, and found that the installation failed all the time.

**Comment by hewigovens** [comment]
Which sample? We can update it

**Comment by developerjet** [comment]
> 

I integrated trustwalletcore according to this step, but the installation failed all the time, and I said that I could not find the previous resources in Amazon.https://developer.trustwallet.com/wallet-core/integration-guide/ios-guide

**Comment by hewigovens** [comment]
can you try this sample https://github.com/trustwallet/wallet-core/tree/master/samples/osx/cocoapods? it works for me, also trying to delete `Podfile.lock`

**Comment by developerjet** [comment]
> can you try this sample https://github.com/trustwallet/wallet-core/tree/master/samples/osx/cocoapods? it works for me, also trying to delete `Podfile.lock`

Now it can be installed normally, because the version corresponding to the pod was not specified before. Thank you
