### ISSUE TITLE
[Codegen] Map coin test folder name to coin-id so cointest

### ISSUE THREAD

**Issue by miloserdow** [trustwallet/wallet-core#2491]
Codegen/cointests generate duplicate folders for existing coins.
This is because some legacy tests are not using coin-id as a directory name, so we should either rename those directories or add mapping (like XRP -> tests/Ripple) to the script.

Please see discussion on [PR-2485](https://github.com/trustwallet/wallet-core/pull/2485) for more context.

**Comment by catenocrypt** [comment]
I am for rename.  Coin ID should not change ever, if name changes we can use `DisplayName`.
