### ISSUE TITLE
Elrond is no longer supported

### ISSUE THREAD

**Issue by DmitriyMikitenko** [trustwallet/wallet-core#2502]
Please update Elrond protobuf to current blockchain requirements

**Comment by kamranwew** [comment]
Hello, I have a serious problem

**Comment by kamranwew** [comment]
Hello, I have a serious problem

**Comment by kamranwew** [comment]
![Uploading CoinInn_2022-08-15 00_48_20.png…]()

**Comment by hewigovens** [comment]
Can you elaborate? just tested, sending is working
