### ISSUE TITLE
List tokens of a wallet from the seed phrase

### ISSUE THREAD

**Issue by hjaffali** [trustwallet/wallet-core#2505]
Hello team,

I would like to know if you can provide an example code to list all the tokens available for each network related to a specific wallet? 

I tried to compile the library in Linux OS, but didn't succeed, and I want to know if it is really possible to achieve what I want before moving to macOS or going deeper in the debugging.

Thank you in advance for your help.

**Comment by hewigovens** [comment]
You need to query the node using the address, wallet core doesn't support networking
