### ISSUE TITLE
New issue on the Trust Wallet ver. 6.27 | Can't keep a connection with PancakeSwap

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/wallet-core#2506]
Today, 08/16/2022 the connection with the DApp PancakeSwap stopped working as it used to work.
Now I need to sign in all the time I open the DAPP... the DAPP can't catch the PancakeSwap request to auto sign in.

To reproduce it, just open Trust Wallet,  Go to DApps... and click on "PancakeSwap"
So, Log in... and after, refresh the page, or tap the close button and back again!

You need to sign in again!!

It's a problem because my DAPP that uses the Trust Wallet core is now with the same issue!

It won't happen on the old TrustWallet version!

**Comment by hewigovens** [comment]
Let's track this on provider repo? I saw you created similar issue there
