### ISSUE TITLE
Add Monero support

### ISSUE THREAD

**Issue by Ridhubharan** [trustwallet/wallet-core#2507]
## Description

Name:
Monero. https://www.getmonero.org/

Symbol:
XMR

Documentation:
https://www.getmonero.org/get-started/what-is-monero/

Reason:
Monero is one of the most private cryptocurrencies and has very low transaction fee.

**Comment by hewigovens** [comment]
We created Monero support issue before, currently team doesn't have bandwidth to do it, will you be able to contribute? otherwise I'd like to close it for now
