### ISSUE TITLE
How can I generate private keys and addresses of other currencies

### ISSUE THREAD

**Issue by developerjet** [trustwallet/wallet-core#2509]
## Description
How can I generate private keys and addresses of other currencies
For example, cointype is 32

                // CoinType = 32
                let privateKey = hdWallet.getDerivedKey(coin: .gcCoin, account: 1, change: 0, address: 0)

https://green-chain.cc/
https://pex.green-chain.cc

Name:

HD Derivation Scheme:BIP44 / 32

Symbol:
GC

Documentation:

Reason:

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).
https://github.com/green-chain/about-us/blob/main/GREEN%20CHAIN.pdf

**Comment by hewigovens** [comment]
You can use `hdWallet.getKey(coin: CoinType, derivationPath: String)` to get the key, since `32` is not a known case defined in `TWCoinType.h`, you might need to use other coin type but same curve / public key type etc

**Comment by developerjet** [comment]
I try to generate the private key in this way, but the generated private key and address are not what I want, because I see that the cointype does not support the 32 coin type

**Comment by hewigovens** [comment]
if `hdWallet.getKey(coin: .ethereum, derivationPath: "m/44'/32'/0'/0/0")` doesn't work, you may need to fork wallet core and add the coin type

**Comment by developerjet** [comment]
How can I add a wallet corresponding to other currencies? At present, you do not support cointype = 32
