### ISSUE TITLE
WIF Format

### ISSUE THREAD

**Issue by ahsankrypto** [trustwallet/wallet-core#2512]
**Is your feature request related to a problem? Please describe.**

I have successfully generated 256 bit private key using trust wallet core in iOS. But i would like to convert the key in WIF format.

**Describe alternatives you've considered**

I have written a custom method to convert it by appending the prefix and running SHA256 and a base58 conversion. But i am looking for a method in trust wallet core that might allow me to convert/create a WIF format private key!

**Comment by hewigovens** [comment]
Please take a look: https://developer.trustwallet.com/wallet-core/faq#does-wallet-core-support-wif
