### ISSUE TITLE
بیایید MINA را در Trustwallet شروع کنیم

### ISSUE THREAD

**Issue by N3481** [trustwallet/wallet-core#2513]
## Description

Name:

HD Derivation Scheme:

Symbol:

Documentation:

Reason:

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by hewigovens** [comment]
duplicated with https://github.com/trustwallet/wallet-core/issues/1828
