### ISSUE TITLE
Use consistent format for address/sender

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#253]
`TW_Binance_Proto_TradeOrder` - change `sender: Data` => `sender: String`
`TWBinanceSendOrder`- change `address: Data` => `address: String`

@alejandro-isaza would you be able to check in the codebase where else we are using this?

**Comment by alejandro-isaza** [comment]
We can't change the Binance protos because they are used for signing. Changing them will generate an invalid signature.
