### ISSUE TITLE
Nano Missing

### ISSUE THREAD

**Issue by NEVARLeVrai** [trustwallet/wallet-core#2535]
hello, 
Today I went to see my wallet and suddenly all my nano disappeared so I look in the nano and there are 0 transactions whereas when I go to a blockchain tracker site I see That I still have the nanos, I have reset trust wallet several times, but the application still does not want to display the nano
![Screenshot_2022-08-25-08-16-33-598_com wallet crypto trustapp](https://user-images.githubusercontent.com/63956787/186589228-7e711207-2724-47aa-8d63-ab43c6c1a503.jpg)
![Screenshot_2022-08-25-08-16-31-531_com wallet crypto trustapp](https://user-images.githubusercontent.com/63956787/186589282-be8f191e-9ae1-4e3b-a8b6-a025276c4429.jpg)
![Screenshot_2022-08-25-08-16-22-954_com android chrome](https://user-images.githubusercontent.com/63956787/186589324-c9261c09-df27-45b4-bf91-3b56e4cd5a82.jpg)

**Comment by NEVARLeVrai** [comment]
I have checked the correct address

**Comment by NEVARLeVrai** [comment]
how do i get them back?

**Comment by catenocrypt** [comment]
Currently nano has issues due to very slow network syncing, this is also mentioned in a banner in the app (AFAIK).
Check the address on official nano explorer, your txs should be there.
