### ISSUE TITLE
[Wasm] Exception investigation

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#2536]
Try again to enable full c++ exception for wasm

**Comment by miloserdow** [comment]
I’ve tried to tweak emscripten (including current version, latest stable version, latest dev version) with different compile options (-O0, -O1, -O2) with exception options set -sNO_DISABLE_EXCEPTIONS (+ other): exceptions are not caught properly (resulting with either with crash, or with annotated crash).

I also tried experimental -fwasm-exceptions but our code won't build with them.

Unfortunately, for now wasm exceptions support is a non-option.
