### ISSUE TITLE
Could not GET 'https://maven.pkg.github.com/trustwallet/wallet-core/com/trustwallet/wallet-core/2.9.8/wallet-core-2.9.8.pom'.

### ISSUE THREAD

**Issue by saberlpslpsl** [trustwallet/wallet-core#2538]
**Describe the bug**
I try run example，but I am get a failed

Could not GET 'https://maven.pkg.github.com/trustwallet/wallet-core/com/trustwallet/wallet-core/2.9.8/wallet-core-2.9.8.pom'. Received status code 401 from server: Unauthorized
**To Reproduce**
I hava setting gpr.user & gpr.key,but I cant  gradle sync success

**Screenshots**
![image](https://user-images.githubusercontent.com/112361447/187117263-f1fd0008-1429-43dc-8586-d212540aebab.png)

**Additional context**
I doubt whether my token is correct, but I can use it to request GitHub API，Successed.

Do you need other permissions or steps？

**Comment by hewigovens** [comment]
Take a look at this guide: https://developer.trustwallet.com/wallet-core/integration-guide/android-guide#adding-library-dependency, make sure your token has package read permission

**Comment by acomet** [comment]
Remove double quotes @saberlpslpsl
