### ISSUE TITLE
Hello, how to generate the wallet address of BTC test network.

### ISSUE THREAD

**Issue by developerjet** [trustwallet/wallet-core#2541]
**Describe the bug**
Hello, how to generate the wallet address of BTC test network.
After reading the code, BTC test network wallet address creation and transfer are not supported at present.

**Comment by hewigovens** [comment]
correct, please take a look at https://developer.trustwallet.com/wallet-core/faq#does-it-support-bitcoin-ethereum-testnet

**Comment by developerjet** [comment]
> correct, please take a look at https://developer.trustwallet.com/wallet-core/faq#does-it-support-bitcoin-ethereum-testnet

Hello, I have modified the registry.json in the downloaded source code and added bitcointest. However, how to generate the corresponding code of the BTC test network.

**Comment by catenocrypt** [comment]
Testnet address needs two modifications: coin in derivation path (second element) should be 1 instead of 0, this is settable in registry.json (generate_files is needed), and prefix is 'tb' instead of 'bc'.

**Comment by developerjet** [comment]
> Testnet address needs two modifications: coin in derivation path (second element) should be 1 instead of 0, this is settable in registry.json (generate_files is needed), and prefix is 'tb' instead of 'bc'.

I modified the registry in the demo code registry.json, adding the configuration of btctest. Then, how to generate btctest related methods in the code? I don't know how to compile and generate new code that can support btctest.

**Comment by developerjet** [comment]
I ran the file and prompted this message.

jett@TdeMacBook-Pro ~ % /Users/jett/Desktop/wallet-core/tools/generate-files ; exit;
/Users/jett/build/local does not exist or not complete, fallback to /usr/local
PREFIX: /usr/local

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
