### ISSUE TITLE
Update request - Algorand ASA integration

### ISSUE THREAD

**Issue by headline-design** [trustwallet/wallet-core#2542]
This is a follow-up issue to one created in June 2022. PRs have been approved to add Algorand ASAs to Trust Wallet, but as of this writing, no update has been made to integrate Algorand ASAs. The previous issue we created was responded to with "Algorand ASA integration is coming" but no timeframe was given for said integration. We have paid for listing fees and completed successful PRs for this integration and we would appreciate a clear timeframe on when we can expect Algorand ASA integration in Trust Wallet.

**Comment by hewigovens** [comment]
I think it's still in our backlog, will check with product / app team to see their priorities

**Comment by Milerius** [comment]
Will re-open when needed
