### ISSUE TITLE
Empty ChainID for Cosmos blockchains

### ISSUE THREAD

**Issue by rsrbk** [trustwallet/wallet-core#2557]
**Describe the bug**
ChainID property on CoinType returns empty strings for all cosmos blockchain expect osmosis.

**To Reproduce**
- https://github.com/trustwallet/wallet-core/pull/2556 (btw I couldn't actually run tests in the iOS project there, no sure if it's broken)
- Reproduced in the TW iOS App: 
<img width="313" alt="Screenshot 2022-09-06 at 10 51 04" src="https://user-images.githubusercontent.com/9006070/188605221-82991693-1fc9-4df9-b1ec-0d1a39deb543.png">

**Expected behavior**
For cosmos it should return "cosmoshub-4"

**Comment by Milerius** [comment]
> **Describe the bug** ChainID property on CoinType returns empty strings for all cosmos blockchain expect osmosis.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> * [Reproduce chainID issue for CoinType #2556](https://github.com/trustwallet/wallet-core/pull/2556) (btw I couldn't actually run tests in the iOS project there, no sure if it's broken)
> * Reproduced in the TW iOS App:
> 
> <img alt="Screenshot 2022-09-06 at 10 51 04" width="313" src="https://user-images.githubusercontent.com/9006070/188605221-82991693-1fc9-4df9-b1ec-0d1a39deb543.png">
> 
> **Expected behavior** For cosmos it should return "cosmoshub-4"

Indeed: https://github.com/trustwallet/wallet-core/blob/1114cf79bf23d8125c717924738522669adfd77f/registry.json#L397 there is no chain id for some cosmos chain in the registry

**Comment by hewigovens** [comment]
X-post comment from: https://github.com/trustwallet/wallet-core/pull/2556#issuecomment-1238084831
