### ISSUE TITLE
The latest version 3.0.3 is not available on maven.

### ISSUE THREAD

**Issue by roxrook** [trustwallet/wallet-core#2575]
**Is your feature request related to a problem? Please describe.**
The latest version `3.0.3` is not available on maven.
```
implementation("com.trustwallet:wallet-core:3.0.3")
```
**Error**
```
> Could not find com.trustwallet:wallet-core:3.0.3.
  Searched in the following locations:
    - https://repo.maven.apache.org/maven2/com/trustwallet/wallet-core/3.0.3/wallet-core-3.0.3.pom
    - https://dl.google.com/dl/android/maven2/com/trustwallet/wallet-core/3.0.3/wallet-core-3.0.3.pom
    - https://jitpack.io/com/trustwallet/wallet-core/3.0.3/wallet-core-3.0.3.pom
    - https://jcenter.bintray.com/com/trustwallet/wallet-core/3.0.3/wallet-core-3.0.3.pom
  Required by:
```

**Describe the solution you'd like**
Can you guys publish the latest version on Maven?

**Describe alternatives you've considered**
To workaround this issue we have to downgrade to `2.6.3` which was released 03/2021.

**Additional context**

**Comment by hewigovens** [comment]
Usually it's caused by github package token, Have you checked this guide? https://developer.trustwallet.com/wallet-core/integration-guide/android-guide#adding-library-dependency
