### ISSUE TITLE
Bitcoin message signing and verification

### ISSUE THREAD

**Issue by CryptoManiac** [trustwallet/wallet-core#2597]
**Is your feature request related to a problem? Please describe.**
Not that I know of.  But I believe somebody thought about that at least once.

**Describe the solution you'd like**
It would be nice to have an ability to sign and verify messages without relying on third-party applications, such as bitcoin node or SPV clients. 

**Describe alternatives you've considered**
Currently I'm using OpenSSL-based solution to implement this functionality on application level. This is too far from optimal one and I'd be glad to get rid of OpenSSL dependency.

**Additional context**

There is a python implementation for reference:

https://github.com/stequald/bitcoin-sign-message/blob/master/signmessage.py

**Comment by catenocrypt** [comment]
Could you elaborate?
- Verify messages created by wallet core, or arbitrary messages?
- What kind of validation? Validation of format and contents like existence and amounts in UTXOs?
- Validation requires a lot of info from the blockchain (e.g. UTXO validation), and in general, wallet-core is not dealing with operations that involve obtaining arbitrary data from the blockchain (the minimal data needed always have to be supplied by the caller, ultimately obtained from a node).

**Comment by CryptoManiac** [comment]
* Arbitrary messages, of course, because compatibility with bitcoin core and electrum is a necessary evil. 
* This feature is usually needed to prove ownership of address. You have an address and you're able to sign some text to prove that you own its private key. Exchanges and some other cryprocurrency related resources are asking for it occasionally. 
* No blockchain or UTXO contexts are requred, the only requirement is access to corresponding private key. Message text is being prefixed with ```Bitcoin Signed Message:\n``` string constant, then hashed twice with sha256. After that resulting hash is signed using the private key to generate a recoverable signature. Verification is done in the similar way but the public key is used to check the signature validity. 

Standalone c++ implementation is available, it's built forked from old bitcoin core sources and built on top of OpenSSL primitives:

https://github.com/scintill/bitcoin-signature-tools

A word of caution, though, this code is dependent on deprecated APIs.

P.S. I see that Trezor software [has this feature](https://wiki.trezor.io/User_manual:Signing_and_verifying_messages). Main reason for creating this issue is that it would be good to have a possibility to implement the same feature using wallet-core API.

**Comment by catenocrypt** [comment]
OK, so it's just about _signature_ validation. Can you filter/prioritize these requirements?
- [single signature verification] Given a signature, and a public key, return if the signature is valid and indeed matches the public key
- [recover from signature] Given a signature, return the matching public key
- [hash signing] Given a hash and a private key, return the corresponding signature
- [tx signature verification] Given a signed bitcoin transaction, verify that the all required signatures are present and they are valid and with the correct public key.

The last one is more work, and we will probably not do it at this time, it may require support for some signature/script types which wallet-core does not use.  But the first 3 are not very complex in wallet-core.

**Comment by CryptoManiac** [comment]
@catenocrypt I believe there is a little misunderstanding.

It's far simpler and this is how it works in electrum, bitcoin core and trezor wallets:

Signature generation:

You have ```message```, address and its private key.

1. [Prepend](https://github.com/scintill/bitcoin-signature-tools/blob/master/signmessage.cpp#L37) ```message``` with ```Bitcoin Signed Message:\n``` magic constant
2. Calculate ```message hash```, a [double sha256 hash](https://github.com/scintill/bitcoin-signature-tools/blob/master/hash.h#L48) of the prefixed message
3. Generate a recoverable signature of ```message hash``` using the private key (see [SignCompact)](https://github.com/scintill/bitcoin-signature-tools/blob/master/key.cpp#L284) function for details
4. Encode resulting signature using Base64.

Signature verification:

You have ```message```, ```address``` and base64 serialized ```signature string```.

1. Decode provided ```address``` to [get public key hash](https://github.com/scintill/bitcoin-signature-tools/blob/master/verifymessage.cpp#L30) which is also commonly known as ```keyId```
2. Perform ```message hash``` calculation like it has been done while signing the ```message```
3. Decode ```signature string``` to get ```signature``` as a vector of bytes.
4. [Try to recover](https://github.com/scintill/bitcoin-signature-tools/blob/master/key.cpp#L327) the ```public key``` using the ```signature``` and ```message hash```. If it's not possible to recover the public key then signature is not valid, cease execution and return boolean false value.
5. Calculate ```hash160``` of recovered public key.
6. Compare ```keyId``` and ```hash160``` and return the boolean result of comparison.

P.S. Obviously, it's only possible to use legacy P2PKH and segwit P2WPKH addresses. Other address types doesn't contain a public key hash so message signing is not applicable to them. It's possible to use P2SH-P2WPKH addresses though, you'll only need to slightly modify the 5 and 6 steps of verification process.

**Comment by catenocrypt** [comment]
Any change to identify some test vector for us which we can reuse? Would be useful.

**Comment by catenocrypt** [comment]
All steps required are available as operations in wallet-core -- signing, recover, hash, base58.  I will add some tests/sample to illustrate.
I still consider whether to add as aggregate atomic operations in the Bitcoin API.

**Comment by catenocrypt** [comment]
Test data mentioned is here:
https://github.com/scintill/bitcoin-signature-tools/tree/master/tests

Test data from Trezor user manual  https://wiki.trezor.io/User_manual:Signing_and_verifying_messages  :
```
address:    39ybp87orA9AQkothsP6SqahY9wFnpnMXv
message:    Hello, world!
signature:  Iy+AzoNCOjfKRkcE3sUEHnTir5gmc41yN+mCTnPIlKvzMgDPsjc8FNpKKbh4P8nqlzRM9w4knv1hEpypyHY0wPs=
```

Online services for verification:
https://www.bitcoin.com/tools/verify-message/
https://www.verifybitcoinmessage.com/

**Comment by CryptoManiac** [comment]
There is online tool for signing and verification:

https://reinproject.org/bitcoin-signature-tool/#sign

I believe this might be useful for testing.
