### ISSUE TITLE
Unable to login in app after last update

### ISSUE THREAD

**Issue by AlchemistAction** [trustwallet/wallet-core#2603]
**Describe the bug**
After last few updates (may be after [this one](https://github.com/trustwallet/wallet-core/pull/2547)) application on Android doesn't allow to login if time is not set to automatic update. 
Red error line says "You can't use application useless time is customised!"

**To Reproduce**
On Android phone turn off "Set time automatically" in settings

**Expected behavior**
This application should not force me to change time settings on my phone

**Comment by hewigovens** [comment]
Hey, We add it for security reason
