### ISSUE TITLE
[CodeGen]: Update new coin templates

### ISSUE THREAD

**Issue by Milerius** [trustwallet/wallet-core#2604]
Originally posted by @hewigovens in https://github.com/trustwallet/wallet-core/pull/2595#discussion_r983022657_

## Motivation

- [ ] Make Entry class final by default, 99% of the time Entry is the final class for new chain additions - (Ethereum have some exceptions)
- [ ] Update `../Data.h` in Address / Signer template

**Comment by hewigovens** [comment]
Template path: `codegen/lib/templates/newcoin/Entry.h.erb`

**Comment by hewigovens** [comment]
Another place need to change: replace `../Data.h` with `Data.h` in `Address.h.erb` and `Signer.h.erb`
