### ISSUE TITLE
Support Bitcoin Testnet Address

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2611]
**Is your feature request related to a problem? Please describe.**
Bitcoin Testnet support is a relatively frequent request, but wallet core (and Trust Wallet) does not generally support testnets.
However, with the multiple derivations per coin support this is now could be used relatively easily.

**Describe the solution you'd like**
Bitcoin now has 2 derivations: default Segwit and Legacy. We could introduce a BitcoinTestnet derivation, which would generate testnet address. Note that testnet address differs in derivation path and hrp.

**Comment by bsgarage45** [comment]
https://github.com/trustwallet/wallet-core/issues/2626#issue-1399423604
