### ISSUE TITLE
The Open Network (TON)

### ISSUE THREAD

**Issue by sylvestrevgenhiveon** [trustwallet/wallet-core#2617]
Name: [The Open Network](https://ton.org/)

HD Derivation Scheme: Unfortunately don't know

Symbol: TONCOIN

Documentation: [TON Docs](https://ton.org/docs/#/)

Reason: The Open Network (TON) and its TONCOIN coin (this is a continuation of the Telegram Open Network project with its GRAM coin). The project is gaining popularity, it is revolutionary, and there are many possibilities such as staking, peer to peer network etc.

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by catenocrypt** [comment]
Wallet core supports Everscale, which is a rename of Free TON project.
https://everscale.network/
<img width="731" alt="image" src="https://user-images.githubusercontent.com/13562139/193938107-0fc2b4d4-722d-466a-8906-4d54a3f04b08.png">

**Comment by sylvestrevgenhiveon** [comment]
But The Open Network is the different project. Please, can you look at this project to investigate? Maybe it is the same and plugin can be used for both platforms: everscale and ton?

**Comment by catenocrypt** [comment]
I understand that they are 2 different projects (Open; Free -> Everscale).
Are you in touch with TON developers? Maybe they can contribute support to wallet core; as Everscale is added it may be not too complex.

**Comment by sylvestrevgenhiveon** [comment]
Unfortunately, I am not in touch with TON developers. I am just a developer from Ukraine, and we used your wallet core to develop our product. We hoped that trust wallet core will support The Open Network. We understand that Everscale is already supported, but if it would be a not big amount of work to add support for TON, as they have a lot in common with Everscale, then we would be very grateful to you.

**Comment by hewigovens** [comment]
@sylvestrevgenhiveon Would you mind sharing your product name?

**Comment by sylvestrevgenhiveon** [comment]
@hewigovens I'm so sorry but NDA.

**Comment by Milerius** [comment]
Has been integrated #2813 - closing
