### ISSUE TITLE
I am trying to getfeeformessage in SOLANA

### ISSUE THREAD

**Issue by DELJUJAZI** [trustwallet/wallet-core#2620]
### Discussed in https://github.com/trustwallet/wallet-core/discussions/2619

<div type='discussions-op-text'>

<sup>Originally posted by **blukhi99** October  4, 2022</sup>
I am trying to [getfeeformessage](https://docs.solana.com/developing/clients/jsonrpc-api#getfeeformessage) in the Solana chain where I need Base64 of encoding message.

I created code  like below

```ts
val transferMessage = Solana.Transfer.newBuilder().apply {
    recipient = AnyAddress(receiver, CoinType.SOLANA).description()
     value = amount.toBigDecimal().toWEI(decimals).toLong()
}.build()
val signingInput = Solana.SigningInput.newBuilder().apply {
    transferTransaction = transferMessage
    recentBlockhash = blockhash
    privateKey = ByteString.copyFrom(Base58.decodeNoCheck(_privateKey))
}.build()
val output = AnySigner.sign(signingInput, CoinType.SOLANA, Solana.SigningOutput.parser())
```
output.encode what I get but, when Pass Base64 encode or without encode Solana throw error  `**"message": "io error: failed to fill whole buffer"**`

Kindly help to resolve this
</div>

**Comment by catenocrypt** [comment]
See https://github.com/trustwallet/wallet-core/discussions/2619
