### ISSUE TITLE
Unable to resolve host "ethereum-rpc.trustwalletapp.com

### ISSUE THREAD

**Issue by sadikyalcin** [trustwallet/wallet-core#2624]
**Describe the bug**
Cannot make a transaction on eth. Get a 'Transaction error' with the message: "Unable to resolve host "ethereum-rpc.trustwalletapp.com": No address associated with hostname".

I've had this issue for a few months now.

**To Reproduce**
- Make a swap on Uniswap
- Approve TX

**Expected behavior**
The TX to confirm

**Screenshots**
![photo_2022-10-05_23-25-57](https://user-images.githubusercontent.com/8109619/194175446-0a642dfe-e577-4692-924b-42e9a9688e91.jpg)

**Additional context**
Tried with 3 different devices

- Android 11 & 12
- TW version: 5.19

**Comment by hewigovens** [comment]
Can you update your app in Google Play, latest version is 6.35

**Comment by hewigovens** [comment]
Check you if you're a beta tester, exit beta program and try updating again
