### ISSUE TITLE
[Solana] Expose unsigned tx as well

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2666]
**Is your feature request related to a problem? Please describe.**
In some cases transaction without signature would be needed, for e.g. for the `getfeeformessage` RPC call. This is available internally, but not exposed. 

**Describe the solution you'd like**
It could be exposed as additional field in `SigningOutput`.

**Additional context**
See discussion https://github.com/trustwallet/wallet-core/discussions/2619

**Comment by Milerius** [comment]
> **Is your feature request related to a problem? Please describe.** In some cases transaction without signature would be needed, for e.g. for the `getfeeformessage` RPC call. This is available internally, but not exposed.
> 
> **Describe the solution you'd like** It could be exposed as additional field in `SigningOutput`.
> 
> **Additional context** See discussion #2619

How about implementing similar way as: https://github.com/trustwallet/wallet-core/pull/2591 introducing new C API for unsigned tx, and make a clear separation? Will require a bit more effort but probably easier to maintain in the future.

**Comment by catenocrypt** [comment]
> How about implementing similar way as: #2591 introducing new C API for unsigned tx, and make a clear separation? Will require a bit more effort but probably easier to maintain in the future.

It's is 'free' to expose any intermediate output in the Signing process, as thery are computed anyways, this is present in several `SingingOuput`s. It is uniform if here is only the Sign method to take `SigningInput`. Only complication is that if you want to use in case the private key is not known, supporting requires adding some conditionals.
The separate API is also fine, it has it's own benefit (being independent), but maybe the Signing way is more uniform across chains.
