### ISSUE TITLE
 code: 'MODULE_NOT_FOUND'

### ISSUE THREAD

**Issue by inspi-writer001** [trustwallet/wallet-core#2672]
Error: Cannot find module '@trustwallet/wallet-core/dist/src/wallet-core'
Require stack:

    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/mac/Documents/healthgo/inner/index.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
**Screenshots**

**Additional context**

**Comment by Milerius** [comment]
> Error: Cannot find module '@trustwallet/wallet-core/dist/src/wallet-core' Require stack:
> 
> ```
> at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
> at Function.Module._load (node:internal/modules/cjs/loader:833:27)
> at Module.require (node:internal/modules/cjs/loader:1057:19)
> at require (node:internal/modules/cjs/helpers:103:18)
> at Object.<anonymous> (/Users/mac/Documents/healthgo/inner/index.js:1:18)
> at Module._compile (node:internal/modules/cjs/loader:1155:14)
> at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
> at Module.load (node:internal/modules/cjs/loader:1033:32)
> at Function.Module._load (node:internal/modules/cjs/loader:868:12)
> at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
> ```
> 
> code: 'MODULE_NOT_FOUND', **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional context** Add any other context about the problem here.

Hello @inspi-writer001, can you please give more informations, how to reproduce it and give your code sample that produce this error?

**Comment by inspi-writer001** [comment]
const { HDWallet } = require("@trustwallet/wallet-core/dist/src/wallet-core");

HDWallet.create(256, "mysecretpassword").then((e) => {
  console.log(e);
});

const createWallet = async () => {
  const wallet = await HDWallet.create(256, "mysecretpassword");
  console.log(wallet);
};

createWallet();

**Comment by inspi-writer001** [comment]
<img width="918" alt="Screenshot 2022-10-24 at 09 35 42" src="https://user-images.githubusercontent.com/94226358/197484391-9051ce8b-008d-41ea-a8ea-b23a7df6eb33.png">


here's a screenshot of the code

**Comment by inspi-writer001** [comment]
or is there a link to an example that i can follow through? thanks

**Comment by inspi-writer001** [comment]
thanks a lot, 
I struggled with that link, but this solved it for me, I followed it exactly as it's shown in the example and it worked
https://github.com/trustwallet/wallet-core/blob/master/samples/node/index.ts

thanks for your speedy response also💯🎉
