### ISSUE TITLE
Using StoredKey is slow in Android than in iOS...

### ISSUE THREAD

**Issue by SinestCorporation** [trustwallet/wallet-core#2681]
When I write code as below, processing speed slower in Android than in iOS.
It takes about 2 seconds in Android device and 0.4 seconds in iOS device.
Even Android devices are newer devices.

val key = StoredKey(name, passwordByteArray)
val wallet = key.wallet(passwordByteArray)

Can I improve processing speed in Android..?
I want to know if this problem can be solved.
Please help me.

**Comment by Milerius** [comment]
> When I write code as below, processing speed slower in Android than in iOS. It takes about 2 seconds in Android device and 0.4 seconds in iOS device. Even Android devices are newer devices.
> 
> val key = StoredKey(name, passwordByteArray) val wallet = key.wallet(passwordByteArray)
> 
> Can I improve processing speed in Android..? I want to know if this problem can be solved. Please help me.

Hello @SinestCorporation - can you give more information such as which Android device are u using, android version etc.

**Comment by SinestCorporation** [comment]
I used Samsung Galaxy S22 device.

**Comment by catenocrypt** [comment]
The wallet private keys are stored encrypted; using two-way encryption, which is resource-intensive. The more resource intensive it is, the longer it takes, but the more secure it is.
Fortunately this operation is executed not to often, a few seconds should be acceptable.

Please note that it is possible to set the level to lower, which means faster but less secure result:

https://github.com/trustwallet/wallet-core/blob/master/include/TrustWalletCore/TWStoredKeyEncryptionLevel.h#L15
https://github.com/trustwallet/wallet-core/blob/master/tests/common/Keystore/StoredKeyTests.cpp#L474
