### ISSUE TITLE
Switch EVM Network not working ios Trust Wallet

### ISSUE THREAD

**Issue by joseptl** [trustwallet/wallet-core#2687]
**Describe the bug**
When I connect the dapp to the BNB Smart Chain network on iOS, the app does not make the change and the trust wallet object remains with the ETH network data.

**To Reproduce**
1. Enter to https://test.winem.io/
2. Click the connect button and select the BNB Smart Chain network
3. If the Trust Wallet app did not make the network change, the dapp will display a modal with the ethereum network id (1).

**Expected behavior**
The dapp must be successfully connected to the BNB Smart Chain

**Screenshots**
![WhatsApp Image 2022-10-28 at 7 40 06 PM](https://user-images.githubusercontent.com/83504893/198750913-b0d3d2c2-6630-434b-93b9-0d509c2d8b6e.jpeg)
![WhatsApp Image 2022-10-28 at 7 40 06 PM (1)](https://user-images.githubusercontent.com/83504893/198750922-4c68c95b-0da5-4e8c-9813-79a719a2ea66.jpeg)

**Additional context**
In the trust wallet application for Android devices, the behavior is as expected for the connection to the BNB Smart Chain network.

**Comment by Milerius** [comment]
Hello @joseptl - thanks for opening the PR, the Issue is unrelated to `wallet-core`, please open a ticket to the following url: https://support.trustwallet.com/en/support/home
