### ISSUE TITLE
[Keystore] Allow keystore to select different encryption algorithms

### ISSUE THREAD

**Issue by y3fers0n** [trustwallet/wallet-core#2701]
Allow keystore for web extension to select different encryption algorithms i.e.: aes-256-ctr and maybe salt

**Comment by hewigovens** [comment]
The changes I can think of:

1. Need to add a new method with AES key length parameter (128/192/256) to `TWStoredKey`
2. Fix the hardcode value `aes-128-ctr` in `EncryptionParameters.cpp`
3. Change Swift / TypeScript Keystore accordingly
4. Tests
