### ISSUE TITLE
Building THORChain Swap transactions for ATOM/LTC/AVAX/BCH/DOGE

### ISSUE THREAD

**Issue by ArtemGoryunov** [trustwallet/wallet-core#2714]
**Is your feature request related to a problem? Please describe.**
Current [implementation](https://github.com/trustwallet/wallet-core/pull/1371) allows to build transaction for BTC, ETH, BNB, THOR. Need to extend it.

**Describe the solution you'd like**
Add support for ATOM/LTC/AVAX/BCH/DOGE

**Describe alternatives you've considered**
None

**Checklist**

- [x] Support ATOM
- [x] Support LTC
- [x] Support AVAX
- [x] Support BCH
- [x] Support DOGE

**Resources**

Resources link

**Additional context**

**Comment by Milerius** [comment]
Completed
