### ISSUE TITLE
[ThorChainSwap/BTC] Handle memo-overflow cases as error

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2730]
ThorChainSwap uses memo field for X-chain swap info. In case of swap from Bitcoin chain, memo is stored in `OP_RETURN` output data. This has a max limit of 80 bytes. In case of longer memo, it is truncated.
Instead, the input TX generation should fail with appropriate message, preventing accidental mis-swap.
The possibility of recently-introduce affiliate fee generally makes the memo longer (#2715).

**Comment by pluto9r** [comment]
This is supported automatically when using THORNode's /quote/swap endpoint. These are new endpoints recently released: https://dev.thorchain.org/thorchain-dev/quickstart-5min-swap

**Comment by pluto9r** [comment]
THORSwap API may offer rich features like support for DEX aggregation. Just a heads up that this functionality exists native to THORNode.

**Comment by Dstoney** [comment]
> ThorChainSwap uses memo field for X-chain swap info. In case of swap from Bitcoin chain, memo is stored in `OP_RETURN` output data. This has a max limit of 80 bytes. In case of longer memo, it is truncated.
> 
> Instead, the input TX generation should fail with appropriate message, preventing accidental mis-swap.
> 
> The possibility of recently-introduce affiliate fee generally makes the memo longer (#2715).
> 
> 

Request a new quote

**Comment by Dstoney** [comment]
Request a new quote
