### ISSUE TITLE
Kotlin Multiplatform project

### ISSUE THREAD

**Issue by MaximPestryakov** [trustwallet/wallet-core#2740]
Create new separate project for Kotlin Multiplatform with JVM, iOS and JS(?) support. Switch current Android (Java) project to maintenance mode

- [ ] Codegen part
    - [ ] Codegen Kotlin KMM for WASM
    - [ ] Extend CoinType to class in order to support Wasm property #2391 
    - [ ] (Optional) Codegen Kotlin KMM for iOS
    - [ ] (Optional) Codegen Kotlin KMM for Android
    - [ ] Extend gitignore to ignore generated file
- [ ] Similar script like `tools/android-release` to release to maven central repository the KMM library, [tutorial here](https://kotlinlang.org/docs/multiplatform-publish-lib.html)
- [ ] Similar script like `tools/android-build` for KMM
- [ ] Similar script like `tools/android-tests` for KMM
- [ ] Minimal UT support
    - [ ] Encoding functionality unit tests just

**Comment by Rastaman231** [comment]
Hi there whats happening
