### ISSUE TITLE
ThorSwap: Support swapping from ERC20 tokens

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2744]
Currently ThorChainSwap supports swaps from ETH and into ERC20 tokens, but not from ERC20 tokens.
Changes needed:
- Extend `SwapInput` (in proto) with (optional) `from_asset: Asset`  (common with #2743)
- Change logic to set the source tokenId in the transaction.

Update: The Eth transaction is always a smart contract call to ThorSwap, and it includes tokenId, which is currently always set to 0. So required change is probably minimal.
Sample Eth tx (swap from Eth):  https://etherscan.io/tx/0x8228E8FE008091C3EEB2268AB806910AB3DF61FDCCB03CCEE9FA6FDB224DD879

**Note**: To double check the parameters of the Eth contract called; specifically 2nd parameter is currently set to `toAssetAddressBin`, but it may be from asset.

**Comment by Baslc** [comment]
For ERC20 tokens you need to call the contract, however for ETH you can actually just transfer to an asgard address with the appropriate memo. This would save quite a bit of gas as the smart contract call is a bit more expensive than native ETH transfers.

Here's an example TX:
https://etherscan.io/tx/0x21CF600051E9A4F4706537073D0FB690C3DF0E6736C079F64250A88B1C9AEBBE

Which was observed on viewblock:
https://viewblock.io/thorchain/tx/21CF600051E9A4F4706537073D0FB690C3DF0E6736C079F64250A88B1C9AEBBE

Both methods are accepted, one is just more gas efficient (but comes with the risk of transferring to an inactive old asgard which means loss of funds). The same should hold true for AVAX, but I am not 100% sure on that.

**Comment by catenocrypt** [comment]
> For ERC20 tokens you need to call the contract, however for ETH you can actually just transfer to an asgard address with the appropriate memo.

Thank you, we will check this out.

**Comment by catenocrypt** [comment]
As info, here is the contract currently used when swapping from ETH:

<img width="915" alt="image" src="https://user-images.githubusercontent.com/13562139/203744718-98d23759-fddc-4e5e-ac36-fa9ff8808a02.png">

https://etherscan.io/address/0xc145990e84155416144c532e31f89b840ca8c2ce#code
https://etherscan.io/tx/0x8228E8FE008091C3EEB2268AB806910AB3DF61FDCCB03CCEE9FA6FDB224DD879

**Comment by catenocrypt** [comment]
Additional info (from Oleg P.):

"Thorchain has pools for Ether as well as a few select ERC20s. It is necessary to use the deposit method on the thorchain router when you swap in an ERC20. However, when going in Thorchain with Ether, you can simply send the Ether to the corresponding inboundAddress with the same memo, just like you would do on other non evm chains. Using send over deposit for Ether will be more gas efficient and will lead to more asset on the other chain."

**Comment by oxyc** [comment]
btw heads up in case you’re not monitoring the interface alerts channel on discord

![5FE27908-6F43-4DFA-8CEF-F109B2187ABB](https://user-images.githubusercontent.com/302736/204653959-92121140-6cda-4e1d-9605-2688bfc74b3d.jpeg)
