### ISSUE TITLE
ThorSwap: Support BSC chain

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2745]
Currently ThorChainSwap implementation supports ETH and BNB Beacon chains, but not BSC.  Support BSC chain, similarly to ERC, as source, as destination, and also with BEP20 tokens.

**Comment by oxyc** [comment]
note that TC doesn’t support BSC, only bep2

**Comment by hewigovens** [comment]
@oxyc good point

**Comment by catenocrypt** [comment]
They should :D

**Comment by oxyc** [comment]
It won the _NextChain_ vote that was taken a few weeks back :)

**Comment by oxyc** [comment]
Thorchain now supports BSC :)

**Comment by momka1234** [comment]
K
