### ISSUE TITLE
ThorSwap: Support swapping from RUNE

### ISSUE THREAD

**Issue by optout21** [trustwallet/wallet-core#2746]
Currently ThorChainSwap supports swaps to RUNE, but not from RUNE.
To support, need to create `SigningInput` for transfer transaction on Rune chain.

**Comment by Helpcenter101** [comment]
> Currently ThorChainSwap supports swaps to RUNE, but not from RUNE.
> To support, need to create `SigningInput` for transfer transaction on Rune chain.

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Helpcentera** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by CustomerTeam001** [comment]
We'd be happy to look into this for you 
kindly file a support ticket below 
https://forms.gle/FhSmn4AznQtZcruX8

**Comment by satoshiotomakan** [comment]
Completed at https://github.com/trustwallet/wallet-core/pull/3357
