### ISSUE TITLE
XRP wallet works but transactions are not visible

### ISSUE THREAD

**Issue by MrWeb** [trustwallet/wallet-core#2749]
**Describe the bug**
I imported in my wallet different currencies, they all work fine, the only one is XRP which is importing ok, showing the amount correctly but in the "transactions list" nothing shows up, it shows "Transactions will appear nere - BUY XRP"

**To Reproduce**
Import XRP in your wallet, open the XRP coin detail and the transactions will not appear.

**Expected behavior**
Import XRP in your wallet, open the XRP coin detail and the transactions should show up

**Screenshots**
![IMG_7593](https://user-images.githubusercontent.com/4120466/202996471-2d842335-8327-4098-86b1-45b7c0728737.jpg)

As a note here, I've imported XRP from 3 different accounts so at least 3 transactions should show up.

**Comment by Milerius** [comment]
Hello, this is not related to wallet-core, there is no transaction handling in wallet core, please contact: https://support.trustwallet.com/en/support/home
