### ISSUE TITLE
Bitcoin transaction signing failed in nodejs

### ISSUE THREAD

**Issue by sc-starman** [trustwallet/wallet-core#2756]
**Describe the bug**
Since there is no test for bitcoin signing, I followed up swift example and everything seems fine until anysigner.sign() method got an exception of error: 5 and I couldn't find any documentation about errors that would explain why this happen.

**To Reproduce**

`                    

           const txIdhash = this.HexCoding.decode("3c94a57a67b245d0e49a4b3e2e7fbd5c72b64ba8dd1ce1da846b304bc1fea98b");

            let utxo = TW.Bitcoin.Proto.UnspentTransaction.create({
                outPoint: {
                    hash,
                    index: 0,
                    sequence: 4294967295,
                },
                amount: new Long(100000),
                script: this.BitcoinScript.lockScriptForAddress("bc1qskg454dpfflwyfan3r7cw5u9sftw6c3dkz7e20",this.CoinType.bitcoin).data(),
            })

            let privateKey = this.wallet.getKey(this.CoinType.bitcoin,"m/44'/0'/1'/0/6")

            let txInput = TW.Bitcoin.Proto.SigningInput.create({
                hashType: this.BitcoinSigHashType.all.value,
                coinType: this.CoinType.bitcoin.value,
                amount: new Long(96000),
                toAddress: "bc1qhklyrncrvhpg93f90aksqp7eljlzy4pn8ltltc",
                privateKey: privateKey.data(),
                plan: {
                    amount: new Long(96000),
                    fee: new Long(4000),
                    branchId: this.HexCoding.decode('0xbb09b876'),
                    change: new Long(0),
                    utxos: [utxo]
                }
            })

            const input = TW.Bitcoin.Proto.SigningInput.encode(txInput).finish();
            let txOutput = this.AnySigner.sign(input, this.CoinType.bitcoin);

            const output = TW.Bitcoin.Proto.SigningOutput.decode(txOutput);

            console.log(txOutput) // error code : 5

`

**Expected behavior**

decoded transaction output successfully signed and ready to broadcast.

**Screenshots**

**Additional context**

**Comment by catenocrypt** [comment]
Error codes are defined in `Common.proto`  https://github.com/trustwallet/wallet-core/blob/master/src/proto/Common.proto#L23
5 is `Error_missing_private_key`. This means there is an UTXO for which there is no matching private key provided. The obvious reason is providing wrong private key, or there may be some issue with the encoding.
