### ISSUE TITLE
Opensea accept and sign failed in andriod

### ISSUE THREAD

**Issue by 18227125653** [trustwallet/wallet-core#2758]
**Describe the bug**
opensea accept and sign failed in andriod.

**To Reproduce**
            val privateKey = PrivateKey(String(WCController.linkEntityNew!!.privateKey).decodeHex())
            val signed = privateKey.sign(
                if (sWCEthereumSignMessage!!.type == WCEthereumSignMessage.WCSignType.TYPED_MESSAGE)
                    sWCEthereumSignMessage!!.data.toByteArray()
                else
                    sWCEthereumSignMessage!!.data.decodeHex(),
                CoinType.ETHEREUM.curve()
            )
            WCController.wcClient.approveRequest(sHandshakeId!!, WCController.bytesToHex(signed))

sWCEthereumSignMessage!!.data like this：
0x57656c636f6d6520746f204f70656e5365 
61210a0a436c69636b20746f207369676e20 
696e20616e6420616363657074207468652 
04f70656e556561205465726d75206f6620 
556572766963655a2068747470735a2f2f6f 
70656e7365612e696f2f746f730a0a546869 
7320726571756573742077696c6c206e6f74 
2074726967676572206120626c6f636b6368 
61696e207472616e73616374696f6e206f722 
0636f757420616e792067617320666565732 
e0a0a596f75722061757468656e746963617 
4696f6e207374617475732077696c6c20726 
573657420616674657220323420686175727 
32e0a0a57616c6c657420616464726573753 
a0a50786536553464575037393665643766 
30386558373831653850623166626433303 
162305637663366310a0a4e6f6e63653a0a5 
9646435323861622d 343838312d 343066612 
d393433322d386438336530353964303033

val signed always same

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vcoolish** [comment]
Hi! You have a bug in your implementation, signPersonalMessage request should have specific prefix 
Please read more about sign in messages here https://eips.ethereum.org/EIPS/eip-4361
