### ISSUE TITLE
Polkadot call_params  is 'dest' or 'to_address' ??

### ISSUE THREAD

**Issue by qbd2021** [trustwallet/wallet-core#2759]
wallet-core   
Polkadot.proto
is "to_address"
message Balance {
    // transfer
    message Transfer {
        // destination address
        string to_address = 1;

        // amount (uint256, serialized little endian)
        bytes value = 2;
    }
    oneof message_oneof {
        Transfer transfer = 1;
    }
}

Polkadot python code is "dest"
https://github.com/polkascan/py-substrate-interface
call_params={
        'dest': '5E9oDs9PjpsBbxXxRE9uMaZZhnBAV38n2ouLB28oecBDdeQo',
        'value': 1 * 10**12
    }
 
Is wallet-core too old?

**Comment by hewigovens** [comment]
No, wallet core reads `to_address` from `Polkadot.proto` and encodes it just like `dest`

**Comment by hewigovens** [comment]
You were viewing the json presentation of `Polkadot::Proto::SigningInput` which is not the final encoded bytes sent to the network, please take a look at `Polkadot::Proto::SigningOutput`
