### ISSUE TITLE
Polkadot call_params is 'dest' or 'toAddress' ?? 

### ISSUE THREAD

**Issue by qbd2021** [trustwallet/wallet-core#2760]
Polkadot python code is "dest"
https://github.com/polkascan/py-substrate-interface

call_params={
'dest': '5E9oDs9PjpsBbxXxRE9uMaZZhnBAV38n2ouLB28oecBDdeQo',
'value': 1 * 10**12
}

This is the result of my coding

TW::Polkadot::Proto::SigningInput
auto balanceCall = input.mutable_balance_call();
auto transfer = balanceCall->mutable_transfer();
auto value = TW::store(TW::uint256_t(2000000000));
transfer->set_to_address(toAddress.string());
transfer->set_value(value.data(), value.size());

"balanceCall": {
"transfer": {
"toAddress": "xxxxxxx",
"value": "dzWUAA=="
}
}
not "dest"
Is my understanding wrong?

**Comment by hewigovens** [comment]
duplicated with https://github.com/trustwallet/wallet-core/issues/2759
