### ISSUE TITLE
Swift Warning: TWPublicKey

### ISSUE THREAD

**Issue by chrislang1** [trustwallet/wallet-core#2761]
The latest release causes a warning [here](https://github.com/trustwallet/wallet-core/blob/d9f73cb4eff52858eb5f78d23e1007cf6f191f16/include/TrustWalletCore/TWCoinType.h#L201) in `TWCoinType.h`. This is causing Xcode builds which treat warnings as errors for production releases to fail.

**Comment by hewigovens** [comment]
Maybe worth to fix this in rust branch

**Comment by catenocrypt** [comment]
In the last iOS build on master, I see this warning -- I assume this is what is meant:

```
 ⚠️  /Users/runner/work/wallet-core/wallet-core/swift/include/TrustWalletCore/TWCoinType.h:201:64: declaration of 'struct TWPublicKey' will not be visible outside of this function
                                                        struct TWPublicKey* _Nonnull publicKey);
```

I assume it could be solved by:
- `include "TWPublicKey.h"` --> but this could lead to circular includes
- forward decl similar to PrivateKey:`struct TWPublicKey;`
