### ISSUE TITLE
Cold Wallet NFC Card

### ISSUE THREAD

**Issue by cryptoplatz-vault** [trustwallet/wallet-core#2762]
**Is your feature request related to a problem? Please describe.**

I want to integrate CryptoPlatz Vault, NFC Cold Wallet Card with Trust Wallet.

**Describe the solution you'd like**

The seed phrase and private keys will be stored encrypted in CryptoPlatz NFC Card. 

**Describe alternatives you've considered**

**Checklist**

- [ ] task number 1
    - [ ] subtask number 1
    - [ ] subtask number 2
- [ ] task number 2
- [ ] task number 3

**Resources**

www.cryptoplatz.ch
Resources link

**Additional context**

**Comment by Milerius** [comment]
Hello, I didn't understand your request - please more specific, closing it for now.

**Comment by cryptoplatz-vault** [comment]
Hi

I want to store the private key on NFC Card, not on smartphone.

**Comment by catenocrypt** [comment]
It would work as a HW wallet, correct?
Trust Wallet currently does not support hardware wallets, but we intend to add that in the future. Check back later. Sorry, CryptoPlatz will be probably not the first HW wallet supported.
