### ISSUE TITLE
[wasm][near] Signing results on the near chain using trust-wallet-core and near-api-js are different

### ISSUE THREAD

**Issue by icebergtsn** [trustwallet/wallet-core#2790]
**Describe the bug**

Premise: I did not find a case where the near chain can be used in wasm. I found the signature method of the near chain in android, and then converted it into ts code, and I tested it according to the case, and the result was the same as the case.
[TestNEARSigner.kt](https://github.com/trustwallet/wallet-core/blob/master/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/near/TestNEARSigner.kt)

Problem: I replaced all the parameters with my own request to initiate a signature, but the result is different from the near-api-js signature result, and I cannot submit it to near, and an error message is displayed. I don’t know whether it is a problem with my usage or a problem with the program , why can I pass the test correctly according to the test file?

**To Reproduce**

```
 const {Base58, Base64, AnySigner, HexCoding} = walletCore
        const signingInput = TW.NEAR.Proto.SigningInput.create({
            signerId: tx.signerId,
            nonce: tx.nonce,
            receiverId: tx.receiverId,
            actions: [TW.NEAR.Proto.Action.create({
                transfer: TW.NEAR.Proto.Transfer.create({
                    deposit: HexCoding.decode(tx.transferAmount)
                })
            })],

            blockHash: Base58.decodeNoCheck(tx.blockHash),
            privateKey: Base58.decodeNoCheck(privateKey).slice(0, 32)
        })
        const encodeInput = TW.NEAR.Proto.SigningInput.encode(signingInput).finish();
        const signed = AnySigner.sign(encodeInput, this.getCoinType());
        const output = TW.NEAR.Proto.SigningOutput.decode(signed);

        const trustSignedTx = Base64.encode(output.signedTransaction)

        const config = {
            networkId: 'mainnet',
            keyStore: new keyStores.BrowserLocalStorageKeyStore(),
            nodeUrl: 'https://rpc.mainnet.near.org',
            walletUrl: 'https://wallet.mainnet.near.org',
            helperUrl: 'https://helper.mainnet.near.org',
            explorerUrl: 'https://explorer.mainnet.near.org',
        };
        const near = await connect(config);
        const createAccountKeyPair = KeyPair.fromString(privateKey)
        await config.keyStore.setKey(config.networkId, tx.signerId, createAccountKeyPair);
        const createAccount = await near.account(tx.signerId);
        const actions = [nearAPI.transactions.transfer(toBN(tx.transferAmount))];
        const {accessKey, publicKey} = await createAccount.findAccessKey(tx.receiverId, actions);
        const nonce = accessKey.nonce.add(toBN(1))
        console.log(Base58.encodeNoCheck(publicKey.data))
        console.log(nonce.toNumber());

        const signedTx = await transactions.signTransaction(tx.receiverId, nonce, actions, baseDecode(tx.blockHash),
            near.connection.signer, createAccount.accountId, config.networkId)
        
        const nearApiJs = Base64.encode(signedTx[1].encode());

        console.log(trustSignedTx)
        console.log(nearApiJs)
```
tx = {
       blockHash:  "C3aoFdR35szPNHFaMTC5kiRYNzQFqHsMUt3eUp9VzVuq",
       nonce :  80041150000003,
       receiverId : "4147efecb1385c33455a57d6e5d20ebd0424400dac1027a3c39d38606aa1025a",
       signerId : "2eb37e9e89919b1b41009eefe76ff50caf1607a0917904eae3511b506e2413a3",
       transferAmount : "1000000000000000000000"
}

privateKey ='xxx'

trustSignedTx:
QAAAADJlYjM3ZTllODk5MTliMWI0MTAwOWVlZmU3NmZmNTBjYWYxNjA3YTA5MTc5MDRlYWUzNTExYjUwNmUyNDEzYTMALrN+nomRmxtBAJ7v52/1DK8WB6CReQTq41EbUG4kE6ODK1AIzEgAAEAAAAA0MTQ3ZWZlY2IxMzg1YzMzNDU1YTU3ZDZlNWQyMGViZDA0MjQ0MDBkYWMxMDI3YTNjMzlkMzg2MDZhYTEwMjVhpBnuxf2ooqY7hgW4Mouq06LGkNMHMW9xanwyfF8yZ9ABAAAAAxAAAAAAAAAAAAAAALfZUwaBMd8YjRfnuC97AVK8kyR90Ip5I2xv25oAAemlovHRdglzVdEeFQv25xbsKim3irs31bJO0n0QudXsZA4=

nearApiJs:
QAAAADJlYjM3ZTllODk5MTliMWI0MTAwOWVlZmU3NmZmNTBjYWYxNjA3YTA5MTc5MDRlYWUzNTExYjUwNmUyNDEzYTMALrN+nomRmxtBAJ7v52/1DK8WB6CReQTq41EbUG4kE6ODK1AIzEgAAEAAAAA0MTQ3ZWZlY2IxMzg1YzMzNDU1YTU3ZDZlNWQyMGViZDA0MjQ0MDBkYWMxMDI3YTNjMzlkMzg2MDZhYTEwMjVhpBnuxf2ooqY7hgW4Mouq06LGkNMHMW9xanwyfF8yZ9ABAAAAAwAAoN7Frck1NgAAAAAAAAAABmc5GDHS/trVisE5uhHaYSbggbILHr0wrFvNCFB8d9HaFVBwKbB3n5S54jE2tWn5A42wyHWBXtDzmJqjDrwsCg==

near-api-js hash : BsbbqXD6VWcEkosyRvWG2zqXixwHnHuZmiiMPwtwg1F

**Expected behavior**
trust-wallect-cor and near-api-js can generate the same signature result, and can be submitted to the near chain correctly

**Screenshots**

near-api-js sign tx
![Ykw1JoP8AX](https://user-images.githubusercontent.com/34512544/206621627-02caab44-56f7-49dc-86c0-3d2e35ebb45b.jpg)

trust-wallet-core sign tx
![LwzWxVWkEg](https://user-images.githubusercontent.com/34512544/206622230-d531dd27-5479-4c44-97a3-e4550afc5d50.jpg)

**Additional context**

**Comment by Milerius** [comment]
@miloserdow can you take a look at this one for wasm?

We recently add new tests for near in c++: https://github.com/trustwallet/wallet-core/blob/f50d771a99519e0723ac25f036c01969f909d710/tests/chains/NEAR/TWAnySignerTests.cpp#L73 and we successfully broadcast it.

**Comment by icebergtsn** [comment]
Hello, is there a solution to this problem?

**Comment by miloserdow** [comment]
> Hello, is there a solution to this problem?

Hi, I'm investigating. I only noticed this issue yesterday

**Comment by punithbm** [comment]
hi @icebergtsn , Can you try this and check once if this works ?  

```
const keypair = this.PrivateKey.createWithData(this.HexCoding.decode(privateKey));
const { Base58, Base64, AnySigner, HexCoding } = walletCore;
const signingInput = TW.NEAR.Proto.SigningInput.create({
    signerId: tx.signerId,
    nonce: tx.nonce,
    receiverId: tx.receiverId,
    actions: [
        TW.NEAR.Proto.Action.create({
            transfer: TW.NEAR.Proto.Transfer.create({
                deposit: HexCoding.decode(tx.transferAmount),
            }),
        }),
    ],

    blockHash: Base58.decodeNoCheck(tx.blockHash),
    privateKey: keypair.data(),
});
const encodeInput = TW.NEAR.Proto.SigningInput.encode(signingInput).finish();
const signed = AnySigner.sign(encodeInput, this.getCoinType());
const output = TW.NEAR.Proto.SigningOutput.decode(signed);

const trustSignedTx = Base64.encode(output.signedTransaction);
```

**Comment by icebergtsn** [comment]
> Hi @icebergtsn , Can you try this and check once if this works ?
> 
> ```
> const { Base58, Base64, AnySigner, HexCoding, PrivateKey } = walletCore;
> const keypair = PrivateKey.createWithData(HexCoding.decode(privateKey));
> const signingInput = TW.NEAR.Proto.SigningInput.create({
>     signerId: tx.signerId,
>     nonce: tx.nonce,
>     receiverId: tx.receiverId,
>     actions: [
>         TW.NEAR.Proto.Action.create({
>             transfer: TW.NEAR.Proto.Transfer.create({
>                 deposit: HexCoding.decode(tx.transferAmount),
>             }),
>         }),
>     ],
> 
>     blockHash: Base58.decodeNoCheck(tx.blockHash),
>     privateKey: keypair.data(),
> });
> const encodeInput = TW.NEAR.Proto.SigningInput.encode(signingInput).finish();
> const signed = AnySigner.sign(encodeInput, this.getCoinType());
> const output = TW.NEAR.Proto.SigningOutput.decode(signed);
> 
> const trustSignedTx = Base64.encode(output.signedTransaction);
> ```

When I executed this line of code
```
const keypair = PrivateKey.createWithData(HexCoding.decode(privateKey));
```
the following error occurred. 
![image](https://user-images.githubusercontent.com/34512544/210038765-7fa117fb-4a14-457f-8514-e4795c205c6f.png)

When using the slice() function to intercept the private key can make the code work normally. But the signature result is still incorrect.

**Comment by punithbm** [comment]
@icebergtsn this might be due to private key format - can you check you're sending the hex private key ? 

Also, I am working on the demo example here - https://github.com/punithbm/wallet-core-vitejs-demo 

But here as well the Signing results of transaction hash is coming different. 

@miloserdow  can you check this repo once   https://github.com/punithbm/wallet-core-vitejs-demo 
I will also further check the issue

**Comment by icebergtsn** [comment]
> @icebergtsn this might be due to private key format - can you check you're sending the hex private key ?
> 
> Also, I am working on the demo example [here](https://github.com/punithbm/wallet-core-vitejs-demo)
> 
> But here as well the Signing results of transaction hash is coming different.
> 
> @miloserdow can you check this repo once https://github.com/punithbm/wallet-core-vitejs-demo I will also further check the issue

Thanks for your answer

These two ways of using the private key are the same, so the private key format is not the reason that affects the results, I used the private key in your demo.
```
const {Base58, PrivateKey, HexCoding} = supportCenter.walletCore
const privateKeyBytes = Base58.decodeNoCheck('5yutZ7z1NUFmUbqBdFuAgWbqdXzpY1wZB7cnau4s9L4gzSFhMKb68XkJiY5yEVJSge3D3ib1bZGyrwnTj17bVvGg').slice(0, 32)
const privateKey = PrivateKey.createWithData(privateKeyBytes);
const privateKey2 = PrivateKey.createWithData(HexCoding.decode('f92589ed1e5568cc10838611996e08c0b5b6922de5024050e3311164df496c1d'));
console.log(privateKey.data())
console.log(privateKey2.data())
```
The result
![image](https://user-images.githubusercontent.com/34512544/210306331-de25bd8f-093b-43ce-9d91-8a0b2e78f4c7.png)

**Comment by punithbm** [comment]
@icebergtsn  its due to the amount format you're sending, Can you check the code here [ https://github.com/punithbm/wallet-core-vitejs-demo](https://github.com/punithbm/wallet-core-vitejs-demo)

It is generating same hash from wallet core and near api js

<img width="1434" alt="Screenshot 2023-01-05 at 1 06 00 PM" src="https://user-images.githubusercontent.com/13044958/210726535-221a9be3-b3c3-49f0-a97e-c49f9d3d2677.png">

Code 👇 
```export async function signNearRaw(tx: TTranx, prvKey: string) {
  const { keyStores, KeyPair, connect, transactions } = nearAPI;
  const config = {
    networkId: 'mainnet',
    keyStore: new keyStores.BrowserLocalStorageKeyStore(),
    nodeUrl: 'https://rpc.mainnet.near.org',
    walletUrl: 'https://wallet.mainnet.near.org',
    helperUrl: 'https://helper.mainnet.near.org',
    explorerUrl: 'https://explorer.mainnet.near.org',
  };
  const near = await connect(config);
  const createAccountKeyPair = KeyPair.fromString(prvKey);
  await config.keyStore.setKey(config.networkId, tx.fromAddress, createAccountKeyPair);
  const createAccount = await near.account(tx.fromAddress);
  const actions = [nearAPI.transactions.transfer(toBN(tx.amountHex ?? ""))];
  const { accessKey, publicKey } = await createAccount.findAccessKey(tx.fromAddress ?? '', actions);
  const nonce = accessKey.nonce.add(toBN(1));
  const signedTx = await transactions.signTransaction(tx.toAddress ?? '', nonce, actions, bs58.decode(tx.blockHash ?? ''), near.connection.signer, createAccount.accountId, config.networkId);
  const nearApiJs = Buffer.from(signedTx[1].encode()).toString('base64');
  return nearApiJs;
}

**Comment by icebergtsn** [comment]
> @icebergtsn 我认为这是由于您发送的金额格式所致，您可以在此处查看代码https://github.com/punithbm/wallet-core-vitejs-demo
> 
> 它从钱包核心和附近的 api js 生成相同的哈希
> 
> <img alt="截图 2023-01-05 1 06 00 PM" width="1434" src="https://user-images.githubusercontent.com/13044958/210726535-221a9be3-b3c3-49f0-a97e-c49f9d3d2677.png">
> 
> 代码👇
> 
> ```
>   const { keyStores, KeyPair, connect, transactions } = nearAPI;
>   const config = {
>     networkId: 'mainnet',
>     keyStore: new keyStores.BrowserLocalStorageKeyStore(),
>     nodeUrl: 'https://rpc.mainnet.near.org',
>     walletUrl: 'https://wallet.mainnet.near.org',
>     helperUrl: 'https://helper.mainnet.near.org',
>     explorerUrl: 'https://explorer.mainnet.near.org',
>   };
>   const near = await connect(config);
>   const createAccountKeyPair = KeyPair.fromString(prvKey);
>   await config.keyStore.setKey(config.networkId, tx.fromAddress, createAccountKeyPair);
>   const createAccount = await near.account(tx.fromAddress);
>   const actions = [nearAPI.transactions.transfer(toBN(tx.amountHex ?? ""))];
>   const { accessKey, publicKey } = await createAccount.findAccessKey(tx.fromAddress ?? '', actions);
>   const nonce = accessKey.nonce.add(toBN(1));
>   const signedTx = await transactions.signTransaction(tx.toAddress ?? '', nonce, actions, bs58.decode(tx.blockHash ?? ''), near.connection.signer, createAccount.accountId, config.networkId);
>   const nearApiJs = Buffer.from(signedTx[1].encode()).toString('base64');
>   return nearApiJs;
> }
> ```

I tested your demo and it works correctly.

**Comment by Milerius** [comment]
> I am very grateful to @punithbm for helping me
> 
> But I have some confusion and hope to get an answer.
> 
> First, does the action amount of the near chain need to be fixed at 32 bits? Why does the buffer need to be reversed? Second, the action amount of the near chain and the [eth chain](https://github.com/trustwallet/wallet-core/blob/master/wasm/tests/Blockchain/Ethereum.test.ts) are not used in the same way. Is there a plan to fix this?

Hello @icebergtsn - sorry for the late reply - as mentioned in my first comment: https://github.com/trustwallet/wallet-core/issues/2790#issuecomment-1343901859 - the code snippet mention the endianness that you need to use, the reason for the buffer to be "reversed" is most likely due to the [endianness](https://en.wikipedia.org/wiki/Endianness)

You should find more information [here](https://docs.near.org/concepts/basics/transactions/overview)

Please open a discussion instead of an issue if u would like to engage another discussion on the topic!

**Comment by ZEFIROFF** [comment]
> @icebergtsn Я думаю, это из-за формата суммы, которую вы отправляете, можете ли вы проверить код здесь [ https: //github.com/punithbm/wallet-core-vitejs-demo](https://github.com/punithbm/wallet-core-vitejs-demo)
> 
> Он генерирует один и тот же хэш из ядра кошелька и near api js
> 
> <img alt="Скриншот 2023-01-05 в 13:06" width="1434" src="https://user-images.githubusercontent.com/13044958/210726535-221a9be3-b3c3-49f0-a97e-c49f9d3d2677.png">
> 
> Код 👇
> 
> ```
>   const { keyStores, KeyPair, connect, transactions } = nearAPI;
>   const config = {
>     networkId: 'mainnet',
>     keyStore: new keyStores.BrowserLocalStorageKeyStore(),
>     nodeUrl: 'https://rpc.mainnet.near.org',
>     walletUrl: 'https://wallet.mainnet.near.org',
>     helperUrl: 'https://helper.mainnet.near.org',
>     explorerUrl: 'https://explorer.mainnet.near.org',
>   };
>   const near = await connect(config);
>   const createAccountKeyPair = KeyPair.fromString(prvKey);
>   await config.keyStore.setKey(config.networkId, tx.fromAddress, createAccountKeyPair);
>   const createAccount = await near.account(tx.fromAddress);
>   const actions = [nearAPI.transactions.transfer(toBN(tx.amountHex ?? ""))];
>   const { accessKey, publicKey } = await createAccount.findAccessKey(tx.fromAddress ?? '', actions);
>   const nonce = accessKey.nonce.add(toBN(1));
>   const signedTx = await transactions.signTransaction(tx.toAddress ?? '', nonce, actions, bs58.decode(tx.blockHash ?? ''), near.connection.signer, createAccount.accountId, config.networkId);
>   const nearApiJs = Buffer.from(signedTx[1].encode()).toString('base64');
>   return nearApiJs;
> }
> ```

I am using your application and the transaction is sent from near-api-js, but it is not sent from trust-wallet-js and I get the same error in kotlin: 

```
"error": {
        "name": "HANDLER_ERROR",
        "cause": {
            "info": {},
            "name": "INVALID_TRANSACTION"
        },
        "code": -32000,
        "message": "Server error",
        "data": {
            "TxExecutionError": {
                "InvalidTxError": {
                    "InvalidNonce": {
                        "ak_nonce": 126619724000003,
                        "tx_nonce": 126619724000003
                    }
                }
            }
        }
    }
```
