### ISSUE TITLE
BECH32 HRP verification is missing

### ISSUE THREAD

**Issue by CryptoManiac** [trustwallet/wallet-core#2804]
Hi guys. I believe there is a bug in the Script::lockScriptForAddress method.

https://github.com/trustwallet/wallet-core/blob/501f683b2b8301bc027b99a1ceaed1e104f70a2f/src/Bitcoin/Script.cpp#L311

It does perform the legacy address prefixes verification correctly, but the same can't be said about BECH32 addresses. This may potentially cause loss of funds.

Perhaps something like this would be more correct:

`   } else if (SegwitAddress::isValid(string, stringForHRP(TW::hrp(coin)))) {`

**Comment by catenocrypt** [comment]
We will investigate.

The `SegwitAddress::isValid` only checks that the address is of the Bech32 format (with valid checksum), and does not check for the hrp prefix.
All valid Segwit addresses will be handled by this branch. But can it happen that a non-segwit address is also taken by this branch? No, becasue Segwit is the only Bech32 address among the Bitcoin clone addresses.
BTW this branch handles Bitcoin and Litecoin segwit addresses, so prefixes 'bc' and 'ltc' (and can also handle 'tb' testnet bitcoin addresses).

Can you think of a valid address (Bitcoin or a clone) that would be incorrectly handled in this branch?

So I don't think there is a bug here.
This lockscript logic could be made more robust (for future changes) if it also took into account the coinId.

**Comment by CryptoManiac** [comment]
Yep indeed. I stumbled on this issue while working with private chain as a contractor. Library accepted bitcoin and litecoin bech32 addresses and allowed user to create transaction. Normally this wouldn’t be much of issue, as access to private key would allow user to spend the resulting output. Unfortunately, the coin in question is using ED25519 signature scheme, meaning that all funds sent to BTC or LTC address are irrevocably lost.

**Comment by Usernamethoma** [comment]
> Hi guys. I believe there is a bug in the Script::lockScriptForAddress method.
> 
> https://github.com/trustwallet/wallet-core/blob/501f683b2b8301bc027b99a1ceaed1e104f70a2f/src/Bitcoin/Script.cpp#L311
> 
> It does perform the legacy address prefixes verification correctly, but the same can't be said about BECH32 addresses. This may potentially cause loss of funds.
> 
> Perhaps something like this would be more correct:
> 
> `   } else if (SegwitAddress::isValid(string, stringForHRP(TW::hrp(coin)))) {`
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
