### ISSUE TITLE
npm build failed for @trustwallet/core package

### ISSUE THREAD

**Issue by idan-krayon** [trustwallet/wallet-core#2834]
**Describe the bug**
trying to build the project with npm run build and this happen:
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/105673674/209805893-4bc2465d-cc7e-4543-bfd4-8f0946e06368.png">

**To Reproduce**
npm run build

**Expected behavior**
successful build

**Additional context**
mac os, tried with node version 16 LTS and switched to 18 LTS

**Comment by punithbm** [comment]
Hi @idan-krayon Are you trying to build this with any frameworks like vite.js or next ?

**Comment by punithbm** [comment]
You can try [here](https://github.com/punithbm/wallet-core-vitejs-demo), Seems to be working fine

**Comment by Milerius** [comment]
Closing, please  @idan-krayon re-open if u still have the problem.

**Comment by idan-krayon** [comment]
To whom it may be helpful,
the only thing that worked for me is to put the "skipLibCheck": true, in the tsconfig file

thanks for the help guys!
