### ISSUE TITLE
TRON SIGERROR

### ISSUE THREAD

**Issue by levochkaa** [trustwallet/wallet-core#2851]
**Describe the bug**
I get this SIGERROR, when broadcasting transaction through https://api.shasta.trongrid.io/wallet/broadcasttransaction
```
{
    code = SIGERROR;
    message = 56616c6964617465207369676e6174757265206572726f723a2064383837613632396564643831356634353833633135653334303330363738643136393835333733343831376539623637386137636533333761303438653631373437316136333236316238306165336336653635393564356137383065396333663533366430366561633065373933393261373639353635366531303432323030206973207369676e65642062792054554b65424d434b464241625056374d397a695250485a574e6e4758775174566d6f20627574206974206973206e6f7420636f6e7461696e6564206f66207065726d697373696f6e2e;
    txid = 1eb221344f02bfa8cbc7a124386454e01d079ede4adf0040e5319f70b3972c37;
}
```

**To Reproduce**
Get TRON block func (result will be used in next part of code):
```swift
func getTronBlock(address: String, completion: @escaping (_ result: TronBlockHeaderModel) -> Void) {
    print("Getting tron block")
    // https://api.trongrid.io/wallet/getnowblock
    // https://api.nileex.io/wallet/getnowblock
    let url = URL(string: "https://api.trongrid.io/wallet/getnowblock")!
    var request = URLRequest(url: url)
    request.httpMethod = "POST"
    
    URLSession.shared.dataTask(with: request) { data, response, error in
        guard let data = data, error == nil else {
            print(error?.localizedDescription ?? "No data")
            return
        }
        
        do {
            let tronBlockHeaderModel = try JSONDecoder().decode(TronBlockHeaderModel.self, from: data)
            print("TRON BLOCK", tronBlockHeaderModel)
            completion(tronBlockHeaderModel)
        } catch {
            print("Error decoding TronBlockHeaderModel")
        }
    }.resume()
}
```

The code, where the error appears (in line `print(json)`:
```swift
func replaced(string: String) -> String {
    string.replacingOccurrences(of: "\\", with: "")
}

let amount = "1"
let wallet = HDWallet(mnemonic: "fromWallet mnemonic", passphrase: "")!
let privateKey = wallet.getKeyForCoin(coin: .tron)
let fromWallet = wallet.getAddressForCoin(coin: .tron) // TUKeBMCKFBAbPV7M9ziRPHZWNnGXwQtVmo
let fromWalletDecoded = Base58.decode(string: fromWallet)!.hexString
let toWallet = "TJieFff3UBzV1W9tkrH3WPMs7Hg7H82Qe1"
let toWalletDecoded = Base58.decode(string: toWallet)!.hexString

let input = TronSigningInput.with {
    $0.transaction = TronTransaction.with {
        $0.transfer = .with {
            $0.ownerAddress = fromWalletDecoded
            $0.toAddress = toWalletDecoded
            $0.amount = Int64(amount)! * 1_000_000
        }
        $0.expiration = Int64(Date().timeIntervalSince1970 + (10 * 60 * 1000))
        $0.timestamp = Int64(Date().timeIntervalSince1970)
        $0.blockHeader = TronBlockHeader.with {
            $0.timestamp = Int64(result.block_header.raw_data.timestamp)
            $0.number = Int64(result.block_header.raw_data.number)
            $0.version = Int32(result.block_header.raw_data.version)
            $0.txTrieRoot = Data(hexString: result.block_header.raw_data.txTrieRoot)!
            $0.parentHash = Data(hexString: result.block_header.raw_data.parentHash)!
            $0.witnessAddress = Data(hexString: result.block_header.raw_data.witness_address)!
        }
    }
    $0.privateKey = privateKey.data
}
let jsonDecoder = JSONDecoder()
let output: TronSigningOutput = AnySigner.sign(input: input, coin: .tron)
let jsonString = try output.jsonString()
let json = try jsonDecoder.decode(TronSigningOutputJson.self, from: Data(jsonString.utf8))
let replacedRealJson = self.replaced(string: json.json)
let sendTronParameters = try jsonDecoder.decode(SendTronParameters.self, from: Data(replacedRealJson.utf8))
let rawData = try JSONEncoder().encode(sendTronParameters.raw_data)
let rawString = String(data: rawData, encoding: .utf8)!
let parameters = [
    "txID": sendTronParameters.txID,
    "raw_data": rawString,
    "signature": sendTronParameters.signature[0]
] as [String: Any]
let headers = [
	"accept": "application/json",
	"content-type": "application/json"
]
var postData = try JSONSerialization.data(withJSONObject: parameters, options: [])
var request = URLRequest(url: URL(string: "https://api.shasta.trongrid.io/wallet/broadcasttransaction")!)
request.httpMethod = "POST"
request.allHTTPHeaderFields = headers
request.httpBody = postData

URLSession.shared.dataTask(with: request, completionHandler: { (data, response, error) -> Void in
    guard let data, error == nil else {
        print("Error getting data about transaction")
        return
    }
    
    do {
        let json = try JSONSerialization.jsonObject(with: data)
        print(json) // SIGERROR here
    } catch {
        print("Error serializing transaction json data")
    }
}).resume()
```

Models, used to decode/encode JSON:
```swift
struct SendTronParameters: Codable {
    var raw_data: SendTronRaw
    var signature: [String]
    var txID: String
}

struct SendTronRaw: Codable {
    var contract: [SendTronRawContract]
    var expiration: Int
    var ref_block_bytes: String
    var ref_block_hash: String
    var timestamp: Int
}

struct SendTronRawContract: Codable {
    var parameter: SendTronRawContractParameter
    var type: String
}

struct SendTronRawContractParameter: Codable {
    var value: SendTronRawContractParameterValue
    var type_url: String
}

struct SendTronRawContractParameterValue: Codable {
    var amount: Int
    var owner_address: String
    var to_address: String
}

struct TronBlockHeaderModel: Codable {
    var block_header: BlockHeaderRawModel
}

struct BlockHeaderRawModel: Codable {
    var raw_data: BlockHeaderDetailsModel
}

struct BlockHeaderDetailsModel: Codable {
    var number: Int
    var txTrieRoot: String
    var witness_address: String
    var parentHash: String
    var version: Int
    var timestamp: Int
}
```

**Expected behavior**
Transaction to be done. `toWallet` gets its TRX.

**Screenshots**
No screenshots to be shown

**Additional context**
I am making a Crypto-wallet app.
Swift 5.7, iOS 15+, Wallet-Core 3.1.7

**Comment by levochkaa** [comment]
Trying to getaccount https://developers.tron.network/reference/account-getaccount
with address `41c94f99b33185c922ca65f129d7c632293cfc2474`
which is actually `TUKeBMCKFBAbPV7M9ziRPHZWNnGXwQtVmo`
gives `{}` empty response

**Comment by levochkaa** [comment]
Solved it.
1. Made an API Key on TronGrid. (put it in headers like `"TRON-PRO-API-KEY": "api_key"`)
2. `.transaction.timestamp` must be the **BLOCK's** `.timestamp` 
3. `.transaction.expiration` = BLOCK's timestamp + (10 * 60 * 60 * 1000)
4. `ownerAddress` and `toAddress` are in **Base58**, not HEX
5. Simply get data from output json of transaction: `output.json.data(using: .utf8)!`
6. Serialize data to json with option `.allowFragments`
7. Then use this json to get httpBody `JSONSerialization.data(withJSONObject:)`
8. Decode the result!

While doing these steps, at some point, I was stuck with another Error: TIME_EXPIRATION_ERROR, but solved it (check p. 2), also was getting TAPOS_ERROR for a long time, something from the code and list above might heko 

Can't really drop the code, because I already rewrote it to be beautiful and clear (not like in the code blocks in the issue, that just had to show the problem)

I hope this steps (and code in the issue) will help someone stuck with these errors!
Also, check https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Blockchains/TronTests.swift, might help, too.

**Comment by thomashooo** [comment]
can you share you swift method, i got same error. how to use the result of [createtransaction](https://api.shasta.trongrid.io/wallet/createtransaction)
when i use your [broadcasttransaction](https://api.shasta.trongrid.io/wallet/broadcasttransaction),
same erorr : SIGERROR

**Comment by thomashooo** [comment]
> can you share you swift method, i got same error. how to use the result of [createtransaction](https://api.shasta.trongrid.io/wallet/createtransaction)
> when i use your [broadcasttransaction](https://api.shasta.trongrid.io/wallet/broadcasttransaction),
> same erorr : SIGERROR

got it.
thx for your template code. but at last my address is not Base58, maybe api changed?
`
   func Sign(header: TronBlockHeaderModel) -> String?  {
        
        guard let amount = BigInt(order.amount) else {return nil}
        
        guard let wallet = YourCurrentWallet else {return nil}
        
        let fromWallet = "TBcBKeXL37LsjCB2r9ggsQ26JfRpbnkmjG" //must activate, u can nile chain for test
        let toWallet = "TJieFff3UBzV1W9tkrH3WPMs7Hg7H82Qe1"
        let pk = wallet.getKeyForCoin(coin: .tron)
        
        let contract = TronTransferContract.with {
            $0.ownerAddress = fromWallet
            $0.toAddress = toWallet
            $0.amount = Int64(BigInt(amount) * BigInt(1_000_000))
        }
        let nowTimestamp = Int64(header.block_header.raw_data.timestamp)
        let input = TronSigningInput.with {
            $0.transaction = TronTransaction.with {
                $0.contractOneof = .transfer(contract)
                $0.timestamp = nowTimestamp
                $0.blockHeader = TronBlockHeader.with {
                    $0.timestamp = nowTimestamp
                    $0.number = Int64(header.block_header.raw_data.number)
                    $0.version = Int32(header.block_header.raw_data.version)
                    $0.txTrieRoot = Data(hexString: header.block_header.raw_data.txTrieRoot)!
                    $0.parentHash = Data(hexString: header.block_header.raw_data.parentHash)!
                    $0.witnessAddress = Data(hexString: header.block_header.raw_data.witness_address)!
                }
                $0.expiration = nowTimestamp + 10 * 60 * 60 * 1000
            }
            $0.privateKey = pk.data
        }

        let output: TronSigningOutput = AnySigner.sign(input: input, coin: .tron)
        print(output.json) //this json directly use for wallet/broadcasttransaction
        return self.SignHex(contract: contract, input: input, output: output) //make raw_data_hex
    }
`
