### ISSUE TITLE
[ThorSwap/ETH] Change to using depositWithExpiry

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#2893]
**Is your feature request related to a problem? Please describe.**
When switching from ERC-20 token (on Ethereum), the new `depositWithExpiry` function should be used instead of `deposit`.

"Announcement: update to the ETH router contract that inbound ETH swaps are executed against. We will deprecate the `deposit` func in the next version of the router, in favor of the `depositWithExpiry` function. This protects users from their inbound tx getting hung up and potentially getting dropped if it ends up hitting an old vault after taking a long time to confirm:

```
Reminder - unprotected deposit() will get deprecated in next Router Update 

All interface devs should be using router.depositWithExpiry(Params, +15minsInUNIXSeconds)

This reverts the tx if it takes more than 15mins to process. The unprotected deposit function will be set to private on the next router upgrade. 
```

**Comment by catenocrypt** [comment]
Relevant call: https://github.com/trustwallet/wallet-core/blob/master/src/THORChain/Swap.cpp#L260

**Comment by Milerius** [comment]
https://etherscan.io/address/0xD37BbE5744D730a1d98d8DC97c42F0Ca46aD7146#code  line 69

**Comment by Helpcentera** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Grouphelpcenter** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9
