### ISSUE TITLE
[browser] Can't resolve 'fs/promises'

### ISSUE THREAD

**Issue by earthgohan** [trustwallet/wallet-core#2896]
I am trying to import wallet `@trustwallet/wallet-core": "^3.1.10"` in browser to generate wallets using `webpack : 5.72.0.`

**To Reproduce**
Create a simple index.html and new index.ts with `@trustwallet/wallet-core`
configure webpack.config.js with wasm-loader and with plugins as follows and fallback as per https://webpack.js.org/configuration/resolve/#resolvefallback and `fs: require.resolve("browserify-fs"),`

**Expected behavior**

```
//index.js
 const walletIdsKey = "all-wallet-ids";
  const storage = new KeyStore.ExtensionStorage(
    walletIdsKey,
    new ChromeStorageMock()
  );

  const walletCore = await initWasm();

  const keystore = new KeyStore.Default(walletCore, storage);
   var wallet = await keystore.import(
    TEST_MNE_1,
    "Coolw",
    "12345678",
    [CoinType.bitcoin, CoinType.solana, CoinType.cardano],
    StoredKeyEncryption.aes128Ctr
  );
  ```

when run `npx webpack` the build should compile and generate new index.html in dist folder. But I am getting the following error

```
ERROR in ./node_modules/@trustwallet/wallet-core/dist/src/keystore/fs-storage.js 9:9-31
Module not found: Error: Can't resolve 'fs/promises' in '/Users/web/node_modules/@trustwallet/wallet-core/dist/src/keystore'
```

**Additional context**
Fix could be to test 
https://medium.com/aspecto/make-your-npm-package-work-on-both-node-js-and-browser-58bff1a18f55
Issue is coming from KeyStore
Need to separate browser and nodeJs builds

**Comment by Helpcentera** [comment]
@earthgohan We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Grouphelpcenter** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Milerius** [comment]
Hello @earthgohan thanks for openning the issue, one current workaround is to use `node-polyfill-webpack-plugin`

```js
const path = require("path");
const NodePolyfillPlugin = require("node-polyfill-webpack-plugin");

module.exports = {
  entry: "./src/index.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  plugins: [
    new NodePolyfillPlugin({
      excludeAliases: ["console"],
    }),
  ],
  resolve: {
    fallback: {
      fs: false,
    },
  },
};
```

Let me know if u have any other questions

**Comment by earthgohan** [comment]
@Milerius Thanks for the fix. Can you also suggest a way to generate esm file into one file instead of two files, in the lines of 

`emcc ... -o output.{html,js} -sWASM={0,1} -sSINGLE_FILE`

using EMSDK ?

**Comment by Milerius** [comment]
> @Milerius Thanks for the fix. Can you also suggest a way to generate esm file into one file instead of two files, in the lines of
> 
> `emcc ... -o output.{html,js} -sWASM={0,1} -sSINGLE_FILE`
> 
> using EMSDK ?

I think SINGLE_FILE is the option that allow that (from the faq)

```
emcc ... -o output.{html,js} -sWASM={0,1} -sSINGLE_FILE merges JavaScript and WebAssembly code in the single output file output.{html,js} (in base64) to produce only one file for deployment. (If paired with --preload-file, the preloaded .data file still exists as a separate file)
```

**Comment by earthgohan** [comment]
Yep! can you suggest me, how to update https://github.com/trustwallet/wallet-core/blob/master/tools/wasm-build with `-sWASM={0,1} -sSINGLE_FILE` option

Thanks a lot in advance!

**Comment by prhasn** [comment]
The compiled [typescript file](https://github.com/trustwallet/wallet-core/blob/master/wasm/src/keystore/fs-storage.ts) transforms `import * as fs from "fs/promises";` to `var fs = require("fs/promises");` in the javascript version included in npm. This should be compiled to `var fs = require("fs").promises;` instead.

**Comment by weixuefeng** [comment]
can you use wallet-core on browser ? need i change some code ?

**Comment by weixuefeng** [comment]
@prhasn i had comment `fs` lib, but i also got 'fs' in 'wallet-core.js', i guess `wallet-core.js` will find `wallet-core.wasm` file, have you resolved the problem?

**Comment by prhasn** [comment]
> @prhasn i had comment `fs` lib, but i also got 'fs' in 'wallet-core.js', i guess `wallet-core.js` will find `wallet-core.wasm` file, have you resolved the problem?

What do you mean? Please elaborate.

**Comment by weixuefeng** [comment]
can you use wallet-core on browser? @prhasn 
maybe you had resolve 'can not resolve fs/promises'?

**Comment by prhasn** [comment]
> can you use wallet-core on browser? @prhasn 
> maybe you had resolve 'can not resolve fs/promises'?

Please check my comment where I mentioned the solution.
