### ISSUE TITLE
Walletconnect (iOS) redirects to Application error (heroku) at link.trustwallet.com

### ISSUE THREAD

**Issue by actuallymentor** [trustwallet/wallet-core#2900]
**Describe the bug**
When attempting to connect Trust on iOS through wallet connect on the same device (so not through QR) the app redirects to a broken heroku app.

**To Reproduce**

1. Open app
2. Navigate to a page to connect to ([example](https://checkout.poap.xyz/#/sale/e0190b1c-d221-4c7a-a8ef-e780dca47507))
3. Press connect and choose Wallet connect
4. Select Trust
5. See error page

**Expected behavior**

The wallet to connect.

**Screenshots**

![IMG_0040](https://user-images.githubusercontent.com/9071382/215721917-43354966-df8a-4442-ada0-33ba73b8dfc1.PNG)

![IMG_0039](https://user-images.githubusercontent.com/9071382/215721923-901cbc33-38bb-4216-9ab2-0b40190ead4f.PNG)

**Comment by Helpcentera** [comment]
> **Describe the bug**
> When attempting to connect Trust on iOS through wallet connect on the same device (so not through QR) the app redirects to a broken heroku app.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Open app
> 2. Navigate to a page to connect to ([example](https://checkout.poap.xyz/#/sale/e0190b1c-d221-4c7a-a8ef-e780dca47507))
> 3. Press connect and choose Wallet connect
> 4. Select Trust
> 5. See error page
> 
> **Expected behavior**
> 
> The wallet to connect.
> 
> **Screenshots**
> 
> ![IMG_0040](https://user-images.githubusercontent.com/9071382/215721917-43354966-df8a-4442-ada0-33ba73b8dfc1.PNG)
> 
> ![IMG_0039](https://user-images.githubusercontent.com/9071382/215721923-901cbc33-38bb-4216-9ab2-0b40190ead4f.PNG)
> 
> 
> 

We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by actuallymentor** [comment]
Can confirm it was fixes. Thanks for the fast response!
