### ISSUE TITLE
Rust Sample Does not Build

### ISSUE THREAD

**Issue by Abvit-eve** [trustwallet/wallet-core#2907]
**Describe the bug**
Rust sample was attempted to be built from [sample repo](https://github.com/trustwallet/wallet-core/tree/master/samples/rust). Seems to be issue building the compiled library from the C/C++ .

Fully admit possible user error but following instructions provided. 

**To Reproduce**
1. Add `    env::set_var("RUST_BACKTRACE", "full");` to build.rs file. 
2. `cargo build`

**Expected behavior**
Expected build does not occur. 

`Backtrace`
 Caused by:
      0: using protoc parser
      1: failed to spawn command "../../build/local/bin/protoc" "-I../../src/proto" "--descriptor_set_out=/tmp/protobuf-parseSlnNXp/descriptor.pbbin" "--include_imports" "../../src/proto/Common.proto" "../../src/proto/Bitcoin.proto" "../../src/proto/Ethereum.proto"
      2: No such file or directory (os error 2)', src/build.rs:39:10
  stack backtrace:
     0:     0x55935d563ca0 - std::backtrace_rs::backtrace::libunwind::trace::h1d00f3fcf4cb5ac4
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x55935d563ca0 - std::backtrace_rs::backtrace::trace_unsynchronized::h920a6ff332484ee2
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55935d563ca0 - std::sys_common::backtrace::_print_fmt::hd7323920c925af6d
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x55935d563ca0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3155a8c966b4beb5
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x55935d588b9e - core::fmt::write::h062c617411b691df
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/fmt/mod.rs:1209:17
     5:     0x55935d560fc5 - std::io::Write::write_fmt::hb61fdf1275c61e1c
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/io/mod.rs:1682:15
     6:     0x55935d563a65 - std::sys_common::backtrace::_print::hd1b4d9664ab500e0
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:47:5
     7:     0x55935d563a65 - std::sys_common::backtrace::print::hca896ae22beb06cb
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:34:9
     8:     0x55935d56516f - std::panicking::default_hook::{{closure}}::h0b5eeed5cf36ab5f
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:267:22
     9:     0x55935d564eaa - std::panicking::default_hook::h8932b573145a321b
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:286:9
    10:     0x55935d565868 - std::panicking::rust_panic_with_hook::h4b1447a24e3e94f8
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:688:13
    11:     0x55935d565607 - std::panicking::begin_panic_handler::{{closure}}::h8701da9995a3820c
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:579:13
    12:     0x55935d56414c - std::sys_common::backtrace::__rust_end_short_backtrace::hb696c5ed02a01598
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:137:18
    13:     0x55935d565322 - rust_begin_unwind
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
    14:     0x55935cf94c83 - core::panicking::panic_fmt::h8aa706a976963c88
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
    15:     0x55935cf94f43 - core::result::unwrap_failed::h065c02f906ca4578
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
    16:     0x55935cf972cb - core::result::Result<T,E>::expect::h6587d3800c2c730a
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1070:23
    17:     0x55935cf955a3 - build_script_build::main::he39b3118a2d0c67c
                                 at /home/adam/PycharmProjects/wallet-core/samples/rust/src/build.rs:28:5
    18:     0x55935cf9622b - core::ops::function::FnOnce::call_once::hbdb957379bb7f206
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
    19:     0x55935cf95cbe - std::sys_common::backtrace::__rust_begin_short_backtrace::h4a1969420a6a79b1
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/sys_common/backtrace.rs:121:18
    20:     0x55935cf96161 - std::rt::lang_start::{{closure}}::hbc40c297e9d47317
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:166:18
    21:     0x55935d55cebb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h8cbb48ae40ddb046
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:286:13
    22:     0x55935d55cebb - std::panicking::try::do_call::h92db802eb38b49b7
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
    23:     0x55935d55cebb - std::panicking::try::ha8949d2082cf3644
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
    24:     0x55935d55cebb - std::panic::catch_unwind::h5e34c1f8a5992ed9
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
    25:     0x55935d55cebb - std::rt::lang_start_internal::{{closure}}::hea52a0bb3f8ff16a
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:148:48
    26:     0x55935d55cebb - std::panicking::try::do_call::h5bc358faf3d68a8b
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:483:40
    27:     0x55935d55cebb - std::panicking::try::h675304212928379d
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:447:19
    28:     0x55935d55cebb - std::panic::catch_unwind::h7ce3ad349ed5c844
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panic.rs:137:14
    29:     0x55935d55cebb - std::rt::lang_start_internal::hcd7e45acd25ab5ab
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:148:20
    30:     0x55935cf9613a - std::rt::lang_start::hf18b75a6af90fe94
                                 at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/rt.rs:165:17
    31:     0x55935cf959be - main
    32:     0x7f7f3ffcf510 - __libc_start_call_main
    33:     0x7f7f3ffcf5c9 - __libc_start_main@GLIBC_2.2.5
    34:     0x55935cf95125 - _start
    35:                0x0 - <unknown>

**Comment by Milerius** [comment]
Hello @Abvit-eve you need to follow the instructions from https://developer.trustwallet.com/wallet-core/developing-the-library/building - it's seems that you do not have protoc installed as the normal build instructions would do. Closing for now, feel free to ask more questions in discussions if u have any.
