### ISSUE TITLE
`hexString` extension conflict

### ISSUE THREAD

**Issue by megakoko** [trustwallet/wallet-core#2916]
Hello TrustWallet team! 

First of all thank you for creating such a great and powerful library and making it open source, we really appreciate it! It's a constant source of inspiration for us!

We're developing an application that is going to use WalletCore along with some other frameworks and we've encountered a conflict with extensions. We're using Swift, mind you.

It so happened that both WalletCore and the other framework use the same names in `Data` extensions, namely `Data(hexString:)` and `Data.hexString` and are public in both frameworks. Resulting in Swift not being able to decide which constructor / property to use when we use them.

So I wanted to ask if you would consider making these two extensions internal? I know your tests rely on them being public but that can be solved by using `@testable import WalletCore`. 

Regards

Andy

**Comment by Milerius** [comment]
Those 2 extension are not intended to be internal since they are used by our end users application, however we can consider a rename or figure something else to avoid conflict, would be nice if you show the details of the conflict.

Cc @hewigovens

**Comment by megakoko** [comment]
I don't know if renaming it will help, there's only so many options for this kind of stuff. We used to have these things named simply `hex` but then encountered a framework with the same name and renamed them on our end to `hexString` and now we have a conflict again...

Perhaps you could make them internal and copy the implementation to the app itself. Yes, it's duplicate code but the implementation of hex conversions doesn't change often anyway.

To give you a bit more context — it's really simple, the other framework we're using has more-or-less the same implementation as you guys with the same names — https://github.com/tangem/tangem-sdk-ios/blob/develop/TangemSdk/TangemSdk/Common/Extensions/Data%2B.swift

The only difference is the return value of our Data(hexString) is optional which allows us to distinguish between the different versions of the constructor by specifying the exact type — `let data: Data = Data(hexString: "")`. `var hexString` is the same so that's not an option.

The framework I'm talking about IS under our control and I do feel a bit selfish asking you to change yours but I thought maybe with you having more users the impact would be greater if you did it on your end. Perhaps there are other users that will stumble upon these kind of conflicts.

For now we've just forked your repository and made the changes ourself (made the extensions internal and added @testable).

**Comment by CharlesBlaqk** [comment]
@megakoko We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by megakoko** [comment]
That's cool, I understand that
