### ISSUE TITLE
Compile Error on fatal error: implicit instantiation of undefined template 'std::numeric_limits<signed char>'

### ISSUE THREAD

**Issue by mohammad-nazari** [trustwallet/wallet-core#2918]
Hi there,

I ran bootstrap.sh  script and got this Erro:
`wallet-core/src/Everscale/CommonTON/RawAddress.cpp:43:49: fatal error: implicit instantiation of undefined template 'std::numeric_limits<signed char>'`

Kubuntu 22.04
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
CMake version 3.22.1
Ninja

**Comment by deletexl** [comment]
Same
`/home/dev/Downloads/wallet-core-master/src/Everscale/CommonTON/RawAddress.cpp:43:49: fatal error: implicit instantiation of undefined template 'std::numeric_limits<signed char>'
    if (value.value() <= static_cast<long>(std::numeric_limits<int8_t>::max()) && value.value() >= static_cast<long>(std::numeric_limits<int8_t>::min())) {
                                                ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/max_size_type.h:53:10: note: template is declared here
  struct numeric_limits;
         ^
1 error generated.
make[3]: *** [CMakeFiles/TrustWalletCore.dir/build.make:1812: CMakeFiles/TrustWalletCore.dir/src/Everscale/CommonTON/RawAddress.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/dev/Downloads/wallet-core-master/build'
make[2]: *** [CMakeFiles/Makefile2:252: CMakeFiles/TrustWalletCore.dir/all] Error 2
make[2]: Leaving directory '/home/dev/Downloads/wallet-core-master/build'
make[1]: *** [CMakeFiles/Makefile2:342: tests/CMakeFiles/tests.dir/rule] Error 2
make[1]: Leaving directory '/home/dev/Downloads/wallet-core-master/build'
make: *** [Makefile:221: tests] Error 2
make: Leaving directory '/home/dev/Downloads/wallet-core-master/build'
root@dev-virtual-machine:/home/dev/Downloads/wallet-core-master# 
`

**Comment by Milerius** [comment]
Hello, thanks for reporting the issue - we have a pending PR with the fix, see #2917
