### ISSUE TITLE
Swift Package Incorrect

### ISSUE THREAD

**Issue by maxxfrazer** [trustwallet/wallet-core#2920]
**Describe the bug**
I've made this issue before, and @Milerius thought he'd fixed it despite my comments on #2732 .

Please understand that the Package.swift file added to the release here is not the one that is used when adding a swift package to a project:
<img width="1037" alt="202214162-9022f731-d284-4d77-ad5f-3f30d23ba0ba" src="https://user-images.githubusercontent.com/5754073/218071731-b09c715e-3a1f-42d5-a490-6cdd6ba262b9.png">

The only `Package.swift` that is used is the one that lives in the root directory of the repository, so essentially this one:

https://github.com/trustwallet/wallet-core/blob/3.1.10/Package.swift

Adding a new commit that bumps the version in `Package.swift` alone will not fix the issue, there should be a check in your release drone to see that the versions match up to the branch commit. I would edit myself, but I do not know where your release CI file is.

**To Reproduce**

Add the package to a swift project via the steps of adding the repo URL + version number, and you will see the binaries fetched in Package.swift are not the same as the version added.

**Expected behavior**

The installed package should have the correct binary versions.

**Screenshots**

This image is still applicable:
<img width="1040" alt="202214842-754c174f-2b6a-4069-bc1a-77ed526461be" src="https://user-images.githubusercontent.com/5754073/218072387-f7d5c3bd-b9ca-4b8e-bc05-8a79576e799d.png">

**Additional context**

Please run a test of trying to install with Xcode to actually see the issue.

**Comment by Milerius** [comment]
It's not possible to fix it with the current format, release need to be compiled to have the sha256, we can only edit the root package afterwards - please do use the one in the release instead.

**Comment by maxxfrazer** [comment]
How do you propose the Package.swift is used as a swift package dependency? Following the README guide does not do this, it takes the package from the repo root.
