### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by deletexl** [trustwallet/wallet-core#2924]
Hi I want build trust core core for Ubuntu 22.04.1 LTS I following build instractions but I got this error.

/home/dev/Downloads/wallet-core-master/src/Everscale/CommonTON/RawAddress.cpp:23:33: fatal error: use of undeclared identifier 'LONG_MAX'
    if (errno == ERANGE && l == LONG_MAX) {
                                ^
1 error generated.
make[3]: *** [CMakeFiles/TrustWalletCore.dir/build.make:1812: CMakeFiles/TrustWalletCore.dir/src/Everscale/CommonTON/RawAddress.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/dev/Downloads/wallet-core-master/build'
make[2]: *** [CMakeFiles/Makefile2:252: CMakeFiles/TrustWalletCore.dir/all] Error 2
make[2]: Leaving directory '/home/dev/Downloads/wallet-core-master/build'
make[1]: *** [CMakeFiles/Makefile2:342: tests/CMakeFiles/tests.dir/rule] Error 2
make[1]: Leaving directory '/home/dev/Downloads/wallet-core-master/build'
make: *** [Makefile:221: tests] Error 2
make: Leaving directory '/home/dev/Downloads/wallet-core-master/build'

**Comment by abacustodian** [comment]
I am seeing this same issue any resolution?
