### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by SamaKaur** [trustwallet/wallet-core#2925]
Describe the bug
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: library "libTrustWalletCore.so" not found

Additional context
App is been crashing when initializing wallet with  
init {
        System.loadLibrary("TrustWalletCore")
    }

Crashlytics has been reporting this issue recently.

Sdk Version: 2.8.0

App Info
minSdkVersion: 26
targetSdkVersion: 33

Device 
Nokia C20

**Comment by Milerius** [comment]
Hello will need more information for this one, it's seems that u didn't build the lib properly. Please follow the instructions on https://developer.trustwallet.com/wallet-core/developing-the-library/building and let us know if u still have a problem.

**Comment by SamaKaur** [comment]
Hi @Milerius , Thanks for replying back. Our Android app is in production working fine on all devices. Accept above mentioned Nokia. So I was wondering, is there any solutions for devices that does not work with trustwallet and crash the app.

**Comment by vcoolish** [comment]
Hi @SamaKaur
We monitor the issue and see it occurs on 0.005% of devices. 
There is no solution for now.
