### ISSUE TITLE
[KMM Error] java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by BreakZero** [trustwallet/wallet-core#2930]
**Describe the bug**
Hi @MaximPestryakov, I tried to use `3.1.14` into KMM project, but i got java.lang.UnsatisfiedLinkError. And i checked the package name from `KMM(com.trustwallet.core)` is not same as `wallet-core(wallet.core.**)`. I am sure i have loaded the `.so` file but i am not sure if i setup the project in right way.

here is my `shared` module gradle file, `wallet-core` implementation in `app` module
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/25579672/218793054-6e0d7175-8b98-4232-a9e1-255ea190d5aa.png">

**Screenshots**
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/25579672/218791502-b08a98e1-4323-4804-bbc6-a36d16890bd3.png">

**Comment by MaximPestryakov** [comment]
@BreakZero Thanks for reporting! I've just fixed this issue: #2929. Please, wait for the next release. And be careful as this library may be unstable. Also, you can only specify it once for common target:
```kotlin
val commonMain by getting {
    dependencies {
        implementation("com.trustwallet:wallet-core-kotlin:3.1.14")
    }
}
```
