### ISSUE TITLE
Can't build WalletCore XCFrameworks

### ISSUE THREAD

**Issue by megakoko** [trustwallet/wallet-core#2938]
Hello!

I'm trying to build the xcframeworks of the library. I've checked out version 3.1.9, installed the dependencies, ran `./bootstrap`. Everything finished successfully. 

When I try to run either `tools/ios-xcframework` or `tools/ios-build` I get an error saying that `WalletCoreRs.xcframework` could not be found. Am I missing something? 

Thank you

```
~/work/tangem/wallet-core tools/ios-xcframework
Building Docc...
~/work/tangem/wallet-core/swift ~/work/tangem/wallet-core
❌ error: There is no XCFramework found at '/Users/megakoko/work/tangem/wallet-core2/swift/WalletCoreRs.xcframework'. (in target 'WalletCore' from project 'TrustWalletCore')
** BUILD DOCUMENTATION FAILED **

~/work/tangem/wallet-core ./tools/ios-build    
Cleanup and init...
~/work/tangem/wallet-core/swift ~/work/tangem/wallet-core
⚙️  Generating plists...
⚙️  Generating project...
⚙️  Writing project...
Created project at /Users/megakoko/work/tangem/wallet-core2/swift/WalletCoreCommon.xcodeproj
~/work/tangem/wallet-core
Building scheme: WalletCoreCommon_macOS, destination: generic/platform=macOS, path: macos-arm64_x86_64
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, name:Any Mac }
{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
❌ error: There is no XCFramework found at '/Users/megakoko/work/tangem/wallet-core2/swift/WalletCoreRs.xcframework'. (in target 'WalletCoreCommon_macOS' from project 'WalletCoreCommon')
** ARCHIVE FAILED **

Building scheme: WalletCoreCommon_iOS, destination: generic/platform=iOS, path: ios-arm64
❌ error: There is no XCFramework found at '/Users/megakoko/work/tangem/wallet-core2/swift/WalletCoreRs.xcframework'. (in target 'WalletCoreCommon_iOS' from project 'WalletCoreCommon')
** ARCHIVE FAILED **

Createing xcframework...
error: the path does not point to a valid framework: /Users/megakoko/work/tangem/wallet-core2/build/ios-frameworks/ios-arm64.xcarchive/Products/Library/Frameworks/WalletCoreCommon.framework
```

**Comment by Chukwulawrence** [comment]
We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by Milerius** [comment]
> Hello!
> 
> I'm trying to build the xcframeworks of the library. I've checked out version 3.1.9, installed the dependencies, ran `./bootstrap`. Everything finished successfully.
> 
> When I try to run either `tools/ios-xcframework` or `tools/ios-build` I get an error saying that `WalletCoreRs.xcframework` could not be found. Am I missing something?
> 
> Thank you
> 
> ```
> ~/work/tangem/wallet-core tools/ios-xcframework
> Building Docc...
> ~/work/tangem/wallet-core/swift ~/work/tangem/wallet-core
> ❌ error: There is no XCFramework found at '/Users/megakoko/work/tangem/wallet-core2/swift/WalletCoreRs.xcframework'. (in target 'WalletCore' from project 'TrustWalletCore')
> ** BUILD DOCUMENTATION FAILED **
> 
> ~/work/tangem/wallet-core ./tools/ios-build    
> Cleanup and init...
> ~/work/tangem/wallet-core/swift ~/work/tangem/wallet-core
> ⚙️  Generating plists...
> ⚙️  Generating project...
> ⚙️  Writing project...
> Created project at /Users/megakoko/work/tangem/wallet-core2/swift/WalletCoreCommon.xcodeproj
> ~/work/tangem/wallet-core
> Building scheme: WalletCoreCommon_macOS, destination: generic/platform=macOS, path: macos-arm64_x86_64
> --- xcodebuild: WARNING: Using the first of multiple matching destinations:
> { platform:macOS, name:Any Mac }
> { platform:macOS, variant:Mac Catalyst, name:Any Mac }
> ❌ error: There is no XCFramework found at '/Users/megakoko/work/tangem/wallet-core2/swift/WalletCoreRs.xcframework'. (in target 'WalletCoreCommon_macOS' from project 'WalletCoreCommon')
> ** ARCHIVE FAILED **
> 
> Building scheme: WalletCoreCommon_iOS, destination: generic/platform=iOS, path: ios-arm64
> ❌ error: There is no XCFramework found at '/Users/megakoko/work/tangem/wallet-core2/swift/WalletCoreRs.xcframework'. (in target 'WalletCoreCommon_iOS' from project 'WalletCoreCommon')
> ** ARCHIVE FAILED **
> 
> Createing xcframework...
> error: the path does not point to a valid framework: /Users/megakoko/work/tangem/wallet-core2/build/ios-frameworks/ios-arm64.xcarchive/Products/Library/Frameworks/WalletCoreCommon.framework
> ```

Hello, u need to follow the build instructions as explained in https://developer.trustwallet.com/wallet-core/developing-the-library/building - please let me know if u still have any questions
