### ISSUE TITLE
Can't build  on ubantu

### ISSUE THREAD

**Issue by AiTaiShan** [trustwallet/wallet-core#2940]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by AiTaiShan** [comment]
An error occurred when I executed the './bootstrap.sh 'command using ubantu build.
![1676784124502](https://user-images.githubusercontent.com/125786180/219932407-a139fcbf-b895-49be-b607-0c5519340769.jpg)
![1676784124502](https://user-images.githubusercontent.com/125786180/219932460-c7d461fc-e67a-4f06-adce-850bea940c45.jpg)
I looked on the Internet and didn't install the ruby environment but when I did, I still had this problem.
![1676784179684](https://user-images.githubusercontent.com/125786180/219932533-ddafe1b5-df75-4ba3-b55e-a6e5761c66b6.jpg)
Please help me thank you

**Comment by Chukwulawrence** [comment]
@AiTaiShan We'd be happy to look into this for you. Kindly file a support ticket here
https://forms.gle/zVGLP7GATPsDHdkH9

**Comment by AiTaiShan** [comment]
@Chukwulawrence Thank you very much for helping me. I can't open your link address

**Comment by Milerius** [comment]
You need to install ruby as your prompt suggest, please let me know if u have any other questions

**Comment by LiWang-555** [comment]
> need to install ruby as your prompt suggest, please let me know if u have any other qu

Hi, I am one of team members with @AiTaiShan, and could you let me know what version of ruby should we use? Actually we met lots of blolking issues when we built it on ubuntu, so we worry that ruby version may matter. Thanks.

**Comment by Milerius** [comment]
> > need to install ruby as your prompt suggest, please let me know if u have any other qu
> 
> Hi, I am one of team members with @AiTaiShan, and could you let me know what version of ruby should we use? Actually we met lots of blolking issues when we built it on ubuntu, so we worry that ruby version may matter. Thanks.

The prerequisited for linux are there: https://developer.trustwallet.com/wallet-core/developing-the-library/building#prerequisites-on-linux - you should be fine by following those instructions

**Comment by AiTaiShan** [comment]
I ran the command 'sudo apt-get install ruby-full' in ubantu version 22.04 and downloaded Ruby-3.0.2p107. I don't know if this version meets the requirements.

**Comment by Milerius** [comment]
> @LiWang-555 I ran the command 'sudo apt-get install ruby-full' in ubantu version 22.04 and downloaded Ruby-3.0.2p107. I don't know if this version meets the requirements.

it does

**Comment by AiTaiShan** [comment]
Thank you for answering my question, but the problem was not solved. I tried to download ruby by executing the 'sudo apt-get install ruby-full' command.
![1676943040207](https://user-images.githubusercontent.com/125786180/220246885-4aec8fee-6dab-4c6f-98a6-5fd61510fc7d.jpg)
Then the same error occurs when executing the './bootstrap.sh 'command.
![1676952992636](https://user-images.githubusercontent.com/125786180/220247323-95381809-18b0-4f87-a1a8-f1e41089ee76.jpg)
I hope you can tell me if this error is caused by the ruby version or other reasons.

**Comment by Milerius** [comment]
> Thank you for answering my question, but the problem was not solved. I tried to download ruby by executing the 'sudo apt-get install ruby-full' command. ![1676943040207](https://user-images.githubusercontent.com/125786180/220246885-4aec8fee-6dab-4c6f-98a6-5fd61510fc7d.jpg) Then the same error occurs when executing the './bootstrap.sh 'command. ![1676952992636](https://user-images.githubusercontent.com/125786180/220247323-95381809-18b0-4f87-a1a8-f1e41089ee76.jpg) I hope you can tell me if this error is caused by the ruby version or other reasons.

It's seems that ur computer is configured with CRLF instead of LF https://stackoverflow.com/questions/1552749/difference-between-cr-lf-lf-and-cr-line-break-types - Can you double check locally and let us know if it works with LF file ending?

**Comment by AiTaiShan** [comment]
I downloaded the source code from github and opened it with vim in real dos format. I ran cat -A to see what the terminator looked like.
![1676984546470](https://user-images.githubusercontent.com/125786180/220353900-f8d4bfcb-c982-474e-9fc3-670600b177d9.jpg)
It doesn't work and then I modify it with vim 'set ff=unix' and it works and then I run 'cat -A' and I get the following result.
![1676984618765](https://user-images.githubusercontent.com/125786180/220354729-2b9ba88e-27d0-412d-91e7-a1568174e4a7.jpg)
Do all files need 'set ff=unix'? That would be a lot of work.

**Comment by Milerius** [comment]
> I downloaded the source code from github and opened it with vim in real dos format. I ran cat -A to see what the terminator looked like. ![1676984546470](https://user-images.githubusercontent.com/125786180/220353900-f8d4bfcb-c982-474e-9fc3-670600b177d9.jpg) It doesn't work and then I modify it with vim 'set ff=unix' and it works and then I run 'cat -A' and I get the following result. ![1676984618765](https://user-images.githubusercontent.com/125786180/220354729-2b9ba88e-27d0-412d-91e7-a1568174e4a7.jpg) Do all files need 'set ff=unix'? That would be a lot of work.

On my computer if I clone a new repo all the file endings are Unix, as I've said this means you've smth missconfigured somewhere that turn everyfile in CRLF format - you can also recursively run: `dos2unix -D filename`

**Comment by aderullyakbar2** [comment]
it's up to you, I just want to sync my crypto on etherscan , bsc
automatically

Pada tanggal Sel, 21 Feb 2023 20.33, Sztergbaum Roman <
***@***.***> menulis:

**Comment by AiTaiShan** [comment]
Thank you. I think I found the reason. I downloaded the code to windows first and then transferred it to the virtual machine,But I ran into a new problem, need to install Xcode on ubantu?
![1676989861983](https://user-images.githubusercontent.com/125786180/220374108-b9fa53ab-efc0-4b28-adaa-8e214212cf1a.jpg)
