### ISSUE TITLE
Could someone provide me the git path of trust wallet pleaes?

### ISSUE THREAD

**Issue by LiWang-555** [trustwallet/wallet-core#2953]
I do know that this is not a real bug, but I really have to know the git path of trust wallet of Chrome extensions, android and iOS, and I only find wallet core in this project. So I put an issue here, and could someone tell me the git path?

Thank you very much. And you guys can feel free to close this issue.

**Comment by Milerius** [comment]
Hello! Those repository are private and not publicly available, sorry.
