### ISSUE TITLE
How to sign message in iOS & Android APP?

### ISSUE THREAD

**Issue by Olive-l** [trustwallet/wallet-core#2963]
**[1] _Describe the requirement_**
I'm developing an APP, which wanna use the wallet to login the app. So I need to sign a message to send to our backend service, to verify the wallet address it's valid or not. 

**[2] _To Reproduce_**
In web-js, to do the validation by blow code:
`sign = await this.provider.request({
                      method: 'personal_sign',
                      params: [message, publicKey],`

**[3] _Expected behavior in iOS_**
I want to do the same thing as web-js in iOS & Android APP. Is there any solution about this???

**[4] _additional remarks_**
I checked the API in iOS wallet-core SDK, it's only one object named "AnySigner" related with Sign. But can't do the 'personal_sign' thing.

**Comment by Milerius** [comment]
> **[1] _Describe the requirement_** I'm developing an APP, which wanna use the wallet to login the app. So I need to sign a message to send to our backend service, to verify the wallet address it's valid or not.
> 
> **[2] _To Reproduce_** In web-js, to do the validation by blow code: `sign = await this.provider.request({ method: 'personal_sign', params: [message, publicKey],`
> 
> **[3] _Expected behavior in iOS_** I want to do the same thing as web-js in iOS & Android APP. Is there any solution about this???
> 
> **[4] _additional remarks_** I checked the API in iOS wallet-core SDK, it's only one object named "AnySigner" related with Sign. But can't do the 'personal_sign' thing.

Hello @Olive-l we support message signing on few blockchains at the moment.

- [ETH Android](https://github.com/trustwallet/wallet-core/blob/master/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/ethereum/TestEthereumMessageSigner.kt)
- [StarkEx Android](https://github.com/trustwallet/wallet-core/blob/master/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/starkex/TestStarkExMessageSigner.kt)
- [Bitcoin iOS](https://github.com/trustwallet/wallet-core/blob/714bfaca8b9fa800fa4e5bcc957fc8e5697fbd76/swift/Tests/Blockchains/BitcoinTests.swift#L178)
- [Ethereum iOS](https://github.com/trustwallet/wallet-core/blob/714bfaca8b9fa800fa4e5bcc957fc8e5697fbd76/swift/Tests/Blockchains/EthereumTests.swift#L287)

Please let me know if u have any other questions

**Comment by Olive-l** [comment]
@Milerius Thanks much for your reply. New question is,  I can't find the class: EthereumMessageSigner or BitcoinMessageSigner in my TrustWalletCore SDK.

I used pod to import the SDK, and the SDK version of iOS is 3.0.4.

**Comment by Olive-l** [comment]
I've updated the SDK version, and it fixed very well. thanks a lot!  @Milerius

**Comment by Milerius** [comment]
You're welcome @Olive-l !
