### ISSUE TITLE
Build failing for Docker

### ISSUE THREAD

**Issue by abacustodian** [trustwallet/wallet-core#2978]
**Describe the bug**
The WalletConsole utility shows incorrect Cardano `addrDefault` value, so I want to build from scratch to see if it works correctly but the build fails with the error below. The WalletConsole was accessed using ```docker run -i -t trustwallet/wallet-core /wallet-core/build/walletconsole/walletconsole```. Related issue #2924.

```
#14 196.1 /wallet-core/src/Everscale/CommonTON/RawAddress.cpp:23:33: fatal error: use of undeclared identifier 'LONG_MAX'
#14 196.1     if (errno == ERANGE && l == LONG_MAX) {
#14 196.1                                 ^
#14 196.1 1 error generated.
#14 196.1 make[3]: *** [CMakeFiles/TrustWalletCore.dir/build.make:1812: CMakeFiles/TrustWalletCore.dir/src/Everscale/CommonTON/RawAddress.cpp.o] Error 1
#14 196.1 make[3]: *** Waiting for unfinished jobs....
#14 199.3 make[3]: Leaving directory '/wallet-core/build'
#14 199.3 make[2]: *** [CMakeFiles/Makefile2:252: CMakeFiles/TrustWalletCore.dir/all] Error 2
#14 199.3 make[2]: Leaving directory '/wallet-core/build'
#14 199.3 make[1]: *** [CMakeFiles/Makefile2:259: CMakeFiles/TrustWalletCore.dir/rule] Error 2
#14 199.3 make[1]: Leaving directory '/wallet-core/build'
#14 199.3 make: *** [Makefile:182: TrustWalletCore] Error 2
#14 199.3 make: Leaving directory '/wallet-core/build'
------
executor failed running [/bin/bash -o pipefail -c tools/generate-files     && cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug     && make -Cbuild -j12 TrustWalletCore]: exit code: 2
```

**To Reproduce**
1. Change line 23 of Dockerfile to ```RUN wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb && dpkg -i ./libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb``` since 2.16 returns 404
2. ```docker build . -t wallet-core-dev``` 

**Expected behavior**
The build to succeed

**Comment by Milerius** [comment]
#2981 should fix it
