### ISSUE TITLE
[Rust CI]: Setup extras for Rust CI

### ISSUE THREAD

**Issue by Milerius** [trustwallet/wallet-core#2984]
**Is your feature request related to a problem? Please describe.**

As we want to write more rust, we will have to ensure the robustness of our implementations. to do this we need cargo caching, run the rust unit tests and display them on the CI, the clippy checks and finally the coverage check.

**Describe the solution you'd like**

We can use github actions if this help for unit tests report in CI.

**Checklist**

- [x] cargo caching
- [x] run rust unit tests
- [x] unit tests report in the CI
- [x] clippy check in the CI
- [x] coverage check + report CI

**Comment by satoshiotomakan** [comment]
I would also like to integrate the [rustfmt](https://github.com/rust-lang/rustfmt) tool for formatting Rust code.
This may require to add the `rustfmt.toml` config file to `wallet-core/rust` directory.

**Comment by rcolomina** [comment]
For cargo caching, [sccache ](https://github.com/mozilla/sccache) is a compiler caching tool, avoiding compilation when possible
