### ISSUE TITLE
[Rust]: Investigate CXX.rs support

### ISSUE THREAD

**Issue by Milerius** [trustwallet/wallet-core#2985]
**Is your feature request related to a problem? Please describe.**

Investigate if we can use https://cxx.rs/ in our project on all platform (mobile, wasm etc) it will help to write more efficient C++ with taking advantage of RAII.

**Describe the solution you'd like**

Optimally we will have better error management with CXX.rs, better RAII support (memory management)

**Describe alternatives you've considered**

 Alternatively we can generate some helpers instead of using CXX.rs

**Resources**

[Resources link](https://cxx.rs/)

**Comment by vccomnet** [comment]
I don't like the rust language. I hope wallet-core is a pure c/c++code project. The project introduces the rust language, which is very troublesome to compile
