### ISSUE TITLE
[Z-Cash] 16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)

### ISSUE THREAD

**Issue by ValeriD** [trustwallet/wallet-core#2991]
Hello!

### Describe the issue

I am following the examples and code guides. The encoded transaction is created and signed successfully: ```0400008085202f8901f963206760b643786aa8099658f5ef2d95839e01dc07bde6fbcabd6bc0992240000000006b48304502210087278d93176756536bd78cfcfe6ca2e64be77fa73900a7c6edc46ea37fd36ae602203d972b659107079ee6ac6978d35eb886f6a59f3e623cec99af8d4b82f025a99a0121029173fe55c86f8e883d668c86ae22e963e05a3ba9835fdf1f24e572963ffcd018ffffff7f0280969800000000001976a914469dec9c187b6887c611e650aa92a5e01f9e8a6088acfec25b05000000001976a914baa320f7178f62db513ce171ceb17411349645c988ac00000000000000000000000000000000000000```

### Expected behaviour

The transaction is successfully broadcasted. Its TXID is obtained.

### Actual behaviour + errors

sendrawtransaction fails with ```mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)``` error message.

My node is online.
Amount for inputs was setted.
Branch id is ```0xc2d6d0b4```.

**Comment by Milerius** [comment]
Need to have more code to understand the behavior, actually there is not enough information to determine the problem.

**Comment by ValeriD** [comment]
Hello, again!

I am providing the steps of building the transaction.

First I am building Bitcoin signing input:
```
Bitcoin.SigningInput.newBuilder().apply {
            hashType = BitcoinScript.hashTypeForCoin(coinType)
            amount = selectedAmount
            byteFee = estimateFee?.toSatoshiPerByte() ?: 0
            toAddress = recipient
            changeAddress = addressDetails?.address ?: ""
            this.coinType = coinType.value()
            addPrivateKey(privatekey...)
            utxos?.forEach { utxo ->
                    addUtxo(
                        Bitcoin.UnspentTransaction.newBuilder().apply {
                            outPoint = Bitcoin.OutPoint.newBuilder().apply {
                                hash = ByteString.copyFrom(
                                    utxo.txid.decodeHex().reversed().toByteArray()
                                )
                                index = utxo.vout ?: 0
                                sequence = Int.MAX_VALUE
                            }.build()
                            amount = utxo.value.toLong()
                            script = ByteString.copyFrom(
                                BitcoinScript.lockScriptForAddress(
                                    addressDetails?.address,
                                    coinType
                                ).data()
                            )
                        }.build()
                    )
                }
        }.build()
```
Then I am creating new Bitcoin Transaction Plan, so that I can replace the branchId:
```
val newInput = Bitcoin.SigningInput.newBuilder(input as Bitcoin.SigningInput).apply {
                        var plan = AnySigner.plan(input, coinType, Bitcoin.TransactionPlan.parser())
                        plan = Bitcoin.TransactionPlan.newBuilder(plan)
                            .setBranchId(ByteString.copyFrom("c2d6d0b4".decodeHex())).build()
                        setPlan(plan).build()
                    }.build()
```
And finally I am signing the input using the AnySigner interface:
```val output = AnySigner.sign(  newInput, coinType,Bitcoin.SigningOutput.parser())```
The value of ```output.encoded``` in one of our tests was 
```
0400008085202f8901f963206760b643786aa8099658f5ef2d95839e01dc07bde6fbcabd6bc0992240000000006b48304502210087278d93176756536bd78cfcfe6ca2e64be77fa73900a7c6edc46ea37fd36ae602203d972b659107079ee6ac6978d35eb886f6a59f3e623cec99af8d4b82f025a99a0121029173fe55c86f8e883d668c86ae22e963e05a3ba9835fdf1f24e572963ffcd018ffffff7f0280969800000000001976a914469dec9c187b6887c611e650aa92a5e01f9e8a6088acfec25b05000000001976a914baa320f7178f62db513ce171ceb17411349645c988ac00000000000000000000000000000000000000
```

**Comment by Milerius** [comment]
You can find few example of how to build ZCash transactions here: https://github.com/trustwallet/wallet-core/blob/master/tests/chains/Zcash/TWZcashTransactionTests.cpp - please let us know if u still have trouble
