### ISSUE TITLE
[Rust]: Refactor crates

### ISSUE THREAD

**Issue by Milerius** [trustwallet/wallet-core#3004]
**Is your feature request related to a problem? Please describe.**

We have to reorganize the crates to be able to publish them independently, the main crate still needs to compile a static library so that we can link it to C++, separate the FFI functions from the Rust interfaces to make a clear separation, start documenting the functions that go

**Describe the solution you'd like**

- Each crate(s) can be published, versionned
- FFI separation with other public functions
- Documentation for FFI functions
- Reorganize tests, write common functions for tests - avoid DRY.

**Checklist**

- [ ] Make crates publishable
- [ ] Separate FFI functions from public functions
- [ ] Documents FFI functions
- [ ] Ideally optimize tests to avoid DRY.

**Comment by satoshiotomakan** [comment]
@Milerius could you please give your vision on how it should look
> FFI separation with other public functions

I think the best way is to move all extern C functions, structures, constants to `ffi.rs` module in each subcrate.
For example, `tw_encoding/lib.rs` will be
```rust
// tw_encoding/lib.rs
pub mod base64; // Consists of Rust implementation only.
pub mod base32; // Consists of Rust implementation only.
// ...
pub mod ffi; // Consists of extern C functions/structures/constants only.
```

**Comment by Milerius** [comment]
> @Milerius could you please give your vision on how it should look
> 
> > FFI separation with other public functions
> 
> I think the best way is to move all extern C functions, structures, constants to `ffi.rs` module in each subcrate. For example, `tw_encoding/lib.rs` will be
> 
> ```rust
> // tw_encoding/lib.rs
> pub mod base64; // Consists of Rust implementation only.
> pub mod base32; // Consists of Rust implementation only.
> // ...
> pub mod ffi; // Consists of `pub extern "C"` functions/structures/constants only.
> ```
> 
> Pros:
> 
> * Makes it more obvious which `extern "C"` functions each crate exports. It's enough to open `ffi.rs` only.
> * Separates function implementation from its extern "C" binding.

Sounds good, ffi.rs for each module make a clear separation.
