### ISSUE TITLE
[Interface] Return `Result` when C++/Rust FFI function fails

### ISSUE THREAD

**Issue by satoshiotomakan** [trustwallet/wallet-core#3007]
**Is your feature request related to a problem? Please describe.**
At this moment, we simply return a default object if a C++/Rust FFI function fails.
A few examples:
https://github.com/trustwallet/wallet-core/blob/d67078daa580b37063c97be66a625aaee9664882/rust/src/encoding/base32.rs#L103-L115
https://github.com/trustwallet/wallet-core/blob/d67078daa580b37063c97be66a625aaee9664882/src/Waves/Signer.cpp#L28-L36

**Describe the solution you'd like**
We could add and return a `TWResult` structure from Rust FFI functions first (as they are not used outside of wallet-core yet):
```rust
/// For example, `TwResult<*mut char>`.
#[repr(C)]
pub struct TWResult<T> {
    /// 0 if Success, otherwise an error code.
    pub code: usize,
    pub data: T,
}
```
`TWResult::code` could be a generic `E` enum `TWResult<TWData, AnySignerSignError>`

**Comment by Milerius** [comment]
> **Is your feature request related to a problem? Please describe.** At this moment, we simply return a default object if a C++/Rust FFI function fails. A few examples:
> 
> https://github.com/trustwallet/wallet-core/blob/d67078daa580b37063c97be66a625aaee9664882/rust/src/encoding/base32.rs#L103-L115
> 
> 
> https://github.com/trustwallet/wallet-core/blob/d67078daa580b37063c97be66a625aaee9664882/src/Waves/Signer.cpp#L28-L36
> 
> **Describe the solution you'd like** We could add and return a `TWResult` structure from Rust FFI functions first (as they are not used outside of wallet-core yet):
> 
> ```rust
> /// For example, `TwResult<*mut char>`.
> #[repr(C)]
> pub struct TWResult<T> {
>     /// 0 if Success, otherwise an error code.
>     pub code: usize,
>     pub data: T,
> }
> ```
> 
> `TWResult::code` could be a generic `E` enum `TWResult<TWData, AnySignerSignError>`

Does cbindgen will generate a template C++ class in this case?

**Comment by satoshiotomakan** [comment]
At the moment this is just an idea, I'll see how it can be done.
> Does cbindgen will generate a template C++ class in this case?

**Comment by satoshiotomakan** [comment]
This is not possible to define a generic C-compatible structure, and `cbindgen` can't help with it.
But there is a workaround - we can define all c-result types for each type manually, and implement common functions by using a [impl_cresult](https://github.com/trustwallet/wallet-core/blob/s/rust-cresult/rust/tw_memory/src/ffi/c_result.rs#L8) macros.

The full example: https://github.com/trustwallet/wallet-core/commit/fd2cf98ba50cced27c5d325041e33fd984112893
