### ISSUE TITLE
How to use wallet-core-3.1.20-sources.jar in java project 

### ISSUE THREAD

**Issue by NaboxAdmin** [trustwallet/wallet-core#3018]
**Describe the bug**

Hi guys , when I decompress the wallet-core-3.1.20-sources.jar,  and copy the source code into my java project(not android application),like this:
![image](https://user-images.githubusercontent.com/86038959/227420140-fe62b6c3-ae51-4121-ad6f-807dc96ba39f.png)

I write code to test private key import, when run it throws exception like this：
![image](https://user-images.githubusercontent.com/86038959/227420878-e6fb87e9-8e10-46c6-a97b-4b07ee2fa170.png)

I checked some other issues, it seems that a package needs to be imported, 
System.loadLibrary("TrustWalletCore");
I do that, but there are other exception like this：
![image](https://user-images.githubusercontent.com/86038959/227421340-98d9326f-2cec-4c44-a707-b90a9c295749.png)

I want to confirm whether it is feasible for me to directly import the source package into the project, or is there a step I am missing?

**Comment by Milerius** [comment]
You can use gradle to import the project, packages are available there: https://github.com/orgs/trustwallet/packages?repo_name=wallet-core
