### ISSUE TITLE
How to generate BITCOIN address using BIP-44 ? 

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/wallet-core#3023]
How to generate BITCOIN address using BIP-44? 

This sample gives me a BIP-84... which is the newest standard pattern.
`getAddressForCoin(CoinType.BITCOIN)`

Can I get the BIP-44 Andress using Trust Wallet Core?

**Comment by Milerius** [comment]
Hello @ronaldoguedess you have bunch of example regarding Bitcoin segwit address manipulation here: https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Addresses/BitcoinAddressTests.swift - please let us know if anything else is needed.
