### ISSUE TITLE
Sign message return incorrect result 

### ISSUE THREAD

**Issue by farhankhwaja** [TrustWallet/wallet-core#305]
When i sign using TrustWallet App on a development version of my website, I should be able to recover the wallet address associated from the signed message. But, the address generated from the signed message comes out to be something random.

My wallet Address as visible on TrustWallet App: 0xbb53DA1379735b8754de08A435a2EC794711Db15

Signed Message: 0x4eb10f6df0a0023601f3e1ee0a65f0b43559abfffa1d868420da8b3f9f66131112f77b6f1a40c712b38ac385da39bbeb36e4dcc53c0f643229f7a91f7b0ac75f1b

Verification Message: Please verify your ETH Address

Result using my code:  0xa6b7c505ced3f705fc4c93dbca2c0874357ebc03

Below is the piece of code used for decoding:

`     
let _sig = sig.substr(2);`
`      const m = ethUtil.toBuffer(Web3.utils.sha3(`\x19Ethereum Signed Message:\n${msg.length}${msg}`));`
`      const v = Web3.utils.hexToNumber('0x' + _sig.slice(128, 130));`
`      const r = '0x' + _sig.slice(0, 64);`
`      const s = '0x' + _sig.slice(64, 128);`
`      vEth = ethUtil.ecrecover(m, v, r, s);`
`      vEth = ethUtil.pubToAddress(vEth);`
`      vEth = ethUtil.bufferToHex(vEth);`

Expected Output/Wallet Address: 0xbb53DA1379735b8754de08A435a2EC794711Db15

I have verified this with Metamask and it works fine. Its only trustwallet which is giving me the issue. if it could be looked into.

**Comment by vikmeup** [comment]
iOS, Android? Which version of the app are you using?

**Comment by farhankhwaja** [comment]
iOS, version 2.2047.0

I even tried using the mnemonic phrase and looped over other possible addresses and was not able to find the one generated by ecrecover. 

This has led to generation of an account i don't control. Possible loss of ERC721/20 too

**Comment by hewigovens** [comment]
@farhankhwaja can you check https://js-eth-sign.surge.sh/ ? `personal_ecRecover` works for me in Trust iOS

**Comment by farhankhwaja** [comment]
@hewigovens I will check the link, but why doesn't the above code which works for all doesn't work for trust wallet?? I want to understand that?

**Comment by hewigovens** [comment]
Did you send personal_sign web3 request? We will add ethereum prefix and hash it before signing, but we don’t hash the data from eth_sigh

**Comment by farhankhwaja** [comment]
yes, it's a personal web3 request.

**Comment by hewigovens** [comment]
Did you pass the raw message or hashed ?

**Comment by farhankhwaja** [comment]
we send the UTF-8 HEX decoded data and then envelop it with our message later when we use ecrecover.

**Comment by farhankhwaja** [comment]
We pass the raw message: 

msg: 'Please verify your ETH Address'

web3.personal.sign(msg, from, (err, res) => {
// Do our processing 
});

**Comment by hewigovens** [comment]
@farhankhwaja Thanks, we didn't use web3 1.0 personal sign api in the example, could you please try this: https://github.com/hewigovens/js-eth-personal-sign-examples/blob/master/index.js#L128 ?

**Comment by farhankhwaja** [comment]
Ohk. Good to know. Also, the Code base for iOS vs Android different. As, it doesn;t seem to be a problem with Android Version of TrustWallet.

And, if you can elaborate on why web3 1.0 personal sign is not being used??

**Comment by rstormsf** [comment]
@farhankhwaja 
https://rstormsf.github.io/js-eth-personal-sign-examples/

Please use the examples in that URL

**Comment by mobile-gragas** [comment]
Hi @hewigovens , in Android, method sign message only supported in web3j.crypto huh, not on by trust wallet core, right?
