### ISSUE TITLE
Add Maya Protocol support

### ISSUE THREAD

**Issue by GiMa-Maya** [trustwallet/wallet-core#3060]
## Description
Maya Protocol is a fork of THORChain. It shares the same code, along with some new features. Maya Protocol will also integrate new chains, such as Dash, Kujira, Cardano and more. Maya Protocol has 2 coins: $CACAO, which is similar to THORChain's $RUNE, and $MAYA, a coin that captures 10% of the protocol's fees. https://docs.mayaprotocol.com/readme-1/introduction

Name: Maya Protocol

HD Derivation Scheme: m/44'/931'/0'/0

Symbol: $CACAO & $MAYA

Documentation: Fork of THORChain, so it works the same. 

Reason:

## Checklist

- [ ] Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).
- [ ] Coin Definition:
- [ ] Add the coin definition to registry.json.
- [ ] Execute codegen/bin/newcoin <coinid>.
- [ ] Execute tools/generate-files.
- [ ] Add coin dispatcher to src/Coin.cpp.
- [ ] Create tests in tests/Xxx/TWCoinTypeTests.cpp.
- [ ] Implement functionality in C++. Put it in a subfolder of src/.
- [ ] Entry.
- [ ] Address.
- [ ] Transaction (if necessary).
- [ ] Signer.
- [ ] Write unit tests. Put them in a subfolder of tests/.
- [ ] Mnemonic phrase - > Address derivation test. Put this test in the CoinTests.cpp file.
- [ ] Transaction signing tests, at least one mainnet transaction test.
- [ ] Add stake, unstake, get rewards tests if the blockchain is PoS like.
- [ ] Add relevant constants in TWEthereumChainID, TWCurve, etc., as necessary.
- [ ] Implement C interface in src/interface.
- [ ] Add tests for TWAnyAddress and TWAnySigner
- [ ] Validate generated code in Android an iOS projects. Write integration tests for each.
- [ ] Extend central derivation and validation tests: make sure the following tests are extended with the new coin: CoinAddressDerivationTests.cpp and CoinAddressValidationTests.cpp, TWHRPTests.cpp, CoinAddressDerivationTests.kt, CoinAddressDerivationTests.swift.
- [ ] Upload coin icon to [trustwallet/assets](https://github.com/trustwallet/assets/#how-to-add-asset) if necessary.

**Comment by Milerius** [comment]
Hello, this is not planned for now - closing
