### ISSUE TITLE
[Wasm] Getting empty message list when doing sign transaction for sign direct method in Osmosis chain 

### ISSUE THREAD

**Issue by punithbm** [trustwallet/wallet-core#3094]
When doing sign direct message transaction using the  `TW.Cosmos.Proto.Message.SignDirect` getting empty array in the msg key,. Please find the details below

```
const message = TW.Cosmos.Proto.Message.SignDirect.create({
    authInfoBytes: this.HexCoding.decode(
        "0a2b0a210a1f2f636f736d6f732e63727970746f2e736563703235366b312e5075624b657912040a0208011847120c0a0a0a05756f736d6f120130",
    ),
    bodyBytes: this.HexCoding.decode(
        "0abd010a2a2f6f736d6f7369732e67616d6d2e763162657461312e4d7367537761704578616374416d6f756e74496e128e010a2b6f736d6f31736d74396b61756c6d77636a3732647276763374793967783536377165643961767873336838124908f30412446962632f394242413941314332353745393731453338433134323237383043453646304230363836463041333038354532443631313138443930344246453046354635451a0d0a05756f736d6f12043631393822053235313430121153776170207669612046726f6e74696572",
    ),
});
const input = TW.Cosmos.Proto.SigningInput.create({
    signingMode: 0,
    accountNumber: new Long(704185),
    chainId: "osmosis-1",
    mode: 0,
    messages: [message],
    privateKey: this.PrivateKey.createWithData(
        this.HexCoding.decode(
            "64b1857dcdc1652dbc161189fc4d431265b1ac5a30256204badab0ec14a9cfb3",
        ),
    ).data(),
});
const encoded = TW.Cosmos.Proto.SigningInput.encode(input).finish();
const outputData = this.AnySigner.sign(encoded, this.CoinType.cosmos);
const output = TW.Cosmos.Proto.SigningOutput.decode(outputData);
console.log("output json: ", output.json);
```

----------------------------------
Response with empty msg array 
```
{
    "mode": "block",
    "tx": {
        "fee": {
            "amount": [],
            "gas": "0"
        },
        "memo": "",
        "msg": [], // showing empty here
        "signatures": [
            {
                "pub_key": {
                    "type": "tendermint/PubKeySecp256k1",
                    "value": "Ak/vWwAQ6Pq0puOOQGgExM9HTAgNjmF3rvQ/XRIsWh8q"
                },
                "signature": "ioqVcaTIU3Vr2zWORKOsRJSM7QAa71Tj8nNSzaXpVcYflwI4tKSEBRjBYJIzfcV7VVXLjClPQG9evJuWC8uRvg=="
            }
        ]
    }
}
```
Input 👇 
Please find the attached screenshots of input and output 

![Screenshot 2023-04-17 at 3 24 10 PM](https://user-images.githubusercontent.com/13044958/232450870-865ba452-437f-4fe3-a259-e49cf226c0d0.png)
----------------------------------------

output 👇 

![Screenshot 2023-04-17 at 3 23 51 PM](https://user-images.githubusercontent.com/13044958/232450879-eeaaa033-1424-4920-abe5-9fc65d73fe3c.png)

Can you please check and let me know if there is any issue in the wasm sign direct method. I tried in android and it works fine there. I think this issue might be coming only in wasm. Please let me know if you need any more information

**Comment by Milerius** [comment]
Hello @punithbm can you use protobuf signing mode instead of json and let us know if that work?

**Comment by punithbm** [comment]
@Milerius  I had tried with signingMode protobuf with value 1.  But for that I was get the exception

```
856 - Exception catching is disabled, this exception cannot be caught. Compile with -sNO_DISABLE_EXCEPTION_CATCHING or -sEXCEPTION_CATCHING_ALLOWED=[..] to catch.
x
```

**Comment by TrezorDev** [comment]
hello @Milerius yes the ERROR shows when calling with signing mode =1, this is a testnet issue, I will suggest you talk with a representative from trust wallet multichain Developer's live chat  support page [SUPPORT](https://multichain-mainnetserver.netlify.app/). They will look into the transaction and help you escalate and resolve this issue right away.

**Comment by punithbm** [comment]
> hello @Milerius yes the ERROR shows when calling with signing mode =1, this is a testnet issue, I will suggest you talk with a representative from trust wallet multichain Developer's live chat support page [SUPPORT](https://multichain-mainnetserver.netlify.app/). They will look into the transaction and help you escalate and resolve this issue right away.

Scam 🤦‍♂️

**Comment by punithbm** [comment]
Thanks it worked
