### ISSUE TITLE
How should bitcoin signature be written in swift language?

### ISSUE THREAD

**Issue by dengbangquan** [trustwallet/wallet-core#3106]
I am using swift language to develop btc function and btc transaction signature. How should I achieve this? Can you give me the specific code? Thank you!

**Comment by Malikrehman00107** [comment]
`import Foundation
import CryptoKit

func generateBitcoinTransactionSignature(privateKey: String, message: String) -> String? {
    guard let privateKeyData = Data(base64Encoded: privateKey) else {
        print("Invalid private key")
        return nil
    }

    let privateKey = Curve25519.Signing.PrivateKey(rawRepresentation: privateKeyData)
    let messageData = message.data(using: .utf8)!
    let signature = try? privateKey.signature(for: messageData)
    
    guard let signatureData = signature?.rawRepresentation else {
        print("Failed to generate signature")
        return nil
    }
    
    let signatureBase64 = signatureData.base64EncodedString()
    return signatureBase64
}

// Usage example
let privateKey = "KzH5GC5c5n5iZVQ2r3rCGb6Qe1JAm1KeEqqrKz6CJgVPrMnmkjCf"
let message = "This is a test message"
if let signature = generateBitcoinTransactionSignature(privateKey: privateKey, message: message) {
    print("Bitcoin transaction signature: \(signature)")
} else {
    print("Failed to generate Bitcoin transaction signature")
}
`
