### ISSUE TITLE
WalletCore.TW_Common_Proto_SigningError.errorMissingPrivateKey

### ISSUE THREAD

**Issue by dengbangquan** [trustwallet/wallet-core#3113]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/16422981/233963437-baa00a7a-8d1d-44cc-b812-1f6dc1e03c45.png">
<img width="994" alt="image" src="https://user-images.githubusercontent.com/16422981/233963507-055e3aab-35da-49f5-9177-fa56e5f12c02.png">
When I use the method of BTC deal to sign as shown, always prompt error message: my WalletCore. TW_Common_Proto_SigningError. ErrorMissingPrivateKey, where is now my problem, please give me some reference, thank you!

**Comment by Milerius** [comment]
Various example of how to sign BTC in swift in the following file: https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Blockchains/BitcoinTests.swift - please take a look carefully and let us know if u have any problem.
