### ISSUE TITLE
Docker Image Missing TrustWalletCore/TWMnemonic.h

### ISSUE THREAD

**Issue by piyushverma** [trustwallet/wallet-core#3114]
**Describe the bug**
I follow steps as in link https://developer.trustwallet.com/developer/wallet-core/integration-guide/server-side but build main failed with main.go:10:11: fatal error: 'TrustWalletCore/TWMnemonic.h' file not found
find /|grep -i TWMnemonic
Can't find above header file in all image.

**To Reproduce**
Follow steps on https://developer.trustwallet.com/developer/wallet-core/integration-guide/server-side 

**Expected behavior**
main.go:10:11: fatal error: 'TrustWalletCore/TWMnemonic.h' file not found

**Comment by Milerius** [comment]
TWMnemonic.h exists in the include folder be sure to respect the following path: `#cgo CFLAGS: -I/wallet-core/include`

This means that ur main.go should be next to the wallet-core folder, otherwise u can adjust the line accordingly.

**Comment by piyushverma** [comment]
Sorry but TWMnemonic.h does not exist in wawllet-core/include even in entire filesystem.
find /|grep -i TWMnemonic
Can't find above header file in all image.

Above command proves this.

Can you just run docker image and check ?
