### ISSUE TITLE
Any plans for ordinals support?

### ISSUE THREAD

**Issue by CryptoManiac** [trustwallet/wallet-core#3119]
Too lazy to write a full request according to provided template, so I’m just asking the question and leaving these links here:

Reference implementation: https://github.com/casey/ord
Ordinals theory explained: https://youtu.be/rSS0O2KQpsI
Ordinals BIP: https://github.com/casey/ord/blob/master/bip.mediawiki

Thanks :)

**Comment by Milerius** [comment]
Thanks for opening this issue, it's not planned for now - closing.
