### ISSUE TITLE
Refactor Ontology transaction test

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/wallet-core#312]
1. Remove `random32()` from `Ont.cpp` and `Ong.cpp`, 
2. Add random nonce field to `SigningInput` in `Ontology.proto` (Allow client to use secure platform random generator)
3. Simplify `TWOntologyTransactionTests`, `OntologyTests.swift` and `TestOntologySigning.kt`

**Comment by NashMiao** [comment]
@hewigovens okay, I will refactor transaction test case according to feedback.
