### ISSUE TITLE
Can not get Sui Address by CoinTye Class

### ISSUE THREAD

**Issue by deeryoona** [trustwallet/wallet-core#3158]
**Describe the bug**
can not find case .sui

**To Reproduce**
func getSuiAddressWithPriKey(priKey: String) -> String {
        
        if let prik = PrivateKey(data: Data(hexString: priKey)!) {
            let address = CoinType.sui.deriveAddress(privateKey: prik)
            return address
        }else{
            return ""
        }
        
    }

**Expected behavior**

**Screenshots**
![5001683703760_ pic](https://github.com/trustwallet/wallet-core/assets/5423076/bd4ab75c-1dcf-4b8a-a71b-4ea17bddfded)

**Additional context**

**Comment by deeryoona** [comment]
iOS by Swift

**Comment by Milerius** [comment]
Hello @deeryoona please ensure that u are using an up to date version of WalletCore, you can check unit tests example in the swift folder for more example.
