### ISSUE TITLE
Problems with pipeline 

### ISSUE THREAD

**Issue by armatusmiles** [TrustWallet/wallet-core#317]
## Expected Behavior
When tests failed - pipe line must show it

## Current Behavior
[Build from master](https://dev.azure.com/TrustWallet/Trust%20Wallet%20Core/_build/results?buildId=2749) Look at "Run codegen tests" they are failed, but pipeline is green.
![image](https://user-images.githubusercontent.com/20345096/56081971-f475ce80-5e1b-11e9-9b8b-1f1aaac607ea.png)

## Possible Solution
1) Fix test ( will be in PR #316 )
2) Fix pipeline script

**Comment by hewigovens** [comment]
Thanks, we will fix the tests

**Comment by armatusmiles** [comment]
But need fix pipeline too. He doesn't work properly...

**Comment by hewigovens** [comment]
It's fixed, https://dev.azure.com/TrustWallet/Trust%20Wallet%20Core/_build/results?buildId=2808 
```
11 tests, 27 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```
