### ISSUE TITLE
Could not find artifact com.trustwallet:wallet-core:jar:3.1.35 in github (https://maven.pkg.github.com/trustwallet/wallet-core)

### ISSUE THREAD

**Issue by jjjb91052** [trustwallet/wallet-core#3176]
**Describe the bug**
Hi, I met "Could not find artifact com.trustwallet:wallet-core:jar:3.1.35 in github (https://maven.pkg.github.com/trustwallet/wallet-core)" Error while importing wallet-core as maven dependency in a java project. But the wallet-core-proto import is successful.

I have read https://developer.trustwallet.com/developer/wallet-core/integration-guide/android-guide and configured the token properly

**To Reproduce**
Tried:
1. Generate a token with "read:package"
2. Configured setting.xml with:
<settings >

    <activeProfiles>
        <activeProfile>github</activeProfile>
    </activeProfiles>

    <profiles>
        <profile>
            <id>github</id>
            <repositories>
                <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/trustwallet/wallet-core</url>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
            </repositories>
        </profile>
    </profiles>

    <servers>
        <server>
            <id>github</id>
            <username>myusername</username>
            <password>mytoken</password>
        </server>
    </servers>
</settings>
3. Add maven dependency
<dependency>
    <groupId>com.trustwallet</groupId>
    <artifactId>wallet-core</artifactId>
    <version>3.1.35</version>
</dependency>

**Expected behavior**
I would like to use HDWallet feature in my java project

**Screenshots**
<img width="576" alt="Snipaste_2023-05-24_00-02-49" src="https://github.com/trustwallet/wallet-core/assets/134418260/c53de09f-c7cb-4d9b-9a0f-56be616fd13f">

<img width="960" alt="Snipaste_2023-05-24_00-07-32" src="https://github.com/trustwallet/wallet-core/assets/134418260/96bfbed2-acd6-4157-9777-296fb8030eb3">

**Additional context**
IDE: Intellij IDEA

**Comment by satoshiotomakan** [comment]
Hi @jjjb91052, could you please try to use the latest tag? 3.1.36
Please also note that we plan to make a new release today, so it can be changed to 3.1.37

**Comment by satoshiotomakan** [comment]
Feel free to re-open the issue if the problem hasn't gone
