### ISSUE TITLE
[Aptos] how to transfer Aptos Token with Swift

### ISSUE THREAD

**Issue by deeryoona** [trustwallet/wallet-core#3180]
I am a iOS developer use Swift
Aptos.test.swift  can not find example for transfer erc20 token
could have an example? Thanks!

**Comment by satoshiotomakan** [comment]
Hi, thank you for creating the issue!
We don't have an example in Swift, but there is in C++:
https://github.com/trustwallet/wallet-core/blob/71b7292e4750e413ff18d32910e8d29e858f6f8f/tests/chains/Aptos/SignerTests.cpp#L639-L682

**Comment by satoshiotomakan** [comment]
@deeryoona please feel free to re-open the issue if you have any questions.
