### ISSUE TITLE
[SOL] sol address is not equal the phantom wallet and okx wallet.

### ISSUE THREAD

**Issue by weixuefeng** [trustwallet/wallet-core#3185]
My mnemonic is :   chuckle camera crime repair twist mushroom chair sort bean age require arch
Phantom wallet & okx wallet's address is : 4kKskCT9CPJUnp3BbcwcjCEguVksQvMgpe9ZHA1oMwrd
Wallet-core address is : BsAjq9C3VZUzSi1eGhNmYfJX9Gt8yy6jT3aFP53m6W3g
what's wrong? what should i do? can i derivation solona address with wallet core?
```
> setMnemonic chuckle camera crime repair twist mushroom chair sort bean age require arch
Mnemonic set (12 words).
> coin sol
Set active coin to: solana    Use 'coin' to change.  (name: 'solana'  symbol: sol  numericalid: 501)
> addrDefault
Result:  BsAjq9C3VZUzSi1eGhNmYfJX9Gt8yy6jT3aFP53m6W3g
```

**Comment by satoshiotomakan** [comment]
Thank you for the issue.
We have a different derivation path by default. In order to generate the same address as Phantom and OKX wallets, you need to specify the proper derivation path: `m/44'/501'/0'/0'`.
I suppose by typing the following command:
```
addrDP m/44'/501'/0'/0'
```

**Comment by satoshiotomakan** [comment]
@weixuefeng I've just checked, we support Solana in our end-user applications if the `m/44'/501'/0'/0'` address is not empty.
