### ISSUE TITLE
[TON]: Support 24 words mnemonic

### ISSUE THREAD

**Issue by satoshiotomakan** [trustwallet/wallet-core#3188]
**Is your feature request related to a problem? Please describe.**
Users can't import wallets created using TON wallets as we don't support 24 words mnemonic (or probably do it other way).

**Describe the solution you'd like**
Consider checking how TON Rust library works and add the changes to Wallet Core so to handle 24 words mnemonic correctly,
Implementation to consider: https://github.com/ston-fi/tonlib-rs/blob/main/src/crypto/mnemonic.rs

**Comment by x80486** [comment]
Regardless, a 24-words wallet is more secure than a 12-words, so it would be great if that could be an option.

**Comment by Milerius** [comment]
U can import 24 words seed in TrustWallet already that follow the bip39 standard
