### ISSUE TITLE
[TON]: Add support for TON Jettons (Fungible tokens)

### ISSUE THREAD

**Issue by satoshiotomakan** [trustwallet/wallet-core#3196]
**Is your feature request related to a problem? Please describe.**
At this moment, Wallet Core supports the TON native asset, but not the TON Jettons (Fungible tokens).

**Describe the solution you'd like**
Allow the end-user to transfer TON Jettons (Tokens): [TEP 74](https://github.com/ton-blockchain/TEPs/blob/master/text/0074-jettons-standard.md).
Either adding a new Protobuf action (such as `TokenTransfer` along with [Transfer](https://github.com/trustwallet/wallet-core/blob/672e9ef33e2eca11e1f6f187ecb2424aa626da3b/src/proto/TheOpenNetwork.proto#L29-L56)) or adding new properties to the existing [Transfer](https://github.com/trustwallet/wallet-core/blob/672e9ef33e2eca11e1f6f187ecb2424aa626da3b/src/proto/TheOpenNetwork.proto#L29-L56) message.

**Checklist**

- [ ] Extend the Protobuf protocol: [TheOpenNetwork.proto](https://github.com/trustwallet/wallet-core/blob/master/src/proto/TheOpenNetwork.proto).
I suppose it should be changed accordingly:
```proto
message TokenTransfer {
    // Questionable (topic for discussion).
    uint64 query_id = 1;
    uint64 amount = 2;
    string dest = 3;
    string response_dest = 4;
    // Questionable (topic for discussion). Should this be used without `forward_payload`?
    uint64 forward_ton_amount = 5;
}

message Transfer {
  // ...

  // Optional field. Should be set in order to transfer Jettons.
    TokenTransfer token_transfer = 9;
}
```
- [ ] Implement the Jetton transferring in [src/TheOpenNetwork](https://github.com/trustwallet/wallet-core/tree/master/src/TheOpenNetwork)
- [ ] Add unit tests in [C++](https://github.com/trustwallet/wallet-core/tree/master/tests/chains/TheOpenNetwork), [Swift](https://github.com/trustwallet/wallet-core/blob/master/swift/Tests/Blockchains/TheOpenNetworkTests.swift), [Kotlin](https://github.com/trustwallet/wallet-core/tree/master/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/theopennetwork)

**Resources**

[TEP 74](https://github.com/ton-blockchain/TEPs/blob/master/text/0074-jettons-standard.md)

**Comment by hewigovens** [comment]
Already implemented, close issue
