### ISSUE TITLE
[Cardano]: Min ADA amount doesn’t work in JS

### ISSUE THREAD

**Issue by satoshiotomakan** [trustwallet/wallet-core#3197]
**Describe the bug**
`TWCardanoOutputMinAdaAmount` and `TWCardanoMinAdaAmount` don't work in JS because of the `uint64_t` return type.

**To Reproduce**
Call the FFI functions mentioned above.

**Screenshots**
![Screenshot 2023-06-05 at 13 11 16](https://github.com/trustwallet/wallet-core/assets/127754187/96ad36ec-7680-4d5a-93fe-11975ed7f2ac)

**Comment by APOKO-BOSS** [comment]
Вася ти не охуйв

**Comment by APOKO-BOSS** [comment]
Lol?

**Comment by APOKO-BOSS** [comment]
> **Опишите ошибку** `TWCardanoOutputMinAdaAmount` и `TWCardanoMinAdaAmount`не работайте в JS из-за `uint64_t`возвращаемого типа.
> 
> **Чтобы воспроизвести** вызов функций FFI, упомянутых выше.
> 
> **Скриншоты** ![Скриншот 05.06.2023 в 13:11:16](https://user-images.githubusercontent.com/127754187/243425869-96ad36ec-7680-4d5a-93fe-11975ed7f2ac.png)
