### ISSUE TITLE
[BTC]How to generate BTC P2TR address

### ISSUE THREAD

**Issue by July-Only** [trustwallet/wallet-core#3204]
I am an iOS developer, using the current swift library, how to generate BTC P2TR address? Thank you!

**Comment by Milerius** [comment]
Hello, taproot is not supported yet, it's under development.

**Comment by weixuefeng** [comment]
taproot address support yet?

**Comment by deeryoona** [comment]
> I am an iOS developer, using the current swift library, how to generate BTC P2TR address? Thank you!

taproot address support yet?

**Comment by deeryoona** [comment]
> taproot address support yet?

taproot address support yet?

**Comment by lamafab** [comment]
We have Taproot internally in [`rust/tw_bitcoin`](https://github.com/trustwallet/wallet-core/pull/3233), but it's not exposed yet via Wallet Core. We're currently going through a slow migration to make this happen, but we're not there yet. I cannot give you a deadline on when this is going to be finalized.
