### ISSUE TITLE
[WASM] how can i build trustwalletcore for browser environment

### ISSUE THREAD

**Issue by weixuefeng** [trustwallet/wallet-core#3234]
how can i build trustwalletcore for browser environment

**Comment by weixuefeng** [comment]
update [cmakelist.txt](https://github.com/trustwallet/wallet-core/blob/28e55d48cefd750d714a059ac3f34b9f3eff06f2/wasm/CMakeLists.txt#L43)
to
```
        LINK_FLAGS "--bind --no-entry --closure 1 -O2 -sSTRICT -sASSERTIONS -sMODULARIZE=1 -sENVIRONMENT=web -sALLOW_MEMORY_GROWTH=1 -sDYNAMIC_EXECUTION=0 -s EXPORTED_FUNCTIONS=['_setThrew']"
```
, this add `sENVIRONMENT=web`

**Comment by Yasinj05** [comment]
how can i solve this issue?
i got this problem too.
