### ISSUE TITLE
[TON] Add support memo for outgoing transactions

### ISSUE THREAD

**Issue by CWDT250** [trustwallet/wallet-core#3250]
**Is your feature request related to a problem? Please describe.**
Many services use memos to process transactions. could you add such functionality to the core?

**Comment by PolyProgrammist** [comment]
This functionality is already in the core. Use this https://github.com/trustwallet/wallet-core/blob/f3b1224f061972ccd8a9104d04e26c2c4764b58b/src/proto/TheOpenNetwork.proto#L52

**Comment by gerardbosch** [comment]
Hi, should this issue be closed then? I see that the Trust Wallet Android app already has the memo/comment field in the send screen.

**Comment by hewigovens** [comment]
Close for already implemented.
