### ISSUE TITLE
Browser Extension - Open source / license

### ISSUE THREAD

**Issue by wsdt** [trustwallet/wallet-core#3264]
Is the Trustwallet browser extension closed source? 

Because I can't find it. 

We would like to add Tron support and distribute it for our DApp. 
As you have just recently added Solana DApp support, we assume this should be a reasonable undertaking on our end. 

Happy to push upstream, if we have a chance of using it. 

Thank you!

**Comment by Milerius** [comment]
Hello, yes the browser extension is closed source.

**Comment by wsdt** [comment]
Ok thanks, could you connect me to the right person for a potential licensing deal? @Milerius

**Comment by ArtemGoryunov** [comment]
You can contribute dApp Tron support to our open source web3 provider https://github.com/trustwallet/trust-web3-provider

**Comment by wsdt** [comment]
@ArtemGoryunov but we would need it as browser extension, not as ios/android app.

**Comment by ArtemGoryunov** [comment]
Browser extension can use web3 provider
