### ISSUE TITLE
Checking mnemonic generate 

### ISSUE THREAD

**Issue by armatusmiles** [TrustWallet/wallet-core#332]
## Expected Behavior
Checking result mnemonic_generate function

## Current Behavior
If mnemonic generate will be failed [here](https://github.com/TrustWallet/wallet-core/blob/265e99f7fdd677a0af0b622e6465ab1c01e8a720/src/HDWallet.cpp#L44)  ( for example bad strength )
Program has not reaction for that and can crash or have unexpected behavior.

## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

**Comment by hewigovens** [comment]
probably duplicated with #235
