### ISSUE TITLE
[Blockchain/Rust] Create `tw_utxo` and adjust `tw_bitcoin`

### ISSUE THREAD

**Issue by lamafab** [trustwallet/wallet-core#3339]
We're planning on separating the UTXO model from `tw_bitcoin` and making it more generic to also support any kind of (Bitcoin) fork, such as Bitcoin Cash, Litecoin, etc. This UTXO crate will not include (standardized) scripts such as P2PKH and so on. Additionally, `tw_bitcoin` should be extended with the `tw_coin_entry` crate similar to https://github.com/trustwallet/wallet-core/pull/3322.

- Create `tw_utxo`
    - _Starting implementing this_
    - [x] Create Protobuf structures
    - [x] ~Extend with `tw_coin_entry`?~ At least use similar mechanisms such as `compile()`, `json_signer()`, ...
        - [x] Add `preimage_hashes()` which generates the Sighashes for signing.
        - [x] Add `compile()` which building the final, serialized transaction.
    - [x] Support SIGHASH variants (`All`, `Single`, `AllPlusAnyoneCanPay`, etc...)
    - [x] Support signature hashing variants (`legacy`, `segwit` and `taproot`).
- Update `tw_bitcoin`
    - _Started implementing this_
    - [x] Make use of `tw_utxo`
    - [x] Extend with `tw_coin_entry` 
    - [x] Add planner for input selection and required "targets"
        - [x] Extend appropriate Protobuf structures
        - [x] Specific planners for BRC20, Ordinals, etc. Standardize those, similar to https://github.com/trustwallet/wallet-core/issues/3338
    - [x] Add proper fee projector/calculator

**Comment by weixuefeng** [comment]
not support generate taproot address yet？
