### ISSUE TITLE
TON derivation path

### ISSUE THREAD

**Issue by nerzh** [trustwallet/wallet-core#3387]
https://github.com/trustwallet/wallet-core/blob/6dc5acb31f9af687edc99d785c90546f2a3af5bf/registry.json#L4310

Hello, please tell me why the derivation path of the TON blockchain is different than in other blockchains?

<img width="747" alt="Снимок экрана 2023-08-22 в 11 13 26" src="https://github.com/trustwallet/wallet-core/assets/10519803/422d03a9-9941-442c-a32c-a7e1de4c3519">

m/44' /60' /0' /0 /0
m/44' /607'/0'

I mean, in TON derivation path missing the following components **/0 /0**

**Comment by cryshado** [comment]
Seems kind of weird. I hope we'll get an explanation. Could it be a mistake or what is the reason?

**Comment by PolyProgrammist** [comment]
Hi, it's not an exception. For example, NEAR has the same derivation path. 
https://github.com/trustwallet/wallet-core/blob/6dc5acb31f9af687edc99d785c90546f2a3af5bf/registry.json#L1942

If you look here:
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#user-content-Change
There is no really valuable meaning in change and address index (/0/0). Change is used for bitcoin. And address index can be easily interchanged with account. So it's about preferences. 

When I implemented and consulted TW team, the preference was m/44' /607'/0'
