### ISSUE TITLE
Unit Tests Fail and TWStoredKeyImportHDWallet Method Does Not Work on Xcode 14.3.1 for iOS in Release Configuration

### ISSUE THREAD

**Issue by subbotkin** [trustwallet/wallet-core#3391]
### Environment
- TrustWalletCore version: 3.2.13
- Xcode version: 14.3.1
- Build configuration: Release

### Problem Description

In the release build of my code, I encountered an issue where the `TWStoredKeyImportHDWallet` method did not function as expected. Additionally, when running the unit tests in the TrustWalletCore project for iOS using the latest version of Xcode (14.3.1), the tests fail in the release configuration. Notably, the tests pass successfully when using Xcode version 14.0.1. 

### Investigation

Upon investigation, I found that the issue seems to be related to the optimization level set for the trezor-crypto target in the release configuration. Specifically, if I set the `GCC_OPTIMIZATION_LEVEL` to 3 (`-O3`) instead of the default `-Os`, the tests begin to pass on Xcode 14.3.1, and the `TWStoredKeyImportHDWallet` method functions correctly.

### Steps to Reproduce
1. Clone TrustWalletCore repository
2. Open the project in Xcode 14.3.1
3. Select the release configuration and set `ENABLE_TESTABILITY = YES` for the WalletCore target
4. Run the unit tests
5. Observe that the tests fail
6. Change `GCC_OPTIMIZATION_LEVEL` for the trezor-crypto target to 3 (`-O3`)
7. Run the tests again
8. Observe that the tests pass

### Expected Behavior

The `TWStoredKeyImportHDWallet` method should function correctly, and the unit tests should pass in the release configuration on Xcode 14.3.1 without requiring changes to the optimization level.

### Actual Behavior

The `TWStoredKeyImportHDWallet` method does not function correctly, and the unit tests fail on Xcode 14.3.1 in the release configuration unless the `GCC_OPTIMIZATION_LEVEL` for the trezor-crypto target is set to 3 (`-O3`).

### Request

Please investigate the issue and provide a fix or guidance on the correct configuration. Thank you.

**Comment by Milerius** [comment]
Hey thanks for the issue, not a big fan of compiling with -O3 for security reason on a cryptographic library, however if it's well supported by trezor, we may want to switch, @satoshiotomakan let's see if pulling upstream change from trezor crypto may solve the problem without change of compiling flag

**Comment by satoshiotomakan** [comment]
@subbotkin could you please double check if the issue has gone?

**Comment by subbotkin** [comment]
@satoshiotomakan I checked with Xcode 15.0.0, the problem is gone (before the fix, the issue was reproducible with Xcode 15.0.0 too). Thank you!
