### ISSUE TITLE
Move BlockchainType.swift from iOS to wallet core

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/wallet-core#341]
```swift
public enum BlockchainType {
    case bitcoin
    case tron
...
```

**Comment by alejandro-isaza** [comment]
How is this different from CoinType?

**Comment by hewigovens** [comment]
Less switch cases, for bitcoin / ethereum forks, we can just use bitcoin/ethereum

**Comment by alejandro-isaza** [comment]
But in the swift implementation we have separate for things like theta which is are Ethereum forks. Also separate Binance and Cosmos, aren't they the same blockchain?
