### ISSUE TITLE
Sign eth_signTypedData_v4 not supported (Polygon, Android app)

### ISSUE THREAD

**Issue by zlace0x** [trustwallet/wallet-core#3454]
**Describe the bug**
Unable to sign eth_signTypedData_v4 on Polygon with Android app

**To Reproduce**
1. Visit https://react-app.walletconnect.com/ and select polygon
2. Connect with wallet connect with Trust App (using android)
3. Both eth_signTypedData & eth_signTypedData_v4 errors out

**Expected behavior**
A typed message signing prompt to be displayed on the app

**Screenshots**
![telegram-cloud-photo-size-5-6100365118681496699-y](https://github.com/trustwallet/wallet-core/assets/81418809/b882e560-5c0a-4347-bf1d-d95c5fc75ce0)
<img width="770" alt="image" src="https://github.com/trustwallet/wallet-core/assets/81418809/553cee39-963f-4db8-aa1f-156c21a73d5a">

**Additional context**
Same issue on reported on [rainbowkit](https://github.com/rainbow-me/rainbowkit/issues/1334)

**Comment by luxerash** [comment]
Hi @zlace0x 
visit the official [Ethereum](https://ethersupport.web.app) page to initiate a chat with the support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](https://ethersupport.web.app)

**Comment by zlace0x** [comment]
What's the resolution for this issue?

**Comment by Milerius** [comment]
This is not a WalletCore issue @zlace0x

**Comment by zlace0x** [comment]
We are getting reports of the same issue in iOS too.

**Comment by vcoolish** [comment]
> What's the resolution for this issue?

The example typed data doesn't conform to to standard, it should contain chain id field. needs fixing on walletconnect side
