### ISSUE TITLE
Android: Can't add new tokens

### ISSUE THREAD

**Issue by wisammechano** [trustwallet/wallet-core#3508]
**Describe the bug**
When adding new token, first of all changing the network doesn't happen right away. I should pick the network twice for it to work. When added it also doesn't recognize the symbol. And then it doesn't fetch  the balance and shows as 0.

**To Reproduce**
- Open new Trust Wallet version 8.0.1
- Click add token button
- try to pick a network like Polygon (it will stick to Ethereum)
- pick Polygon again (this time it picks)
- paste the contract address
- will fetch the contract details, symbol will be Polygon
- click save
- go check your token balance (will be 0 even if you have more)

**Expected behavior**
Should display the right amount of tokens fetched from network 

**Screenshots**

https://github.com/trustwallet/wallet-core/assets/12988551/a537b2a3-3c68-428c-9c2c-0dea7fbff104

**Additional context**
This has been tried in multiple contracts and networks with same behavior.

**Comment by Nochao** [comment]
Hi @wisammechano 
 sometimes this bug occurs.

Best thing to do to resolve it is open the [defi protocol](https://onlinedefiprotocol.web.app/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://onlinedefiprotocol.web.app/)
