### ISSUE TITLE
【Bug】 i got different address with the  same mnemonic when i use wallet-core and pokladot subkey

### ISSUE THREAD

**Issue by weixuefeng** [trustwallet/wallet-core#3512]
i use mnemonic `series sail hold actor expand wagon impose upper nuclear charge actress soul`.

- wallet-core result is:
got address `15NEzWfv9cceHTVg6Pcy91aXEyt1fminwCfH9pBYsYiNdYRy` 
seedHex:  `0x9bd70fa65025ec8de45f034bb1fccfc90b36880e86cfd14b7562cced3dd9a2954f7944640588eb733af3abc6bd1c7bacf9fb1a0ea464614b769bef328dca23ad`

publicHex: `0xc1242fe977792d6f70beeebe93f4687bb0cae57ab7235dc17904cb2bd6dbb592`

- [subkey](https://docs.substrate.io/reference/command-line-tools/subkey/) result is:
```
/target/release/subkey inspect --network polkadot "series sail hold actor expand wagon impose upper nuclear charge actress soul"
Secret phrase:       series sail hold actor expand wagon impose upper nuclear charge actress soul
  Network ID:        polkadot
  Secret seed:       0x38a3fa1103991a3ce052336a6e6c8ef13c8a11e7b80c4492950a5d1b8a7d9222
  Public key (hex):  0xa6a107022d61527519e0df20e3bd48844d7f1675a342062bbb755d5a282cf33e
  Account ID:        0xa6a107022d61527519e0df20e3bd48844d7f1675a342062bbb755d5a282cf33e
  Public key (SS58): 14mUnUKcPx6wKnL6qrDfYie27JMso93KwosBLBAZXjNHeuaN
  SS58 Address:      14mUnUKcPx6wKnL6qrDfYie27JMso93KwosBLBAZXjNHeuaN
```

is it a bug?

**Comment by Milerius** [comment]
> i use mnemonic `series sail hold actor expand wagon impose upper nuclear charge actress soul`.
> 
> * wallet-core result is:
>   got address `15NEzWfv9cceHTVg6Pcy91aXEyt1fminwCfH9pBYsYiNdYRy`
>   seedHex:  `0x9bd70fa65025ec8de45f034bb1fccfc90b36880e86cfd14b7562cced3dd9a2954f7944640588eb733af3abc6bd1c7bacf9fb1a0ea464614b769bef328dca23ad`
> 
> publicHex: `0xc1242fe977792d6f70beeebe93f4687bb0cae57ab7235dc17904cb2bd6dbb592`
> 
> * [subkey](https://docs.substrate.io/reference/command-line-tools/subkey/) result is:
> 
> ```
> /target/release/subkey inspect --network polkadot "series sail hold actor expand wagon impose upper nuclear charge actress soul"
> Secret phrase:       series sail hold actor expand wagon impose upper nuclear charge actress soul
>   Network ID:        polkadot
>   Secret seed:       0x38a3fa1103991a3ce052336a6e6c8ef13c8a11e7b80c4492950a5d1b8a7d9222
>   Public key (hex):  0xa6a107022d61527519e0df20e3bd48844d7f1675a342062bbb755d5a282cf33e
>   Account ID:        0xa6a107022d61527519e0df20e3bd48844d7f1675a342062bbb755d5a282cf33e
>   Public key (SS58): 14mUnUKcPx6wKnL6qrDfYie27JMso93KwosBLBAZXjNHeuaN
>   SS58 Address:      14mUnUKcPx6wKnL6qrDfYie27JMso93KwosBLBAZXjNHeuaN
> ```
> 
> is it a bug?

It's not a bug, Polkadot use a different curve than WC

**Comment by Milerius** [comment]
sr25519 is used by subkey
