### ISSUE TITLE
[TapRoot] how can i generate taproot address now?

### ISSUE THREAD

**Issue by deeryoona** [trustwallet/wallet-core#3551]
**Describe the bug**
how can i generate taproot address now

**To Reproduce**
how can i generate taproot address now from publickey, i am an ios developer

**Comment by satoshiotomakan** [comment]
Duplicates https://github.com/trustwallet/wallet-core/discussions/3155, https://github.com/trustwallet/wallet-core/issues/3204#issuecomment-1808142176
