### ISSUE TITLE
How transfer BTC with TapRoot Address,eg: tapRoot Address1 to another tapRoot Address, i am an ios developer

### ISSUE THREAD

**Issue by deeryoona** [trustwallet/wallet-core#3580]
**Describe the bug**
How transfer BTC with TapRoot Address,eg: tapRoot Address1 to another tapRoot Address, i am an ios developer
eg:bc1pdgv0kguuwwn9q5qp5e896jxlq346xmpfzfy7a8hy0hewsstegf5s2mjfx9 to
     bc1pk72p9347skum86rhk6hy8vj886a5d0tj74tvurxv8g2snempzzsqe9e49d

**Comment by weixuefeng** [comment]
not support yet.

**Comment by Milerius** [comment]
We are planning to do a full rework of Bitcoin in Rust in Q1 and support every kind of BTC operation(s) through a new single interface for every UTXO's chain(s)

**Comment by hanxianlong** [comment]
> We are planning to do a full rework of Bitcoin in Rust in Q1 and support every kind of BTC operation(s) through a new single interface for every UTXO's chain(s)

Hi @Milerius  what's the progress of  the new btc interface, is it possible to support ordinal or brc20 now?

**Comment by satoshiotomakan** [comment]
Hi @hanxianlong, we do support BRC20 and ordinals (nft) transfers, please take a look into the examples: 
https://github.com/trustwallet/wallet-core/blob/7523c9805ce094639dfbda6d643e439f5ef1705e/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/bitcoin/TestBitcoinSigning.kt#L163-L483

**Comment by hanxianlong** [comment]
@satoshiotomakan Thank you so much, I'll have a try later.
