### ISSUE TITLE
Aptos address might be invalid if there is a leading 0

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#3584]
Reported from community, it was introduced in pr https://github.com/trustwallet/wallet-core/pull/3497 and the test was ignored

<img width="1171" alt="image" src="https://github.com/trustwallet/wallet-core/assets/360470/5b7cf1cb-082a-4a04-9f3a-4d679423a023">

I confirmed by checking Petra and Pontem

<img width="376" alt="Screenshot 0005-12-03 at 18 36 42" src="https://github.com/trustwallet/wallet-core/assets/360470/d99e7dbf-01eb-4f2c-b43a-1e069d0c4b9d">
<img width="377" alt="Screenshot 0005-12-03 at 18 36 53" src="https://github.com/trustwallet/wallet-core/assets/360470/8c689921-0a47-465b-9bc8-67fc122481ca">

We should make sure the address length is correct too.

**Comment by Milerius** [comment]
Not an issue, confirmed with aptos team
