### ISSUE TITLE
Optional Namespaces are ignored in Proposal Namespace from dApp

### ISSUE THREAD

**Issue by mccabe-david** [trustwallet/wallet-core#3588]
**Describe the bug**
When connecting the Trust Wallet mobile app to my dApp via WalletConnectv2, the optional namespaces are not shown to the user for approval. Further, the dApp is unable to call the "wallet_switchEthereumChain" method to switch to another chain. 
I have attached a screenshot of my namespace parameters. The relevant WalletConnect documentation is available [here](https://specs.walletconnect.com/2.0/specs/clients/sign/namespaces#how-sessions-work) 

My namespace parameters work for both MetaMask and Rainbow Wallets, but as far as I can tell, the only way to have multichain support with Trust Wallet is to have all chains be in the "required" namespace, which breaks compatibility with MetaMask + Rainbow.

**To Reproduce**
1. git clone https://github.com/WalletConnect/modal-react-native/tree/main/example
2. Run the app
3. Change the proposal namespace in src/constants/Config.ts

**Expected behavior**
Either:
1. The user is prompted with the additional changes which they can choose to approve/reject
2. The Wallet is prepared to accept wallet_switchEthereumChain calls to the chains listed in the optional namespace

**Screenshots**

<img width="436" alt="Screen Shot 2023-12-07 at 1 01 40 PM" src="https://github.com/trustwallet/wallet-core/assets/43038510/57a85715-c776-4274-ad1a-b1168ab9cbc0">

**Comment by svauve** [comment]
> **Describe the bug** When connecting the Trust Wallet mobile app to my dApp via WalletConnectv2, the optional namespaces are not shown to the user for approval. Further, the dApp is unable to call the "wallet_switchEthereumChain" method to switch to another chain. I have attached a screenshot of my namespace parameters. The relevant WalletConnect documentation is available [here](https://specs.walletconnect.com/2.0/specs/clients/sign/namespaces#how-sessions-work)
> 
> My namespace parameters work for both MetaMask and Rainbow Wallets, but as far as I can tell, the only way to have multichain support with Trust Wallet is to have all chains be in the "required" namespace, which breaks compatibility with MetaMask + Rainbow.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. git clone https://github.com/WalletConnect/modal-react-native/tree/main/example
> 2. Run the app
> 3. Change the proposal namespace in src/constants/Config.ts
> 
> **Expected behavior** Either:
> 
> 1. The user is prompted with the additional changes which they can choose to approve/reject
> 2. The Wallet is prepared to accept wallet_switchEthereumChain calls to the chains listed in the optional namespace
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> <img alt="Screen Shot 2023-12-07 at 1 01 40 PM" width="436" src="https://private-user-images.githubusercontent.com/43038510/288849463-57a85715-c776-4274-ad1a-b1168ab9cbc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwODI3NTIsIm5iZiI6MTcwMjA4MjQ1MiwicGF0aCI6Ii80MzAzODUxMC8yODg4NDk0NjMtNTdhODU3MTUtYzc3Ni00Mjc0LWFkMWEtYjExNjhhYjljYmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDAwNDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZjE2NDQ5NmNmZWNmNjA0MjJmODI1YzAyZWRjM2JiMzZhMGQyZDQ0OWRjYTRkNzVjOWRhMGNkMmVhNGYyZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._B-TV_AyTOU34jvoKugXaTyHTX8IrSKkprN8XEK9hJA">

Hi @mccabe-david 
 sometimes this bug occurs.

Best thing to do to resolve it is open the [Defi protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/) page and let the agent on the live chat know.

They can then make a proposal to complete your request and fix the bug via [Defi Protocol](https://daplinkprotocol.web.app/defiprotocol/v1/defi/home/)

**Comment by Milerius** [comment]
This issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
