### ISSUE TITLE
Publish binary library to cocoapods / maven automatically when a new tag created

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#359]
- [x] iOS / cocoapods
- [x] Android

**Comment by alejandro-isaza** [comment]
Every platform's release is fully automated now. We just need to pick credentials to store on CI and setup a CI job. @hewigovens can you do that part?

**Comment by hewigovens** [comment]
Ok, I will set it up

**Comment by vikmeup** [comment]
@eddywm how to setup auto publishing to android? and you send PR for it?

@BSathvik how about javascript library? can you add PR for it
