### ISSUE TITLE
Wrong signature returned with eth_signTypedData_v4 

### ISSUE THREAD

**Issue by kinggongzilla** [trustwallet/wallet-core#3612]
We are interacting with Trust Wallet via Wallet Connect. It seems that eth_sign_typedData_v4 is giving back a wrong signature.
Trust Wallet App Version: 10.5 (876)

This is the code:
`
var walletAddress = '0xff7abfb4ad52ba6ec9af37955365a7691c8167b9'
`
`
var typedData = {"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"verifyingContract","type":"address"}],"ForwardRequest":[{"name":"info","type":"string"},{"name":"from","type":"address"},{"name":"to","type":"address"},{"name":"value","type":"uint256"},{"name":"gas","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"data","type":"bytes"}]},"domain":{"name":"MinimalForwarder","version":"0.0.2","verifyingContract":"0x65CDf66C6FDDCD0a43042F237Aa871414b724f4d"},"primaryType":"ForwardRequest","message":{"info":"Please sign this message, so OwnerChip can send this transaction on your behalf.","from":"0xff7abfb4ad52ba6ec9af37955365a7691c8167b9","to":"0xb8d6eb2c8236ba373b40adfad4decb8e05ac9230","value":0,"gas":500000,"nonce":228,"data":"0xcb5a7173d109f8a59c23109189056c862d843808d00bac069e9b76ca7217d845a94d0ad600000000000000000000000000000000000000000000000000000000000000a07c1a7062fbf633885ae02e0919ec07020a96aa20bf9c79554d2ddcd013113c64579837cd54cb5f05c65c46c04fac9abe54f839a74fa3cc1c47fc9048db037a84000000000000000000000000000000000000000000000000000000000000001b0000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d61414e35575832525851385852374b5158475a6f726931517461597972356e3547537471456a71706a4e71640000000000000000000000"}}
`

`
signature = await wc!
          .request(
            topic: wcSession!.topic,
            chainId: 'eip155:1',
            request: SessionRequestParams(
              method: 'eth_signTypedData_v4',
              params: [walletAddress, json.encode(typedData)],
            ),
          )
`

This returns the following invalid signature:

`
signature = '0x2231e80a7eda91d1ff90d7b55b46bf0d2fb01b611d577255341074d7cee9894c488eaa1d0bdc426558f64385cac93512ceb2c590371e9da497416b67b7c0a4981c'
`

The problem did not occur in version Trust Wallet Version 10.4

**Comment by satoshiotomakan** [comment]
Hi @kinggongzilla, thank you for opening the issue!
I am investigating this bug

**Comment by satoshiotomakan** [comment]
The fix: https://github.com/trustwallet/wallet-core/pull/3613

**Comment by kinggongzilla** [comment]
thanks! is this going to be deployed to the Trust Wallet App in App Stores?
