### ISSUE TITLE
[Bitcoin] Change explorer to mempool.space

### ISSUE THREAD

**Issue by vcoolish** [trustwallet/wallet-core#3638]

**Comment by satoshiotomakan** [comment]
Thank you for opening the issue!
What's the advantage of using mempool.space?

**Comment by vcoolish** [comment]
it provides mempool status and better transaction information, like fee rate, time, utxo representation 
![IMAGE 2024-01-10 18:26:36](https://github.com/trustwallet/wallet-core/assets/32914239/68ba6c87-1560-46bc-a875-39ff1973dbf2)
![IMAGE 2024-01-10 18:27:15](https://github.com/trustwallet/wallet-core/assets/32914239/8fb1a34d-d823-4271-ac0e-5d7207a7542c)

![IMAGE 2024-01-10 18:27:06](https://github.com/trustwallet/wallet-core/assets/32914239/433f1bf5-24cb-46b5-a635-3c839f33f30c)

![IMAGE 2024-01-10 18:26:47](https://github.com/trustwallet/wallet-core/assets/32914239/32516a27-1793-42f3-9574-1f4bde49606b)

![IMAGE 2024-01-10 18:26:39](https://github.com/trustwallet/wallet-core/assets/32914239/ca6d015d-c23b-4307-a5dc-06036ddbfb7a)
