### ISSUE TITLE
Sending entire Tezos balance to a new address fails and waists 0.26 XTZ burn cap

### ISSUE THREAD

**Issue by songproducer** [trustwallet/wallet-core#3647]
My friend just tried to send his entire Tezos balance to a new tezos address and it failed with error

Empty implicit delegated contract
Emptying an implicit delegated account is not allowed.

So the transaction failed and also burned the account-creation fee.

**Describe the solution you'd like**
For the entire balance to be sent and for it not to fail.

**Describe alternatives you've considered**
Don't automatically send the whole balance when max is used. Instead deduct 0.01 to leave the account with some dust so the transaction doesn't fail.

![image](https://github.com/trustwallet/wallet-core/assets/597346/7dffc837-1c2b-4b5b-98a3-240111d60608)

**Comment by Vasually** [comment]
Hi @songproducer sorry about this.
Are you still having this error?

**Comment by satoshiotomakan** [comment]
Hi @songproducer, could you clarify which app you use to broadcast the transaction?

**Comment by songproducer** [comment]
Trust wallet on iOS

**Comment by songproducer** [comment]
> Hi @songproducer sorry about this.
> 
> Are you still having this error?

It was a Tezos protocol error code so I can only assume that the way the trust wallet max send implementation works it is a reproducible issue.

**Comment by Milerius** [comment]
This issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
