### ISSUE TITLE
[Cosmos] Add support for timeout_height field

### ISSUE THREAD

**Issue by y3fers0n** [trustwallet/wallet-core#3683]
Cosmos dApps request to sign a doc with timeout_height field set when using signAmino, and currently wallet-core does not have a way to set that field.

**Describe the solution you'd like**
Allow to set timeout_height when signing a StdSignDoc on cosmos using WalletKit

**Resources**

Resources link
https://github.com/cosmos/cosmos-sdk/pull/6089

**Comment by satoshiotomakan** [comment]
Completed at https://github.com/trustwallet/wallet-core/pull/3684
