### ISSUE TITLE
My wallet balance is not showing 

### ISSUE THREAD

**Issue by Poseidon200314** [trustwallet/wallet-core#3697]
I made a transaction(bitcoin) that took about 5 days to complete and as if that’s not enough i couldn’t make another transaction within that 5 days and then after the transaction went through it was showing me url error when I tried to send out some money to someone so I tried re importing my wallet and this time my balance was even showing at all,it was showing $0 meanwhile all my transactions history were still there and in blockchair my balance is still intact so the fault should definitely be from your end….can you fix the fault or do I have to stop using trust wallet???

this is my bitcoin wallet: bc1qs8ar05sca7je3kzaylhm6kunw7379tsl5rjtax

![IMG_5274](https://github.com/trustwallet/wallet-core/assets/161301838/ec4ead6b-a49e-4f93-b89c-60ff6e38a6b1)
![IMG_5275](https://github.com/trustwallet/wallet-core/assets/161301838/27b573db-ded0-4561-8ce8-e25a4a262eae)

**Comment by ArtemGoryunov** [comment]
Hi @Poseidon200314 
Please submit a support ticket https://support.trustwallet.com/en/support/home
Please make sure you use the latest app version

**Comment by satoshiotomakan** [comment]
Please create a ticket at https://support.trustwallet.com/en/support/tickets/new if you have not done it yet.
I close the issue as it is not related to WalletCore.
