### ISSUE TITLE
Comments in proto files misleading

### ISSUE THREAD

**Issue by johnnyluo** [trustwallet/wallet-core#3706]
**Describe the bug**
All the proto files that use a type call uint256 contains a comment `(uint256, serialized little endian)` . which indicated the byte order it is expecting , it will be copied to all the files it generated. 

So when user import WalletCore and trying to use it , will also see the comments . For example , I am using it in swift to develop an IOS application,  Refer to the following screenshot
<img width="653" alt="image" src="https://github.com/trustwallet/wallet-core/assets/749608/db3ebe21-7914-4ea6-a8d7-04ce64795af3">

This comment is **wrong** , and mislead user , is says `(uint256, serialized little endian)` , but in fact it is actually expecting `big endian` also called network order 

**To Reproduce**
Just search the code base 

**Expected behavior**
the comment should be `(uint256, serialized big endian)`

**Screenshots**

**Additional context**

**Comment by satoshiotomakan** [comment]
Hi @johnnyluo, that's right, thank you for the notice! We'll definitely fix the comments
