### ISSUE TITLE
Native assets/coins impossible to search or add when creating new mnemonic

### ISSUE THREAD

**Issue by zewebdev1337** [trustwallet/wallet-core#3719]
**Describe the bug**
Creating a new mnemonic in the Chrome extension version results in ALL native coins being hidden and impossible to find via search/"Import token" funcionality

**To Reproduce**
Download Trust on Chrome
Import old mnemonic with active accounts and holding assets (I don't know if this is the only way to trigger, but this is what I did). Here, active assets are visible and can be found on search searching but assets that aren't already in the wallet when it loads are bugged too. 
Create new mnemonic
After creation, no asset will be visible
Click "Manage Crypto"
Search for ANY native coin (ETH on ETH, BTC on BTC, BNB on BNB, Matic on PolygonPOS, TRX on TRON, the list goes on and on as no native asset can be searched (and obviously these assets don't have a contract address in order to add them.). Update: The ONLY NATIVE asset I could find by searching was SOL on SOL. Check last screenshot.

**Expected behavior**
One should be able to search for and add/remove NATIVE coins (not tokens) like in the mobile version

**Screenshots**

![Screenshot_2024-03-08_21-40-03](https://github.com/trustwallet/wallet-core/assets/112774130/802d580e-9680-4373-81f0-0c4e04720c12)
![Screenshot_2024-03-08_21-39-38](https://github.com/trustwallet/wallet-core/assets/112774130/4eeec3d7-60dc-4e76-bd22-b6b186217003)
![Screenshot_2024-03-08_21-38-24](https://github.com/trustwallet/wallet-core/assets/112774130/0e8f23d1-d3f3-4611-bf11-ea67acc81edd)

SOL on SOL is the only one I could find:
![Screenshot_2024-03-08_21-39-04](https://github.com/trustwallet/wallet-core/assets/112774130/805d6783-c8b3-4f10-ac57-3a5171bc77a2)

**Additional context**
Running on Chromium 116 on archlinux

**Comment by satoshiotomakan** [comment]
Hi @y3fers0n, could you please take a look at the issue?

**Comment by zewebdev1337** [comment]
let me know if there's any additional info/help I can provide

**Comment by y3fers0n** [comment]
Could you try updating the extension? Which version do you have now? Thanks

**Comment by satoshiotomakan** [comment]
Hi @zewebdev1337, could you please create a ticket at https://support.trustwallet.com/en/support/tickets/new if you haven't done yet?
I close the issue as it is not related to WalletCore.

**Comment by zewebdev1337** [comment]
hey there, sorry for the delay, I did not have access to the specific system where this was ocurring but now I do, unfortunately I forgot to check the version installed at the time but I can confirm that reinstalling the extension fixed the issue for me. I believe I have an image of the drive somewhere but seeing that the latest version no longer presents this issue I'm not sure it would be required to look into it still
