### ISSUE TITLE
signTypedData does not work

### ISSUE THREAD

**Issue by cieltan** [trustwallet/wallet-core#3721]
**Describe the bug**
Trust Wallet is unable to signTypedData (all versions) preventing users from signing off-chain messages. This is a sev-1 bug and the only resolution for it right now is having users import their accounts to other wallet applications.

**To Reproduce**

1. Go on https://metamask.github.io/test-dapp/
2. Connect TrustWallet, change network to Avalanche
3. Try to use any signTypedData function

**Expected behavior**
User should be able to use signTypedData.

**Screenshots**
<img width="1724" alt="Screenshot 2024-03-11 at 12 44 13 PM" src="https://github.com/trustwallet/wallet-core/assets/40251412/621c9aeb-eb7d-4734-b9e2-add9e0062510">

**Comment by satoshiotomakan** [comment]
Hi @y3fers0n, could you please also take a look at this issue too? 🙂

**Comment by y3fers0n** [comment]
Hello, we recently found an issue and has been fixed, it will be available in the next release, but metamask has custom logic in their dApp for setting chainId, so it might still failing there. Thanks for reporting!
