### ISSUE TITLE
[Solana]: Invalid destination address (Fee calculation and unsigned transaction data)

### ISSUE THREAD

**Issue by JaimeToca** [trustwallet/wallet-core#3722]
**Describe the bug**
The following scenario happens and can be reproduced during fee calculation when you need to get an unsigned transaction data. Note: It does work with signed transaction

**My address**
Gw3tTxAgCMeQ2PozgN7zzDV8GSJBedPsPJbeJUcNeVne

**Api call**
https://api.rango.exchange/basic/swap?from=SOLANA.USDC--EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v&to=ETH.USDC--0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48&amount=1000000000&slippage=3.0&disableEstimate=true&fromAddress=Gw3tTxAgCMeQ2PozgN7zzDV8GSJBedPsPJbeJUcNeVne&toAddress=0x95222290dd7278aa3ddd389cc1e1d165cc4bafe5&apiKey=d341575a-8451-46c5-812b-125097ae7f39

**Serialized Message Base64** (from Rango network call)
AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQADB+y37qqaqKmX2XAwrq2gH1OIvsuslV+KP6krCv6lQrF/fLaI53KVmos3V5RFWA5J2XtZ6IJ/MUnrVPy6BScq6B3gOLhHgJrYb8iMKNU0D4cpT29khrdj+l9j7gzTg73kvmvfBDoYA94EJf9JLNKnkrfM5F0zQ9ZMg4ueSkt51aVLBkwkrmTl5G1OPyyp3UZBeIJtehO7aNA3aUz6Hn6EtK0DBkZv5SEXMv/srbpyw5vnvIzlu8X3EmssQ5s6QAAAAKFLzTYC6vfOspR18AlAfdoQQSzchbXIKs9TVzmL7XEYfkN8MINxpcAJo1peZUBeVtOX/cALtpPzYZ5hq+MqFfYDBABLeyJyZXF1ZXN0SWQiOiIyYjRiYjI4ZC02ZjE5LTQ0NjItODQwNS0wZjE0OWIzYTBiMGUiLCJzdGVwcyI6MSwiZGFwcFRhZyI6NjJ9BQAFAsBcFQAGEwAAAQwHCA0JAg4KCw8QEQMSExRxzD+pq7p9Vp/0kR/SjBgyjS3hOfBGMdAgBUFurx5jmlB1QX94JllO0QAAAAAAAAAAAAAAAJUiIpDdcniqPd04nMHh0WXMS6/lAQAAAAAAAAAAAAAAAKC4aZHGIYs2wdGdSi6esM42ButIIT0PAAAAAAABE15VVwN+rkjDzI0e7OXgq25CpALGVkk+AV4JUqDeEbYFARYEBgcJAAMXGAkZCwwN

**Blockhash**
5Caqq7M94ETrBXMrcZDqVyLnNicMzt4a2x9CDP82E2zB

```kotlin
val decodeTransaction = Base64.decode(serializedMessage) 
val decodeData = TransactionDecoder.decode(CoinType.Solana, decodeTransaction)
val decodedTransactionOutput = DecodingTransactionOutput.ADAPTER.decode(decodeData).transaction

val rawMessage = RawMessage(v0 = decodedTransactionOutput.v0?.copy(recent_blockhash = blockHash))
```

SigningInput - Hex encoded

```kotlin
SigningInput(
    tx_encoding = Encoding.Base64,
    raw_message = rawMessage,
)

```
SigningInput hexencoded
`0xa201a2051a9f050a0408011803122c4777337454784167434d655132506f7a674e377a7a44563847534a4265645073504a62654a55634e65566e65122c3950707a4e68553346635a375062424858746b575774324d635957615a5a577670644447344d797458554a51122c47364756484c45736d4d4a6336734b4b31566f774a5479703446334e66795a37634b79677041324c64704531122c3847357276334155615865664331484c6d346b354239596153476b586570626a627265786857695635346f74122b52616e676f68517861576970366931747741416e52564c6d6f62396a383866696437737132444d41415457122b436f6d70757465427564676574313131313131313131313131313131313131313131313131313131313131122c427264674e3252507a454d574639365a626e6e4a6155745144517837565258596148486259434276636557421a2c3543617171374d393445547242584d72635a447156794c6e4e69634d7a743461327839434450383245327a42224f08041a4b7b22726571756573744964223a2232623462623238642d366631392d343436322d383430352d306631343962336130623065222c227374657073223a312c2264617070546167223a36327d220908051a0502c05c1500228a01080612130000010c07080d09020e0a0b0f1011031213141a71cc3fa9abba7d569ff4911fd28c18328d2de139f04631d02005416eaf1e639a5075417f7826594ed100000000000000000000000095222290dd7278aa3ddd389cc1e1d165cc4bafe501000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48213d0f00000000002a400a2c324a63424145566e4177566f3475386436316971674850727a5a7575677572376356546a57756273564c486a120501160406071a090003171809190b0c0da80101
`

```kotlin
TransactionCompiler.preImageHashes(CoinType.Solana, signingInput)
```

hex encoded

`0x18102238412070726f766964656420616464726573732028652e672e2064657374696e6174696f6e20616464726573732920697320696e76616c6964`

```kotlin
PreSigningOutput.ADAPTER.decode(preImageOutputData)

PreSigningOutput{data_=[size=0], error=Error_invalid_address, error_message=A provided address (e.g. destination address) is invalid}
```

**Comment by satoshiotomakan** [comment]
Hi @JaimeToca, thank you for the opening the issue and explaining it in details.
The `Error_invalid_address` error occurs because we required to provide a `SigningInput::sender` address to fill the `PreSigningOutput::signers` list.
But if `SigningInput::raw_message` is provided, it's not necessary, and we can simply extract the signers list from `MessageVersioned`.
Fix: https://github.com/trustwallet/wallet-core/pull/3723

**Comment by JaimeToca** [comment]
Thank you @satoshiotomakan sounds good !!
