### ISSUE TITLE
[EverScale] There have different address about wallet-core & everWallet

### ISSUE THREAD

**Issue by weixuefeng** [trustwallet/wallet-core#3730]
when i use mnemonic for create everScale wallet. i got two different address.

wallet-core generate address is:
`0:f3e77dc96a8b5f20771e981a03b1806eaac30bf5d118a51ae905401e65bc4eba`

everWallet address is:
`0:dfff1d8c4a5b6a6bb422b91b781958a52998f17fbf01689a227cab8fa17fdbd0`

mnemonic is: 
`fee fold else repair boring alpha curious view margin december desk move`

can you help me?

@satoshiotomakan

**Comment by weixuefeng** [comment]
thanks for you reply. it's no problem. it's test mnemonic.

**Comment by satoshiotomakan** [comment]
Hi @weixuefeng, if I'm not mistaken, TON (and I believe Everscale) has a different mnemonic derivation standard, not BIP39.
We had a similar issue but with an error importing 24 words Mnemonic created using TON wallets: https://github.com/trustwallet/wallet-core/issues/3188
At this moment, we do not plan to support a different derivation standard as we are the multi-chain wallet

**Comment by weixuefeng** [comment]
No only mnemonic. when i use same privateKey, i got different address about wallet-core and everWallet.

wallet-core info:
```
{chainKey: EVER, accountPosition: 0, accountAddress: 0:f70e57671468d1c3123a8baeb007d3d483226c99a6f087c6c59053ae3565b298, accountPrivateKey: 15742ae3803f7c8549d8afaaccbe049a56872f28e3ec8c206547652f36bd9e6e, accountPublicKey: 5c6479f2997317622f8ce1efae8e7d5d448aa60b5bede2d70ce20e781032f571, accountExtendedPrivateKey: , accountExtendedPublicKey: , extendedPath: , accountPath: m/44'/396'/0'/0/0, wipPrivateKey: null, secretKey: null, btcAccounts: null}
```

everWallet info:
```
0:c04a3b76473ae6a33df68a63f41099362062c66893e0064592f14e76656f6b7c
priv: 15742ae3803f7c8549d8afaaccbe049a56872f28e3ec8c206547652f36bd9e6e
```
