### ISSUE TITLE
TrustWallet popup stuck in loading state on token approve 

### ISSUE THREAD

**Issue by uncleGena** [trustwallet/wallet-core#3734]
**Describe the bug**
When executing `approve` on token contract, it starts popup with stacked loader. Problem is that this loader stacks and never disappears. 

**To Reproduce**

1. [ethers.js v6.11.1](https://docs.ethers.org/v6/)
2. [trustwallet/web3-react-trust-wallet](https://github.com/trustwallet/web3-react-trust-wallet)
3. chain: BSC Testnet (Binance Chain Testnet)
4. custom token: 
 - address: 0x8eB171BAc8b42D85d2fE9AAA18B2dD62ef186126
 - symbol: PATEX

```typescript
const data = contractERC20Token.interface.encodeFunctionData('approve', [
  addressContractToApprove, // string
  amountToApprove, // bigint
])

const tx = await signer.sendTransaction({
  to: contractERC20TokenAddress, // string
  data, // string
})
```
**Expected behavior**
Open window with transaction info and buttons.

**Screenshots**
<img width="611" alt="image" src="https://github.com/trustwallet/wallet-core/assets/11743243/48f513d7-7436-4600-95c2-e08d51d8bdba">

**Additional context**
Sometimes loader stuck forever and only reinstalling extension helps. [Here](https://github.com/trustwallet/developer/issues/312) similar bug report.

**Comment by Pasha8914** [comment]
https://github.com/wevm/wagmi/issues/3718

same issue but with wagmi

**Comment by Pasha8914** [comment]
@hewigovens @Milerius

**Comment by dan1kov** [comment]
same problem

**Comment by DaStepn** [comment]
> Hi @uncleGena, we are investigating the issue at the moment and will provide ETA for hotfix release tomorrow.

Follow up, the fix is available for regression testing by QA team so a rough ETA for CWS submission is either Monday or Tuesday.

**Comment by Milerius** [comment]
This issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
