### ISSUE TITLE
I cant connected my wallet to web3 

### ISSUE THREAD

**Issue by Moemine1992** [trustwallet/wallet-core#3736]
![Screenshot_20240313-081952_Chrome](https://github.com/trustwallet/wallet-core/assets/163213643/a273a778-941f-4788-8979-4d5fa32f1caa)

![Screenshot_20240313-035701_Chrome](https://github.com/trustwallet/wallet-core/assets/163213643/4a41d487-bb39-42c6-a473-29c6332d1071)

![Screenshot_20240313-171754_Chrome](https://github.com/trustwallet/wallet-core/assets/163213643/0a5455bd-2939-40af-9bce-a4fcf9723787)

Can you please solve my issue to use my trust wallet to connect with web3 again

**Comment by Moemine1992** [comment]
![Screenshot_20240313-082316_Chrome](https://github.com/trustwallet/wallet-core/assets/163213643/537f196b-cffe-484d-a782-689e5bc10a18)

**Comment by Moemine1992** [comment]
> Hi @stylianos-panagakos, here's another web-extension related ticket

Dear i didn't understand, can you give me simple solutuon to do it

**Comment by satoshiotomakan** [comment]
Hi @Moemine1992, thank you for the report! Our team is looking for a solution already

**Comment by Moemine1992** [comment]
> Hi @Moemine1992, thank you for the report! Our team is looking for a solution already

Thank you dear, so appreciate it

**Comment by Moemine1992** [comment]
> Hi @Moemine1992, thank you for the report! Our team is looking for a solution already

Please i need to know if this web3 is not scam can you help me with this

**Comment by Moemine1992** [comment]
When is complet and closed so now i can make a connect
