### ISSUE TITLE
Error Permit signature "Chain ID mismatch"

### ISSUE THREAD

**Issue by artemki2077** [trustwallet/wallet-core#3745]
**Describe the bug**
error when calling a signature for a permit, when trying to give the user a signature offer for a permit, the trust wallet application issues a `Chain ID mismatch`, although before that I change the network through the RPC request `wallet_switchEthereumChain`, and through the application itself I check which network is selected, and the strangest thing is that it only works on the iphone version of the application so both on android and the web version, everything works as it should. To request a signature, I use the `eth-permit` library, and create a provader through the ether-js library

**To Reproduce**
you can call a permit for any coin through the eth-permit library, then the trust will issue this error:

**Expected behavior**
I wanted to trigger a signature request for a permit

**Screenshots**
<img width="239" alt="Снимок экрана 2024-03-19 в 09 14 37" src="https://github.com/trustwallet/wallet-core/assets/86531080/00799eb2-40a0-42e9-8065-13c9abd5c136">

![photo_2024-03-19 08 46 47](https://github.com/trustwallet/wallet-core/assets/86531080/d9afc975-70e2-4259-bd32-c045554c9dd3)
![photo_2024-03-19 08 49 11](https://github.com/trustwallet/wallet-core/assets/86531080/2ed7d8e2-d8ae-4daf-8540-c1caafd5aada)

**Additional context**
Would you like to know if anyone has experienced this error? and is it still a wallet error or a library?, I'm still inclined to a wallet error since I tested it on all devices, on the trust and on the meta mask, and the error is issued only on the trust wallet iphone version

**Comment by satoshiotomakan** [comment]
Hi @artemki2077, could you please specify Trust Wallet app platform and version?

**Comment by artemki2077** [comment]
> Hi @artemki2077, could you please specify Trust Wallet app platform and version?

Version 11.2, specially updated before the tests, iphone version

**Comment by satoshiotomakan** [comment]
@artemki2077, thank you
Could you also share the EIP712 JSON payload (not a screenshot)?

**Comment by artemki2077** [comment]
**this is the json of the date that is submitted to the permit from the iPhone**
```json
{"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Permit":[{"name":"owner","type":"address"},{"name":"spender","type":"address"},{"name":"value","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"deadline","type":"uint256"}]},"primaryType":"Permit","domain":{"name":"","version":"1","chainId":"0x38","verifyingContract":"0xfb5b838b6cfeedc2873ab27866079ac55363d37e"},"message":{"owner":"0xc33d3EA257B5eDC234Bd2f87CC561Be9f9C1b203","spender":"0x0dDC70aE6Ae350A2Add5eE591A96c7Ac39722E62","value":"1461501637330902918203684832716283019655932542975","nonce":"0x","deadline":"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}}
```

**the json date that is submitted to the android**
```json
{"types":{"EIP712Domain":[{"name":"name","type":"string"},{"name":"version","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"Permit":[{"name":"owner","type":"address"},{"name":"spender","type":"address"},{"name":"value","type":"uint256"},{"name":"nonce","type":"uint256"},{"name":"deadline","type":"uint256"}]},"primaryType":"Permit","domain":{"name":"FLOKI","version":"1","chainId":"0x38","verifyingContract":"0xfb5b838b6cfeedc2873ab27866079ac55363d37e"},"message":{"owner":"0xc33d3EA257B5eDC234Bd2f87CC561Be9f9C1b203","spender":"0x0dDC70aE6Ae350A2Add5eE591A96c7Ac39722E62","value":"1461501637330902918203684832716283019655932542975","nonce":"0x0000000000000000000000000000000000000000000000000000000000000000","deadline":"0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}}
```
I just looked at it and for some reason the date that is issued by the library on the iPhone is not complete there is no name domain and also nonce looks 0x, but even so I do not really understand then why the error `Chain ID mismatch` pops up

**Comment by satoshiotomakan** [comment]
@artemki2077 thank you for providing the payloads.
@gastonm5 could you please take a look if the problem is related to the DApp adapter?

**Comment by artemki2077** [comment]
as I understood, maybe I'm wrong that because of the provider, the library cannot get the nonce and name for the permit, I implemented on the backend via web3py to receive this data, and rewrote the library a little, then everything worked

**Comment by wilsommary676** [comment]
I tried investing in Cryptocurrency Via a trading Platform, I studied the platform and invested some money in it and I was advised to deposit more to be able to receive some additional profits, The honest truth is that I would never do cryptocurrency, but due to how it profitable and lost if stuff I thought I could earn from it as well, I deposited all I had and it all turned from something exciting to something Heartbreaking I was denied access to my money, I couldn’t withdraw they took everything I had just in a blink of an eye,I then later Found out it possible to get what you lost via crypto and in assets too back. I then search on how i could take the step of getting what they took from me back and then I found Market peace recovery they are an Elite Funds recovery company and they got me out of the mess I was in, not just by recovering my money but they also recovered my assets. This is a Fund Recovery and Legal you can talk to them ease the pain you feeling and get everything you lost back. There is a way to get all what you lost back just talk to Quest Finance For Help and Guidance. Email on Jeffsilbert 39 gmail com

**Comment by Milerius** [comment]
This issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
