### ISSUE TITLE
iOS Trust Wallet App

### ISSUE THREAD

**Issue by camicasii** [trustwallet/wallet-core#3747]
I want to report an issue with the TrustWallet application for iOS. After a thorough analysis, I identified that the issue lies in the native RPCs provided by the app. These RPCs do not allow reading data from smart contracts, and when calculating gas for transactions, they do so below the network's minimums, resulting in failed transactions.

To address the data reading issue, I've had to switch RPCs. However, this entails additional effort due to the numerous web pages I manage that rely on this application. It's worth noting that users prefer using TrustWallet.

Please, I urge you to correct this issue as soon as possible.

https://21billiondollars.com/

**Comment by camicasii** [comment]
This issue occurs to me while using the following versions:

React 17-18
Next.js 13-15
ethers.js 5.7 and 6.11

**Comment by camicasii** [comment]
To address this issue, I attempted to utilize ethers.js 5.7 with a Web3Provider as follows:

`
const provider = new ethers.providers.Web3Provider(window.ethereum, "any");`
`const signer = provider.getSigner();`
`const contract = new ethers.Contract(address, ABI, signer) 
`

However, all function calls made using this approach resulted in failures.

I managed to resolve the issue by switching to a JsonRpcProvider:

` 
const provider = new ethers.providers.JsonRpcProvider("https://bsc-dataseed1.bnbchain.org", "any");`
`const signer = new ethers.VoidSigner(<user address>, provider);`
`

This modification allowed me to successfully interact with smart contracts and execute transactions without errors.

Using ethers 6 the error persists, but it only happens on iPhone, iPad and Mac

**Comment by camicasii** [comment]
I'm encountering a specific issue with TrustWallet where I can only successfully execute transactions by increasing the gas limit and gas price. This issue persists across BSC, Poligon, and OPbnb networks.

I would appreciate your assistance in resolving this matter as soon as possible.

**Comment by satoshiotomakan** [comment]
Hi @camicasii, thank you for opening the issue!
Our team is working on it, I'll give an update as soon as possible

**Comment by vcoolish** [comment]
> I'm encountering a specific issue with TrustWallet where I can only successfully execute transactions by increasing the gas limit and gas price. This issue persists across BSC, Poligon, and OPbnb networks.
> 
> I would appreciate your assistance in resolving this matter as soon as possible.

Hi, I can leave the fees empty, we will calculate it properly for you

**Comment by Milerius** [comment]
This issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
