### ISSUE TITLE
Remove or Skip signature verify in solana compiler

### ISSUE THREAD

**Issue by damian-zhao** [trustwallet/wallet-core#3749]
So far I can not find a way to simulateTransaction in SolanaFeeService.kt, because rpc server doesn't accept an unsigned tx, and we can not access the private key in calculateFee() method, so I have the idea of compile the signingInput and a faked signature, and simulate with the compiled result.
Here is the sample code:
```
        val signingInput = solanaSignService.buildSigningInput(
            transaction = transaction,
            fee = getDefaultFee(transaction),
            nonce = BigInteger.ZERO,
            privateKey = null
        ).firstOutput()
        val signatures = listOf("edb5a6193a797ac058fea943480b40617ed1fe442f84c648165ea5a99df2a8b6c4bb1c625569a9bd81619e89c0bb6103098303231274665675cfd25c1e129705")
        val pubKeys = listOf(Base58.decodeNoCheck(transaction.asset.account.address)!!.hex())
        val compiledByteArray = transactionCompilerService.compileWithSignatures(CoinType.Solana, signingInput.encode(), signatures, pubKeys)
        val signingOutput = SigningOutput.ADAPTER.decode(compiledByteArray)
        print(signingOutput)
        val result = rpcClient.simulateTransaction(signingOutput.encoded)
```

To do this, we have to skip the signature verify logic in wallet core:
https://github.com/trustwallet/wallet-core/blob/master/rust/chains/tw_solana/src/compiler.rs#L89

I also noticed for some other chains, they don't verify in compile.rs. So I wonder, if we can remove the verify logic for solana.

**Comment by satoshiotomakan** [comment]
Hi @damian-zhao, could you please describe the reason why should we remove signature verifying on `TransactionCompiler.compile`?

Did you encourage a problem after the recent Solana refactoring https://github.com/trustwallet/wallet-core/pull/3691?
As I can see, we always performed the signature validation:
https://github.com/trustwallet/wallet-core/blob/b530432921d7a9709428b0162673e0ab72de1c3d/src/Solana/Signer.cpp#L520-L522

**Comment by damian-zhao** [comment]
Hi @satoshiotomakan , I updated the issue description. Pls check, thanks!

**Comment by satoshiotomakan** [comment]
Hi @ar-g, could you please advice, how do you estimate transaction fee for an unsigned Solana transaction? I remember we even added a corresponding property to the `SigningOutput`

**Comment by ar-g** [comment]
@damian-zhao what kind of transaction you want to sign? we do have a method `calculateFee(message: String, messageEncoding: MessageEncoding)` to estimate fee for message it uses `getFeeForMessage` rpc call under the hood

**Comment by ar-g** [comment]
Can you give more context why do you need it and what are you trying to achieve?

**Comment by damian-zhao** [comment]
@ar-g  Hi, I want to optimize gas fee for `calculateFee(transaction: Transaction)`, I want to set a higher priority price and a lower priority limit. Because default gas limit is 200000, which is too high, so I want to simulate transaction and get the `gasUsed`. 

The problem of `getFeeForMessage`is, it uses the default gas limit(200000) to calculate the total fee. So it doesn't help us reduce the gas limit and the total gas fee.

**Comment by satoshiotomakan** [comment]
I have one suggestion @damian-zhao - how about checking if the provided signature is "zero" (consists of 64 zeros), and then do not validate it? So then we still verify the signatures, and at the same time allow the users to compile a transaction with dummy signatures.
Could you please open a PR? It should be straightforward to either remove these 3 lines of code
https://github.com/trustwallet/wallet-core/blob/c4ffde3d170821fd0c5c50512505222c59e47db7/rust/chains/tw_solana/src/compiler.rs#L89-L91
or just add one if statement

**Comment by damian-zhao** [comment]
Hi @ar-g , good idea! Let me try if 64 zeros works.

**Comment by damian-zhao** [comment]
Hi @ar-g , PR created, pls review, thanks.

https://github.com/trustwallet/wallet-core/pull/3754
