### ISSUE TITLE
Binance import keystore is crashing

### ISSUE THREAD

**Issue by leoneparise** [trustwallet/wallet-core#377]
## Expected Behavior

Should import the wallet

## Current Behavior

Crashing the app with the message:
```
Assertion failed: (m_value.object->find(key) != m_value.object->end()), function operator[], file /Users/leone/Development/Workspaces/TrustWallet/private-trust-wallet-ios/Pods/TrustWalletCore/build/local/include/nlohmann/json.hpp, line 3331.
```

## Steps to Reproduce (for bugs)

```
1. Create a wallet on https://www.binance.org/en/ and download the keystore
2. Run the TrustWallet app on branch: import-account-wallets#1088
3. Try to import the binance keystore
```

### Wallet
Keystore
```json
{
    "version": 1,
    "id": "276aa85c-170a-4fbb-9467-98a26d53631b",
    "crypto": {
        "ciphertext": "73c8b7b66a8117e168c37262a663fc00fc53eb688a78b1a5a6919e1b62ba22dc",
        "cipherparams": {
            "iv": "0bf37d61ea16f1dca9465f6fcb2c1cb7"
        },
        "cipher": "aes-256-ctr",
        "kdf": "pbkdf2",
        "kdfparams": {
            "dklen": 32,
            "salt": "24abdd39ac85aa28b837e5bb8ad97c6e3899337d95d82136859f562f94bc509c",
            "c": 262144,
            "prf": "hmac-sha256"
        },
        "mac": "38ad20f36289b6a36c0bb53dc318726d051a153ff07985f512be9c9bd12891be53ea1cf6cce70e5bbada64b0b00ec55054d726f6553b66041934b3a54478551f"
    }
}
```
Password:
```
Binance#2019
```
Private key:
```
000dfebbbbceff3ed46102124e66fde244751c163f4da61701ea2e79b9f410a5
```
Public key:
```
bnb16waaqfealxdtfrne7gqfkc4895vs0hvzq60t8g
```

**Comment by alejandro-isaza** [comment]
We need to add support for PBKDF2

**Comment by alejandro-isaza** [comment]
@leoneparise are you sure about that password? I got it to pass with the test vectors [here](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition) but not with this file.

**Comment by leoneparise** [comment]
Yes @alejandro-isaza, the password is correct. You can unlock the wallet on binance.org.

**Comment by hewigovens** [comment]
Is this one fixed? @leoneparise @alejandro-isaza

**Comment by alejandro-isaza** [comment]
No. Added support for PBKDF2 but the file still does not import. Looks like something is wrong on their side.

**Comment by PeterCore** [comment]
binance keyStore mac is 64bit , Added support for PBKDF2 but the file still does not import，but keccak256 is 32 bit

**Comment by PeterCore** [comment]
@hewigovens @alejandro-isaza 
1.PBKDF2 generate drivedKeys 
let drivedKeys  =  try! PKCS5.PBKDF2(password: passwordData.bytes, salt: Array(salt!.bytes), iterations: c, keyLength: keyLength, variant: .sha256).calculate()
            derivedKey = Data(bytes: drivedKeys)
2. "aes-256-ctr" generate priavteKey
 let decryptionKey = derivedKey[0...31]
                let aesCipher = try AES(key: decryptionKey.bytes, blockMode: CTR(iv: IV!.bytes), padding: .noPadding)
                decryptedPK = try aesCipher.decrypt(cipherText.bytes)
            let priavteKey =  Data(bytes: decryptedPK).toHexString()

**Comment by PeterCore** [comment]
@leoneparise

**Comment by hewigovens** [comment]
@PeterCore Hi can you open a pr to fix this? Thanks!

**Comment by PeterCore** [comment]
@hewigovens     
public func decrypt(password: String) throws -> Data {
        let derivedKey: Data
        switch crypto.kdf {
        case "scrypt":
            let scrypt = Scrypt(params: crypto.kdfParams)
            derivedKey = try scrypt.calculate(password: password)
        case "pbkdf2":
            guard let passwordData = password.data(using: .utf8) else {
                throw DecryptError.invalidPassword
            }
             let derivedKeys = try PKCS5.PBKDF2(password: passwordData.bytes, salt: Array(crypto.kdfParams.salt.bytes), iterations: 262144, keyLength: crypto.kdfParams.desiredKeyLength, variant: .sha256).calculate()
             derivedKey = Data(bytes: derivedKeys)
            
        default:
            throw DecryptError.unsupportedKDF
        }
        
        var variant: SHA3.Variant = .keccak256
        if crypto.cipher == "aes-256-ctr" { //binance
            variant = .keccak512
        }
        
        let mac = KeystoreKey.computeMAC(prefix: derivedKey[derivedKey.count - 16 ..< derivedKey.count], key: crypto.cipherText, variant)
        if mac != crypto.mac {
            throw DecryptError.invalidPassword
        }

        let decryptedPK: [UInt8]
        switch crypto.cipher {
        case "aes-128-ctr":
            let decryptionKey = derivedKey[0...15]
            let aesCipher = try AES(key: decryptionKey.bytes, blockMode: CTR(iv: crypto.cipherParams.iv.bytes), padding: .noPadding)
            decryptedPK = try aesCipher.decrypt(crypto.cipherText.bytes)
        case "aes-128-cbc":
            let decryptionKey = derivedKey[0...15]
            let aesCipher = try AES(key: decryptionKey.bytes, blockMode: CBC(iv: crypto.cipherParams.iv.bytes), padding: .noPadding)
            decryptedPK = try aesCipher.decrypt(crypto.cipherText.bytes)
        case "aes-256-ctr":
            let decryptionKey = derivedKey[0...31]
            let aesCipher = try AES(key: decryptionKey.bytes, blockMode: CBC(iv: crypto.cipherParams.iv.bytes), padding: .noPadding)
            decryptedPK = try aesCipher.decrypt(crypto.cipherText.bytes)
        default:
            throw DecryptError.unsupportedCipher
        }

        return Data(bytes: decryptedPK)
    }

**Comment by leoneparise** [comment]
Ok @hewigovens, I'll do today.

**Comment by vikmeup** [comment]
let's close this for now
