### ISSUE TITLE
Support for Custom Derivation Path

### ISSUE THREAD

**Issue by kaumudpa** [trustwallet/wallet-core#3774]
# Feature Request: Support for Custom Derivation Paths in Trust Wallet

## Is your feature request related to a problem? Please describe.

Many Trust Wallet users rely on Hierarchical Deterministic (HD) wallets for managing their cryptocurrency holdings across various blockchains. A significant limitation of Trust Wallet is the inability to specify custom derivation paths when importing existing wallets from mnemonic phrases. This forces users to migrate to less secure or less convenient wallets that offer customizable derivation paths, particularly when accessing addresses generated from non-standard derivation paths.

## Describe the solution you'd like

Implement a feature to allow users to input custom derivation paths during the wallet import process. Ideally, the following scenarios should be supported:

- **Importing an existing HD Wallet:** Provide direct input fields for customizing the derivation path when importing using a mnemonic phrase.
- **Creating a New HD Wallet (if applicable):** Offer advanced options when creating a new multi-coin wallet to allow users to specify custom derivation paths.

## Describe alternatives you've considered

Currently, users requiring custom derivation paths are forced to use alternative wallets:

- **Other software wallets:** Some wallets like Exodus and Coinomi provide limited custom derivation path support, but introduce increased security risks compared to Trust Wallet.
- **Hardware Wallets:** Using Ledger or Trezor offers the most security and control over derivation paths, but adds hardware costs and less convenience for frequent transactions.

## Checklist

- [ ] UI Changes: Design a user-friendly interface to input custom derivation paths, potentially with presets for common paths to help guide users.
- [ ] Wallet Import Logic: Update the wallet import process to accept and utilize a custom derivation path.
- [ ] Wallet Generation Logic (if applicable): Update the wallet generation functionality to incorporate custom derivation path options.
- [ ] Documentation: Update the Trust Wallet documentation to clearly explain the custom derivation path feature and provide usage examples.

## Resources

- BIP 32 (Hierarchical Deterministic Wallets): [https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)
- BIP 44 (Multi-Account Hierarchy for Deterministic Wallets): [https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)

## Additional context

Adding custom derivation path support would make Trust Wallet a more versatile and powerful solution for advanced cryptocurrency users and developers, improving convenience and compatibility without sacrificing the established security Trust Wallet offers.

**Comment by satoshiotomakan** [comment]
Hi @kaumudpa, this issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
