### ISSUE TITLE
ETH wallet bug affecting the Android App

### ISSUE THREAD

**Issue by Sami32** [trustwallet/wallet-core#3787]
**Describe the bug**
ETH wallet is not updated, the data do not show up anymore so no way to unstake with Trust wallet (tested with versions 8.11 to 8.12.2)

**To Reproduce**
Open Trust Wallet and select the ETH wallet with ongoing staking and click on "Native staking".
Android 7.0 MIUI 11 (Xiaomi)

**Expected behavior**
ETH wallet get updated, data showed and unstaking possible.

**Screenshots**
![IMG_20240410_201536](https://github.com/trustwallet/wallet-core/assets/18471069/163af54f-6647-4a19-8d8e-a86477143a72)
![IMG_20240410_203553](https://github.com/trustwallet/wallet-core/assets/18471069/aede6af6-ad21-4cdb-9904-5203027ede21)

**Additional context**
Re-installing your wallet or cleaning all the App data "fix" this issue for few minutes (importing an existing multicoins wallet).
With or without VPN didn't changed this issue.
It happened to briefly show the informations fine some very rare times but i wasn't able to understand what could have triggered it.

Since your Android wallet is not open source, feel free to relay this issue to the App team.
Thanks

**Comment by satoshiotomakan** [comment]
Hi @Sami32, this issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
