### ISSUE TITLE
Sol prv

### ISSUE THREAD

**Issue by windswrold** [trustwallet/wallet-core#3790]
Using the same mnemonic phrase and okx web3 wallet, the addresses taken out are different, and the private key lengths are also different.

memo : know fresh kid distance swap upset ramp capable mask donor walnut sentence

okx prv :1cbA28aaabRshcg8YF85ARSXgC5G9W1B9MPgooGgQVzbTyMGcK95fbCrViugLWFbKEASWA5yrpkn86RWjLgJH6b
okx adds: 12j1biq4aqN7CpH9jamuRjd562yRgNxitpy1uPv4WxG3

**Comment by ameerrah** [comment]
Contact the Defi support page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/)

**Comment by satoshiotomakan** [comment]
Hi @windswrold, thank you for the question.
In general, we use the `m/44'/501'/0'` derivation path different from the `m/44'/501'/0'/0'` standard Solana and OKX wallets.
However, we support the standard derivation path. In WalletCore, you can use `TWDerivationSolanaSolana` derivation type when deriving an address:
```c++
    const auto mnemonic = "know fresh kid distance swap upset ramp capable mask donor walnut sentence";
    const auto passphrase = "";
    const auto coin = TWCoinTypeSolana;
    HDWallet wallet = HDWallet(mnemonic, passphrase);

    const auto privKey = wallet.getKey(coin, TWDerivationSolanaSolana);
    const auto pubKey = privKey.getPublicKey(TWPublicKeyTypeEd25519);
    EXPECT_EQ(Solana::Address(pubKey).string(), "12j1biq4aqN7CpH9jamuRjd562yRgNxitpy1uPv4WxG3");
```

In TrustWallet app, we check balance of both `m/44'/501'/0'/0'` and `m/44'/501'/0'` accounts when creating/importing a wallet, and enable the account that is not empty (has transaction history).
