### ISSUE TITLE
Solana transactions is stacked in the pending status forever

### ISSUE THREAD

**Issue by spooky-finn** [trustwallet/wallet-core#3791]
**Issue Summary:**

I encountered an issue when attempting to send SOL tokens multiple times using the Trust Wallet. The transactions get stuck in a pending status indefinitely, preventing them from being completed.

**Observations:**

This issue appears to be specific to the Trust Wallet, as transactions work fine when using the Solflare wallet.
Other users have reported experiencing the same problem.
https://community.trustwallet.com/t/can-t-withdraw-my-usdt-sol-why-i-have-all-in-order/952516/25

**Expected Behavior:**

Transactions should be processed successfully when initiated from the Trust Wallet, similar to the behavior observed with the Solflare wallet.

**Steps to Reproduce:**

Attempt to send SOL tokens multiple times using the Trust Wallet.
Observe that the transactions get stuck in a pending status.

**Additional Information:**

Trust Wallet version: 11.2 (967)
Operating System: IOS 17.4.1

**Comment by Milerius** [comment]
This issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
