### ISSUE TITLE
Hot to transfer usdt on Sol

### ISSUE THREAD

**Issue by deeryoona** [trustwallet/wallet-core#3792]
let tokenTransferMessage = SolanaTokenTransfer.with {
            $0.tokenMintAddress = "SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt"
            $0.senderTokenAddress = "EDNd1ycsydWYwVmrYZvqYazFqwk1QjBgAUKFjBoz1jKP"
            $0.recipientTokenAddress = "3WUX9wASxyScbA7brDipioKfXS1XEYkQ4vo3Kej9bKei"
            $0.amount = 4000  // 0.004
            $0.decimals = 6
        }
        let input = SolanaSigningInput.with {
            $0.tokenTransferTransaction = tokenTransferMessage
            $0.recentBlockhash = "CNaHfvqePgGYMvtYi9RuUdVxDYttr1zs4TWrTXYabxZi"
            $0.privateKey = Data(Base58.decodeNoCheck( string: "9YtuoD4sH4h88CVM8DSnkfoAaLY7YeGC2TarDJ8eyMS5")!)
        }

        let output: SolanaSigningOutput = AnySigner.sign(input: input, coin: .solana)
when i user sol rpc sendTransaction
return error:
{
    code = "-32002";
    data =     {
        accounts = "<null>";
        err =         {
            InstructionError =             (
                0,
                InvalidAccountData
            );
        };
        logs =         (
            "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1]",
            "Program log: Instruction: TransferChecked",
            "Program log: Error: InvalidAccountData",
            "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 1357 of 200000 compute units",
            "Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction"
        );
        returnData = "<null>";
        unitsConsumed = 0;
    };
    message = "Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction";
}

**Comment by satoshiotomakan** [comment]
Hi @deeryoona, `EDNd1ycsydWYwVmrYZvqYazFqwk1QjBgAUKFjBoz1jKP` account balance is 0 SRM. Did you try to transfer from a non-empty SRM account?

**Comment by deeryoona** [comment]
> Hi @deeryoona, `EDNd1ycsydWYwVmrYZvqYazFqwk1QjBgAUKFjBoz1jKP` account balance is 0 SRM. Did you try to transfer from a non-empty SRM account?

The code I wrote is from the example provided by Trust, and I followed that logic to make a transfer. It's throwing an error

**Comment by deeryoona** [comment]
> SRM account

what is the meaning of SRM account?

**Comment by satoshiotomakan** [comment]
In the example you sent above, you try to send 0.004 [Serum](https://explorer.solana.com/address/SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt) tokens from the Serum account https://explorer.solana.com/address/3WUX9wASxyScbA7brDipioKfXS1XEYkQ4vo3Kej9bKei, however the balance is 0.

Also just noticed that the owner of this [SRM address](https://explorer.solana.com/address/3WUX9wASxyScbA7brDipioKfXS1XEYkQ4vo3Kej9bKei) is [HBYC51YrGFAZ8rM7Sj8e9uqKggpSrDYrinQDZzvMtqQp](https://explorer.solana.com/address/HBYC51YrGFAZ8rM7Sj8e9uqKggpSrDYrinQDZzvMtqQp), however the private key you set belongs to the [B1iGmDJdvmxyUiYM8UEo2Uw2D58EmUrw4KyLYMmrhf8V](https://explorer.solana.com/address/B1iGmDJdvmxyUiYM8UEo2Uw2D58EmUrw4KyLYMmrhf8V) address.

Please use the corresponding private key and top up the SRM balance of the SRM account.
