### ISSUE TITLE
I cant find mg balance its. 0 !!

### ISSUE THREAD

**Issue by Ktt155** [trustwallet/wallet-core#3798]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Ktt155** [comment]
Itbjustbkeeps telling me download the app and inalready downloaded it twice and more

**Comment by Ktt155** [comment]
Cam you please help me find my money its bery important

**Comment by satoshiotomakan** [comment]
Hi @Ktt155, this issue is not related to the wallet core repository, please create a ticket to get help from the Customer Support team: https://support.trustwallet.com/en/support/tickets/new
