### ISSUE TITLE
Why is my balance 0 !

### ISSUE THREAD

**Issue by Ktt155** [trustwallet/wallet-core#3799]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Ktt155** [comment]
![image](https://github.com/trustwallet/wallet-core/assets/165494919/5c5326c6-76b6-43cf-bc10-cb13f743615b)]()![image](https://github.com/trustwallet/wallet-core/assets/165494919/d06c3584-ed4a-445d-b8ab-50d58219d99e)![image](https://github.com/trustwallet/wallet-core/assets/165494919/5b1ad33a-8d3f-4f07-8361-630e37d47f0b)

**Comment by ameerrah** [comment]
Contact the Defi support page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI SUPPORT](https://accessonlinedefiprotocol.web.app/)
