### ISSUE TITLE
Stacks (Bitcoin L2)

### ISSUE THREAD

**Issue by 10gic** [trustwallet/wallet-core#3808]
## Description

Name: [Stacks](https://www.stacks.co)

HD Derivation Scheme: BIP44 m/44'/5757'/0'/0/0

Symbol: STX

Documentation: https://docs.stacks.co

Reason: A leading Bitcoin L2, market cap rank 29 in [coingecko](https://www.coingecko.com/en/coins/stacks)

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by 10gic** [comment]
Hi @Milerius, Do you have any plans to support stacks?

**Comment by Milerius** [comment]
No for the moment @10gic
