### ISSUE TITLE
Sui ECDSA

### ISSUE THREAD

**Issue by enriquesouza** [trustwallet/wallet-core#3816]
I can see that the SUI Derivation path is: m/44'/784'/0'/0'/0', so it means it is Ed25519

Does WC also support ECDSA Secp256k1, Derivation path  ```m/54'/784'/0'/0'/0'```?

https://docs.sui.io/concepts/cryptography/transaction-auth/keys-addresses

**Comment by satoshiotomakan** [comment]
Hi @enriquesouza, we do not support secp256k1 and secp256p1 schemes for SUI blockchain yet

**Comment by enriquesouza** [comment]
> Hi @enriquesouza, we do not support secp256k1 and secp256p1 schemes for SUI blockchain yet

Thank you
