### ISSUE TITLE
Supporting TON Connect

### ISSUE THREAD

**Issue by kehiy** [trustwallet/wallet-core#3820]
**Is your feature request related to a problem? Please describe.**

I have NFT and tokens on my TON account in the trust wallet, but since there is no TON connect on the trust wallet they are kind of locked!

**Describe the solution you'd like**

Trust wallet can start supporting the TON Connect standard, which is defined here:

https://docs.ton.org/develop/dapps/ton-connect/wallet

**Describe alternatives you've considered**

I was thinking of sending them back to to keeper (even when it will be hard to manage all wallets) but as I said they are locked, no ton connect or NFT or jetton support on the trust wallet.

**Comment by Cognacy** [comment]
Are you able to resolve this error?

**Comment by satoshiotomakan** [comment]
Hi @kehiy, sorry that you can't transfer the NFTs back to the keeper.
We work on adding TON Connect support to Trust Wallet

This issue is not related to the wallet core repository, so I close it for now.
