### ISSUE TITLE
Not support BTC Taproot address or SegWit address?

### ISSUE THREAD

**Issue by Sunshineyg00** [trustwallet/wallet-core#3821]
**Describe the bug**
When using TWBitcoinAddressIsValidString to verify a correct BTC Taproot address or  a SegWit address, the return result is NO, which should be right.

**To Reproduce**
1. use the latest version TrustWalletCore (4.0.40)
2. try to verify a BTC Taproot address and a SegWit address:
    NSLog(@"--== btc: %d", TWBitcoinAddressIsValidString(TWStringCreateWithUTF8Bytes(@"bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq".UTF8String)));
    NSLog(@"--== btc: %d", TWBitcoinAddressIsValidString(TWStringCreateWithUTF8Bytes(@"bc1p5d7rjq7g6rdk2yhzks9smlaqtedr4dekq08ge8ztwac72sfr9rusxg3297".UTF8String)));
3. the results are both "NO"

**Expected behavior**
The results are both "YES" as these are valid addresses.

**Comment by satoshiotomakan** [comment]
Hi @Sunshineyg00, we're already working on this, thank you for noticing

**Comment by Sunshineyg00** [comment]
> Hi @Sunshineyg00, we're already working on this, thank you for noticing

Thank you for your reply and your tremendous effort!

**Comment by nftsupply** [comment]
whats the status on this? 

let taprootKey = wallet.getKey(coin: .bitcoin, derivationPath: "m/86\'/0\'/0\'/0/0")
let taprootAddress = btcCoin.deriveAddress(privateKey: taprootKey)
        
does not generate a valid taproot address

**Comment by satoshiotomakan** [comment]
Hi @nftsupply, @Sunshineyg00 we finished working on full BTC Rust migration, and P2TR address generation is coming soon. I'll give an update once it's ready for the production use

**Comment by ronaldoguedess** [comment]
> Hi @nftsupply, @Sunshineyg00 we finished working on full BTC Rust migration, and P2TR address generation is coming soon. I'll give an update once it's ready for the production use

Why migration Rust is necessary? the Main SKD is in Rush?
Amazing news!!

**Comment by satoshiotomakan** [comment]
An API to generate Taproot address has been added at https://github.com/trustwallet/wallet-core/pull/4074
