### ISSUE TITLE
Will TrustWalletCore support Privacy manifest files and Signatures?

### ISSUE THREAD

**Issue by Sunshineyg00** [trustwallet/wallet-core#3823]
Hi,

I noticed that TrustWalletCore may use some APIs listed below, which are required reason APIs:
st_blocks
fstat
lstat
mach_absolute_time
...

So TrustWalletCore may need to include a privacy manifest file that reports the API to satisfy the Apple requirement in https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

Thank you very much.

**Comment by satoshiotomakan** [comment]
Hi @Sunshineyg00, thank you for the note!
`mach_absolute_time` - will be removed when the next Protobuf C++ library will be available
Regarding the other APIs, I'll investigate what can be done
