### ISSUE TITLE
Interact with Smart Contracts is error on OpenSea or Joepegs

### ISSUE THREAD

**Issue by DucVanVu** [trustwallet/wallet-core#3829]
**Describe the bug**
I connect the wallet to the trust wallet then do "make offer" nft on opensea or joepeg and get the error "The task could not be completed. (Error TrustWalletConnect.WCError 1.)"

**Comment by satoshiotomakan** [comment]
Hi @DucVanVu, this issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
