### ISSUE TITLE
[Ethereum] Error in EthereumMessageSigner for hex messages

### ISSUE THREAD

**Issue by JaimeToca** [trustwallet/wallet-core#3831]
**Describe the bug**
Some dapps directly return message to sign as hexadecimal, when assembling the ethereum message, wallet core could check if it needs to be decoded or not, and do the formatting/size.

https://github.com/trustwallet/wallet-core/blob/406abe4b0649a74279b2e7b77a2b10d1bb61520c/rust/tw_evm/src/message/eip191.rs#L25

Logic could be something like:
```
if string.isHex() -> hex::decode(s)
else -> s.as_bytes()
``` 
**Problem**
If client tries to decode hex string and transform to string, wallet core returns **"invalid data when serializing a protocol buffer"**

`EthereumMessageSigner.signMessage(<PrivateKey>, <Message>)`

**To Reproduce**
 Message: "0xc0a96273d5c3fbe4d4000491f08daef9c17f88df846c1d6f57eb5f33c1fbd035"

**Comment by satoshiotomakan** [comment]
Hi @JaimeToca, thank you for the suggestion! I think we can do that. The only note is that we should check if the provided data contains expected "Ethereum Signed Message" EIP191 prefix, otherwise I think we shouldn't allow to sign such a message.
