### ISSUE TITLE
[Sui Sign Error] When i use sui sign transaction, i got null information

### ISSUE THREAD

**Issue by weixuefeng** [trustwallet/wallet-core#3843]
i use wallet core sign txBytes. i got empty. not unSignedTx, no signature, no debugString !

i got txBytes: `AAACAAgA4fUFAAAAAAAgDPEBaSJaJRETsxmNyB0VunIob3M1OoIS8DutEL0PCpkCAgABAQAAAQEDAAAAAAEBAIdFNNZpoeEtRVLQEfYM0lx46xschKfJ5EnfmtpnCHNFAQDUBmObgpOd26p42IT8ABXrYTxYmCTgdv/w2WaDAhhJwB7zBQAAAAAg/M0At5v4FrSuDsud8gentX4EIzGADgYCipczvtYS17qHRTTWaaHhLUVS0BH2DNJceOsbHISnyeRJ35raZwhzRe8CAAAAAAAACLEiAAAAAAAA`

and call 
```
    Sui.SigningInput input = Sui.SigningInput(
        privateKey: privateKeyHex.toUint8List(),
        signDirectMessage: Sui.SignDirect(unsignedTxMsg: txBytes));
    Sui.SigningOutput output = Sui.SigningOutput.fromBuffer(
        AnySigner.sign(input.writeToBuffer(), TWCoinType.TWCoinTypeSui)
            .toList());
```

then i got empty:

**Comment by satoshiotomakan** [comment]
Hi @weixuefeng, the problem should be with the Protobuf message you try to pass to the `AnySigner.sign` function, because I checked the txBytes, and it should be signed normally.
Could you please tell if the code worked before the last release?

**Comment by weixuefeng** [comment]
yes. before i merge tw_sui code, it works good.

**Comment by satoshiotomakan** [comment]
Could you please send me the encoded signing input **without private key**, I'll check what can be the problem.
Is it also possible you have local changes that may be the reason?

**Comment by satoshiotomakan** [comment]
Sorry, I meant `Sui.SigningInput.writeToBuffer().toHex()`
But please do not set `privateKeyHex` before sending the SigningInput encoded data

**Comment by weixuefeng** [comment]
yes. i had run the `./tools/generate-files` i'll check it later.

**Comment by weixuefeng** [comment]
> Sorry, I meant `Sui.SigningInput.writeToBuffer().toHex()` But please do not set `privateKeyHex` before sending the SigningInput encoded data

yes. if you have txBytes. you can got `Sui.SigningInput.writeToBuffer().toHex()`, i'll check it.

**Comment by satoshiotomakan** [comment]
Hi @weixuefeng, did you have a chance to check `Sui.SigningInput.writeToBuffer().toHex()`?

**Comment by weixuefeng** [comment]
`0x0a2077f7b65eec2bf69003ce7ce103d47e81d6229b302829475e4d0a375b370b124912a7020aa4024141414341416967686745414141414141414167646e4a5872634654514e563058302f64313549672b2b3143572f2b6b5170776d774d48485766327478436343416741424151414141514544414141414141454241417a7841576b695769555245374d5a6a636764466270794b47397a4e54714345764137725243394477715a41516e68683757754d436a483379354d674a4e71325a7475394d3933576a484d51396b3646595347374d5a584c495431427741414141416743514d5666675136563179515773554e5966712f6d476a315051344351324b5135366e66736f51786f53514d38514670496c6f6c45524f7a475933494852573663696876637a553667684c774f3630517651384b6d6534434141414141414141394b73694141414141414141`

@satoshiotomakan

**Comment by satoshiotomakan** [comment]
Thanks @weixuefeng, as I thought, this SigningInput was generated using the legacy Protobuf API.
> 0x0a2077f7b65eec2bf69003ce7ce103d47e81d6229b302829475e4d0a375b370b124912a7020aa4024141414341416967686745414141414141414167646e4a5872634654514e563058302f64313549672b2b3143572f2b6b5170776d774d48485766327478436343416741424151414141514544414141414141454241417a7841576b695769555245374d5a6a636764466270794b47397a4e54714345764137725243394477715a41516e68683757754d436a483379354d674a4e71325a7475394d3933576a484d51396b3646595347374d5a584c495431427741414141416743514d5666675136563179515773554e5966712f6d476a315051344351324b5135366e66736f51786f53514d38514670496c6f6c45524f7a475933494852573663696876637a553667684c774f3630517651384b6d6534434141414141414141394b73694141414141414141

We've updated indexes slightly: `SigningInput.sign_direct_message` had 2 index, now it's 3: https://github.com/trustwallet/wallet-core/pull/3769/files

Could you please try to clean the cache of the Android app, or even compile the entire object from scratch?

**Comment by weixuefeng** [comment]
got it!. thanks for your reply @satoshiotomakan
