### ISSUE TITLE
Please add Harmony EVM Node

### ISSUE THREAD

**Issue by BeycanDeveloper** [trustwallet/wallet-core#3850]
We have a pre-sale plugin where I get commissions from EVM networks. One of our clients pre-sold on the Harmony EVM network. We were able to see this with CoinStats, but it is not paired with the existing Harmony EVM in Trust Wallet. I would appreciate it if you could add the Harmony EVM Node. I have sent a ticketta about this before.

Name: Harmony https://docs.harmony.one/home/developers/getting-started

HD Derivation Scheme: https://github.com/FireStack-Lab/harmony-sdk-examples/blob/master/tutorial/README.md
Symbol: ONE
Documentation: https://docs.harmony.one/home/developers/getting-started
Reason: In desc

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by satoshiotomakan** [comment]
Hi @BeycanDeveloper, at the moment we do not add new blockchains into WalletCore without a positive decision from our Business Development team.
Please create a new ticket, a request to add the blockchain to Trust Wallet: https://support.trustwallet.com/en/support/tickets/new

**Comment by BeycanDeveloper** [comment]
I did already, but you guys not answer.

**Comment by satoshiotomakan** [comment]
@BeycanDeveloper, sorry to hear that
Please try to re-submit the ticket

**Comment by BeycanDeveloper** [comment]
@satoshiotomakan brother, I sent maybe three times.

**Comment by satoshiotomakan** [comment]
I'll escalate it to the CS team @BeycanDeveloper
