### ISSUE TITLE
It's not responding to WalletConnect transactions.

### ISSUE THREAD

**Issue by BeycanDeveloper** [trustwallet/wallet-core#3851]
**Describe the bug**
It's not responding to WalletConnect transactions.

**To Reproduce**
Establish a WalletConnect connection and try signing

https://web3modal-laboratory-v3.vercel.app/

**Expected behavior**
Have to give response

**Screenshots**
No have any response

**Comment by satoshiotomakan** [comment]
Hi @BeycanDeveloper, this issue is not related to the wallet core repository
https://github.com/trustwallet/wallet-core/issues/3850

**Comment by BeycanDeveloper** [comment]
@satoshiotomakan I know, I created it here because I couldn't create an issue in the WalletConnectSwift repo. Can you move it to the correct repo?

**Comment by BeycanDeveloper** [comment]
@satoshiotomakan btw this is not for Harmony, for Trust Wallet = EVM, Solana, Tron not give any response

**Comment by satoshiotomakan** [comment]
I see, thanks
Please submit a ticket with the bug description to https://support.trustwallet.com/en/support/tickets/new
