### ISSUE TITLE
AnySigner.plan Estimating Zero Fee for Small Transactions

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/wallet-core#3860]
I'm encountering an issue where users trying to send 0.0001 BTC are getting a zero fee estimate using AnySigner.plan with a fee rate of 100 Sat/vB. This seems to be related to the dust filter settings.

### Here's the relevant code snippet:

I'm facing issues when users try to send 0.0001 BTC, as it return 0 estimating fee usign `AnySigner.plan` with 100Sat/vb.

```kotlin
                    val input = Bitcoin.SigningInput.newBuilder().apply {
                        this.amount = amount       //1962973
                        if (maxAmount) {
                            this.useMaxAmount = true //auto-sweep
                        }
                        this.hashType = BitcoinSigHashType.ALL.value()
                        this.toAddress = addressToTss //Receiver ADDRESS (TO) MUST BE TSS
                        this.changeAddress = changeAddressLeftOver.ifEmpty { addressFrom } //LEFT OVER
                        this.byteFee = feePervByte.byteFee.toLong()
                        this.coinType = CoinType.BITCOIN.value()
                    }
```

### **Questions:**
1 : When AnySigner.plan returns zero for all, does this indicate that the value is below the dust limit?
2 : How can I calculate the dust limit to inform users before calling `AnySigner.plan`.?
3 : Do you think it's valid to use `disableDustFilter = true`? I tested this configuration with AnySigner.plan and managed to get the estimated fee, as well as successfully send the transaction. I'm considering keeping disableDustFilter enabled and adding a manual minimum limit, like 0.00001 BTC, following Trust Wallet. What do you think of this approach?

### **Additional Context:**
Amount to send: 0.0001 BTC
Fee Rate: 100 Sat/vB
Total Balance: tBTC: 0.016012

**Comment by satoshiotomakan** [comment]
Hi @ronaldoguedess, dust filter was improved at https://github.com/trustwallet/wallet-core/pull/3675
So first of all, you should set a proper `SigningInput.dust_policy` to `fixed_dust_threshold = 1000` or `fixed_dust_threshold = 546` (in case of P2PKH, P2WPKH transfers). Otherwise, we use a legacy high dust threshold.
More info on dust thresholds at https://bitcoin.stackexchange.com/questions/10986/what-is-meant-by-bitcoin-dust

Regarding `disableDustFilter`, I don't recommend to use it.

Please let me know if it solves the issue

**Comment by ronaldoguedess** [comment]
Hi @satoshiotomakan 

I removed `disableDustFilter`, thanks.


Can I use like this? Will this set up the dust limit to 0.00001 BTC?

```kotlin
val input = Bitcoin.SigningInput.newBuilder().apply {
    this.amount = amount
    if (maxAmount) {
        this.useMaxAmount = true //auto-sweep
    }
    this.hashType = BitcoinSigHashType.ALL.value()
    this.toAddress = addressTo //receiver
    this.changeAddress = changeAddressLeftOver.ifEmpty { addressFrom } //LEFT OVER
    this.byteFee = feePervByte.byteFee.toLong()
    this.coinType = CoinType.BITCOIN.value()
    this.dustPolicyCase //do i need to set it?
    this.fixedDustThreshold = 1000 // or 546 for P2PKH, P2WPKH transfers

}```

**Comment by satoshiotomakan** [comment]
@ronaldoguedess yes
