### ISSUE TITLE
Importing TON Wallet with Seed Phrase: Issues with Wallet Core

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/wallet-core#3871]
I've encountered an issue while trying to import a TON wallet using the seed phrase. The Wallet core is indicating that the seed phrase is incorrect, although I've generated it according to standard procedures.

I noticed that there's no sample available for importing from a Seed Phrase in the existing documentation for the Trust Wallet core. You can find the documentation here: [link to the documentation](https://github.com/trustwallet/wallet-core/blob/master/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/theopennetwork/TestTheOpenNetworkAddress.kt)

Could there be something different about TON seed phrases that I'm missing? I'd appreciate any insights or guidance on how to properly import a TON wallet using the seed phrase.

Thank you for your help!

**Comment by satoshiotomakan** [comment]
Hi @ronaldoguedess, we do not plan to support TON mnemonic passphrase at the moment
Ref: https://github.com/trustwallet/wallet-core/issues/3188
