### ISSUE TITLE
Trust Wallet integration bug

### ISSUE THREAD

**Issue by forbesus** [trustwallet/wallet-core#3872]
**Describe the bug**
I am integrating trust wallet to my dapp using mobile.  
I am getting error when I send token for swap

**To Reproduce**
In my dapp, I have to connect trust wallet and swap token A to token B.
Connecting wallet is working well, but I can't get approve sign on trust mobile wallet.
Integrating with extension is working perfectly, but integrating mobile wallet is not working well.

**Expected behavior**
I wanna get approve confirmation

**Screenshots**

**Additional context**

**Comment by satoshiotomakan** [comment]
Hi @forbesus, this issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
