### ISSUE TITLE
How to transfer Solana NFT by swift,i am an ios developer

### ISSUE THREAD

**Issue by deeryoona** [trustwallet/wallet-core#3875]
How to transfer Solana NFT by swift,i am an ios developer
i can not find an example  in swift/tests/blockchans/solanatests folder

**Comment by satoshiotomakan** [comment]
Hi @deeryoona, please create a discussion next time when you have a question as the issues are for the bugs or feature requests.
NFT transfer can be created via the same `Solana.Proto.CreateAndTransferToken` with amount equal to 1 and decimals to 0:
See an example here https://www.helius.dev/blog/solana-dev-101-how-to-transfer-solana-tokens-with-typescript
