### ISSUE TITLE
invalid ELF header in javascript library

### ISSUE THREAD

**Issue by rohitshukla11** [TrustWallet/wallet-core#388]
![Screenshot from 2019-04-30 16-01-22](https://user-images.githubusercontent.com/20769944/56956243-3c595d00-6b61-11e9-8c29-a7c055317d15.png)

**Comment by BSathvik** [comment]
Only macOS is supported at the moment. I will be adding support for Linux is the near future.

**Comment by rohitshukla11** [comment]
Okay, thanks for the support.

**Comment by dvlpr-n** [comment]
No support for Linux yet? I have also this issue
