### ISSUE TITLE
Swap TON to USDT using Trust Wallet Core Library

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/wallet-core#3883]
I'm looking to perform a swap from TON (The Open Network) to USDT using the Trust Wallet Core library. I have an API that provides the quote, so I just need to assemble the transaction, adding the router and the destination token.

Is this library ready for a swap? Can anyone help me modify this code for a swap?

Here's the existing code for a basic transfer:

```kotlin
  val privateKey = PrivateKey("c38f49de2fb13223a9e7d37d5d0ffbdd89a5eb7c8b0ee4d1c299f2cefe7dc4a0".toHexByteArray())

        val transfer = TheOpenNetwork.Transfer.newBuilder()
            .setWalletVersion(TheOpenNetwork.WalletVersion.WALLET_V4_R2)
            .setDest("EQBm--PFwDv1yCeS-QTJ-L8oiUpqo9IT1BwgVptlSq3ts90Q")
            .setAmount(10)
            .setSequenceNumber(6)
            .setMode(TheOpenNetwork.SendMode.PAY_FEES_SEPARATELY_VALUE or TheOpenNetwork.SendMode.IGNORE_ACTION_PHASE_ERRORS_VALUE)
            .setExpireAt(1671132440)
            .setBounceable(true)
            .build()

        val input = TheOpenNetwork.SigningInput.newBuilder()
            .setTransfer(transfer)
            .setPrivateKey(ByteString.copyFrom(privateKey.data()))
            .build()

        val output = AnySigner.sign(input, CoinType.TON, SigningOutput.parser())

        // tx: https://tonscan.org/tx/3Z4tHpXNLyprecgu5aTQHWtY7dpHXEoo11MAX61Xyg0=
        val expectedString = "te6ccgICAAQAAQAAALAAAAFFiAGwt/q8k4SrjbFbQCjJZfQr64ExRxcUMsWqaQODqTUijgwAAQGcEUPkil2aZ4s8KKparSep/OKHMC8vuXafFbW2HGp/9AcTRv0J5T4dwyW1G0JpHw+g5Ov6QI3Xo0O9RFr3KidICimpoxdjm3UYAAAABgADAAIBYmIAM33x4uAd+uQTyXyCZPxflESlNVHpCeoOECtNsqVW9tmIUAAAAAAAAAAAAAAAAAEAAwAA"

```
Any assistance in modifying this code for performing a swap would be greatly appreciated!

Btw, this is the api to provide quotes for swap, pools etc:
https://api.ston.fi/swagger-ui/

**Comment by Milerius** [comment]
> I'm looking to perform a swap from TON (The Open Network) to USDT using the Trust Wallet Core library. I have an API that provides the quote, so I just need to assemble the transaction, adding the router and the destination token.
> 
> Is this library ready for a swap? Can anyone help me modify this code for a swap?
> 
> Here's the existing code for a basic transfer:
> 
> ```kotlin
>   val privateKey = PrivateKey("c38f49de2fb13223a9e7d37d5d0ffbdd89a5eb7c8b0ee4d1c299f2cefe7dc4a0".toHexByteArray())
> 
>         val transfer = TheOpenNetwork.Transfer.newBuilder()
>             .setWalletVersion(TheOpenNetwork.WalletVersion.WALLET_V4_R2)
>             .setDest("EQBm--PFwDv1yCeS-QTJ-L8oiUpqo9IT1BwgVptlSq3ts90Q")
>             .setAmount(10)
>             .setSequenceNumber(6)
>             .setMode(TheOpenNetwork.SendMode.PAY_FEES_SEPARATELY_VALUE or TheOpenNetwork.SendMode.IGNORE_ACTION_PHASE_ERRORS_VALUE)
>             .setExpireAt(1671132440)
>             .setBounceable(true)
>             .build()
> 
>         val input = TheOpenNetwork.SigningInput.newBuilder()
>             .setTransfer(transfer)
>             .setPrivateKey(ByteString.copyFrom(privateKey.data()))
>             .build()
> 
>         val output = AnySigner.sign(input, CoinType.TON, SigningOutput.parser())
> 
>         // tx: https://tonscan.org/tx/3Z4tHpXNLyprecgu5aTQHWtY7dpHXEoo11MAX61Xyg0=
>         val expectedString = "te6ccgICAAQAAQAAALAAAAFFiAGwt/q8k4SrjbFbQCjJZfQr64ExRxcUMsWqaQODqTUijgwAAQGcEUPkil2aZ4s8KKparSep/OKHMC8vuXafFbW2HGp/9AcTRv0J5T4dwyW1G0JpHw+g5Ov6QI3Xo0O9RFr3KidICimpoxdjm3UYAAAABgADAAIBYmIAM33x4uAd+uQTyXyCZPxflESlNVHpCeoOECtNsqVW9tmIUAAAAAAAAAAAAAAAAAEAAwAA"
> ```
> 
> Any assistance in modifying this code for performing a swap would be greatly appreciated!
> 
> Btw, this is the api to provide quotes for swap, pools etc: https://api.ston.fi/swagger-ui/

Hello the library is not yet ready for swap.
