### ISSUE TITLE
[TON] Calculating Transaction Network Fees

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/wallet-core#3886]
I'm implementing TON (The Open Network) and using Trust Wallet Core to build TON transactions. However, I noticed that the network fee calculation is missing in the [sample code](https://github.com/trustwallet/wallet-core/blob/master/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/theopennetwork/TestTheOpenNetworkSigner.kt).

Is there a way to get the network fee for TON transactions similar as we can calculate fees using .plan for Bitcoin?
`AnySigner.sign(input, CoinType.TON, TheOpenNetwork.SigningOutput.parser())`

**Comment by JaimeToca** [comment]
Hi @ronaldoguedess 

After you sign, you can get "encoded" from SigningOutput and call

`/estimateFee` from node

https://toncenter.com/api/v2/#/send/estimate_fee_estimateFee_post

**Comment by ronaldoguedess** [comment]
So, there is no off-chain soluction to calc this fee like we have in bitcoin?

I tested this api and it provide me it... can I considere just this field? `"gas_fee": 155200,`
```
{
  "ok": true,
  "result": {
    "@type": "query.fees",
    "source_fees": {
      "@type": "fees",
      "in_fwd_fee": 926400,
      "storage_fee": 11819211,
      "gas_fee": 155200,
      "fwd_fee": 0
    },
    "destination_fees": [],
    "@extra": "1717772010.2004683:12:0.7120622247973473"
  }
}
```

**Comment by Saintloxx** [comment]
[](url)

**Comment by JaimeToca** [comment]
> Hi @JaimeToca
> 
> So, there is no off-chain soluction to calc this fee like we have in bitcoin?
> 
> I tested this api and it provide me it... Can I considere just this field? `"gas_fee": 155200,` or should I considere the match of in_fwd_fee + storage_fee + gas_fee?
> 
> ```
> {
>   "ok": true,
>   "result": {
>     "@type": "query.fees",
>     "source_fees": {
>       "@type": "fees",
>       "in_fwd_fee": 926400,
>       "storage_fee": 11819211,
>       "gas_fee": 155200,
>       "fwd_fee": 0
>     },
>     "destination_fees": [],
>     "@extra": "1717772010.2004683:12:0.7120622247973473"
>   }
> }
> ```

Fees = in_fwd_fee + storage_fee + gas_fee + fwd_fee

In BTC you still need the price from the network. Not I am not aware of.

**Comment by ronaldoguedess** [comment]
Hey, is there something wrong with this?

I've successfully broadcasted my transaction, but the gas fee seems completely off.

Here's what the API shows me based on my [transaction](https://testnet.tonscan.org/tx/by-msg-hash/1q2p2RKOYeG5dTjp4ABAjh0FiowRZIy6xjpx3KJZ9NI=) and wallet address:

![image](https://github.com/trustwallet/wallet-core/assets/18597639/3d77ffdd-1c02-45de-a289-73ab02ccdfe0)

```
{
  "ok": true,
  "result": {
    "@type": "query.fees",
    "source_fees": {
      "@type": "fees",
      "in_fwd_fee": 987200,
      "storage_fee": 137,
      "gas_fee": 0,
      "fwd_fee": 0
    },
    "destination_fees": [],
    "@extra": "1718588867.165973:1:0.445657813246111"
  }
}
```
