### ISSUE TITLE
Cosmos gov send proposals

### ISSUE THREAD

**Issue by enriquesouza** [trustwallet/wallet-core#3895]
I am developing a feature using WC and I am trying to find a way to send proposals to cosmos (DYDX) more specifically. 

Therefore I could see we are able to vote. I am trying then to send via RAW JSON but it seems the operation isn't supported. 

Is there any way of doing that?

```
{
                "title": "\(title)",
                "deposit": "\(deposit)",
                "summary": "\(summary)",
                "messages": [
                    {
                        "@type": "/cosmos.gov.v1.MsgExecLegacyContent",
                        "content": {
                            "@type": "/cosmos.gov.v1beta1.TextProposal",
                            "title": "\(contentTitle)",
                            "description": "\(contentDescription)"
                        },
                        "authority": "\(authority)"
                    }
                ]
            }
```

**Comment by Milerius** [comment]
> I am developing a feature using WC and I am trying to find a way to send proposals to cosmos (DYDX) more specifically.
> 
> Therefore I could see we are able to vote. I am trying then to send via RAW JSON but it seems the operation isn't supported.
> 
> Is there any way of doing that?
> 
> ```
> {
>                 "title": "\(title)",
>                 "deposit": "\(deposit)",
>                 "summary": "\(summary)",
>                 "messages": [
>                     {
>                         "@type": "/cosmos.gov.v1.MsgExecLegacyContent",
>                         "content": {
>                             "@type": "/cosmos.gov.v1beta1.TextProposal",
>                             "title": "\(contentTitle)",
>                             "description": "\(contentDescription)"
>                         },
>                         "authority": "\(authority)"
>                     }
>                 ]
>             }
> ```

Hello u can use this proto message: https://github.com/trustwallet/wallet-core/blob/3e8484cb15a82a01ab88909c3e32732fe82a1818/src/proto/Cosmos.proto#L318

**Comment by Milerius** [comment]
and there is the unit test: https://github.com/trustwallet/wallet-core/blob/3e8484cb15a82a01ab88909c3e32732fe82a1818/tests/chains/Cosmos/SignerTests.cpp#L325

**Comment by enriquesouza** [comment]
hum... I can se we can vote, but I actually need to create the proposal to be voted. Is that possible?

**Comment by Milerius** [comment]
> hum... I can se we can vote, but I actually need to create the proposal to be voted. Is that possible?

as this we don't have it yet unfortunately, that's not something we are planning todo, but u can make a pull request!

**Comment by enriquesouza** [comment]
Is it possible to send it as a custom JSON? Actually I am trying but not working as well:

```
input.messages = [CosmosMessage.with {
                $0.rawJsonMessage = CosmosMessage.RawJSON.with {
                    $0.type = "/cosmos.gov.v1beta1.MsgSubmitProposal"
                    $0.value = proposalJSON
                }
            }]
            ```

**Comment by enriquesouza** [comment]
Ok, I will try to add it myself. Should I implement it in C++, rust. How is the right way? Both?

**Comment by satoshiotomakan** [comment]
Hi @enriquesouza, in order to add support for new Cosmos tx messages, you should add them in Rust first. Please take a look at an example:
https://github.com/trustwallet/wallet-core/blob/406abe4b0649a74279b2e7b77a2b10d1bb61520c/rust/tw_cosmos_sdk/src/transaction/message/cosmos_gov_message.rs

**Comment by enriquesouza** [comment]
@Milerius @satoshiotomakan do we have any way to send any message using JSON for cosmos?

**Comment by enriquesouza** [comment]
I will pr the new messages

**Comment by satoshiotomakan** [comment]
Hi @enriquesouza, consider using https://github.com/trustwallet/wallet-core/blob/37a5e6b35bac481339e11e52c173462e3a5cb140/src/proto/Cosmos.proto#L347
