### ISSUE TITLE
An error occurs when using Solana signature data on Android：Incorrect count of signatures passed to compile Context: 0. Expected '1' signatures, provided '2'

### ISSUE THREAD

**Issue by qq253682355** [trustwallet/wallet-core#3916]
val wallet = getSolanaWallet(mnemonic)
        val tx = Base58.decodeNoCheck(txData)

        val decodedData = TransactionDecoder.decode(CoinType.SOLANA, tx)
        val decodedOutput = Solana.DecodingTransactionOutput.parseFrom(decodedData)

        val rawTx = decodedOutput.transaction.toBuilder().apply {
            if (decodedOutput.transaction.hasV0()) {
                v0 = decodedOutput.transaction.v0.toBuilder().setRecentBlockhash(blockHash)
                    .build()
            } else {
                legacy = decodedOutput.transaction.legacy.toBuilder().setRecentBlockhash(blockHash)
                    .build()
            }
        }.build()

        val signingInput = Solana.SigningInput.newBuilder().apply {
            rawMessage = rawTx
            privateKey = ByteString.copyFrom(Base58.decodeNoCheck(wallet?.privateKey32))
        }.build()

        val output = AnySigner.sign(signingInput, CoinType.SOLANA, SigningOutput.parser())
        return output.encoded

**Comment by qq253682355** [comment]
Thank you everyone, I need help, I'm very frustrated right now, the same code works fine on iOS.

**Comment by qq253682355** [comment]
This is rawMessage：

`# wallet.core.jni.proto.Solana$RawMessage@4629acf5
signatures {
  pubkey: "7ZThUSETBJ58iuHCziUtb5vW79jCmpF6jG4ASc1YLb5G"
  signature: "4kvBTKWqxzEfUouo6G4ZhaC65dUDMDERbetz3fUdLXdvURiZtLpgoaFG2W1qzgvk6xGYhC87DKVz3cRLxB32WGPL"
}
v0 {
  account_keys: "7ZThUSETBJ58iuHCziUtb5vW79jCmpF6jG4ASc1YLb5G"
  account_keys: "H86jPWk3WkoKcAgLfC7WhCTTVEz7V8of5MQeuTDhqug9"
  account_keys: "6HXaFu5VhNJf42PkK68URhtUvajVjwoa4aNXLMgyXRR3"
  account_keys: "11111111111111111111111111111111"
  account_keys: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
  account_keys: "6EwaJTuvtUs1z6Le1yFh8HMx2EBBsuExa5ba53d7W1eJ"
  account_keys: "ComputeBudget111111111111111111111111111111"
  account_keys: "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
  account_keys: "6m2CDdhRgxpH4WjvdzxAYbGxwdGUz5MziiL5jek2kBma"
  address_table_lookups {
    account_key: "4jgg9CHLiTeQUwSDK9srby9Vp1NhDGqpdacWvUASGUwY"
    readonly_indexes: 2
    readonly_indexes: 22
    readonly_indexes: 15
    writable_indexes: 244
    writable_indexes: 39
    writable_indexes: 26
    writable_indexes: 251
    writable_indexes: 29
  }
  address_table_lookups {
    account_key: "69Ctch8q8SfrHEAYkt3kMXDezs36g6YMwFXnaEmFpUrC"
    writable_indexes: 16
    writable_indexes: 17
    writable_indexes: 18
    writable_indexes: 11
    writable_indexes: 12
    writable_indexes: 13
    writable_indexes: 14
    writable_indexes: 15
  }
  address_table_lookups {
    account_key: "HRgmoardqTNkwnGBeK8iDB8ZKoVRzqx6tjfGUjufW8SE"
    readonly_indexes: 0
    writable_indexes: 1
    writable_indexes: 2
    writable_indexes: 3
    writable_indexes: 7
    writable_indexes: 8
  }
  address_table_lookups {
    account_key: "3dRSy7KdrHFG8bjarahABwjAAScgXU6segTv1KPTCzm7"
    readonly_indexes: 68
  }
  header {
    num_readonly_unsigned_accounts: 6
    num_required_signatures: 1
  }
  instructions {
    program_data: "\003]Z\000\000\000\000\000\000"
    program_id: 6
  }
  instructions {
    program_data: "\002\260\f\a\000"
    program_id: 6
  }
  instructions {
    accounts: 0
    accounts: 1
    program_data: "\003\000\000\000av\345\016\361X\274V\374A\017\307\2274T\213\372\256\333\250\204\213\b\335oD`\376\315\3509\347\r\000\000\000\000\000\000\0001719108180805\360\035\037\000\000\000\000\000\245\000\000\000\000\000\000\000\006\335\366\341\327e\241\223\331\313\341F\316\353y\254\034\264\205\355_[7\221:\214\365\205~\377\000\251"
    program_id: 3
  }
  instructions {
    accounts: 1
    accounts: 10
    accounts: 0
    accounts: 27
    program_data: "\001"
    program_id: 4
  }
  instructions {
    accounts: 0
    accounts: 1
    program_data: "\002\000\000\000.\265\361\003\000\000\000\000"
    program_id: 3
  }
  instructions {
    accounts: 1
    program_data: "\021"
    program_id: 4
  }
  instructions {
    accounts: 0
    accounts: 2
    accounts: 0
    accounts: 13
    accounts: 3
    accounts: 4
    program_data: "\001"
    program_id: 7
  }
  instructions {
    accounts: 0
    accounts: 1
    accounts: 2
    accounts: 10
    accounts: 13
    accounts: 29
    accounts: 0
    accounts: 1
    accounts: 12
    accounts: 11
    accounts: 17
    accounts: 18
    accounts: 16
    accounts: 21
    accounts: 15
    accounts: 14
    accounts: 19
    accounts: 20
    accounts: 4
    accounts: 28
    accounts: 9
    accounts: 12
    accounts: 2
    accounts: 30
    accounts: 22
    accounts: 24
    accounts: 25
    accounts: 26
    accounts: 23
    accounts: 5
    accounts: 5
    accounts: 31
    accounts: 4
    program_data: "\370\306\236\221\341u\207\310.\265\361\003\000\000\000\000vL\210\000\000\000\000\000\222)\210\000\000\000\000\000\001\000\000\000.\265\361\003\000\000\000\000\001\000\000\000\002\000\000\000\001\000\000\000\006\001\000\000\000d\001\000\000\000\n\001\000\000\000d"
    program_id: 8
  }
  instructions {
    accounts: 1
    accounts: 0
    accounts: 0
    program_data: "\t"
    program_id: 4
  }
  recent_blockhash: "DhDqzBvxi3iAKd8VPbsd8FaRUNRfid1HNpyNq7xtLq7w"
}`

**Comment by qq253682355** [comment]
<img width="868" alt="image" src="https://github.com/trustwallet/wallet-core/assets/8443828/00ecd0d6-cc32-4457-99dc-0be7ee4ac2dc">

**Comment by aminsato** [comment]
@qq253682355 Could you please share how did you resolve the isse?, I'm encountering the same problem

**Comment by satoshiotomakan** [comment]
Hi @aminsato, do you have the same problem? Did you try to sign a raw transaction `Solana.Proto.RawMessage`, or one of the pre-defined message types in `Solana.Proto.SigningInput.transaction_type`?

**Comment by aminsato** [comment]
> Hi @aminsato, do you have the same problem? Did you try to sign a raw transaction `Solana.Proto.RawMessage`, or one of the pre-defined message types in `Solana.Proto.SigningInput.transaction_type`?

Exactly

**Comment by aminsato** [comment]
> > Hi @aminsato, do you have the same problem? Did you try to sign a raw transaction `Solana.Proto.RawMessage`, or one of the pre-defined message types in `Solana.Proto.SigningInput.transaction_type`?
> 
> Exactly
I get the error on the following lines
```
val compiledWithSignature =TransactionCompiler.compileWithSignatures(coinType, input, allSignatures, publicKeys)
val output = Solana.SigningOutput.parseFrom(compiledWithSignature)
if (!output.errorMessage.isNullOrEmpty()) {
    throw Exception(output.errorMessage)
}
```

**Comment by satoshiotomakan** [comment]
Could you please share how do you generate the `SigningInput`?

> > > Hi @aminsato, do you have the same problem? Did you try to sign a raw transaction `Solana.Proto.RawMessage`, or one of the pre-defined message types in `Solana.Proto.SigningInput.transaction_type`?
> > 
> > 
> > Exactly
> > I get the error on the following lines
> 
> ```
> val compiledWithSignature =TransactionCompiler.compileWithSignatures(coinType, input, allSignatures, publicKeys)
> val output = Solana.SigningOutput.parseFrom(compiledWithSignature)
> if (!output.errorMessage.isNullOrEmpty()) {
>     throw Exception(output.errorMessage)
> }
> ```

**Comment by aminsato** [comment]
> Could you please share how do you generate the `SigningInput`?
> 
> > > > Hi @aminsato, do you have the same problem? Did you try to sign a raw transaction `Solana.Proto.RawMessage`, or one of the pre-defined message types in `Solana.Proto.SigningInput.transaction_type`?
> > > 
> > > 
> > > Exactly
> > > I get the error on the following lines
> > 
> > 
> > ```
> > val compiledWithSignature =TransactionCompiler.compileWithSignatures(coinType, input, allSignatures, publicKeys)
> > val output = Solana.SigningOutput.parseFrom(compiledWithSignature)
> > if (!output.errorMessage.isNullOrEmpty()) {
> >     throw Exception(output.errorMessage)
> > }
> > ```

```
   val nonceAccount = Solana.CreateNonceAccount.newBuilder()
            .setNonceAccountPrivateKey(
                ByteString.copyFrom(
                    "017b9745062211b8ed330cf92ce0212a87c0ac68b16a9f02096198a77e3d424b".decodeHex()
                        .toByteArray()
                )
            )
            .setRent(100000)
            .build()


        var input =Solana.SigningInput.newBuilder()
            .setRecentBlockhash(solanaSpecific.recentBlockHash)
            .setCreateNonceAccount(nonceAccount)

            .setPrivateKey(
                ByteString.copyFrom(
                    "49aa18e396912a11d0736088db3fc72ea1070a6919e02ceaf5ebeb7b076eedc5"
                        .decodeHex()
                        .toByteArray()
            ))
            .setSender("49aa18e396912a11d0736088db3fc72ea1070a6919e02ceaf5ebeb7b076eedc5").build().toByteArray()
```

**Comment by satoshiotomakan** [comment]
@aminsato you need to provide 2 signatures into `TransactionCompiler.compile` function:
1. Signature gotten via signing the pre-image hash using `SigningInput.nonceAccountPrivateKey`
2. And signature gotten via signing the same pre-image hash using `SigningInput.privateKey`

Please move the funds out of these two wallets, as you've revealed the secrets publicly

**Comment by aminsato** [comment]
> @aminsato you need to provide 2 signatures into `TransactionCompiler.compile` function:
> 
> 1. Signature gotten via signing the pre-image hash using `SigningInput.nonceAccountPrivateKey`
> 2. And signature gotten via signing the same pre-image hash using `SigningInput.privateKey`
> 
> Please move the funds out of these two wallets, as you've revealed the secrets publicly

Thanks,
The private key was fake

Do you know how to sign a transaction using SigningInput.nonceAccountPrivateKey?

**Comment by satoshiotomakan** [comment]
@aminsato you need to get the transaction pre-image hash via `TransactionCompiler.preImageHashes(input)`, and then sign it using those two keys:
```kt
// Repeat the same for both keys
val data = Numeric.hexStringToByteArray("YOUR_PRIVATE_KEY_HEX")
var privateKey = PrivateKey(data)
// Pass the sig into `TransactionCompiler.compile()`
val signature = privateKey.sign(preImageHash, Curve.ED25519)
```

**Comment by aminsato** [comment]
@satoshiotomakan 
 I have another question.
The purpose of using a nonce account in a slow-signing multisig wallet is to avoid the blockhash not found error. I aim to use the nonce account to bypass the recent blockhash. However, despite this, I still encounter the error when signing the transaction slowly.

Here is my code 
```
 val input = Solana.SigningInput.newBuilder()
            .setNonceAccount(nonceAccount.nonceAccount)
            .setAdvanceNonceAccount(advanceNonceAccount)
            .setRecentBlockhash(solanaSpecific.recentBlockHash)
            .setSender(keysignPayload.coin.address)
            .setPriorityFeePrice(
                Solana.PriorityFeePrice.newBuilder()
                    .setPrice(PRIORITY_FEE_PRICE)
                    .build()
            )
            .setPriorityFeeLimit(
                Solana.PriorityFeeLimit.newBuilder()
                    .setLimit(PRIORITY_FEE_LIMIT)
                    .build()
            )

```
