### ISSUE TITLE
Can not find my token

### ISSUE THREAD

**Issue by Hakolacash** [trustwallet/wallet-core#3920]
My name is Rufai Hakeem,am one of Trust wallet user and been using for couple of year,I sent $85 token on Ton to a Trust wallet Toncoin address and to my surprised I was credited 0.0001 of Ton in my Trust wallet Ton,please For the sake God help out on this.here's the transaction details.From my Telegram Ton wallet and Trust wallet alert details

**Comment by DApps-Github** [comment]
> My name is Rufai Hakeem,am one of Trust wallet user and been using for couple of year,I sent $85 token on Ton to a Trust wallet Toncoin address and to my surprised I was credited 0.0001 of Ton in my Trust wallet Ton,please For the sake God help out on this.here's the transaction details.From my Telegram Ton wallet and Trust wallet alert details

Hey there @Hakolacash  !

kindly refresh your wallet, if the issue persists, It means the backend systems went down as a result of transcript error. 
Your query would be best dealt with by the support team.
 I’ll have to refer you to the official support live chat with the ticket ID XDC7463
 
Please see the link below to our dedicated support line: 
 [Trust wallet dApps Support Requests Ticket](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for further assistance.

**Comment by satoshiotomakan** [comment]
Hi @Hakolacash, please contact the support team of the TON wallet from which you have sent funds.
Please also try to create a ticket here: https://support.trustwallet.com/en/support/tickets/new

I'll close the ticket since this issue is not related to the wallet core repository,
