### ISSUE TITLE
Is there any way to unify the "series chain"? don't add registry.json

### ISSUE THREAD

**Issue by weixuefeng** [trustwallet/wallet-core#3924]
Is there any way to unify the "series chain"? don't add registry json. only by parameters.

like: evm, cosmos, substrate ...

As more and more chains are created, is it possible to provide a unified interface for these chains? so that we can add custom network on frontend.

because the workflow is long, add `register.json`, compile wallet-core, update android, iOS, publish ..

**Comment by Milerius** [comment]
Yes we are working on something we call "Day 1 chain support" we are migrating to a database and will enable a front end long term to be able to propose new chain and quickly whitelist them. no ETA.
