### ISSUE TITLE
i can't add my Dchain L2 bcs chain id out of u32

### ISSUE THREAD

**Issue by oleksiivinogradov** [trustwallet/wallet-core#3937]
**Describe the bug**

i try too update registry.json:
Error: RegistryError("invalid value: integer `2716446429837000`, expected u32 at line 4787 column 28")

https://github.com/oleksiivinogradov/wallet-core/commit/f01e9efc8637a83a676b8386c5305c3b126a0a8b

**To Reproduce**

just add like https://github.com/oleksiivinogradov/wallet-core/commit/f01e9efc8637a83a676b8386c5305c3b126a0a8b

**Expected behavior**

must work cd codegen-v2 && cargo run -- new-evmchain <chain>

**Screenshots**

**Additional context**

**Comment by satoshiotomakan** [comment]
Hi @oleksiivinogradov, `coinId` in registry.json is for internal usage only, in particular, to uniquely identify the chain in the chain list (see `TWCoinType` enum). It can be any value, but must be unique. The important is to use the real `chainId` that is a string.
So you can simply remove first or last digits from the `coinId` you tried to use.
