### ISSUE TITLE
Dchain adding

### ISSUE THREAD

**Issue by oleksiivinogradov** [trustwallet/wallet-core#3938]
## Description

DChain - blockchain for games and studios. 

🔗 Deployment support with go-to-market strategy. With an average revenue of $85k per month from our games, 135+ strategic partnerships, and 16 committed projects, DChain unlocks endless opportunities. Benefit from our expert team's go-to-market strategy, unique liquidity system, and low transaction fees, while accessing our exclusive market tailored for crypto and blockchain projects.

Website: https://www.dchain.foundation/
Whitepaper: https://docs.openbisea.com/dexstudio/d-chain/d-chain

Marketing plan: https://docs.google.com/document/d/1MrC5Q7vMykBYs2HovCfYbAa_iY6o6C_ox4fCPR9frqg/edit?usp=sharing

Name: [ETH](https://ethereum.org) 

HD Derivation Scheme:
[
    {
      "path": "m/44'/60'/0'/0/0"
    }
  ]

Symbol: ETH

Documentation:
https://docs.openbisea.com/dexstudio/d-chain/about-us

Reason:
Our dexStudios already release first and second NFT game and first VR game will released soon. You can check the first game - https://motodex.dexstudios.games/ and second game - https://dexgo.club/en

Our motoDEX now top 4 game on dAppRadar with 230k UAW, 61ETH last sales campaign, and dexGO reach 15M+ views and 50k followers in 4 months

Now we are on the way to add our games on other games to Dchain with maximize Trust Wallet using.
## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by satoshiotomakan** [comment]
Hi @oleksiivinogradov, thank you for opening the issue.
At the moment we do add new blockchains to WalletCore without a positive decision from our Business Development team.
Please create a new ticket, a request to add the blockchain to Trust Wallet:
https://support.trustwallet.com/en/support/tickets/new
