### ISSUE TITLE
Taproot Address Generation Failure

### ISSUE THREAD

**Issue by nftsupply** [trustwallet/wallet-core#3951]
// Generate Wrapped SegWit address (BIP49)
```
let wrappedSegwitKey = wallet.getKey(coin: .bitcoin, derivationPath: "m/49\'/0\'/0\'/0/0")
let wrappedSegwitAddress = btcCoin.deriveAddress(privateKey: wrappedSegwitKey)

// Generate Taproot address (BIP86)
let taprootKey = wallet.getKey(coin: .bitcoin, derivationPath: "m/86\'/0\'/0\'/0/0")
let taprootAddress = btcCoin.deriveAddress(privateKey: taprootKey)
```

this does not generate a valid taproot address, what is the proper way to get the taproot address and what is the proper way to get the xpub of the master fingerprint

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @nftsupply
