### ISSUE TITLE
UnsignedTx Issue :: Solana

### ISSUE THREAD

**Issue by enriquesouza** [trustwallet/wallet-core#3952]
@satoshiotomakan 

Hi we are trying to use the property to calculate fees, and so to integrate with blowfish, but it is returning some encoding errors.

```TW_Solana_Proto_SigningOutput :: unsignedTx ```

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "simulateTransaction",
    "params": [
        "BCpmx5k6s9eiSfMvfabgWBKNsTFHWURKfhbrDtk4Mmasj53R4yzoUtAaqCAAWX7n1HgPvC3MDpqNSWtA6nhev1KYz58jcvzPKQFa7qbBxSQRqfhXz4sAMkeB6UdfHX8UKTXKw8K8F8HTdwDiwCNuf9sPTUrC7QJQ9oTGNTrcV8cAEmU2TjwyPSXM6LZ4dphZ5YNLYMnEWtVw9Yh3XYDMQH5SQboRpLVGrw9ZGJSA9UcCHdjdh9LbJ7SH78SdEmYNNKQnei2B",
        {
            "encoding": "base64",
            "sigVerify": false,
            "replaceRecentBlockhash": true,
            "innerInstructions": true
        }
    ]
}
```

and I get decoding errors (`failed to deserialize solana_sdk::transaction::versioned::VersionedTransaction: io error: failed to fill whole buffer`)

The signed transaction works fine, therefore the unsigned get the above error

https://github.com/vultisig/vultisig-ios/blob/blowfish-sol/VultisigApp/VultisigApp/Chains/Solana.swift#L148

**Comment by satoshiotomakan** [comment]
Hi @enriquesouza, thank you for opening the issue.
As far as I remember, `simulateTransaction` takes a signed transaction or transaction with zeroized signatures. Please take a look at the test in Rust: https://github.com/trustwallet/wallet-core/blob/221584f3ea91da1ba236d06834db9ce5d24a9f40/rust/tw_any_coin/tests/chains/solana/solana_compile.rs#L347-L385
Please note `PreImageHelper` and `CompilerHelper` are wrappers over `TransactionCompiler.preImageHelper()` and `TransactionCompiler.compile()` functions.

**Comment by enriquesouza** [comment]
@satoshiotomakan worked. Thanks!

```
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "simulateTransaction",
    "params": [
      "4yWSgAC8koXqMxCmhGqAYJbCTJVcDGQBYLcNpepQ4R1UktM1a8F5nDkavSPQSyryJbcdPSGzK9QGAqidg1Gjbmd19ZPtkhMbyaHiwgGTnpzpaXeWDcUsEMEvHEacsmxkFu4BHLXKYuLd1rH5irvRNTRkd1GwvXLbu9PoqWc2ofuucbVqNgm4C8F2Qs6p4ZHszGRC4b9SNtxdoYu5dRPFTk4rSGfMmT8PurGGBE2i2go37EP6A5SLT9bUy1SrpxWP11Mii71YXFwkppXjnKj4G8cfQ9HD15zLFuu6bFfGe3gsSFvCyJKv2K3n52RzshyYhvPJFrBr6is9bGBeNSh2wADjcAYnsS2sZ"
    ]
  }
'
```

Response:

```
{"jsonrpc":"2.0","result":{"context":{"apiVersion":"1.18.18","slot":280572199},"value":{"accounts":null,"err":null,"innerInstructions":null,"logs":["Program ComputeBudget111111111111111111111111111111 invoke [1]","Program ComputeBudget111111111111111111111111111111 success","Program 11111111111111111111111111111111 invoke [1]","Program 11111111111111111111111111111111 success"],"returnData":null,"unitsConsumed":300}},"id":1}
```

**Comment by AlexDarsky** [comment]
Hello, I encountered the same problem as you on the simulateTransaction step.Following is my code：

> 
 let transferMessage = SolanaTransfer.with {
                        $0.recipient = to
                        $0.value = amount
                    }
                    let input = SolanaSigningInput.with {
                        $0.transactionType = .transferTransaction(transferMessage)
                        $0.recentBlockhash = blockHash
                        $0.sender = address
                    }
let hashes = TransactionCompiler.preImageHashes(coinType: .solana, txInputData: try input.serializedData())
let preSigningOutput = try SolanaPreSigningOutput(serializedBytes: hashes)
let message = Base58.encode(data: preSigningOutput.data)
> 


But then i also got the error (failed to deserialize solana_sdk::transaction::versioned::VersionedTransaction: io error: failed to fill whole buffer).Have you dealt with this situation?
