### ISSUE TITLE
delayed notifications

### ISSUE THREAD

**Issue by melaxon** [trustwallet/wallet-core#3956]
**Describe the bug**
In I-phone 12 the notification upon receiving USDT is significantly delayed, approx. by one hour. Also i do not see the received transaction among todays transactions until the notification arrived. While the total reflects the amount received and I'm able to send the received coins. Every time the delay becomes longer. Today I'm still waiting for notification more than three hours.
I see you updated the app recently. Perhaps there is a bug in new code. 
On the screenshot there is only outgoing transaction of 114 USDT, but incoming one for 31 USDT is missing

**To Reproduce**
In I-phone:
- update the wallet to the most recent version
- receive some USDT coins in TRC-20 network

**Expected behavior**
A push notification must appear immediately and when get into the app one must see the record of incoming transaction for USDT Tron coins

**Screenshots**
![IMG_C9596CC5F789-1](https://github.com/user-attachments/assets/88bc5bc9-86ea-4bb9-9ddd-a5de69c000c8)

**Additional context**

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID USD5562, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)
Thank you for posting @melaxon
