### ISSUE TITLE
[Android] Trust Wallet doesn't show up for Solana dApps

### ISSUE THREAD

**Issue by theDurin** [trustwallet/wallet-core#3958]
**Describe the bug**
On Android the Trust Wallet mobile app does not show up as a selectable option for Solana dApp connection.

**To Reproduce**
1. Use chrome/firefox/brave on Android and go to: https://anza-xyz.github.io/wallet-adapter/example/
2. Press Connect Wallet
3. Trust wallet should be inside the app-selection drawer that opens, but it isn't. (if no other Solana wallet is detected, you even get redirected to a different page)

**Expected behavior**
Trust Wallet mobile app shows up and can be selected to connect to a Solana dApp.

**Screenshots**
![photo_2024-07-27_15-26-51](https://github.com/user-attachments/assets/bcf31ffe-87af-4a32-b881-a3d8840e3249)

**Additional context**
I remember this working before the last Android app update on 23.07.24

**Comment by theDurin** [comment]
Why was this closed without comment?

**Comment by ARKN-SOL** [comment]
Not closed... Still an issue

**Comment by Milerius** [comment]
this issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
