### ISSUE TITLE
TON transaction error after update LIB

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/wallet-core#3962]
I've noticed that there are breaking changes in the latest library of Trust Wallet Core for the TON Network. Specifically, I'm unable to set the sequence and transfer for TON. Here's an example of the issue:

**Can't set the sequence, and transfer for TON....**
![image](https://github.com/user-attachments/assets/77518f3f-362f-49fd-8381-6fb8d4b5fe30)

Does anyone have an updated sample for the new library?

**Comment by satoshiotomakan** [comment]
Hi @ronaldoguedess, you can find examples at https://github.com/trustwallet/wallet-core/blob/master/android/app/src/androidTest/java/com/trustwallet/core/app/blockchains/theopennetwork/TestTheOpenNetworkSigner.kt

**Comment by satoshiotomakan** [comment]
Please note that `sequence` and `expire_at` moved to `SigningInput` to make it possible to sign a transaction with multi ?Transfer messages
