### ISSUE TITLE
Add my project to the list

### ISSUE THREAD

**Issue by ronaldoguedess** [trustwallet/wallet-core#3973]
How can I add my project to this list?

I am interested in including my project on this list and would like to understand the process. Could you provide guidance on the steps required to add my project?

![image](https://github.com/user-attachments/assets/fed1910d-c7e8-4063-8285-a31f62e41d87)

**Comment by Willisplayed** [comment]
No

**Comment by ronaldoguedess** [comment]
Why not? It's saying "Add yours too!"
My project is usign WalletCore.

**Comment by satoshiotomakan** [comment]
Hi @ronaldoguedess, thank you for asking! I'm glad to use TrustWalletCore in your project! Please let me know the name, so we consider adding it. Did you publish mobile apps (Android, iOS), or is it Desktop/Web?

**Comment by ronaldoguedess** [comment]
Hi Satoshi,

Thank you for the Wallet Core — it's reliable, secure, and up-to-date lib. It's a pleasure to use it.

Yes, we’ve launched the app on [Google Play](https://play.google.com/store/apps/details?id=org.ecoinwallet&referrer=utm_source%3Dwallet-core%26utm_medium%3Dgithub%26utm_content%3Dlink); It's a cryptocurrency wallet called **ECOIN Wallet**.


--- 
Check that Alice link is off on that list!

**Comment by ronaldoguedess** [comment]
![image](https://github.com/user-attachments/assets/3832c61f-bcd0-4966-9390-49f7362c96a1)
I added a brief mention of this library in our provider — thanks again!

By the way, will this logo be updated to reflect the new Trust Identic branding?

**Comment by satoshiotomakan** [comment]
Hi @ronaldoguedess, what's the official website? https://ecoinwallet.org/ doesn't work for me (EU)

**Comment by ronaldoguedess** [comment]
> Hi @ronaldoguedess, what's the official website? https://ecoinwallet.org/ doesn't work for me (EU)

Could you use the Google Play link? The website is under contruction yet.

`https://play.google.com/store/apps/details?id=org.ecoinwallet&referrer=utm_source%3Dwallet-core%26utm_medium%3Dgithub%26utm_content%3Dlink`

**Comment by satoshiotomakan** [comment]
Done @ronaldoguedess
