### ISSUE TITLE
Is TON Wallet V5R1 in development?

### ISSUE THREAD

**Issue by 10gic** [trustwallet/wallet-core#3982]
Experts, thank you for supporting TON. I would like to ask if the development of Ton Wallet [V5R1](https://github.com/ton-org/ton/blob/master/src/wallets/v5r1/WalletContractV5R1.ts) has already started. If not, I'm interested in contributing. Do you welcome PRs?

**Comment by satoshiotomakan** [comment]
Hi, we aren't working on TON Wallet V5R1 yet, so please feel free to open a PR. Please note that adding support for V5R1 doesn't mean it will be used in Trust Wallet apps.
Contracts are at https://github.com/trustwallet/wallet-core/tree/master/rust/chains/tw_ton/resources/wallet
All about wallet is at https://github.com/trustwallet/wallet-core/tree/master/rust/chains/tw_ton/src/wallet

**Comment by 10gic** [comment]
Hi @satoshiotomakan. I've submitted a pull request https://github.com/trustwallet/wallet-core/pull/3983 and would appreciate it if you could take a moment to review it.
