### ISSUE TITLE
how to initwasm? I can not find anything related from document

### ISSUE THREAD

**Issue by fukemy** [trustwallet/wallet-core#3992]
Hi all, I am new about wallet-core, I want to use NextJS to integrate with WalletCore, step by step, by following code above:

```
useEffect(() => {
    initWasm().then((WalletCore) => {
      const { CoinType, HexCoding, HDWallet,
        AnyAddress, Derivation, DerivationPath } = WalletCore;
      const mnemonic = "abandon ability able about above absent absorb abstract absurd abuse access accident";
      const wallet = HDWallet.createWithMnemonic(mnemonic, "")
      const address = wallet.getAddressForCoin(CoinType.bitcoin)
      console.log("Bitcoin Address:", address)
    }).catch(error => {
      console.log('initWasp error', error)
    })
  }, [])
```

I put the file `wallet-core.wasm` into nextjs build folder, then run it, after run I got this error:
***initWasp error 2153272 - Exception catching is disabled, this exception cannot be caught. Compile with -sNO_DISABLE_EXCEPTION_CATCHING or -sEXCEPTION_CATCHING_ALLOWED=[..] to catch***

Can someone help?

**Comment by satoshiotomakan** [comment]
You cannot just copy wallet-core.wasm, please import `@trustwallet/wallet-core` package

**Comment by satoshiotomakan** [comment]
Duplicate https://github.com/trustwallet/wallet-core/discussions/3193#discussioncomment-10393910
