### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by kenneth** [TrustWallet/wallet-core#400]
```
protobuf-3.7.0/src/google/protobuf/compiler/java/java_extension_lite.cc: (Empty error message)
tar: Error exit delayed from previous errors.
```

**Comment by hewigovens** [comment]
could you elaborate your problem? we do support macOS / Linux, make sure you have read docs:

https://developer.trustwallet.com/wallet-core/contributing
https://developer.trustwallet.com/wallet-core/linux
