### ISSUE TITLE
Unable to deposit or send without please provide information is needed to deposit to a wallet

### ISSUE THREAD

**Issue by Vero7979** [trustwallet/wallet-core#4024]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Checklist**

- [x] task number 1
    - [ ] subtask number 1
    - [ ] subtask number 2
- [ ] task number 2
- [ ] task number 3

**Resources**

Resources link

**Additional context**

**Comment by summerly01** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Vero7979
