### ISSUE TITLE
Trust wallet 

### ISSUE THREAD

**Issue by Murali1968** [trustwallet/wallet-core#4025]

**Comment by Murali1968** [comment]
Want to link 
up with Github API INTEGRATION

**Comment by summerly01** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Murali1968
