### ISSUE TITLE
There is no community information on this jetton. Please exercise caution

### ISSUE THREAD

**Issue by lovety16** [trustwallet/wallet-core#4042]
Good evening, a whooping sum of 2.1 TON was transferred to me on the 02.09.2024, 19:34:35 the assets was credited on my wallet but I can't use it. There is no Community information on this jetton. Please exercise caution. Is the error messages showing on my dashboard. The below are the information needed to trace the errors. Kindly help me to look into this issue as soon as possible and find solutions to it. Thanks. 

Account:
EQB12UvXiN7ZrWrRZXaiiREEqGAHrryv-AuzMNgYoT4ntp1w

Interfaces:
jetton_wallet_v1

Hash: 79f17f81388e0672ba720823c168cbc43a7de6e98c30c853c1938303d521f52f

LT:
48889317000001

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@lovety16 
Support
 {c}2024.

**Comment by case-hub** [comment]
Hello are you able to resolve your issue?

**Comment by satoshiotomakan** [comment]
Hi @lovety16, as I can see, https://tonviewer.com/transaction/79f17f81388e0672ba720823c168cbc43a7de6e98c30c853c1938303d521f52f transaction executed successfully. Did you use TrustWallet? iOS, Android or Browser Extension? Which version? What kind of errors did you have?

**Comment by lovety16** [comment]
I used telegram wallet, and I used an android phone. The error messages I'm
seeing is There is no community information on this jetton. Please exercise
caution (Issue #4042)

**Comment by satoshiotomakan** [comment]
@lovety16 this issue is not related to the wallet core repository, please reach out Telegram Customer Support
