### ISSUE TITLE
Sui error 

### ISSUE THREAD

**Issue by enriquesouza** [trustwallet/wallet-core#4045]
**Describe the bug**
While sending coins using Pay Sui to a new address I am not being able to sign a transaction. 

If I send some coins to this target address from another wallet and activate that account then I can send coins to it using the same code. 

Not sure Sui has any method to create and activate an account as Solana does, but if it does I would be happy to be helped.

**Comment by satoshiotomakan** [comment]
Hi @enriquesouza, did you use WalletCore directly to send coins to or from the target address? Or did you use TrustWallet app? Which version and platform?

**Comment by enriquesouza** [comment]
Hey @satoshiotomakan sorry for not specify I am using the library wallet core on Swift, Android, Windows (Wasm, Go, Typescript)

https://github.com/vultisig/vultisig-ios/blob/main/VultisigApp/VultisigApp/Chains/Sui.swift

**Comment by enriquesouza** [comment]
<img width="388" alt="image" src="https://github.com/user-attachments/assets/05cd853d-ae01-4a5e-bf8f-04f120ece57e">

That is how I activate an address, using another wallet

**Comment by satoshiotomakan** [comment]
And which error do you have when signing/broadcasting?

**Comment by enriquesouza** [comment]
Hey, @satoshiotomakan I am trying to get a clear message. I will post it here. ```signature verification failed``` Therefore it is not always. I am not sure yet where the issue is.

**Comment by enriquesouza** [comment]
I found the issue here. @satoshiotomakan nothing to do with Wallet Core. Tks.
