### ISSUE TITLE
Does TrustWallet support `cosmos_signDirect` for WalletConnect

### ISSUE THREAD

**Issue by borngraced** [trustwallet/wallet-core#4050]
Seems Trustwallet does but no doc on the data types like here in WC docs
https://docs.reown.com/advanced/multichain/rpc-reference/cosmos-rpc#cosmos_signdirect
`bodyBytes` and `authInfoBytes` are both encoded in base64, does TrustWallet require `base64`, `hex` or raw bytes in json?

**Comment by satoshiotomakan** [comment]
Hi @borngraced, `bodyBytes` and `authInfoBytes` both are raw bytes as declared in `Cosmos.proto`:
https://github.com/trustwallet/wallet-core/blob/7523c9805ce094639dfbda6d643e439f5ef1705e/src/proto/Cosmos.proto#L240-L246

You can always check doc comments in the Protobuf files

**Comment by borngraced** [comment]
@satoshiotomakan, sorry I'm reopening this issue. 
I want to confirm if this is the expected json def trustwallet is expecting according to your proto defs and since I'm still encountering `failed to sign message`
```rust
json!({
           "signingMode": "Protobuf",
           "accountNumber": sign_doc.account_number.to_string(),
           "chainId": sign_doc.chain_id,
            "messages": [
             {
               "signDirectMessage": {
                   "bodyBytes": sign_doc.body_bytes,
                    "authInfoBytes": sign_doc.auth_info_bytes
                  }
             }
         ]
})
```
