### ISSUE TITLE
[Feature Request] - Add Lightning Network Support

### ISSUE THREAD

**Issue by ffrediani** [trustwallet/wallet-core#4055]
Lightning Network has becoming increasing popular overtime and there aren't many rock solid solutions available that does custody of user's fund.

Trust Wallet besides being used as a Web3 solution is present on many mobile devices and by having Lightning Network support can be used on the day by day by people in general to make micro-payments.

Initially I put that is more important that TrustWallet develops a solution where they are responsible for the custody of user's funds (as of Wallet of Sathosi) in order to increase adoption and later on give users who wish the option to connect their own nodes, if it is the case.
Custody of user's funds may be a point of concern but remember that Binance has Lightning Network support already and TrustWallet can take advantage of it, including the nodes if it is the case.

There are different ways to monetise this functionality other than just fees earned by the channels, but also fees of when users send BTC via mainnet to fund their wallets and make spendings. 
Different from the user's own BTC address (e.g: bc1q...) the Lightning Solution can provide another unique BTC mainnet address for deposits (with custody by TrustWallet) in order that it can be used by Lightning transactions and vice-versa.

Soon Lightning Network thoguht Taproot Assets will become even more popular for payments as it will start supporting stablecoins as well.

Please consider adding this support and make TrustWallet a real day by day wallet for people to use on their day life and use what is already developed to integrate it more easily.

**Comment by ffrediani** [comment]
@vikmeup @johnnynanjiang if you wish to contribute to this Feature Request, be welcome.

**Comment by Milerius** [comment]
Hey this as nothing todo with wallet-core, closing.

**Comment by ffrediani** [comment]
@Milerius so if Lightning Network get added to TrustWallet no code changes would be necessary to wallet-code ?

**Comment by satoshiotomakan** [comment]
Hi @ffrediani, that's right. Lightning is a complex protocol, we did some research, and found a good Kotlin libraries for Lightning support - [breez_sdk](https://breez.technology/sdk/)
If we do the support, we'll use the SDK in WalletKit (private repo yet)

**Comment by ffrediani** [comment]
@satoshiotomakan I still don't get it.
The issue was closed saying it has nothing to do with wallet-core. The doubt is that if Lightning gets implemented to TrustWallet, wouldn't it be necessary code changes to wallet-core even using this SDK ? Or WalletKit that you mention integrates with wallet-core in this context ?

**Comment by ffrediani** [comment]
By the way, when you do please consider already Taproot Assets in order to have also stablecoins in Lightning.
