### ISSUE TITLE
Add support for Pactus Blockchain

### ISSUE THREAD

**Issue by Ja7ad** [trustwallet/wallet-core#4056]
## Description
Pactus is an open source, layer-1 blockchain technology with a revolutionary, secure, Solid State Proof of Stake Consensus.

Name: [Pactus](https://pactus.org)
HD Derivation Scheme: `m/44'/21888'/3'/0'`
Symbol: PAC
Documentation: https://docs.pactus.org
Reason:

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by Milerius** [comment]
Hello, it's not planned.
