### ISSUE TITLE
Help me retrieve my balances and withdraw

### ISSUE THREAD

**Issue by Mohurd** [trustwallet/wallet-core#4058]
How do I import my tokens and claim all m my assets
![Screenshot_20241009-022922](https://github.com/user-attachments/assets/44f70b25-cddf-4a85-808b-8438914918ed)
![Screenshot_20241006-125439](https://github.com/user-attachments/assets/1bdf1673-c143-46b4-b158-2babfacd5685)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@Mohurd 
Support.

**Comment by Milerius** [comment]
Not related to wallet-core, closing.
