### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by VytPal** [trustwallet/wallet-core#4059]
I am trying to build Trust Wallet Core for use in a Windows desktop application, but I am unsure of the exact steps or changes involved in successfully building the project for Windows. Could you provide detailed guidance on how to build and configure the project for use in a Windows desktop application?

I am aware of the existing Windows port: [kaetemi/wallet-core-windows](https://github.com/kaetemi/wallet-core-windows), but it appears outdated, as it has not seen updates for over 3 years.

**Comment by Milerius** [comment]
Hey @VytPal it's not planned to support windows sorry.
