### ISSUE TITLE
TON address generate is wrong

### ISSUE THREAD

**Issue by deeryoona** [trustwallet/wallet-core#4063]
version:4.1.10
switf exapple code is:
func testAddressFromPrivateKey() {
        let data = Data(hexString: "63474e5fe9511f1526a50567ce142befc343e71a49b865ac3908f58667319cb8")
        let privateKey = PrivateKey(data: data!)!
        let publicKey = privateKey.getPublicKeyEd25519()
        let address = AnyAddress(publicKey: publicKey, coin: .ton)
       
when i test this method,the result is EQBm--PFwDv1yCeS-QTJ-L8oiUpqo9IT1BwgVptlSq3ts90Q,
not UQBm--PFwDv1yCeS-QTJ-L8oiUpqo9IT1BwgVptlSq3ts4DV

**Comment by satoshiotomakan** [comment]
Hi @deeryoona, do you use CocoaPods or an SPM packet? We didn't update CocoaPods for some time, I'll schedule the update this week

**Comment by deeryoona** [comment]
> i use SPM packet

**Comment by deeryoona** [comment]
> Hi @deeryoona, do you use CocoaPods or an SPM packet? We didn't update CocoaPods for some time, I'll schedule the update this week

i use SPM packet

**Comment by deeryoona** [comment]
> [satoshiotomakan](/satoshiotomakan)

@satoshiotomakan [satoshiotomakan](https://github.com/satoshiotomakan)

**Comment by deeryoona** [comment]
> Hi @deeryoona, do you use CocoaPods or an SPM packet? We didn't update CocoaPods for some time, I'll schedule the update this week

i updated the latest version 4.1.12,the problem already exist @satoshiotomakan

**Comment by satoshiotomakan** [comment]
Hi @deeryoona, could you please update to 4.1.13? Now you should have all changes.
We haven't updated our SPM packages since 4.0.33

**Comment by deeryoona** [comment]
> Hi @deeryoona, could you please update to 4.1.13? Now you should have all changes. We haven't updated our SPM packages since 4.0.33

this proble solved,thanks,[satoshiotomakan](https://github.com/satoshiotomakan)
