### ISSUE TITLE
World Chain (WLD)

### ISSUE THREAD

**Issue by CicheR** [trustwallet/wallet-core#4066]
#### Worldcoin is launching its own L2: World Chain. After many migrations within the Ethereum Ecosystem, Worldcoin can finally find its new permanent home in a place that can scale.

Name: **World Chain**

HD Derivation Scheme:

Symbol: **WLD**

Documentation: https://worldcoin.org/blog/engineering/finding-scalable-home-for-worldcoin

Reason: World Coin is migrating to its own Ethereum layer 2 implementation

**Comment by satoshiotomakan** [comment]
Hi @CicheR, at the moment we do not merge new blockchains into WalletCore without a positive decision from our Business Development team.
Please create a new ticket, a request to add the blockchain to Trust Wallet:
https://support.trustwallet.com/en/support/tickets/new
