### ISSUE TITLE
TON staking

### ISSUE THREAD

**Issue by enriquesouza** [trustwallet/wallet-core#4073]
How can I stake using Wallet Core? Is there any example? Can I use the custom payload?

**Comment by satoshiotomakan** [comment]
Hi @enriquesouza, here we go
https://github.com/trustwallet/wallet-core/blob/26aa4289b0e9cd57d958f5f4342aaa9c53851fc0/rust/tw_tests/tests/chains/ton/ton_sign.rs#L387-L422

We don't have an exact staking transaction example, but the custom payload in general

**Comment by enriquesouza** [comment]
Thanks @satoshiotomakan
