### ISSUE TITLE
signrawtransactionwithkey with base58, the private key is invalid

### ISSUE THREAD

**Issue by AlexDarsky** [trustwallet/wallet-core#4075]
Hello,
I'm using walletCore(swift) to signrawtransactionwithkey for siging inputs for raw transaction.But the response always is "Invalid private key".

How do I get the base58 encode string is :
{
let wallet = HDWallet(mnemonic: mnemonic, passphrase: "")
let derivationPath = CoinType.bitcoin.derivationPath()
let privateKey = wallet.getKey(coin: .bitcoin, derivationPath: derivationPath)
let privateKey58 =  Base58.encodeNoCheck(data: privateKey.data)
}

Finally, the server replied to my error "Invalid private key"Is it that the steps I used are wrong?
Is there any error in my steps?

**Comment by Mohurd** [comment]
Please help me understand this can I request help

**Comment by satoshiotomakan** [comment]
Hi @AlexDarsky @Mohurd, I'm checking it right now. Will post an update shortly

**Comment by satoshiotomakan** [comment]
@AlexDarsky @Mohurd `signrawtransactionwithkey` takes a private key in [WIF](https://learnmeabitcoin.com/technical/keys/private-key/wif/) format encoded as base58Check. Currently, WC doesn't support WIF encoding.
As a quick solution, you can write something like:
```swift
let wallet = HDWallet(mnemonic: mnemonic, passphrase: "")
let derivationPath = CoinType.bitcoin.derivationPath()
let privateKey = wallet.getKey(coin: .bitcoin, derivationPath: derivationPath)

let prefix: Data = Data([0x80])
let compression: Data = Data([0x01])
let wifPrivateKey = prefix + privateKey.data + compression
let wifPrivateKey58 = Base58.encode(data: wifPrivateKey)
```
