### ISSUE TITLE
Failure to transfer before bnb sunset closer 

### ISSUE THREAD

**Issue by Brindle79** [trustwallet/wallet-core#4088]
**Describe the bug**
A clear and concise description of what the bug  
Multiplie coins  have not been transferred before bnb sunset final stage  milestone  come to end   Is bugging me  loose ends 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by satoshiotomakan** [comment]
Hi @Brindle79, could you please provide more context? Do you have an error when trying to migrate your funds from BNB to BSC? Or you don't have a button to migrate the funds? Have you tried to update the app to the latest version?
Please create a ticket here if u believe there is a bug in the application: https://support.trustwallet.com/en/support/tickets/new

**Comment by satoshiotomakan** [comment]
Please contact Customer Support

**Comment by Brindle79** [comment]
What device you using I  found I had repeat few times for some reason load faster  if open one extension wallet the load second send through longest open wallet it's browser link issues then
