### ISSUE TITLE
Export Bech32 functions

### ISSUE THREAD

**Issue by 10gic** [trustwallet/wallet-core#4100]
Exporting the bech32 related functions would increase the utility of this library.

For example, Sui uses bech32 to encode its private keys. https://github.com/sui-foundation/sips/blob/main/sips/sip-15.md

**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Solution 1:
```c
struct TWBech32;
TWString *_Nonnull TWBech32Encode(TWString* _Nonnull hrp, TWData *_Nonnull data);
TWData* _Nullable TWBech32Decode(TWString* _Nonnull string);  // The hrp part is easy to obtain, it will not be returned

struct TWBech32m;
TWString* _Nullable TWBech32mEncode(TWString* _Nonnull hrp, TWData *_Nonnull data);
TWData* _Nullable TWBech32mDecode(TWString* _Nonnull string);  // The hrp part is easy to obtain, it will not be returned
```

**Describe alternatives you've considered**
Solution 2:
```c
enum TWBech32ChecksumVariant {
  TWBech32ChecksumVariantBip173
  TWBech32ChecksumVariantBip350
}

struct TWBech32;
TWString *_Nonnull TWBech32Encode(TWString* _Nonnull hrp, TWData *_Nonnull data, enum TWBech32ChecksumVariant variant);
TWData* _Nullable TWBech32Decode(TWString* _Nonnull string, enum TWBech32ChecksumVariant variant);  // The hrp part is easy to obtain, it will not be returned
```

**Checklist**

**Resources**

Resources link
https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki

**Additional context**

**Comment by 10gic** [comment]
Hi @satoshiotomakan, I can work on this. Which solution do you prefer? Do you have any other better solutions?

**Comment by satoshiotomakan** [comment]
Hi @10gic, good suggestion. I think the `Solution 1` seems to be more unambiguous, homogeneous. For example, we have similar `TWBase58Encode`, `TWBase58EncodeNoCheck`.

**Comment by 10gic** [comment]
Hi @satoshiotomakan, your comment reminds me that there is one more solution:
Solution 3:
```c
struct TWBech32;
TWString *_Nonnull TWBech32Encode(TWString* _Nonnull hrp, TWData *_Nonnull data);
TWData* _Nullable TWBech32Decode(TWString* _Nonnull string);
TWString *_Nonnull TWBech32EncodeM(TWString* _Nonnull hrp, TWData *_Nonnull data);  // bip350 Variant
TWData* _Nullable TWBech32DecodeM(TWString* _Nonnull string);  // bip350 Variant
```

It's hard to choose solution 1 and solution 3.

**Comment by satoshiotomakan** [comment]
Thank you for the PR @10gic, it's merged finally :)
