### ISSUE TITLE
[BTC]: AnySigner.plan returns empty for BCH (BitcoinV2)

### ISSUE THREAD

**Issue by JaimeToca** [trustwallet/wallet-core#4105]
**Describe the bug**
Context PR: https://github.com/trustwallet/wallet-core/pull/4049

When trying to calculate plan for `BitcoinCash`, anySigner.plan returns empty fields. Do note, signing transactions works completely fine. Here are the steps to reproduce:

**To Reproduce**
1) Create SigningInput with coinType value in legacy SignignInput. (hex format)
`509101aa019702122102b35012159dbf8515aa98018e5cc49185d885a169996f5d851a36715b082b1e301a0f10051a0b626974636f696e6361736852e0011a6c0a240a207cbf7249c5f33a8157b27fe4f743bd9bbeabeb694ac71510ae3f2c9d38ea06c2100110f49e1d1841220608ffffffff0f3a36626974636f696e636173683a717a3965336733373263676d7178767a6164353230746e36756439326c79357479633376776735383265222f08904e222a717a307133786d673338737239347277387767343576756a6168376b7a6d613363736b78796d6e773036280230023a382236626974636f696e636173683a717a3965336733373263676d7178767a6164353230746e36756439326c7935747963337677673538326570e807`

2) Decoded signingInput
`SigningResult(outputs=[SigningInput{hash_type=0, amount=0, byte_fee=0, to_address=, change_address=, use_max_amount=false, coin_type=145, lock_time=0, output_op_return=[size=0], use_max_utxo=false, disable_dust_filter=false, time=0, signing_v2=SigningInput{public_keys=[[hex=02b35012159dbf8515aa98018e5cc49185d885a169996f5d851a36715b082b1e30]], chain_info=ChainInfo{p2pkh_prefix=0, p2sh_prefix=5, hrp=bitcoincash}, dangerous_use_fixed_schnorr_rng=false, builder_=TransactionBuilder{version=UseDefault, lock_time=0, inputs=[Input{out_point=OutPoint{hash=[hex=7cbf7249c5f33a8157b27fe4f743bd9bbeabeb694ac71510ae3f2c9d38ea06c2], vout=1}, value_=479092, sighash_type=65, sequence=Sequence{sequence=-1}, receiver_address=bitcoincash:qz9e3g372cgmqxvzad520tn6ud92ly5tyc3vwg582e}], outputs=[Output{value_=10000, to_address=qz0q3xmg38sr94rw8wg45vujah7kzma3cskxymnw06}], input_selector=SelectDescending, fee_per_vb=2, change_output=Output{value_=0, to_address=bitcoincash:qz9e3g372cgmqxvzad520tn6ud92ly5tyc3vwg582e}, fixed_dust_threshold=1000}}}], blockNumber=0)`

3) Call anySigner `val plan = AnySigner.plan(signingInput, coin, TransactionPlan.ADAPTER)`

4) TransactionPlan result
`TransactionPlan{amount=0, available_amount=0, fee=0, change=0, branch_id=[size=0], error=OK, output_op_return=[size=0], preblockhash=[size=0], preblockheight=0, planning_result_v2=TransactionPlan{error=OK, error_message=, available_amount=0, send_amount=0, vsize_estimate=0, fee_estimate=0, change=0}}`

As you can see it retuns okay, but all values are set to 0. When signing transactions, a completely valid encoded field is return. Some examples broadcasted:

https://blockchair.com/bitcoin-cash/transaction/019c5c3e4917843a4da5e9070ee7942eafe007ac539df68ce1d53c5c70a24ead
https://blockchair.com/bitcoin-cash/transaction/c206ea389d2c3fae1015c74a69ebabbe9bbd43f7e47fb257813af3c54972bf7c

**Comment by satoshiotomakan** [comment]
Solved at the https://github.com/trustwallet/wallet-core/pull/4118
