### ISSUE TITLE
[Solana]: Support specifying fee payer for an encoded transaction

### ISSUE THREAD

**Issue by 10gic** [trustwallet/wallet-core#4114]
**Is your feature request related to a problem? Please describe.**
A fee payer on Solana is an account that covers the transaction fees for a user. The fee payer is the first writable signer account in the list of accounts for a transaction.

Fee payers can simplify the user experience by allowing users to interact with an app without needing to acquire the native token. Developers can sponsor these fees to make it easier for users to engage with their app.

It would be amazing if this library supported specifying a fee payer for an encoded transaction.

**Describe the solution you'd like**
Add a function likes: `tw_solana_transaction_add_fee_payer(encoded_tx, fee_payer)`

**Describe alternatives you've considered**

**Checklist**

**Resources**

https://solana.com/docs/core/fees

**Additional context**

**Comment by satoshiotomakan** [comment]
Hi @10gic, you can specify an external fee payer by
https://github.com/trustwallet/wallet-core/blob/3772536bd3de5cf3a8b412f598823fc6ea5285fe/src/proto/Solana.proto#L274-L277
