### ISSUE TITLE
Hello, I wants to have inquery about   Transaction Hash: 0x18d3cc11e60e04b116e7b73863a8961986fafd472be007ae1e7949a61f018b06  Thanks

### ISSUE THREAD

**Issue by abgraham14** [trustwallet/wallet-core#4116]
## Description

Name:

HD Derivation Scheme:

Symbol:

Documentation:

Reason:

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by satoshiotomakan** [comment]
This issue is not related to the wallet core repository, please create a ticket to get help with your question: https://support.trustwallet.com/en/support/tickets/new

**Comment by abgraham14** [comment]
Are you sure there's nothing you can do to help me here?

**Comment by abgraham14** [comment]
I submitted a ticket over a week ago

**Comment by abgraham14** [comment]
Thank you I submitted a ticket over a week ago. I really need you guys to take a look at this and help me out with it.  Sent from my iPhoneOn Nov 19, 2024, at 11:58 AM, Sergei Boiko ***@***.***> wrote:﻿
This issue is not related to the wallet core repository, please create a ticket to get help with your question: https://support.trustwallet.com/en/support/tickets/new

**Comment by abgraham14** [comment]
Please help Sergio. I haven't heard back in over a week from support..
    On Tuesday, November 19, 2024 at 11:58:42 AM MST, Sergei Boiko ***@***.***> wrote:  
 
 


This issue is not related to the wallet core repository, please create a ticket to get help with your question: https://support.trustwallet.com/en/support/tickets/new
