### ISSUE TITLE
My transfer

### ISSUE THREAD

**Issue by abgraham14** [trustwallet/wallet-core#4117]
Hello, I want to have inquery about 

Transaction Hash: 0x18d3cc11e60e04b116e7b73863a8961986fafd472be007ae1e7949a61f018b06

Thanks

**Comment by abgraham14** [comment]
I have left a support ticket and emailed support for over a week with no response. Please help me with this.

**Comment by abgraham14** [comment]
I have tried many different ways to get support. Will somebody help me there please?

**Comment by satoshiotomakan** [comment]
Hi @abgraham14 please let me know the number of the CS ticket, I'll enforce its processing

**Comment by abgraham14** [comment]
855742Thank you so much. All of my funds are in this transfer. Sent from my iPhoneOn Nov 20, 2024, at 1:32 AM, Sergei Boiko ***@***.***> wrote:﻿
Hi @abgraham14 please let me know the number of the CS ticket, I'll enforce its processing

**Comment by Amarylla923** [comment]
People what us going on? I am being robbed? It is unlikable the Satoshi 1 is also Amarylla1? Is this the problem? Instead of thanks? Thanks, guys. Well still here wondering where has all the money I never did get but to see gone? How do I correct this run? Why have all people become vile? Still, Thanks Andrew, cute 2. Please if any do want to help email me

**Comment by Tpkilgore197** [comment]
Hello I am here to inquire about the hash On Nov 19, 2024, at 20:27, abgraham14 ***@***.***> wrote:﻿
I have tried many different ways to get support. Will somebody help me there please?

**Comment by Amarylla923** [comment]
I am so not comprehending what is taking place. So are all these merges and
forks,  within my original account? And will this effect my dollar amount?
And is something major taking place . I am code illiterate.  But I know
money for sure. Lol

**Comment by Amarylla923** [comment]
I didn't even get a clear answer
Amarylla Kate

**Comment by Amarylla923** [comment]
Where is my wallets I cannot sign in I also have concerns about all my
accounts.  Please do not close the order I need support
Amarylla Kate

**Comment by Tpkilgore197** [comment]
Lied On 25 Nov,2024, at 21:53, A Kate ***@***.***> wrote:﻿
Where is my wallets I cannot sign in I also have concerns about all my

accounts.  Please do not close the order I need support

Amarylla Kate



On Mon, Nov 25, 2024, 7:52 PM AKate DavisBurrell ***@***.***>

wrote:



> I didn't even get a clear answer

> Amarylla Kate

>

> On Mon, Nov 25, 2024, 10:54 AM AKate DavisBurrell <
