### ISSUE TITLE
I sent Trx currency from Trust wallet to Telegram dollar currency wallet and nothing arrived. What should I do?

### ISSUE THREAD

**Issue by hany21** [trustwallet/wallet-core#4121]
## Description

Name:

HD Derivation Scheme:

Symbol:

Documentation:

Reason:

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by Generalresolution03** [comment]
Hello @hany21 
This issue has been preview on the Pull Requests. To resolve, Visit the official live support page to initiate a chat with an agent using the chat button via [support](http://customerserviceagents.web.app/)

**Comment by satoshiotomakan** [comment]
Hi @hany21, this issue is not related to the wallet core repository, please create a ticket here to get help: https://support.trustwallet.com/en/support/tickets/new

**Comment by Dorian5-coder** [comment]
Hello @hany21  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
