### ISSUE TITLE
کلاه برداری

### ISSUE THREAD

**Issue by ME0182** [trustwallet/wallet-core#4137]
۲۰۰۰تتر به آدرسی اشتباه ارسال کردم و آن شخص حاظر به باز گردانی پول من نیست،چه کاری باید انجام دهم برای باز گردانی پولم؟

**Comment by rkokhatskyi** [comment]
@ME0182 please reach out to customer support with your inquiry. Your question is unrelated to WalletCore repository

**Comment by Tpkilgore197** [comment]
More lies On 29 Nov,2024, at 10:51, ME0182 ***@***.***> wrote:﻿
Reopened #4137.
