### ISSUE TITLE
DU𝕏

### ISSUE THREAD

**Issue by THYDUX** [trustwallet/wallet-core#4146]
## Description
Dux is your new crypto,designed for smart trading & investment. Customize your strategy,trade confidently, & watch your portfolio grow.

Name:

HD Derivation Scheme:

Symbol:

Documentation:

Reason:

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by satoshiotomakan** [comment]
Hi @THYDUX, please consider creating a ticket, a request to add the blockchain to Trust Wallet:
https://support.trustwallet.com/en/support/tickets/new

**Comment by Tpkilgore197** [comment]
Your all full of shit liers and theirs your not helping me out your stealing  my worry k On 02 Dec,2024, at 03:23, Sergei Boiko ***@***.***> wrote:﻿
Closed #4146 as not planned.
