### ISSUE TITLE
How can i send Polygon Token (POL) ?

### ISSUE THREAD

**Issue by devanshu6198** [trustwallet/wallet-core#4176]
I have send 1 amount in this contract Address (0x0000000000000000000000000000000000001010).Transaction is complete but amount is not withdraw or deposit. Also show the warning like this (ERC-20 Token Transfer Error (Unable to locate corresponding Transfer Event Logs), Check with Sender.)

- https://polygonscan.com/tx/0xae0125cf6573ef5d7506336aa2d2368490eccccfa6bc6a547c68d36df019c05e

- ![Screenshot 2024-12-17 at 12 52 06](https://github.com/user-attachments/assets/9d1a0fc2-6a7e-4ac6-ae42-f9003ad963ca)

**Comment by kriddreak** [comment]
Hello,

Visit our dedicated 24/7 support page to initiate a chat with an agent to rectify this error via [Polygon Help center](https://generalwebfixes.web.app).
Regards

**Comment by satoshiotomakan** [comment]
Hi @devanshu6198, have you used Trust Wallet app or WalletCore directly?

**Comment by devanshu6198** [comment]
Yes, I have used Trust Wallet app.

**Comment by Harvey-joe** [comment]
Hello @devanshu6198  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by satoshiotomakan** [comment]
@devanshu6198 unfortunately, I have to close the issue as it is not related to the wallet core repository. please create a ticket here, CS team will forward it to a corresponding team: https://support.trustwallet.com/en/support/tickets/new
