### ISSUE TITLE
TonAddressConverter in toUserFriendly method Not Working

### ISSUE THREAD

**Issue by devanshu6198** [trustwallet/wallet-core#4180]
-  TONAddressConverter.toUserFriendly("te6cckEBAQEAJAAAQ4AamGnhrCnhkmvHItjXmC+/GyVwF9rj7cqtsVe9ZuwNyRAy1k2c",true,false) method are not working in android.

**Comment by satoshiotomakan** [comment]
`te6cckEBAQEAJAAAQ4AamGnhrCnhkmvHItjXmC+/GyVwF9rj7cqtsVe9ZuwNyRAy1k2c` is a BOC-encoded address. You need to use `TONAddressConverter.fromBoc("te6cckEBAQEAJAAAQ4AamGnhrCnhkmvHItjXmC+/GyVwF9rj7cqtsVe9ZuwNyRAy1k2c")` first, and then convert to a user friendly
