### ISSUE TITLE
Method to return amount, toAddress based on SigningInput

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/wallet-core#426]
```
struct SigningInputPresent {
   let amount: String
   let toAddress: String
}
```

```C++
func present(coin: CoinType: input: SigningInput) -> SigningInputPresent {
    switch {
   case .cosmos(let input):
      return SigningInputPresent(amount: input.coins.amount, toAddress: input.address)
   }
```

We would need to have a switch for each coin returning this info so it could be presented to the user to sign

**Comment by hewigovens** [comment]
why do we need this in wallet core? It's most like UI related and might change frequently.

**Comment by vikmeup** [comment]
@hewigovens let's schedule a discussion with @leoneparise. 

I foresee to have three main ways to have the ability for wallets to sign transactions:

1) Regular wallet - send coin/token transfer
2) DApps via TrustProvider 
3) Deep links

One of the challenges for representing in UI what kind of data are you signing, in order to make it clear we can parse signing inputs and return parsed information to the developers to present in UI.

I just attached a simple example in the issue above, but let's discuss and come up with a better way to handle it

**Comment by hewigovens** [comment]
close this for now, we might need to find a  more lightweight way to achieve this
