### ISSUE TITLE
Add support for NEO

### ISSUE THREAD

**Issue by ArtemGoryunov** [TrustWallet/wallet-core#44]
Name: [NEO](https://neo.org)
HD Derivation Scheme:  BIP44 Coin / 888
Symbol: `NEO`
Documentation:   [NEO](https://docs.neo.org)

## Checklist

- [ ] Implement functionality in C++. Put it in a subfolder of `src/`.
    - [x] Address (if necessary)
    - [ ] Transaction (if necessary)
    - [ ] Signer
- [x] Write unit tests for Address. Put them in a subfolder of `tests/`.
- [ ] Write unit tests for Transaction/Signer. Put them in a subfolder of `tests/`.
- [x] Add relevant constants in `TWCoinType`, `TWP2SHPrefix`, `TWEthereymChainID`, `TWHRP`, etc., as necessary.
- [x] Return correct curve and purpose in `src/Coin.cpp`.
- [x] Implement address validation and derivation in `src/Coin.cpp`.
- [x] Implement coin configuration `src/include/TWCoinTypeConfiguration.cpp`.
- [x] Write interface header in `include/TrustWalletCore` and implement the interface in `src/interface`.
    - [x] Address interface (if necessary).
    - [x] Signing interface.
- [x] Validate generated code in Android an iOS projects.
- [ ] Write integration tests for each.

**Comment by hewigovens** [comment]
@ArtemGoryunov the links in the issue are still about Nano

**Comment by ArtemGoryunov** [comment]
@hewigovens thanks, fixed
