### ISSUE TITLE
TrustWallet iOS app collapses when connecting with WalletConnect

### ISSUE THREAD

**Issue by dedicatedguy** [TrustWallet/wallet-core#447]
## Expected Behavior

When trying to connect with WalletConnect after scanning the QR code and clicking "send test transaction" in the website, the app crashes.

## Current Behavior

Instead of proceeding with the test, the app suddenly crashes. This shouldn't be happening.

## Possible Solution

A better integration with WalletConnect should be implemented to prevent the app from crashing when using WalletConnect.

## Steps to Reproduce (for bugs)

1. Download the TrustWallet app from the iOS App Store

2. Visit https://example.walletconnect.org/

3. Click Connect to WalletConnect and scan the QR with the TrustWallet iOS app.

4. Click "send test transaction" in WalletConnect.

Videos:

iPad POV: https://www.youtube.com/watch?v=t8VjPBiZX0s

Computer with WalletConnect POV: https://www.youtube.com/watch?v=P-t6DHhiZQs

Video where the 2 devices can be seen at the same time: https://www.youtube.com/watch?v=3BhvAggi_wU 

## Context

This issue affected me because I wasn't able to use/test WalletConnect.

The integration with WalletConnect should be improved.

**Comment by dedicatedguy** [comment]
@vikmeup I don't think it is the iPad. What makes you think that?

**Comment by vikmeup** [comment]
@dedicatedguy This issue has been fixed on the iOS app and will be released this week. 

on iPad, if `popoverPresentationController` not specified for alert view controller, it just crashes the app.

**Comment by alexanderbez** [comment]
Hey @vikmeup 👋 

I'm looking into using TrustWallet for a Cosmos webapp. Any chance you can point me to the resolved issue for the iOS app?

**Comment by vikmeup** [comment]
Does Cosmos webapp supports WalletConnect? Can you provide content that you are signing?

**Comment by alexanderbez** [comment]
@vikmeup this will be a simple MEW like webapp used to generate and sign Cosmos txs. 

I don't have anything to show you atm, but just wanted to know if TrustWallet iOS app will work with walletconnect and be able to provide me signing functionality?

**Comment by vikmeup** [comment]
Yes! We are able to support it, this would be awesome! We would need to add cosmos models on app side to support signing.  I will message you in tendermint slack group tonight for details

**Comment by alexanderbez** [comment]
Cool! So as of right now, if I establish a connection through wallet-connect, I can’t sign cosmos messages? Thanks!
