### ISSUE TITLE
Wallet connect personal_sign

### ISSUE THREAD

**Issue by olaf89** [TrustWallet/wallet-core#461]
## Expected Behavior

personal_sign should display same message and return same signature when using built-in browser as well as walletconnect

Initially reported to walletconnect repo https://github.com/WalletConnect/walletconnect-monorepo/issues/141 When using personal_sign text is displayed as a hex value instead of plain text.

## Current Behavior
Message is displayed as hex

## Steps to Reproduce (for bugs)

```
1. Sign message with personal_sign using walletconnect
2.
3.
```

## Your Environment

iOS latest trust wallet version

**Comment by hewigovens** [comment]
Thanks for the report, can you share an example json rpc request?

**Comment by olaf89** [comment]
So when signing message "test", which is sent as "0x74657374" which is 0x prefixed hex

This is the rpc request
```
{
    "id": 5,
    "jsonrpc": "2.0",
    "method": "personal_sign",
    "params": [
        "0x0000000000085d4780b73119b644ae5ecd22b376",
        "0x74657374"
    ]
}
```

Then the approval dialog is showing and im asked to confirm text "0x74657374", when in fact i should see "test".

**Comment by hewigovens** [comment]
@olaf89 Trust expects to sign `params[0]`, metamask also gives a warning

> The eth_personalSign method requires params ordered [message, address]. This was previously handled incorrectly, and has been corrected automatically. Please switch this param order for smooth behavior in the future."

**Comment by olaf89** [comment]
Yes there are 2 bugs at the moment, 
1. walletconnect is reverting the order of params thats why in my example i had to make it also reverted to have the text signed. This is reported in WalletConnect/walletconnect-monorepo#141
.
2. Issue that i am reporting here is that instead of displaying the text, i am presented with the hex value.

**Comment by hewigovens** [comment]
this will be fixed in next release
