### ISSUE TITLE
Transactions hangs when using walletconnect

### ISSUE THREAD

**Issue by olaf89** [TrustWallet/wallet-core#462]
originally reported to walletconnect repo https://github.com/WalletConnect/walletconnect-monorepo/issues/142

I tried integrating walletconnect for my dapp. I was using trust wallet on iOS for testing. I was able to connect and read account. Unfortunately When i tried to use eth_sendTransaction there was no response and i was never asked for confirmation on the wallet. 

I tried using sendTransaction api.
```
walletConnector.sendTransaction({data, gas, from , to })
```

as well as sendCustomRequest
```
walletConnector.sendCustomRequest({
    id,
    jsonrpc,
    method: "eth_sendTransaction",
    params: [{ data, gas, from, to }]
})
```

@pedrouid mentioned

> I've also experienced this which is caused by when you're missing a field on the transaction object. However this should not happen as the only fields that are strictly required are the from and data fields.

**Comment by hewigovens** [comment]
Thanks for the report, we will handle optional fields

**Comment by hewigovens** [comment]
@olaf89 btw, it's `gasLimit` not `gas`

**Comment by hewigovens** [comment]
Hi, after some discussions, we think it's better to let the dapp to pass all the values, this keeps the behaviors across all the wallets (gasPrice preference, nonce etc)

**Comment by olaf89** [comment]
in Ethereum JSON RPC spec its 'gas' https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction.

Should the dapp track nonce then? This is not current behaviour and for example metamask is even ignoring provided nonce.

The built in browser works without passing this optional values, will it be changed as well? I was expecting the built in browser and walletconnect should work the same way.

I am afraid this stricter parameters requirements this will make it harder to adopt walletconnect, cause now you might need to change more code in the app to add gas tracking, nonce tracking, gas estimation.

**Comment by hewigovens** [comment]
I think Ethereum JSON RPC spec is a bit outdated for `gasLimit`. We did a light version for wallet connect, you will see we just show a transaction `digest`, we might unify the behavior, but it would takes more time than I expected

**Comment by vikmeup** [comment]
I think this is an issue with ethereum/web3 spec itself, wallet itself should only be responsible for signing transactions on what’s provided and don’t change provided input for signing. 

Dapp should be responsible to calculate all the information it needs, it should be all abstracted into web3 module itself and developers won’t even know about it. 

Currently Binance DEX + WalletConnect has a great example of being only responsible for signing what’s being provided.

**Comment by olaf89** [comment]
Can you provide me with a link to the JSON RPC spec that you are using?

**Comment by hewigovens** [comment]
@olaf89 I don't have a new spec, it just doesn't match defacto implementation in metamask or walletconnect (https://docs.walletconnect.org/client-sdk#send-transaction-eth_sendtransaction)

**Comment by olaf89** [comment]
I am using sendCustomRequest, method and the 'gas' property its even showed in the example
https://docs.walletconnect.org/quick-start/dapps wallet

**Comment by olaf89** [comment]
Same with metamask docs https://metamask.github.io/metamask-docs/API_Reference/JSON_RPC_API

**Comment by hewigovens** [comment]
> I am using sendCustomRequest, method and the 'gas' property its even showed in the example
> https://docs.walletconnect.org/quick-start/dapps wallet
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/73e0c581b02107ee76f1d77281d3facfc460f64e/68747470733a2f2f6170702e676974626f6f6b2e636f6d2f73686172652f73706163652f7468756d626e61696c2f2d4c4a4a65436a634c72723533446354314d6c372e706e67">**[Dapps (Browser)](https://docs.walletconnect.org/quick-start/dapps)**Quick Start For Dapps with Examples

nice, the doc is out of sync again @pedrouid

**Comment by hewigovens** [comment]
please try latest iOS build from App Store, only from and data are required fileds now
