### ISSUE TITLE
Add support for I/O Coin

### ISSUE THREAD

**Issue by iocrypto** [TrustWallet/wallet-core#47]
Name: <a href="https://www.iocoin.io">I/O Coin</a>
<br>HD Derivation Scheme:
<br>Symbol: IOC
<br>Documentation: <a href="https://github.com/IOCoin/DIONS">IOC</a>

## Checklist

- [ ] Implement functionality in C++. Put it in a subfolder of `src/`.
    - [ ] Address (if necessary)
    - [ ] Transaction (if necessary)
    - [ ] Signer
- [ ] Write unit tests. Put them in a subfolder of `tests/`.
- [ ] Add relevant constants in `TWCoinType`, `TWP2SHPrefix`, `TWEthereymChainID`, `TWHRP`, etc., as necessary.
- [ ] Return correct curve and purpose in `src/Coin.cpp`.
- [ ] Implement address validation and derivation in `src/Coin.cpp`.
- [ ] Implement coin configuration `src/include/TWCoinTypeConfiguration.cpp`.
- [ ] Write interface header in `include/TrustWalletCore` and implement the interface in `src/interface`.
    - [ ] Address interface (if necessary).
    - [ ] Signing interface.
- [ ] Validate generated code in Android an iOS projects. Write integration tests for each.

**Comment by vikmeup** [comment]
@iocrypto please provide all the details described in the template: https://github.com/TrustWallet/wallet-core/wiki/Adding-Support-for-a-New-Blockchain

Are you planning to work on this integration?

**Comment by iocrypto** [comment]
going over the details now. I will be working on this.

**Comment by vikmeup** [comment]
@iocrypto Sounds great! Feel free to join our telegram group @walletcore if you have questions, our devs available anytime!

**Comment by hewigovens** [comment]
Hi, This issue is a month old, any updates? Would you mind if we close it for now?

**Comment by Wizfarm** [comment]
> Hi, This issue is a month old, any updates? Would you mind if we close it for now?
We are on Trezor integration almost ready for the pull request making some final adjustments https://github.com/trezor/blockbook/pull/137#issuecomment-476749618

**Comment by iocrypto** [comment]
Hi, We have submitted a pull request to Trezor last week and have been addressing review feedback since then. We have one more issue remaining which is to write some standard unit tests. So next couple of days we expect to have our pull request accepted if all good.

**Comment by Wizfarm** [comment]
> Hi, This issue is a month old, any updates? Would you mind if we close it for now?

Trezor has merged our code, clear for Trust to proceed https://github.com/trezor/blockbook/pull/137/commits/e4904d8abed6d616320eff81206716d3ea4fa43f

**Comment by iocrypto** [comment]
Hi, Just an update on where we are now :
we've been busy last two weeks implementing support for I/O Coin in blockbook. Martin is now testing our pull request changes so far no problems. 

I have forked wallet-core and will next implement the necessary changes in there as per your guidelines.

**Comment by iocrypto** [comment]
Hi, quick update, we added Address.h and Address.cpp as well as associated unit tests for first phase of PR.

**Comment by iocrypto** [comment]
quick update, code for Address.cpp and Address.h as well as unit tests was reviewed and accepted. This was approved and merged into trust wallet master.
Now we are on the interface associated changes.
