### ISSUE TITLE
Enable eva cash image

### ISSUE THREAD

**Issue by mcmich** [TrustWallet/wallet-core#471]
Eva Cash is an erc20 token and we love to make our token logo visible to trust wallet users and price.

 

theevacash.com

https://etherscan.io/token/0xba14b245d449965bdbeb630ebe135b569474f5b1

https://coinmarketcap.com/currencies/eva-cash/

Image link.  https://i.imgur.com/0jCpmcs.jpg

Expected Behavior

## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

**Comment by hewigovens** [comment]
please upload your icon here: https://github.com/TrustWallet/tokens
