### ISSUE TITLE
Android library for minSdkVersion

### ISSUE THREAD

**Issue by GHChrisSu** [TrustWallet/wallet-core#482]
'com.trustwallet.walletcore:walletcore:0.10.0'

The current android support minsdk is 23, I want to know why? My project right now is 19, and will be suit for most of android devices, I'm afraid of lead some problem for me change to 19

looking for help, thanks

**Comment by vikmeup** [comment]
I would highly recommend using Android 6 and higher for providing a wallet with a better security mechanism. 

We do not plan to support outdated Android SDK's
