### ISSUE TITLE
pod 'TrustWalletCore' not found

### ISSUE THREAD

**Issue by Kerita** [TrustWallet/wallet-core#493]
I add ```pod 'TrustWalletCore'```  to Podfile,

 and then ```pod install```,

but cannot found this package

```
$ pod search TrustWalletCore
[!] Unable to find a pod with name, author, summary, or description matching `TrustWalletCore`
```

**Comment by hewigovens** [comment]
try `pod install --repo-update`

**Comment by Kerita** [comment]
Thank you. Another problem.

```
$ pod install
Analyzing dependencies
Downloading dependencies
Installing SwiftProtobuf (1.5.0)
Installing TrustWalletCore (0.12.0)
[!] The 'Pods-tempWallet' target has libraries with conflicting names: libtrustwalletcore.a.

```

**Comment by hewigovens** [comment]
what's your cocoapods version? try to update to 1.7.1

**Comment by liehuntianshi** [comment]
$ pod install
Analyzing dependencies
Downloading dependencies
Installing SwiftProtobuf (1.5.0)
Installing TrustWalletCore (0.12.0)
[!] The 'Pods-tempWallet' target has libraries with conflicting names: libtrustwalletcore.a.

//===========================================
$ pod --version
1.7.1
How can I solve this problem?

**Comment by hewigovens** [comment]
can you share your Podfile?

**Comment by liehuntianshi** [comment]
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tempWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'TrustWalletCore'

  # Pods for tempWallet

  target 'tempWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tempWalletUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
//===================================
Thank you very much.

**Comment by hewigovens** [comment]
please uncomment `use_frameworks!`

**Comment by liehuntianshi** [comment]
Thank you so much
