### ISSUE TITLE
Wallet Core Compile Error

### ISSUE THREAD

**Issue by FinancialBlock** [TrustWallet/wallet-core#494]
We have been working on trying to install the wallet core to our repo using Xcode 9.4 and it will not compile. When we update our Xcode it makes our entire code not work or compile can I get a fix to this it seems like you get one or the other with this update

**Comment by hewigovens** [comment]
Hi, we don't have any plan to support old Xcode, can you update to Xcode 10? or try the prebuilt binary in cocoapods

**Comment by FinancialBlock** [comment]
Thank you I am running 10.2 right now I will rebuild it and let you know how it works out.
