### ISSUE TITLE
Add support for

### ISSUE THREAD

**Issue by bitzec** [TrustWallet/wallet-core#514]
## Description
Zcash 2.0 fork on sapling mpc
Monthly blockreward decreas 5-50% 

Name:

HD Derivation Scheme:

Symbol:
 https://github.com/bitzec/bitzec
http://explorer.bitzec.org
Documentation:

Reason: because bzc bitzec
The binary digit zero knowledge electronic currency   : )
## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by hewigovens** [comment]
please check our [requirements](https://developer.trustwallet.com/wallet-core/newblockchain#requirements), it looks like bitzec is not even listed in CMC

**Comment by bitzec** [comment]
Its on coinpaprika.com
