### ISSUE TITLE
undefined method `filter' in master branch

### ISSUE THREAD

**Issue by Woo-ing** [TrustWallet/wallet-core#518]
I got this error when I do generate-files after pulled master branch,
./tools/generate-files 
(erb):88:in `block in <main>': undefined method `filter' for #<Array:0x00007fabaa981928> (NoMethodError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/erb.rb:864:in `result'
        from codegen/bin/coins:28:in `block in <main>'
        from codegen/bin/coins:25:in `each'
        from codegen/bin/coins:25:in `<main>'

How should I do?

**Comment by hewigovens** [comment]
Hi, can you install ruby 2.6.3?

**Comment by Woo-ing** [comment]
@hewigovens  thanks, It's works.
