### ISSUE TITLE
Support for Black Lion Coin, Waves Token

### ISSUE THREAD

**Issue by BlackLionFounder** [TrustWallet/wallet-core#52]
## Expected Behavior
1. Be able to add BlackLionCoin tokens into the wallet.

## Context

We're trying to accomplish a simple process that our customers can buy our tokens and eventually exchange for Black Lion Coffees.

**Comment by hewigovens** [comment]
Could you please follow other coin request issues? and add details as more as possible. You can click the link from readme.

**Comment by BlackLionFounder** [comment]
> Could you please follow other coin request issues? and add details as more as possible. You can click the link from readme.

I'm sorry, I don't understand.
