### ISSUE TITLE
Bug: Handling Multiple transactions for Zilliqa on Android

### ISSUE THREAD

**Issue by edisonljh** [TrustWallet/wallet-core#522]
Thank you for support Zilliqa mainnet zils!

## Current Behavior

When you try to send more than one transactions within a block, only one of the transactions is confirmed. The rest will never be confirmed, and will hence remain stuck on the wallet as "pending"

## Possible Solution

In a Zilliqa network, double spending and sharding friendly transactions relies on the concept of "nonces". Account nonce (64-bits) is a counter that is initialised to 0, and increments with the number of transactions sent from an account. 

For example, if I send 3 transactions, the `nonce` of the payload should hence be _i_, _i_ + 1, _i_ + 2, where _i_ is the nonce of the first transaction.

The bug is likely raised because the application does not cater for increasing nonce _within_ a block. Currently, the implementation seems to be fetching for the current balance and nonce, and then sending a transaction with nonce + 1. However, this also means that if we are sending three transactions in sequence, the three transactions will have the same nonce, resulting in two of them being rejected by the blockchain. This happens because the chain has not confirmed the first transaction, and the account nonce will remain the same.

To solve it, you might have to keep an internal counter to track the expected nonce value. Psuedo code:
1. Send `GetBalance` from the network to obtain current nonce value, _i_ and store it as an internal counter _c_
2. User sends transaction. Increase _c_ by one and send payload. 
3. Set internal counter as _c_ + 1
4. Repeat 2-3 as long as transactions occur at the same block
5. Once the new block is mined, check if the new nonce === _c_
6. If it is, check if the transactions sent by the wallet are confirmed by the chain. If it is not, remove the transaction from the wallet (remove from pending)
7. If new nonce !== _c_, then one of the transactions failed. Remove that transaction from the "pending" pool

## Steps to Reproduce (for bugs)

Send more than one transaction from trust wallet for mainnet zil. 
Only one of the transactions will get confirmed, the others will fail. For the transactions which failed, it will forever remain on the wallet application as "pending"

## Context

Maybe begin with removing the transactions that are not confirmed instead of leaving it as "pending" forever on the wallet application.
Properly keeping track of nonces is hard and might require a lot of hours to solve it.

## Your Environment

Galaxy S10, Android 9

**Comment by hewigovens** [comment]
Thanks for reporting, will address this soon

**Comment by wowa1234567** [comment]
Entschuldigung für verspetung

hewig <notifications@github.com> schrieb am Di., 18. Juni 2019, 04:12:

**Comment by hewigovens** [comment]
We have fixed this in both Android and iOS, will be included in future releases

**Comment by edisonljh** [comment]
Thank you!

**Comment by vikmeup** [comment]
Will be released in the next few days.
