### ISSUE TITLE
Null pointer dereference on sign for Zcoin, Litecoin and Dash

### ISSUE THREAD

**Issue by eddywm** [TrustWallet/wallet-core#523]
```

2019-06-19 23:14:57.406 8611-8611/? A/DEBUG: Cause: null pointer dereference
eax 00000000  ebx c672afec  ecx cb692898  edx e6491e10
edi 00000019  esi 00000000
ebp c576e108  esp c576df80  eip c6356e0f
```

`(TW::Bitcoin::TransactionSigner<TW::Bitcoin::Transaction>::sign(TW::Bitcoin::Script, unsigned int, TW::Bitcoin::Proto::UnspentTransaction const&)+719)j92LpIAYhqU_cWuEGadOJg==/lib/x86/libTrustWalletCore.so `

```
(TW::Bitcoin::TransactionSigner<TW::Bitcoin::Transaction>::sign()+925)
2019-06-19 23:14:57.436 8611-8611/? A/DEBUG:     #02 pc 002ec68e  /data/app/com.wallet.crypto.trustapp-j92LpIAYhqU_cWuEGadOJg==/lib/x86/libTrustWalletCore.so 
```

`(TWBitcoinTransactionSignerSign+62)j92LpIAYhqU_cWuEGadOJg==/lib/x86/libTrustWalletCore.so (Java_wallet_core_jni_BitcoinTransactionSigner_sign+97)`

**Comment by hewigovens** [comment]
not set correct coin type in SigningInput
