### ISSUE TITLE
Bitcoin::Address() Produces incorrect address for private key

### ISSUE THREAD

**Issue by nezero** [TrustWallet/wallet-core#532]
## Expected Behavior

From the private key `0x4646464646464646464646464646464646464646464646464646464646464646` i would expect the the code to produce the a  bitcoin address (not a Segwit address) of `191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r`

## Current Behavior

Currently the code appears to produce a bitcoin address of `1JHMeqKunF2Up6zxnMQGhJu5667BXz98YQ`

## Steps to Reproduce (for bugs)

Add the following test to CoinAddressDerivationTests.cpp

```
...
#include "Bitcoin/Address.h"
...

TEST(Coin, DeriveBitcoinAddress) {
    const auto privateKey = PrivateKey(parse_hex("0x4646464646464646464646464646464646464646464646464646464646464646"));
    const auto address = Bitcoin::Address(privateKey.getPublicKey(TWPublicKeyTypeSECP256k1), TW::p2pkhPrefix(TWCoinTypeBitcoin)).string();
    EXPECT_EQ(address, "191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r");
}
```

Run the test and observe its failure.
## Context

While attempting to add the DeepOnion blockchain to the project, I noticed that a similar test for DeepOnion address's failed.

I noticed there was only a test for generating Segwit address' for bitcoin so I created a test for a regular Bitcoin address. 

I followed the process laid out [here](https://en.bitcoin.it/wiki/Wallet_import_format) to generate a WIF private key using the raw private key mentioned above. The WIF being `5JMEedKT4F1YJ9tzySE333ATNVgXXSu8Hp1MnVMXDeQbF4NddpL`

I imported the WIF into Bitcoins electrum wallet and it generated the following bitcoin address `191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r`

I've also used another project [mcdalla's CryptoTools](https://github.com/mcdallas/cryptotools) to generate the bitcoin address using the following python script.

```
from btctools import generate_keypair, push, script_to_address, OP
from ECDSA.secp256k1 import PrivateKey, PublicKey

private = PrivateKey.from_hex('4646464646464646464646464646464646464646464646464646464646464646')
print(private.hex())
print(private.wif())
public = private.to_public()
print(public.hex(True))
print(public.to_address('P2PKH'))

``` 

It produced the following output.

```
4646464646464646464646464646464646464646464646464646464646464646
5JMEedKT4F1YJ9tzySE333ATNVgXXSu8Hp1MnVMXDeQbF4NddpL
024bc2a31265153f07e70e0bab08724e6b85e217f8cd628ceb62974247bb493382
191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r
```

As the derived Bitcoin address is the same as electrum's, I took the assumption that there is possibly an issue with wallet-core code.

I added some debug to the wallet-core code to print out the raw compressed public key and it matches the one generated by the cryptotools library.

```
[ RUN      ] Coin.DeriveBitcoinAddress
TWPublicKeyTypeSECP256k1
Private Key: 4646464646464646464646464646464646464646464646464646464646464646
Public Key: 024bc2a31265153f07e70e0bab08724e6b85e217f8cd628ceb62974247bb493382
/Users/User/Documents/workspace/wallet-core/tests/CoinAddressDerivationTests.cpp:18: Failure
Expected equality of these values:
  address
    Which is: "1JHMeqKunF2Up6zxnMQGhJu5667BXz98YQ"
  "191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r"
[  FAILED  ] Coin.DeriveBitcoinAddress (1 ms)
```

This leads me to suspect the there is possibly a bug somewhere in the encoding of the public Address rather than generating the public key its self.

I will update the ticket if I find any more info.

## Your Environment

All this was investigated in an OSX environment.

**Comment by hewigovens** [comment]
Hi, I just tested it with http://bitpay.github.io/bitcore-playground/app/#/address and got the address `1JHMeqKunF2Up6zxnMQGhJu5667BXz98YQ `

**Comment by nezero** [comment]
Interesting, using Bitcoin Core I got this.

```
importprivkey 5JMEedKT4F1YJ9tzySE333ATNVgXXSu8Hp1MnVMXDeQbF4NddpL "wallet-core"

getaddressesbylabel wallet-core
{
  "191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r": {
    "purpose": "receive"
  }
}
```

**Comment by hewigovens** [comment]
hmm, let me check this

**Comment by hewigovens** [comment]
@nezero I find the reason, wallet core always uses compressed public key for bitcoin address, so if you comment out public key type check in `Base58Address.h`

```c++
    /// Initializes a  address with a public key and a prefix.
    Base58Address(const PublicKey& publicKey, const Data& prefix) {
//        if (publicKey.type != TWPublicKeyTypeSECP256k1) {
//            throw std::invalid_argument("Bitcoin::Address needs a compressed SECP256k1 public key.");
//        }
        const auto data = publicKey.hash(prefix, Hash::sha256ripemd);
        std::copy(data.begin(), data.end(), bytes.begin());
    }
```
And update your test:

```c++
TEST(Coin, DeriveBitcoinAddress) {
    const auto privateKey = PrivateKey(parse_hex("0x4646464646464646464646464646464646464646464646464646464646464646"));
    const auto address = Bitcoin::Address(privateKey.getPublicKey(TWPublicKeyTypeSECP256k1Extended), TW::p2pkhPrefix(TWCoinTypeBitcoin)).string();
    EXPECT_EQ(address, "191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r");
}
```

**Comment by nezero** [comment]
Ok, thanks for clearing that up, I had forgotten you needed to append a version byte to the private key when creating the WIF to get the compressed public key! 

Just verified what you've told me in many ways!

Thanks again.

**Comment by mamumi** [comment]
> ## Expected Behavior
> From the private key `0x4646464646464646464646464646464646464646464646464646464646464646` i would expect the the code to produce the a bitcoin address (not a Segwit address) of `191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r`
> 
> ## Current Behavior
> Currently the code appears to produce a bitcoin address of `1JHMeqKunF2Up6zxnMQGhJu5667BXz98YQ`
> 
> ## Possible Solution
> ## Steps to Reproduce (for bugs)
> Add the following test to CoinAddressDerivationTests.cpp
> 
> ```
> ...
> #include "Bitcoin/Address.h"
> ...
> 
> TEST(Coin, DeriveBitcoinAddress) {
>     const auto privateKey = PrivateKey(parse_hex("0x4646464646464646464646464646464646464646464646464646464646464646"));
>     const auto address = Bitcoin::Address(privateKey.getPublicKey(TWPublicKeyTypeSECP256k1), TW::p2pkhPrefix(TWCoinTypeBitcoin)).string();
>     EXPECT_EQ(address, "191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r");
> }
> ```
> 
> Run the test and observe its failure.
> 
> ## Context
> While attempting to add the DeepOnion blockchain to the project, I noticed that a similar test for DeepOnion address's failed.
> 
> I noticed there was only a test for generating Segwit address' for bitcoin so I created a test for a regular Bitcoin address.
> 
> I followed the process laid out [here](https://en.bitcoin.it/wiki/Wallet_import_format) to generate a WIF private key using the raw private key mentioned above. The WIF being `5JMEedKT4F1YJ9tzySE333ATNVgXXSu8Hp1MnVMXDeQbF4NddpL`
> 
> I imported the WIF into Bitcoins electrum wallet and it generated the following bitcoin address `191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r`
> 
> I've also used another project [mcdalla's CryptoTools](https://github.com/mcdallas/cryptotools) to generate the bitcoin address using the following python script.
> 
> ```
> from btctools import generate_keypair, push, script_to_address, OP
> from ECDSA.secp256k1 import PrivateKey, PublicKey
> 
> private = PrivateKey.from_hex('4646464646464646464646464646464646464646464646464646464646464646')
> print(private.hex())
> print(private.wif())
> public = private.to_public()
> print(public.hex(True))
> print(public.to_address('P2PKH'))
> ```
> 
> It produced the following output.
> 
> ```
> 4646464646464646464646464646464646464646464646464646464646464646
> 5JMEedKT4F1YJ9tzySE333ATNVgXXSu8Hp1MnVMXDeQbF4NddpL
> 024bc2a31265153f07e70e0bab08724e6b85e217f8cd628ceb62974247bb493382
> 191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r
> ```
> 
> As the derived Bitcoin address is the same as electrum's, I took the assumption that there is possibly an issue with wallet-core code.
> 
> I added some debug to the wallet-core code to print out the raw compressed public key and it matches the one generated by the cryptotools library.
> 
> ```
> [ RUN      ] Coin.DeriveBitcoinAddress
> TWPublicKeyTypeSECP256k1
> Private Key: 4646464646464646464646464646464646464646464646464646464646464646
> Public Key: 024bc2a31265153f07e70e0bab08724e6b85e217f8cd628ceb62974247bb493382
> /Users/User/Documents/workspace/wallet-core/tests/CoinAddressDerivationTests.cpp:18: Failure
> Expected equality of these values:
>   address
>     Which is: "1JHMeqKunF2Up6zxnMQGhJu5667BXz98YQ"
>   "191EQkjT83LL2pxfy7NWUkDTv2fFRPs39r"
> [  FAILED  ] Coin.DeriveBitcoinAddress (1 ms)
> ```
> 
> This leads me to suspect the there is possibly a bug somewhere in the encoding of the public Address rather than generating the public key its self.
> 
> I will update the ticket if I find any more info.
> 
> ## Your Environment
> All this was investigated in an OSX environment.

i tested test_address.py but not work
ModuleNotFoundError: No module named 'btctools'
how to install btctools?
