### ISSUE TITLE
Add support for FIO

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#545]
FIO is an EOS fork, https://fio.foundation/

**Comment by wowa1234567** [comment]
Sorry this is another issue how does the magic cube work without any equal
wallet trus or anything else with app N26 i want to make myself as easy as
possible can you give me app combination there for typing the font white
would be really cool 😘😁

hewig <notifications@github.com> schrieb am Di., 16. Juli 2019, 06:17:

**Comment by catenocrypt** [comment]
"The FIO Protocol is a decentralized, open-source blockchain protocol that  [...]  sits alongside other blockchains as a service layer, and is integrated purely on the application-level through a standardized set of SDKs and APIs."

**Comment by hewigovens** [comment]
Reference docs:

1. https://developers.fioprotocol.io/api/API-spec
2. https://developers.fioprotocol.io/sdks
3. https://developers.fioprotocol.io/wallet-integration-guide/options

**Comment by catenocrypt** [comment]
See also umbrella-issue in internal:  https://github.com/trustwallet/internal/issues/213
