### ISSUE TITLE
"No Accounts Available"

### ISSUE THREAD

**Issue by cbarraford** [TrustWallet/wallet-core#546]
Related to https://github.com/WalletConnect/walletconnect-monorepo/issues/163

## Expected Behavior
Use walletconnect to connect my trust wallet to a dapp.

## Current Behavior
When I connect, I get a "no accounts available" error (see related issue above).

**Comment by hewigovens** [comment]
Make sure you use multi-coin wallet

**Comment by cbarraford** [comment]
thanks @hewigovens Im using the wallet "Trust" on iOS. Is there a different wallet to use?

**Comment by hewigovens** [comment]
multi coin is a wallet type in Trust, you can have ethereum only wallet too

**Comment by wowa1234567** [comment]
Can you recommend key program please 🗝️😅

hewig <notifications@github.com> schrieb am Di., 16. Juli 2019, 10:26:

**Comment by cbarraford** [comment]
@hewigovens sorry for the newbie question, where do i find a multi-coin wallet, if not the iOS app?

**Comment by cbarraford** [comment]
Nevermind, found it. Here is where it is for future googlers. 

![e3ac5224-b03f-42e6-beb3-b6aded50c066](https://user-images.githubusercontent.com/246180/61884138-f6136000-aefb-11e9-9a43-8003032bb83f.jpg)

**Comment by fdharamshi** [comment]
> Nevermind, found it. Here is where it is for future googlers.
> 
> ![e3ac5224-b03f-42e6-beb3-b6aded50c066](https://user-images.githubusercontent.com/246180/61884138-f6136000-aefb-11e9-9a43-8003032bb83f.jpg)

But what is I want to connect BSC to the Dapp? On connecting using the multi-coin wallet I can't use the BSC on the DAPP. How do I change that?

**Comment by happyeric77** [comment]
Might I have a question, 
when I use multi-coin wallet, it is actually able to connect to DAPP.
But I found that the web3-provider of wallectconnect became not able to point to correct chain ID. See the screen shot below:
<img width="791" alt="Screen Shot 2021-06-13 at 17 52 08" src="https://user-images.githubusercontent.com/52155607/121801112-9568aa00-cc70-11eb-800a-964c5ceb0b9f.png">

**Comment by vavepl** [comment]
bump

**Comment by pasevin** [comment]
same issue here.

**Comment by nlukic97** [comment]
Just bumped into this.

Tried to connect TrustWallet to a dApp I'm building using WalletConnect V2 (QR code scan).

It didn't work when I passed in the avalanche fuji chain as an argument to the WalletConnectV2 connector, but worked fine when I pass in Avalanche Mainnet.

**Comment by juliocarneiro** [comment]
> Just bumped into this.
> 
> Tried to connect TrustWallet to a dApp I'm building that implements WalletConnect V2 (QR code scan).
> 
> It didn't work (No accounts Available) when I passed in the avalanche Fuji chain as an argument to the WalletConnectV2 connector, but worked fine when I pass in Avalanche Mainnet.

same problem here!

**Comment by nebolax** [comment]
Same issue
