### ISSUE TITLE
Change default bitcoin derivationPath on  Android

### ISSUE THREAD

**Issue by wangpeng1582655** [TrustWallet/wallet-core#548]
On Android:
CoinType.derivationPath()  is return the default path，hao can I create account use bip44 
derivation path protocol for all coins.

**Comment by hewigovens** [comment]
Try `HDWallet.getKey(derivationPath)`

**Comment by wangpeng1582655** [comment]
HDWallet hdWallet = new HDWallet(mnemonic,pass);
        CoinType coinType = CoinType.createFromValue(CoinType.BITCOIN.value());
        String derivationPath = "m/44'/0'/0'/0/0";
        PrivateKey privateKey = hdWallet.getKey(derivationPath);
        String address = coinType.deriveAddress(privateKey);
        Log.e(TAG,"address=" + address);

address=bc1q8tlethru8qd0m9z4mdp0gq3mejjmq8t5dvp0nj

but user bip44 derivationPath to get privateKey，then can not  get bip44 protocol address , the address is still bip84 format address.

**Comment by wangpeng1582655** [comment]
@hewigovens

**Comment by hewigovens** [comment]
Don't use `coinType.deriveAddress` it's sugar method to use default configs, if you want to get legacy address, try to use `BitconAddress` class directly

**Comment by wangpeng1582655** [comment]
@hewigovens    Missing private key.
        StoredKey storedKey = StoredKey.load(mPath);
        if(storedKey == null){
            return;
        }
        HDWallet hdWallet = storedKey.wallet(pass);
        Bitcoin.SigningInput.Builder signInputBuilder = Bitcoin.SigningInput.newBuilder()
                .setAmount(30000)
                .setHashType(0x01)
                .setToAddress("1BFj5g3Ak8z6n4B1UQRj9qSXGYFQTp2JMB")
                .setChangeAddress("17gWULND2wzNYWmPsxA1owdz3mbRCRreov")
                .setByteFee(10);

        //Add privateKey
        String derivationPath = "m/44'/0'/0'/0/0";
        PrivateKey privateKey = hdWallet.getKey(derivationPath);
        signInputBuilder.addPrivateKey(ByteString.copyFrom(privateKey.data()));

        Bitcoin.OutPoint outPoint = Bitcoin.OutPoint.newBuilder()
                 /*当前utxo交易的tx_id = fd617d375eb41b72b546235f9b61e969415b0771a737f9fdce81e7ba598a2791*/
                .setHash(ByteString.copyFrom(Numeric.hexStringToByteArray("fd617d375eb41b72b546235f9b61e969415b0771a737f9fdce81e7ba598a2791")))
                .setIndex(0)
                .setSequence((int) Long.MAX_VALUE)
                .build();
        /*script_hex : 76a9146d86e63f39f6ee390ae83c05a537768eb2946e0c88ac*/
        String script_hex = "76a9146d86e63f39f6ee390ae83c05a537768eb2946e0c88ac";
        Bitcoin.UnspentTransaction utxo = Bitcoin.UnspentTransaction.newBuilder()
                .setAmount(50000)
                .setOutPoint(outPoint)
                .setScript(ByteString.copyFrom(Numeric.hexStringToByteArray(script_hex)))
                .build();
        signInputBuilder.addUtxo(utxo);

        Bitcoin.SigningInput signingInput = signInputBuilder.build();
        BitcoinTransactionSigner signer = new BitcoinTransactionSigner(signingInput);
        Common.Result result = signer.sign();
        Log.e(TAG,"Sign Error = " + result.getError());
       Sign Error = Missing private key.

I create privateKey base on bip44  and added the key,but is still throw Missing private key, is anywhere wrong?

**Comment by hewigovens** [comment]
can you check `TestBitcoinSigning.kt`? make sure the private key matches the utxo

**Comment by hewigovens** [comment]
`BitcoinTransactionSigner` doesn't care about how the private key is derived

**Comment by wangpeng1582655** [comment]
@hewigovens   
StoredKey.decryptMnemonic(String password)    input wrong password, the application crash，
Crash message:
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3396 (com.trustwallet)

Is there a method for verifying passwords?

**Comment by hewigovens** [comment]
@wangpeng1582655 can you create another issue? it's a different question

**Comment by hewigovens** [comment]
https://github.com/TrustWallet/wallet-core/issues/554
