### ISSUE TITLE
Refactor Aeternity implementation

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/wallet-core#549]
1. Aeternity decimal is 18, to avoid potential overflow we should use type `uint256_t` for `amount`, `fee`, `ttl`, `nonce` in `Transaction`, and `bytes` in `Aeternity.proto`

2. Fix `Transaction::encode` especially 0 case, it seems that we don't need to call `RLP::encode` for each field

3. Add more transaction encoding / signing tests, and at least one mainnet tx

4. Update block explorer to official `https://explorer.aepps.com/#/`

5. Add random address test from block explorer to `TEST(Coin, ValidateAddressAeternity)`

**Comment by Defuera** [comment]
@hewigovens regarding point 1. I've updated code according go sdk,
amount and ttl is now uint_256, but kept nonce and fee as uint_64, see https://github.com/aeternity/aepp-sdk-go/blob/d4be4d627b/aeternity/transactions_test.go#L28

**Comment by hewigovens** [comment]
@Defuera for 1, don't forget to update `Aeternity.proto` and `TWAeternitySigner.cpp`, we need to convert bytes to uint256_t
