### ISSUE TITLE
StoredKey.decryptMnemonic crashed in jni

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/wallet-core#554]
> StoredKey.decryptMnemonic(String password) input wrong password, the application crash，Crash message:
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 3396 (com.trustwallet)

**Comment by hewigovens** [comment]
@wangpeng1582655 can you try master? it will return null for invalid password

**Comment by wangpeng1582655** [comment]
@hewigovens 
Is there a new lib? I used gradle dependencies.

**Comment by hewigovens** [comment]
not yet, we will prepare new build after #551
