### ISSUE TITLE
How should I do to get the privatekey string from HDWallet?

### ISSUE THREAD

**Issue by hengmu** [TrustWallet/wallet-core#557]
## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

## Your Environment

I'm Android,how should I do if I want to get Coin privatekey that is string not byte[] from HDWallet,and I use  the way named decryptPrivateKey() from the StoredKey,but I get mnemonic but not privatekey.My walletcore version is 0.12.1.

**Comment by hewigovens** [comment]
`HDWallet.getKey` and `HDWallet.getKeyForCoin`
