### ISSUE TITLE
import wallet from to use importPrivateKey()

### ISSUE THREAD

**Issue by hengmu** [TrustWallet/wallet-core#558]
## Expected Behavior

I want to import wallet to use importPrivateKey() which is from StoredKey.

## Current Behavior

I use importPrivateKey(),but there is some problem.

## Steps to Reproduce (for bugs)

1. I use importHDWallet(),import wallet success.
2. I get the PrivateKey from that imported HDWallet.
3. I use the PrivateKey.data() and use importPrivateKey() want to import wallet,but there is some problem.

> error-msg:JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x7b

## Your Environment

Android,walletcore  version:0.12.1

**Comment by hewigovens** [comment]
How do you get the private key from HDWallet? Can you paste your code?
