### ISSUE TITLE
Binance Chain - Add ability to mint, burn tokens functionality

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#560]
Add support in our current protobufs

**Comment by hewigovens** [comment]
https://docs.binance.org/api-reference/transactions.html#amino-types

**Comment by vikmeup** [comment]
@hewigovens would you be able to work on adding all most common operations to create/mint tokens? this might be necessary functionality for managing tokens

**Comment by hewigovens** [comment]
sure, will work on this later
