### ISSUE TITLE
[Cosmos] Add undelegate functionality

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/wallet-core#561]
Based on https://github.com/cosmos/cosmos-sdk/blob/1a7f31f7c8de1feded6b7c0df45c71a5f40c61df/x/staking/types/msg.go

**Comment by johnnynanjiang** [comment]
I planned to start on this work yesterday, unfortunately have to postpone till next week due to a work assignment.

**Comment by leoneparise** [comment]
Already fixed on https://github.com/TrustWallet/wallet-core/pull/565
