### ISSUE TITLE
How to build BCH or BSV transaction

### ISSUE THREAD

**Issue by hengmu** [TrustWallet/wallet-core#563]
## Expected Behavior

I want to build bch or bsv transaction,but there is no example for android.

## Current Behavior

val signerBuilder = Bitcoin.SigningInput.newBuilder()
            .setAmount(55_000)
            .setHashType(0x01)
            .setToAddress("1GDCMHsTLBkawQXP8dqcZtr8zGgb4XpCug")
            .setChangeAddress("1CSR6tXqngr1CfwVF23V4bQotttJmzXqpf")
            .setByteFee(10)
In this way,if I want to build BCH or BSV transaction,what the HashType value is? is 0x01 or other?

## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

**Comment by hewigovens** [comment]
TWSignatureHashTypeAll (0x01) | TWSignatureHashTypeFork (0x40)
