### ISSUE TITLE
Bitcoin signed binary data  miss script type

### ISSUE THREAD

**Issue by wangpeng1582655** [TrustWallet/wallet-core#564]
@hewigovens 
Bitcoin sign success，but the binary data decoded missing script type 
the code:
```kotlin
                Bitcoin.SigningInput.Builder signInputBuilder = Bitcoin.SigningInput.newBuilder()
                        .setAmount(sendAmount)
                        .setHashType(0x01)
                        .setToAddress(toAddress)
                        .setChangeAddress(changeAddress)
                        .setByteFee(byteFee)
                        .setUseMaxAmount(isUseMaxAmount)
                        .addAllUtxo(utxos)
                        .addAllPrivateKey(privateKeys);
                Bitcoin.SigningInput signingInput = signInputBuilder.build();

                BitcoinTransactionSigner signer = new BitcoinTransactionSigner(signingInput);

             Common.Result result = signer.sign();
```
Signed success
binary data:

0100000001fd617d375eb41b72b546235f9b61e969415b0771a737f9fdce81e7ba598a2791000000006a47304402207abc356bd414e113dee3979561b6ab6b5c7b0de6d45c4fb8822b201fa7063fc802200bacf5610bd2474c619e75a127718d58fdd64a07d16f672d53768df8abe4806b01210379a16ab0205329f5bcc8e596f2834c6eb504ffa4c233add4476259303f79f222ffffffff013c9e0000000000001976a914707a3559494373e3fdbadde2218b73a4b5f9f27b88ac00000000

but  the binary data decoded  for inputs missing script type:
on https://live.blockcypher.com/btc/decodetx/
```json
{
    "addresses": [
        "1BFj5g3Ak8z6n4B1UQRj9qSXGYFQTp2JMB"
    ], 
    "block_height": -1, 
    "block_index": -1, 
    "confirmations": 0, 
    "double_spend": false, 
    "fees": 0, 
    "hash": "3a5152c9d63ca3773d02ef4a28149f79175629955554ed7b610b7593038a82f9", 
    "inputs": [
        {
            "age": 0, 
            "output_index": 0, 
            "prev_hash": "91278a59bae781cefdf937a771075b4169e9619b5f2346b5721bb45e377d61fd", 
            "script": "47304402207abc356bd414e113dee3979561b6ab6b5c7b0de6d45c4fb8822b201fa7063fc802200bacf5610bd2474c619e75a127718d58fdd64a07d16f672d53768df8abe4806b01210379a16ab0205329f5bcc8e596f2834c6eb504ffa4c233add4476259303f79f222", 
            "script_type": "empty", 
            "sequence": 4294967295
        }
    ], 
    "outputs": [
        {
            "addresses": [
                "1BFj5g3Ak8z6n4B1UQRj9qSXGYFQTp2JMB"
            ], 
            "script": "76a914707a3559494373e3fdbadde2218b73a4b5f9f27b88ac", 
            "script_type": "pay-to-pubkey-hash", 
            "value": 40508
        }
    ], 
    "preference": "low", 
    "received": "2019-08-01T03:37:28.514694454Z", 
    "relayed_by": "18.212.147.36", 
    "size": 191, 
    "total": 40508, 
    "ver": 1, 
    "vin_sz": 1, 
    "vout_sz": 1
}
```

**Comment by hewigovens** [comment]
Did you call `BitcoinScript.buildPayToPublicKeyHash` or `BitcoinScript.buildPayToWitnessPubkeyHash` to get the correct script?

**Comment by wangpeng1582655** [comment]
`        Bitcoin.SigningInput.Builder signInputBuilder = Bitcoin.SigningInput.newBuilder()
                .setAmount(30000)
                .setHashType(0x01)
                .setToAddress("1BFj5g3Ak8z6n4B1UQRj9qSXGYFQTp2JMB")
                .setChangeAddress("17gWULND2wzNYWmPsxA1owdz3mbRCRreov")
                .setByteFee(10)
                .setUseMaxAmount(true);

        //Add privateKey
        String derivationPath = "m/44'/0'/0'/0/0";
        PrivateKey privateKey = hdWallet.getKey(derivationPath);
        signInputBuilder.addPrivateKey(ByteString.copyFrom(privateKey.data()));

        Bitcoin.OutPoint outPoint = Bitcoin.OutPoint.newBuilder()
                 /*当前utxo交易的tx_id = fd617d375eb41b72b546235f9b61e969415b0771a737f9fdce81e7ba598a2791*/
                .setHash(ByteString.copyFrom(Numeric.hexStringToByteArray("fd617d375eb41b72b546235f9b61e969415b0771a737f9fdce81e7ba598a2791")))
                .setIndex(0)
                .setSequence((int) Long.MAX_VALUE)
                .build();

        Bitcoin.UnspentTransaction utxo = Bitcoin.UnspentTransaction.newBuilder()
                .setAmount(50000)
                .setOutPoint(outPoint)
                /* script_hex : 76a9146d86e63f39f6ee390ae83c05a537768eb2946e0c88ac */
                .setScript(ByteString.copyFrom(Numeric.hexStringToByteArray("76a9146d86e63f39f6ee390ae83c05a537768eb2946e0c88ac")))
                .build();
        signInputBuilder.addUtxo(utxo);

        Bitcoin.SigningInput signingInput = signInputBuilder.build();

        BitcoinTransactionSigner signer = new BitcoinTransactionSigner(signingInput);
Common.Result result = signer.sign();
Bitcoin.SigningOutput signingOutput = result.getObjects(0).unpack(Bitcoin.SigningOutput.class);`

the script_hash geted from api：
https://chain.so/api/v2/get_tx_unspent/BTC/1Az8FtHoKDC18jas7UDVL9qZMVHJUjSzQc
`{
  "status" : "success",
  "data" : {
    "network" : "BTC",
    "address" : "1Az8FtHoKDC18jas7UDVL9qZMVHJUjSzQc",
    "txs" : [
      {
        "txid" : "fd617d375eb41b72b546235f9b61e969415b0771a737f9fdce81e7ba598a2791",
        "output_no" : 0,
        "script_asm" : "OP_DUP OP_HASH160 6d86e63f39f6ee390ae83c05a537768eb2946e0c OP_EQUALVERIFY OP_CHECKSIG",
        "script_hex" : "76a9146d86e63f39f6ee390ae83c05a537768eb2946e0c88ac",
        "value" : "0.00050000",
        "confirmations" : 2397,
        "time" : 1563331541
      }
    ]
  }
}`
the binary data:

0100000001fd617d375eb41b72b546235f9b61e969415b0771a737f9fdce81e7ba598a2791000000006a473044022023a649ebb33ded87075ff4ec50d01a4b350b7e243919389c163a71af19ed4d7c0220684b658a33fc6684904665ac3d7b0ec288bdbb3558500cb2bd53d59b24fb7cf301210379a16ab0205329f5bcc8e596f2834c6eb504ffa4c233add4476259303f79f222ffffffff0230750000000000001976a914707a3559494373e3fdbadde2218b73a4b5f9f27b88ac4c450000000000001976a9144949941eac7693e2d5ed208d7e86c4fca04f938288ac00000000

Use the above tools decoded，the result is also missing script_type，and the transaction can not broadcast.  the script should be right，if not，how can i get the correct script.

**Comment by hewigovens** [comment]
1. can you try to reverse utxo tx id bytes (fd617d375eb41b72b546235f9b61e969415b0771a737f9fdce81e7ba598a2791)? 
2. did you set unlocking script to `Bitcoin.SigningInput.script`?

This is a mainnet tx for your reference: https://github.com/TrustWallet/wallet-core/blob/master/tests/interface/TWBitcoinCashTests.cpp#L92
