### ISSUE TITLE
How to bulid ETH transaction?

### ISSUE THREAD

**Issue by hengmu** [TrustWallet/wallet-core#571]
Ethereum.SigningInput signingInput = Ethereum.SigningInput.newBuilder()
                .setPrivateKey(ByteString.copyFrom(new PrivateKey(bytes).data()))
                .setToAddress("0xD6FF417CA3253FfB1A36783BCB97134191CeeFD2")
                .setChainId(ByteString.copyFrom(BitcoinUtil.hexStringToByteArray("0x1")))
                .setNonce(ByteString.copyFrom(BitcoinUtil.hexStringToByteArray("0x1")))
              .setGasPrice(ByteString.copyFrom(BitcoinUtil.hexStringToByteArray("0x04a817c800")))
                .setGasLimit(ByteString.copyFrom(BitcoinUtil.hexStringToByteArray("0x5208")))
                .setAmount(ByteString.copyFrom(BitcoinUtil.hexStringToByteArray("0x3e8")))
                //.setPayload(ByteString.copyFrom(BitcoinUtil.toByteArray(encodedFunction)))
                .build();
        Ethereum.SigningOutput sign = EthereumSigner.sign(signingInput);

This is my code for build ETH trasaction,I get the sign.getEncoded() data and to publish,but there is some error.

## Current Behavior

Publish Error: Error: Returned error: invalid sender
This is the error msg.

## Steps to Reproduce (for bugs)

```
1.
2.
3.
```

## Your Environment

Android  0.12.1

**Comment by hewigovens** [comment]
Can you submit a well formatted issue?
