### ISSUE TITLE
Add support for TON

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#585]
- https://test.ton.org/
- https://github.com/ton-blockchain/ton
- https://test.ton.org/testnet

**Comment by catenocrypt** [comment]
Merged PR #691 .
Complete TON Address support, general infrastructure (Cell structure, hashing, serialization), and also creation of account initialization message.  Tested on TON testnet2.
Note: mainnet launch is delayed to Q2 2020.
Closing issue.
