### ISSUE TITLE
Feature request: Add Cosmos arbitrary message signature

### ISSUE THREAD

**Issue by faith0811** [trustwallet/wallet-core#587]
## Overview
Since Cosmos has released its Cosmos-SDK, developers can easily fork and modify a Tendermint based blockchain with their own logic.
These blockchains share the basic Tendermint standard transaction struct, but different ``msg`` struct in the Std/Tx.
In Trust wallet, only 4 existed msg types used by official Cosmos chain are available. And it would be nice if arbitrary messages is supported in Trust wallet.

## Expected Behavior
With calling method ``walletConnector.trustSignTransaction(network, tx)``, I can send any payload into Cosmos StdTx.msg by adding arbitrary message into `tx` struct.

## Current Behavior
I cannot send any other msgs except the 4 official ones.

## Possible Solution
Add a new Message type in protobuf, let it pass the checks, assemble the Std/Tx and pass it to the final signature function.

**Comment by vikmeup** [comment]
@hewigovens any thoughts on this how to make this work? 

should we create a separate method that will encode json and sign? similar idea for bnb chain

**Comment by hewigovens** [comment]
Yes, add a raw json input

**Comment by vikmeup** [comment]
Should this be a standard for all chains? 

Something like this to define in proto:

```
Enum Transaction {
    case standard(definedTransaction TransactionModel)
    case custom(string JSON) 
}
```

?
