### ISSUE TITLE
Initialiser for HDWallet with data is not working correctly

### ISSUE THREAD

**Issue by cbhaiji** [trustwallet/wallet-core#632]
**Describe the bug**
```
HDWallet.init(data: Data, passphrase: String)
```
This method is not generating HDWallet correctly.

**To Reproduce**
```
let mnemonic = "fit toy aspect clerk auto advice chimney inspire jar bitter correct area"
let mnemonicSeed = HDWallet.init(data: , passphrase: "").seed

let wallet = HDWallet.init(data: mnemonicSeed, passphrase: "")
let mnemonicFromWallet = wallet.mnemonic
```

**Expected behavior**
If the wallet was generated correctly `mnemonicFromWallet` would have been equal to `mnemonic` but it is not the case.

**Comment by hewigovens** [comment]
Hi, if you look at the code of `HDWallet(data, passphrase)`, `data` is not `seed`, it's binary data of a mnemonic, so it's not a bug

**Comment by cbhaiji** [comment]
@hewigovens what should be the encoding type for converting mnemonic from `String` to `Data` type?

I tried the following but did not work at all:
```
(lldb) po HDWallet.init(data: DASHTests.mnemonic.data(using: String.Encoding.ascii)!, passphrase: "").mnemonic
"\u{07}"

(lldb) po HDWallet.init(data: DASHTests.mnemonic.data(using: String.Encoding.utf8)!, passphrase: "").mnemonic
"\u{07}"
```

So I am still not able to use `HDWallet.init(data: Data, passphrase: String)` method.

Please let me know what can I do here.

Thanks in advance!

**Comment by hewigovens** [comment]
take a look at  `mnemonic_from_data` in `bip39.c`, it's not a string representation

**Comment by cbhaiji** [comment]
@hewigovens do we have a test case to check `HDWallet.init(data: Data, passphrase: String)` method?

**Comment by hewigovens** [comment]
```swift
let data = Data(hexString: "00000000000000000000000000000000")!
let phrase = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"

let hd1 = HDWallet(data: data, passphrase: "")
let hd2 = HDWallet(mnemonic: phrase, passphrase: "")

XCTAssertEqual(hd1.seed, hd2.seed)
```
https://github.com/trezor/python-mnemonic/blob/master/vectors.json
