### ISSUE TITLE
Wrong BTC and LTC BIP44 paths

### ISSUE THREAD

**Issue by cbhaiji** [trustwallet/wallet-core#633]
**Describe the bug**
For BTC and LTC derivationPath is not correct. Hence it is not generating correct address as well.

**To Reproduce**
```
CoinType.bitcoin.derivationPath()
"m/84\'/0\'/0\'/0/0"

CoinType.litecoin.derivationPath()
"m/84\'/2\'/0\'/0/0"
```

**Expected behavior**
```
CoinType.bitcoin.derivationPath()
"m/44\'/0\'/0\'/0/0"

CoinType.litecoin.derivationPath()
"m/44\'/2\'/0\'/0/0"
```

**Additional context**
For following currencies, ethereum and dash it is giving correct derivationPath henec generating correct address as well

```
CoinType.ethereum.derivationPath()
"m/44\'/60\'/0\'/0/0"
CoinType.dash.derivationPath()
"m/44\'/5\'/0\'/0/0"
```

**Comment by hewigovens** [comment]
We're using [bip84](https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki) for bitcoin and litecoin

**Comment by cbhaiji** [comment]
@hewigovens is there any way we can generate bip44 addresses from this library? It is since for all our coins we are using `BIP44`.
Also, can we generate addresses for `Bitcoin Testnet`?

**Comment by hewigovens** [comment]
Yes, you can change the path in `coins.json` and use `BitcoinAddress`, some forks have done this; we don't support testnet

**Comment by amsqcsq** [comment]
你好，新版本没有coins.json了，我应该在哪里修改这个路径和生成测试网的地址。
