### ISSUE TITLE
I have issue in using wallet-core ios project.

### ISSUE THREAD

**Issue by fullstact69** [trustwallet/wallet-core#637]
**Describe the bug**
I have tried to implement wallet-core in swift4.2 and swift5. 
But there are many bugs in there.
After I installed pod, I can see many bugs and undefined symbols in installed pod sdk.
How can I resolve these bugs?

**Comment by vikmeup** [comment]
Create a new issue and provide details according to the guidelines

**Comment by fullstact69** [comment]
I attached the image with many issues.
![Capture](https://user-images.githubusercontent.com/53449197/64585618-59433f80-d34e-11e9-9899-44e43296ae6c.PNG)

**Comment by fullstact69** [comment]
How can I resolve this?
