### ISSUE TITLE
Add support for Elastos

### ISSUE THREAD

**Issue by peter-strauss** [trustwallet/wallet-core#644]
## Description

**Name**: 
Elastos

**HD Derivation Scheme**: 
BIP32

**Symbo**l: 
ELA

**Documentation**: 
https://github.com/elastos/Elastos.ELA/tree/master/docs

**Reason:**
Elastos has a rapidly growing ecosystem, is very secure due to being merge-mined with Bitcoin,
and has introduced ETH and NEO sidechains anyone can build DApps on without having to learn a new programming language.

In addition, a peer-to-peer network for communication, Decentralized IDs and a fully decentralized data storage bring new opportunities for developers and users.

## Checklist

- [ ] Add the coin definition to coins.json and TWCoinType.
- [ ] Implement functionality in C++. Put it in a subfolder of src/.
	- [ ] Address (if necessary).
	- [ ] Transaction (if necessary).
	- [ ] Signer.
- [ ] Write unit tests. Put them in a subfolder of tests/.
	- [ ] Mnemonic phrase - > Address derivation test. Put this test in the CoinTests.cpp file.
	- [ ] Transaction signing tests, at least a mainnet transaction test.
- [ ] Add relevant constants in TWEthereumChainID, TWCurve, etc., as necessary.
- [ ] Implement address validation and derivation.
	- [ ] Implement validation and derivation in src/Coin.cpp.
	- [ ] Add tests for validation in tests/CoinAddressValidationTests.cpp and derivation in tests/CoinAddressDerivationTests.cpp.
- [ ] Write interface header in include/TrustWalletCore and implement the interface in src/interface.
	- [ ] Address interface (if necessary).
	- [ ] Signing interface.
- [ ] Validate generated code in Android an iOS projects. Write integration tests for each.
- [ ] Upload coin icon to trustwallet/assets if necessary.

**Comment by vikmeup** [comment]
https://developer.trustwallet.com/wallet-core/newblockchain#requirements

**Comment by peter-strauss** [comment]
@vikmeup The requirement "The native coin is listed in the top 30 coins on CoinMarketCap." was "The native coin is listed in the top **100** coins on CoinMarketCap." when the issue was submitted. 

https://developer.trustwallet.com/wallet-core/newblockchain#requirements was updated just 5 days ago. Its even still in Google Cache.

![image](https://user-images.githubusercontent.com/33350987/65866466-1684ee00-e375-11e9-9043-bc32cd84cd36.png)

Anyways, if Elastos reaches top 30, I'll let you know.

Cheers
