### ISSUE TITLE
The address of Waves blockchain is different from official wallet 

### ISSUE THREAD

**Issue by scottphc** [trustwallet/wallet-core#651]
**Describe the bug**
The address of Waves blockchain is different from https://dex.wavesplatform.com/import/restore when use the same private key.

**To Reproduce**
priKey: `EWEAHcDsr87HrUaQxCFSrc77cbDvWfSzgQCB45HAt6xu`
official wallet address: `3P2GGkhPLJpvCn8ngZxESSi6L4DGUZsV3ft`
wallet-core address: `3PBVtpnRcEhpQoSXVRTA4R4VDVJzsA91KK4`

**Expected behavior**
should be same with Waves official wallet

**Comment by vikmeup** [comment]
@scottphc official wallet does not follow standards of BIP44.

Wallet Core strictly follows BIP44 standard and you can see derivation path here: https://github.com/trustwallet/wallet-core/blob/master/coins.json#L980

**Comment by hewigovens** [comment]
How do you get the address from the test private key in wallet core, can you show us the code?

**Comment by scottphc** [comment]
@vikmeup I think it's not related to BIP44.
@hewigovens here is the code in swift.
```
let data = Data(hexString: "c8a4a75823932bae11046c07cc2dad446e8b269e73b030e57800ac628808b866")
let key = PrivateKey(data: data!)!
let address = CoinType.waves.deriveAddress(privateKey: key)
```

**Comment by hewigovens** [comment]
What's the encoding of `EWEAHcDsr87HrUaQxCFSrc77cbDvWfSzgQCB45HAt6xu`?

**Comment by scottphc** [comment]
base58

**Comment by Tolsi** [comment]
Hi, @scottphc ! I'm a developer from waves core team who did this integration. @vikmeup is right, official waves wallet uses non-standard keys derivation scheme from the seed that does not support hardware wallets like Ledger, in which all keys are created according to bip44. In trustwallet, all keys also work according to bip44. If you have a desire and the developers will allow it, we can somehow integrate the legacy waves seed into a trustwallet. @vikmeup what do you think?

**Comment by Tolsi** [comment]
I missed that question about the private key. I will check

**Comment by Tolsi** [comment]
Yes, I remembered, there's a normal ed25519 private key here, but waves use X25519. [Look his for details](https://github.com/wavesplatform/nanos-app-waves/wiki/Integration-manual#cryptography-protocol).

**Comment by abhijitrath791** [comment]
Is there any way to Derive private key from any website by inputting derivation path like iancoleman. sorry, I am not a coder.😭
