### ISSUE TITLE
Codegen new blockchain template

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#653]
When you add a new blockchain support, you have to manually create all the files (most of the time is copy / paste)

It would be nice to have a scaffolding does that for you, like `create-react-app`, we can also code defines and models

**Comment by catenocrypt** [comment]
Added script codegen/bin/newcoin, with skeleton templates.  Branch newcoin-653, PR #719 .
Note: protobuf aruments are not included.
Todo: update documentation.

**Comment by catenocrypt** [comment]
PR #719 merged, new templates added, keeping issue open for documentation.

**Comment by hewigovens** [comment]
let's track the document issue here: https://github.com/trustwallet/developer/issues/65
