### ISSUE TITLE
Add Base32 C++ wrapper

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#655]
In wallet core, Nimiq, Stellar and Algorand need to use base32 encoding, it would be nice to have a C++ `Base32` class like `Base58` or wrapper like `Base64`

**Comment by catenocrypt** [comment]
Since this is implemented elsewhere (Trezor), and used from there, no need to reinvent the wheel, I just create a wrapper for it.

**Comment by catenocrypt** [comment]
#697 merged
