### ISSUE TITLE
Add basic manual How to use Android implementation

### ISSUE THREAD

**Issue by tomaz-dev** [trustwallet/wallet-core#656]
In current README.md there is the only info how to add dependency to build.gradle. There is none info how to use it.
Some minimal examples would be very helpful:
 - How to generate Bitcoin address.
 - How to create and sign Bitcoin transaction.
 - How to send Bitcoin transaction.
etc...

**Comment by hewigovens** [comment]
Take a look at tests: https://github.com/trustwallet/wallet-core/tree/master/android/app/src/androidTest/java/com/trustwallet/core/app
