### ISSUE TITLE
Xcode 11 Support

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#658]
Currently fails to run on Xcode 11

![IMAGE 2019-09-21 10:12:28](https://user-images.githubusercontent.com/1641795/65376724-5141a480-dc58-11e9-86d8-389022a552e1.jpg)

**Comment by hewigovens** [comment]
I think it's a cmake issue, can't set the `CMAKE_OSX_SYSROOT` with Xcode 11, current workaround is to set `CMAKE_OSX_SYSROOT` manually

**Comment by hewigovens** [comment]
created an issue here: https://gitlab.kitware.com/cmake/cmake/issues/19755
