### ISSUE TITLE
Add support for

### ISSUE THREAD

**Issue by defhouse** [TrustWallet/wallet-core#66]
## Description

Name:

HD Derivation Scheme:

Symbol:

Documentation:

Reason:

## Checklist

- [ ] Coin configuration
- - [ ] coin type / decimals
- - [ ] recommended tx block explorer
- [ ] Address
- - [ ] derived from bip39 phrases
- - [ ] from public key / string
- - [ ] validation
- [ ] Transaction
- - [ ] serialization
- - [ ] signing
- [ ] C interfaces
- - [ ] Validate generated code in Android and iOS projects
- [ ] Tests
- - [ ] Unit test
- - [ ] integration test ( Java / Swift)

**Comment by vikmeup** [comment]
Please follow the guidelines and fill out information for your coin/blockchain and reopen it.
