### ISSUE TITLE
Add support for Aion

### ISSUE THREAD

**Issue by ivan-trust** [TrustWallet/wallet-core#67]
Name: [Aion](https://aion.network/)
HD Derivation Scheme: BIP44 Coin / `425`
Symbol: `AION`

Checklist

* [ ]   Coin configuration
* * [ ]   coin type / decimals
* * [ ]   recommended block explorer ([example](https://mainnet.aion.network/#/dashboard))
* [ ]   Account / Address
* * [ ]   derived from bip39 phrases
* * [ ]   from public key / string
* * [ ]   validation
* [ ]   Transaction
* * [ ]   serialization
* * [ ]   signing
* [ ]   C interfaces
* * [ ]   Validate generated code in Android and iOS projects
* [ ]   Tests
* * [ ]   Unit test
* * [ ]   integration test ( Java / Swift)

**Comment by hewigovens** [comment]
It's done
