### ISSUE TITLE
Add support for BitcoinV (BTCV)

### ISSUE THREAD

**Issue by bitcoinVBR** [trustwallet/wallet-core#670]
Description:
BitcoinV is a more decentralized version of Bitcoin. The key to its decentralization is its ability to give out variable block rewards (VBR). VBR can be large or small. When set to large reward payout, the BitcoinV network starts to behave like a lottery system where many SOLO miners are scattered and decentralized trying to hit the BIG block reward payout.

Name: BitcoinV   http://bitcoinv.org

Derivation Scheme: Variable Block Rewards (VBR)

Symbol: BTCV

Documentation: 
BitcoinV is Bitcoin with VBR feature. All Bitcoin documentation still applies.

Reason to support: 
BitcoinV adds the VBR feature to Bitcoin that naturally creates more decentralization.

Code:
https://github.com/bitcoinVBR/bitcoinV

**Comment by vikmeup** [comment]
https://developer.trustwallet.com/wallet-core/newblockchain#requirements
