### ISSUE TITLE
Feature: Expand QR code to read amount, symbol & memo for binance chain.

### ISSUE THREAD

**Issue by kaiansaari** [trustwallet/wallet-core#674]
**Limitation:**
The current QR code scanner on trust wallet can only read on chain addresses eg. `tbnb1w6rcrjsk0hjdsgt8anmpl42t6p2fgf7d0vkxnp`.

**Gap:**
The QR scanner cannot read additional information eg. `asset`, `amount` & `memo` which could save the user time in manual entry.

**Impact:**
When providing some of the new use cases binance chain enables, not being able to provide a QR code with included `asset`, `amount` & `memo` creates a non-trivial challenge for users. The number of steps, time needed and mental effort required to input this information manually creates a high barrier/friction for users and increases the likelihood of errors.

Additionally, it creates a trust issue as some of the new applications require users to connect their wallet via keystore, ledger or wallet connect; which creates risk that the raw transaction is different from what the user expects. Putting the power in the users hands is important.

**Ideal Solution:**
Trust wallet should be able to read additional information necessary to complete a transaction including `address`, `asset`, `amount` and `memo`. This would reduce friction significantly and enable a whole new range of services on binance chain utilising the `memo` field.

Example format:
`o:tbnb1w6rcrjsk0hjdsgt8anmpl42t6p2fgf7d0vkxnp`
`a:RUNE-A1F`
`A:100.00000000`
`M:ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ABCDEFGHIJKLMNOPQRS`

![twexampleqr](https://user-images.githubusercontent.com/26814804/66174669-95419a00-e699-11e9-9b3c-0aac91eee822.png)

**Additional Context:**
The binance chain ecosystem is growing due to the availability of developer tooling, speed/performance, memo field and addition of new stable coins eg. TrueAUD, TrueHKD etc. These factors are conducive to building interesting applications around binance chain such as hedged escrow as seen with Canyacoin and THORChain's BEPSwap - Both utilise the binance memo field to give specific instructions to layer2 applications, as well as requiring (in some cases) specific amounts and assets.

With Binance chain recently upgrading their websocket & api to read memo fields, the opportunities are endless for layer 2 applications and Trust Wallet should prepare to add value via expanded QR capabilities.

**Example - Bep2Bot**
A simple example is the telegram @bep2bot which enables users to tip any Binance Chain BEP2 token. Currently the user will have to specify the asset and amount. 

With expanded QR capabilities we can remove this burden from the user and make it a 2 step process **Scan & Confim** to send any combination of address, asset, amount & memo.

![image](https://user-images.githubusercontent.com/26814804/66174289-9e316c00-e697-11e9-929d-b00d1052510b.png)
 
**Example - Canya Hedged Escrow:**
The new Canyacoin hedged escrow relies on memo fields to give instructions to the layer2 application including `CAN Amount`, `TrueUSD Value`, `Job ID`. 

The hedged escrow will protect the `TrueUSD` value of the assets and when the escrow is disbursed the asset quantity is adjusted up/down to maintain that `TrueUSD` price.

This could all be included in a QR code for the user to scan without them every connecting their wallet via ledger, wallet connect etc.

![image](https://user-images.githubusercontent.com/26814804/66174366-f36d7d80-e697-11e9-9999-7090f7325d32.png)

**Example - THORChain's BEPSwap:**
BEPSwap is currently in testnet and allows users to swap between any BEP2 asset using continuous liquidity pools. Swaps are currently performed using a memo instruction to specify the `asset` the users wishes to swap to, in addition to an optional `forwarding address`.

Again this could simply be a QR code, eliminating the need to unlock a users wallet via keystore to execute transactions in browser.

![image](https://user-images.githubusercontent.com/26814804/66174575-092f7280-e699-11e9-8625-0d69da04877c.png)

**Comment by vikmeup** [comment]
Currently you can pass two param into the qr code: `?amount=12.123&memo=123` - which is a standard on many wallets. 

This is a tricky use case to handle for different chains, formats and wallets. We do not plan to support any custom logic per QR code until we gonna develop a standard that covert many chains and have support for many wallets to integrate

But at the moment you can use `memo` field per your use case.

**Comment by kaiansaari** [comment]
Thanks @vikmeup. I wasn't aware of that. It would be great if you could support `asset` and then trust wallet could read everything from the QR code. Appreciate the speed of your reply!

**Comment by vikmeup** [comment]
Closing as it's not related to Wallet Core repo
