### ISSUE TITLE
Stellar account_merge

### ISSUE THREAD

**Issue by terorie** [trustwallet/wallet-core#685]
**Is your feature request related to a problem? Please describe.**
When emptying a Stellar account, the mandatory 1 XLM minimum balance remains stuck in the old account.

**Describe the solution you'd like**
The [account merge](https://www.stellar.org/developers/guides/concepts/list-of-operations.html#account-merge) operation type makes it possible to fully empty an account, not losing any XLM in the process.
When pressing send amount "Max" in Trust Wallet, we could set a "full" flag that instructs the Stellar signer in `wallet-core` to sent an account merge instead of a payment.

**Describe alternatives you've considered**
not applicable

**Additional context**
Some exchanges (for whatever stupid reason) don't support account merge transactions, and will burn funds sent with account merge. Maybe we should display a warning.
https://support.kraken.com/hc/en-us/articles/360023090812-Stellar-Lumens-XLM-account-merge

**Comment by hewigovens** [comment]
it might be ok to add it, but for normal users, your account should be always there once activated if you keep using a same recovery phrase

**Comment by vikmeup** [comment]
Feel free to implement this but as of now I will close this issue
