### ISSUE TITLE
Split coins.json to small files

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#698]
coins.json is 1000+ lines

**Comment by vikmeup** [comment]
it would looks like this ? 
`coins/ethereum.json`
`coins/bitcoin.json`

Having one file is ok too

**Comment by catenocrypt** [comment]
The advantage would be reduced risk of merge conflict on the coins.json file. On a second thought, I don't think it is worth the effort -- we don't have new coins that often, and long-living pending pull request should be avoided anyways.

**Comment by vikmeup** [comment]
Make sense!
