### ISSUE TITLE
WebAssembly support

### ISSUE THREAD

**Issue by EnoRage** [trustwallet/wallet-core#700]
**Is your feature request related to a problem? Please describe.**
Using wallet-core with Browser for web-based crypto wallets / operations with private keys

**Describe the solution you'd like**
Make a special build for WebAsm + examples of using at Browser

**Additional context**
Best option to start - made a research about compiling C++ to WebAsm. Trying to understands which parts of wallet-core are not supported. It is possible to replace them with [WEB Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) Also [this article](https://medium.com/@tdeniffel/pragmatic-compiling-from-c-to-webassembly-a-guide-a496cc5954b8) can help to start compiling C++ to WebAsm

**Comment by hewigovens** [comment]
Wasm is very promising, we will research this later

**Comment by catenocrypt** [comment]
Most similar browser-based wallets are Javascript based, but with that we would loose the synergy of wallet-core.  WebAsm is promising, but I have doubts because of thelibrary usage (boost) and heavy templating used.

**Comment by vikmeup** [comment]
I don't think that's possible at the moment, closing
