### ISSUE TITLE
Add the option to restore Stellar wallets by secret/private key

### ISSUE THREAD

**Issue by exegg** [trustwallet/wallet-core#705]
**Is your feature request related to a problem? Please describe.**
Somewhat related. I have a couple XLM addresses that only have secret keys as backups, not mnemonic, and these can't be restored on Trust Wallet since there's only the option to restore a mnemonic phrase.

**Describe the solution you'd like**
Well... Import by secret key.

**Describe alternatives you've considered**
Using other wallet like Guarda which I don't like as much as Trust...

**Additional context**
n/a

**Comment by hewigovens** [comment]
can you post this to https://feedback.trustwallet.com/ instead?
