### ISSUE TITLE
How do I introduce trust-core c++ code into my Golang project?

### ISSUE THREAD

**Issue by Jinxiansen** [trustwallet/wallet-core#707]
Hello !
How do I introduce `trust-core` **C++ language** code into my **Golang** project? 
Our project wants to access several of these currencies, but it won't work after trying.😔

```c++
> Executing task: clang++ ./tests/main.cpp -g <

In file included from ./tests/main.cpp:14:
In file included from /usr/local/include/gtest/gtest.h:62:
In file included from /usr/local/include/gtest/internal/gtest-internal.h:40:
/usr/local/include/gtest/internal/gtest-port.h:825:12: error: no member named 'make_tuple' in namespace 'std'
using std::make_tuple;
      ~~~~~^
/usr/local/include/gtest/internal/gtest-port.h:826:12: error: no member named 'tuple' in namespace 'std'
using std::tuple;
      ~~~~~^
/usr/local/include/gtest/internal/gtest-port.h:905:3: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  GTEST_DISALLOW_ASSIGN_(RE);
  ^
/usr/local/include/gtest/internal/gtest-port.h:671:34: note: expanded from macro 'GTEST_DISALLOW_ASSIGN_'
  void operator=(type const &) = delete
                                 ^
/usr/local/include/gtest/internal/gtest-port.h:948:3: warning: deleted function definitions are a C++11 extension [-Wc++11-extensions]
  GTEST_DISALLOW_COPY_AND_ASSIGN_(GTestLog);
  ^
 
/usr/local/include/gtest/internal/gtest-internal.h:1226:11: error: expected unqualified-id
constexpr bool RegisterTypedTestCase_P_IsDeprecated() { return true; }
          ^
/usr/local/include/gtest/internal/gtest-internal.h:1231:1: error: unknown type name 'constexpr'
constexpr bool InstantiateTypedTestCase_P_IsDeprecated() { return true; }
^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
81 warnings and 20 errors generated.
终端进程已终止，退出代码: 1
```

C++ Version:
```shell
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

macOS Version: **10.14.5**

Is there an example of c++ code for golang access trust? Or the solution, we need it very much!  🤔

> English is not my native language; please excuse typing errors.

**Comment by hewigovens** [comment]
Did you follow https://developer.trustwallet.com/wallet-core/contributing? it builds fine on macOS

**Comment by Jinxiansen** [comment]
@hewigovens 
I have tried this environment configuration, but I can't solve the current problem. 
Our requirement is to introduce the code of several currency transaction signatures in the `trust wallet` c++ language in the golang project, and then package it for iOS and Android APP, but It seems that I can only use the code of the golang reference `trust wallet` c++ language to write it again.🌝

**Comment by hewigovens** [comment]
We haven't tried calling from go code, it should work (after compiling)

- headers: `include/TrustWalletCore`
- libs: `build/lib*.a`

**Comment by Jinxiansen** [comment]
@hewigovens 
Hello, thank you very much for your suggestion. I tried to use the .a static library in golang, but I have the following error, the example code is [here](https://github.com/Jinxiansen/GoTrust)：

```go
Undefined symbols for architecture x86_64:
  "_TWHDWalletIsValid", referenced from:
      __cgo_63a67a486bb0_Cfunc_TWHDWalletIsValid in _x002.o
     (maybe you meant: __cgo_63a67a486bb0_Cfunc_TWHDWalletIsValid)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Process exiting with code: 1

```

**Comment by hewigovens** [comment]
A few things:

1. not just `libTrustWalletCore.a`, but also `libprotobuf.a`, `trezor-crypto/libTrezorCrypto.a`
2. link libc++ not libstdc++

**Comment by Jinxiansen** [comment]
But I did not find `trezor-crypto/libTrezorCrypto.a`

![WX20191101-194859](https://user-images.githubusercontent.com/16829428/68022913-ab666880-fce0-11e9-8916-0cd36db8b012.png)

**Comment by Jinxiansen** [comment]
In addition, I would like to ask you what compiler tool you are using. I want to try running the wallet-core project and see the compilation results.
However, it is currently not working in VSCode of macOS, and it encounters the most recent error.

**Comment by hewigovens** [comment]
full path: `build/trezor-crypto/libTrezorCrypto.a`, wallet core needs clang

**Comment by hewigovens** [comment]
Ok, I figured it out, try this code:

```go
package main

// #cgo CFLAGS: -I${SRCDIR}
// #cgo LDFLAGS: -L${SRCDIR} -lTrezorCrypto -lTrustWalletCore -lprotobuf -lc++
// #include "TWHDWallet.h"
// #include "TWString.h"
import "C"

import "fmt"

func main() {
	fmt.Print("I'm log.")
	test()
}

func test() {
	fmt.Println("--------------------")
	str := C.TWStringCreateWithUTF8Bytes(C.CString("L3fi366VNv7arRq5FSbiN6tcJJB4"))
	a := C.TWHDWalletIsValid(str)
	fmt.Println("Res = ", a)
}

```

**Comment by Jinxiansen** [comment]
![image](https://user-images.githubusercontent.com/16829428/68035458-9dbfdb80-fcfe-11e9-96c0-8f23dc15e7dc.jpg)

@hewigovens 

Thank you very much!  It's finally working!😋
