### ISSUE TITLE
How to get the string form of the private key ？

### ISSUE THREAD

**Issue by Jinxiansen** [trustwallet/wallet-core#708]
Hello !
How to get the string form of the private key？

 I found the **TWPublicKeyDescription** method, 
but did not find a similar `TWPrivateKeyDescription` method .

```C++
TWString *_Nonnull TWPublicKeyDescription(struct TWPublicKey *_Nonnull publicKey) {
    const auto string = TW::hex(publicKey->impl.bytes);
    return TWStringCreateWithUTF8Bytes(string.c_str());
}

```

I need to compile it as a `lib*.a` file for use in a golang project.

> English is not my native language; please excuse typing errors.

**Comment by hewigovens** [comment]
1. call `TWPrivateKeyData` to get and encode the data to hex string in go
2. fork wallet core and add similar method to `TWPrivateKey.h`

**Comment by Jinxiansen** [comment]
Yes, I added a similar method in `TWPrivateKey.h`

```C++
TW_EXPORT_PROPERTY
TWString *_Nonnull TWPrivateKeyDescription(struct TWPrivateKey *_Nonnull pk);

// 
TWString *_Nonnull TWPrivateKeyDescription(struct TWPrivateKey *_Nonnull pk) {
    const auto string = TW::hex(pk->impl.bytes);
    return TWStringCreateWithUTF8Bytes(string.c_str());
}

```

Thanks !
