### ISSUE TITLE
Update Protocol Buffers to latest stable version

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#721]
We're using 3.7.0 now, checklist:

1. tools/install-dependencies
2. Dockerfile
3. macOS / Linux CI

**Comment by catenocrypt** [comment]
Latest version is 3.10.1 (from Oct 29; for 3.11 only RCs exist yet)

**Comment by hewigovens** [comment]
should we leverage some package manager to easily update dependency? Hunter, vcpkg etc

**Comment by catenocrypt** [comment]
Update: protobuf 3.11.0 has been just released
https://github.com/protocolbuffers/protobuf/releases

**Comment by catenocrypt** [comment]
https://github.com/grpc/grpc/issues/21334  (created by me).
Grpc-protobuf 1.25 brings in protobuf 3.10, which has a bug on Android.
Options: 
* wait for new grpc-protobuf
* go with older protobuf 3.9.0, grpc-protobuf 1.24.

**Comment by catenocrypt** [comment]
Changes merged, builds completed, docker image also completed.  Closing issue.
