### ISSUE TITLE
Allow adding multiple accounts/wallets of the same currency

### ISSUE THREAD

**Issue by Joohansson** [trustwallet/wallet-core#727]
I did a thorough evaluation of the iOS wallet and specifically for Nano currency. I successfully imported the Trust 12-word mnemonic into a Ledger Nano S hardware wallet to check if the Nano was recovered. Then I did the opposite and imported a standard 24-word Ledger recovery phrase into Trust as a new wallet. It found the Nano account, so far so good. It's very useful you can recover like this between two completely different wallet solutions in case one of them breaks and you need fast recover. The limitation comes when you have multiple accounts on the Ledger, say Nano#1, Nano#2 and Nano#3. Trust will only derive the first one from the BIP39 phrase.

What about allowing Trust to add multiple accounts of the same currency. That way you could manually add Nano#1, Nano#2 and Nano#3 into Trust. Maybe also useful if you have one savings account and one spending account for example (not related to Ledger). Maybe works for other coins as well. All native Nano wallets support this feature.

**Comment by vikmeup** [comment]
Hey there! This is definitely is a great idea and it’s currently supported by Wallet Core itself to derive any account number. 

We considered to add accounts to TW app, but we find it as confusing UX and low usage from the end user. 

Thank you for sharing feedback!
