### ISSUE TITLE
Create wallet-core subspec to support only models for TrustSDK

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#728]
In order to revive our TrustSDK (https://github.com/trustwallet/TrustSDK-iOS/blob/master/TrustWalletSDK.podspec) we would need to have TrustSDK distributed to developers and it needs to be lightweight as it does not require any crypto magic since Trust Provider will be build in into wallets itself.

I would propose to have a separate pod spec that only contains all the models and protos

**Comment by hewigovens** [comment]
something like:
```ruby
pod 'TrustWalletCore/Core'  # C++
pod 'TrustWalletCore/Model' # move SwiftProtobuf dependency here
```

**Comment by vikmeup** [comment]
OR just:
```
pod 'TrustWalletCore'  # C++
pod 'TrustWalletCore/Model' # move SwiftProtobuf dependency here or TrustWalletCore/Types
```
