### ISSUE TITLE
[Research phrase] Lightning Network

### ISSUE THREAD

**Issue by vikmeup** [TrustWallet/wallet-core#73]
For better UX I'm leaning toward a custodial solution where the user would have an option to run their own node.

Example of the Hub: https://github.com/BlueWallet/LndHub

**Comment by johnnynanjiang** [comment]
> For better UX I'm leaning toward a custodial solution where the user would have an option to run their own node.
> 
> Example of the Hub: https://github.com/BlueWallet/LndHub

Would that be an option that the mobile app picks a node to connect to from a trusted source?
https://1ml.com/node?order=channelcount

**Comment by johnnynanjiang** [comment]
How to integrate Lightning network into a crypto project
https://medium.com/chlunetwork/bitcoin-lightning-network-tutorial-how-to-integrate-lightning-to-a-crypto-project-f48743c8644a

**Comment by johnnynanjiang** [comment]
The Lightning Hackday: Challenges and Solutions for Mobile Lightning Wallets
https://steemit.com/bitcoin/@cryptoexpert0/the-lightning-hackday-challenges-and-solutions-for-mobile-lightning-wallets

**Comment by hewigovens** [comment]
close for now

**Comment by IamRezaMousavi** [comment]
> close for now
@hewigovens Did you change your mind?😅

**Comment by IamRezaMousavi** [comment]
> close for now

Do you have any plan to add lightning network support?
