### ISSUE TITLE
ANDROID: java.lang.UnsatisfiedLinkError when using the published trust wallet core library

### ISSUE THREAD

**Issue by rikysya** [trustwallet/wallet-core#735]
Description:
Exception: `java.lang.UnsatisfiedLinkError: No implementation found for long wallet.core.jni.PrivateKey.nativeCreate()` on creating new Ethereum private key, or trying to call anything from `jni` pkg.

Steps to reproduce:
1)Add to your apps build gradle:
`dependencies {
    implementation 'com.trustwallet:wallet-core:0.12.24'
}`
2) Try to invoke any method that makes JNI call.

Context and environment:
Device: simulator(x86_64 arch)
Tried on android versions: 9.0, 8.0

**Comment by hewigovens** [comment]
Have you load wallet core? check the test:
```kotlin
System.loadLibrary("TrustWalletCore")
```

**Comment by rikysya** [comment]
Oh, thanks, it worked!
I thought that library did it internally.
