### ISSUE TITLE
error install cocoapods

### ISSUE THREAD

**Issue by oleksiivinogradov** [trustwallet/wallet-core#739]
Analyzing dependencies
Downloading dependencies
Installing SwiftProtobuf (1.3.1)
Installing TrustWalletCore (0.10.0)
[!] The 'Pods-' target has libraries with conflicting names: libtrustwalletcore.a.

**Comment by hewigovens** [comment]
Did you follow the guide? https://developer.trustwallet.com/wallet-core/contributing#before-you-start, if you can run `bootstrap.sh` successfully, you won't get this error

**Comment by ackratos** [comment]
https://github.com/trustwallet/wallet-core/issues/493#issuecomment-498546112
