### ISSUE TITLE
Provide a way to derive a coin address from a wallet, without retrieving private keys

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#740]
**Is your feature request related to a problem? Please describe.**

Not directly, it is motivated by security.  Minimalize passing around private keys as much as possible.

**Describe the solution you'd like**

Currently it is possible to obtain a derived private key from an HDWallet, and obtain an address from the private key.  These two steps should be combined into one.

**Describe alternatives you've considered**

**Additional context**

**Comment by hewigovens** [comment]
just need to add a shortcut method?

**Comment by catenocrypt** [comment]
A possible improvement for the future is to minimize private/secret exposure outside of WalletCore library.  Client apps could be shielded almost completely from secrets (except for the use case of obtaining recovery phrase for showing to user).  In all other cases references to a wallet, with secrets stored inside lib, would be enough.

Benefits:
* more explicit visibilty of usage of secrets
* more conscious usage of secrets by developers
* less exposure, less risk of secret leak type bugs
* simpler possibility of additional measures on secret storage in temp memory (e.g. always encrypted) 
* easier security audit.
Lib and client app are in the same memory space, so this in itself does not protect against potential compromise of app, but still beneficial for above reasons.

This would be a bigger change, future work.  The shortcut method asked in this issue is a small step, done now nonetheless.
