### ISSUE TITLE
Add support for Cardano

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#745]
## Description

Name:  Cardano (ADA)   https://www.cardano.org
HD Derivation Scheme:  BIP44  m/44/1815
Symbol:   ADA
Documentation:   https://github.com/vacuumlabs/cardano-crypto.js  https://github.com/vacuumlabs/adalite  https://daedaluswallet.io/
Reason:    https://twitter.com/TrustWalletApp/status/1199434970072322049

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by hewigovens** [comment]
you might need this: https://gist.github.com/hewigovens/f8d168b8d337292e0c12040c6dfaeb0f

**Comment by hewigovens** [comment]
https://github.com/Atomicwallet/cardano-crypto.js

**Comment by catenocrypt** [comment]
For address derivation, you may. try:
in walletconsole:

- coin ada
- newkey
- pubpri #
- addrpub #
Result:  Ae2tdPwUPEZ7n97UGCpGkDYuPW7HG7zFwxELZwvtyAE8L8Ypii5L94GdGyR
-
- setMnemonic cost dash dress stove morning robust group affair stomach vacant route volume yellow salute laugh
- addrDefault
Result:  Ae2tdPwUPEZ6RUCnjGHFqi59k5WZLiv3HoCCNGCW8SYc5H9srdTzn1bec4W

You can try this in adalite also:
- https://adalite.io/
- select Mnemonic
- enter above mnemonic
- Unlock
- check My Addresses (right side, a bit down), first address should be same as above

**Comment by catenocrypt** [comment]
Address part merged, signing part is still WIP #797 .

**Comment by catenocrypt** [comment]
To test tx creation:

- Create new Cardano address (rec. phrase, derived prikey, addr)
- Send some ADA to it
- check address&txs on https://cardanoexplorer.com
- put together new transaction, sign it with Signer -- see Cardano/SignerTests.cpp.
- push result to node, like this:

```shell
curl -d '{"txHash":"ebf58670ee1512d597876fe632e92790bd70568374bdbe5a69c5d8ed107607ee","txBody":"82839f8200d8185824825820a49bad3f69bbab0e4d3e51991ce7a1116c0fd322a7731246b92df455e67e686100ff9f8282d818582183581c0f1fdc075b3e562ff4c8dc6979b136aeedd087a7d3bf554f774b58eba0001abb7c9a121a007a12008282d818582183581c20b55a0bd5cbc39b58cdd8977e863aca7d387a5a0fc37a473eb72042a0001aa6fa2f8a1a001bece4ffa0818200d8185885825840835610e371e632d829eb63bf44ec39d0487c19d4d98b8dce9dd88d88414ce5bb1ae60957699bf72b212ca823520cf7d86af5d1304cd90248fe60bd1fe442870f584045b3fe46b52c839566e697cbe72e248cd0f01e10c7c5696c8f202fe9776602b63c5878f0e27869d1d9ff69c9773211406970742f7cc316690b9d9133794e4f0e"}' -H "Content-Type: application/json" https://adalite.io/api/txs/submit
```

**Comment by catenocrypt** [comment]
RCP API info:


Get transactions

curl https://cardanoexplorer.com/api/addresses/summary/<ADDRESS>

ex.:  curl https://cardanoexplorer.com/api/addresses/summary/Ae2tdPwUPEZLmY8zETphpoDsrE7pDv3PpufADh5bS41Xqajrgzm3MhJdgmw

curl -d '["Ae2tdPwUPEZLmY8zETphpoDsrE7pDv3PpufADh5bS41Xqajrgzm3MhJdgmw"]' -H "Content-Type: application/json" https://explorer2.adalite.io/api/bulk/addresses/utxo

Submit prepared raw TX

curl -d '{"txHash":"11dc0c05383cd905d512a3f9ba5ae8e2affce41e2a33600140a00d44a2d842e5","txBody":"8283 ... 930b"}' -H "Content-Type: application/json" https://adalite.io/api/txs/submit

**Comment by catenocrypt** [comment]
A note on multi-input transactions:
- The transaction data contains signatures.  It has to have the same number of signatures as input UTXOs, and in the same order.  The private key of signature N must match the address of UTXO N.
- In the SigningInput to WalletCore CardanoSigner the order does not matter.  Signer will take each UTXO, find its matching private key, and create a signature with it.
- If there are multiple UTXOs with the same address, in the SigningInput is enough to add the private key once.  Signer will create exactly N signatures, in the right order, if needed using a private key more than once.
- The UTXOs specified has to contain the address as well.  This is needed to be able to match UTXOs with private keys.  It should be no problem to provide this info, as address summary includes addresses along UTXOs.
