### ISSUE TITLE
wallet core binary build docker image

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#748]
Easier for using wallet core in server side (Linux/Golang)

**Comment by hewigovens** [comment]
https://github.com/trustwallet/developer/issues/77

**Comment by hewigovens** [comment]
@catenocrypt maybe it's better to have a docker image instead? only keep final built static libraries, make a small runnable / linkable image

**Comment by catenocrypt** [comment]
I see such options for building a docker image with binaries:
1. do the building when building the docker image. drawback: image is 'littered' with build artifacts, difficult to clean
2. do the build locally (outside of docker), and include in the docker image the end result binaries only
3. include linux binary artifacts in the release every time (all libs, exes, public include files), in the docker build take binaries from github release (similar how some deps are taken, or how git sources are taken).  This is the most flexible & practical solution, as release artifacts are available any time.
We should pick a solution; currently I did 1., but I think 2. or even 3. would be better.

**Comment by catenocrypt** [comment]
See PR #755 .

**Comment by catenocrypt** [comment]
Finalized with PR #761 .  A single docker image is kept, good for building (dev environment), but also for running (contains pre-built binaries).  Closing issue.
