### ISSUE TITLE
Ethereum signer works wrong

### ISSUE THREAD

**Issue by ArtemGoryunov** [TrustWallet/wallet-core#75]
## Steps to Reproduce (for bugs)

Result for ETH signer `RLP.encode(transaction.sign)` from the `trust-core` doesn't equal to 
`EthereumSigner.sign.encoded` from the `wallet-core`.

**Comment by alejandro-isaza** [comment]
Can you please provide a failing test case?

**Comment by alejandro-isaza** [comment]
Should be fixed now.
