### ISSUE TITLE
ERC20 transaction history doesnt showing correctly

### ISSUE THREAD

**Issue by ersanyakit** [trustwallet/wallet-core#759]
**Describe the bug**
TrustWallet have a small problem on transaction history.  As you know we can send multiple tokens transfer in one transaction using Ethereum platform...
If we send multiple tokens in one transaction using same address, its showing only 1 transaction with amount...
TX Hash correct but amount value is incorrect. 
It must sum amounts inside of transaction.

Sample TX for Multiple Token Transfer:
https://etherscan.io/tx/0xe3cdfc749e90ed6fa1ab2ee202f9d4f4c4872dd41a9f6dcf46d18aaff8324247

Problem is here:
https://etherscan.io/address/0x02d0781229bca317505d1d6e012ba786cd78a1db#tokentxns

**To Reproduce**

**Expected behavior**

**Screenshots**
![photo6003757251061461234](https://user-images.githubusercontent.com/10724463/70310518-e3e9ec80-1820-11ea-9dc5-0db340185e27.jpg)

**On Etherscan**

![www](https://user-images.githubusercontent.com/10724463/70310534-f2d09f00-1820-11ea-954d-0cc8d3e90483.png)

**Additional context**

**Comment by vikmeup** [comment]
Currently it's expected behavior. We will improve this in the future, as rare use case
