### ISSUE TITLE
An Easier Download of TRUST WALLET MacOS for Newbies

### ISSUE THREAD

**Issue by senevrensel** [trustwallet/wallet-core#768]
Hello TrustWallet Team,

am a macuser but nothing to do with Terminal nor commands . 
Can you pls just create a link and after clicking it we can download the Trust Wallet Desktop version for MacOs. 
I visited the TrustCore Wallet page ( https://developer.trustwallet.com/wallet-core/building ) and wrote the command ./bootstrap.sh and that didnt work . 
Can you pls mention the download for Newbies pls.
Thanks.

**Comment by vikmeup** [comment]
Trust Wallet does not have a desktop version at the moment
