### ISSUE TITLE
Add support for Nimiq

### ISSUE THREAD

**Issue by terorie** [TrustWallet/wallet-core#77]
Name: [Nimiq](https://nimiq.com)
Symbol: `NIM`
Documentation: [Protocol Reference](https://nimiq-network.github.io/developer-reference/)

__Checklist__

 - [x] Coin configuration
   - [x] Coin Type / Decimals
   - [x] Recommended Block Explorer ([Nimiq.Watch](https://nimiq.watch))
   - [ ] Added to switch statements in `src/interface/TWCoinType.cpp` _→ in progress_
 - [x] Account / Address
   - [x] From Private Key
   - [x] From Public Key
   - [x] From/To String (User-Friendly Address)
 - [x] Transaction
   - [x] Serialization
   - [x] Signing
 - [ ] C interfaces
   - [ ] Validate generated code in Android and iOS projects _→ in progress_
 - [ ] Tests
   - [x] Unit Test
   - [ ] Integration Test
 - [ ] RPC endpoint _→ in progress_

View progress [here](https://github.com/terorie/trustwallet-core/pull/1/files?utf8=✓&diff=unified)

**Comment by terorie** [comment]
# Nimiq RPC documentation

### Setup

1. Download the Nimiq source ([nimiq-network/core](https://github.com/nimiq-network/core))
   - Prebuilt binaries: https://nimiq.com/de/#downloads
   - From source
      - Clone `git@github.com:nimiq-network/core.git`
      - `npm install`
      - Binary is under `clients/nodejs`
   - I could also throw together a Docker image for you
2. Write a config file ([sample](#sample-config))
3. Start and sync Nimiq: `./nimiq --config=sample.conf`
4. Implement a client

### RPC documentation

<todo>

### Sample config

For a light node listening on `wss://nimiq.trustwallet.com:8443` (that serves other peers).
Running a node that doesn't listen is also possible with the `dumb` mode, which is more resistant against DoS attacks.

Regardless of `dumb` mode or not, an RPC server is listening on `8648`.

```jsonc
{
    host: "nimiq.trustwallet.com",
    port: 8443,
    tls: {
        cert: "./my.domain.cer",
        key: "./my.domain.key"
    },
    protocol: "wss",
    type: "light",
    network: "main",
    statistics: 60, // Print stats every x seconds
    rpcServer: {
        enabled: "yes",
        port: 8648,
        allowip: ["192.168.0.0/24"],
    },
    log: {
        // Possible values: "trace", "verbose", "debug", "info", "warning", "error", "assert"
        level: "info",
    }
}
```

**Comment by hewigovens** [comment]
Do you guys have public rpc endpoint for testing?

**Comment by terorie** [comment]
@hewigovens Not that I know. I can start one though.

**Comment by terorie** [comment]
@hewigovens We now have https://trust-us-01.hexapool.io/ 
If you have questions during development, I am @terorie on Telegram.

**Comment by hewigovens** [comment]
Thanks, I will test it out
