### ISSUE TITLE
Add account / address explorer url to coin configuration

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#771]
something like this in `coins.json`
```json
{
  "explorer": {
    "url": "https://etherscan.io",
    "txPath": "/tx/",
    "accountPath": "/address/"
  }
}
```

**Comment by catenocrypt** [comment]
Explorer account URL has been added, next to transaction URL:

```
TWString *_Nonnull TWCoinTypeConfigurationGetTransactionURL(enum TWCoinType type, TWString *_Nonnull transactionID);
TWString *_Nonnull TWCoinTypeConfigurationGetAccountURL(enum TWCoinType type, TWString *_Nonnull accountID);
public static func getTransactionURL(type: CoinType, transactionID: String) -> String {
public static func getAccountURL(type: CoinType, accountID: String) -> String {
public static native String getTransactionURL(CoinType type, String transactionID);
public static native String getAccountURL(CoinType type, String accountID);
```

PR: #773 .

**Comment by catenocrypt** [comment]
Done.

Script used to process coins.json attached below.
------------------------
import json
import urlparse
import collections

def loadCoins():
    with open('./coins.json', 'r') as fp:
        # OrderedDict is used to preserve key order
        obj = json.load(fp, object_pairs_hook=collections.OrderedDict)
    return obj

def saveCoins(c):
    with open('./coins2.json', 'w') as fp:
        json.dump(c, fp, indent=4, sort_keys=False)

def urlHost(url):
    o = urlparse.urlparse(url)
    return o.scheme + "://" + o.netloc

def urlRest(url):
    host = urlHost(url)
    return url[len(host):]

def urlCheck(url):
    url2 = urlHost(url) + urlRest(url)
    if url2 != url:
        print("ERROR")
        print("mismatch", url, url2)

def transform(cc):
    print(len(cc))
    for c in cc:
        exp = c['explorer']
        if len(exp) == 0:
            print("WARNING: Missing explorer")
            print(c)
        else:
            urlCheck(exp)
            host = urlHost(exp)
            path = urlRest(exp)
            print(host, path)
            del c['explorer']
            # take out info and put it back to preserve order
            infoSaved = c['info']
            del c['info']
            exp = {
                "url": host,
                "txPath": path,
                "accountPath": "/"
            }
            c['explorer'] = exp
            c['info'] = infoSaved
            print(c['explorer'])

c = loadCoins()
transform(c)
saveCoins(c)
