### ISSUE TITLE
Can txid be returned when the transaction is signed?

### ISSUE THREAD

**Issue by spring820313** [trustwallet/wallet-core#774]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by catenocrypt** [comment]
The hash of a transaction is computed internally during signing, but this is currently not exposed to the outside.

**Comment by spring820313** [comment]
OK!

**Comment by hewigovens** [comment]
usually you can get tx id after you broadcast it

**Comment by spring820313** [comment]
I want to get txid ahead of time

**Comment by catenocrypt** [comment]
Have you considered doing this yourself within WalletCore?  That would be a good contribution, and we would include it if done right.
Either done as a separate method in Eth Signer -- takes an encoded tx and returns ID, or within the sign method, as an extra output field.

Relevant source file:
https://github.com/trustwallet/wallet-core/tree/master/src/Ethereum
