### ISSUE TITLE
Harmony ONE Native Token - Total amount not updated correctly

### ISSUE THREAD

**Issue by yelllowsin** [trustwallet/wallet-core#778]
Tested on iOS 13.3, Trust Wallet Version: 2.6984.0 (6984)

**Describe the bug**

Transactions sent from **shard 0 to shard 1 do not update currectly the total amount** on Trust Wallet - Harmony ONE Native Token. Transactions sent from shard 0 to shard 0 update the total amount correctly though (see printscreen of the total amount shown on Trust Wallet) and all the transactions received here on Block Explorer. Total amount on Trust Wallet should be **1.007** accordinly to: https://explorer.harmony.one/#/address/one1tuugefqrwfszukxdxm32w5nmer0r6nj4axt5p6

Instead it is **1.003**

**To Reproduce**

Create a native Harmony ONE wallet on Trust Wallet and send some tokens using the HMY:

./hmy transfer --from one1q563tnpv4tnh7l30p2wy3gnu3akhd6va97w7ku --to one1tuugefqrwfszukxdxm32w5nmer0r6nj4axt5p6 --from-shard 0 --to-shard 1 --amount 0.001 --chain-id mainnet --passphrase yourpass

**Expected behavior**

Total amount on Trust Wallet should increase by **0.001**

**Screenshots**

![unnamed](https://user-images.githubusercontent.com/7217595/70924348-1e653d80-2008-11ea-9671-56abd3b09ef6.jpg)

**Comment by vikmeup** [comment]
That's expected as Harmony team suggested to only use shard `0` until they build infrastructure for wallets to support many shards easily
