### ISSUE TITLE
Harmony ONE Native Token - Outgoing transactions failing

### ISSUE THREAD

**Issue by yelllowsin** [trustwallet/wallet-core#779]
Tested on iOS 13.3, Trust Wallet Version: 2.6984.0 (6984)

**Describe the bug**

Outoing transactions failing (they are not even confirmed in the blockexplorer if you check the link):

https://explorer.harmony.one/#/tx/0xc02739fe95cde7b29eea28f0b8a7f7e129fbb36e21c612d3f0b1d6f52b3face1

**To Reproduce**

Send any amount or total amount from Trust Wallet to any Harmony ONE Native Token address.

**Expected behavior**

Sending transactions should be working normally.

**Screenshots**
![outgoing_tx](https://user-images.githubusercontent.com/7217595/70925612-4a81be00-200a-11ea-8e83-7be543fe7eb5.jpg)

**Comment by vikmeup** [comment]
What could be the reason for failing? is there any info you can provide

**Comment by yelllowsin** [comment]
> What could be the reason for failing? is there any info you can provide

I can't see any reason for them to fail, not even gas. Maybe @gupadhyaya could take a look on this?

**Comment by vikmeup** [comment]
@yelllowsin do you have enough funds on shard 0 when you send it?

**Comment by yelllowsin** [comment]
> @yelllowsin do you have enough funds on shard 0 when you send it?

Sure, you can see my funds on shard 0 here: https://explorer.harmony.one/#/address/one1tuugefqrwfszukxdxm32w5nmer0r6nj4axt5p6

I have 1.003 on shard 0 and trying to send 1. Tried also with lower amounts.

**Comment by yelllowsin** [comment]
ha, weird...now the TX worked with a lower amount. I still cannot send the max amount though, it fails. It seems the issue is more related to sending the max amount here now.

**Comment by hewigovens** [comment]
I think this is fixed in latest iOS app
