### ISSUE TITLE
Add support for Filecoin

### ISSUE THREAD

**Issue by terorie** [trustwallet/wallet-core#780]
## Description

Name: [Filecoin](https://filecoin.io/)
HD Derivation Scheme: tbd
Symbol: `FIL`
Documentation:
 - [Specification](https://filecoin-project.github.io/specs/)
 - [Lotus Node Docs](https://lotu.sh)
 - [Lotus Node Source](https://github.com/filecoin-project/lotus)
 - [Testnet Explorer](http://user.kittyhawk.wtf:8000)

## Blockers

 - [x] Wait for Filecoin to obtain SLIP-44 ID (https://github.com/satoshilabs/slips/pull/841)
 - [x] Work out BIP-44 derivation paths
 - [x] Select key pair type (BLS or secp256k1)

## Checklist

Finish check list [here](https://developer.trustwallet.com/wallet-core/newblockchain#blockchain-checklist).

**Comment by hewigovens** [comment]
I think we can open a slipp44 pull request behalf of Filecoin team ？

**Comment by terorie** [comment]
@hewigovens Good idea. I think the Filecoin team has already started work on the SLIP44 issue though. I'll check with them.

**Comment by terorie** [comment]
Update: @jleni Has volunteered to get the SLIP44

**Comment by jleni** [comment]
Yes, here is the PR https://github.com/satoshilabs/slips/pull/841

**Comment by prusnak** [comment]
Remember that All Testnets should use 1 as SLIP-44 value

**Comment by catenocrypt** [comment]
Target is now mainnet (not test).  @terorie , could you pls update description accordingly?
