### ISSUE TITLE
Refactor HDWallet

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#794]
## Current problem

`HDWallet` supports BIP32, BIP39, BIP44(SLIP44/SLIP10), the derivation scheme is implicitly inferred from coin and curve type, but current design is not easy to support Cardano or Substrate which has a different derivation scheme other than BIP32, and we check curve type in `HDWallet`, `PrivateKey`, `PublicKey`, we need a better abstraction to encapsulate curve, derivation scheme.

**Comment by hewigovens** [comment]
will reopen it when we start working on it

**Comment by catenocrypt** [comment]
I feel this issue no longer makes sense.
