### ISSUE TITLE
Add support for Nano

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/wallet-core#8]
Name: [Nano](https://nano.org/en)
HD Derivation Scheme: BIP44/165
Symbol: `NANO`

Checklist

- [ ] Implement functionality in C++. Put it in a subfolder of `src/`.
    - [ ] Address (if necessary)
    - [ ] Transaction (if necessary)
    - [ ] Signer
- [ ] Write unit tests. Put them in a subfolder of `tests/`.
- [ ] Add relevant constants in `TWCoinType`, `TWP2SHPrefix`, `TWEthereymChainID`, `TWHRP`, etc., as necessary.
- [ ] Return correct curve and purpose in `src/Coin.cpp`.
- [ ] Implement address validation and derivation in `src/Coin.cpp`.
- [ ] Implement coin configuration `src/include/TWCoinTypeConfiguration.cpp`.
- [ ] Write interface header in `include/TrustWalletCore` and implement the interface in `src/interface`.
    - [ ] Address interface (if necessary).
    - [ ] Signing interface.
- [ ] Validate generated code in Android an iOS projects. Write integration tests for each.

**Comment by zhyatt** [comment]
@hewigovens @eddywm Thanks for looking into the integration of Nano into your wallet. Some of the links you have aren't updated with the latest information. For example block details in the nanode.co link above are incorrect. We'd recommend reviewing the integration guides here https://developers.nano.org/guides and if you have questions please reach out to info-at-nano.org to connect with our team.

**Comment by eddywm** [comment]
Hey @zhyatt 
https://developers.nano.org/guides seems to be lacking important information necessary for integration.
Necessary Informations are missing in that guide like :

- Mnemonic derivation standard : Public Key <-- Private Key <-- Phrase
- Account / Address Derivation 
- Transaction structure and building

That's the reason why we picked old seemingly outdated guide.

**Comment by vikmeup** [comment]
@eddywm can you update progress on the integration?

**Comment by eddywm** [comment]
I'll be starting in this week. 
I was waiting for the curve and to finish top priority tasks I had.

**Comment by roosmaa** [comment]
Nano team has asked me to pick up this integration. Plan is to have the pull-requests up for review by the end of the week.

**Comment by eddywm** [comment]
> Nano team has asked me to pick up this integration. Plan is to have the pull-requests up for review by the end of the week.

That's awesome we'll be glad to help with some guidance.

**Comment by roosmaa** [comment]
Ok, I have integration ready on my fork of wallet-core. Will be creating 2 pull requests (as per the integration guide), first one for the trezor-crypto changes. When that is merged, will create the 2nd PR for the actual coin integration. There are a couple of points where I'd like TW team input, which I'll raise in the respective PRs.
