### ISSUE TITLE
Add Support for Nervos

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#801]
Reference

- https://github.com/satoshilabs/slips/blob/master/slip-0044.md (CKB / 309)
- https://github.com/nervosnetwork/ckb

SDK
- https://github.com/ashchan/ckb-sdk-swift
- https://github.com/nervosnetwork/ckb-sdk-js

Address format
- https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0021-ckb-address-format/0021-ckb-address-format.md

Serialization
- https://github.com/nervosnetwork/molecule
- https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0008-serialization/0008-serialization.md

Cell/Script/Transaction
- https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0019-data-structures/0019-data-structures.md

**Comment by vikmeup** [comment]
Closing until we have more interest in Nervos integration.
