### ISSUE TITLE
Cardano Shelley and Staking support

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#805]
https://staking.cardano.org/en/

**Comment by catenocrypt** [comment]
Shelby is a Cardano testnet, with balances from a Nov29 snapshot.
https://testnet.iohkdev.io/en/
Modified Deadalus and Yoroi wallets are available with Shelby/staking support.  Faucet is available:
https://testnet.iohkdev.io/en/cardano/shelley/tools/faucet/
The Jörmungandr node is here:
https://github.com/input-output-hk/jormungandr
For delegation transaction, this may be relevant:
https://input-output-hk.github.io/jormungandr/stake_pool/delegating_stake.html

**Comment by catenocrypt** [comment]
In Shelley, address format has changed as well.  E.g.:
`addr1s3hdtrqgs47l7ue5srga8wmk9dzw279x9e7lxadalt6z0fk64nnn2mgtn87mrny9r77gm09h6ecslh3gmarrvrp9n4yzmdnecfxyu59j5lempe`
instead of 
`Ae2tdPwUPEZ6SqAETdiJgPYHpAey2MWakEVRDESWYzBePi7u5uAL5ah26qx`

**Comment by hewigovens** [comment]
😂，Bech32 address?

**Comment by catenocrypt** [comment]
Yes, good gess. Bech32, but with longer data (like 65 bytes).

**Comment by catenocrypt** [comment]
Yoroi (browser extension wallet) for Shelley:   https://github.com/Emurgo/yoroi-frontend
Yoroi for mainnet (older):   https://github.com/input-output-hk/yoroi-frontend

**Comment by hewigovens** [comment]
I think we will use the new address format in the app

**Comment by catenocrypt** [comment]
I plan to test staking support on Shelley testnet with 'Yoroi - Shelley'web wallet, and shelleyexplorer.cardano.org.  However, apparently there is no fauces for this testnet, only for the beta/nightly nets, where on has to create most part of the infrastructure.
( https://faucet.beta.jormungandr-testnet.iohkdev.io/send-money/<ADDRD>
https://testnet.iohkdev.io/en/cardano/shelley/tools/faucet/ )

**Comment by catenocrypt** [comment]
Info: 
Yoroi Mobile for Android now supports staking (Shelley testnet)
iOS app is under review by Apple. Will be released shortly!
https://play.google.com/store/apps/details?id=com.emurgo&hl=en

**Comment by hewigovens** [comment]
https://cryptoslate.com/charles-hoskinson-no-release-date-for-shelley-mainnet-until-more-milestones-achieved/

A few months away

**Comment by catenocrypt** [comment]
Info: Cardano produces first block for its Shelley blockchain
https://decrypt.co/26805/cardano-produces-first-block-for-its-shelley-blockchain?utm_source=twitter&utm_medium=social&utm_campaign=auto

**Comment by vikmeup** [comment]
let's close this for now, will re-open later

**Comment by jpmcb** [comment]
Hi all - can this be re-opened? The [ADA Shelley mainnet ](https://cryptobriefing.com/cardano-launches-shelley-mainnet-offers-staking-rewards/) went live in July of last year and it'd be great to see first class ADA support and staking come to Trust wallet

**Comment by catenocrypt** [comment]
We will reopen as resources permit.
