### ISSUE TITLE
Add Generic AnyAddress

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#813]
To reduce C interfaces

**Comment by hewigovens** [comment]
I have something in progress, will push today

**Comment by catenocrypt** [comment]
Since it's a breaking change, what's the plan for transition?  My idea:
1. Add new AnyAddress, mark old ones as deprecated, but leave them
2. Remove old ones, in 1-2 months
We will need to communicate clearly how to transition.

**Comment by hewigovens** [comment]
That's actually not a big change, no new features introduced, so users can stay at the old version
