### ISSUE TITLE
Refactor AnySigner to reduce C interfaces

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#816]
To reduce C interfaces and remove string based AnySigner

It needs to be type safe as currently is, but we want to avoid duplication for code gen every time you need introduce a new blockchain

Related: https://github.com/trustwallet/wallet-core/issues/813

**Comment by vikmeup** [comment]
One idea would be to find all `TW_{blockchain}_Proto_SigningOutput` and create signers automatically to avoid new developers to learn about exposing interfaces to Swift/Kotlin and this will reduce overhead and codebase

**Comment by hewigovens** [comment]
we can change `codegen/bin/newcoin` a bit to create dummy proto and TW_Signer

**Comment by vikmeup** [comment]
Can we do something like this instead:

```
message Message {    
     oneof message_oneof {
        Cosmos cosmos = 1;
        Bitcoin Bitcoin = 2;
    }
}
```

`AnySigner.sign(message: Message)`

In this case we have one method to process any case for signing and avoid having interfaces in C

**Comment by catenocrypt** [comment]
> In this case we have one method to process any case for signing and avoid having interfaces in C

Interesting idea.  Concern: wouldn't be the proto msg class bloated?

An alternative is havin many coin-specific proto messages, but a single C interface, taking use of the fact that the _Proto_ typedefs are only aliases to Data, so any message can be inside.

**Comment by vikmeup** [comment]
It's better UX for having enums. `CoinType` also has many cases too. 

I don't think there would be many blockchains types in general, not likely to have more than 100 blockchain types by 2025, we should be ok as a it's very intuitive solution.

Unless you guys have better suggestion? 

> An alternative is having many coin-specific proto messages
I think that's the example above? or that's what I meant by that example. 

Proto message needs to be type specific to avoid bugs

**Comment by hewigovens** [comment]
Is this still an issue? right now you only have to implement c++ signer + swift or kotlin test

**Comment by hewigovens** [comment]
Can't avoid switch cases, either BitcoinSigner or AnySigner.sign(.bitcoin)

**Comment by vikmeup** [comment]
It's the same process as for any address. C interfaces for codegen is not intuitive. I prefer to have one entry point.

```
let input = BitcoinSigningInput {
    $0.value = 1
}

let result = AnySigner.sign(message: input)
```

For me this is much easier to understand and statically typed cases.  I just want to avoid to have any C interfaces in general. 

In the future if we plan to migrate to any other languages - protos would be much easier to adopt than having C interfaces. (aka Rust, but not benefits atm)

**Comment by hewigovens** [comment]
you can't avoid C interface...that's the key of interoperation, Proto -> serialized as string -> pass through C interface

**Comment by hewigovens** [comment]
we can have some sugars and have to unify signer output first, it's quite different now
