### ISSUE TITLE
[Cosmos] Invalid signature it contains special characters in memo

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#820]
**Describe the bug**
If you use special characters in the memo you will get an error: `signature verification failed; verify correct account sequence and chain-id`

thanks to @rstormsf for finding it :-)

**To Reproduce**

Sign transaction with memo: `<>` and broadcast to the network.

```json
{
   "height":"0",
   "txhash":"F4DE27C349622DC0E4A5A23538AA1A35A16BE5AEAFEE24FBF9E1D98393689D11",
   "code":4,
   "raw_log":"{\"codespace\":\"sdk\",\"code\":4,\"message\":\"signature verification failed; verify correct account sequence and chain-id\"}",
   "gas_used":"20612"
}
```

**Comment by hewigovens** [comment]
interesting, I also tried Ledger + Cosmostation / imToken, got the same error, probably something wrong in node itself

**Comment by vikmeup** [comment]
I'm going to close this, I assume it's cosmos limitations, same for bnb chain

**Comment by hewigovens** [comment]
can you report this to cosmos team?
