### ISSUE TITLE
Update ETC explorer

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#822]
http://cryptocoindaddy.com/blockscout-shutting-down-ethereum-classic-hosting-in-january-2020/

**Comment by catenocrypt** [comment]
Options for ETC explorer:
- https://blockscout.com/etc/mainnet/
- https://etc.tokenview.com/en
- https://etcblockexplorer.com/home

Non-options:
- gastracker.io — shutting down
- http://etherhub.io/ — site access issues
