### ISSUE TITLE
[CI] Broken master build

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#825]
**Describe the bug**

CI is broken on master https://dev.azure.com/TrustWallet/Trust%20Wallet%20Core/_build/results?buildId=18872&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=d6d1571a-a17f-534d-f3cd-109ff09fc86e

**Comment by hewigovens** [comment]
should be fixed by #826
