### ISSUE TITLE
Add json signing output for Zilliqa and Nano blockchains.

### ISSUE THREAD

**Issue by leoneparise** [trustwallet/wallet-core#827]
**Is your feature request related to a problem? Please describe.**
Currently iOS Signables for Zilliqa and Nano return a struct to broadcast the transaction. 

**Describe the solution you'd like**
Can we do the same as we did in Cosmos and return the json?

**Describe alternatives you've considered**

**Additional context**

**Comment by hewigovens** [comment]
Let’s do separate issues

**Comment by leoneparise** [comment]
#830, #831

**Comment by hewigovens** [comment]
Thanks, close this now
