### ISSUE TITLE
[CI Fails] Wallet Core Android Maven Upload

### ISSUE THREAD

**Issue by vikmeup** [trustwallet/wallet-core#828]
**Describe the bug**

CI does not work for Maven: https://dev.azure.com/TrustWallet/6544d497-8d9a-4cd6-8299-4b47ad7081a2/_build/results?buildId=19064

**Comment by catenocrypt** [comment]
Execution failed for task ':trustwalletcore:bintrayUpload'.
> Could not create version '1.0.1': HTTP/1.1 401 Unauthorized [message:This resource requires authentication]

**Comment by hewigovens** [comment]
What's the status of this issue? @madcake @vcoolish

**Comment by madcake** [comment]
Fixed
