### ISSUE TITLE
Update Ethereum Classic Blockchain Explorer

### ISSUE THREAD

**Issue by gitr0n1n** [trustwallet/wallet-core#835]
It looks like the block explorer is pointing to gastracker.io. This block explorer closed its doors.

Can you change it to one of the following open-source long-term commitment ETC explorers:

https://blockscout.com/etc/mainnet/

or

https://expedition.dev/?network=mainnet

**Comment by hewigovens** [comment]
already updated in this pr: https://github.com/trustwallet/wallet-core/pull/824
