### ISSUE TITLE
Publish latest Trust Wallet Core Java library to maven repository

### ISSUE THREAD

**Issue by johnnynanjiang** [trustwallet/wallet-core#875]
Can you publish latest Trust Wallet Core Java library to maven repository so that we can use it , particularly latest version has AnySigner which is available in the latest iOS cocoa pod.

**Comment by madcake** [comment]
Automating published in maven:
api 'com.trustwallet:wallet-core:2.0.2'

**Comment by johnnynanjiang** [comment]
Thanks @madcake , I think I was looking at a deprecated trust wallet maven entry.

I tried `implementation 'com.trustwallet:wallet-core:2.0.2'` in my Android project, and wonder how can I get access to class `AnySigner`(it is available in Trust Walelt CocoaPod).

**Comment by hewigovens** [comment]
can you check the tests? `import wallet.core.java.AnySigner`

**Comment by johnnynanjiang** [comment]
@hewigovens 

Yes `AnySigner` is available in tests as source code, but when I import `com.trustwallet:wallet-core:2.0.2` as a dependency, `AnySigner` is not accessible.

**Comment by johnnynanjiang** [comment]
@hewigovens @madcake please see the screenshot, that `AnySigner` is not available in `com.trustwallet:wallet-core:2.0.2`

![Screen Shot 2020-03-05 at 10 30 44](https://user-images.githubusercontent.com/11918567/75932783-70618500-5ecc-11ea-8257-d9b6d791d20a.png)
