### ISSUE TITLE
Provide an example for AnySigner usage in v2.x for Go / C++

### ISSUE THREAD

**Issue by gituser** [trustwallet/wallet-core#889]
**Is your feature request related to a problem? Please describe.**
Because of the [AnySigner refactoring](https://github.com/trustwallet/wallet-core/pull/862) the [old AnySigner example](https://github.com/trustwallet/wallet-core/blob/0f42c150c1c8df671097b36bc41ce57e2dbd225b/samples/cpp/sample.cpp#L122)  no longer works making the binary linked to recent wallet-core version crashing.

```
terminating with uncaught exception of type std::invalid_argument: Invalid private key data
SIGABRT: abort
PC=0x7fdc87685e97 m=0 sigcode=18446744073709551610
```

**Describe the solution you'd like**
Provide an example for new AnySigner for Go / C++ in samples/go/ samples/cpp/ to ease the pain for developers.

Also add in release notes that AnySigner interface has been changed and what to do in order to make it work again in v2.x version.

**Additional context**
This issue is actual for wallet-core >= v2.x

**Comment by hewigovens** [comment]
WIP in https://github.com/trustwallet/wallet-core/pull/890

**Comment by gituser** [comment]
Thanks!

**Comment by gituser** [comment]
@hewigovens there is no Go example though, only C++ one. 

Can you add it as well please?

Thank you.
