### ISSUE TITLE
JNI codegen issue for RippleSigner.sign() wrong return data type which doesn't exist

### ISSUE THREAD

**Issue by eddywm** [TrustWallet/wallet-core#89]
RippleSigner.sign() throws a JNI error.

 JNI DETECTED ERROR IN APPLICATION: JNI GetStaticMethodID called with pending exception java.lang.ClassNotFoundException: Didn't find class "wallet.core.jni.proto.Proto$SigningOutput" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/data/app/com.wallet.crypto.trustapp.test-yhNuLZQpu5n6m7Q_gQfoKQ==/base.apk", zip file "/data/app/com.wallet.crypto.trustapp-k9nRS0JYYCFBUHJ1VngIGA==/base.apk"],nativeLibraryDirectories=[/data/app/com.wallet.crypto.trustapp.test-yhNuLZQpu5n6m7Q_gQfoKQ==/lib/x86, /data/app/com.wallet.crypto.trustapp-k9nRS0JYYCFBUHJ1VngIGA==/lib/x86, /data/app/com.wallet.crypto.trustapp.test-yhNuLZQpu5n6m7Q_gQfoKQ==/base.apk!/lib/x86, /data/app/com.wallet.crypto.trustapp-k9nRS0JYYCFBUHJ1VngIGA==/base.apk!/lib/x86, /system/lib]]
2019-03-04 10:56:29.522 11829-11862/com.wallet.crypto.trustapp A/crypto.trustap: java_vm_ext.cc:542]   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
2019-03-04 10:56:29.522 11829-11862/com.wallet.crypto.trustapp A/crypto.trustap: java_vm_ext.cc:542]   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)

**Comment by vikmeup** [comment]
@alejandro-isaza I believe this is a blocker for Android app to integrate Ripple.

**Comment by eddywm** [comment]
Fixed with https://github.com/TrustWallet/wallet-core/pull/92
