### ISSUE TITLE
Pod install conflict names

### ISSUE THREAD

**Issue by vanphandinh** [trustwallet/wallet-core#899]
**Describe the bug**
I cannot install TrustWalletCore via Pod in XCode Swift.
"[!] The 'Pods-certificates' target has libraries with conflicting names: libtrustwalletcore.a."
This error is always displayed even though I have remove all pods

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1019" alt="Screen Shot 2020-03-19 at 9 26 38 PM" src="https://user-images.githubusercontent.com/13887599/77077868-68572880-6a28-11ea-95c8-3959d2ae6af8.png">
<img width="1440" alt="Screen Shot 2020-03-19 at 9 26 53 PM" src="https://user-images.githubusercontent.com/13887599/77077879-6beaaf80-6a28-11ea-857f-bc28f57b0758.png">

**Additional context**

**Comment by liuan3756** [comment]
dude how to fix this? my project got the issue too

**Comment by vanphandinh** [comment]
> dude how to fix this? my project got the issue too

uncomment use_frameworks!
seems that is the problem.
