### ISSUE TITLE
Add FIO account interface

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#913]
1. FIO public key -> default short account name
2. account name less equal than 12 chars, only of lowercase letters a through z, and numbers 1 through 5 and `.`, `@`
3. validate account name

we can resue code in `EOS/Name.cpp`

**Comment by catenocrypt** [comment]
> we can resue code in `EOS/Name.cpp`

For FIO, it's better to use   class `Actor` from  `src/FIO/Signer.cpp`.
