### ISSUE TITLE
swift got a error:  "Error validating transaction: Transaction 01dde1a3d0521f7b00394674de58a9fb2da1db8fe8e4e084aa2eaa377975eb54 orphaned, missing reference 828725f838eea6136f54113ad975017d272151ebd174f8427b0f45e4941ca9b2."

### ISSUE THREAD

**Issue by togiter** [trustwallet/wallet-core#920]
ios swift  
My btc address:  bc1qvut9je4y3hvnnlqw4ezyd5mn778jj9flqkky7c
<img width="875" alt="截屏2020-04-1000 50 52" src="https://user-images.githubusercontent.com/18685332/78920171-937fe580-7ac5-11ea-9deb-0c79e8d02b26.png">

create a transaction : 
`01000000000101b2a91c94e4450f7b42f874d1eb5121277d0175d93a11546f13a6ee38f82587820000000000ffffffff02a086010000000000160014874cc80fdcee23f59e7b9b09a7ebd90c45b9fcbfe26e01000000000016001467165966a48dd939fc0eae4446d373f78f29153f02483045022100e40a09d72f1b28b17e5a29fab69989bc25871464ce640780a483c0d90122a251022049c905370f1dcde682e58b0fa08b1740e51405aba9a010b5fcc85926f3df37a3012102a901f355b553d3617e64969f5f67133c15540dd5ddc3138e36cd8a75403dfe2e00000000`

send transaction got a error:
error: "Error validating transaction: Transaction 01dde1a3d0521f7b00394674de58a9fb2da1db8fe8e4e084aa2eaa377975eb54 orphaned, missing reference 828725f838eea6136f54113ad975017d272151ebd174f8427b0f45e4941ca9b2."
And I descoderawtransaction got the result:
<img width="974" alt="截屏2020-04-1000 41 38" src="https://user-images.githubusercontent.com/18685332/78919854-18b6ca80-7ac5-11ea-9ed3-c82313658eeb.png">

**Comment by hewigovens** [comment]
Could you please check?
1. `BitcoinUnspentTransaction.outPoint.hash` order, usually you need to reverse it if you get from API
2. `BitcoinSigningInput.scripts`, you should set `scripts[<script_hash>] = <BitcoinScript.buildPayToPublicKeyHash>` for p2wpkh

**Comment by togiter** [comment]
I try again and agin, got the same err:
`"Error validating transaction: Transaction 9a5433797dbc9804e4cecfbe8beb341ff1f5fb27fc637dd3f407bd2631259052 orphaned, missing reference b2a91c94e4450f7b42f874d1eb5121277d0175d93a11546f13a6ee38f8258782."`

**Comment by togiter** [comment]
I update the code as follow:
<img width="904" alt="截屏2020-04-1015 27 51" src="https://user-images.githubusercontent.com/18685332/78972255-e8604200-7b3f-11ea-826f-8dbcf8fb279e.png">

And I try again and agin, got the same err:
"Error validating transaction: Transaction 9a5433797dbc9804e4cecfbe8beb341ff1f5fb27fc637dd3f407bd2631259052 orphaned, missing reference b2a91c94e4450f7b42f874d1eb5121277d0175d93a11546f13a6ee38f8258782."

I don't know how to do....please help me,thx!

**Comment by hewigovens** [comment]
try this: 
```swift
let script = BitcoinScript.buildForAddress() // utxo address
let scriptHash = script.matchPayToWitnessPublicKeyHash() // to redeem p2wpkh
input.scripts[scriptHash.hexString] = BitcoinScript.buildPayToPublicKeyHash(hash: scriptHash).data
```

**Comment by togiter** [comment]
The same error again!!
from:  bc1qvut9je4y3hvnnlqw4ezyd5mn778jj9flqkky7c

**Comment by hewigovens** [comment]
this is testnet: https://api.blockcypher.com/v1/bcy/test/txs/push

**Comment by hewigovens** [comment]
your utxo is in mainnet

**Comment by hewigovens** [comment]
it worked: https://btc1.trezor.io/tx/9a5433797dbc9804e4cecfbe8beb341ff1f5fb27fc637dd3f407bd2631259052

**Comment by togiter** [comment]
Yes, I see. Thank you very much. It was caused by a stupid mistake of mine. Thank you again for your trouble.

**Comment by hewigovens** [comment]
@togiter we'd like to include this tx as a real world test case, would you mind to share the private key of bc1qvut9je4y3hvnnlqw4ezyd5mn778jj9flqkky7c? Thanks

**Comment by headria** [comment]
@togiter sorry brother, how are you solving the problem?

**Comment by jiuyaopinyin** [comment]
> Yes, I see. Thank you very much. It was caused by a stupid mistake of mine. Thank you again for your trouble.

hi,How did you solve the problem of testnet,please?

**Comment by jiuyaopinyin** [comment]
> Yes, I see. Thank you very much. It was caused by a stupid mistake of mine. Thank you again for your trouble.

hi,How did you solve the problem of testnet,please?

**Comment by akhilccrb** [comment]
![Screenshot 2022-04-21 at 4 40 19 PM](https://user-images.githubusercontent.com/45847512/164445902-8eebaea7-f443-489d-abe0-1c67829f26d3.png)


Please check this error?
Do I need to update SDK ?

**Comment by hewigovens** [comment]
@akhilccrb try updating to latest SPM build
