### ISSUE TITLE
Perform static code analysis with cppcheck

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#922]
Perform static code analysis with cppcheck, see PR #921 .

E.g.: `cppcheck --quiet --force walletconsole`

**Comment by catenocrypt** [comment]
Only 3 warning found in src/:

```
$ cppcheck --quiet --force src
src/NEO/Serializable.h:57:28: error: Uninitialized struct member: value.usage [uninitStructMember]
            resp.push_back(value);
                           ^
src/NEO/Serializable.h:57:28: error: Uninitialized struct member: value.prevIndex [uninitStructMember]
            resp.push_back(value);
                           ^
src/NEO/Serializable.h:57:28: error: Uninitialized struct member: value.value [uninitStructMember]
            resp.push_back(value);
                           ^
```

**Comment by catenocrypt** [comment]
A more complete invocation has found more findings:

cppcheck --force --quiet --enable=all android include samples src tools walletconsole

**Comment by hewigovens** [comment]
I remember codacy has cppcheck, maybe we can change options there

**Comment by hewigovens** [comment]
@catenocrypt what should we do for this issue? Add to build script?

**Comment by catenocrypt** [comment]
No, for now I was just thinking a one-time scan through the result, and find any real issues.

**Comment by hewigovens** [comment]
a lint script in `tools` would be nice

**Comment by hewigovens** [comment]
I think we can setup danger to run clang format and cppcheck

**Comment by catenocrypt** [comment]
No major/critical findings found currently; I have addressed a number of selected low-impact medium issues, #938 .

**Comment by catenocrypt** [comment]
A number of selected low-impact issues addressed, cppcheck script added to tools folder, PR #938 . Closing.
