### ISSUE TITLE
Linux CI fails, docker image not found

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#923]
Probably related to making docker image private; should be built; or taken from private (with docker login?)

See:
https://dev.azure.com/TrustWallet/Trust%20Wallet%20Core/_build/results?buildId=26097&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=40b1ee41-44d6-5bba-aa04-4b76a5c732e5&l=17

```
Unable to find image 'trustwallet/wallet-core:latest' locally
docker: Error response from daemon: pull access denied for trustwallet/wallet-core, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

**Comment by hewigovens** [comment]
@vikmeup service account access seems not working
