### ISSUE TITLE
Cannot paste address in Trust Wallet dapp browser

### ISSUE THREAD

**Issue by john-light** [trustwallet/wallet-core#924]
**Describe the bug**
I cannot paste an address into the address field when using a dapp in the dapp browser. Using an Android 9.0 phone.

**To Reproduce**

- Go to a https://mainnet.aragon.org/#/light/0x1f868e337abe47c16e2ac85ce2f0e33c518466b1/
- Click "Add tokens"
- Try to paste an address in the address field
- Notice that only "autofill" option appears, rather than "paste"

**Expected behavior**
I expect to be able to paste addresses (or any other text) in text fields

**Screenshots**

![2f90690c-d1fd-4d8f-b5d8-531f16acf55e](https://user-images.githubusercontent.com/9424721/79356829-596f7300-7f0d-11ea-93c4-c80d9fc0554b.png)

**Additional context**
I cannot find a proper place to report this issue. Trust Wallet Android Source repo is archived, so I couldn't create an issue there. And when I created an account in the Trust Wallet forum to post in the Support & Feedback section I couldn't make a post or even send a DM. So I created the issue here.

**Comment by hewigovens** [comment]
you can try to report it here: https://t.me/trust_developers, I will transfer this issue to android team

**Comment by vcoolish** [comment]
Couldn’t reproduce, tried different versions and devices. Seems like it's related to user’s device

**Comment by catenocrypt** [comment]
I could also not reproduce.  Anyways, does not seem to be related to Trust Wallet.  Closing.
