### ISSUE TITLE
LTC and DASH, how to sign

### ISSUE THREAD

**Issue by RuralPeople** [trustwallet/wallet-core#935]
Now I have a problem, when LTC and DASH build the signature of the structure, they will report an error. Is the method of LTC and DASH signature 
-----
AnySigner.sign(input.build(), LTC, Bitcoin.SigningOutput.parser())
or
AnySigner.sign(input.build(), DASH, Bitcoin.SigningOutput.parser())
-----

Looking forward to your reply, thank you!

**Comment by hewigovens** [comment]
https://developer.trustwallet.com/wallet-core/integration-guide/wallet-core-usage#transaction-signing

**Comment by RuralPeople** [comment]
LTC 签名的时候， 如果toAddress 使用普通地址（非隔离见证地址）时会导致崩溃。
错误如下： 
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x20 in tid 19049 (roidJUnitRunner)

**Comment by hewigovens** [comment]
Can you share your full code?

**Comment by RuralPeople** [comment]
`  val mSigningInput = Bitcoin.SigningInput.newBuilder()
                .setAmount(BigDecimal(Amount).multiply(BigDecimal(100000000)).longValueExact())
                .setHashType(BitcoinSigHashType.ALL.value())
                .setToAddress(toAddress)
                .setChangeAddress(formAddress)
                .setByteFee(BigDecimal(Fee).setScale(0, BigDecimal.ROUND_UP).longValueExact())
        val mPrivateKey = PrivateKey(mPrivateKey.toHexByteArray())
        mSigningInput.addPrivateKey(ByteString.copyFrom(mPrivateKey.data()))
        val publicKeyBtc = mPrivateKey.getPublicKeySecp256k1(true)
        val bytes_sha256 = Hash.sha256(publicKeyBtc.data())
        val bytes_ripemd160 = Hash.ripemd(bytes_sha256)
        val script = BitcoinScript.buildPayToPublicKeyHash(bytes_ripemd160)
        for (buff in mUtxoList) {
            val txHash = buff.tx_hash.toHexBytes()
            txHash.reverse()
            val outpoint0 = Bitcoin.OutPoint.newBuilder()
                    .setHash(ByteString.copyFrom(txHash))
                    .setIndex(buff.tx_pos)
                    .setSequence(Long.MAX_VALUE.toInt())
                    .build()
            val utxo0 = Bitcoin.UnspentTransaction.newBuilder()
                    .setAmount(buff.value)
                    .setOutPoint(outpoint0)
                    .setScript(ByteString.copyFrom(script.data()))
                    .build()
            mSigningInput.addUtxo(utxo0)
        }
        val output = AnySigner.sign(mSigningInput.build(), CoinType.LITECOIN, Bitcoin.SigningOutput.parser())
        val encoded = output.encoded`

**Comment by RuralPeople** [comment]
private fun organizeLtc(formAddress: String, toAddress: String, mPrivateKey: String, Amount: String, Fee: String, mUtxoList: List<UtxoList>, symbol: String): String {
        val mSigningInput = Bitcoin.SigningInput.newBuilder()
                .setAmount(BigDecimal(Amount).multiply(BigDecimal(100000000)).longValueExact())
                .setHashType(BitcoinSigHashType.ALL.value())
                .setToAddress(toAddress)
                .setChangeAddress(formAddress)
                .setByteFee(BigDecimal(Fee).setScale(0, BigDecimal.ROUND_UP).longValueExact())
        val mPrivateKey = PrivateKey(mPrivateKey.toHexByteArray())
        mSigningInput.addPrivateKey(ByteString.copyFrom(mPrivateKey.data()))
        val publicKeyBtc = mPrivateKey.getPublicKeySecp256k1(true)
        val bytes_sha256 = Hash.sha256(publicKeyBtc.data())
        val bytes_ripemd160 = Hash.ripemd(bytes_sha256)
        val script = BitcoinScript.buildPayToPublicKeyHash(bytes_ripemd160)
        for (buff in mUtxoList) {
            val txHash = buff.tx_hash.toHexBytes()
            txHash.reverse()
            val outpoint0 = Bitcoin.OutPoint.newBuilder()
                    .setHash(ByteString.copyFrom(txHash))
                    .setIndex(buff.tx_pos)
                    .setSequence(Long.MAX_VALUE.toInt())
                    .build()
            val utxo0 = Bitcoin.UnspentTransaction.newBuilder()
                    .setAmount(buff.value)
                    .setOutPoint(outpoint0)
                    .setScript(ByteString.copyFrom(script.data()))
                    .build()
            mSigningInput.addUtxo(utxo0)
        }
        val output = AnySigner.sign(mSigningInput.build(), CoinType.LITECOIN, Bitcoin.SigningOutput.parser())
        val encoded = output.encoded
        return Numeric.toTextString(encoded.toByteArray())
    }

**Comment by hewigovens** [comment]
you need to set coin type
`mSigningInput.setCoinType(CoinType.DASH)`

**Comment by RuralPeople** [comment]
ok。谢谢！

**Comment by RuralPeople** [comment]
您的库里面有没有生成wif格式私钥的通用方法？

**Comment by hewigovens** [comment]
no, we removed
