### ISSUE TITLE
[Advice Please] Adding Bitcoin Testnet programmatically

### ISSUE THREAD

**Issue by dmdeklerk** [trustwallet/wallet-core#942]
If questions are not appreciated in the issue section please direct me elsewhere.
Otherwise consider it a feature request regarding documentation. 😄 

Question: 
Is it possible to add coin support by programmatic extending of CoinType and related classes from either Swift or Kotlin (i'm a noob regarding both those languages).

Context:
After adding wallet-core to both android and ios I would like to add support for Bitcoin Testnet and some other BTC clones which are not included in the default build. 

What we did so far:
We did do a full C build so if that is the only option, however unfortunate, it would be a solution as well. 

What I'd hope for:
Is how to figure out to add the following construct programmatically from either Swift or Kotlin (so one can still use the official pods and android packages).

```json
    {
        "id": "testnet",
        "name": "Testnet",
        "symbol": "BTC",
        "decimals": 8,
        "blockchain": "Testnet",
        "derivationPath": "m/44'/1'/0'/0/0",
        "curve": "secp256k1",
        "publicKeyType": "secp256k1",
        "p2pkhPrefix": 0,
        "p2shPrefix": 5,
        "hrp": "bc",
        "publicKeyHasher": "sha256ripemd",
        "base58Hasher": "sha256d",
        "xpub": "zpub",
        "xprv": "zprv",
    },
```

** while updating the other relevant fields for testnet of course.

Super cool project!

**Comment by hewigovens** [comment]
it's not possible, wallet core behavior is heavily inferred from static coin type (sip44 id), so fork and build your own lib is the recommended way.
