### ISSUE TITLE
Remove TON blockchain support

### ISSUE THREAD

**Issue by catenocrypt** [trustwallet/wallet-core#954]
It was announced, that after the delays so far, Telegram has decided to abandon TON blockchain project, due to SEC lawsuits.
Remove partial support for TON.

**Comment by hewigovens** [comment]
let's keep an eye on TON community, not to remove it right way (cold-blooded, lol)

**Comment by vikmeup** [comment]
let's close this for now, until decide to move forward, deletion is easy

**Comment by sylvestrevgenhiveon** [comment]
Hello. Will you add TON support in the near future?

**Comment by catenocrypt** [comment]
TON is not an active project anymore.  However, the recently added Everscale seems to be a continuation of it.

**Comment by sylvestrevgenhiveon** [comment]
@catenocrypt There are two continuations: Everscale and The Open Network. The Open Network is enthusiastic, very fast and be popular very fast.
