### ISSUE TITLE
In the function hdwallet::getPublicKeyFromExtended function, to create the PublicKey object, can we use the return value by calling Coin::publicKeyType(coin)?

### ISSUE THREAD

**Issue by vicishero** [trustwallet/wallet-core#964]
In the function hdwallet::getPublicKeyFromExtended function, to create the PublicKey object, can we use the return value by calling Coin::publicKeyType(coin)?

**Comment by hewigovens** [comment]
didn't get it, they're different types, `Coin::publicKeyType` returns enum type
