### ISSUE TITLE
[Binance Chain] Support cross chain / staking messages

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#966]
Explorer: 

- https://testnet-explorer.binance.org/
- https://explorer.binance.org/smart-testnet

Cross chain:
- https://github.com/binance-chain/docs-site/blob/master/docs/smart-chain/validator/cross-chain-transfer.md
- https://github.com/binance-chain/go-sdk/blob/bsc_base/types/msg/msg-bridge.go

Staking:
- https://github.com/binance-chain/go-sdk/blob/bsc_base/types/msg/msg-sidechain-stake.go

**Comment by hewigovens** [comment]
smart chain will be launched next month, binance chain messages seem stable now

**Comment by catenocrypt** [comment]
For BSC address, my current simple proposal:
- change in coins.json: Decouple coin ID and slip44 ID, by adding a `slip44` field
- add new entry for BSC: different coin ID (e.g. 100714), same slip44 + derivation path, same symbol.
- allow multiple entries with same symbol -- this is not replied on or used anywhere, but small adjustments may be needed.

**Comment by hewigovens** [comment]
@catenocrypt I'm working on a branch, will create a pr soon
