### ISSUE TITLE
Tron.TransferTRC20Contract transfer amount overflow

### ISSUE THREAD

**Issue by vcoolish** [trustwallet/wallet-core#967]
**Describe the bug**
TRC20 tokens transfer amount is incorrect. Tron.TransferTRC20Contract takes amount as long but it overflows due to 18 decimals.

**Comment by catenocrypt** [comment]
Tron coin has decimals 6, but TRC20 tokens can have up to **18**.
With int64, and 18 decimals, maximum amount is **9.22**3372036854775808.
Suggestion is to change amount in _TransferTRC20Contract_ and _TransferAssetContract_ to **256**-bit ('bytes' type, similar to Eth), but leave to int64 in _TransferContract_.

**Comment by catenocrypt** [comment]
Merged.  Only TransferTRC20Contract was modified, TransferAssetContract not.
