### ISSUE TITLE
Ethereum and ERC20 gas price is incorrect at iOS.

### ISSUE THREAD

**Issue by ddeeano** [trustwallet/wallet-core#973]
**Describe the bug**
Ethereum and ERC20 gas price is incorrect at iOS.
There is a bug with the gas price value entered when signing Ethereum using the SDK.

Example 
Input : 16GWEI 
Ethereum transaction result : 256GWEI

**Comment by catenocrypt** [comment]
What do you mean by input?  Input provided in SigningInput.gas_price?  Do you have a full example?

**Comment by ddeeano** [comment]
Sorry, This is full example. 
let input = EthereumSigningInput.with {
    $0.chainID = Data(hexString: "01")!
    $0.nonce = Data(hexString: "2d")!
    $0.gasPrice = Data(hexString: "1dcd65000")!
    $0.gasLimit = Data(hexString: "5208")!
    $0.toAddress = "0x41a48f5817a40431479870bed3e785f864c6d21e"
    $0.amount = Data(hexString: "5af3107a4000")!
    $0.privateKey = Data(hexString: privateKey)!
    //$0.payload = Data(hexString: data.drop0x)!
}

**Input Gas Price**
$0.gasPrice = Data(hexString: "1dcd65000")!
**1dcd65000 -> 8GWEI** 

When transaction transfer success, actually used gas price is 128GWEI 
I think maybe 8GWEI * 16 = 128 GWEI


this transaction hash 0xafd20b09294d8bac7d5dc79dd0bec3afd796f1a514f3e420ae93eee63b136c4d

**Comment by catenocrypt** [comment]
Maybe the hex string as parsed as "1d cd 65 00 00" as opposed to "01 dc d6 50 00".
Can you try like this:

```
$0.gasPrice = Data(hexString: "01dcd65000")!
```

**Comment by hewigovens** [comment]
hi, can you try latest wallet core 2.0.14? `Data(hexString:)` will return nil if the hex string length is odd (to avoid case like this)

**Comment by ddeeano** [comment]
Thanks, Solved this issue
