### ISSUE TITLE
[CI] Improve Android CI speed

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#975]
ndk supports ccache, the trick is when to update ccache folder, probably we can check `cache hit rate` (lower than 50%)

**Comment by catenocrypt** [comment]
An idea: parallelize builds for the different android architectures, tests are run on only one anyways.  It may be tricky, because build for all arch is done with a single gradle command.

**Comment by catenocrypt** [comment]
I'm trying to achieve that Android CI build does not build all 4 abi variants, only x86, as only that one is used for the tests.
So far unsuccessful: pr #1072 .

**Comment by catenocrypt** [comment]
With c2767d9, CI run time wnt down to 16 min, previously 28.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/13562139/90282240-485c5180-de6e-11ea-94de-d8d18e0b3236.png">

**Comment by hewigovens** [comment]
Very nice 🚀
