### ISSUE TITLE
Support Bitcoin RBF

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#976]
RBF stands for replace by fee: https://bitcoincore.org/en/faq/optin_rbf/
we need to allow user to set `nLockTime` somehow

**Comment by catenocrypt** [comment]
In opt-in RBF, opt-in is signaled by the sequence field (equal to UINT32_MAX, or lower).

In my understanding, not of the relevant issues fall in the responsibility of wallet-core:

- Whether node replaces or keeps first tx, in case a potential replacement pair occurs -- concern of miners
- Chosing UTXOs, including pending TX or not -- concern of the SW using wallet-core (app)
- Setting RBF opt-in signal -- concern of the SW using wallet-core (app)
- showing UX options to end user -- app

**Comment by vikmeup** [comment]
@catenocrypt Wallet Core just need to have an option to set RBF easily. The rest is not a concern of the Wallet Core responsibility

**Comment by hewigovens** [comment]
Thanks @yutianwu's testing, it seems we don't do anything to enable RBF, this https://blockchair.com/bitcoin/transaction/da2a9ce5d71ff7490bc9025e2888ca109b68ec0bd0e7d26195e1783305c00117 replaced https://blockchair.com/bitcoin/transaction/e3ed21e6e7707f46a23fd2fbaf3b52fd09dbc1ae27db467f4fcc12efb3d3e72e successfully (byte fee 80 vs byte fee 1)

**Comment by catenocrypt** [comment]
The seq on the replacment tx is UINT_MAX, it's not seen what was on the replaced TX, I assume the same.  My guess:
- some miners implement not opt-in, but more relaxed RBF flavor
- the original TX had seq=0, so it was opt-in-RBF -- I doubt this, as TrustWallet does not do this.
I will do some testing on my own too, this info is not conclusive for me.

**Comment by hewigovens** [comment]
the replaced tx sequence was 0, I didn't set `sequence`
```swift
let utxos = [
    BitcoinUnspentTransaction.with {
        $0.outPoint.hash = Data(Data(hexString: "8b5f4861c6d4a4ea361aa4066d720067f73854d9a1b1d01e2b0e3c9e150bc5a3")!.reversed())
        $0.outPoint.index = 0
        $0.script = lockScript.data
        $0.amount = 54700
    }
]
```
