### ISSUE TITLE
[CI] Integrate lint

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#978]
clang-tidy or cppcheck

**Comment by hewigovens** [comment]
cmake "-DCMAKE_CXX_CPPCHECK=/usr/bin/cppcheck;--std=c++17;--enable=warning"

**Comment by catenocrypt** [comment]
Current status:

Some lint scripts exists, but they are not set up correctly, tools not installed, not integrated into the pipeline.

Scripts (in tools):
- lint-all            check all using clang-tidy
- lint                check diff using clang-tidy
- lint-cppcheck-all   check all using cppcheck, but setup is not sufficient
- lint-cppcheck       check diff using cppcheck

Script invocations in the pipeline:
- in bootstrap.sh, lint is invoked, if clang-tidy is installed

Test and chose the more appropriate:  `clang-tiny` or `cppcheck`.

Setup exception list, fix major deviations, and include check in CI pipeline.

One comparison of C++ static code analyzers:
https://www.slant.co/topics/263/~best-open-source-c-static-analysis-tools

**Comment by hewigovens** [comment]
GitHub has https://securitylab.github.com/tools/codeql and action, maybe we can setup this one (security)
