### ISSUE TITLE
[Keystore] Support side chain

### ISSUE THREAD

**Issue by hewigovens** [trustwallet/wallet-core#979]
To better support binance smart chain or other side chains, we could probably extend current keystore json like

```json
{
    "sidechain": [
        {
            "name": "Smart Chain",
            "type": "Ethereum",
            "address": "0x"
        }
    ]
}
```

**Comment by catenocrypt** [comment]
See solution proposal here:
https://gist.github.com/catenocrypt/ed41907ef092e39095f40745712729f3

**Comment by catenocrypt** [comment]
See in https://github.com/trustwallet/internal/pull/286
