### ISSUE TITLE
Bitcoin signed and witness error

### ISSUE THREAD

**Issue by JavionHe** [trustwallet/wallet-core#982]
this is my kotlin code:

var wallet = HDWallet("it is mnemonic...","")
            val coinBtc: CoinType = CoinType.BITCOIN
            val addressBtc = wallet.getAddressForCoin(coinBtc)
            val secretPrivateKeyBtc = wallet.getKeyForCoin(coinBtc)
            val toAddress = "1MoXrqTD6MfecxYBA3NMTaLcB9y1Ucu2LK"
            val changeAddress = "bc1q7fhqwluhcrs2ekkme0cu5nlvav2mdx7j7jel9t"
            val script = BitcoinScript.buildForAddress(addressBtc, coinBtc)
            val scriptHash = script.matchPayToWitnessPublicKeyHash()

            val utxoTxId = "b3cbc89fdf9640bddf9eff15d53047e405b3339f7e31f6e272a8b1f8f055fed0".hexStringToByteArray()
            utxoTxId.reverse()
            val outPoint = Bitcoin.OutPoint.newBuilder().apply {
                this.hash = ByteString.copyFrom(utxoTxId)
                this.index = 0
                this.sequence = (4294967293).toInt()
            }.build()
            val utxo = Bitcoin.UnspentTransaction.newBuilder().apply {
                this.amount = 360476
                this.outPoint = outPoint
                this.script = ByteString.copyFrom(script.data())
            }.build()

            val input = Bitcoin.SigningInput.newBuilder().apply {
                this.amount = 50000
                this.hashType = BitcoinSigHashType.ALL.value().or(BitcoinSigHashType.FORK.value())
                this.toAddress = toAddress
                this.changeAddress = changeAddress
                this.byteFee = 62
                this.coinType = coinBtc.value()
                this.addPrivateKey(ByteString.copyFrom(secretPrivateKeyBtc.data()))
                this.putScripts(scriptHash.toHexString(),ByteString.copyFrom(BitcoinScript.buildPayToPublicKeyHash(scriptHash).data()))
            }
            input.addUtxo(utxo)

            val plan = AnySigner.plan(input.build(), CoinType.BITCOIN, Bitcoin.TransactionPlan.parser())
            input.plan = plan
            val output = AnySigner.sign(input.build(), CoinType.BITCOIN, Bitcoin.SigningOutput.parser())

            val signedTransaction = output.encoded?.toByteArray()
            Log.i("!!!!!", "Signed BTC transaction: ${signedTransaction?.toHexString(false)}")

result, my signed rawtx is:
01000000000101d0fe55f0f8b1a872e2f6317e9f33b305e44730d515ff9edfbd4096df9fc8cbb30000000000fdffffff0250c30000000000001976a914e42f68ef9f148bb7ae1a453e5c6bb8c0dbc99a9e88ac1086040000000000160014f26e077f97c0e0acdadbcbf1ca4feceb15b69bd202473044022047120cfc638bec974f155a6e834c81b755f4d0757122316fc46a46ef92325106022028007a0b82586dd3fdd42ec2c12efd941581da6d2c67386e223eea887c74bb254121029b4052ffe47ab582a2d21014ba1dc9fb703d8525b4825c56607e80f01f74ef0600000000

but open website:
https://btc.com/3be0a2ae0c79b1948bb829be7578f19879c4771e95db01383e7d0be5794bb4b0

can get the main network rawtx is:
01000000000101d0fe55f0f8b1a872e2f6317e9f33b305e44730d515ff9edfbd4096df9fc8cbb30000000000fdffffff0250c30000000000001976a914e42f68ef9f148bb7ae1a453e5c6bb8c0dbc99a9e88ac1086040000000000160014f26e077f97c0e0acdadbcbf1ca4feceb15b69bd2024830450221008099254c014a99948f7a16d3096140107a7f9cafdcd1917c564bbe4147f15bcf0220247c905ea2b62382269b1f6d928043e2b24e3e020aec3971e073a32913f17e1d0121029b4052ffe47ab582a2d21014ba1dc9fb703d8525b4825c56607e80f01f74ef0600000000

and input rawtx to 
https://live.blockcypher.com/btc/decodetx/

can found only the witness is different:
error rawtx:
![image](https://user-images.githubusercontent.com/40451929/84163384-05fc4a00-aaa4-11ea-8b04-cc76f6d17ccf.png)

main network rawtx:
![image](https://user-images.githubusercontent.com/40451929/84163456-19a7b080-aaa4-11ea-99a8-4450c01ae783.png)

I want to sign the same rawtx on the main network , please help me how to resolve it !!!

**Comment by catenocrypt** [comment]
My first guess is that the witness script used is different than `matchPayToWitnessPublicKeyHash`.  I will check into it later.

**Comment by hewigovens** [comment]
Remove BitcoinSigHashType.FORK.value() and try again?

**Comment by JavionHe** [comment]
@hewigovens you are right ,thank you very much.
