### ISSUE TITLE
Support customizing fee calculation in UnspentSelector

### ISSUE THREAD

**Issue by hewigovens** [TrustWallet/wallet-core#99]
We had `BitcoinFeeCalculator` in trust-core, and `BitcoinUnspentSelector` took a closure to participate in the selection process (https://github.com/TrustWallet/private-trust-core/commit/ce519262e4e21a7c549ac1452e7833acdeaa3876). That's because Zcash suggests using fixed fee regardless input / output size.

What's the best way to achieve this? using C++ lambda or just create a new one for fixed fee blockchains?

**Comment by alejandro-isaza** [comment]
Yes, we can use a `std::function`
